/*
 * CommonSQL.java
 * 
 */


package com.wipro.igrs.loanadvance.sql;

/**
 * @author jagadish
 * 
 */
public class CommonSQL {

	// ---------------Advance Master--------------------
	public static final String	SELECT_ADVANCE_TYPE_ID_SEQ						= "SELECT IGRS_EMP_ADV_TYPE_SEQ.NEXTVAL FROM DUAL";

	public static final String	INSERT_ADVANCE_MASTER_DETAILS					= "INSERT INTO IGRS_EMP_ADVANCE_TYPE_MASTER "
																						+ "(ADVANCE_TYPE_ID,ADVANCE_NAME,ADVANCE_DESC,ADVANCE_STATUS,"
																						+ "ADVANCE_AMOUNT,NO_INSTALLMENT,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE,RATE_OF_INTEREST,APPLICABLE_CLASS,SALARY_LIMITATION,ADVANCE_CONDITION)"
																						+ "VALUES(?,?,?,?,?,?,?,SYSDATE,?,SYSDATE,?,?,?,?)";

	/*public static final String	RETRIEVE_ADVANCE_MASTER_DETAILS					= "SELECT ADVANCE_TYPE_ID,ADVANCE_NAME,ADVANCE_AMOUNT,NO_INSTALLMENT FROM IGRS_EMP_ADVANCE_TYPE_MASTER "
																						+ "WHERE ADVANCE_STATUS = 'A' ORDER BY ADVANCE_AMOUNT";*/
	public static final String	RETRIEVE_ADVANCE_MASTER_DETAILS =" SELECT ADVANCE_TYPE_ID,ADVANCE_NAME,ADVANCE_AMOUNT,NO_INSTALLMENT , rate_of_interest "
																+" FROM IGRS_EMP_ADVANCE_TYPE_MASTER "				
																+" WHERE ADVANCE_STATUS = 'A' ORDER BY ADVANCE_AMOUNT ";

	public static final String	RETRIEVE_ADVANCE_MASTER_COMPONENT				= "SELECT ADVANCE_TYPE_ID,ADVANCE_NAME,ADVANCE_AMOUNT,NO_INSTALLMENT,ADVANCE_DESC FROM IGRS_EMP_ADVANCE_TYPE_MASTER "
																						+ "WHERE ADVANCE_STATUS = 'A' AND ADVANCE_TYPE_ID =?";

	// ----------Apply For Advance------------
	public static final String	SELECT_ADVANCE_TXN_ID_SEQ						= "SELECT IGRS_EMP_ADV_TXN_DTL_SEQ.NEXTVAL FROM DUAL";

	public static final String	INSERT_ADVANCE_TXN_MASTER_DETAILS				= "INSERT INTO IGRS_EMP_ADVANCE_TXN_DETAILS "
																						+ "(ADVANCE_TXN_ID,EMP_ID,ADVANCE_TYPE_ID,ADVANCE_STATUS,REMARKS,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE,ADVANCE_AMOUNT) "
																						+ "VALUES(?,?,?,?,?,?,SYSDATE,?,SYSDATE,?)";

	public static final String	RETRIEVE_ADVANCE_TYPE_LIST						= "SELECT ADVANCE_TYPE_ID,ADVANCE_NAME,ADVANCE_AMOUNT FROM IGRS_EMP_ADVANCE_TYPE_MASTER "
																						+ "WHERE ADVANCE_STATUS = 'A' ORDER BY ADVANCE_TYPE_ID";

	public static final String	AVAILABLE_PENDING_ADVANCELIST					= "SELECT ADVANCE_TXN_ID,ADVANCE_AMOUNT	,ADVANCE_STATUS  FROM IGRS_EMP_ADVANCE_TXN_DETAILS WHERE EMP_ID= ? AND ADVANCE_STATUS ='P'";

	public static final String	AVAILABLE_ADVANCE_DETAILS_LIST_FOR_APPROVE		= "SELECT EMP_ID,ADVANCE_TYPE_ID,ADVANCE_AMOUNT	,REMARKS,ADVANCE_TXN_ID FROM IGRS_EMP_ADVANCE_TXN_DETAILS WHERE ADVANCE_TXN_ID = ?";

	public static final String	UPDATE_AVAILABLE_DETAILS_TRANSACTION_MASTER		= "UPDATE IGRS_EMP_ADVANCE_TXN_DETAILS"
																						+ " SET ADVANCE_STATUS = ?"
																						+ " ,COMMENTS      = ?"
																						+ " ,UPDATED_BY    = ?"
																						+ " ,UPDATED_DATE  = SYSDATE"
																						+ " WHERE  ADVANCE_TXN_ID = ?"
																						+ " AND EMP_ID =  ? ";

	public static final String	AVAILABLE_ADVANCE_COMPONENTS_FOR_VIEW			= "SELECT ADVANCE_NAME,ADVANCE_AMOUNT,NO_INSTALLMENT,ADVANCE_DESC,ADVANCE_TYPE_ID, RATE_OF_INTEREST,APPLICABLE_CLASS,SALARY_LIMITATION,ADVANCE_CONDITION  FROM  IGRS_EMP_ADVANCE_TYPE_MASTER WHERE ADVANCE_TYPE_ID = ?";

	public static final String	AVAILABLE_ADVANCE_TYPE_PER_TXN_ID				= "SELECT ADVANCE_NAME FROM IGRS_EMP_ADVANCE_TYPE_MASTER"
																						+ " WHERE ADVANCE_TYPE_ID IN(SELECT ADVANCE_TYPE_ID FROM IGRS_EMP_ADVANCE_TXN_DETAILS WHERE ADVANCE_TXN_ID= ? )";

	public static final String	SELECT_AVAILABLE_COMPONENTS_WITH_STATUS			= "SELECT  EMP_ID,ADVANCE_TYPE_ID,ADVANCE_STATUS,REMARKS,ADVANCE_AMOUNT	,CREATED_DATE,COMMENTS FROM"
																						+ " IGRS_EMP_ADVANCE_TXN_DETAILS WHERE ADVANCE_TXN_ID=?";

	public static final String	CHECK_ADVANCE_NAME								= "SELECT * FROM IGRS_EMP_ADVANCE_TYPE_MASTER WHERE ADVANCE_NAME = ? AND ADVANCE_STATUS = 'A'";

	public static final String	UPDATE_ADVANCE_MASTER_TYPE						= "UPDATE IGRS_EMP_ADVANCE_TYPE_MASTER SET ADVANCE_AMOUNT = ?,NO_INSTALLMENT= ?,ADVANCE_DESC= ?,RATE_OF_INTEREST=? , APPLICABLE_CLASS=? , SALARY_LIMITATION=?, ADVANCE_CONDITION=? WHERE ADVANCE_TYPE_ID= ?";

	public static final String	FETCH_ADVANCE_AMOUNT_BY_ID						= "SELECT ADVANCE_AMOUNT FROM IGRS_EMP_ADVANCE_TYPE_MASTER WHERE ADVANCE_TYPE_ID =? AND ADVANCE_STATUS = 'A'";

	public static final String	CHECK_AVAILABLE_EMPID							= "SELECT EMP_ID FROM IGRS_EMP_ADVANCE_TXN_DETAILS WHERE EMP_ID= ?";

	public static final String	CHECK_AVAILABLE_REFID							= "SELECT ADVANCE_TXN_ID FROM IGRS_EMP_ADVANCE_TXN_DETAILS WHERE ADVANCE_TXN_ID= ?";

	// *************Loan Sql
	// Queries********************************************
	public static final String	RETRIEVE_LOAN_MASTER_DETAILS					= "SELECT LOAN_TYPE_ID,LOAN_NAME,MIN_LOAN_AMOUNT,MAX_LOAN_AMOUNT,RATE_OF_INTEREST FROM IGRS_EMP_LOAN_TYPE_MASTER WHERE LOAN_STATUS ='A' ORDER BY LOAN_TYPE_ID";

	public static final String	SELECT_LOAN_TYPE_ID_SEQ							= "SELECT IGRS_EMP_LOAN_TYP_SEQ.NEXTVAL FROM DUAL";

	public static final String	INSERT_LOAN_TYPE_MASTER_DETAILS					= "INSERT INTO IGRS_EMP_LOAN_TYPE_MASTER (LOAN_TYPE_ID,LOAN_NAME,LOAN_DESC,LOAN_STATUS,"
																						+ " MAX_LOAN_AMOUNT,MIN_LOAN_AMOUNT"
																						+ " ,MIN_NO_INSTALLMENT,MAX_NO_INSTALLMENT,RATE_OF_INTEREST,TYPE_OF_INTEREST,CREATED_BY,"
																						+ " CREATED_DATE,UPDATED_BY,UPDATED_DATE) VALUES (?,?,?,?,?,?,?,?,?,?,?,SYSDATE,?,SYSDATE) ";

	public static final String	AVAILABLE_LOAN_COMPONENTLIST					= "SELECT LOAN_NAME,MIN_LOAN_AMOUNT,MAX_LOAN_AMOUNT,MIN_NO_INSTALLMENT,"
																						+ " MAX_NO_INSTALLMENT,TYPE_OF_INTEREST,RATE_OF_INTEREST,LOAN_DESC,LOAN_TYPE_ID FROM IGRS_EMP_LOAN_TYPE_MASTER"
																						+ " WHERE LOAN_TYPE_ID = ?";

	public static final String	UPDATE_LOAN_MASTER_TYPE							= "UPDATE IGRS_EMP_LOAN_TYPE_MASTER SET MIN_LOAN_AMOUNT= ?,MAX_LOAN_AMOUNT= ?,MIN_NO_INSTALLMENT= ?,"
																						+ "MAX_NO_INSTALLMENT= ?,RATE_OF_INTEREST= ?,LOAN_DESC= ?,UPDATED_BY =?"
																						+ ",UPDATED_DATE= SYSDATE WHERE LOAN_TYPE_ID= ?";

	public static final String	GET_LOAN_TYPES									= "SELECT LOAN_TYPE_ID,LOAN_NAME FROM IGRS_EMP_LOAN_TYPE_MASTER";

	public static final String	GET_LOAN_AMOUNT_FROM_MASTER						= "SELECT MAX_LOAN_AMOUNT,MAX_NO_INSTALLMENT FROM IGRS_EMP_LOAN_TYPE_MASTER WHERE LOAN_TYPE_ID=?";

	public static final String	SELECT_LOAN_TXN_MASTER_DETAILS_ID				= "SELECT IGRS_LOAN_TXN_ID_SEQ.NEXTVAL FROM DUAL";

	public static final String	INSERT_LOAN_TRANSACTION_MASTER_DETAILS			= "INSERT INTO IGRS_EMP_LOAN_TXN_DETAILS (LOAN_TXN_ID,EMP_ID,LOAN_TYPE_ID,NO_INSTALLMENTS,LOAN_AMOUNT,"
																						+ " LOAN_STATUS,REMARKS,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE) VALUES(?,?,?,?,?,?,?,?,SYSDATE,?,SYSDATE)";

	public static final String	GET_LOAN_TRANSACTION_DETAILS					= "SELECT LOAN_TXN_ID,LOAN_AMOUNT,LOAN_STATUS,LOAN_TYPE_ID FROM IGRS_EMP_LOAN_TXN_DETAILS WHERE EMP_ID= ? AND LOAN_STATUS='P' ORDER BY CREATED_DATE";

	public static final String	GET_LOAN_DETAILS_FROM_LOAN_TXN_DETAILS_MASTER	= "SELECT LOAN_TXN_ID,EMP_ID,LOAN_TYPE_ID,NO_INSTALLMENTS,LOAN_AMOUNT,REMARKS FROM IGRS_EMP_LOAN_TXN_DETAILS WHERE LOAN_TXN_ID= ?";

	public static final String	GET_LOAN_TYPE_FROM_LOAN_TYPE_MASTER				= "SELECT LOAN_TYPE_ID,LOAN_NAME FROM IGRS_EMP_LOAN_TYPE_MASTER WHERE LOAN_TYPE_ID IN(SELECT LOAN_TYPE_ID FROM IGRS_EMP_LOAN_TXN_DETAILS WHERE LOAN_TXN_ID= ?)";

	public static final String	UPDATE_LOAN_DETAILS_TRANSACTION_MASTER			= "UPDATE IGRS_EMP_LOAN_TXN_DETAILS"
																						+ " SET LOAN_STATUS = ?"
																						+ " ,APPROVER_REMARKS = ?"
																						+ " ,APPROVER_ID = ?"
																						+ " ,UPDATED_BY  = ?"
																						+ " ,UPDATED_DATE  = SYSDATE"
																						+ " WHERE  LOAN_TXN_ID = ?"
																						+ " AND EMP_ID =  ? ";

	public static final String	GET_LOAN_STATUS_DETAILS							= "SELECT LOAN_AMOUNT,NO_INSTALLMENTS,CREATED_DATE,REMARKS,APPROVER_REMARKS,LOAN_STATUS,APPROVER_ID FROM IGRS_EMP_LOAN_TXN_DETAILS WHERE LOAN_TXN_ID= ?";

	public static final String	GET_LOAN_TYPE									= "SELECT LOAN_NAME FROM IGRS_EMP_LOAN_TYPE_MASTER WHERE LOAN_TYPE_ID IN(SELECT LOAN_TYPE_ID FROM IGRS_EMP_LOAN_TXN_DETAILS WHERE LOAN_TXN_ID= ?)";

	public static final String	CHECK_LOAN_NAME									= "SELECT * FROM IGRS_EMP_LOAN_TYPE_MASTER WHERE LOAN_NAME = ? AND LOAN_STATUS = 'A' ";

	public static final String	CHECK_LOAN_AMOUNT								= "SELECT MAX_LOAN_AMOUNT FROM IGRS_EMP_LOAN_TYPE_MASTER WHERE LOAN_TYPE_ID = ? AND LOAN_STATUS = 'A'";

	public static final String	CHECK_INSTALLMENT_NO							= "SELECT MAX_NO_INSTALLMENT FROM IGRS_EMP_LOAN_TYPE_MASTER WHERE LOAN_TYPE_ID = ? AND LOAN_STATUS = 'A'";

	public static final String	CHECK_LOANAPPLIED_EMPID							= "SELECT EMP_ID FROM IGRS_EMP_LOAN_TXN_DETAILS WHERE EMP_ID=?";

	public static final String	CHECK_LOAN_TXN_ID								= "SELECT LOAN_TXN_ID FROM IGRS_EMP_LOAN_TXN_DETAILS WHERE LOAN_TXN_ID=?";

}
