package com.wipro.igrs.newreginit.constant;

public class RegInitConstant {
	public static final String VALUATION_PLOT_PAGE = "valuationPlot";
	public static final String DISPLAY_VALUATION_PAGE = "valuationDisplay";
	public static final String DISPLAY_PROPERTY_PAGE = "displayProperty";
	public static final String VALUATION_AGRI_PAGE = "valuationAgri";
	public static final String REGCOMP_SEARCH_FORM = "regInitSearch";
	public static final String DUTY_SEARCH_FORM = "dutySearch";
	public static final String VALUATION_BUILDING_PAGE = "valuationBuilding";
	public static final String PARTY_PAGE_FORM = "regInitForm";
	public static final String CONSENTER_PAGE_FORM = "consenterForm";
	public static final String OWNER_PAGE_FORM = "ownerForm";
	public static final String TRANS_PARTY_PAGE_FORM = "regTransPartyForm";
	public static final String MAPPING_FORM = "regInitMappingForm";
	public static final String REG_INIT_CONFIRM_PAGE = "regInitConfirm";
	public static final String REG_INIT_MAPPING_PAGE = "regInitMapping";
	public static final String NON_PROP_PARTICULAR_MAPPING_PAGE = "particularNonPropMapping";
	public static final String ADD_ACTION = "ADD_ACTION";
	public static final String VIEW_ACTION = "VIEW_ACTION";
	public static final String MODIFY_ACTION = "MODIFY_ACTION";
	public static final String DELETE_ACTION = "DELETE_ACTION";
	public static final String SEARCH_ACTION = "SEARCH_ACTION";
	public static final String CHANGE_PARTY_ACTION = "CHANGE_PARTY_ACTION";
	public static final String DISPLAY_ACTION = "displayAction";
	public static final String NEXT_ACTION = "NEXT_ACTION";
	public static final String PAYMENT_ACTION = "PAYMENT_ACTION";
	public static final String CANCEL_ACTION = "CANCEL_ACTION";
	public static final String STORE_ACTION = "STORE_ACTION";
	public static final String PREVIOUS_ACTION = "PREVIOUS_ACTION";
	public static final String PLOT_SUBMIT_ACTION = "propertycalc";
	public static final String AGRI_USAGE_ACTION = "usageAgri";
	public static final String PROPERTY_TYPE_ACTION = "propertyAction";
	public static final String PLOT_USAGE_ACTION = "usagePlotAction";
	public static final String RESET_ACTION = "RESET_ACTION";
	public static final String USAGE_BUILDING_ACTION = "usageBuildingAction";
	public static final String BUILDING_SUBMIT_ACTION = "buildingSubmitAction";
	public static final String FLOOR_ACTION = "floorAction";
	public static final String ADD_MORE_ACTION = "addMoreAction";
	public static final String DELETE_MORE_ACTION = "deleteMoreAction";
	public static final String REGCOMP_DISTRICT_ACTION = "REGCOMP_DISTRICT_ACTION";
	public static final String REGCOMP_WARDPATWARI_ACTION = "REGCOMP_WARDPATWARI_ACTION";
	public static final String REGCOMP_MOHALLA_ACTION = "REGCOMP_MOHALLA_ACTION";
	public static final String REGCOMP_ACTION_PROPERTY_SEARCH = "propertySearchAction";
	public static final String THIRD_FLOOR = "TFA";
	public static final String FOURTH_FLOOR = "FFF";
	//ADDED BY ROOPAM
	public static final String SUBMIT_ACTION = "SUBMIT_ACTION";
	public static final String ADD_FLOOR_ACTION = "ADD_FLOOR_ACTION";
	public static final String DELETE_FLOOR_ACTION = "DELETE_FLOOR_ACTION";
	//Start Session Name
	public static final String PROPERTY_DTO_SESSION = "PROPERTY_DTO_SESSION";
	public static final String PROPERTY_TYPE_SESSION = "PROPERTY_TYPE_SESSION";
	public static final String ERROR_FLAG = "ERROR_FLAG";
	public static final String ERROR_LIST = "ERROR_LIST";
	public static final String HASH_SESSION = "HASH_SESSION";
	public static final String HASHMAP_DTO_SESSION = "HASHMAP_DTO_SESSION";
	public static final String REGCOM_PROPERTY_SEARCH = "regCompletionPropertySearch";
	public static final String MPCST_ACTION = "MPCST_ACTION";
	//End Session Name
	public final static String PLOT_ID = "PLOT_ID";
	public final static String BUILDING_ID = "BUILDING_ID";
	public final static String AGRICULTURELAND_ID = "AGRICULTURELAND_ID";
	public static final String DISPLAY_PROPERTY_LIST_PAGE = "valuationList";
	public static final String VALUATION_VIEW_POPUP_PAGE = "valuationPopup";
	public static final String PROPERTY_TYPE_BUILDING = "PROPERTY_TYPE_BUILDING";
	public static final String PROPERTY_TYPE_PLOT = "PROPERTY_TYPE_PLOT";
	public static final String PROPERTY_TYPE_AGRI_LAND = "PROPERTY_TYPE_AGRI_LAND";
	//following added by Roopam
	public static final String CHANGE_TRANSACTING_PARTY_ACTION = "CHANGE_TRANSACTING_PARTY_ACTION";
	public static final String NEXT_TO_PROPERTY_ACTION = "NEXT_TO_PROPERTY_ACTION";
	public static final String CANCEL_TRANSACTING_PART_ACTION = "CANCEL_TRANSACTING_PART_ACTION";
	public static final String OK_ACTION = "OK_ACTION";
	public static final String NO_ACTION = "NO_ACTION";
	public static final String OTHER_ACTION = "OTHER_ACTION";
	public static final String TRNS_ROLE_TYPE_ACTION = "TRNS_ROLE_TYPE_ACTION";
	public static final String NEXT_TO_MAPPING_ACTION = "NEXT_TO_MAPPING_ACTION";
	public static final String NEXT_TO_CONFIRM_ACTION = "NEXT_TO_CONFIRM_ACTION";
	public static final String CONFIRMATION_OK_ACTION = "CONFIRMATION_OK_ACTION";
	public static final String TRANS_PARTY_VIEW_ACTION = "TRANS_PARTY_VIEW_ACTION";
	public static final String FINAL_ACTION = "FINAL_ACTION";
	public static final String NEXT_TO_PAYMENT_ACTION = "NEXT_TO_PAYMENT_ACTION";
	public static final String FINAL_ACTION_FEE = "FINAL_ACTION_FEE";
	public static final String NEXT_TO_FEE_PAYMENT_ACTION = "NEXT_TO_FEE_PAYMENT_ACTION";
	public static final String NEXT_TO_ADJU_PAYMENT_ACTION = "NEXT_TO_ADJU_PAYMENT_ACTION";
	//added by Shreeraj
	public static final String SUBMIT_ADJU_ACTION = "SUBMIT_ADJU_ACTION";
	public static final String ADJU_COMPLETED = "ADJU_COMPLETED";
	public static final String SUBMIT_ADJU_NON_PROP_ACTION = "SUBMIT_ADJU_NON_PROP_ACTION";
	//end
	public static final String NEXT_TO_PROPERTY_ACTION_THROUGH_MAP = "NEXT_TO_PROPERTY_ACTION_THROUGH_MAP";
	public static final String RESET_APPLICANT_ACTION = "RESET_APPLICANT_ACTION";
	public static final String RESET_TRANSACTING_ACTION = "RESET_TRANSACTING_ACTION";
	public static final String RESET_MAPPING_ACTION = "RESET_MAPPING_ACTION";
	public static final String RESET_PROPERTY_ACTION = "RESET_PROPERTY_ACTION";
	public static final String ADD_MORE_PROP_ACTION = "ADD_MORE_PROP_ACTION";
	public static final String APPLICANT_USERID_CHECK_ACTION = "APPLICANT_USERID_CHECK_ACTION";
	public static final String APPLICANT_VIEW = "APPLICANT_VIEW";
	public static final String TRANSACTING_PARTY_VIEW = "TRANSACTING_PARTY_VIEW";
	public static final String MAPPING_VIEW = "MAPPING_VIEW";
	public static final String PROPERTY_VIEW = "PROPERTY_VIEW";
	public static final String CALCULATE_DUTIES_ACTION = "CALCULATE_DUTIES_ACTION";
	public static final String COMPLETE_APPLICATION_ACTION = "COMPLETE_APPLICATION_ACTION";
	public static final String ADJUDICATION_ACTION = "ADJUDICATION_ACTION";
	public static final String CHANGE_PROPERTY_ACTION = "CHANGE_PROPERTY_ACTION";
	public static final String ADD_NEXT_PROP_DETLS_ACTION = "ADD_NEXT_PROP_DETLS_ACTION";
	public static final String UPLOAD_FILE = "UPLOAD_FILE";
	public static final String UPLOAD_FILE_TRNS = "UPLOAD_FILE_TRNS";
	public static final String DECLARE_SHARE_CHECK_ACTION = "DECLARE_SHARE_CHECK_ACTION";
	public static final String PRINT_ACTION = "PRINT_ACTION";
	public static final String PRINT_ACTION_FINAL = "PRINT_ACTION_FINAL";
	public static final String UPLOAD_FILE_ANGLE_1 = "UPLOAD_FILE_ANGLE_1";
	public static final String UPLOAD_FILE_ANGLE_2 = "UPLOAD_FILE_ANGLE_2";
	public static final String UPLOAD_FILE_ANGLE_3 = "UPLOAD_FILE_ANGLE_3";
	public static final String UPLOAD_PROPERTY_MAP = "UPLOAD_PROPERTY_MAP";
	public static final String UPLOAD_PROPERTY_RIN = "UPLOAD_PROPERTY_RIN";
	public static final String UPLOAD_PROPERTY_KHASRA = "UPLOAD_PROPERTY_KHASRA";
	public static final String UPLOAD_PROPERTY_KHASRA_CLR = "UPLOAD_PROPERTY_KHASRA_CLR";
	public static final String UPLOAD_PHOTO_PROOF = "UPLOAD_PHOTO_PROOF";
	public static final String UPLOAD_PHOTO_PROOF_TRNS = "UPLOAD_PHOTO_PROOF_TRNS";
	public static final String UPLOAD_NOTARIZED_AFFIDAVIT_EXECUTANT = "UPLOAD_NOTARIZED_AFFIDAVIT_EXECUTANT";
	public static final String UPLOAD_EXECUTANT_PHOTO = "UPLOAD_EXECUTANT_PHOTO";
	public static final String UPLOAD_EXECUTANT_PHOTO_2 = "UPLOAD_EXECUTANT_PHOTO_2";
	public static final String UPLOAD_NOTARIZED_AFFIDAVIT_ATTORNEY = "UPLOAD_NOTARIZED_AFFIDAVIT_ATTORNEY";
	public static final String UPLOAD_ATTORNEY_PHOTO = "UPLOAD_ATTORNEY_PHOTO";
	public static final String UPLOAD_CLAIMANT_PHOTO = "UPLOAD_CLAIMANT_PHOTO";
	public static final String UPLOAD_ATTORNEY_PHOTO_2 = "UPLOAD_ATTORNEY_PHOTO_2";
	public static final String UPLOAD_PAN_EXECUTANT = "UPLOAD_PAN_EXECUTANT";
	public static final String UPLOAD_PAN_CLAIMANT = "UPLOAD_PAN_CLAIMANT";
	public static final String UPLOAD_NOTARIZED_AFFIDAVIT_EXECUTANT_TRNS = "UPLOAD_NOTARIZED_AFFIDAVIT_EXECUTANT_TRNS";
	public static final String UPLOAD_EXECUTANT_PHOTO_TRNS = "UPLOAD_EXECUTANT_PHOTO_TRNS";
	public static final String UPLOAD_EXECUTANT_PHOTO_2_TRNS = "UPLOAD_EXECUTANT_PHOTO_2_TRNS";
	public static final String UPLOAD_NOTARIZED_AFFIDAVIT_ATTORNEY_TRNS = "UPLOAD_NOTARIZED_AFFIDAVIT_ATTORNEY_TRNS";
	public static final String UPLOAD_ATTORNEY_PHOTO_TRNS = "UPLOAD_ATTORNEY_PHOTO_TRNS";
	public static final String UPLOAD_CLAIMANT_PHOTO_TRNS = "UPLOAD_CLAIMANT_PHOTO_TRNS";
	public static final String UPLOAD_ATTORNEY_PHOTO_2_TRNS = "UPLOAD_ATTORNEY_PHOTO_2_TRNS";
	public static final String UPLOAD_PAN_EXECUTANT_TRNS = "UPLOAD_PAN_EXECUTANT_TRNS";
	public static final String UPLOAD_PAN_CLAIMANT_TRNS = "UPLOAD_PAN_CLAIMANT_TRNS";
	//Added by Neeti --- Property Locking
	public static final String UPLOAD_SIGNED_APPLICATION = "UPLOAD_SIGNED_APPLICATION";
	public static final String MODIFY_PARTY_ACTION = "MODIFY_PARTY_ACTION";
	public static final String MODIFY_PROPERTY_ACTION = "MODIFY_PROPERTY_ACTION";
	public static final String MODIFY_PROPERTY_ACTION_CLR = "MODIFY_PROPERTY_ACTION_CLR";
	public static final String MODIFY_BANK_ACTION = "MODIFY_BANK_ACTION";
	public static final String SAVE_PARTY_ACTION = "SAVE_PARTY_ACTION";
	public static final String SUBMIT_FORM_ACTION = "SUBMIT_FORM_ACTION";
	public static final String MODIFY_FILE_ANGLE_1 = "MODIFY_FILE_ANGLE_1";
	public static final String MODIFY_FILE_ANGLE_2 = "MODIFY_FILE_ANGLE_2";
	public static final String MODIFY_FILE_ANGLE_3 = "MODIFY_FILE_ANGLE_3";
	public static final String MODIFY_PROPERTY_MAP = "MODIFY_PROPERTY_MAP";
	public static final String MODIFY_PROPERTY_RIN = "MODIFY_PROPERTY_RIN";
	public static final String MODIFY_PROPERTY_KHASRA = "MODIFY_PROPERTY_KHASRA";
	public static final String SAVE_PROP_ACTION = "SAVE_PROP_ACTION";
	public static final String POSTAL_CHECK_ACTION = "POSTAL_CHECK_ACTION";
	public static final String COPY_APPLICANT_ADDRESS_ACTION = "COPY_APPLICANT_ADDRESS_ACTION";
	public static final String UNIT_ACTION = "UNIT_ACTION";
	public static final String MODIFY_EXTRA_DETLS_ACTION = "MODIFY_EXTRA_DETLS_ACTION";
	public static final String SAVE_EXTRA_DETLS_ACTION = "SAVE_EXTRA_DETLS_ACTION";
	public static final String CHANGE_CATEGORY_ACTION = "CHANGE_CATEGORY_ACTION";
	public static final String EXTRA_DETLS_NO_ACTION = "EXTRA_DETLS_NO_ACTION";
	public static final String DEL_MORE_PARTICULAR_ACTION = "DEL_MORE_PARTICULAR_ACTION";
	public static final String ADD_MORE_PARTICULAR_ACTION = "ADD_MORE_PARTICULAR_ACTION";
	public static final String SAVE_PARTICULARS_ACTION = "SAVE_PARTICULARS_ACTION";
	public static final String RESET_PARTICULARS_ACTION = "RESET_PARTICULARS_ACTION";
	public static final String CANCEL_PARTICULARS_ACTION = "CANCEL_PARTICULARS_ACTION";
	public static final String MODIFY_PARTICULAR_DETLS_ACTION = "MODIFY_PARTICULAR_DETLS_ACTION";
	public static final String SAVE_PARTICULAR_DETLS_ACTION = "SAVE_PARTICULAR_DETLS_ACTION";
	public static final String ADD_KHASRA_ACTION = "ADD_KHASRA_ACTION";
	public static final String DEL_KHASRA_ACTION = "DEL_KHASRA_ACTION";
	public static final String GENDER_ACTION = "GENDER_ACTION";
	public static final String GENDER_TRNS_ACTION = "GENDER_TRNS_ACTION";
	public static final String GENDER_MODIFY_ACTION = "GENDER_MODIFY_ACTION";
	public static final String CHANGE_CLAIMANT_ACTION = "CHANGE_CLAIMANT_ACTION";
	public static final String CHANGE_CLAIMANT_TRNS_ACTION = "CHANGE_CLAIMANT_TRNS_ACTION";
	public static final String GENERATE_ECODE_ZERO_AMNT_ACTION = "GENERATE_ECODE_ZERO_AMNT_ACTION";
	public static final String AUTH_PER_GENDER_ACTION = "AUTH_PER_GENDER_ACTION";
	public static final String AUTH_PER_GENDER_TRNS_ACTION = "AUTH_PER_GENDER_TRNS_ACTION";
	public static final String AUTH_PER_GENDER_MODIFY_ACTION = "AUTH_PER_GENDER_MODIFY_ACTION";
	public static final String POSTAL_COUNTRY_CHANGE = "POSTAL_COUNTRY_CHANGE";
	public static final String POSTAL_STATE_CHANGE = "POSTAL_STATE_CHANGE";
	public static final String VALIDATE_SHARES_ACTION = "VALIDATE_SHARES_ACTION";
	public static final String RESET_SHARES_ACTION = "RESET_SHARES_ACTION";
	public static final String BACK_TO_REG_DISPLAY_ACTION = "BACK_TO_REG_DISPLAY_ACTION";
	public static final String BACK_TO_EXTRA_DISPLAY_ACTION = "BACK_TO_EXTRA_DISPLAY_ACTION";
	public static final String BACK_TO_PARTICULAR_DISP_ACTION = "BACK_TO_PARTICULAR_DISP_ACTION";
	public static final String VALIDATE_PARTICULAR_MAP_ACTION = "VALIDATE_PARTICULAR_MAP_ACTION";
	public static final String RESET_PARTICULAR_MAPPING_ACTION = "RESET_PARTICULAR_MAPPING_ACTION";
	public static final String PRINT_PAYMENT_ACTION = "PRINT_PAYMENT_ACTION";
	public static final String ADD_KHASRA_EDIT_ACTION = "ADD_KHASRA_EDIT_ACTION";
	public static final String DEL_KHASRA_EDIT_ACTION = "DEL_KHASRA_EDIT_ACTION";
	public static final String MULTI_UPLOAD_APP_ACTION = "MULTI_UPLOAD_APP_ACTION";
	public static final String PARTY_POPUP_CLOSE_MAPPING_ACTION = "PARTY_POPUP_CLOSE_MAPPING_ACTION";
	public static final String PARTY_POPUP_CLOSE_CONFIRM_ACTION = "PARTY_POPUP_CLOSE_CONFIRM_ACTION";
	public static final String REFRESH_ACTION = "REFRESH_ACTION";
	public static final String ADD_CONSENTER_ACTION = "ADD_CONSENTER_ACTION";
	public static final String DEL_CONSENTER_ACTION = "DEL_CONSENTER_ACTION";
	public static final String GET_CONSENTER_DISTRICT = "GET_CONSENTER_DISTRICT";
	public static final String RESET_CONSENTER_ACTION = "RESET_CONSENTER_ACTION";
	public static final String SAVE_LAST_CONSENTER = "SAVE_LAST_CONSENTER";
	public static final String CANCEL_CONSENTER_ACTION = "CANCEL_CONSENTER_ACTION";
	public static final String SAVE_CONSENTER_ACTION = "SAVE_CONSENTER_ACTION";
	public static final String BACK_TO_CONSENTER_DISPLAY_ACTION = "BACK_TO_CONSENTER_DISPLAY_ACTION";
	public static final String MODIFY_CONSENTER_ACTION = "MODIFY_CONSENTER_ACTION";
	public static final String GET_CONSENTER_DISTRICT_MODIFY = "GET_CONSENTER_DISTRICT_MODIFY";
	public static final String NO_ACTION_CONSENTER = "NO_ACTION_CONSENTER"; //added by ankit for aadhar integration
	public static final String ZIP_MPCST_ACTION = "ZIP_MPCST_ACTION";
	public static final String ADD_MORE_APP_OWNER_ACTION = "ADD_MORE_APP_OWNER_ACTION";
	public static final String DELETE_MORE_APP_OWNER_ACTION = "DELETE_MORE_APP_OWNER_ACTION";
	public static final String ADD_MORE_TRNS_OWNER_ACTION = "ADD_MORE_TRNS_OWNER_ACTION";
	public static final String DELETE_MORE_TRNS_OWNER_ACTION = "DELETE_MORE_TRNS_OWNER_ACTION";
	public static final String MODIFY_OWNER_ACTION = "MODIFY_OWNER_ACTION";
	public static final String OWNER_POPUP_CLOSE_ACTION = "OWNER_POPUP_CLOSE_ACTION";
	public static final String BACK_TO_OWNER_DISPLAY_ACTION = "BACK_TO_OWNER_DISPLAY_ACTION";
	public static final String SAVE_OWNER_ACTION = "SAVE_OWNER_ACTION";
	public static final String OWNER_POPUP_MODIFY_CLOSE_ACTION = "OWNER_POPUP_MODIFY_CLOSE_ACTION";
	public static final String OWNER_NO_ACTION = "OWNER_NO_ACTION"; // Aadhar Integration
	public static final String AADHAR_CHECK = "AADHAR_CHECK"; // Aadhar Integration
	public static final String Aadhar_Validation_Consenter = "Aadhar Validation Consenter";// Aadhar Integration
	public static final String NO_ACTION_CONSENTER_DISPLAY = "NO_ACTION_CONSENTER_DISPLAY"; // Aadhar Integration
	//PARTY TYPES
	public static final String PARTY_BUYER = "BUYER";
	public static final String PARTY_SELLER_SELF = "SELLER-SELF";
	public static final String PARTY_SELLER_POA = "SELLER-PoA HOLDER";
	public static final String PARTY_OWNER = "OWNER";
	public static final String PARTY_DONOR = "DONOR";
	public static final String PARTY_DONEE = "DONEE";
	public static final String PARTY_POA_HOLDER = "PoA HOLDER";
	public static final String PARTY_POA_ACCEPTER = "PoA ACCEPTER";
	public static final String PARTY1_OWNER = "Party1(Owner)";
	public static final String PARTY2_OWNER = "Party2(Owner)";
	public static final String PARTY1_POA_HOLDER = "Party1(PoA Holder)";
	public static final String PARTY2_POA_HOLDER = "Party2(PoA Holder)";
	//property constants
	public static final String PROPERTY_TYPE = "3";
	public static final String WARD_OR_PATWARI = "WARD";
	public static final String BUILDING = "2";
	//estamp constants
	public static final String ESTAMP_CODE_MPET = "MP01";
	public static final String DISTRICT_CODE = "11";
	//
	public static final String ERROR_MSG = "COULD NOT UPDATE";
	//deed ids added by Roopam
	//public static final int DEED_CONVEYANCE_NP = 1020;
	public static final int DEED_CONVEYANCE_P = 1053;
	public static final int DEED_GIFT = 1055;
	public static final int DEED_CERTIFICATE_SALE = 1052;
	public static final int DEED_POA = 1038;
	//public static final int DEED_POA_P = 1064;
	public static final int DEED_EXCHANGE = 1054;
	public static final String DEED_EXCHANGE_STRING = "1054";
	public static final int DEED_DEPOSIT_OF_TITLE = 1006;
	public static final int DEED_TRUST = 1048;
	public static final int AWARD_WITHOUT_PROP = 1099;
	public static final int DEED_ADOPTION = 1003;
	public static final int DEED_CANCELLATION_OF_WILL_POA = 1014;
	//public static final int DEED_LEASE_PV = 1056;
	public static final int DEED_LEASE_NPV = 1029;
	//public static final int DEED_TRUST_PV = 1063;
	public static final int DEED_SETTLEMENT_PV = 1061;
	//public static final int DEED_MORTGAGE_PV = 1057;
	public static final int DEED_RELEASE_PV = 1060;
	//public static final int DEED_TRANSFER_LEASE_PV = 1062;
	public static final int DEED_AWARD_PV = 1051;
	//public static final int DEED_AGREEMENT_MEMO_PV = 1050;
	public static final int DEED_PARTITION_PV = 1058;
	//public static final int DEED_PARTITION_NPV = 1065;
	public static final int DEED_MORTGAGE_NPV = 1032;
	//public static final int DEED_SETTLEMENT_NPV = 1071;
	public static final int DEED_WILL_NPV = 1084;
	public static final int DEED_TRANSFER_LEASE_NPV = 1072;
	public static final int DEED_RECONV_MORTGAGE_NPV = 1041;
	public static final int DEED_SURRENDER_LEASE_NPV = 1046;
	public static final int DEED_AGREEMENT_MEMO_NPV_LOAN = 1097;
	public static final int DEED_AGREEMENT_MEMO_NPV = 1005;
	public static final int DEED_PARTNERSHIP_NPV = 1037;
	//public static final int DEED_FURTHER_CHARGE_PV = 1066;
	public static final int DEED_FURTHER_CHARGE_NPV = 1027;
	public static final int DEED_COMPOSITION_NPV = 1019;
	public static final int DEED_LETTER_OF_LICENCE_NPV = 1030;
	public static final int DEED_SECURITY_BOND_NPV = 1043;
	public static final int DEED_TRANSFER_NPV = 1047;
	//public static final int DEED_PARTNERSHIP_PV = 1070;
	//role ids added by Roopam
	public static final int ROLE_BUYER = 50001;
	public static final int ROLE_SELLER_SELF = 50002;
	public static final int ROLE_SELLER_POA_HOLDER = 50003;
	public static final int ROLE_OWNER_SELF = 50004;
	public static final int ROLE_DONOR = 50005;
	public static final int ROLE_DONEE = 50006;
	public static final int ROLE_OWNER_POA_HOLDER = 50007;
	public static final int ROLE_POA_ACCEPTER = 50008;
	public static final int ROLE_POA_ACCEPTER_POA = 50046;
	public static final int ROLE1_OWNER_SELF = 50009;
	public static final int ROLE2_OWNER_SELF = 50010;
	public static final int ROLE1_OWNER_POA_HOLDER = 50011;
	public static final int ROLE1_OWNER_AUTHENTICATED_POA_HOLDER = 50074;
	public static final int ROLE2_OWNER_AUTHENTICATED_POA_HOLDER = 50075;
	public static final int ROLE2_OWNER_POA_HOLDER = 50012;
	public static final int ROLE_BUYER_POA_HOLDER = 50014;
	public static final int ROLE_TRUSTEE = 50015;
	public static final int ROLE_ADOPTING_PARENT = 50016;
	public static final int ROLE_CHILD_ADOPTED = 50017;
	public static final int ROLE_CUSTODIAN = 50018;
	public static final int ROLE_ADOPTING_PARENT_POA_HOLDER = 50053;
	public static final int ROLE_CHILD_ADOPTED_POA_HOLDER = 50054;
	public static final int ROLE_CUSTODIAN_POA_HOLDER = 50055;
	public static final int ROLE_CANCELLATION_1 = 50019;
	public static final int ROLE_CANCELLATION_2 = 50020;
	public static final int ROLE_CANCELLATION_1_POA_HOLDER = 50056;
	public static final int ROLE_CANCELLATION_2_POA_HOLDER = 50057;
	public static final int ROLE_LESSER = 50021; //AS OWNER
	public static final int ROLE_LESSEE = 50022; //AS BUYER
	public static final int ROLE_TRUSTEE_POA_HOLDER = 50023;
	public static final int ROLE_SETTLER_SELF = 50024;
	public static final int ROLE_SETTLER_POA_HOLDER = 50025;
	public static final int ROLE_CLAIMANT_SELF = 50026;
	public static final int ROLE_CLAIMANT_POA_HOLDER = 50027;
	public static final int ROLE_MORTGAGER_SELF = 50028;
	public static final int ROLE_MORTGAGER_POA_HOLDER = 50029;
	public static final int ROLE_MORTGAGEE_SELF = 50030;
	public static final int ROLE_MORTGAGEE_POA_HOLDER = 50031;
	public static final int ROLE_RELEASER_SELF = 50032;
	public static final int ROLE_RELEASER_POA_HOLDER = 50033;
	public static final int ROLE_RELEASEE_SELF = 50034;
	public static final int ROLE_RELEASEE_POA_HOLDER = 50035;
	public static final int ROLE_TRANSFERER_SELF = 50036;
	public static final int ROLE_TRANSFERER_POA_HOLDER = 50037;
	public static final int ROLE_TRANSFEREE_SELF = 50038;
	public static final int ROLE_TRANSFEREE_POA_HOLDER = 50039;
	public static final int ROLE_AWARDER_SELF = 50040;
	public static final int ROLE_AWARDER_POA_HOLDER = 50041;
	public static final int ROLE_AWARDEE_SELF = 50042;
	public static final int ROLE_AWARDEE_POA_HOLDER = 50043;
	public static final int ROLE_LESSER_SELF = 50021;
	public static final int ROLE_LESSER_POA_HOLDER = 50044;
	public static final int ROLE_LESSEE_SELF = 50022;
	public static final int ROLE_LESSEE_POA_HOLDER = 50045;
	public static final int ROLE_ACCEPTER_POA_HOLDER = 50046;
	public static final int ROLE_TESTATOR_SELF = 50047;
	public static final int ROLE_TESTATOR_POA_HOLDER = 50048;
	public static final int ROLE_SURRENDERER_SELF = 50049;
	public static final int ROLE_SURRENDERER_POA_HOLDER = 50050;
	public static final int ROLE_DONOR_POA_HOLDER = 50051;
	public static final int ROLE_DONEE_POA_HOLDER = 50052;
	public static final int ROLE_EXECUTANT_SELF = 50019;
	public static final int ROLE_EXECUTANT_POA_HOLDER = 50056;
	public static final int ROLE_TRANS_PARTY_SELF = 50058;
	public static final int ROLE_TRANS_PARTY_POA_HOLDER = 50059;
	public static final int ROLE_RETIRING_PARTY_SELF = 50060;
	public static final int ROLE_RETIRING_PARTY_POA_HOLDER = 50061;
	public static final int ROLE_CO_OWNER_SELF = 50062;
	public static final int ROLE_CO_OWNER_POA_HOLDER = 50063;
	public static final int ROLE_CO_OWNER_AUTHENTICATED_POA_HOLDER = 50099;
	//PAYMENT CONSTANTS
	public static final String PAYMENT_FLAG_INITIATED = "I";
	public static final String PAYMENT_FLAG_PROCESSED = "P";
	public static final String PAYMENT_FLAG_COMPLETED = "C";
	//INSTRUMENTS
	public static final int INST_CONVEYANVE_P_2090 = 2090;
	public static final int INST_CONVEYANVE_P_2091 = 2091;
	public static final int INST_CONVEYANVE_P_2092 = 2092;
	public static final int INST_CONVEYANVE_P_2093 = 2093;
	public static final int INST_CONVEYANVE_P_2094 = 2094;
	public static final int INST_CONVEYANVE_P_2095 = 2095;
	public static final int INST_LEASE_PV_1 = 2175;
	public static final int INST_LEASE_PV_2 = 2176;
	public static final int INST_SETTLEMENT_PV_1 = 2114;
	public static final int INST_PARTITION_PV_1 = 2106;
	public static final int INST_PARTITION_PV_2 = 2108;
	public static final int INST_MORTGAGE_NPV_1 = 2054;
	public static final int INST_POA_1 = 2068;
	public static final int INST_POA_3 = 2066;
	public static final int INST_POA_2 = 2069;
	public static final int INST_SETTLEMENT_NPV_1 = 2154;
	public static final int INST_WILL_NPV_1 = 2174;
	public static final int INST_TRUST_NPV_P = 2083;
	public static final int INST_TRUST_NPV_NP = 2082;
	public static final int INST_PARTNERSHIP_NPV_1 = 2063;
	public static final int INST_PARTNERSHIP_NPV_2 = 2064;
	public static final int INST_AGREEMENT_MEMO_NPV_1 = 2005;
	public static final int INST_AGREEMENT_MEMO_NPV_2 = 2006;
	public static final int INST_AGREEMENT_MEMO_NPV_3 = 2007;
	public static final int INST_AGREEMENT_MEMO_NPV_4 = 2008;
	public static final int INST_AGREEMENT_MEMO_NPV_5 = 2009;
	public static final int INST_AGREEMENT_MEMO_NPV_6 = 2011;
	public static final int INST_AGREEMENT_MEMO_NPV_6_LOAN = 2264;
	public static final int INST_AGREEMENT_MEMO_NPV_7 = 2085;
	public static final int INST_AGREEMENT_MEMO_NPV_8 = 2177;
	public static final int INST_AGREEMENT_MEMO_NPV_9 = 2178;
	public static final int INST_AGREEMENT_MEMO_NPV_10 = 2010;
	public static final int INST_TRANSFER_NPV_1 = 2078; // PROPERTY NOT REQUIRED
	public static final int INST_TRANSFER_NPV_2 = 2079; // PROPERTY NOT REQUIRED
	public static final int INST_TRANSFER_NPV_3 = 2080; // PROPERTY REQUIRED BUT PV NOT REQUIRED
	public static final int INST_TRANSFER_NPV_4 = 2081; // PROPERTY REQUIRED BUT PV NOT REQUIRED
	public static final int INST_FURTHER_CHARGE_NPV_1 = 2041; // PROPERTY NOT REQUIRED
	public static final int INST_FURTHER_CHARGE_NPV_2 = 2039; // PROPERTY REQUIRED BUT PV NOT REQUIRED
	public static final int INST_DISSOLUTION_NPV = 2065;
	public static final int INST_DISSOLUTION_2 = 2153;
	public static final int INST_PARTNERSHIP_EXCLUDING_CASH = 2209;
	public static final int INST_BUILDER_1 = 2177;
	public static final int INST_BUILDER_2 = 2179;
	public static final int INST_SHARE_DEBENTURE = 2250;
	public static final int INST_AUTHENTICATE_POA = 2252;
	public static final int INST_TRUST_DISSOLUTION = 2117;
	public static final int INST_GIFT_FAMILY = 2097;
	public static final int INST_POA_FAMILY = 2067;
	//added by ankit for plant and machinery
	public static final int INST_PLANT_MACHINERY_ONLY = 2272;
	public static final int INST_GIFT_MOVABLE_PROP = 2276; // added by ankit for gift instrument 2276
	//ADDED BY SHRUTI
	public static final String REGCOMP_PROPERTYTYPE_ACTION = "REGCOMP_PROPERTYTYPE_ACTION";
	public static final String REGCOMP_PROPL1TYPE_ACTION = "REGCOMP_PROPL1TYPE_ACTION";
	public final static String DISTRICT_ACTION = "distChange";
	public final static String THESIL_ACTION = "thesilAction";
	public final static String AREA_TYPE_ACTION = "areaAction";
	public final static String WARD_ACTION = "wardAction";
	public final static String WARD_STATUS = "W";
	public final static String PATWARI_STATUS = "P";
	public final static String WARD_PATWARI_ACTION = "wardPatwariAction";
	//added by roopam
	public final static String INDIVIDUAL_ID = "2";
	public final static String ORGANISATION_ID = "1";
	public final static String GOVT_OFFCL_ID = "3";
	//public final static String FILE_UPLOAD_PATH = "F:/Upload/01/";
	public final static String FILE_UPLOAD_PATH = "01/";
	public final static String FILE_UPLOAD_PATH_PARTY = "/01/";
	public final static String FILE_UPLOAD_PATH_PROP = "/02/";
	public final static String FILE_UPLOAD_PATH_CONSENTER = "/04/";
	public final static String FILE_UPLOAD_PATH_DEED_DRAFT = "/03/";
	public final static String FILE_UPLOAD_PARTY = "01";
	public final static String FILE_UPLOAD_PROP = "02";
	public final static String DEFAULT_PATH = "";
	public final static String FILE_UPLOAD_AUDIT_REPORT = "05"; //Added by ankit for plant and machinery
	public final static String FILE_UPLOAD_PATH_AUDIT_REPORT = "/05/"; //Added by ankit for plant and machinery
	public final static String FILE_UPLOAD_PROP_DETLS = "06"; //Added by ankit for prop val changes
	public final static String FILE_UPLOAD_PATH_PROP_DETLS = "/06/"; //Added by ankit for prop val changes
	//PARTY RELATED UPLOAD
	public final static String FILE_NAME_CERTIFICATE = "01.";
	public final static String FILE_NAME_PHOTO_PROOF = "02.";
	public final static String FILE_NAME_NOTARIZED_AFFIDAVIT_EXECUTANT = "03.";
	public final static String FILE_NAME_EXECUTANT_PHOTO = "04.";
	public final static String FILE_NAME_NOTARIZED_AFFIDAVIT_ATTORNEY = "05.";
	public final static String FILE_NAME_ATTORNEY_PHOTO = "06.";
	public final static String FILE_NAME_CLAIMANT_PHOTO = "07.";
	public final static String FILE_NAME_PAN_FORM_60 = "08.";
	//Added bY Neeti --- Property Locking
	public final static String FILE_NAME_SIGNED_APPL_PROP_LOCK = "LOCK.";
	//PROPERTY RELATED UPLOADS
	public final static String FILE_NAME_PROP_ANGLE_1 = "01.";
	public final static String FILE_NAME_PROP_ANGLE_2 = "02.";
	public final static String FILE_NAME_PROP_ANGLE_3 = "03.";
	public final static String FILE_NAME_PROP_MAP = "04.";
	public final static String FILE_NAME_PROP_RIN = "05.";
	public final static String FILE_NAME_PROP_KHASRA = "06.";
	public final static String FILE_NAME_MPCST_MAP1 = "MAP1.";
	public final static String FILE_NAME_MPCST_MAP2 = "MAP2.";
	public final static String FILE_NAME_CLR_MAP = "MapCLR.";
	public final static String FILE_NAME_CLR_KHASRA = "KhasraCLR.";
	public final static String FILE_NAME_AUDIT_REPORT = "AuditReport."; // Added by ankit for plant and machinery
	//public final static String UPLOAD_COLLECTOR_CERTIFICATE_ID = "01";
	public final static String ST_CONSTANT = "1";
	public final static String PAN_CONSTANT = "4";
	//TITLE DEED--ADDED BY ROOPAM
	public static final String REGCOMP_PROPL2TYPE_ACTION = "REGCOMP_PROPL2TYPE_ACTION";
	//REGISTRATION TXN STATUSES
	public static final String STATUS_APP_SAVED = "1";
	public static final String STATUS_TRNS_SAVED = "2";
	public static final String STATUS_PROP_SAVED = "3";
	public static final String STATUS_MULTI_PROP_IN_PROGRESS = "4";
	//public static final String STATUS_MULTI_PROP_PV_RECVD="5";
	public static final String STATUS_SHARES_SAVED = "5";
	public static final String STATUS_BACKED_MAPPING_SAVED = "6";
	public static final String STATUS_FINAL_SCREEN = "9";
	public static final String STATUS_COMPLETE = "10";
	public static final String STATUS_MULTI_PROP_PV_RECVD = "7";
	public static final String CONSENTER_IN_PROGRESS = "20";
	//
	public static final String TXN_ID_PREFIX = "";
	public static final String SPLIT_CONSTANT = "~^";
	public static final String SPLIT_CONSTANT_KHASRA = ",";
	public static final String NOT_APPLICABLE = "N/A";
	public static final String EXTRA_FIELD_NOT_APPLICABLE = "NA";
	public static final int NPV_PROP_REQ_CONSTANT_1 = 1; //PROPERTY DETAILS REQUIRED BUT PV NOT REQUIRED
	public static final int NPV_PROP_NOT_REQ_CONSTANT_2 = 2; //PROPERTY DETAILS NOT REQUIRED
	//LABELS
	/*public static final String AGREEMENT_OF_MEMO_INST_2005="Amount of Bill of Exchange (Rs)";
	public static final String AGREEMENT_OF_MEMO_INST_2006="Amount of Security (Rs)";
	public static final String AGREEMENT_OF_MEMO_INST_2007="Amount of Security (Rs)";
	public static final String AGREEMENT_OF_MEMO_INST_2009="Consideration Amount (Rs)";
	public static final String AGREEMENT_OF_MEMO_INST_2011="Amount Of Debt (Rs)";
	public static final String AGREEMENT_OF_MEMO_INST_2085="Amount of Security (Rs)";
	public static final String AGREEMENT_OF_MEMO_INST_2177="Cost Of Construction";
	public static final String PARTNERSHIP_INST_2063="Consideration amount (Rs)";
	public static final String PARTNERSHIP_INST_2064="Amount Of shares contributed (Rs)";
	public static final String PARTNERSHIP_INST_2065="Base Value (Rs)";*/
	public static final int CLAIMANT_FLAG_1 = 1;
	public static final int CLAIMANT_FLAG_2 = 2;
	public static final int CLAIMANT_FLAG_3 = 3;
	public static final int CLAIMANT_FLAG_4 = 4;
	public static final int POA_HOLDER_FLAG = 1;
	public static final int CLAIMANT_FLAG_5 = 5;
	public static final int CLAIMANT_FLAG_6 = 6;
	public static final String LOGGED_IN_USER_RU = "2";
	public static final String LOGGED_IN_USER_SP = "3";
	public static final String LOGGED_IN_USER_SPB = "4";
	public static final String LOGGED_IN_USER_FI = "7";
	public static final String LOGGED_IN_USER_PO = "5"; //Post officer SP
	public static final String LOGGED_IN_USER_PUBOFC = "8";
	public static final String LOGGED_IN_USER_DRS = "I";
	public static final String LANGUAGE_HINDI = "hi";
	public static final String LANGUAGE_ENGLISH = "en";
	public static final String FEMALE_HINDI = "महिला";
	public static final String FEMALE_ENGLISH = "Female";
	public static final String MALE_HINDI = "पुरूष";
	public static final String MALE_ENGLISH = "Male";
	public static final String YES_HINDI = "हां";
	public static final String YES_ENGLISH = "Yes";
	public static final String NO_HINDI = "नहीं";
	public static final String NO_ENGLISH = "No";
	public static final String SQM_HINDI = "वर्ग मीटर";
	public static final String SQM_ENGLISH = "SQM";
	public static final String HECTARE_HINDI = "हेक्टेयर";
	public static final String HECTARE_ENGLISH = "HECTARE";
	public static final String WARD_HINDI = "वार्ड";
	public static final String WARD_ENGLISH = "Ward";
	public static final String PATWARI_HINDI = "पटवारी का हल्का";
	public static final String PATWARI_ENGLISH = "Patwari/Halka";
	public static final String MODNAME_HINDI = "पंजीकरण की प्रक्रिया";
	public static final String MODNAME_ENGLISH = "Registration Process";
	public static final String FUNCTION_REGINIT_HINDI = "शुरुआत";
	public static final String FUNCTION_REGINIT_ENGLISH = "Initiation";
	public static final String FUNCTION_ADJU_HINDI = "अधिनिर्णयन";
	public static final String FUNCTION_ADJU_ENGLISH = "Adjudication";
	//adjudication messages.
	public static final String ADJU_MSG_1 = "Adjudication Incomplete. / अधिनिर्णय आवेदन अधूरा है।";
	public static final String ADJU_MSG_2 = "Invalid Adjudication number. / अमान्य अधिनिर्णय नंबर।";
	public static final String ADJU_MSG_3 = "This Adjudication application has been deleted. So it can not be used in Registration Initiation. / यह अधिनिर्णय आवेदन हटा दिया गया है। यह पंजीकरण शुरूआत में प्रयोग नहीं किया जा सकता है।";
	public static final String ADJU_MSG_4 = "This application can be accessed through Registration Initiation dashboard. / यह आवेदन पंजीकरण शुरूआत डैशबोर्ड के माध्यम से संसाधित किया जा सकता है।";
	public static final String CREDITOR_HINDI = " (लेनदार)";
	public static final String CREDITOR_ENGLISH = " (Creditor)";
	public static final String DEBTOR_HINDI = " (ऋणी)";
	public static final String DEBTOR_ENGLISH = " (Debtor)";
	public static final String BENEFICIARY_HINDI = " (लाभार्थी)";
	public static final String BENEFICIARY_ENGLISH = " (Beneficiary)";
	public static final String NOT_DECLARED_HINDI = "घोषित नहीं किया";
	public static final String NOT_DECLARED_ENGLISH = "Not Declared";
	public static final String REGCOMP_SUBAREA_ACTION = "REGCOMP_SUBAREA_ACTION";
	//NEW DEED IDS
	public static final int DEED_AGREEMENT_MEMO_PV = 1005; // earlier 1050
	public static final int DEED_CONVEYANCE_NP = 1053; // earlier 1020
	public static final int DEED_FURTHER_CHARGE_PV = 1027; // earlier 1066
	public static final int DEED_LEASE_PV = 1029; // earlier 1056
	public static final int DEED_MORTGAGE_PV = 1032; // earlier 1057
	public static final int DEED_PARTNERSHIP_PV = 1037; // earlier 1070
	public static final int DEED_POA_P = 1038; // earlier 1064
	public static final int DEED_TRUST_PV = 1048; // earlier 1063
	public static final int DEED_PARTITION_NPV = 1058; // earlier 1065
	public static final int DEED_SETTLEMENT_NPV = 1061; // earlier 1071
	public static final int DEED_TRANSFER_LEASE_PV = 1072; // earlier 1062
	public static final int DEED_SECURITY = 1043;
	public static final int DEED_MORTGAGE_CROP = 1033;
	public static final int DEED_AGREEMENT_MEMO_PV_LOAN = 1097;
	public static final int DEED_ACK_RECEIPT = 1093;
	public static final int INST_ACK_RECEIPT_1 = 2187;
	public static final int DEED_BANK_GAURANTEE = 1087;
	public static final int INST_BANK_GAURANTEE_1 = 2204;
	public static final int DEED_CONSENT = 1088;
	public static final int INST_CONSENT_1 = 2205;
	public static final int DEED_DEC_UNDER_MP = 1090;
	public static final int INST_DEC_UNDER_MP_1 = 2212;
	public static final int DEED_DOC_AMEND = 1091;
	public static final int INST_DOC_AMEND_1 = 2213;
	public static final int INST_AGREEMENT_MEMO_NPV_WITHOUTPOS = 2009;
	public static final String PARTY_1_EN = "Party 1";
	public static final String PARTY_1_HI = "पक्षकार 1";
	public static final String PARTY_2_EN = "Party 2";
	public static final String PARTY_2_HI = "पक्षकार 2";
	public static final String MESSAGE_1_HI = "दल ठीक से गुणों के साथ मैप नहीं। पुनः दर्ज करें।";
	public static final String MESSAGE_1_EN = "Parties not properly mapped with properties. Please re-enter.";
	public static final String MESSAGE_2_HI = "संपत्ति आईडी या खसरा नो के लिए शेयरों को ठीक से परिभाषित नहीं किया गया है: ";
	//public static final String MESSAGE_2_EN = "Shares not properly defined. Please re-enter Share for Property Id or Khasra No: ";
	public static final String MESSAGE_2_EN = "Shares not properly defined for Property Id or Khasra No: ";
	public static final String MESSAGE_3_HI = "पार्टी जोड़ने के लिए 'अधिक जोड़ें' बटन पर क्लिक करें।";
	public static final String MESSAGE_3_EN = "Please click on Add More button to add the party.";
	public static final String MESSAGE_3_New_EN = "Please Enter Details Of Mandatory Party Type";
	public static final String MESSAGE_3_New_HI = "अनिवार्य पार्टी का विवरण दर्ज करें |";
	public static final String CANCELLATION_LABEL_EN = "Cancellation deed : ";
	public static final String CANCELLATION_LABEL_HI = "रद्‌द करने की लिखत : ";
	public static final String STATUS_COMPL_EN = "Complete";
	public static final String STATUS_COMPL_HI = "पूर्ण";
	public static final String STATUS_PEND_EN = "Pending";
	public static final String STATUS_PEND_HI = "अपूर्ण";
	public static final String STATUS_PARTIAL_EN = "Partial";
	public static final String STATUS_PARTIAL_HI = "अधूरा";
	public static final String STATUS_PROCESS_EN = "Processed";
	public static final String STATUS_PROCESS_HI = "संसाधित";
	public static final String STATUS_PEND_PAY_EN = "-";
	public static final String STATUS_PEND_PAY_HI = "-";
	public static final int MAX_FILE_SIZE = 500;
	public static final int MAX_FILE_SIZE_MPCST_MAP = 3000;
	public static final int MAX_FILE_SIZE_AUDIT_REPORT = 3000; //added by ankit for plant and machinery
	public static final int MAX_FILE_HEIGHT = 14031;
	public static final int MAX_FILE_WIDTH = 9921;
	/*public static final int MAX_FILE_HEIGHT = 297;
	public static final int MAX_FILE_WIDTH = 210;*/
	public static final String lbl_reg_init_upload_msg1 = "Invalid file selection. Please try again. / अवैध फाइल का चयन किया गया है। पुनः प्रयास करें।";
	public static final String lbl_reg_init_upload_msg2 = "Invalid file type. Please select another file. / अवैध फ़ाइल प्रकार का चयन किया गया है। अन्य फाइल चुनें।";
	public static final String lbl_reg_init_upload_msg3 = "File size is Greater than 500 KB. Please select another file. / फ़ाइल का माप 500 KB से अधिक है। अन्य फाइल चुनें।";
	public static final String lbl_reg_init_upload_msg4 = "Unable to upload file. Please try again. / फाइल अपलोड करने में असमर्थ। पुनः प्रयास करे।";
	public static final String lbl_reg_init_upload_msg5 = "File dimensions are Greater than 9921 x 14031. Please select another file. / फ़ाइल आयाम 9921 x 14031 से अधिक हैं। अन्य फाइल चुनें।";
	public static final String lbl_reg_init_upload_msg6 = "File size is Greater than 3000 KB. Please select another file. / फ़ाइल का माप 3000 KB से अधिक है। अन्य फाइल चुनें।";
	//public static final String mpcst_url="http://10.125.243.25/mpcost/ApolloPro.aspx?pasDistId={0}&pasTehsId={1}&pasAreaTypeId={2}&pasSubAreaTypeId={3}&pasWardPatwariId={4}&pasMohallaColonyId={5}&pasPropertyId={6}&pasRegTxnId={7}&pasSellersList=&pasSellersAddressList=&pasPlace={8}&pasDate={9}";
	// public static final String mpcst_url="http://164.100.196.33/mpcstfinal/ApolloPro.aspx?pasDistId={0}&pasTehsId={1}&pasAreaTypeId={2}&pasSubAreaTypeId={3}&pasWardPatwariId={4}&pasMohallaColonyId={5}&pasPropertyId={6}&pasRegTxnId={7}&pasSellersList=&pasSellersAddressList=&pasPlace={8}&pasDate={9}";	
	//done by akansha for mpcst change
	public static final String mpcst_url = "http://164.100.196.33/mpcstnew/ApolloPro.aspx?pasDistId={0}&pasTehsId={1}&pasAreaTypeId={2}&pasSubAreaTypeId={3}&pasWardPatwariId={4}&pasMohallaColonyId={5}&pasPropertyId={6}&pasRegTxnId={7}&pasSellersList=&pasSellersAddressList=&pasPlace={8}&pasDate={9}";
	//end by akansha for mpcst change
	//added by Shreeraj
	public static final String UPLOAD_DEED_DRAFT = "UPLOAD_DEED";
	public static final String UPLOAD_NAME_SIGN_DOC = "deedDraft.PDF";
	public static final String UPLOAD_DEED_CONSUMED = "deedConsumed.PDF";
	public static final String UPLOAD_DEED_UPLOADED = "deedUploaded.PDF";
	public static final String MPCST_FILE_1 = "image1.jpg";
	public static final String MPCST_FILE_2 = "image2.jpg";
	public static final String FAILURE_MSG = "failureMsg";
	public static final String PRINT_CONSENTER_PDF = "PRINT_CONSENTER_PDF";
	public static final String PRINT_CONSENTER_PDF_ENGLISH_JRXML = "uploadDeedPDF.jrxml";
	public static final String PRINT_CONSENTER_PDF_HINDI_JRXML = "uploadDeedPDFH.jrxml";
	public static final String UPLOAD_CONSENTER_DOC = "UPLOAD_CONSENTER_DOC";
	public static final String CONSENTER_PAGE = "PAGE ";
	public static final String DELETE_CONSENTER_DOC = "DELETE_CONSENTER_DOC";
	public static final String MERGE_CONSENTER_DEEDDRAFT = "MERGE_CONSENTER_DEEDDRAFT";
	public static final String UPLOAD_CONSENTER = "UPLOAD_CONSENTER";
	public static final String MERGED_DEED_DOC = "DeedDocument.pdf";
	public static final String ADD_UPLOADS_AGAIN = "ADD_UPLOADS_AGAIN";
	public static final String PROP_DETLS_DOC = "PropDetails.PDF"; //added by ankit for prop val
	// Added by Rahul - Memorandum - 
	public static final int INST_AGREEMENT_MEMO_MEDIA = 2255;
	public static final int INST_AGREEMENT_MEMO_WORK_CONTRACT = 2256;
	//Added by Ankit  - aadhar integration
	public static final String TRUE_VALUE = "TRUE_VALUE";
	public static final String FALSE_VALUE = "FALSE_VALUE";
	public static final String ERR_CODE_SEPARATOR = "ERR_CODE_SEPARATOR";
	public static final String LEFT_PARENTHESIS = "LEFT_PARENTHESIS";
	public static final String RIGHT_PARENTHESIS = "RIGHT_PARENTHESIS";
	public static final String FDC = "FDC";
	public static final String IDC = "IDC";
	public static final String LOT = "LOT";
	public static final String LOV = "LOV";
	public static final String PIP = "PIP";
	public static final String UDC = "UDC";
	public static final String LANGCODE = "LANGCODE";
	public static final String DOMAIN_ID = "DOMAIN_ID";
	public static final String TID = "TID";
	public static final String SUB_AUA_CODE = "SUB_AUA_CODE";
	public static final String LICENSE_KEY = "LICENSE_KEY";
	public static final String FDC_EKYC = "FDC_EKYC";
	public static final String IDC_EKYC = "IDC_EKYC";
	public static final String LOT_EKYC = "LOT_EKYC";
	public static final String LOV_EKYC = "LOV_EKYC";
	public static final String PIP_EKYC = "PIP_EKYC";
	public static final String UDC_EKYC = "UDC_EKYC";
	public static final String CONSENT = "CONSENT";
	public static final String AADHAR_DEMOGRH_URL = "AADHAR_DEMOGRH_URL";
	public static final String AADHAR_EKYC_URL = "AADHAR_EKYC_URL";
	public static final String RESIDENT_PHOTO_NAME = "RESIDENT_PHOTO_NAME";
	public static final String RES_IMG_FORMAT = "RES_IMG_FORMAT";
	public static final String AADHAR_CONNECTION_TIMEOUT = "AADHAR_CONNECTION_TIMEOUT";
	public static final String AADHAR_READ_TIMEOUT = "AADHAR_READ_TIMEOUT";
	public static final String AADHAR_EKYC_GENRIC_MSG = "AADHAR_EKYC_GENRIC_MSG";
	public static final String UNABLE_PROCESS_EKYC_REQ = "UNABLE_PROCESS_EKYC_REQ";
	public static final String TECHNICAL_ERROR = "TECHNICAL_ERROR";
	public static final String EKYC_RESPONSE_TIMEOUT_ERR = "EKYC_RESPONSE_TIMEOUT_ERR";
	public static final String AADHAR_RESPONSE_TIMEOUT_ERR = "AADHAR_RESPONSE_TIMEOUT_ERR";
	public static final String AADHAR_AUTH_GENERIC_MSG = "AADHAR_AUTH_GENERIC_MSG";
	public static final String UNABLE_PROCESS_AADHAR_REQ = "UNABLE_PROCESS_AADHAR_REQ";
	public static final String MODEL_DEFAULT_VALUE = "MODEL_DEFAULT_VALUE";
	public static final String DEPT_CODE = "DEPT_CODE";
	public static final String AES_ENCRYPTION_KEY_AADHAR = "AES_ENCRYPTION_KEY_AADHAR";
	public static final String OWNER_GENDER_ACTION = "OWNER_GENDER_ACTION";
	public static final String OWNER_GENDER_ACTION_TRNS = "OWNER_GENDER_ACTION_TRNS";
	public static final String OWNER_GENDER_ACTION_MODIFY = "OWNER_GENDER_ACTION_MODIFY";
	public static final String SUBMIT_FORM_ACTION_OWNER = "SUBMIT_FORM_ACTION_OWNER";
	public static final String OWNER_NO_ACTION_FOR_DISABLITY = "OWNER_NO_ACTION_FOR_DISABLITY";
	public static final String other_gender_ENGLISH = "Others";
	public static final String other_gender_hindi = "अन्य";
	//added by saurav
	public static final int TRANSFER_RIGHT_1 = 2273;
	public static final int TRANSFER_RIGHT_2 = 2274;
	//Added by ankit for plant and machinery
	public static final String UPLOAD_AUDIT_REPORT = "UPLOAD_AUDIT_REPORT";
	//added by Rustam
	public static final String LOGGED_IN_USER_TEHSILDAR="9";
	public static final String LOGGED_IN_USER_HONORABLE_JUDEG="12";
//added by ankit for aadhar bypass work
	public static final String ADHAR_BYPASS_MODULE_NAME_1 = "REGISTRATION PROCESS";
	public static final String ADHAR_STATUS_DESC_1 = "ADHAR_AUTH_ENABLE";
	public static final String ADHAR_STATUS_DESC_2 = "ADHAR_EKYC_ENABLE";
	
	//added by ankit for GIS work
	public static final String gis_duplicate_error= "GIS ID already exist \n\n जीआईएस आईडी पहले से मौजूद है";
	//added by saurav for mutation fee payment
	public static final String NEXT_TO_MUTATION_FEE_PAYMENT_ACTION = "NEXT_TO_MUTATION_FEE_PAYMENT_ACTION";
	public static final String FINAL_ACTION_MUTATION_FEE="FINAL_ACTION_MUTATION_FEE";
	
	//added by ankit for esing and pdf work
	public static final String aspserver_publicCertificateName = "aspserver_publicCertificateName";
	public static final String aspclient_privateCertificateName = "aspclient_privateCertificateName";
	public static final String FORMVIA_PATH = "FORMVIA_PATH";
	public static final String FORMVIA_FILENAME = "FORMVIA_FILENAME";
	public static final String FORMVIB_PATH = "FORMVIB_PATH";
	public static final String FORMVIB_FILENAME = "FORMVIB_FILENAME";
	public static final String ASP_ESIGN_RESPONSE_URL = "ASP_ESIGN_RESPONSE_URL";
	public static final String ESIGN_DEPT_ID = "ESIGN_DEPT_ID";
	public static final String HASHFILE_TEMP_PATH = "HASHFILE_TEMP_PATH";
	public static final String ERROR_MSG_ESIGN_ALL= "ESIGN NOT COMPLETED FOR ALL PARTIES";
	public static final String UPLOAD_FORM_A_1_FILE = "UPLOAD_FORM_A_1_FILE";
	public static final String UPLOAD_FORM_A_2_FILE = "UPLOAD_FORM_A_2_FILE";
	
}
