package com.wipro.igrs.SROMapping.sql;

public class SROMappingSQL {

	public static final String GET_OFFICE_SEQ="SELECT IGRS_SRO_OFC_SEQ.NEXTVAL FROM DUAL";
	//public static final String GET_SRO_OFC_SEQ="SELECT IGRS_WARD_MASTER_SEQ.NEXTVAL FROM DUAL";

	public static final String SELECT_STATE_LIST = "select state_id,upper(state_name),h_state_name from igrs_state_master where state_status='A' and country_id=? and state_id=1";
	public static final String SELECT_COUNTRY_LIST = "select country_id,upper(country_name),h_country_name from igrs_country_master where country_status='A'";
	public static final String SELECT_DISTRICT_LIST = "SELECT DISTRICT_ID,DISTRICT_NAME,H_DISTRICT_NAME FROM IGRS_DISTRICT_MASTER WHERE DISTRICT_ID in(SELECT district_id FROM igrs_office_master WHERE office_id =? and office_status='A') AND SRO_FLAG  ='A' AND DISTRICT_STATUS='A' AND STATE_ID=? ORDER BY DISTRICT_NAME ASC";
	public static final String SELECT_TEHSIL_LIST ="SELECT distinct TEHSIL_ID,upper(tehsil_name),H_TEHSIL_NAME FROM v_hierarchy vv WHERE district_id =? AND NOT EXISTS (SELECT 'x' FROM (SELECT v1.DISTRICT_ID, v1.TEHSIL_ID, v1.AREA_TYPE_ID, v1.SUB_AREA_TYPE_ID  FROM (  SELECT T.DISTRICT_ID,  T.TEHSIL_ID,  T.AREA_TYPE_ID, T.SUB_AREA_TYPE_ID, COUNT (distinct T.WARD_PATWARI_ID) c1 FROM v_hierarchy t GROUP BY T.DISTRICT_ID, T.TEHSIL_ID,  T.AREA_TYPE_ID,T.SUB_AREA_TYPE_ID) v1,(  SELECT O.DISTRICT_ID, O.TEHSIL_ID, O.AREA_TYPE_ID,O.SUB_AREA_TYPE_ID,COUNT (O.WARD_PATWARI_ID) c2 FROM igrs_office_ward_mapping o where O.STATUS_FLAG='A' GROUP BY O.DISTRICT_ID, O.TEHSIL_ID, O.AREA_TYPE_ID, O.SUB_AREA_TYPE_ID) v2 WHERE  v1.district_id = v2.district_id AND V1.tehsil_id = v2.tehsil_id AND v1.area_type_id = v2.area_type_id AND v1.sub_area_type_id = v2.sub_area_type_id AND v1.c1 = v2.c2) t11    WHERE     t11.DISTRICT_ID = vv.district_id AND t11.tehsil_id = vv.TEHSIL_ID AND t11.area_type_id = vv.AREA_TYPE_ID AND t11.sub_area_type_id = vv.SUB_AREA_TYPE_ID)order by upper(tehsil_name) ASC ";
	public static final String SELECT_AREA_LIST = "SELECT distinct AREA_TYPE_ID,upper(AREA_TYPE_NAME),H_AREA_TYPE_NAME FROM v_hierarchy vv WHERE district_id =? AND TEHSIL_ID=?  AND NOT EXISTS (SELECT 'x' FROM (SELECT v1.DISTRICT_ID, v1.TEHSIL_ID, v1.AREA_TYPE_ID, v1.SUB_AREA_TYPE_ID  FROM (  SELECT T.DISTRICT_ID,  T.TEHSIL_ID,  T.AREA_TYPE_ID, T.SUB_AREA_TYPE_ID, COUNT (distinct T.WARD_PATWARI_ID) c1 FROM v_hierarchy t GROUP BY T.DISTRICT_ID, T.TEHSIL_ID,  T.AREA_TYPE_ID,T.SUB_AREA_TYPE_ID) v1,(  SELECT O.DISTRICT_ID, O.TEHSIL_ID, O.AREA_TYPE_ID,O.SUB_AREA_TYPE_ID,COUNT (O.WARD_PATWARI_ID) c2 FROM igrs_office_ward_mapping o where O.STATUS_FLAG='A' GROUP BY O.DISTRICT_ID, O.TEHSIL_ID, O.AREA_TYPE_ID, O.SUB_AREA_TYPE_ID) v2 WHERE  v1.district_id = v2.district_id AND V1.tehsil_id = v2.tehsil_id AND v1.area_type_id = v2.area_type_id AND v1.sub_area_type_id = v2.sub_area_type_id AND v1.c1 = v2.c2) t11    WHERE     t11.DISTRICT_ID = vv.district_id AND t11.tehsil_id = vv.TEHSIL_ID AND t11.area_type_id = vv.AREA_TYPE_ID AND t11.sub_area_type_id = vv.SUB_AREA_TYPE_ID)order by upper(AREA_TYPE_NAME) ASC ";
	public static final String SELECT_SAREA_LIST="SELECT distinct SUB_AREA_TYPE_ID,upper(SUB_AREA_TYPE_NAME),H_SUB_AREA_TYPE_NAME FROM v_hierarchy vv WHERE district_id =? AND TEHSIL_ID=? AND AREA_TYPE_ID=? AND NOT EXISTS (SELECT 'x' FROM (SELECT v1.DISTRICT_ID, v1.TEHSIL_ID, v1.AREA_TYPE_ID, v1.SUB_AREA_TYPE_ID  FROM (  SELECT T.DISTRICT_ID,  T.TEHSIL_ID,  T.AREA_TYPE_ID, T.SUB_AREA_TYPE_ID, COUNT (distinct T.WARD_PATWARI_ID) c1 FROM v_hierarchy t GROUP BY T.DISTRICT_ID, T.TEHSIL_ID,  T.AREA_TYPE_ID,T.SUB_AREA_TYPE_ID) v1,(  SELECT O.DISTRICT_ID, O.TEHSIL_ID, O.AREA_TYPE_ID,O.SUB_AREA_TYPE_ID,COUNT (O.WARD_PATWARI_ID) c2 FROM igrs_office_ward_mapping o where O.STATUS_FLAG='A' GROUP BY O.DISTRICT_ID, O.TEHSIL_ID, O.AREA_TYPE_ID, O.SUB_AREA_TYPE_ID) v2 WHERE  v1.district_id = v2.district_id AND V1.tehsil_id = v2.tehsil_id AND v1.area_type_id = v2.area_type_id AND v1.sub_area_type_id = v2.sub_area_type_id AND v1.c1 = v2.c2) t11    WHERE     t11.DISTRICT_ID = vv.district_id AND t11.tehsil_id = vv.TEHSIL_ID AND t11.area_type_id = vv.AREA_TYPE_ID AND t11.sub_area_type_id = vv.SUB_AREA_TYPE_ID)order by upper(SUB_AREA_TYPE_NAME) ASC ";
	public static final String SELECT_WARD_LIST = "SELECT DISTINCT ward_patwari_id, UPPER(ward_patwari_name), h_ward_patwari_name FROM igrs_ward_patwari_master WHERE ward_patwari_status  ='A' AND ward_patwari_id  IN (( SELECT DISTINCT WARD_PATWARI_ID FROM IGRS_GUIDELINE_MASTER_CHILD1  WHERE TEHSIL_ID =? AND AREA_TYPE_ID =? AND SUB_AREA_TYPE_ID =? AND STATUS_FLAG ='3' AND ward_patwari_id IS NOT NULL) minus ( SELECT DISTINCT ward_patwari_id FROM igrs_office_ward_mapping owm WHERE tehsil_id =? AND area_type_id =? AND sub_area_type_id =? AND STATUS_FLAG ='A' AND ward_patwari_id IS NOT NULL )) ORDER BY UPPER(ward_patwari_name) ASC";
	public static final String SELECT_SRO_OFC_LIST ="Select OFFICE_ID,upper(OFFICE_NAME),H_OFFICE_NAME from IGRS_OFFICE_MASTER WHERE DISTRICT_ID=? and office_type_id=3 AND OFFICE_STATUS  ='A' order by upper(OFFICE_NAME) ASC ";
	
	public static final String SELECT_DISTRICT_LIST_EDIT="SELECT dm.DISTRICT_ID, dm.DISTRICT_NAME, dm.H_DISTRICT_NAME FROM IGRS_DISTRICT_MASTER dm,(SELECT DISTINCT (DISTRICT_ID) FROM IGRS_OFFICE_WARD_MAPPING WHERE status_flag = 'A') aa WHERE dm.DISTRICT_ID IN (SELECT district_id FROM igrs_office_master WHERE office_id =? AND office_status = 'A')AND dm.district_id = aa.DISTRICT_ID AND dm.SRO_FLAG = 'A' AND dm.DISTRICT_STATUS ='A' AND dm.STATE_ID = ? ORDER BY dm.DISTRICT_NAME ASC"; 
	public static final String SELECT_TEHSIL_LIST_EDIT="SELECT TEHSIL_ID, upper( TEHSIL_NAME), H_TEHSIL_NAME FROM IGRS_TEHSIL_MASTER WHERE TEHSIL_ID IN(SELECT DISTINCT(TEHSIL_ID) FROM igrs_office_ward_mapping WHERE DISTRICT_ID =? AND STATUS_FLAG  ='A' ) AND TEHSIL_STATUS='A' ORDER BY upper(TEHSIL_NAME) ASC";		
	public static final String SELECT_AREA_LIST_EDIT ="SELECT area_type_id, upper(area_type_name), h_area_type_name FROM igrs_area_type_master WHERE area_type_id IN (SELECT DISTINCT(area_type_id) FROM igrs_office_ward_mapping WHERE district_id=? AND tehsil_id =? and STATUS_FLAG='A' )and AREA_TYPE_STATUS='A' ORDER BY upper(area_type_name) ASC";
	public static final String SELECT_RURAL_SUBAREA_LIST_EDIT = "SELECT sub_area_type_id, upper(sub_area_type_name), h_sub_area_type_name FROM igrs_sub_area_type_master WHERE sub_area_type_id IN (SELECT DISTINCT(sub_area_type_id) FROM igrs_office_ward_mapping WHERE  AREA_TYPE_ID =? AND TEHSIL_ID=? AND STATUS_FLAG  ='A') and SUB_AREA_TYPE_STATUS='A' ORDER BY upper(sub_area_type_name) ASC";
	public static final String SELECT_URBAN_SUBAREA_LIST_EDIT = "SELECT sub_area_type_id, upper(sub_area_type_name), h_sub_area_type_name FROM igrs_sub_area_type_master WHERE sub_area_type_id IN (SELECT DISTINCT(sub_area_type_id) FROM igrs_office_ward_mapping WHERE AREA_TYPE_ID =? AND TEHSIL_ID   =? AND STATUS_FLAG ='A' ) AND SUB_AREA_TYPE_STATUS='A' ORDER BY upper(sub_area_type_name) ASC";  		
	public static final String SELECT_WARD_LIST_EDIT = " SELECT ward_patwari_id , Upper(ward_patwari_name) , h_ward_patwari_name FROM IGRS_WARD_PATWARI_MASTER WHERE ward_patwari_id IN (select distinct ward_patwari_id from igrs_guideline_master_child1 where ward_patwari_id in ( SELECT ward_patwari_id FROM IGRS_OFFICE_WARD_MAPPING WHERE tehsil_id =? AND area_type_id =? AND sub_area_type_id=? AND office_id =? AND STATUS_FLAG ='A' ))AND WARD_PATWARI_STATUS='A'ORDER BY Upper(ward_patwari_name) ASC";
	public static final String SELECT_SRO_OFC_LIST_EDIT= "SELECT DISTINCT office_id,upper(OFFICE_NAME) ,H_OFFICE_NAME FROM IGRS_OFFICE_MASTER Where OFFICE_ID in (SELECT DISTINCT(office_id) FROM igrs_office_ward_mapping WHERE district_id =? AND tehsil_id=? AND area_type_id=? AND sub_area_type_id =? AND STATUS_FLAG='A')AND office_type_id ='3' AND OFFICE_STATUS ='A' ORDER BY upper(OFFICE_NAME) ASC";
	public static final String DELETE_ENTRY = "update  igrs_office_ward_mapping set status_flag='D' where ward_patwari_id in ";
	
	public static final String INSERT_SRO_OFC_DATA =" INSERT INTO IGRS_OFFICE_WARD_MAPPING D (D.OFFICE_WARD_MAPPING_ID,D.DISTRICT_ID,D.TEHSIL_ID,D.AREA_TYPE_ID,D.SUB_AREA_TYPE_ID,D.CREATED_BY,D.CREATED_DATE,D.WARD_PATWARI_ID,D.OFFICE_ID,D.STATUS_FLAG)VALUES (?,?,?,?,?,?,SYSDATE,?,?,'A')";
	
	


}