package com.wipro.igrs.expmptc28.sql;

public class ExpMPTC28CommonSQL {
	public static final String SELECT_ALL_DISTRICTS = "SELECT DISTRICT_ID, DISTRICT_NAME FROM IGRS_DISTRICT_MASTER";
	public static final String SELECT_ALL_EMPLOYEES = "SELECT EMP_ID FROM IGRS_EMP_MASTER";
	public static final String SELECT_IGRS_EXP_MPTC_28_SEQ_NEXT = "SELECT IGRS_EXP_MPTC_28_SEQ.nextval FROM dual";
	public static final String SELECT_EMP_DETAILS = "SELECT D.DESIG_NAME, O.OFFICE_NAME, S.COMPONENT_VALUE "
														+ "FROM IGRS_EMP_OFFICIAL_DETAILS E, "
														    + "IGRS_EMP_DESIGNATION_MASTER D, " 
														    + "IGRS_EMP_OFFICE_MAPPING OM, "
														    + "IGRS_OFFICE_MASTER O, "
														    + "IGRS_EMP_SALARY_BASIC_DTLS S "
														    + "WHERE E.EMP_ID = ? AND OM.EMP_ID = E.EMP_ID AND S.EMP_ID = E.EMP_ID "
														    + "AND E.EMP_DESIGNATION_ID = D.DESIG_ID "
														    + "AND OM.OFFICE_ID = O.OFFICE_ID";
	public static final String ADD_EXP_MPTC28_DTLS = "INSERT INTO IGRS_EXP_MPTC_28_DTLS(EXP_VOUCHER_NO, DISTRICT_ID, ENTRY_DATE, ENTERED_BY, REMARKS) VALUES (?, ?, sysdate, ?, ?)";
	public static final String ADD_EXP_MPTC28_DTLS_MAP = "INSERT INTO IGRS_EXP_MPTC_28_DTLS_MAP(EXP_VOUCHER_NO, EMP_ID, DEPARTURE_FROM, DEPARTURE_DATE, ARRIVAL_TO, ARRIVAL_DATE, PURPOSE_OF_JOURNEY, EXP_AMOUNT, MODE_OF_TRAVEL, TRAVEL_CLASS, NO_KILOMETER, FARE_IN_CASE_TRNASFER, DA_AMOUNT, HQ_EXTEND_DA, HQ_JOURNEY_HOURS, JOURNEY_EXTEND_DA, JOURNEY_EXTEND_AMOUNT, JOURNEY_DURATION_HOURS, SP_EXTEND_DA, SP_AMOUNT, SP_JOURNEY_HOURS, EACH_LINE_TOTAL, REMARKS, REMARKS_DATE) " +
																						"VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, sysdate)";
}