/*
 * Copyright Notice
 *==============================================================================
 * This file contains proprietary information of Wipro Infotech, Bangalore.
 * Copying or reproduction without prior written approval is prohibited.
 * Copyright (c) 2007-08
 *==============================================================================
 *
 * File Name   :   CommonSQL.java
 * Author      :   Samuel Prabhakaran
 * 
 * ----------------------------------------------------------------------------
 * Version         Last Modified By     Last Modified On           Modification
 * ----------------------------------------------------------------------------
 * 1.0             Samuel Prabhakaran       17th March, 2008	 		
 * --------------------------------------------------------------------------------
 */



package com.wipro.igrs.rti.sql;

public class CommonSQL {
    public static final String IGRS_RTI_INFO = 
        "SELECT COUNT(*) FROM SYS.IGRS_RTI_INFO WHERE TRUNC(REQUEST_DATE) BETWEEN TO_CHAR(TO_DATE('";
    public static final String SET_DRO_NAME = 
        "UPDATE IGRS_RTI_INFO SET DRO_NAME=? WHERE RTI_ID=?";
    public static final String RESOLUTION_INFO = 
        "UPDATE IGRS_RTI_INFO SET RESOLUTION_INFO=? , RESOLUTION_REMARK =? WHERE RTI_ID=?";
    public static final String RTI_STATUS1 = 
        "SELECT RTI_ID,FIRST_NAME,MID_NAME,LAST_NAME,GENDER,AGE,FATHER_NAME,MOTHER_NAME,SPOUSE_NAME,ADDRESS,CITY," + 
        "COUNTRY,STATE,PIN,PHONE,MOBILE,EMAIL,IDPROOFNO,REQUEST_INFO,RESOLUTION_INFO,RESOLUTION_REMARK,RTI_STATUS," + 
        "DRO_NAME,SR_NAME,TO_CHAR(REQUEST_DATE,'DD/MM/YYYY'),TO_CHAR(RESOLUTION_DATE,'DD/MM/YYYY') " + 
        "FROM IGRS_RTI_INFO"; // WHERE "; //RTI_ID= ? AND RTI_STATUS=? ";//AND  TRUNC(REQUEST_DATE) BETWEEN ? ";
    //public static final String RTI_ID="SELECT RTI_ID,FIRST_NAME,MID_NAME FROM IGRS_RTI_INFO WHERE RTI_ID=?"; 

    public static final String INSERT_VALUES = 
        "INSERT INTO IGRS_RTI_INFO (RTI_ID, FIRST_NAME,MID_NAME,LAST_NAME,GENDER,AGE,FATHER_NAME,MOTHER_NAME,SPOUSE_NAME,ADDRESS,CITY,COUNTRY,STATE,PIN,PHONE,MOBILE,EMAIL,IDPROOFNO,REQUEST_INFO,REQUEST_DATE,RTI_STATUS)"; //VALUES";//(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,sysdate,?)";

    //  "INSERT INTO IGRS_RTI_INFO (RTI_ID, FIRST_NAME,MID_NAME,LAST_NAME,GENDER,AGE,FATHER_NAME,MOTHER_NAME,SPOUSE_NAME,ADDRESS,CITY,COUNTRY,STATE,PIN,PHONE,MOBILE,EMAIL,IDPROOFNO,REQUEST_INFO,REQUEST_DATE,RTI_STATUS)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,sysdate,?)";

    public static final String REQUEST_INFO = 
        "SELECT RTI_ID,REQUEST_DATE,REQUEST_INFO,RTI_STATUS FROM IGRS_RTI_INFO"; //WHERE FIRST_NAME=? AND MID_NAME=? AND AND LAST_NAME=? AND REQUEST_INFO=?"; 

    public static final String INSERT_RTI_INFO = 
        "INSERT INTO IGRS_RTI_INFO(RTI_ID,FIRST_NAME,MID_NAME,LAST_NAME,GENDER,AGE,FATHER_NAME,MOTHER_NAME,SPOUSE_NAME,ADDRESS,CITY,COUNTRY,STATE,PIN,PHONE,MOBILE,EMAIL,IDPROOFNO,REQUEST_INFO,REQUEST_DATE,RTI_STATUS) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,SYSDATE,'OPEN')";

    public static final String UPDATE_RTI_INFO = 
        "UPDATE IGRS_RTI_INFO SET RESOLUTION_INFO=? , RESOLUTION_REMARK =?,DRO_NAME=?,DR_NAME=?,DR_ID=?,RESOLUTION_DATE=SYSDATE,RTI_STATUS='CLOSE' WHERE RTI_ID=?";

    public static final String UPDATE_RESOLUTION1 = 
        "UPDATE IGRS_RTI_INFO SET RESOLUTION_INFO=?, RESOLUTION_REMARK=?  WHERE RTI_ID=?";

    public static final String SAVE_CLOSE1 = 
        "UPDATE IGRS_RTI_INFO SET RESOLUTION_INFO=?, RESOLUTION_REMARK=?,RTI_STATUS=?  WHERE RTI_ID=?";

    public static final String COUNTRY = 
        "SELECT COUNTRY_ID,COUNTRY_NAME FROM IGRS_COUNTRY_MASTER";

    public static final String DISTRICT = 
        "SELECT DISTRICT_ID,DISTRICT_NAME FROM IGRS_DISTRICT_MASTER WHERE ";
    public static final String STATE = 
        "SELECT STATE_ID,STATE_NAME FROM IGRS_STATE_MASTER";

    public static final String COUNT = 
        "SELECT COUNT(*) FROM IGRS_RTI_REQUEST_TXN WHERE ";

    public static final String EMPLOYEE = 
        "SELECT USER_ID FROM IGRS_USERS_LIST";

    public static final String IGRS_ID_TYPE = 
        "SELECT PHOTO_PROOF_TYPE_ID,PHOTO_PROOF_TYPE_NAME FROM IGRS_PHOTOID_PROOF_TYPE_MASTER";
       // " WHERE COMMON_RELATED_ID ='IGRS-ID-TYPE'";

    public static final String CHALLAN = 
        "INSERT INTO IGRS_PAYMENT_CHALLAN_DETAILS(CHALLAN_ID,CHALLAN_DATE,CHALLAN_AMOUNT) VALUES(?,?,?)";

    public static final String CASH = 
        "INSERT INTO IGRS_PAYMENT_CASH_DETAILS(CASH_RECEIPT_ID) VALUES(?)";


    //-----------------------------------------------------------------------

    public static final String REQUEST_RTI = 
        "INSERT INTO IGRS_RTI_TXN_PARTY_DETAILS(RTI_TXN_ID,PARTY_TYPE_ID,PARTY_FIRST_NAME,PARTY_MIDDLE_NAME,PARTY_LAST_NAME,PARTY_GENDER,PARTY_AGE,GUARDIAN_NAME,MOTHER_NAME,PARTY_ADDRESS,COUNTRY_ID,STATE_ID,DISTRICT_ID,POSTAL_CODE,PHONE_NUMBER,MOBILE_NUMBER,EMAIL_ID,PHOTO_PROOF_TYPE_ID,PHOTO_PROOF_ID) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";


    public static final String REQUEST_RTI_DETAILS = 
        "INSERT INTO IGRS_RTI_REQUEST_TXN(TRANSACTION_ID,REQUEST_TEXT,RTI_STATUS,CREATED_BY,CREATED_DATE) VALUES(?,?,?,?,SYSDATE)";

    public static final String RTI_INTIMATION_MAPPING = "INSERT INTO IGRS_RTI_INTIMATION_MAPPING(TRANSACTION_ID,INTIMATION_TYPE_ID,INTIMATION_TYPE_VALUE) VALUES(?,?,?)";
    
    public static final String GET_RTI_INTIMATION ="SELECT TRANSACTION_ID,INTIMATION_TYPE_ID,INTIMATION_TYPE_VALUE FROM IGRS_RTI_INTIMATION_MAPPING";
   public static final String RTI_STATUS = 
        "SELECT A.RTI_TXN_ID,A.PARTY_FIRST_NAME,A.PARTY_MIDDLE_NAME,A.PARTY_LAST_NAME,A.PARTY_GENDER,A.PARTY_AGE,A.GUARDIAN_NAME,A.MOTHER_NAME,A.PARTY_ADDRESS,A.DISTRICT_ID," + 
        "A.COUNTRY_ID,A.STATE_ID,A.POSTAL_CODE,A.PHONE_NUMBER,A.MOBILE_NUMBER,A.EMAIL_ID,B.REQUEST_TEXT,B.RTI_STATUS," + 
        "TO_CHAR(B.CREATED_DATE,'DD/MM/YYYY'),A.PHOTO_PROOF_TYPE_ID,A.PHOTO_PROOF_ID,B.REPLY_COMMENTS,B.ASSIGN_USER_ID,TO_CHAR(B.DUE_DATE,'DD/MM/YYYY'),E.TRANSACTION_ID,TO_CHAR(E.CREATED_DATE,'DD/MM/YYYY'),E.GROSS_AMOUNT " + 
        "FROM IGRS_RTI_TXN_PARTY_DETAILS A,IGRS_RTI_REQUEST_TXN B, IGRS_RTI_PAYMENT_TXN_MAPPING C,IGRS_PAYMENT_TXN_MAP D,IGRS_PAYMENT_MODE_DETAILS E WHERE A.RTI_TXN_ID = B.TRANSACTION_ID AND A.RTI_TXN_ID=C.TRANSACTION_ID AND C.PAYMENT_TXN_ID = D.PAYMENT_TXN_ID AND E.TRANSACTION_ID = D.PAYMENT_MODE_TXN_ID ";



    public static final String INSERT_RESOLUTION = 
        "INSERT INTO IGRS_RTI_TXN_COMMENTS(TRANSACTION_ID,USER_ID,USER_COMMENTS,COMMENT_DATE)VALUES(?,?,?,sysdate)" ;

    public static final String SAVE_CLOSE = 
        "UPDATE IGRS_RTI_REQUEST_TXN SET RTI_STATUS=?,NO_OF_PAGES=?,NO_HOURS=?,UPDATE_DATE=sysdate  WHERE TRANSACTION_ID=?";
        
    public static final String RTI_TXN_COMMENTS =
        "SELECT TRANSACTION_ID,USER_ID,USER_COMMENTS,COMMENT_DATE FROM IGRS_RTI_TXN_COMMENTS";
    
    public static final String INTIMATION_TYPE_ID =
    	"SELECT INTIMATION_TYPE_ID FROM IGRS_RTI_INTIMATION_MAPPING";
    
    
    //--------- Intimation Fee
   // public static final String RTI_EMAIL_INTIMATION_FEE_BASE_VALUE ="SELECT A.PARAM_VALUE FROM IGRS_SERVICE_FEE_PARAM_MAPPING A,IGRS_SERVICE_FEE_PARAM_MASTER B,IGRS_FUNCTION_MASTER C WHERE A.PARAM_ID=B.PARAM_ID AND B.PARAM_DESCRIPTION='SERVICE BASE VALUE' AND A.FUNCTION_ID=C.FUNCTION_ID AND C.FUNCTION_NAME='RTI_EMAIL_INTIMATION' AND C.SUB_MODULE_ID='101'"; 
    
    //public static final String RTI_SMS_INTIMATION_FEE_BASE_VALUE ="SELECT A.PARAM_VALUE FROM IGRS_SERVICE_FEE_PARAM_MAPPING A,IGRS_SERVICE_FEE_PARAM_MASTER B,IGRS_FUNCTION_MASTER C WHERE A.PARAM_ID=B.PARAM_ID AND B.PARAM_DESCRIPTION='SERVICE BASE VALUE' AND A.FUNCTION_ID=C.FUNCTION_ID AND C.FUNCTION_NAME='RTI_SMS_INTIMATION' AND C.SUB_MODULE_ID='101'"; 
    //public static final String RTI_EMAIL_INTIMATION_FEE_SALES_TAX ="SELECT A.PARAM_VALUE FROM IGRS_SERVICE_FEE_PARAM_MAPPING A,IGRS_SERVICE_FEE_PARAM_MASTER B,IGRS_FUNCTION_MASTER C WHERE A.PARAM_ID=B.PARAM_ID AND B.PARAM_DESCRIPTION='CENTRAL SALES TAX' AND A.FUNCTION_ID=C.FUNCTION_ID AND C.FUNCTION_NAME='RTI_EMAIL_INTIMATION' AND C.SUB_MODULE_ID='101'";    
    
    //public static final String RTI_EMAIL_INTIMATION_FEE_EDUCATION_CESS ="SELECT A.PARAM_VALUE FROM IGRS_SERVICE_FEE_PARAM_MAPPING A,IGRS_SERVICE_FEE_PARAM_MASTER B,IGRS_FUNCTION_MASTER C WHERE A.PARAM_ID=B.PARAM_ID AND B.PARAM_DESCRIPTION='EDUCATION CESS' AND A.FUNCTION_ID=C.FUNCTION_ID AND C.FUNCTION_NAME='RTI_EMAIL_INTIMATION' AND C.SUB_MODULE_ID='101'"; 
    
   //public static final String  RTI_EMAIL_INTIMATION_FEE_VALUE_ADDED_TAX ="SELECT A.PARAM_VALUE FROM IGRS_SERVICE_FEE_PARAM_MAPPING A,IGRS_SERVICE_FEE_PARAM_MASTER B,IGRS_FUNCTION_MASTER C WHERE A.PARAM_ID=B.PARAM_ID AND B.PARAM_DESCRIPTION='VALUE ADDED TAX' AND A.FUNCTION_ID=C.FUNCTION_ID AND C.FUNCTION_NAME='RTI_EMAIL_INTIMATION' AND C.SUB_MODULE_ID='101'"; 
   
   // public static final String RTI_SMS_INTIMATION_FEE_SALES_TAX ="SELECT A.PARAM_VALUE FROM IGRS_SERVICE_FEE_PARAM_MAPPING A,IGRS_SERVICE_FEE_PARAM_MASTER B,IGRS_FUNCTION_MASTER C WHERE A.PARAM_ID=B.PARAM_ID AND B.PARAM_DESCRIPTION='CENTRAL SALES TAX' AND A.FUNCTION_ID=C.FUNCTION_ID AND C.FUNCTION_NAME='RTI_SMS_INTIMATION' AND C.SUB_MODULE_ID='101'";    
    
   // public static final String RTI_SMS_INTIMATION_FEE_EDUCATION_CESS ="SELECT A.PARAM_VALUE FROM IGRS_SERVICE_FEE_PARAM_MAPPING A,IGRS_SERVICE_FEE_PARAM_MASTER B,IGRS_FUNCTION_MASTER C WHERE A.PARAM_ID=B.PARAM_ID AND B.PARAM_DESCRIPTION='EDUCATION CESS' AND A.FUNCTION_ID=C.FUNCTION_ID AND C.FUNCTION_NAME='RTI_SMS_INTIMATION' AND C.SUB_MODULE_ID='101'"; 
    
   // public static final String  RTI_SMS_INTIMATION_FEE_VALUE_ADDED_TAX ="SELECT A.PARAM_VALUE FROM IGRS_SERVICE_FEE_PARAM_MAPPING A,IGRS_SERVICE_FEE_PARAM_MASTER B,IGRS_FUNCTION_MASTER C WHERE A.PARAM_ID=B.PARAM_ID AND B.PARAM_DESCRIPTION='VALUE ADDED TAX' AND A.FUNCTION_ID=C.FUNCTION_ID AND C.FUNCTION_NAME='RTI_SMS_INTIMATION' AND C.SUB_MODULE_ID='101'";
    
   // public static final String RTI_POST_INTIMATION_FEE_BASE_VALUE ="SELECT A.PARAM_VALUE FROM IGRS_SERVICE_FEE_PARAM_MAPPING A,IGRS_SERVICE_FEE_PARAM_MASTER B,IGRS_FUNCTION_MASTER C WHERE A.PARAM_ID=B.PARAM_ID AND B.PARAM_DESCRIPTION='SERVICE BASE VALUE' AND A.FUNCTION_ID=C.FUNCTION_ID AND C.FUNCTION_NAME='RTI_POST_INTIMATION' AND C.SUB_MODULE_ID='101'"; 
    
   // public static final String RTI_POST_INTIMATION_FEE_SALES_TAX ="SELECT A.PARAM_VALUE FROM IGRS_SERVICE_FEE_PARAM_MAPPING A,IGRS_SERVICE_FEE_PARAM_MASTER B,IGRS_FUNCTION_MASTER C WHERE A.PARAM_ID=B.PARAM_ID AND B.PARAM_DESCRIPTION='CENTRAL SALES TAX' AND A.FUNCTION_ID=C.FUNCTION_ID AND C.FUNCTION_NAME='RTI_POST_INTIMATION' AND C.SUB_MODULE_ID='101'";    
    
    //public static final String RTI_POST_INTIMATION_FEE_EDUCATION_CESS ="SELECT A.PARAM_VALUE FROM IGRS_SERVICE_FEE_PARAM_MAPPING A,IGRS_SERVICE_FEE_PARAM_MASTER B,IGRS_FUNCTION_MASTER C WHERE A.PARAM_ID=B.PARAM_ID AND B.PARAM_DESCRIPTION='EDUCATION CESS' AND A.FUNCTION_ID=C.FUNCTION_ID AND C.FUNCTION_NAME='RTI_POST_INTIMATION' AND C.SUB_MODULE_ID='101'"; 
    
   // public static final String  RTI_POST_INTIMATION_FEE_VALUE_ADDED_TAX ="SELECT A.PARAM_VALUE FROM IGRS_SERVICE_FEE_PARAM_MAPPING A,IGRS_SERVICE_FEE_PARAM_MASTER B,IGRS_FUNCTION_MASTER C WHERE A.PARAM_ID=B.PARAM_ID AND B.PARAM_DESCRIPTION='VALUE ADDED TAX' AND A.FUNCTION_ID=C.FUNCTION_ID AND C.FUNCTION_NAME='RTI_POST_INTIMATION' AND C.SUB_MODULE_ID='101'";
    
    
   // public static final String RTI_PAGE_INTIMATION_FEE_BASE_VALUE ="SELECT A.PARAM_VALUE FROM IGRS_SERVICE_FEE_PARAM_MAPPING A,IGRS_SERVICE_FEE_PARAM_MASTER B,IGRS_FUNCTION_MASTER C WHERE A.PARAM_ID=B.PARAM_ID AND B.PARAM_DESCRIPTION='SERVICE BASE VALUE' AND A.FUNCTION_ID=C.FUNCTION_ID AND C.FUNCTION_NAME='RTI_PAGES' AND C.SUB_MODULE_ID='101'";
    
    
//public static final String RTI_PAGE_INTIMATION_FEE_SALES_TAX ="SELECT A.PARAM_VALUE FROM IGRS_SERVICE_FEE_PARAM_MAPPING A,IGRS_SERVICE_FEE_PARAM_MASTER B,IGRS_FUNCTION_MASTER C WHERE A.PARAM_ID=B.PARAM_ID AND B.PARAM_DESCRIPTION='CENTRAL SALES TAX' AND A.FUNCTION_ID=C.FUNCTION_ID AND C.FUNCTION_NAME='RTI_PAGES' AND C.SUB_MODULE_ID='101'";    
    
    //public static final String RTI_PAGE_INTIMATION_FEE_EDUCATION_CESS ="SELECT A.PARAM_VALUE FROM IGRS_SERVICE_FEE_PARAM_MAPPING A,IGRS_SERVICE_FEE_PARAM_MASTER B,IGRS_FUNCTION_MASTER C WHERE A.PARAM_ID=B.PARAM_ID AND B.PARAM_DESCRIPTION='EDUCATION CESS' AND A.FUNCTION_ID=C.FUNCTION_ID AND C.FUNCTION_NAME='RTI_PAGES' AND C.SUB_MODULE_ID='101'"; 
    
  // public static final String  RTI_PAGE_INTIMATION_FEE_VALUE_ADDED_TAX ="SELECT A.PARAM_VALUE FROM IGRS_SERVICE_FEE_PARAM_MAPPING A,IGRS_SERVICE_FEE_PARAM_MASTER B,IGRS_FUNCTION_MASTER C WHERE A.PARAM_ID=B.PARAM_ID AND B.PARAM_DESCRIPTION='VALUE ADDED TAX' AND A.FUNCTION_ID=C.FUNCTION_ID AND C.FUNCTION_NAME='RTI_PAGES' AND C.SUB_MODULE_ID='101'"; 
   
    
   // public static final String RTI_HOUR_INTIMATION_FEE_BASE_VALUE ="SELECT A.PARAM_VALUE FROM IGRS_SERVICE_FEE_PARAM_MAPPING A,IGRS_SERVICE_FEE_PARAM_MASTER B,IGRS_FUNCTION_MASTER C WHERE A.PARAM_ID=B.PARAM_ID AND B.PARAM_DESCRIPTION='SERVICE BASE VALUE' AND A.FUNCTION_ID=C.FUNCTION_ID AND C.FUNCTION_NAME='RTI_HOUR' AND C.SUB_MODULE_ID='101'"; 

//public static final String RTI_HOUR_INTIMATION_FEE_SALES_TAX ="SELECT A.PARAM_VALUE FROM IGRS_SERVICE_FEE_PARAM_MAPPING A,IGRS_SERVICE_FEE_PARAM_MASTER B,IGRS_FUNCTION_MASTER C WHERE A.PARAM_ID=B.PARAM_ID AND B.PARAM_DESCRIPTION='CENTRAL SALES TAX' AND A.FUNCTION_ID=C.FUNCTION_ID AND C.FUNCTION_NAME='RTI_HOUR' AND C.SUB_MODULE_ID='101'";    
    
   // public static final String RTI_HOUR_INTIMATION_FEE_EDUCATION_CESS ="SELECT A.PARAM_VALUE FROM IGRS_SERVICE_FEE_PARAM_MAPPING A,IGRS_SERVICE_FEE_PARAM_MASTER B,IGRS_FUNCTION_MASTER C WHERE A.PARAM_ID=B.PARAM_ID AND B.PARAM_DESCRIPTION='EDUCATION CESS' AND A.FUNCTION_ID=C.FUNCTION_ID AND C.FUNCTION_NAME='RTI_HOUR' AND C.SUB_MODULE_ID='101'"; 
    
  // public static final String  RTI_HOUR_INTIMATION_FEE_VALUE_ADDED_TAX ="SELECT A.PARAM_VALUE FROM IGRS_SERVICE_FEE_PARAM_MAPPING A,IGRS_SERVICE_FEE_PARAM_MASTER B,IGRS_FUNCTION_MASTER C WHERE A.PARAM_ID=B.PARAM_ID AND B.PARAM_DESCRIPTION='VALUE ADDED TAX' AND A.FUNCTION_ID=C.FUNCTION_ID AND C.FUNCTION_NAME='RTI_HOUR' AND C.SUB_MODULE_ID='101'"; 
   
   
   
   
   public static final String RTI_INTIMATION ="SELECT A.FUNCTION_NAME,B.SERVICE_NAME,C.PARAM_NAME,D.PARAM_VALUE FROM IGRS_FUNCTION_MASTER A, IGRS_SERVICE_MASTER B, IGRS_SERVICE_FEE_PARAM_MASTER C, IGRS_SERVICE_FEE_PARAM_MAPPING D WHERE A.FUNCTION_ID = D.FUNCTION_ID AND B.SERVICE_ID=D.SERVICE_ID AND C.PARAM_ID = D.PARAM_ID AND D.FUNCTION_ID='1001'";
   
    
    public static final String RTI_ASSIGN ="UPDATE IGRS_RTI_REQUEST_TXN SET REPLY_COMMENTS=?,ASSIGN_USER_ID=?,DUE_DATE=?,REPLY_STATUS=?,RTI_STATUS=? WHERE TRANSACTION_ID=?";
    
    public static final String RTI_EMAIL_FEE ="select COUNT(A.INTIMATION_TYPE_ID) from IGRS_RTI_INTIMATION_MAPPING A,IGRS_RTI_REQUEST_TXN B where A.INTIMATION_TYPE_ID='1' AND A.TRANSACTION_ID=B.TRANSACTION_ID" ;
    
    public static final String RTI_SMS_FEE ="select COUNT(A.INTIMATION_TYPE_ID) from IGRS_RTI_INTIMATION_MAPPING A,IGRS_RTI_REQUEST_TXN B where A.INTIMATION_TYPE_ID='2' AND A.TRANSACTION_ID=B.TRANSACTION_ID";
    
    public static final String RTI_POST_FEE ="select COUNT(A.INTIMATION_TYPE_ID) from IGRS_RTI_INTIMATION_MAPPING A,IGRS_RTI_REQUEST_TXN B where A.INTIMATION_TYPE_ID='3' AND A.TRANSACTION_ID=B.TRANSACTION_ID";
    
    public static final String RTI_APPEAL ="select COUNT(*) FROM IGRS_RTI_REQUEST_TXN WHERE";
    
    public static final String RTI_PAGE_FEE = "select SUM(NO_OF_PAGES) from IGRS_RTI_REQUEST_TXN where";
    
    public static final String RTI_HOUR_FEE = "select SUM(NO_HOURS) from IGRS_RTI_REQUEST_TXN where";

	public static final String RTI_UPDATE_DATE =
    	"SELECT TO_CHAR(UPDATE_DATE,'DD/MM/YYYY') FROM IGRS_RTI_REQUEST_TXN";
    
    public static final String RTI_REQUEST_DATE =
    	"SELECT TO_CHAR(CREATED_DATE,'DD/MM/YYYY') FROM IGRS_RTI_REQUEST_TXN";

	 public static final String RTI_PAYMENT ="INSERT INTO IGRS_RTI_PAYMENT_TXN_MAPPING(TRANSACTION_ID,PAYMENT_TXN_ID) VALUES(?,?)";

}
