package com.wipro.igrs.reginit.sql;


public class RegCommonSQL {
	public static final String SELECT_APPL_TYPE = "SELECT A.APPELLATE_TYPE_ID,A.APPELLATE_TYPE_NAME FROM IGRS_APPELLATE_TYPE_MASTER A WHERE A.APPELLATE_TYPE_STATUS='A' ORDER BY A.APPELLATE_TYPE_ID DESC";
	public static final String SELECT_COUNTRY = "SELECT C.COUNTRY_ID,C.COUNTRY_NAME FROM IGRS_COUNTRY_MASTER C WHERE C.COUNTRY_STATUS='A'";
	public static final String SELECT_STATE = "SELECT STATE_ID,STATE_NAME FROM IGRS_STATE_MASTER WHERE STATE_STATUS='A'";
	public static final String SELECT_DISTRICT = "SELECT DISTRICT_ID,DISTRICT_NAME FROM IGRS_DISTRICT_MASTER WHERE DISTRICT_STATUS='A'";
	public static final String SELECT_PHOTO_PROOF = "SELECT P.PHOTO_PROOF_TYPE_ID,P.PHOTO_PROOF_TYPE_NAME FROM IGRS_PHOTOID_PROOF_TYPE_MASTER P WHERE P.PHOTO_PROOF_TYPE_STATUS='A' ORDER BY P.PHOTO_PROOF_TYPE_ID ASC";
	public static final String SELECT_DEED_TYPE = "SELECT DEED_TYPE_ID,DEED_TYPE_NAME FROM IGRS_DEED_TYPE_MASTER WHERE DEED_STATUS='A'";
	//following added by Roopam
	public static final String SELECT_DEED_TYPE_OPTIONAL = "SELECT DEED_TYPE_ID,DEED_TYPE_NAME FROM IGRS_DEED_TYPE_MASTER WHERE DEED_STATUS='A' AND DEED_CATEGORY='O'";
	public static final String SELECT_DEED_INSTRUMENT = "SELECT INSTRUMENT_ID,INSTRUMENT_NAME FROM IGRS_DEED_INSTRUMENT_MASTER WHERE INSTRUMENT_STATUS='A' AND DEED_TYPE_ID=?"; 
	public static final String SELECT_DEED_EXEMPTION = "SELECT EXEMPTION_ID,EXEMPTION_NAME FROM IGRS_DEED_EXEMPTION_MASTER WHERE EXEMPTION_STATUS='A' AND INSTRUMENT_ID=?";
	public static final String SELECT_DEED_EXEMPTION_ONDEED = "SELECT EXEMPTION_ID,EXEMPTION_NAME FROM IGRS_DEED_EXEMPTION_MASTER WHERE EXEMPTION_STATUS='A' AND DEED_TYPE_ID=?";
	public static final String SELECT_OTHER_FEE = "SELECT MP.PARAM_VALUE,MP.PARAM_TYPE,M.OPERATOR_NAME FROM IGRS_SERVICE_FEE_PARAM_MAPPING MP,IGRS_OPERATOR_MASTER M,IGRS_FUNCTION_MASTER F WHERE F.FUNCTION_ID=MP.FUNCTION_ID AND MP.OPERATOR_ID=M.OPERATOR_ID AND F.FUNCTION_ID=";
	public static final String INSERT_STAMP_DUTY = "INSERT INTO IGRS_ESTAMP_TXN_DETAILS (TRANSACTION_ID,ESTAMP_DUTY,ESTAMP_OTHER_FEES,ESTAMP_TOTAL,ESTAMP_STATUS,ESTAMP_PURPOSE,ESTAMP_DATE,ESTAMP_CODE,PAYMENT_TXN_ID) VALUES(?,?,?,?,'A',?,SYSDATE,?,?)";
	public static final String INSERT_REG_TXN = "INSERT INTO IGRS_REG_INITN_TXN_DETAILS IG (IG.TRANSACTION_ID,IG.ESTAMP_TXN_ID,IG.FUNCTION_ID,IG.APPLICATION_STATUS,IG.CREATED_BY,IG.CREATED_DATE) VALUES (?,?,?,'A','ADMIN',SYSDATE)";
	public static final String INSERT_TEMP_REG_TXN = "INSERT INTO IGRS_REG_INITN_TXN_DETAILS (TRANSACTION_ID,APPLICATION_STATUS) VALUES (?,?)";
	public static final String INSERT_REG_DEED = "INSERT INTO IGRS_REG_INITN_DEED_DETAILS ID (ID.REG_TXN_ID,ID.DEED_TYPE_ID,ID.INSTRUMENT_ID,ID.EXEMPTION_ID) VALUES (?,?,?,?)";
	public static final String INSERT_REG_TXN_PARTY = "INSERT INTO IGRS_REG_INITN_TXN_PARTY_DTLS (REG_TXN_ID, PARTY_TYPE_ID, PARTY_FIRST_NAME, PARTY_MIDDLE_NAME, PARTY_LAST_NAME,PARTY_GENDER, PARTY_AGE, NATIONALITY, COUNTRY_ID, STATE_ID,DISTRICT_ID, PARTY_ADDRESS, POSTAL_CODE, PHONE_NUMBER, MOBILE_NUMBER,EMAIL_ID, PHOTO_PROOF_TYPE_ID, PHOTO_PROOF_ID, BANK_NAME, BANK_ADDRESS,ORGANIZATION_NAME, GUARDIAN_NAME, MOTHER_NAME, CATEGORY_ID, CASTE_ID,RELIGION_ID, PARTY_THUMB_IMPRESSION, PARTY_PHOTO, PARTY_SIGNATURE) Values (?,?,?,?,?,?,?,?,?,?,?,?,?,?, ?,?, ?, ?, ?, ?,?, ?, ?, NULL, NULL,NULL, NULL, NULL, NULL)";
	// IGRS_REG_INITN_TXN_PARTY_DTLS IN reginit
	public static final String INSERT_EXECUTION_DET = "UPDATE IGRS_REG_TXN_PARTY_DETAILS SET DEED_EXECUTION_DATE=?,DEED_EXECUTED_OUT_INDIA=? WHERE REG_TXN_ID=? AND PARTY_TXN_ID=?";
	public static final String INSERT_REG_PROPERTY_DETAILS = 
		"INSERT INTO  IGRS_REG_INIT_PROPERTY_DETAILS (" 
		+"PROPERTY_TYPE_ID,DISTRICT_ID,TEHSIL_ID,"
		+"WARD_PATWARI_ID,MOHALLA_VILLAGE_ID,"
		+"AREA_TYPE_ID,MUNCIPAL_BODY_TYPE_ID,"
		+"VIKAS_KHAND,RI_CIRCLE ,LAYOUT_DETAIL,"
		+"KHASRA_NUMBER,NAZOOL_SHEET_NUMBER,"
		+"RIN_PUSHTIKA_NUMBER,PROPERTY_ADDRESS,"
		+"EAST_BOUNDARY,WEST_BOUNDARY,NORTH_BOUNDARY,"
		+"SOUTH_BOUNDARY,PROPERTY_TXN_ID,UOM_ID,"
		+"PROPERTY_L1_ID,PROPERTY_L2_ID,TOTAL_AREA,"
		+"REG_TXN_ID) VALUES " 
		+"(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,"
		+"?,?,?,?,?,?)";
	public static final String INSERT_REG_PROPERTY_FLOOR_DTLS = 
			"INSERT INTO  IGRS_REG_INIT_PROP_FLOOR_DTLS ("
			+"FLOOR_TXN_ID,PROPERTY_TXN_ID,FLOOR_ID,"
			+"TOTAL_AREA,CONSTRUCTED_AREA,PROPERTY_L1_ID,"
			+"PROPERTY_L2_ID) VALUES(?,?,?,?,?,?,?)";
	
	public static final String INSERT_REG_PROP_SUBCLAUSE_MAP = 
		"INSERT INTO  IGRS_REG_INIT_PROP_SCLAUSE_MAP (PROPERTY_TXN_ID,"
		+"SUBCLAUSE_ID,SUBCLAUSE_VALUE,FLOOR_TXN_ID) VALUES (?,?,?,?)";
	public static final String INSERT_REG_PROPERTY_VALUE_DTLS = 
		"INSERT INTO  IGRS_REG_INIT_PROP_VALUE_DTLS( "
		+"PROPERTY_TXN_ID,FLOOR_TXN_ID,MARKET_VALUE,"
		+"CONSIDERATION_VALUE) VALUES (?,?,?,?)";
	//following added by roopam
	public static final String PROPERT_VAL_REQ_CHECK="SELECT PROPERTY_RELATED_DEED FROM IGRS_DEED_TYPE_MASTER WHERE DEED_TYPE_ID=?";
	/*public static final String SELECT_PARTY_TYPE = "SELECT iptm.PARTY_TYPE_ID,PARTY_TYPE_NAME FROM IGRS_PARTY_TYPE_MASTER_TEMP iptm, IGRS_PARTY_TYPE_DEED_MAP_TEMP iptdm WHERE PARTY_TYPE_STATUS='A' AND iptm.PARTY_TYPE_ID=iptdm.PARTY_TYPE_ID AND iptdm.DEED_TYPE_ID=";*/
	public static final String SELECT_PARTY_TYPE = "SELECT iptm.PARTY_TYPE_ID,PARTY_TYPE_NAME FROM IGRS_PARTY_TYPE_MASTER iptm, IGRS_PARTY_TYPE_DEED_MAP iptdm WHERE PARTY_TYPE_STATUS='A' AND MAPPING_STATUS='A' AND iptm.PARTY_TYPE_ID=iptdm.PARTY_TYPE_ID AND iptdm.DEED_TYPE_ID=?";
	/*public static final String INSERT_REG_TXN_PARTY_NEW = "INSERT INTO IGRS_REG_INIT_TXN_PARTY_TEMP VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";*/
	//above commented and following added by roopam for removing temp.
	//public static final String INSERT_REG_TXN_PARTY_NEW = "INSERT INTO IGRS_REG_INIT_TXN_PARTY_DTLS(REG_TXN_ID,PARTY_TYPE_ID, PARTY_FIRST_NAME, PARTY_MIDDLE_NAME, PARTY_LAST_NAME, PARTY_GENDER, PARTY_AGE, NATIONALITY, COUNTRY_ID, STATE_ID, DISTRICT_ID, PARTY_ADDRESS, POSTAL_CODE, PHONE_NUMBER, MOBILE_NUMBER, EMAIL_ID, PHOTO_PROOF_TYPE_ID, PHOTO_PROOF_ID, ORGANIZATION_NAME, AUTHRZD_PERSN_NAME, GUARDIAN_NAME, MOTHER_NAME, CASTE, RELIGION, PARTY_TXN_ID, IS_APPLICANT, IS_TXN_COMPLETE, DISABILITY, OWNERSHIP_SHARE, RELATION_WITH_OWNER, SHARE_OF_PROPERTY, PARTY_ROLE_TYPE_ID, CREATED_BY, CREATED_DATE, SPOUSE_NAME, OWNER_ID) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,sysdate,?,?)";
	public static final String GET_REG_TXN_ID_SEQ="SELECT IGRS_REG_TXN_ID_SEQ.NEXTVAL FROM DUAL";
    public static final String INSERT_REG_INIT_TXN_DETLS = "INSERT INTO IGRS_REG_INIT_TXN_DETLS VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
    //public static final String UPDATE_REG_INIT_TXN_PARTY_DETLS = "UPDATE IGRS_REG_INIT_TXN_PARTY_DTLS SET IS_TXN_COMPLETE='Y' WHERE REG_TXN_ID=";
    public static final String INSERT_POA_OWNER_MAPPING = "INSERT INTO IGRS_REG_INIT_POA_OWNER_MAP VALUES (?,?,?,?,sysdate,?,?)";
    public static final String DROP_REG_TXN_ID_SEQ="DROP SEQUENCE IGRS_REG_TXN_ID_SEQ";
    public static final String RESTART_REG_TXN_ID_SEQ="CREATE SEQUENCE IGRS_REG_TXN_ID_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 999999 MINVALUE 1 NOCYCLE NOCACHE NOORDER";
    public static final String PREVIOUS_REG_ID_DD="SELECT SUBSTR (REG_TXN_ID, 0, 2) FROM IGRS_REG_INIT_TXN_PARTY_DTLS WHERE CREATED_DATE = (SELECT MAX (CREATED_DATE) FROM IGRS_REG_INIT_TXN_PARTY_DTLS)";
    public static final String PREVIOUS_REG_ID_MM="SELECT SUBSTR (REG_TXN_ID, 3, 2) FROM IGRS_REG_INIT_TXN_PARTY_DTLS WHERE CREATED_DATE = (SELECT MAX (CREATED_DATE) FROM IGRS_REG_INIT_TXN_PARTY_DTLS)";
    public static final String PREVIOUS_REG_ID_YY="SELECT SUBSTR (REG_TXN_ID, 5, 2) FROM IGRS_REG_INIT_TXN_PARTY_DTLS WHERE CREATED_DATE = (SELECT MAX (CREATED_DATE) FROM IGRS_REG_INIT_TXN_PARTY_DTLS)";
    public static final String CURRENT_DATE_TIME="select sysdate from dual";
    public static final String PREVIOUS_CREATED_DATE="SELECT CREATED_DATE FROM IGRS_REG_INIT_TXN_PARTY_DTLS WHERE CREATED_DATE = (SELECT MAX (CREATED_DATE) FROM IGRS_REG_INIT_TXN_PARTY_DTLS)";
    //public static final String GET_APPLICANT_REG_DETLS="select FIRST_NAME,MIDDLE_NAME,LAST_NAME,GENDER,NATIONALITY,COUNTRY_ID,STATE_ID,DISTRICT_ID,ADDRESS,POSTAL_CODE,PHONE_NUMBER,MOBILE_NUMBER,EMAIL_ID,PHOTO_PROOF_TYPE_ID,PHOTO_PROOF_ID,GUARDIAN_NAME,MOTHER_NAME,SPOUSE_NAME from IGRS_USER_REG_DETAILS where user_id=";
    //public static final String INSERT_REG_DEED_DETLS="INSERT INTO IGRS_REG_INIT_DEED_DETLS(REG_TXN_ID,DEED_TYPE_ID,INSTRUMENT_ID,EXEMPTION_ID,CREATED_BY,CREATED_DATE) VALUES (?,?,?,?,?,sysdate)";
    //public static final String INSERT_REG_PROPERTY_DETLS="INSERT INTO IGRS_REG_INIT_PROPRTY_DTLS(PROPERTY_ID,REG_TXN_ID,CREATED_BY,CREATED_DATE,PROP_VAL_ID,MARKET_VALUE) VALUES (?,?,?,sysdate,?,?)";
    //public static final String GET_PENDING_APPLICATIONS_DETLS = "SELECT DISTINCT (RD.REG_TXN_ID), RD.CREATED_DATE, DM.DEED_TYPE_NAME, SUBSTR (RD.REG_TXN_ID, length(RD.REG_TXN_ID)-5, length(RD.REG_TXN_ID)) as sequence FROM IGRS_DEED_TYPE_MASTER DM, IGRS_REG_INIT_TXN_PARTY_DTLS RD, IGRS_REG_INIT_DEED_DETLS DD WHERE DM.DEED_TYPE_ID = DD.DEED_TYPE_ID AND RD.REG_TXN_ID = DD.REG_TXN_ID AND RD.IS_TXN_COMPLETE = 'N' AND RD.IS_APPLICANT = 'Y' AND (RD.CREATED_BY = ? OR RD.UPDATE_BY = ?) ORDER BY sequence DESC";
    //public static final String UPDATE_REG_INIT_PROP_DETLS = "UPDATE IGRS_REG_INIT_PROPRTY_DTLS SET VIKAS_KHAND = ?,RI_CIRCLE = ?,LAYOUT_DETAIL = ?,KHASRA_NUMBER = ?,NAZOOL_SHEET_NUMBER = ?,RIN_PUSHTIKA_NUMBER = ?,PLOT_NUMBER = ?,PROPERTY_ADDRESS = ?,EAST_BOUNDARY = ?,WEST_BOUNDARY = ?,NORTH_BOUNDARY = ?,SOUTH_BOUNDARY = ?,UPDATE_BY = ?,UPDATE_DATE = sysdate,KHASRA_AREA=?,LAGAAN=?,PROPERTY_LANDMARK=? WHERE REG_TXN_ID = ? AND PROPERTY_ID = ?";
    public static final String GET_REG_PROPERTY_ID_SEQ="SELECT IGRS_REG_PROPRTY_ID_SEQ.NEXTVAL FROM DUAL";
    //public static final String INSERT_REG_PROP_TRANS_MAP="INSERT INTO IGRS_REG_INIT_PROP_TRANS_MAP(REG_TXN_ID,PROPERTY_ID,TRANS_PARTY_ID,CREATED_BY,CREATED_DATE,MAPPING_TXN_ID) VALUES (?,?,?,?,sysdate,IGRS_REG_TRANS_PROP_MAP_ID_SEQ.NEXTVAL)";
    public static final String GET_REG_TRANS_PARTY_ID_SEQ="SELECT IGRS_REG_TRANS_PARTY_ID_SEQ.NEXTVAL FROM DUAL";
    public static final String GET_REG_TRANS_PARTY_PROP_MAP_ID_SEQ="SELECT IGRS_REG_TRANS_PROP_MAP_ID_SEQ.NEXTVAL FROM DUAL";
    //public static final String INSERT_OWNER_DETAILS="INSERT INTO IGRS_REG_INIT_TXN_PARTY_DTLS(REG_TXN_ID,PARTY_TYPE_ID,PARTY_FIRST_NAME,PARTY_GENDER,PARTY_AGE,NATIONALITY,PARTY_ADDRESS,MOBILE_NUMBER,EMAIL_ID,PHOTO_PROOF_TYPE_ID,PHOTO_PROOF_ID,ORGANIZATION_NAME,AUTHRZD_PERSN_NAME,PARTY_TXN_ID,IS_APPLICANT,IS_TXN_COMPLETE,SHARE_OF_PROPERTY,PARTY_ROLE_TYPE_ID,CREATED_BY,CREATED_DATE) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,sysdate)";
    //public static final String INSERT_DUTIES_DETAILS="INSERT INTO IGRS_REG_INIT_STAMP_DUTY_DETLS(DUTY_TXN_ID,REG_TXN_ID,STAMP_DUTY,GRAM_DUTY,NAGAR_DUTY,UPKAR,REG_FEE,TOTAL,CREATED_DATE,CREATED_BY,MARKET_VALUE_SHARE,DUTY_ALREADY_PAID,REG_ALREADY_PAID) VALUES(IGRS_REG_INIT_DUTY_ID_SEQ.NEXTVAL,?,?,?,?,?,?,?,sysdate,?,?,?,?)";
    public static final String GET_APPLICANT_DIST_ID="SELECT DISTRICT_ID FROM IGRS_REG_INIT_TXN_PARTY_DTLS WHERE UPPER(IS_APPLICANT)='Y' AND REG_TXN_ID=?";
    //FOLLOWING QUERIES FOR GETTING SAVED APPLICATION DETAILS
    //public static final String GET_SAVED_AAPLICANT_DETLS = "SELECT * FROM IGRS_REG_INIT_TXN_PARTY_DTLS WHERE IS_APPLICANT='Y' and  REG_TXN_ID=";
    public static final String GET_SAVED_TXN_PARTY_DETLS = "SELECT * FROM IGRS_REG_INIT_TXN_PARTY_DTLS WHERE IS_APPLICANT='N' and  REG_TXN_ID=";
    public static final String GET_SAVED_POA_OWNER_MAP_DETLS = "SELECT * FROM IGRS_REG_INIT_POA_OWNER_MAP WHERE REG_INIT_TXN_ID=";
    public static final String GET_SAVED_REGINIT_TXN_DETLS = "SELECT * FROM IGRS_REG_INIT_TXN_DETLS WHERE TRANSACTION_ID=";
    /*//FOLLOWING QUERIES FOR DELETING PARTIAL SAVED APPLICATIONS FROM DASHBOARD
    public static final String DEL_REG_INIT_TRANS_DETLS ="delete from IGRS_REG_INIT_TXN_PARTY_DTLS where REG_TXN_ID =";
    public static final String DEL_REG_INIT_PROP_DETLS ="delete from IGRS_REG_INIT_PROPRTY_DTLS where REG_TXN_ID =";
    public static final String DEL_REG_INIT_MAP_DETLS ="delete from IGRS_REG_INIT_POA_OWNER_MAP where REG_INIT_TXN_ID =";
    public static final String DEL_REG_INIT_DEED_DETLS ="delete from IGRS_REG_INIT_DEED_DETLS where REG_TXN_ID =";*/
    //FOLLOWING QUERIES FOR GETTING PARTIAL SAVED APPLICATION STATUSES
    public static final String GET_REG_INIT_TRANS_STATUS ="SELECT IS_APPLICANT,CREATED_DATE from IGRS_REG_INIT_TXN_PARTY_DTLS where REG_TXN_ID=? and CREATED_DATE=(select max(CREATED_DATE) from IGRS_REG_INIT_TXN_PARTY_DTLS where REG_TXN_ID=?)";
    public static final String GET_REG_INIT_PROP_STATUS ="SELECT EAST_BOUNDARY from IGRS_REG_INIT_PROPRTY_DTLS where REG_TXN_ID=";
    public static final String GET_REG_INIT_PROP_VAL_ID ="SELECT PROP_VAL_ID from IGRS_REG_INIT_PROPRTY_DTLS where REG_TXN_ID=?";
    public static final String GET_REG_INIT_MAP_STATUS ="SELECT REG_INIT_TXN_ID from IGRS_REG_INIT_POA_OWNER_MAP where REG_INIT_TXN_ID=";
    public static final String GET_REG_INIT_TXN_STATUS ="SELECT TRANSACTION_ID from IGRS_REG_INIT_TXN_DETLS where TRANSACTION_ID=";
    public static final String GET_REG_INIT_DEED_STATUS ="SELECT DEED_TYPE_ID from IGRS_REG_INIT_DEED_DETLS where REG_TXN_ID=";
    public static final String GET_REG_INIT_PROPERTY_ID ="SELECT PROPERTY_ID from IGRS_REG_INIT_PROPRTY_DTLS where CREATED_DATE=(SELECT MAX(CREATED_DATE) from IGRS_REG_INIT_PROPRTY_DTLS where REG_TXN_ID=? ) AND REG_TXN_ID=?";
    //FOLLOWING QUERIES FOR GETTING COUNTRY, STATE AND DISTRICT NAME FROM DATABASE CORRESPONDING TO THE IDS PROVIDED
    public static final String GET_COUNTRY_NAME="SELECT COUNTRY_NAME FROM IGRS_COUNTRY_MASTER WHERE COUNTRY_ID=?";
    public static final String GET_STATE_NAME="SELECT STATE_NAME FROM IGRS_STATE_MASTER WHERE STATE_ID=?";
    public static final String GET_DISTRICT_NAME="SELECT DISTRICT_NAME FROM IGRS_DISTRICT_MASTER WHERE DISTRICT_ID=?";
    public static final String GET_PHOTO_PROOF_NAME="SELECT PHOTO_PROOF_TYPE_NAME FROM IGRS_PHOTOID_PROOF_TYPE_MASTER WHERE PHOTO_PROOF_TYPE_ID=?";
    public static final String GET_PARTY_ROLE_NAME="SELECT PARTY_TYPE_NAME FROM IGRS_PARTY_TYPE_MASTER WHERE PARTY_TYPE_ID=?";
    public static final String GET_DEED_NAME="SELECT DEED_TYPE_NAME FROM IGRS_DEED_TYPE_MASTER WHERE DEED_TYPE_ID=?";
    public static final String GET_INST_NAME="SELECT INSTRUMENT_NAME FROM IGRS_DEED_INSTRUMENT_MASTER WHERE INSTRUMENT_ID=?";
    public static final String GET_EXMP_NAME="SELECT EXEMPTION_NAME FROM IGRS_DEED_EXEMPTION_MASTER WHERE EXEMPTION_ID=?";
    public static final String GET_SUBCLASE_NAME="SELECT SUB_CLAUSE_DESC FROM IGRS_SUB_CLAUSE_MASTER WHERE SUB_CLAUSE_ID=?";
    public static final String GET_CATEGORY_NAME="SELECT CATEGORY_NAME FROM IGRS_PERSON_CATEGORY_MASTER WHERE CATEGORY_ID=?";
    //FOLLOWING QUERY FOR GETTING PROPERTY DETAILS FOR DASHBOARD FROM DATABASE
    /*public static final String GET_PROP_DETLS_DASHBOARD="SELECT A.DISTRICT_ID,"+
    													"DISTRICT_NAME,"+
    													"A.TEHSIL_ID,"+
    													"TEHSIL_NAME,"+
    													"A.AREA_ID,"+
    													"AREA_TYPE_NAME,"+
    													"A.WARD_ID,"+
    													"WARD_PATWARI_NAME,"+
    													"WARD_OR_PATWARI,"+
    													"A.MAHALLA_ID,"+
    													"MOHALLA_VILLAGE_NAME,"+
    													"A.GOV_BODY_ID,"+
    													"MUNICIPAL_BODY_NAME,"+
    													"A.PROP_TYPE_ID,"+
    													"PROPERTY_TYPE_NAME,"+
    													"AREA,AREA_UNIT_ID "+
    													"FROM IGRS_PROP_TXN_DETAILS A, IGRS_DISTRICT_MASTER B, IGRS_TEHSIL_MASTER C,"+
    													"IGRS_AREA_TYPE_MASTER D, IGRS_WARD_PATWARI_MASTER E, IGRS_MOHALLA_VILLAGE_MASTER F,"+
    													"IGRS_MUNICIPAL_BODY_MASTER G, IGRS_PROPERTY_TYPE_MASTER H "+
    													"WHERE B.DISTRICT_ID = A.DISTRICT_ID "+
    													"AND C.TEHSIL_ID = A.TEHSIL_ID "+
    													"AND D.AREA_TYPE_ID=A.AREA_ID "+
    													"AND E.WARD_PATWARI_ID=A.WARD_ID "+
    													"AND F.MOHALLA_VILLAGE_ID=A.MAHALLA_ID "+
    													"AND G.MUNICIPAL_BODY_ID=A.GOV_BODY_ID "+
    													"AND H.PROPERTY_TYPE_ID=A.PROP_TYPE_ID "+
    													"AND VAL_TXN_ID =";*/
    //FOLLOWING QUERY FOR GETTING PARTY ROLE TYPE IDS FROM DB
    public static final String GET_PARTY_ROLE_ID_DASHBOARD="select PARTY_ROLE_TYPE_ID from IGRS_REG_INIT_TXN_PARTY_DTLS where REG_TXN_ID=";
    public static final String GET_POA_LIST_DASHBOARD="select PARTY_FIRST_NAME,PARTY_LAST_NAME,AUTHRZD_PERSN_NAME,PARTY_TXN_ID from IGRS_REG_INIT_TXN_PARTY_DTLS where (PARTY_ROLE_TYPE_ID=50003 or PARTY_ROLE_TYPE_ID=50007 or PARTY_ROLE_TYPE_ID=50011 or PARTY_ROLE_TYPE_ID=50012) and  REG_TXN_ID=";
    public static final String GET_OWNER_LIST_DASHBOARD="select PARTY_FIRST_NAME,PARTY_LAST_NAME,AUTHRZD_PERSN_NAME,PARTY_TXN_ID from IGRS_REG_INIT_TXN_PARTY_DTLS where (PARTY_ROLE_TYPE_ID=50004 or PARTY_ROLE_TYPE_ID=50009 or PARTY_ROLE_TYPE_ID=50010) and  REG_TXN_ID=";
    //FOLLOWING QUERIES FOR MULTIPLE PROPERTIES AND NEW CONFIRMATION SCREEN
    //public static final String GET_PROPERTY_ID_MARKET_VALUE="select PROPERTY_ID,MARKET_VALUE from IGRS_REG_INIT_PROPRTY_DTLS where REG_TXN_ID=";
    /*public static final String GET_TRANSACTING_PARTY_DETS="SELECT B.PARTY_TYPE_NAME,A.PARTY_FIRST_NAME,A.PARTY_LAST_NAME,A.AUTHRZD_PERSN_NAME,A.PARTY_TXN_ID,A.PARTY_ROLE_TYPE_ID "+
    														"FROM IGRS_REG_INIT_TXN_PARTY_DTLS A,"+
    														"IGRS_PARTY_TYPE_MASTER B,"+
    														"IGRS_REG_INIT_PROP_TRANS_MAP C "+
    														"WHERE B.PARTY_TYPE_ID=A.PARTY_ROLE_TYPE_ID "+
    														"AND C.TRANS_PARTY_ID=A.PARTY_TXN_ID "+
    														"AND C.REG_TXN_ID=A.REG_TXN_ID "+
    														"AND C.REG_TXN_ID=? "+
    														"AND C.PROPERTY_ID=? ORDER BY A.PARTY_TXN_ID";*/
    public static final String GET_APPLICANT_PARTY_DETS="SELECT B.PARTY_TYPE_NAME,A.PARTY_FIRST_NAME,A.PARTY_LAST_NAME,A.AUTHRZD_PERSN_NAME,A.PARTY_TXN_ID,A.PARTY_ROLE_TYPE_ID "+
    													"FROM IGRS_REG_INIT_TXN_PARTY_DTLS A,"+
    													"IGRS_PARTY_TYPE_MASTER B "+
    													"WHERE B.PARTY_TYPE_ID=A.PARTY_ROLE_TYPE_ID "+
    													"AND A.IS_APPLICANT='Y' "+ 
    													"AND A.REG_TXN_ID=?";
    /*public static final String GET_PARTY_DETS="SELECT A.PARTY_TYPE_ID, B.APPELLATE_TYPE_NAME, A.PARTY_FIRST_NAME, "+
    										 "A.PARTY_MIDDLE_NAME, A.PARTY_LAST_NAME, "+
    										 "A.PARTY_GENDER, A.PARTY_AGE, "+
    										 "A.NATIONALITY,C.COUNTRY_NAME, "+
    										 "D.STATE_NAME,E.DISTRICT_NAME, "+
    										 "A.PARTY_ADDRESS, A.POSTAL_CODE, "+
    										 "A.PHONE_NUMBER, A.MOBILE_NUMBER, "+
    										 "A.EMAIL_ID, A.PHOTO_PROOF_TYPE_ID, "+
    										 "A.PHOTO_PROOF_ID, A.ORGANIZATION_NAME, "+
    										 "A.AUTHRZD_PERSN_NAME, A.GUARDIAN_NAME, "+
    										 "A.MOTHER_NAME, A.CASTE, "+
    										 "A.RELIGION, A.PARTY_TXN_ID, "+
    										 "A.DISABILITY, A.OWNERSHIP_SHARE, "+
    										 "A.RELATION_WITH_OWNER, A.SHARE_OF_PROPERTY, "+
    										 "A.PARTY_ROLE_TYPE_ID, F.PARTY_TYPE_NAME,A.SPOUSE_NAME,A.OWNER_ID "+
    										 "FROM IGRS_REG_INIT_TXN_PARTY_DTLS A, "+
    										 "IGRS_APPELLATE_TYPE_MASTER B, "+
    										 "IGRS_COUNTRY_MASTER C, "+
    										 "IGRS_STATE_MASTER D, "+
    										 "IGRS_DISTRICT_MASTER E, "+
    										 "IGRS_PARTY_TYPE_MASTER F "+
    										 "WHERE A.PARTY_TYPE_ID=B.APPELLATE_TYPE_ID "+
    										 "AND A.COUNTRY_ID=C.COUNTRY_ID "+
    										 "AND A.STATE_ID=D.STATE_ID "+
    										 "AND A.DISTRICT_ID=E.DISTRICT_ID "+
    										 "AND A.PARTY_ROLE_TYPE_ID=F.PARTY_TYPE_ID "+
    										 "AND REG_TXN_ID=? "+ 
    										 "AND PARTY_TXN_ID=? ";*/
    //public static final String GET_REG_INIT_PROP_VALUATION_ID ="SELECT PROP_VAL_ID from IGRS_REG_INIT_PROPRTY_DTLS where REG_TXN_ID=? AND PROPERTY_ID=?";
    public static final String GET_REG_INIT_OTHER_PROP_DETS ="SELECT VIKAS_KHAND, RI_CIRCLE, LAYOUT_DETAIL, KHASRA_NUMBER,"+
    														"RIN_PUSHTIKA_NUMBER, NAZOOL_SHEET_NUMBER,"+
    														"PLOT_NUMBER, PROPERTY_ADDRESS, NORTH_BOUNDARY,"+
    														"SOUTH_BOUNDARY, EAST_BOUNDARY, WEST_BOUNDARY, KHASRA_AREA, LAGAAN, PROPERTY_LANDMARK "+
    														"FROM IGRS_REG_INIT_PROPRTY_DTLS "+
    														"WHERE REG_TXN_ID=? "+
    														"AND PROPERTY_ID=?";
    /*public static final String GET_REG_INIT_DUTY_DETS="SELECT STAMP_DUTY,GRAM_DUTY,NAGAR_DUTY,UPKAR,REG_FEE,TOTAL,A.SHARE_VALUE,A.DUTY_ALREADY_PAID,A.REG_ALREADY_PAID "+ 
    												  "FROM IGRS_PROP_STAMP_DUTY_DETAILS A,IGRS_REG_INIT_PROPRTY_DTLS B "+
    												  "WHERE B.PROP_VAL_ID=A.VAL_TXN_ID "+
    												  "AND B.REG_TXN_ID=";*/
    public static final String GET_REG_INIT_DUTY_DETS_FOR_CONFIRMATION="SELECT STAMP_DUTY,GRAM_DUTY,NAGAR_DUTY,UPKAR,REG_FEE,TOTAL,MARKET_VALUE_SHARE,DUTY_ALREADY_PAID,REG_ALREADY_PAID,SECURED_AMOUNT FROM IGRS_REG_INIT_STAMP_DUTY_DETLS WHERE REG_TXN_ID=?";
    //public static final String GET_APPLICANT_ROLE_ID="SELECT PARTY_ROLE_TYPE_ID FROM IGRS_REG_INIT_TXN_PARTY_DTLS WHERE UPPER(IS_APPLICANT)='Y' AND REG_TXN_ID=";
    public static final String GET_PROPERTY_DETAILS_FOR_DUTY_CALC="SELECT PROP_L1_TYPE__ID,AREA_ID,GOV_BODY_ID FROM IGRS_PROP_TXN_DETAILS WHERE VAL_TXN_ID=?";
    //public static final String GET_REG_INIT_DEED_INST_ID ="SELECT DEED_TYPE_ID,INSTRUMENT_ID, EXEMPTION_ID,ADJUDICATION_ID FROM IGRS_REG_INIT_DEED_DETLS WHERE REG_TXN_ID=";
    public static final String GET_BUILDING_FLOOR_DETAILS="SELECT FLOOR_TXN_ID,PROP_L1_TYPE__ID,PROP_L2_TYPE__ID,FLOOR_TYPE_ID,CONSIDER_AMOUNT,AREA,CONSTRUCTED_AREA,"+
    													  "B.PROPERTY_TYPE_L1_NAME,C.PROPERTY_TYPE_L2_NAME,D.FLOOR_NAME "+
    													  "FROM IGRS_PROP_FLOOR_DETAILS A,"+
    													  "IGRS_PROP_TYPE_L1_MASTER B,"+
    													  "IGRS_PROP_TYPE_L2_MASTER C,"+
    													  "IGRS_FLOOR_MASTER D "+
    													  "WHERE B.PROPERTY_TYPE_L1_ID=A.PROP_L1_TYPE__ID "+
    													  "AND C.PROPERTY_TYPE_L2_ID=A.PROP_L2_TYPE__ID "+
    													  "AND D.FLOOR_ID=A.FLOOR_TYPE_ID "+
    													  "AND VAL_TXN_ID=?";
    
    public static final String GET_ESTAMP_PURPOSE="SELECT PURPOSE_OF_DOC FROM IGRS_REG_TXN_DETLS WHERE REG_TXN_ID=?";
    public static final String UPDATE_ESTAMP_PURPOSE="UPDATE IGRS_REG_TXN_DETLS SET PURPOSE_OF_DOC=? WHERE REG_TXN_ID=?";
    
    public static final String GET_REG_INIT_DUTY_DETS_EXCHANGE_DEED="SELECT A.STAMP_DUTY,A.GRAM_DUTY,A.NAGAR_DUTY,A.UPKAR,A.REG_FEE,A.TOTAL,A.SHARE_VALUE,A.DUTY_ALREADY_PAID,A.REG_ALREADY_PAID "+ 
	  																"FROM IGRS_PROP_STAMP_DUTY_DETAILS A "+
	  																"WHERE A.VAL_TXN_ID=?";
	  																
    //public static final String GET_REF_VAL_ID_EXCHNG_DEED="SELECT A.REF_VAL_TXN_ID FROM IGRS_PROP_TXN_DETAILS A WHERE A.VAL_TXN_ID=(SELECT MAX(B.PROP_VAL_ID) FROM IGRS_REG_INIT_PROPRTY_DTLS B WHERE B.REG_TXN_ID=?)";
    //public static final String GET_EXCHNG_DEED_FINAL_MV="SELECT A.MARKET_VALUE FROM IGRS_PROP_TXN_DETAILS A WHERE A.VAL_TXN_ID=";
    
    
    //public static final String GET_SHARE_OF_PROPERTY_LIST="SELECT SHARE_OF_PROPERTY FROM IGRS_REG_INIT_TXN_PARTY_DTLS WHERE PARTY_ROLE_TYPE_ID=(SELECT PARTY_ROLE_TYPE_ID FROM IGRS_REG_INIT_TXN_PARTY_DTLS WHERE UPPER(IS_APPLICANT)='Y' AND REG_TXN_ID=? ) AND REG_TXN_ID=?";
    //public static final String GET_SHARE_OF_PROPERTY_LIST="SELECT SHARE_OF_PROPERTY FROM IGRS_REG_INIT_TXN_PARTY_DTLS WHERE (UPPER(IS_APPLICANT)='Y' OR UPPER(IS_APPLICANT)='C' ) AND REG_TXN_ID=";
    //public static final String GET_APPLICANT_SHARE_HOLDERS="SELECT * FROM IGRS_REG_INIT_TXN_PARTY_DTLS WHERE PARTY_ROLE_TYPE_ID=(SELECT PARTY_ROLE_TYPE_ID FROM IGRS_REG_INIT_TXN_PARTY_DTLS WHERE UPPER(IS_APPLICANT)='Y' AND REG_TXN_ID=? ) AND UPPER(IS_APPLICANT)!='Y' AND REG_TXN_ID=?";
    //public static final String GET_APPLICANT_SHARE_HOLDERS="SELECT * FROM IGRS_REG_INIT_TXN_PARTY_DTLS WHERE UPPER(IS_APPLICANT)='C' AND REG_TXN_ID=";
    //public static final String GET_OWNER_DETAILS="SELECT PARTY_FIRST_NAME,PARTY_GENDER,PARTY_AGE,NATIONALITY,PARTY_ADDRESS,MOBILE_NUMBER,EMAIL_ID,PHOTO_PROOF_TYPE_ID,PHOTO_PROOF_ID,ORGANIZATION_NAME,AUTHRZD_PERSN_NAME FROM IGRS_REG_INIT_TXN_PARTY_DTLS WHERE PARTY_TXN_ID=";
    //FOLLOWING QUERIES FOR NEW PAYMENT MODALITY
    //public static final String GET_REG_INIT_PAYMENT_FLAG ="SELECT PAYMENT_FLAG from IGRS_REG_INIT_TXN_DETLS where TRANSACTION_ID=";
    //public static final String INSERT_REG_INIT_PAYMENT_DETLS ="INSERT INTO IGRS_REG_INIT_TXN_DETLS(TRANSACTION_ID,ESTAMP_AMOUNT,PAYMENT_FLAG,CREATED_BY,CREATED_DATE,ESTAMP_PURPOSE) VALUES(?,?,?,?,sysdate,?)";
    //public static final String GET_REG_INIT_PAYMENT_TXN_ID ="SELECT PAYMENT_TXN_ID,PAID_AMOUNT FROM IGRS_REG_INIT_TXN_DETLS WHERE TRANSACTION_ID=";
    public static final String UPDATE_REG_INIT_ESTAMP_CODE ="UPDATE IGRS_REG_INIT_TXN_DETLS SET ESTAMP_TXN_ID=? WHERE TRANSACTION_ID=? AND PAYMENT_TXN_ID=?";
    //public static final String UPDATE_PAYMENT_FLAG_PURPOSE="UPDATE IGRS_REG_INIT_TXN_DETLS SET PAYMENT_FLAG=?, UPDATE_BY=?, UPDATE_DATE=sysdate WHERE TRANSACTION_ID=? AND PAYMENT_TXN_ID=?";

    //FOLLOWING QUERY FOR GETTING eSTAMP dETAILS
    //COmmented by SIMRAN--10 july
    //public static final String GET_ESTAMP_DETAILS="SELECT ESTAMP_TXN_ID,ESTAMP_AMOUNT,CREATED_DATE,PAYMENT_TXN_ID,ESTAMP_DATE,ESTAMP_TYPE_ID,ESTAMP_VALIDITY_DATE,ESTAMP_STATUS " +
    											 // "FROM IGRS_REG_INIT_TXN_DETLS WHERE TRANSACTION_ID =";
    public static final String GET_ESTAMP_DETAILS= "SELECT a.ESTAMP_TXN_ID,a.ESTAMP_AMOUNT,a.CREATED_DATE,a.PAYMENT_TXN_ID,a.ESTAMP_DATE," +
    		"a.ESTAMP_TYPE_ID,a.ESTAMP_VALIDITY_DATE,a.ESTAMP_STATUS,a.ESTAMP_CODE FROM " +
    		"IGRS_ESTAMP_DETLS a, IGRS_REG_ESTAMP_MAP b WHERE " +
    		"a.ESTAMP_TXN_ID = b.ESTAMP_TXN_ID AND b.REG_TXN_ID =?";
//FOLLOWING QUERIES ARE FOR ADJUDICATION
  // public static final String GET_REG_INIT_ADJUDICATION_STATUS="SELECT ADJUDCN_TXN_ID,IS_ADJU_COMPLETE FROM IGRS_REG_ADJUDCN_FINAL_DTLS WHERE ADJUDCN_TXN_ID=";
    public static final String UPDATE_TRANS_PARTY_TABLE="UPDATE IGRS_REG_INIT_TXN_PARTY_DTLS SET REG_TXN_ID=?,IS_TXN_COMPLETE='N',UPDATE_BY=?,UPDATE_DATE=sysdate WHERE ADJUDICATION_ID=?";
    public static final String UPDATE_STAMP_DUTY_TABLE="UPDATE IGRS_REG_INIT_STAMP_DUTY_DETLS SET REG_TXN_ID=?,MODIFIED_BY=?,MODIFIED_DATE=sysdate WHERE ADJUDICATION_ID=?";
    public static final String UPDATE_PROP_DETLS_TABLE="UPDATE IGRS_REG_INIT_PROPRTY_DTLS SET REG_TXN_ID=?,UPDATE_BY=?,UPDATE_DATE=sysdate WHERE ADJUDICATION_ID=?";
    public static final String UPDATE_DEED_DETLS_TABLE="UPDATE IGRS_REG_INIT_DEED_DETLS SET REG_TXN_ID=?,UPDATE_BY=?,UPDATE_DATE=sysdate WHERE ADJUDICATION_ID=?";
    public static final String UPDATE_PROP_TRANS_MAP_TABLE="UPDATE IGRS_REG_INIT_PROP_TRANS_MAP SET REG_TXN_ID=?,UPDATE_BY=?,UPDATE_DATE=sysdate WHERE ADJUDICATION_ID=?";
    public static final String GET_PROPERTY_ID_MARKET_VALUE_ADJU="select PROPERTY_TXN_ID,MARKET_VALUE from IGRS_REG_ADJUDCN_PROP_DTLS where ADJUDCN_TXN_ID=?";
    public static final String GET_ADJUDICATED_DUTY_DETS="SELECT A.STAMP_DUTY,A.JANPAD_DUTY,A.MUNICIPAL_DUTY,A.UPKAR_DUTY,A.REGISTRATION_FEE,A.TOTAL_DUTY,B.MARKET_VALUE_SHARE,B.DUTY_ALREADY_PAID,B.REG_ALREADY_PAID FROM IGRS_REG_ADJUDCN_FINAL_DTLS A,IGRS_REG_INIT_STAMP_DUTY_DETLS B WHERE A.ADJUDCN_TXN_ID=B.ADJUDICATION_ID AND A.ADJUDCN_TXN_ID=?";


//QUERIES FOR EXCHANGE DEED
    
    //public static final String GET_ALL_VALUATION_IDS_EXCHANGE="SELECT VAL_TXN_ID FROM IGRS_PROP_TXN_DETAILS WHERE REF_VAL_TXN_ID=";
    //public static final String GET_ALL_PROPERTY_DETLS_EXCHANGE="SELECT VAL_TXN_ID,DISTRICT_ID,TEHSIL_ID,MARKET_VALUE,PARTY_TYPE FROM IGRS_PROP_TXN_DETAILS WHERE VAL_TXN_ID=";

//FOLLOWING QUERIES FOR GETTING SUB-CLAUSE LIST
    
    //public static final String GET_SUB_CLAUSE_LIST_NON_BUILDING="SELECT SUB_CLAUSE_ID FROM IGRS_PROP_SUBCLAUSE_DETAILS WHERE VAL_TXN_ID=";
    //public static final String GET_SUB_CLAUSE_LIST_BUILDING="SELECT SUB_CLAUSE_ID FROM IGRS_PROP_SUBCLAUSE_DETAILS WHERE VAL_TXN_ID=";
    //public static final String GET_SUB_CLAUSE_LIST_BUILDING="SELECT SUB_CLAUSE_ID FROM IGRS_PROP_SUBCLAUSE_DETAILS WHERE VAL_TXN_ID=? AND FLOOR_TXN_ID=?";

    //added by shruti for DEPOSIT OF TITLE DEED
    //public static final String SELECT_DEED_ID="select  DEED_ID FROM IGRS_STAMP_DUTY_DETAILS WHERE DUTY_TXN_ID=?";
    public static final String SELECT_EXEMPTION_ID="select EXEMPTION_ID FROM IGRS_EXEMPTION_DETAILS WHERE DUTY_TXN_ID=?";
    //public static final String SELECT_INSTRUMENT_ID="select  INSTRUMENT_ID FROM IGRS_STAMP_DUTY_DETAILS WHERE DUTY_TXN_ID=?";
    public static final String INSERT_REG_DEED_EXTRA_DTLS="INSERT INTO IGRS_REG_DEEDS_EXTRA_DTLS( REG_TXN_ID,BANK_NAME_DEPOSIT_DEED,"
    													+"BRANCH_NAME_DEPOSIT_DEED,BANK_ADDRESS_DEPOSIT_DEED,BANK_AUTH_PERSON_DEPOSIT_DEED,LOAN_AMOUNT,SANCTIONED_AMOUNT,"
    													+"CREATED_BY,CREATED_DATE,TRUST_NAME,TRUST_DATE,RENT,ADVANCE,DEVELOPMENT_CHARGE,OTHER_REC_CHARGE_PAID,PREMIUM,TERM_OF_LEASE,WITH_POSSESSION,SEC_LOAN_AMT,"
    													+"PARTY_FIRST_NAME,PARTY_MIDDLE_NAME,PARTY_LAST_NAME,PARTY_GENDER,PARTY_AGE,GUARDIAN_NAME,MOTHER_NAME,SPOUSE_NAME,NATIONALITY,PARTY_ADDRESS,COUNTRY_ID,STATE_ID,"
    													+"DISTRICT_ID,PHONE_NUMBER,MOBILE_NUMBER,EMAIL_ID,CATEGORY_ID,DISABILITY,DISABILITY_DESC,PHOTO_PROOF_TYPE_ID,PHOTO_PROOF_ID,ADVANCE_PAYMNT_DATE,POSSESION_GIVEN,"
    													+"POA_WITH_CONSIDRTN,POA_PERIOD,PAID_LOAN_AMT,CONTRIBUTORY_PROP,DISSOLUTION_DATE,RETIRMENT_DATE)"
    													+"VALUES(?,?,?,?,?,?,?,?,SYSDATE,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";

    public static final String SELECTPROPERTYTYPEL1DETAILS="SELECT PROPERTY_TYPE_L1_ID,PROPERTY_TYPE_L1_NAME FROM IGRS_PROP_TYPE_L1_MASTER WHERE PROPERTY_TYPE_ID=?"; 
    public static final String GET_REG_INIT_NON_PROP_DUTY_DETS="SELECT STAMP_DUTY,GRAM_DUTY,NAGAR_DUTY,UPKAR,REG_FEE,TOTAL,A.SHARE_VALUE,A.DUTY_ALREADY_PAID,A.REG_ALREADY_PAID "+ 
	  "FROM IGRS_STAMP_DUTY_DETAILS A,IGRS_REG_INIT_NON_PROP_DTLS B "+
	  "WHERE B.DUTY_TXN_ID=A.DUTY_TXN_ID "+
	  "AND B.REG_TXN_ID=";

//end of code by shruti
    
    
    //FOLLOWING ADDED BY ROOPAM ON OR AFTER 25TH APRIL 2013
    public static final String SELECT_CATEGORY = "SELECT A.CATEGORY_ID,A.CATEGORY_NAME FROM IGRS_PERSON_CATEGORY_MASTER A WHERE A.CATEGORY_STATUS='A' ORDER BY A.CATEGORY_ID DESC";
    
    //post database restructuring 16 May 2013
    public static final String INSERT_REG_TXN_PARTY_NEW = "INSERT INTO IGRS_REG_TXN_PARTY_DETLS(REG_TXN_ID,APPELLATE_TYPE_ID, PARTY_FIRST_NAME, PARTY_MIDDLE_NAME, PARTY_LAST_NAME, PARTY_GENDER, PARTY_AGE, NATIONALITY, COUNTRY_ID, STATE_ID, DISTRICT_ID, PARTY_ADDRESS, POSTAL_CODE, PHONE_NUMBER, MOBILE_NUMBER, EMAIL_ID, PHOTO_PROOF_TYPE_ID, PHOTO_PROOF_ID, ORGANIZATION_NAME, AUTHRZD_PERSN_NAME, GUARDIAN_NAME, MOTHER_NAME, CATEGORY_ID, PARTY_TXN_ID, IS_APPLICANT, OCCUPATION_ID, DISABILITY, RELATION_WITH_OWNER, SHARE_OF_PROPERTY, PARTY_TYPE_ID, CREATED_BY, CREATED_DATE, SPOUSE_NAME, OWNER_ID, DISABILITY_DESC, MEMBER_MINORITY, BELOW_POVERTY_LINE,CATEGORY_ST_SCHEDULE_AREA,COLLECTOR_PERMISSION_NUMBER,COLLECTOR_CERTIFICATE_PATH,PHOTO_PROOF_PATH,NOT_AFFD_EXEC_PATH,EXEC_PHOTO_PATH,NOT_AFFD_ATTR_PATH,ATTR_PHOTO_PATH,CLAIMNT_PHOTO_PATH,PAN_FORM_60_PATH,POA_SR_OFFICE_NAME,POA_REG_NO,POA_REG_DATE,ROLE_NAME,RELATION_TYPE_ID,UNIVERSAL_DEED_CLAIMANT_FLAG,AUTH_PER_COUNTRY_ID,AUTH_PER_STATE_ID,AUTH_PER_DISTRICT_ID,AUTH_PER_PARTY_ADDRESS) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,sysdate,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
    public static final String INSERT_OWNER_DETAILS="INSERT INTO IGRS_REG_TXN_PARTY_DETLS(REG_TXN_ID,APPELLATE_TYPE_ID,PARTY_FIRST_NAME,PARTY_GENDER,PARTY_AGE,NATIONALITY,PARTY_ADDRESS,MOBILE_NUMBER,EMAIL_ID,PHOTO_PROOF_TYPE_ID,PHOTO_PROOF_ID,ORGANIZATION_NAME,AUTHRZD_PERSN_NAME,PARTY_TXN_ID,IS_APPLICANT,SHARE_OF_PROPERTY,PARTY_TYPE_ID,CREATED_BY,CREATED_DATE) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,sysdate)";
    public static final String INSERT_REG_DEED_DETLS="INSERT INTO IGRS_REG_TXN_DETLS(REG_TXN_ID,REGISTRATION_TXN_STATUS,DEED_ID,INSTRUMENTS_ID,CREATED_BY,CREATED_DATE,REF_VAL_TXN_ID,DUTY_TXN_ID,ADJUDICATION_FLAG) VALUES (?,?,?,?,?,sysdate,?,?,?)";//changes by Shreeraj
    public static final String GET_PROP_DETLS_FROM_VAL="SELECT MARKET_VALUE,AREA_ID,GOV_BODY_ID,PROP_TYPE_ID,PROP_L1_TYPE__ID,PROP_L2_TYPE__ID,AREA_UNIT_ID,AREA,DISTRICT_ID,TEHSIL_ID,WARD_PATWARI_ID,MOHALLA_ID,SYSTEM_MV FROM IGRS_PROP_VAL_DETAILS WHERE VAL_TXN_ID=?";
    public static final String INSERT_REG_PROPERTY_DETLS="INSERT INTO IGRS_REG_PROPRTY_DTLS(PROPERTY_ID,REG_TXN_ID,MARKET_VALUE,AREA_TYPE_ID,GOV_BODY_ID,PROP_TYPE_ID,L1_TYPE_ID,L2_TYPE_ID,AREA_UNIT_ID,AREA,DISTRICT_ID,TEHSIL_ID,WARD_ID,MOHALLA_ID,CREATED_BY,CREATED_DATE,VAL_TXN_ID,PROP_TXN_COMPL_FLAG,INITIAL_MARKET_VALUE,SYSTEM_MV) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,sysdate,?,?,?,?)";
    public static final String GET_APPLICANT_ROLE_ID="SELECT PARTY_TYPE_ID FROM IGRS_REG_TXN_PARTY_DETLS WHERE UPPER(IS_APPLICANT)='Y' AND REG_TXN_ID=?";
    public static final String INSERT_REG_PROP_TRANS_MAP="INSERT INTO IGRS_REG_INIT_PROP_TRANS_MAP(REG_TXN_ID,PROPERTY_ID,PARTY_TXN_ID,CREATED_BY,CREATED_DATE,MAPPING_TXN_ID) VALUES (?,?,?,?,sysdate,IGRS_REG_TRANS_PROP_MAP_ID_SEQ.NEXTVAL)";
    public static final String GET_SHARE_OF_PROPERTY_LIST="SELECT SHARE_OF_PROPERTY FROM IGRS_REG_TXN_PARTY_DETLS WHERE (UPPER(IS_APPLICANT)='Y' OR UPPER(IS_APPLICANT)='C' ) AND REG_TXN_ID=?";
    public static final String GET_PROP_DETLS_DASHBOARD="SELECT A.DISTRICT_ID,"+
														"DISTRICT_NAME,"+
														"A.TEHSIL_ID,"+
														"TEHSIL_NAME,"+
														"A.AREA_TYPE_ID,"+
														"AREA_TYPE_NAME,"+
														"A.WARD_ID,"+
														"WARD_PATWARI_NAME,"+
														"WARD_OR_PATWARI,"+
														"A.MOHALLA_ID,"+
														"MOHALLA_VILLAGE_NAME,"+
														"A.GOV_BODY_ID,"+
														"MUNICIPAL_BODY_NAME,"+
														"A.PROP_TYPE_ID,"+
														"PROPERTY_TYPE_NAME,"+
														"AREA,AREA_UNIT_ID, "+
														"H_DISTRICT_NAME, "+
														"H_TEHSIL_NAME, "+
														"H_AREA_TYPE_NAME, "+
														"H_WARD_PATWARI_NAME, "+
														"H_MOHALLA_VILLAGE_NAME, "+
														"H_MUNICIPAL_BODY_NAME, "+
														"H_PROPERTY_TYPE_NAME "+														
														"FROM IGRS_REG_PROPRTY_DTLS A, IGRS_DISTRICT_MASTER B, IGRS_TEHSIL_MASTER C,"+
														"IGRS_AREA_TYPE_MASTER D, IGRS_WARD_PATWARI_MASTER E, IGRS_MOHALLA_VILLAGE_MASTER F,"+
														"IGRS_MUNICIPAL_BODY_MASTER G, IGRS_PROPERTY_TYPE_MASTER H "+
														"WHERE B.DISTRICT_ID = A.DISTRICT_ID "+
														"AND C.TEHSIL_ID = A.TEHSIL_ID "+
														"AND D.AREA_TYPE_ID=A.AREA_TYPE_ID "+
														"AND E.WARD_PATWARI_ID=A.WARD_ID "+
														"AND F.MOHALLA_VILLAGE_ID=A.MOHALLA_ID "+
														"AND G.MUNICIPAL_BODY_ID=A.GOV_BODY_ID "+
														"AND H.PROPERTY_TYPE_ID=A.PROP_TYPE_ID "+
														"AND A.VAL_TXN_ID =?";
    public static final String GET_SUB_CLAUSE_LIST_NON_BUILDING="SELECT SUB_CLAUSE_ID FROM IGRS_PROP_SUBCLAUSE_VAL_DTLS WHERE VAL_TXN_ID=?";
    public static final String GET_SUB_CLAUSE_LIST_BUILDING="SELECT SUB_CLAUSE_ID FROM IGRS_PROP_SUBCLAUSE_VAL_DTLS WHERE VAL_TXN_ID=? AND FLOOR_TXN_ID=?";
    public static final String UPDATE_REG_INIT_PROP_DETLS = "UPDATE IGRS_REG_PROPRTY_DTLS SET VIKAS_KHAND = ?,RI_CIRCLE = ?,LAYOUT_DETAIL = ?,NAZOOL_SHEET_NUMBER = ?,PLOT_NUMBER = ?,PROPERTY_ADDRESS = ?,EAST_BOUNDARY = ?,WEST_BOUNDARY = ?,NORTH_BOUNDARY = ?,SOUTH_BOUNDARY = ?,UPDATE_BY = ?,UPDATE_DATE = sysdate,PROPERTY_LANDMARK=?,ANGLE_1_PATH=?,ANGLE_2_PATH=?,ANGLE_3_PATH=?,MAP_PATH=?,RIN_PATH=?,KHASRA_PATH=? WHERE REG_TXN_ID = ? AND PROPERTY_ID = ?";
    public static final String INSERT_REG_INIT_PROP_KHASRA_DETLS = "INSERT INTO IGRS_REG_PROP_KHASARA_DTLS(KHASRA_TXN_ID,PROPERTY_ID,KHASRA_NUMBER,RIN_PUSHTIKA_NUMBER,KHASRA_AREA,LAGAAN,CREATED_BY,CREATED_DATE) VALUES (IGRS_REG_KHASRA_TXN_ID_SEQ.NEXTVAL,?,?,?,?,?,?,sysdate)";
    public static final String INSERT_REG_EXEMPTION_DETLS = "INSERT INTO IGRS_REG_EXEMPTION_DETLS(TRANSACTION_ID,REG_TXN_ID,EXEMPTION_ID,CREATED_BY,CREATED_DATE) VALUES (IGRS_REG_EXEMP_ID_SEQ.NEXTVAL,?,?,?,sysdate)";
    public static final String GET_REG_INIT_DEED_INST_ID ="SELECT DEED_ID,INSTRUMENTS_ID,ADJUDICATION_FLAG,CANCELLATION_TYPE_FLAG FROM IGRS_REG_TXN_DETLS WHERE REG_TXN_ID=?";
    public static final String GET_REG_EXEMPTION_DETLS="SELECT EXEMPTION_ID FROM IGRS_REG_EXEMPTION_DETLS WHERE REG_TXN_ID=?";
    public static final String GET_PROPERTY_ID_MARKET_VALUE="select PROPERTY_ID,MARKET_VALUE from IGRS_REG_PROPRTY_DTLS where REG_TXN_ID=?";
    public static final String GET_TRANSACTING_PARTY_DETS="SELECT B.PARTY_TYPE_NAME,A.PARTY_FIRST_NAME,A.PARTY_LAST_NAME,A.AUTHRZD_PERSN_NAME,A.PARTY_TXN_ID,A.PARTY_TYPE_ID "+
														  "FROM IGRS_REG_TXN_PARTY_DETLS A,"+
														  "IGRS_PARTY_TYPE_MASTER B,"+
														  "IGRS_REG_INIT_PROP_TRANS_MAP C "+
														  "WHERE B.PARTY_TYPE_ID=A.PARTY_TYPE_ID "+
														  "AND C.PARTY_TXN_ID=A.PARTY_TXN_ID "+
														  "AND C.REG_TXN_ID=A.REG_TXN_ID "+
														  "AND C.REG_TXN_ID=? "+
														  "AND C.PROPERTY_ID=? ORDER BY A.PARTY_TXN_ID";
    public static final String GET_REG_INIT_DUTY_DETS="SELECT A.STAMP_DUTY,A.GRAM_DUTY,A.NAGAR_DUTY,A.UPKAR,A.REG_FEE,A.TOTAL,A.SHARE_VALUE,A.DUTY_ALREADY_PAID,A.REG_ALREADY_PAID "+ 
	  												  "FROM IGRS_PROP_STAMP_DUTY_DETAILS A,IGRS_REG_PROPRTY_DTLS B "+
	  												  "WHERE B.VAL_TXN_ID=A.VAL_TXN_ID "+
	  												  "AND B.REG_TXN_ID=?";
    public static final String GET_REF_VAL_ID_EXCHNG_DEED="SELECT REF_VAL_TXN_ID FROM IGRS_REG_TXN_DETLS WHERE REG_TXN_ID=?";
    public static final String GET_EXCHNG_DEED_FINAL_MV="SELECT A.MARKET_VALUE FROM IGRS_PROP_VAL_DETAILS A WHERE A.VAL_TXN_ID=?";
    public static final String INSERT_DUTIES_DETAILS="INSERT INTO IGRS_REG_INIT_STAMP_DUTY_DETLS(REG_INIT_DUTY_TXN_ID,REG_TXN_ID,STAMP_DUTY,GRAM_DUTY,NAGAR_DUTY,UPKAR,REG_FEE,TOTAL,CREATED_DATE,CREATED_BY,MARKET_VALUE_SHARE,DUTY_ALREADY_PAID,REG_ALREADY_PAID,SECURED_AMOUNT) VALUES(IGRS_REG_INIT_DUTY_ID_SEQ.NEXTVAL,?,?,?,?,?,?,?,sysdate,?,?,?,?,?)";
    public static final String GET_PENDING_APPLICATIONS_DETLS = "SELECT RD.REG_TXN_ID, RD.CREATED_DATE, DM.DEED_TYPE_NAME, SUBSTR (RD.REG_TXN_ID, length(RD.REG_TXN_ID)-5, length(RD.REG_TXN_ID)) as sequence, RD.REGISTRATION_TXN_STATUS FROM IGRS_DEED_TYPE_MASTER DM, IGRS_REG_TXN_DETLS RD WHERE (RD.ADJUDICATION_FLAG IS NULL OR RD.ADJUDICATION_FLAG IN ('R') ) AND DM.DEED_TYPE_ID = RD.DEED_ID AND REGISTRATION_TXN_STATUS in (1,2,3,4,5,6,9,10) AND (RD.CREATED_BY = ? OR RD.UPDATE_BY = ?) ORDER BY RD.CREATED_DATE DESC";
    public static final String GET_REG_INIT_PROP_VALUATION_ID ="SELECT VAL_TXN_ID from IGRS_REG_PROPRTY_DTLS where REG_TXN_ID=? AND PROPERTY_ID=?";
    public static final String GET_PROP_DETLS_DISPLAY="SELECT A.DISTRICT_ID,"+
													  "DISTRICT_NAME,"+
													  "A.TEHSIL_ID,"+
													  "TEHSIL_NAME,"+
													  "A.AREA_TYPE_ID,"+
													  "AREA_TYPE_NAME,"+
													  "A.WARD_ID,"+
													  "WARD_PATWARI_NAME,"+
													  "WARD_OR_PATWARI,"+
													  "A.MOHALLA_ID,"+
													  "MOHALLA_VILLAGE_NAME,"+
													  "A.GOV_BODY_ID,"+
													  "MUNICIPAL_BODY_NAME,"+
													  "A.PROP_TYPE_ID,"+
													  "PROPERTY_TYPE_NAME,"+
													  "AREA,AREA_UNIT_ID,A.VIKAS_KHAND,"+
													  "A.RI_CIRCLE,A.LAYOUT_DETAIL,A.NAZOOL_SHEET_NUMBER,"+
													  "A.PLOT_NUMBER,A.PROPERTY_ADDRESS,A.NORTH_BOUNDARY,"+
													  "A.SOUTH_BOUNDARY,A.EAST_BOUNDARY,A.WEST_BOUNDARY,A.PROPERTY_LANDMARK, "+
													  "A.ANGLE_1_PATH,A.ANGLE_2_PATH,A.ANGLE_3_PATH,A.MAP_PATH,A.RIN_PATH,A.KHASRA_PATH, "+
													  "A.MARKET_VALUE,A.L1_TYPE_ID,A.L2_TYPE_ID, "+
													  "H_DISTRICT_NAME,"+
													  "H_TEHSIL_NAME,"+
													  "H_AREA_TYPE_NAME,"+
													  "H_WARD_PATWARI_NAME,"+
													  "H_MOHALLA_VILLAGE_NAME,"+
													  "H_MUNICIPAL_BODY_NAME,"+
													  "H_PROPERTY_TYPE_NAME "+													  
													  "FROM IGRS_REG_PROPRTY_DTLS A, IGRS_DISTRICT_MASTER B, IGRS_TEHSIL_MASTER C,"+
													  "IGRS_AREA_TYPE_MASTER D, IGRS_WARD_PATWARI_MASTER E, IGRS_MOHALLA_VILLAGE_MASTER F,"+
													  "IGRS_MUNICIPAL_BODY_MASTER G, IGRS_PROPERTY_TYPE_MASTER H "+
													  "WHERE B.DISTRICT_ID = A.DISTRICT_ID "+
													  "AND C.TEHSIL_ID = A.TEHSIL_ID "+
													  "AND D.AREA_TYPE_ID=A.AREA_TYPE_ID "+
													  "AND E.WARD_PATWARI_ID=A.WARD_ID "+
													  "AND F.MOHALLA_VILLAGE_ID=A.MOHALLA_ID "+
													  "AND G.MUNICIPAL_BODY_ID=A.GOV_BODY_ID "+
													  "AND H.PROPERTY_TYPE_ID=A.PROP_TYPE_ID "+
													  "AND A.PROPERTY_ID =?";
    public static final String GET_PROP_KHASRA_DETLS_DISPLAY ="SELECT KHASRA_NUMBER,KHASRA_AREA,LAGAAN,RIN_PUSHTIKA_NUMBER "+
															  "FROM IGRS_REG_PROP_KHASARA_DTLS "+
															  "WHERE PROPERTY_ID=?";
    public static final String GET_PARTY_DETS="SELECT A.APPELLATE_TYPE_ID, B.APPELLATE_TYPE_NAME, A.PARTY_FIRST_NAME, "+
	 										  "A.PARTY_MIDDLE_NAME, A.PARTY_LAST_NAME, "+
	 										  "A.PARTY_GENDER, A.PARTY_AGE, "+
	 										  "A.NATIONALITY,C.COUNTRY_NAME, "+
	 										  "D.STATE_NAME,E.DISTRICT_NAME, "+
	 										  "A.PARTY_ADDRESS, A.POSTAL_CODE, "+
	 										  "A.PHONE_NUMBER, A.MOBILE_NUMBER, "+
	 										  "A.EMAIL_ID, A.PHOTO_PROOF_TYPE_ID, "+
	 										  "A.PHOTO_PROOF_ID, A.ORGANIZATION_NAME, "+
	 										  "A.AUTHRZD_PERSN_NAME, A.GUARDIAN_NAME, "+
	 										  "A.MOTHER_NAME, A.CATEGORY_ID, "+
	 										  "A.CATEGORY_ID, A.PARTY_TXN_ID, "+
	 										  "A.DISABILITY, A.DISABILITY_DESC, "+
	 										  "A.RELATION_WITH_OWNER, A.SHARE_OF_PROPERTY, "+
	 										  "A.PARTY_TYPE_ID, F.PARTY_TYPE_NAME,A.SPOUSE_NAME,A.OWNER_ID, "+
	 										  "A.OCCUPATION_ID, A.OCCUPATION_ID, A.COLLECTOR_PERMISSION_NUMBER, A.COLLECTOR_CERTIFICATE, A.MEMBER_MINORITY, A.BELOW_POVERTY_LINE, A.CATEGORY_ST_SCHEDULE_AREA, "+
	 										  "A.COLLECTOR_CERTIFICATE_PATH,A.PHOTO_PROOF_PATH,A.NOT_AFFD_EXEC_PATH,A.EXEC_PHOTO_PATH,A.NOT_AFFD_ATTR_PATH,A.ATTR_PHOTO_PATH,A.CLAIMNT_PHOTO_PATH,A.PAN_FORM_60_PATH, "+
	 										  "A.POA_SR_OFFICE_NAME,A.POA_REG_NO,A.POA_REG_DATE,A.DISTRICT_ID,A.ROLE_NAME,A.RELATION_TYPE_ID,A.UNIVERSAL_DEED_CLAIMANT_FLAG, "+
	 										  "A.AUTH_PER_COUNTRY_ID,A.AUTH_PER_STATE_ID,A.AUTH_PER_DISTRICT_ID,A.AUTH_PER_PARTY_ADDRESS "+
	 										  "FROM IGRS_REG_TXN_PARTY_DETLS A, "+
	 										  "IGRS_APPELLATE_TYPE_MASTER B, "+
	 										  "IGRS_COUNTRY_MASTER C, "+
	 										  "IGRS_STATE_MASTER D, "+
	 										  "IGRS_DISTRICT_MASTER E, "+
	 										  "IGRS_PARTY_TYPE_MASTER F "+
	 										  "WHERE A.APPELLATE_TYPE_ID=B.APPELLATE_TYPE_ID "+
	 										  "AND A.COUNTRY_ID=C.COUNTRY_ID "+
	 										  "AND A.STATE_ID=D.STATE_ID "+
	 										  "AND A.DISTRICT_ID=E.DISTRICT_ID "+
	 										  "AND A.PARTY_TYPE_ID=F.PARTY_TYPE_ID "+
	 										  "AND REG_TXN_ID=? "+ 
	 										  "AND PARTY_TXN_ID=? ";
    public static final String GET_OWNER_DETAILS="SELECT PARTY_FIRST_NAME,PARTY_GENDER,PARTY_AGE,NATIONALITY,PARTY_ADDRESS,MOBILE_NUMBER,EMAIL_ID,PHOTO_PROOF_TYPE_ID,PHOTO_PROOF_ID,ORGANIZATION_NAME,AUTHRZD_PERSN_NAME FROM IGRS_REG_TXN_PARTY_DETLS WHERE PARTY_TXN_ID=?";
    public static final String GET_SAVED_AAPLICANT_DETLS = "SELECT REG_TXN_ID,APPELLATE_TYPE_ID,PARTY_FIRST_NAME,"+
    													   "PARTY_MIDDLE_NAME,PARTY_LAST_NAME,PARTY_GENDER,"+
    													   "PARTY_AGE,NATIONALITY,COUNTRY_ID,"+
    														"STATE_ID,DISTRICT_ID,PARTY_ADDRESS,"+
    														"POSTAL_CODE,PHONE_NUMBER,MOBILE_NUMBER,"+
    														"EMAIL_ID,PHOTO_PROOF_TYPE_ID,PHOTO_PROOF_ID,"+
    														"ORGANIZATION_NAME,AUTHRZD_PERSN_NAME,"+
    														"GUARDIAN_NAME,MOTHER_NAME,CATEGORY_ID,"+
    														"PARTY_TXN_ID,DISABILITY,RELATION_WITH_OWNER,"+
    														"SHARE_OF_PROPERTY,PARTY_TYPE_ID,SPOUSE_NAME,"+
    														"OWNER_ID,DISABILITY_DESC,OCCUPATION_ID,"+
    														"COLLECTOR_PERMISSION_NUMBER,COLLECTOR_CERTIFICATE_PATH,"+
    														"MEMBER_MINORITY,BELOW_POVERTY_LINE,"+
    														"CATEGORY_ST_SCHEDULE_AREA,PHOTO_PROOF_PATH,NOT_AFFD_EXEC_PATH,EXEC_PHOTO_PATH,NOT_AFFD_ATTR_PATH, "+
    														"ATTR_PHOTO_PATH,CLAIMNT_PHOTO_PATH,PAN_FORM_60_PATH,POA_SR_OFFICE_NAME,POA_REG_NO,POA_REG_DATE, "+
    														"ROLE_NAME,RELATION_TYPE_ID,UNIVERSAL_DEED_CLAIMANT_FLAG,AUTH_PER_COUNTRY_ID,AUTH_PER_STATE_ID,AUTH_PER_DISTRICT_ID,AUTH_PER_PARTY_ADDRESS "+
    														"FROM IGRS_REG_TXN_PARTY_DETLS WHERE UPPER(IS_APPLICANT)='Y' and  REG_TXN_ID=?";
    public static final String GET_APPLICANT_SHARE_HOLDERS="SELECT REG_TXN_ID,APPELLATE_TYPE_ID,PARTY_FIRST_NAME,"+
	   														"PARTY_MIDDLE_NAME,PARTY_LAST_NAME,PARTY_GENDER,"+
	   														"PARTY_AGE,NATIONALITY,COUNTRY_ID,"+
	   														"STATE_ID,DISTRICT_ID,PARTY_ADDRESS,"+
	   														"POSTAL_CODE,PHONE_NUMBER,MOBILE_NUMBER,"+
	   														"EMAIL_ID,PHOTO_PROOF_TYPE_ID,PHOTO_PROOF_ID,"+
	   														"ORGANIZATION_NAME,AUTHRZD_PERSN_NAME,"+
	   														"GUARDIAN_NAME,MOTHER_NAME,CATEGORY_ID,"+
	   														"PARTY_TXN_ID,DISABILITY,RELATION_WITH_OWNER,"+
	   														"SHARE_OF_PROPERTY,PARTY_TYPE_ID,SPOUSE_NAME,"+
	   														"OWNER_ID,DISABILITY_DESC,OCCUPATION_ID,"+
	   														"COLLECTOR_PERMISSION_NUMBER,COLLECTOR_CERTIFICATE_PATH,"+
	   														"MEMBER_MINORITY,BELOW_POVERTY_LINE,"+
	   														"CATEGORY_ST_SCHEDULE_AREA,PHOTO_PROOF_PATH,NOT_AFFD_EXEC_PATH,EXEC_PHOTO_PATH,NOT_AFFD_ATTR_PATH, "+
    														"ATTR_PHOTO_PATH,CLAIMNT_PHOTO_PATH,PAN_FORM_60_PATH,POA_SR_OFFICE_NAME,POA_REG_NO,POA_REG_DATE, "+
    														"ROLE_NAME,RELATION_TYPE_ID,UNIVERSAL_DEED_CLAIMANT_FLAG,AUTH_PER_COUNTRY_ID,AUTH_PER_STATE_ID,AUTH_PER_DISTRICT_ID,AUTH_PER_PARTY_ADDRESS "+
	   														"FROM IGRS_REG_TXN_PARTY_DETLS WHERE UPPER(IS_APPLICANT)='C' and  REG_TXN_ID=?";
    public static final String GET_ALL_VALUATION_IDS_EXCHANGE="SELECT VAL_TXN_ID FROM IGRS_PROP_VAL_DETAILS WHERE REF_VAL_TXN_ID=? ORDER BY VAL_TXN_ID ASC";
    public static final String GET_ALL_PROPERTY_DETLS_EXCHANGE="SELECT VAL_TXN_ID,DISTRICT_ID,TEHSIL_ID,MARKET_VALUE,PARTY_TYPE FROM IGRS_PROP_VAL_DETAILS WHERE VAL_TXN_ID=?";
  //FOLLOWING QUERIES FOR DELETING PARTIAL SAVED APPLICATIONS FROM DASHBOARD
    public static final String DEL_REG_INIT_TRANS_DETLS ="delete from IGRS_REG_TXN_PARTY_DETLS where REG_TXN_ID =";
    public static final String DEL_REG_INIT_PROP_DETLS ="delete from IGRS_REG_PROPRTY_DTLS where REG_TXN_ID =";
    public static final String DEL_REG_INIT_MAP_DETLS ="delete from IGRS_REG_INIT_PROP_TRANS_MAP where REG_INIT_TXN_ID =";
    public static final String DEL_REG_INIT_DEED_DETLS ="delete from IGRS_REG_TXN_DETLS where REG_TXN_ID =";
    public static final String DEL_REG_INIT_EXEMP_DETLS ="delete from IGRS_REG_EXEMPTION_DETLS where REG_TXN_ID =";
    public static final String DEL_REG_INIT_PROP_KHASRA_DETLS ="delete from IGRS_REG_PROP_KHASARA_DTLS where PROPERTY_ID IN (SELECT PROPERTY_ID FROM IGRS_REG_PROPRTY_DTLS WHERE REG_TXN_ID=?)";
    public static final String DEL_REG_INIT_TXN_DETLS ="UPDATE IGRS_REG_TXN_DETLS SET REGISTRATION_TXN_STATUS=100 WHERE REG_TXN_ID=?";
    //
    public static final String GET_APPLICANT_REG_DETLS="select FIRST_NAME,MIDDLE_NAME,LAST_NAME,GENDER,NATIONALITY,COUNTRY_ID,STATE_ID,DISTRICT_ID,ADDRESS,POSTAL_CODE,PHONE_NUMBER,MOBILE_NUMBER,EMAIL_ID,PHOTO_PROOF_TYPE_ID,PHOTO_PROOF_ID,GUARDIAN_NAME,MOTHER_NAME,SPOUSE_NAME,AGE,CATEGORY_ID,OCCUPATION from IGRS_USER_REG_DETAILS where user_id=?";
    public static final String GET_OCCUPATION_LIST = "SELECT O.OCCUPATION_ID,O.OCCUPATION_NAME FROM IGRS_OCCUPATION_MASTER O ORDER BY O.OCCUPATION_ID ASC";
    public static final String GET_OCCUPATION_NAME="SELECT OCCUPATION_NAME FROM IGRS_OCCUPATION_MASTER WHERE OCCUPATION_ID=?";
    public static final String GET_APPLICANT_SHARE="SELECT SHARE_OF_PROPERTY FROM IGRS_REG_TXN_PARTY_DETLS WHERE IS_APPLICANT='Y' AND REG_TXN_ID=?";
    public static final String GET_PARTY_TXN_ID_LIST="select PARTY_TXN_ID from IGRS_REG_INIT_PROP_TRANS_MAP where PROPERTY_ID=?";
    public static final String GET_PARTY_DETAILS_PDF="SELECT REG_TXN_ID,APPELLATE_TYPE_ID,PARTY_FIRST_NAME,"+
													 "PARTY_MIDDLE_NAME,PARTY_LAST_NAME,PARTY_GENDER,"+
													 "PARTY_AGE,NATIONALITY,COUNTRY_ID,"+
													 "STATE_ID,DISTRICT_ID,PARTY_ADDRESS,"+
													 "POSTAL_CODE,PHONE_NUMBER,MOBILE_NUMBER,"+
													 "EMAIL_ID,PHOTO_PROOF_TYPE_ID,PHOTO_PROOF_ID,"+
													 "ORGANIZATION_NAME,AUTHRZD_PERSN_NAME,"+
													 "GUARDIAN_NAME,MOTHER_NAME,CATEGORY_ID,"+
													 "PARTY_TXN_ID,DISABILITY,RELATION_WITH_OWNER,"+
													 "SHARE_OF_PROPERTY,PARTY_TYPE_ID,SPOUSE_NAME,"+
													 "OWNER_ID,DISABILITY_DESC,OCCUPATION_ID,"+
													 "COLLECTOR_PERMISSION_NUMBER,COLLECTOR_CERTIFICATE_PATH,"+
													 "MEMBER_MINORITY,BELOW_POVERTY_LINE,"+
													 "CATEGORY_ST_SCHEDULE_AREA,PHOTO_PROOF_PATH,NOT_AFFD_EXEC_PATH,EXEC_PHOTO_PATH,NOT_AFFD_ATTR_PATH, "+
													 "ATTR_PHOTO_PATH,CLAIMNT_PHOTO_PATH,PAN_FORM_60_PATH,POA_SR_OFFICE_NAME,POA_REG_NO,POA_REG_DATE,RELATION_TYPE_ID,AUTH_PER_COUNTRY_ID,AUTH_PER_STATE_ID,AUTH_PER_DISTRICT_ID,AUTH_PER_PARTY_ADDRESS "+
													 "FROM IGRS_REG_TXN_PARTY_DETLS WHERE PARTY_TXN_ID=?";
    public static final String GET_GUIDELINE_RATE_WITH_L2="SELECT A.GUIDELINE_VALUE FROM IGRS_GUIDELINE_MASTER_CHILD2 A, IGRS_GUIDELINE_MASTER_CHILD1 B, IGRS_GUIDELINE_MASTER_PARENT C "+
    													  "WHERE C.DISTRICT_ID=? AND C.GUIDELINE_ID=B.GUIDELINE_ID AND B.TEHSIL_ID=? AND B.WARD_PATWARI_ID=? AND B.MOHALLA_VILLAGE_ID=? "+ 
    													  "AND B.GUIDELINE_CHILD1_ID=A.GUIDELINE_CHILD1_ID AND A.PROPERTY_TYPE_ID=? AND A.PROPERTY_TYPE_L1_ID=? AND A.PROPERTY_TYPE_L2_ID=?";
    public static final String GET_GUIDELINE_RATE_WITHOUT_L2="SELECT A.GUIDELINE_VALUE FROM IGRS_GUIDELINE_MASTER_CHILD2 A, IGRS_GUIDELINE_MASTER_CHILD1 B, IGRS_GUIDELINE_MASTER_PARENT C "+
	  															"WHERE C.DISTRICT_ID=? AND C.GUIDELINE_ID=B.GUIDELINE_ID AND B.TEHSIL_ID=? AND B.WARD_PATWARI_ID=? AND B.MOHALLA_VILLAGE_ID=? "+ 
	  															"AND B.GUIDELINE_CHILD1_ID=A.GUIDELINE_CHILD1_ID AND A.PROPERTY_TYPE_ID=? AND A.PROPERTY_TYPE_L1_ID=?";
    //BELOW ADDED BY ROOPAM FOR TITLE DEED
    public static final String SELECT_DEED_ID="select DEED_ID FROM IGRS_PROP_STAMP_DUTY_DETAILS WHERE DUTY_TXN_ID=?";
    public static final String SELECT_INSTRUMENT_ID="select INSTRUMENT_ID FROM IGRS_PROP_STAMP_DUTY_DETAILS WHERE DUTY_TXN_ID=?";
    public static final String SELECT_PROPERTY_TYPE_L2_DETAILS="SELECT PROPERTY_TYPE_L2_ID,PROPERTY_TYPE_L2_DESC FROM IGRS_PROP_TYPE_L2_MASTER WHERE PROPERTY_TYPE_L1_ID=? AND PROPERTY_TYPE_L2_STATUS='A'";
    public static final String SELECT_UNIT_LIST_DETAILS="SELECT A.UOM_ID,A.UOM_NAME FROM IGRS_UOM_MASTER A, IGRS_PROP_TYPE_L1_MASTER B WHERE A.UOM_ID=B.UOM_ID AND B.PROPERTY_TYPE_L1_ID=?";
    public static final String GET_PROPERTY_TYPE_NAME="SELECT PROPERTY_TYPE_NAME FROM IGRS_PROPERTY_TYPE_MASTER WHERE PROPERTY_TYPE_ID=?";
    public static final String INSERT_REG_PROP_DETLS_NON_PROP_DEEDS = "INSERT INTO IGRS_REG_PROPRTY_DTLS(PROPERTY_ID,REG_TXN_ID,VIKAS_KHAND,RI_CIRCLE,LAYOUT_DETAIL,NAZOOL_SHEET_NUMBER,PLOT_NUMBER,PROPERTY_ADDRESS,EAST_BOUNDARY,WEST_BOUNDARY,NORTH_BOUNDARY,SOUTH_BOUNDARY,PROPERTY_LANDMARK,  AREA_TYPE_ID ,  GOV_BODY_ID ,  PROP_TYPE_ID ,  L1_TYPE_ID ,  L2_TYPE_ID ,  AREA_UNIT_ID ,  AREA ,  PROP_TXN_COMPL_FLAG ,  DISTRICT_ID ,  TEHSIL_ID,  WARD_ID ,  MOHALLA_ID ,  CREATED_BY ,  CREATED_DATE,ANGLE_1_PATH,ANGLE_2_PATH,ANGLE_3_PATH,MAP_PATH,RIN_PATH,KHASRA_PATH) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,sysdate,?,?,?,?,?,?)";
    public static final String INSERT_REG_PROP_FLOOR_DETLS = "INSERT INTO IGRS_REG_FLOOR_DETAILS(FLOOR_TXN_ID,PROPERTY_ID,L1_TYPE_ID,L2_TYPE_ID,FLOOR_TYPE_ID,CONSTRUCTED_AREA,AREA,AREA_UNIT_ID,CREATED_BY,CREATED_DATE) VALUES(IGRS_REG_FLOOR_DETLS_SEQ.NEXTVAL,?,?,?,?,?,?,?,?,sysdate)";
    public static final String GET_PROPERTY_ID_LIST_NON_PROP_DEED="select PROPERTY_ID from IGRS_REG_PROPRTY_DTLS where REG_TXN_ID=?";
    public static final String GET_TRANS_PARTY_DETS_NON_PROP_DEED="SELECT B.PARTY_TYPE_NAME,A.PARTY_FIRST_NAME,A.PARTY_LAST_NAME,A.AUTHRZD_PERSN_NAME,A.PARTY_TXN_ID,A.PARTY_TYPE_ID "+
	  													  "FROM IGRS_REG_TXN_PARTY_DETLS A,"+
	  													  "IGRS_PARTY_TYPE_MASTER B "+
	  													  "WHERE B.PARTY_TYPE_ID=A.PARTY_TYPE_ID AND IS_APPLICANT IN ('Y','N','C') "+
	  													  "AND A.REG_TXN_ID=? "+
	  													  "ORDER BY A.PARTY_TXN_ID";
    public static final String GET_REG_NON_PROP_DUTY_DETS="SELECT A.STAMP_DUTY,A.GRAM_DUTY,A.NAGAR_DUTY,A.UPKAR,A.REG_FEE,A.TOTAL "+ 
	  														"FROM IGRS_PROP_STAMP_DUTY_DETAILS A "+
	  														"WHERE A.DUTY_TXN_ID=?";
    public static final String GET_BUILDING_FLOOR_DETAILS_NON_PROP="SELECT FLOOR_TXN_ID,L1_TYPE_ID,L2_TYPE_ID,A.FLOOR_TYPE_ID,A.AREA_UNIT_ID,AREA,CONSTRUCTED_AREA,"+
	  															   "B.PROPERTY_TYPE_L1_NAME,C.PROPERTY_TYPE_L2_NAME,D.FLOOR_NAME,E.UOM_NAME "+
	  															   "FROM IGRS_REG_FLOOR_DETAILS A,"+
	  															   "IGRS_PROP_TYPE_L1_MASTER B,"+
	  															   "IGRS_PROP_TYPE_L2_MASTER C,"+
	  															   "IGRS_FLOOR_MASTER D, "+
	  															   "IGRS_UOM_MASTER E "+
	  															   "WHERE B.PROPERTY_TYPE_L1_ID=A.L1_TYPE_ID "+
	  															   "AND C.PROPERTY_TYPE_L2_ID=A.L2_TYPE_ID "+
	  															   "AND D.FLOOR_ID=A.FLOOR_TYPE_ID "+
	  															   "AND E.UOM_ID=A.AREA_UNIT_ID AND A.PROPERTY_ID=?";
    public static final String GET_REG_PAYMENT_TXN_ID_SEQ="SELECT IGRS_REG_PAYMNT_TXN_ID_SEQ.NEXTVAL FROM DUAL";
    public static final String GET_REG_INIT_PAYMENT_FLAG ="SELECT PAYMENT_FLAG,TXN_ID from IGRS_REG_PAYMENT_DETLS where CREATED_DATE=(SELECT MAX(CREATED_DATE) FROM IGRS_REG_PAYMENT_DETLS WHERE REG_TXN_ID=?) AND REG_TXN_ID=?";
    public static final String INSERT_REG_INIT_PAYMENT_DETLS ="INSERT INTO IGRS_REG_PAYMENT_DETLS(TXN_ID,REG_TXN_ID,CREATED_BY,CREATED_DATE,PAYMENT_FLAG,PAYABLE_AMOUNT,SOURCE_MOD_FLAG,PAYMENT_TYPE_ID) VALUES(?,?,?,sysdate,?,?,?,?)";
    public static final String GET_ALL_PAID_AMOUNTS="select PAID_AMOUNT from IGRS_REG_PAYMENT_DETLS where PAYMENT_FLAG IN ('P','C') AND REG_TXN_ID=?";
    public static final String GET_REG_INIT_PAYMENT_TXN_ID ="SELECT PAYMENT_TXN_ID,PAID_AMOUNT,PAYABLE_AMOUNT FROM IGRS_REG_PAYMENT_DETLS WHERE CREATED_DATE=(SELECT MAX(CREATED_DATE) FROM IGRS_REG_PAYMENT_DETLS WHERE REG_TXN_ID=?) AND REG_TXN_ID=?";
    public static final String GET_REG_DIST_ID ="SELECT DISTRICT_ID FROM IGRS_REG_PROPRTY_DTLS WHERE CREATED_DATE=(SELECT MIN(CREATED_DATE) FROM IGRS_REG_PROPRTY_DTLS WHERE REG_TXN_ID=?) AND REG_TXN_ID=?";
    public static final String INSERT_REG_ESTAMP_MAP_DETLS = "INSERT INTO IGRS_REG_ESTAMP_MAP(TRANSACTION_ID,ESTAMP_TXN_ID,REG_TXN_ID,CREATED_BY,CREATED_DATE) VALUES(IGRS_REG_ESTAMP_MAP_ID_SEQ.NEXTVAL,?,?,?,sysdate)";
    public static final String UPDATE_PAYMENT_FLAG="UPDATE IGRS_REG_PAYMENT_DETLS SET PAYMENT_FLAG=? WHERE REG_TXN_ID=?";
    public static final String GET_BANK_DETLS="SELECT BANK_NAME_DEPOSIT_DEED,BRANCH_NAME_DEPOSIT_DEED,BANK_ADDRESS_DEPOSIT_DEED,BANK_AUTH_PERSON_DEPOSIT_DEED,LOAN_AMOUNT,SANCTIONED_AMOUNT,"
    											+"TRUST_NAME,TRUST_DATE,RENT,ADVANCE,DEVELOPMENT_CHARGE,OTHER_REC_CHARGE_PAID,PREMIUM,TERM_OF_LEASE,WITH_POSSESSION,SEC_LOAN_AMT,PARTY_FIRST_NAME,"
    											+"PARTY_MIDDLE_NAME,PARTY_LAST_NAME,PARTY_GENDER,PARTY_AGE,GUARDIAN_NAME,MOTHER_NAME,SPOUSE_NAME,NATIONALITY,PARTY_ADDRESS,COUNTRY_ID,STATE_ID,"
    											+"DISTRICT_ID,PHONE_NUMBER,MOBILE_NUMBER,EMAIL_ID,CATEGORY_ID,DISABILITY,DISABILITY_DESC,PHOTO_PROOF_TYPE_ID,PHOTO_PROOF_ID,ADVANCE_PAYMNT_DATE,POSSESION_GIVEN,POA_WITH_CONSIDRTN,POA_PERIOD,PAID_LOAN_AMT,CONTRIBUTORY_PROP,DISSOLUTION_DATE,RETIRMENT_DATE FROM IGRS_REG_DEEDS_EXTRA_DTLS WHERE REG_TXN_ID=?";
    public static final String UPDATE_REG_INIT_TXN_STATUS = "UPDATE IGRS_REG_TXN_DETLS SET REGISTRATION_TXN_STATUS=? WHERE REG_TXN_ID=?";
    public static final String GET_PARTY_IDS_EXCHNG_PDF="SELECT PARTY_TXN_ID FROM IGRS_REG_TXN_PARTY_DETLS WHERE IS_APPLICANT IN ('Y','N','C') AND PARTY_TYPE_ID IN (?,?) AND REG_TXN_ID=?";
    public static final String GET_PROP_IDS_EXCHNG_PDF="SELECT DISTINCT(PROPERTY_ID) FROM IGRS_REG_INIT_PROP_TRANS_MAP WHERE PARTY_TXN_ID IN(SELECT PARTY_TXN_ID FROM IGRS_REG_TXN_PARTY_DETLS WHERE PARTY_TYPE_ID IN (?,?) AND REG_TXN_ID=?) AND REG_TXN_ID=?";
    public static final String GET_PARTY_TXN_ID_LIST_TITLE_DEED="select PARTY_TXN_ID from IGRS_REG_TXN_PARTY_DETLS where IS_APPLICANT IN ('Y','C','N') AND REG_TXN_ID=?";
    public static final String GET_CONSID_AMNT_SYS_MV ="SELECT CONSIDER_AMOUNT,SYSTEM_MV from IGRS_PROP_VAL_DETAILS where VAL_TXN_ID=?";
    public static final String GET_CONSID_AMNT_TITLE_DEED ="SELECT USER_ENTERED_VAL FROM IGRS_STAMP_DUTY_DETAILS A, IGRS_REG_TXN_DETLS B WHERE A.DUTY_TXN_ID=B.DUTY_TXN_ID AND B.REG_TXN_ID=?";
    public static final String GET_BUILDING_FLOOR_DETAILS_TITLE_DEED="SELECT FLOOR_TXN_ID,L1_TYPE_ID,L2_TYPE_ID,FLOOR_TYPE_ID,AREA_UNIT_ID,AREA,CONSTRUCTED_AREA,"+
	  																	"B.PROPERTY_TYPE_L1_NAME,C.PROPERTY_TYPE_L2_NAME,D.FLOOR_NAME,E.UOM_NAME "+
	  																	"FROM IGRS_REG_FLOOR_DETAILS A,"+
	  																	"IGRS_PROP_TYPE_L1_MASTER B,"+
	  																	"IGRS_PROP_TYPE_L2_MASTER C,"+
	  																	"IGRS_FLOOR_MASTER D, IGRS_UOM_MASTER E "+
	  																	"WHERE B.PROPERTY_TYPE_L1_ID=A.L1_TYPE_ID "+
	  																	"AND C.PROPERTY_TYPE_L2_ID=A.L2_TYPE_ID "+
	  																	"AND D.FLOOR_ID=A.FLOOR_TYPE_ID AND E.UOM_ID=A.AREA_UNIT_ID "+
	  																	"AND PROPERTY_ID=?";
    public static final String GET_PAYMENT_DETLS_DISPLAY ="SELECT B.PAYMENT_MODE_ID,A.PAYMENT_MODE,B.PAYMENT_TXN_ID,B.PAID_AMOUNT,B.CREATED_DATE FROM IGRS_PAYMENT_MODE_MASTER A,IGRS_REG_PAYMENT_DETLS B WHERE B.PAYMENT_MODE_ID=A.PAYMENT_MODE_ID AND B.PAYMENT_FLAG='C' AND B.REG_TXN_ID=?";
    public static final String UPDATE_REG_TXN_PARTY_NEW = "UPDATE IGRS_REG_TXN_PARTY_DETLS SET PARTY_FIRST_NAME=?,"+
    														"PARTY_MIDDLE_NAME=?, PARTY_LAST_NAME=?,  PARTY_GENDER=?,"+
    														"PARTY_AGE=?, NATIONALITY=?, DISTRICT_ID=?,"+
    														"PARTY_ADDRESS=?, POSTAL_CODE=?, PHONE_NUMBER=?,"+
    														"MOBILE_NUMBER=?, EMAIL_ID=?, PHOTO_PROOF_TYPE_ID=?,"+
    														"PHOTO_PROOF_ID=?, ORGANIZATION_NAME=?, AUTHRZD_PERSN_NAME=?,"+
    														"GUARDIAN_NAME=?, MOTHER_NAME=?, CATEGORY_ID=?,"+
    														"OCCUPATION_ID=?, DISABILITY=?, RELATION_WITH_OWNER=?,"+
    														"UPDATE_BY=?, UPDATE_DATE=sysdate, SPOUSE_NAME=?,"+
    														"DISABILITY_DESC=?, MEMBER_MINORITY=?, BELOW_POVERTY_LINE=?,"+
    														"CATEGORY_ST_SCHEDULE_AREA=?,COLLECTOR_PERMISSION_NUMBER=?,COLLECTOR_CERTIFICATE_PATH=?,"+
    														"PHOTO_PROOF_PATH=?,NOT_AFFD_EXEC_PATH=?,EXEC_PHOTO_PATH=?,"+
    														"NOT_AFFD_ATTR_PATH=?,ATTR_PHOTO_PATH=?,CLAIMNT_PHOTO_PATH=?,"+
    														"PAN_FORM_60_PATH=?,POA_SR_OFFICE_NAME=?,POA_REG_NO=?,POA_REG_DATE =?,RELATION_TYPE_ID=?,AUTH_PER_COUNTRY_ID=?,AUTH_PER_STATE_ID=?,AUTH_PER_DISTRICT_ID=?,AUTH_PER_PARTY_ADDRESS=? "+
    														"WHERE REG_TXN_ID=? AND PARTY_TXN_ID=?";
    public static final String UPDATE_OWNER_DETAILS="UPDATE IGRS_REG_TXN_PARTY_DETLS SET APPELLATE_TYPE_ID=?,"+
    												"PARTY_FIRST_NAME=?,PARTY_GENDER=?,PARTY_AGE=?,NATIONALITY=?,"+
    												"PARTY_ADDRESS=?,MOBILE_NUMBER=?,EMAIL_ID=?,PHOTO_PROOF_TYPE_ID=?,"+
    												"PHOTO_PROOF_ID=?,ORGANIZATION_NAME=?,AUTHRZD_PERSN_NAME=?,"+
    												"UPDATE_BY=?,UPDATE_DATE=sysdate "+
    												"where REG_TXN_ID=? and PARTY_TXN_ID=?";
    public static final String DELETE_REG_INIT_PROP_KHASRA_DETLS = "DELETE FROM IGRS_REG_PROP_KHASARA_DTLS WHERE PROPERTY_ID=?";
    public static final String GET_ESTAMP_CODE ="SELECT A.ESTAMP_CODE FROM IGRS_ESTAMP_DETLS A, IGRS_REG_ESTAMP_MAP B WHERE A.ESTAMP_TXN_ID=B.ESTAMP_TXN_ID AND B.REG_TXN_ID=?";
    public static final String GET_PENDING_APP_STATUS ="SELECT REGISTRATION_TXN_STATUS,ADJUDICATION_FLAG from IGRS_REG_TXN_DETLS where REG_TXN_ID=?";
    public static final String GET_PROPERTY_ID_OF_APPLICANT ="SELECT B.PROPERTY_ID, C.VAL_TXN_ID FROM IGRS_REG_TXN_PARTY_DETLS A, IGRS_REG_INIT_PROP_TRANS_MAP B, IGRS_REG_PROPRTY_DTLS C WHERE C.PROPERTY_ID=B.PROPERTY_ID AND B.PARTY_TXN_ID=A.PARTY_TXN_ID AND A.IS_APPLICANT='Y' AND A.REG_TXN_ID=?";
    public static final String GET_LATEST_PROPERTY_ID="SELECT A.PROPERTY_ID, A.VAL_TXN_ID FROM IGRS_REG_PROPRTY_DTLS A WHERE A.CREATED_DATE=(SELECT MAX(B.CREATED_DATE) FROM IGRS_REG_PROPRTY_DTLS B WHERE  B.REG_TXN_ID=? ) AND A.REG_TXN_ID=?";
    public static final String GET_ALL_PROPERTY_DETLS_EXCHANGE_DASH="SELECT B.PROPERTY_ID,B.VAL_TXN_ID,B.MARKET_VALUE,A.PARTY_TYPE FROM IGRS_PROP_VAL_DETAILS A,IGRS_REG_PROPRTY_DTLS B  WHERE B.VAL_TXN_ID=A.VAL_TXN_ID AND A.VAL_TXN_ID=?";
    public static final String GET_REMAINING_VALUATION_IDS_EXCHANGE_DASH="SELECT A.VAL_TXN_ID FROM IGRS_PROP_VAL_DETAILS A,IGRS_REG_PROPRTY_DTLS B WHERE B.VAL_TXN_ID=A.VAL_TXN_ID AND B.NORTH_BOUNDARY IS NULL AND REF_VAL_TXN_ID=? ORDER BY VAL_TXN_ID ASC";
    public static final String GET_DUTY_TXN_ID ="SELECT DUTY_TXN_ID FROM IGRS_REG_TXN_DETLS WHERE REG_TXN_ID=?";
    public static final String GET_APPLICANT_ADDRESS="SELECT DISTRICT_ID,PARTY_ADDRESS,COUNTRY_ID,STATE_ID FROM IGRS_REG_TXN_PARTY_DETLS WHERE IS_APPLICANT='Y' AND REG_TXN_ID=?";
    public static final String UPDATE_REG_INIT_TXN_STATUS_WITH_ADDRESS = "UPDATE IGRS_REG_TXN_DETLS SET REGISTRATION_TXN_STATUS=?,POSTAL_COUNTRY_ID=?,POSTAL_STATE_ID=?,POSTAL_DISTRICT_ID=?,POSTAL_ADDRESS=? WHERE REG_TXN_ID=?";
    public static final String UPDATE_BANK_DTLS="UPDATE IGRS_REG_DEEDS_EXTRA_DTLS SET BANK_NAME_DEPOSIT_DEED=?,BRANCH_NAME_DEPOSIT_DEED=?,BANK_ADDRESS_DEPOSIT_DEED=?,BANK_AUTH_PERSON_DEPOSIT_DEED=?,LOAN_AMOUNT=?,SANCTIONED_AMOUNT=?,UPDATE_BY=?,UPDATE_DATE=SYSDATE,TRUST_NAME=?,TRUST_DATE=?,RENT=?,ADVANCE=?,DEVELOPMENT_CHARGE=?,OTHER_REC_CHARGE_PAID=?,PREMIUM=?,TERM_OF_LEASE=?,WITH_POSSESSION=?,SEC_LOAN_AMT=?,"
    										+"PARTY_FIRST_NAME=?,PARTY_MIDDLE_NAME=?,PARTY_LAST_NAME=?,PARTY_GENDER=?,PARTY_AGE=?,GUARDIAN_NAME=?,MOTHER_NAME=?,SPOUSE_NAME=?,NATIONALITY=?,PARTY_ADDRESS=?,COUNTRY_ID=?,STATE_ID=?,DISTRICT_ID=?,PHONE_NUMBER=?,MOBILE_NUMBER=?,EMAIL_ID=?,CATEGORY_ID=?,DISABILITY=?,DISABILITY_DESC=?,PHOTO_PROOF_TYPE_ID=?,PHOTO_PROOF_ID=?,ADVANCE_PAYMNT_DATE=?,POSSESION_GIVEN=?,POA_WITH_CONSIDRTN=?,POA_PERIOD=?,PAID_LOAN_AMT=?,CONTRIBUTORY_PROP=?,DISSOLUTION_DATE=?,RETIRMENT_DATE=? WHERE REG_TXN_ID=?";
    public static final String INSERT_REG_TXN_DETLS="INSERT INTO IGRS_REG_TXN_DETLS(REG_TXN_ID,REGISTRATION_TXN_STATUS,DEED_ID,INSTRUMENTS_ID,CREATED_BY,CREATED_DATE,REF_VAL_TXN_ID,DUTY_TXN_ID,CANCELLATION_TYPE_FLAG,ADJUDICATION_FLAG) VALUES (?,?,?,?,?,sysdate,?,?,?,?)";
    public static final String GET_PARTY_TXN_IDS_FOR_PROP_MAP = "SELECT PARTY_TXN_ID FROM IGRS_REG_TXN_PARTY_DETLS WHERE ((PARTY_TXN_ID NOT IN (SELECT UNIQUE PARTY_TXN_ID FROM IGRS_REG_INIT_PROP_TRANS_MAP WHERE REG_TXN_ID=?) AND IS_APPLICANT NOT IN ('O')) OR IS_APPLICANT IN ('Y','C')) AND REG_TXN_ID=?";
    public static final String GET_PARTY_TXN_IDS_FOR_PROP_MAP_TRUST_NPV_NP = "SELECT PARTY_TXN_ID FROM IGRS_REG_TXN_PARTY_DETLS WHERE ((PARTY_TXN_ID NOT IN (SELECT UNIQUE PARTY_TXN_ID FROM IGRS_REG_INIT_PROP_TRANS_MAP WHERE REG_TXN_ID=?) AND IS_APPLICANT NOT IN ('O'))) AND REG_TXN_ID=?";
    public static final String GET_EXTRA_FIELD_LABEL="SELECT LABEL_AMOUNT FROM IGRS_DEED_INSTRUMENT_MASTER WHERE LABEL_VALUE_REQUIRED='Y' AND INSTRUMENT_ID=?";
    public static final String GET_CLAIMANT_FLAG="SELECT CLAIMANT_FLAG,POA_HOLDER_FLAG FROM IGRS_PARTY_TYPE_MASTER WHERE PARTY_TYPE_ID=?";
    public static final String GET_USER_TYPE_ID="SELECT USER_TYPE_ID FROM IGRS_USERS_LIST WHERE USER_ID=?";
    public static final String GET_DIST_ID_NAME_RU="SELECT A.DISTRICT_ID, B.DISTRICT_NAME FROM IGRS_USER_REG_DETAILS A, IGRS_DISTRICT_MASTER B WHERE A.DISTRICT_ID=B.DISTRICT_ID AND A.USER_ID=?";
    public static final String GET_DIST_ID_NAME_OFFC_NAME_DRS="SELECT A.DISTRICT_ID, B.DISTRICT_NAME, A.OFFICE_NAME FROM IGRS_OFFICE_MASTER A, IGRS_DISTRICT_MASTER B WHERE A.DISTRICT_ID=B.DISTRICT_ID AND A.OFFICE_ID=?";
    public static final String GET_DIST_ID_NAME_SP="SELECT DISTINCT(A.DISTRICT_ID), B.DISTRICT_NAME  FROM IGRS_SP_DETLS A, IGRS_DISTRICT_MASTER B WHERE A.DISTRICT_ID=B.DISTRICT_ID AND A.APPLCTN_STATUS=8 AND A.CREATED_BY=?";
    public static final String COUNT_PROP_ID="SELECT COUNT(PROPERTY_ID) FROM IGRS_REG_PROPRTY_DTLS WHERE REG_TXN_ID=?";
    public static final String GET_REG_APPLICANT_DIST_ID ="SELECT DISTRICT_ID FROM IGRS_REG_TXN_PARTY_DETLS WHERE IS_APPLICANT='Y' AND REG_TXN_ID=?";
    public static final String GET_PENDING_APPLICATIONS_DETLS_ADJU = "SELECT RD.REG_TXN_ID, RD.CREATED_DATE, DM.DEED_TYPE_NAME, SUBSTR (RD.REG_TXN_ID, length(RD.REG_TXN_ID)-5, length(RD.REG_TXN_ID)) as sequence, RD.REGISTRATION_TXN_STATUS FROM IGRS_DEED_TYPE_MASTER DM, IGRS_REG_TXN_DETLS RD WHERE RD.ADJUDICATION_FLAG IN ('A') AND DM.DEED_TYPE_ID = RD.DEED_ID AND REGISTRATION_TXN_STATUS in (1,2,3,4,5,6,9,10) AND (RD.CREATED_BY = ? OR RD.UPDATE_BY = ?) ORDER BY RD.CREATED_DATE DESC";
    public static final String GET_COMMON_DEED_FLAG="SELECT COMMON_DEED_FLAG FROM IGRS_DEED_TYPE_MASTER WHERE DEED_TYPE_ID=?";
    public static final String GET_TRANS_PARTY_DETS_COMMON_DEED="SELECT A.ROLE_NAME,A.PARTY_FIRST_NAME,A.PARTY_LAST_NAME,A.AUTHRZD_PERSN_NAME,A.PARTY_TXN_ID,A.PARTY_TYPE_ID "+
	  																"FROM IGRS_REG_TXN_PARTY_DETLS A "+
	  																"WHERE IS_APPLICANT IN ('Y','N','C') "+
	  																"AND A.REG_TXN_ID=? "+
	  																"ORDER BY A.ROLE_NAME";
    public static final String INSERT_PARTICULAR_DETAILS="INSERT INTO IGRS_REG_TXN_PARTICULAR_DETLS(PARTICULAR_TXN_ID,REG_TXN_ID,PARTICULAR_NAME,PARTICULAR_DESC,CREATED_BY,CREATED_DATE) VALUES(IGRS_REG_TXN_PARTICULAR_ID_SEQ.NEXTVAL,?,?,?,?,SYSDATE)";
    public static final String GET_PARTICULAR_LIST="select PARTICULAR_TXN_ID,PARTICULAR_NAME,PARTICULAR_DESC from IGRS_REG_TXN_PARTICULAR_DETLS where REG_TXN_ID=?";
    public static final String GET_PARTICULAR_DETAILS="SELECT PARTICULAR_NAME,PARTICULAR_DESC FROM IGRS_REG_TXN_PARTICULAR_DETLS WHERE PARTICULAR_TXN_ID=?";
    public static final String UPADTE_PARTICULAR_DETAILS="UPDATE IGRS_REG_TXN_PARTICULAR_DETLS SET PARTICULAR_NAME=?,PARTICULAR_DESC=? WHERE PARTICULAR_TXN_ID=?";
    public static final String GET_PARTY_DETAILS_PDF_COMMON_DEED="SELECT REG_TXN_ID,APPELLATE_TYPE_ID,PARTY_FIRST_NAME,"+
	 																"PARTY_MIDDLE_NAME,PARTY_LAST_NAME,PARTY_GENDER,"+
	 																"PARTY_AGE,NATIONALITY,COUNTRY_ID,"+
	 																"STATE_ID,DISTRICT_ID,PARTY_ADDRESS,"+
	 																"POSTAL_CODE,PHONE_NUMBER,MOBILE_NUMBER,"+
	 																"EMAIL_ID,PHOTO_PROOF_TYPE_ID,PHOTO_PROOF_ID,"+
	 																"ORGANIZATION_NAME,AUTHRZD_PERSN_NAME,"+
	 																"GUARDIAN_NAME,MOTHER_NAME,CATEGORY_ID,"+
	 																"PARTY_TXN_ID,DISABILITY,RELATION_WITH_OWNER,"+
	 																"SHARE_OF_PROPERTY,PARTY_TYPE_ID,SPOUSE_NAME,"+
	 																"OWNER_ID,DISABILITY_DESC,OCCUPATION_ID,"+
	 																"COLLECTOR_PERMISSION_NUMBER,COLLECTOR_CERTIFICATE_PATH,"+
	 																"MEMBER_MINORITY,BELOW_POVERTY_LINE,"+
	 																"CATEGORY_ST_SCHEDULE_AREA,PHOTO_PROOF_PATH,NOT_AFFD_EXEC_PATH,EXEC_PHOTO_PATH,NOT_AFFD_ATTR_PATH, "+
	 																"ATTR_PHOTO_PATH,CLAIMNT_PHOTO_PATH,PAN_FORM_60_PATH,POA_SR_OFFICE_NAME,POA_REG_NO,POA_REG_DATE,ROLE_NAME,RELATION_TYPE_ID,UNIVERSAL_DEED_CLAIMANT_FLAG, "+
	 																"AUTH_PER_COUNTRY_ID,AUTH_PER_STATE_ID,AUTH_PER_DISTRICT_ID,AUTH_PER_PARTY_ADDRESS  "+
	 																"FROM IGRS_REG_TXN_PARTY_DETLS WHERE PARTY_TXN_ID=? ORDER BY ROLE_NAME ";
    public static final String GET_TODAY_APP_COUNT="SELECT COUNT(REG_TXN_ID) FROM IGRS_REG_TXN_DETLS WHERE TRUNC(CREATED_DATE)= TRUNC(SYSDATE)";
    public static final String DROP_REG_TXN_ID_SEQ_1="DROP SEQUENCE IGRS_REG_TXN_ID_SEQ";
    public static final String CREATE_REG_TXN_ID_SEQ_1="CREATE SEQUENCE IGRS_REG_TXN_ID_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 999999 MINVALUE 1 NOCYCLE  NOCACHE ORDER";
    public static final String GET_RELATIONSHIP_LIST = "SELECT O.RELATION_TYPE_ID,O.RELATION_TYPE_NAME FROM IGRS_RELATION_TYPE_MASTER O WHERE O.GENDER=?";
    public static final String GET_RELATIONSHIP_NAME="SELECT RELATION_TYPE_NAME FROM IGRS_RELATION_TYPE_MASTER WHERE RELATION_TYPE_ID=?";
    public static final String SELECT_PARTY_TYPE_INST_WISE = "SELECT A.PARTY_TYPE_ID,A.PARTY_TYPE_NAME FROM IGRS_PARTY_TYPE_MASTER A, IGRS_PARTY_TYPE_INST_MAP B WHERE PARTY_TYPE_STATUS='A' AND MAPPING_STATUS='A' AND A.PARTY_TYPE_ID=B.PARTY_TYPE_ID AND B.INSTRUMENT_ID=?";
    public static final String GET_EXECUTANT_CLAIMANT_LIST = "SELECT  A.CLAIMANT_FLAG_ID,A.CLAIMANT_FLAG_DESC    FROM IGRS_CLAIMANT_FLAG_MASTER A WHERE A.CLAIMANT_FLAG_ID IN (1,2,3,4) ORDER BY A.CLAIMANT_FLAG_ID ASC";
    public static final String GET_EXECUTANT_CLAIMANT_NAME="SELECT CLAIMANT_FLAG_DESC FROM IGRS_CLAIMANT_FLAG_MASTER WHERE CLAIMANT_FLAG_ID=?";
		
   //added by SHREERAJ
    public static final String GET_ADJU_FLAG="SELECT ADJUDICATION_FLAG FROM IGRS_REG_TXN_DETLS WHERE REG_TXN_ID=?";
    public static final String INSERT_ADJU_DUTY="INSERT INTO IGRS_REG_ADJUDCN_FINAL_DTLS(ADJUDCN_TXN_ID,CREATED_BY,CREATED_DATE,STAMP_DUTY,MUNICIPAL_DUTY,JANPAD_DUTY,UPKAR_DUTY,TOTAL_DUTY,REGISTRATION_FEE,MARKET_VALUE_SHARE,DUTY_ALREADY_PAID,REG_ALREADY_PAID,SECURED_AMOUNT,ADJUDICATION_REMARKS) VALUES (?,?,SYSDATE,?,?,?,?,?,?,?,?,?,?,?)";
    public static final String UPDATE_REG_ADJU_STATUS="UPDATE IGRS_REG_TXN_DETLS SET REGISTRATION_TXN_STATUS = 10 WHERE ADJUDICATION_FLAG='A' AND REG_TXN_ID=?";
    public static final String GET_REG_ADJU_DUTY_DETS_FOR_CONFIRMATION="SELECT STAMP_DUTY,JANPAD_DUTY,MUNICIPAL_DUTY,UPKAR_DUTY,REGISTRATION_FEE,TOTAL_DUTY,MARKET_VALUE_SHARE,DUTY_ALREADY_PAID,REG_ALREADY_PAID,SECURED_AMOUNT,ADJUDICATION_REMARKS FROM IGRS_REG_ADJUDCN_FINAL_DTLS WHERE ADJUDCN_TXN_ID=?";
    public static final String GET_ADJU_REMARKS="SELECT ADJUDICATION_REMARKS FROM IGRS_REG_ADJUDCN_FINAL_DTLS WHERE ADJUDCN_TXN_ID=?";
    public static final String UPDATE_ADJU_REG_STATUS="UPDATE IGRS_REG_TXN_DETLS SET REGISTRATION_TXN_STATUS = 3 , ADJUDICATION_FLAG='R', UPDATE_BY=?, UPDATE_DATE=sysdate WHERE REG_TXN_ID=?";
    public static final String GET_REG_INIT_ADJUDICATION_STATUS="SELECT ADJUDICATION_FLAG,REGISTRATION_TXN_STATUS FROM IGRS_REG_TXN_DETLS WHERE REG_TXN_ID=?";											
    
    // added by VINAY SHARMA
    
    public static final String GET_RELATIONSHIP_LIST_HI = "SELECT O.RELATION_TYPE_ID,O.H_RELATION_TYPE_NAME FROM IGRS_RELATION_TYPE_MASTER O WHERE O.GENDER=?";
    
    //HINDI QUERIES BY ROOPAM
    public static final String SELECT_PHOTO_PROOF_HINDI = "SELECT P.PHOTO_PROOF_TYPE_ID,P.PHOTO_PROOF_TYPE_NAME,P.H_PHOTO_PROOF_TYPE_NAME FROM IGRS_PHOTOID_PROOF_TYPE_MASTER P WHERE P.PHOTO_PROOF_TYPE_STATUS='A' ORDER BY P.PHOTO_PROOF_TYPE_ID ASC";
    public static final String SELECT_CATEGORY_HINDI = "SELECT A.CATEGORY_ID,A.CATEGORY_NAME,A.H_CATEGORY_NAME FROM IGRS_PERSON_CATEGORY_MASTER A WHERE A.CATEGORY_STATUS='A' ORDER BY A.CATEGORY_ID DESC";
    public static final String GET_OCCUPATION_LIST_HINDI = "SELECT O.OCCUPATION_ID,O.OCCUPATION_NAME,O.H_OCCUPATION_NAME FROM IGRS_OCCUPATION_MASTER O ORDER BY O.OCCUPATION_ID ASC";
    public static final String GET_PARTY_ROLE_NAME_HINDI="SELECT H_PARTY_TYPE_NAME FROM IGRS_PARTY_TYPE_MASTER WHERE PARTY_TYPE_ID=?";
    public static final String GET_DISTRICT_NAME_HINDI="SELECT H_DISTRICT_NAME FROM IGRS_DISTRICT_MASTER WHERE DISTRICT_ID=?";
    public static final String GET_COUNTRY_NAME_HINDI="SELECT H_COUNTRY_NAME FROM IGRS_COUNTRY_MASTER WHERE COUNTRY_ID=?";
    public static final String GET_STATE_NAME_HINDI="SELECT H_STATE_NAME FROM IGRS_STATE_MASTER WHERE STATE_ID=?";
    public static final String GET_OCCUPATION_NAME_HINDI="SELECT H_OCCUPATION_NAME FROM IGRS_OCCUPATION_MASTER WHERE OCCUPATION_ID=?";
    public static final String GET_CATEGORY_NAME_HINDI="SELECT H_CATEGORY_NAME FROM IGRS_PERSON_CATEGORY_MASTER WHERE CATEGORY_ID=?";
    public static final String GET_PHOTO_PROOF_NAME_HINDI="SELECT H_PHOTO_PROOF_TYPE_NAME FROM IGRS_PHOTOID_PROOF_TYPE_MASTER WHERE PHOTO_PROOF_TYPE_ID=?";
    
    public static final String GET_UNIT_NAME="SELECT UOM_NAME FROM IGRS_UOM_MASTER WHERE UOM_ID=?";
    public static final String GET_UNIT_NAME_HINDI="SELECT H_UOM_NAME FROM IGRS_UOM_MASTER WHERE UOM_ID=?";
    
    public static final String GET_TEHSIL_NAME="SELECT TEHSIL_NAME FROM IGRS_TEHSIL_MASTER WHERE TEHSIL_ID=?";
    public static final String GET_TEHSIL_NAME_HINDI="SELECT H_TEHSIL_NAME FROM IGRS_TEHSIL_MASTER WHERE TEHSIL_ID=?";
    
    public static final String GET_AREA_TYPE_NAME="SELECT AREA_TYPE_NAME FROM IGRS_AREA_TYPE_MASTER WHERE AREA_TYPE_ID=?";
    public static final String GET_AREA_TYPE_NAME_HINDI="SELECT H_AREA_TYPE_NAME FROM IGRS_AREA_TYPE_MASTER WHERE AREA_TYPE_ID=?";
    
    public static final String GET_WARD_NAME="SELECT WARD_PATWARI_NAME FROM IGRS_WARD_PATWARI_MASTER WHERE WARD_PATWARI_ID=?";
    public static final String GET_WARD_NAME_HINDI="SELECT H_WARD_PATWARI_NAME FROM IGRS_WARD_PATWARI_MASTER WHERE WARD_PATWARI_ID=?";
    
    public static final String SELECTPROPERTYTYPEL1DETAILS_HINDI="SELECT PROPERTY_TYPE_L1_ID,PROPERTY_TYPE_L1_NAME,H_PROPERTY_TYPE_L1_NAME FROM IGRS_PROP_TYPE_L1_MASTER WHERE PROPERTY_TYPE_ID=?";
    
    public static final String SELECT_PROPERTY_TYPE_L2_DETAILS_HINDI="SELECT PROPERTY_TYPE_L2_ID,PROPERTY_TYPE_L2_DESC,H_PROPERTY_TYPE_L2_NAME FROM IGRS_PROP_TYPE_L2_MASTER WHERE PROPERTY_TYPE_L1_ID=? AND PROPERTY_TYPE_L2_STATUS='A'";
    
    public static final String SELECT_UNIT_LIST_DETAILS_HINDI="SELECT A.UOM_ID,A.UOM_NAME,A.H_UOM_NAME FROM IGRS_UOM_MASTER A, IGRS_PROP_TYPE_L1_MASTER B WHERE A.UOM_ID=B.UOM_ID AND B.PROPERTY_TYPE_L1_ID=?";
    
    public static final String GET_PROPERTY_TYPE_NAME_HINDI="SELECT H_PROPERTY_TYPE_NAME FROM IGRS_PROPERTY_TYPE_MASTER WHERE PROPERTY_TYPE_ID=?";
    
    public static final String GET_L1_NAME="SELECT PROPERTY_TYPE_L1_DESC FROM IGRS_PROP_TYPE_L1_MASTER WHERE PROPERTY_TYPE_L1_ID=?";
    public static final String GET_L1_NAME_HINDI="SELECT H_PROPERTY_TYPE_L1_NAME FROM IGRS_PROP_TYPE_L1_MASTER WHERE PROPERTY_TYPE_L1_ID=?";
    
    public static final String GET_L2_NAME="SELECT PROPERTY_TYPE_L2_DESC FROM IGRS_PROP_TYPE_L2_MASTER WHERE PROPERTY_TYPE_L2_ID=?";
    public static final String GET_L2_NAME_HINDI="SELECT H_PROPERTY_TYPE_L2_NAME FROM IGRS_PROP_TYPE_L2_MASTER WHERE PROPERTY_TYPE_L2_ID=?";
    
    public static final String GET_FLOOR_NAME="SELECT FLOOR_NAME FROM IGRS_FLOOR_MASTER WHERE FLOOR_ID=?";
    public static final String GET_FLOOR_NAME_HINDI="SELECT H_FLOOR_NAME FROM IGRS_FLOOR_MASTER WHERE FLOOR_ID=?";
    
    public static final String GET_EXTRA_FIELD_LABEL_HINDI="SELECT H_LABEL_AMOUNT FROM IGRS_DEED_INSTRUMENT_MASTER WHERE LABEL_VALUE_REQUIRED='Y' AND INSTRUMENT_ID=?";
    
    public static final String GET_RELATIONSHIP_LIST_HINDI = "SELECT O.RELATION_TYPE_ID,O.RELATION_TYPE_NAME,O.H_RELATION_TYPE_NAME FROM IGRS_RELATION_TYPE_MASTER O WHERE O.GENDER=?";
    
    public static final String SELECT_APPL_TYPE_HINDI = "SELECT A.APPELLATE_TYPE_ID,A.APPELLATE_TYPE_NAME,A.H_APPELLATE_TYPE_NAME FROM IGRS_APPELLATE_TYPE_MASTER A WHERE A.APPELLATE_TYPE_STATUS='A' ORDER BY A.APPELLATE_TYPE_ID DESC";
    
    public static final String GET_RELATIONSHIP_NAME_HINDI="SELECT H_RELATION_TYPE_NAME FROM IGRS_RELATION_TYPE_MASTER WHERE RELATION_TYPE_ID=?";
    
    public static final String GET_APPLETE_NAME="SELECT APPELLATE_TYPE_NAME FROM IGRS_APPELLATE_TYPE_MASTER WHERE APPELLATE_TYPE_ID=?";
    public static final String GET_APPLETE_NAME_HINDI="SELECT H_APPELLATE_TYPE_NAME FROM IGRS_APPELLATE_TYPE_MASTER WHERE APPELLATE_TYPE_ID=?";
    
    public static final String GET_EXECUTANT_CLAIMANT_LIST_HINDI = "SELECT  A.CLAIMANT_FLAG_ID,A.CLAIMANT_FLAG_DESC,A.H_CLAIMANT_FLAG_DESC    FROM IGRS_CLAIMANT_FLAG_MASTER A WHERE A.CLAIMANT_FLAG_ID IN (1,2,3,4) ORDER BY A.CLAIMANT_FLAG_ID ASC";
    public static final String GET_EXECUTANT_CLAIMANT_LIST_WILL_HINDI = "SELECT  A.CLAIMANT_FLAG_ID,A.CLAIMANT_FLAG_DESC,A.H_CLAIMANT_FLAG_DESC    FROM IGRS_CLAIMANT_FLAG_MASTER A WHERE A.CLAIMANT_FLAG_ID IN (1,2) ORDER BY A.CLAIMANT_FLAG_ID ASC";
    
    public static final String SELECT_PARTY_TYPE_HINDI = "SELECT iptm.PARTY_TYPE_ID,PARTY_TYPE_NAME,H_PARTY_TYPE_NAME FROM IGRS_PARTY_TYPE_MASTER iptm, IGRS_PARTY_TYPE_DEED_MAP iptdm WHERE PARTY_TYPE_STATUS='A' AND MAPPING_STATUS='A' AND iptm.PARTY_TYPE_ID=iptdm.PARTY_TYPE_ID AND iptdm.DEED_TYPE_ID=?";
    public static final String SELECT_PARTY_TYPE_INST_WISE_HINDI = "SELECT A.PARTY_TYPE_ID,A.PARTY_TYPE_NAME,A.H_PARTY_TYPE_NAME FROM IGRS_PARTY_TYPE_MASTER A, IGRS_PARTY_TYPE_INST_MAP B WHERE PARTY_TYPE_STATUS='A' AND MAPPING_STATUS='A' AND A.PARTY_TYPE_ID=B.PARTY_TYPE_ID AND B.INSTRUMENT_ID=?";
    
    public static final String OFFICE_NAME=
		"SELECT OFFICE_NAME FROM IGRS_OFFICE_MASTER WHERE OFFICE_ID=?";
    public static final String OFFICE_NAME_HINDI=
		"SELECT H_OFFICE_NAME FROM IGRS_OFFICE_MASTER WHERE OFFICE_ID=?";
    

   
}
