package com.wipro.igrs.complaintdetails.sql;

public class ComplaintDetailsSQL {
	

	public static final String SELECTED_FIELDS = "SELECT comp.FIRST_NAME ||' '|| comp.MIDDLE_NAME ||' ' ||comp.LAST_NAME,"+
	"compD.DESIG_NAME,compO.OFFICE_NAME,"+
	"ddo.FIRST_NAME ||' '|| ddo.MIDDLE_NAME ||' ' ||ddo.LAST_NAME,ddoD.DESIG_NAME,ddoO.OFFICE_NAME,"+
	"DETAILED_HEAD_NAME_E "+
	"FROM IGRS_EMP_COMPLAINT_DETAILS left outer join IGRS_EMP_COMPLAINT_STATUS_DTLS on IGRS_EMP_COMPLAINT_STATUS_DTLS.COMPLAINT_NO=IGRS_EMP_COMPLAINT_DETAILS.COMPLAINT_NO left outer join IGRS_EMP_SALARY_STACK on IGRS_EMP_COMPLAINT_DETAILS.COMPLAINEE_USER_ID = IGRS_EMP_SALARY_STACK.EMP_ID left outer join IGRS_EXP_DETAILED_HEAD_MASTER on IGRS_EMP_SALARY_STACK.COMPONENT_ID = IGRS_EXP_DETAILED_HEAD_MASTER.DETAILED_HEAD_ID join IGRS_EMP_MASTER comp on IGRS_EMP_COMPLAINT_DETAILS.COMPLAINEE_USER_ID = comp.EMP_ID join IGRS_EMP_COMPLAINT_ACTION_DTLS on IGRS_EMP_COMPLAINT_DETAILS.COMPLAINT_NO = IGRS_EMP_COMPLAINT_ACTION_DTLS.COMPLAINT_NO  join IGRS_EMP_OFFICIAL_DETAILS compOD on comp.EMP_ID = compOD.EMP_ID join IGRS_EMP_DESIGNATION_MASTER compD on "+
	"compOD.EMP_DESIGNATION_ID = compD.DESIG_ID join IGRS_EMP_OFFICE_MAPPING empM on "+
	"comp.EMP_ID = empM.EMP_ID join IGRS_OFFICE_MASTER compO on empM.OFFICE_ID = compO.OFFICE_ID join IGRS_OFFICE_TYPE_MASTER compT on compO.OFFICE_TYPE_ID = compT.OFFICE_TYPE_ID "+
	"join IGRS_EMP_MASTER ddo on IGRS_EMP_COMPLAINT_DETAILS.DEPUTED_PE_USER_ID = ddo.EMP_ID join IGRS_EMP_OFFICIAL_DETAILS ddoOD on ddo.EMP_ID = ddoOD.EMP_ID join IGRS_EMP_DESIGNATION_MASTER ddoD on "+
	"ddoOD.EMP_DESIGNATION_ID = ddoD.DESIG_ID join IGRS_EMP_OFFICE_MAPPING ddoM on "+
	"ddo.EMP_ID = ddoM.EMP_ID join IGRS_OFFICE_MASTER ddoO on ddoM.OFFICE_ID = ddoO.OFFICE_ID join IGRS_OFFICE_TYPE_MASTER ddoT on ddoO.OFFICE_TYPE_ID = ddoT.OFFICE_TYPE_ID ";
	
	

	public static final String SELECT_OFFICES_BY_TYPE = "SELECT OFFICE_ID,OFFICE_NAME FROM IGRS_OFFICE_MASTER WHERE OFFICE_TYPE_ID = ?";
	public static final String SELECT_COMP_STAUS = "SELECT DISTINCT IGRS_EMP_COMPLAINT_STATUS_DTLS.COMPLAINT_STATUS FROM IGRS_EMP_COMPLAINT_STATUS_DTLS join IGRS_EMP_COMPLAINT_DETAILS on IGRS_EMP_COMPLAINT_STATUS_DTLS.COMPLAINT_NO=IGRS_EMP_COMPLAINT_DETAILS.COMPLAINT_NO";
	
	public static final String PAYMENT_EXACT_DATE = "IGRS_EMP_COMPLAINT_ACTION_DTLS.DATE_OF_ISSUANCE = ?"; 
	public static final String PAYMENT_RANGE_DATE = "IGRS_EMP_COMPLAINT_ACTION_DTLS.DATE_OF_ISSUANCE BETWEEN ? AND ?";
	
	public static final String EMPLOYEE_CODE = "IGRS_EMP_COMPLAINT_DETAILS.COMPLAINEE_USER_ID like ?";
	public static final String EMP_F_NAME = "comp.FIRST_NAME like '%' || ? || '%'";
	public static final String EMP_M_NAME = "comp.MIDDLE_NAME like '%' || ? || '%'";
	public static final String EMP_L_NAME = "comp.MIDDLE_NAME like '%' || ? || '%'";
	
	public static final String STATUS = "IGRS_EMP_COMPLAINT_STATUS_DTLS.COMPLAINT_STATUS = ?";
	
	public static final String LOCATION = "compT.OFFICE_TYPE_ID = ?";
	
	public static final String OFFICE = "empM.OFFICE_ID = ? ";
	
	
	
	
}
