package com.wipro.igrs.propertylock.sql;

public class PlockSQL {
	
	
public static final String COUNTRY_QUERY = "Select COUNTRY_ID, COUNTRY_NAME from IGRS_COUNTRY_MASTER "+
	                                            "WHERE COUNTRY_STATUS='A' AND COUNTRY_ID=1";
//added by shruti
public static final String COUNTRY_QUERY_H = "Select COUNTRY_ID, H_COUNTRY_NAME from IGRS_COUNTRY_MASTER "+
"WHERE COUNTRY_STATUS='A' AND COUNTRY_ID=1";
//end

public static final String STATE_QUERY = "Select STATE_ID, STATE_NAME from IGRS_STATE_MASTER "+
		                                 "Where  STATE_STATUS='A' AND COUNTRY_ID=? AND STATE_ID=1";

//added by shruti
public static final String STATE_QUERY_H = "Select STATE_ID, H_STATE_NAME from IGRS_STATE_MASTER "+
"Where  STATE_STATUS='A' AND COUNTRY_ID=? AND STATE_ID=1";
//end
public static final String SERVICE_FEE_PROCEDURE = "CALL IGRS_SERVICE_FEE_PKG.IGRS_SERVICE_FEE_PROC(?,?,?,?,?,?)";

//added by shruti---15 May 2014
public static final String GET_SERVICE_FEE_RU="SELECT FEE_RU FROM IGRS_FUNCTION_SERVICE_MAPPING WHERE FUNCTION_ID=?"; 

public static final String GET_SERVICE_FEE_SP="SELECT FEE_SP FROM IGRS_FUNCTION_SERVICE_MAPPING WHERE FUNCTION_ID=?"; 

public static final String GET_SERVICE_FEE_DR="SELECT FEE_DR FROM IGRS_FUNCTION_SERVICE_MAPPING WHERE FUNCTION_ID=?"; 

public static final String CHECKUSERTYPE="SELECT USER_TYPE_ID FROM IGRS_USERS_LIST WHERE USER_ID=?";

public static final String GETOFFICENAME="SELECT iom.office_name,iom.DISTRICT_ID,idm.district_name FROM igrs_office_master iom,igrs_district_master idm"
	+" where iom.district_id=idm.district_id and iom.office_id=?";

public static final String GETSPDISTRICT="SELECT idm.district_name,isd.DISTRICT_ID FROM IGRS_SP_DETLS isd," 
	+"igrs_district_master idm WHERE isd.district_id=idm.district_id" 
	+" and isd.CREATED_BY=? AND isd.STATUS='A' AND isd.APPLCTN_STATUS='8'";

public static final String GETRUDISTRICT="SELECT idm.district_name,iurd.DISTRICT_ID FROM IGRS_USER_REG_DETAILS iurd ,IGRS_DISTRICT_MASTER idm WHERE iurd.district_id=idm.district_id and USER_ID=?";

public static final String REG_LOCK_DETLS_QRY = "SELECT p.PROPERTY_TXN_ID, m.LOCK_STATUS_NAME,d.DEED_TYPE_NAME, p.REGISTRATION_NUMBER, TO_CHAR(p.REGISTRATION_DATE,'dd/MM/yyyy') "+
                                                "FROM IGRS_PROP_LOCK_TXN_DETLS p, IGRS_REG_TXN_DETLS r, IGRS_DEED_TYPE_MASTER d, IGRS_PROP_LOCK_STATUS_MASTER m "+
                                                "WHERE p.REGISTRATION_NUMBER = r.REGISTRATION_NUMBER AND r.DEED_ID=d.DEED_TYPE_ID AND p.LOCK_STATUS_ID=m.LOCK_STATUS_ID "+
                                                "AND p.REGISTRATION_NUMBER=? AND p.STATUS_FLAG='A'";

//added by shruti-21 feb 2014

public static final String REG_LOCK_DETLS_QRY_H = "SELECT p.PROPERTY_TXN_ID, m.H_LOCK_STATUS_NAME,d.DEED_TYPE_NAME, p.REGISTRATION_NUMBER, TO_CHAR(p.REGISTRATION_DATE,'dd/MM/yyyy') "+
                                                "FROM IGRS_PROP_LOCK_TXN_DETLS p, IGRS_REG_TXN_DETLS r, IGRS_DEED_TYPE_MASTER d, IGRS_PROP_LOCK_STATUS_MASTER m "+
                                                "WHERE p.REGISTRATION_NUMBER = r.REGISTRATION_NUMBER AND r.DEED_ID=d.DEED_TYPE_ID AND p.LOCK_STATUS_ID=m.LOCK_STATUS_ID "+
                                                "AND p.REGISTRATION_NUMBER=? AND p.STATUS_FLAG='A'";
//end
public static final String REL_LOCK_DETLS_QRY1 ="SELECT p.PROPERTY_TXN_ID, m.LOCK_STATUS_NAME,TO_CHAR(p.LOCK_DATE,'dd/MM/yyyy'),p.REGISTRATION_NUMBER, TO_CHAR(p.REGISTRATION_DATE,'dd/MM/yyyy'), p.PROPERTY_LOCK_ID "+
                                                "FROM IGRS_PROP_LOCK_TXN_DETLS p,IGRS_PROP_LOCK_STATUS_MASTER m "+
                                                "WHERE p.LOCK_STATUS_ID=m.LOCK_STATUS_ID AND p.STATUS_FLAG='A' AND p.LOCK_STATUS_ID=2 "+
                                                "AND (p.PROPERTY_LOCK_ID=? OR (p.LOCK_DATE BETWEEN TO_DATE(?, 'dd/mm/yyyy')-1 AND TO_DATE(?, 'dd/mm/yyyy')+1))  ";


//added by shruti

public static final String REL_LOCK_DETLS_QRY1_H ="SELECT p.PROPERTY_TXN_ID, m.H_LOCK_STATUS_NAME,TO_CHAR(p.LOCK_DATE,'dd/MM/yyyy'),p.REGISTRATION_NUMBER, TO_CHAR(p.REGISTRATION_DATE,'dd/MM/yyyy'), p.PROPERTY_LOCK_ID "+
                                                "FROM IGRS_PROP_LOCK_TXN_DETLS p,IGRS_PROP_LOCK_STATUS_MASTER m "+
                                                "WHERE p.LOCK_STATUS_ID=m.LOCK_STATUS_ID AND p.STATUS_FLAG='A' AND p.LOCK_STATUS_ID=2 "+
                                                "AND (p.PROPERTY_LOCK_ID=? OR (p.LOCK_DATE BETWEEN TO_DATE(?, 'dd/mm/yyyy')-1 AND TO_DATE(?, 'dd/mm/yyyy')+1))  ";


//end
public static final String VIEW_DETLS_QRY ="SELECT t.PROPERTY_LOCK_ID, t.REGISTRATION_NUMBER, t.PROPERTY_TXN_ID, m.LOCK_STATUS_NAME,t.LOCK_STATUS_ID  " +
											" FROM IGRS_PROP_LOCK_TXN_DETLS t, IGRS_PROP_LOCK_STATUS_MASTER m " +
											" WHERE m.LOCK_STATUS_ID=t.LOCK_STATUS_ID AND (t.LOCK_STATUS_ID='1' OR t.LOCK_STATUS_ID='2') " +
											" AND(t.PROPERTY_LOCK_ID=? OR" +
											" t.REGISTRATION_NUMBER=? OR t.LOCK_STATUS_ID=? " +
											" OR((t.LOCK_DATE BETWEEN TO_DATE(?, 'dd/mm/yyyy')-1 AND TO_DATE(?, 'dd/mm/yyyy')+1) " +
											" OR(t.RELEASE_DATE BETWEEN TO_DATE(?, 'dd/mm/yyyy')-1 AND TO_DATE(?, 'dd/mm/yyyy')+1))) "+
											" AND t.PROPERTY_LOCK_ID NOT IN(SELECT PROPERTY_LOCK_ID FROM IGRS_PROP_LOCK_TXN_DETLS WHERE LOCK_DATE IS NULL AND RELEASE_DATE IS NULL AND (LOCK_STATUS_ID='1' OR LOCK_STATUS_ID='2'))";

public static final String VIEW_DETLS_QRY_NEW ="SELECT t.PROPERTY_LOCK_ID, t.REGISTRATION_NUMBER, t.PROPERTY_TXN_ID, m.LOCK_STATUS_NAME,t.LOCK_STATUS_ID  " +
" FROM IGRS_PROP_LOCK_TXN_DETLS t, IGRS_PROP_LOCK_STATUS_MASTER m " +
" WHERE m.LOCK_STATUS_ID=t.LOCK_STATUS_ID AND (t.LOCK_STATUS_ID='1' OR t.LOCK_STATUS_ID='2') " +
" AND t.PROPERTY_LOCK_ID NOT IN(SELECT PROPERTY_LOCK_ID FROM IGRS_PROP_LOCK_TXN_DETLS WHERE LOCK_DATE IS NULL AND RELEASE_DATE IS NULL AND (LOCK_STATUS_ID='1' OR LOCK_STATUS_ID='2'))"+
" AND(t.PROPERTY_LOCK_ID=? OR" +
" t.REGISTRATION_NUMBER=? OR t.LOCK_STATUS_ID=? " +
" OR((t.LOCK_DATE BETWEEN TO_DATE(?, 'dd/mm/yyyy')-1 AND TO_DATE(?, 'dd/mm/yyyy')+1) " +
" OR(t.RELEASE_DATE BETWEEN TO_DATE(?, 'dd/mm/yyyy')-1 AND TO_DATE(?, 'dd/mm/yyyy')+1)))";


//added by shruti
public static final String VIEW_DETLS_QRY_H ="SELECT t.PROPERTY_LOCK_ID, t.REGISTRATION_NUMBER, t.PROPERTY_TXN_ID, m.H_LOCK_STATUS_NAME,t.LOCK_STATUS_ID  " +
" FROM IGRS_PROP_LOCK_TXN_DETLS t, IGRS_PROP_LOCK_STATUS_MASTER m " +
" WHERE m.LOCK_STATUS_ID=t.LOCK_STATUS_ID AND (t.LOCK_STATUS_ID='1' OR t.LOCK_STATUS_ID='2') " +
" AND(t.PROPERTY_LOCK_ID=? OR" +
" t.REGISTRATION_NUMBER=? OR t.LOCK_STATUS_ID=? " +
" OR((t.LOCK_DATE BETWEEN TO_DATE(?, 'dd/mm/yyyy')-1 AND TO_DATE(?, 'dd/mm/yyyy')+1) " +
" OR(t.RELEASE_DATE BETWEEN TO_DATE(?, 'dd/mm/yyyy')-1 AND TO_DATE(?, 'dd/mm/yyyy')+1))) "+
" AND t.PROPERTY_LOCK_ID NOT IN(SELECT PROPERTY_LOCK_ID FROM IGRS_PROP_LOCK_TXN_DETLS WHERE LOCK_DATE IS NULL AND RELEASE_DATE IS NULL AND (LOCK_STATUS_ID='1' OR LOCK_STATUS_ID='2'))";
//end
public static final String VIEW_DETLS_QRY_H_NEW ="SELECT t.PROPERTY_LOCK_ID, t.REGISTRATION_NUMBER, t.PROPERTY_TXN_ID, m.H_LOCK_STATUS_NAME,t.LOCK_STATUS_ID  " +
" FROM IGRS_PROP_LOCK_TXN_DETLS t, IGRS_PROP_LOCK_STATUS_MASTER m " +
" WHERE m.LOCK_STATUS_ID=t.LOCK_STATUS_ID AND (t.LOCK_STATUS_ID='1' OR t.LOCK_STATUS_ID='2') " +
" AND t.PROPERTY_LOCK_ID NOT IN(SELECT PROPERTY_LOCK_ID FROM IGRS_PROP_LOCK_TXN_DETLS WHERE LOCK_DATE IS NULL AND RELEASE_DATE IS NULL AND (LOCK_STATUS_ID='1' OR LOCK_STATUS_ID='2'))"+
" AND(t.PROPERTY_LOCK_ID=? OR" +
" t.REGISTRATION_NUMBER=? OR t.LOCK_STATUS_ID=? " +
" OR((t.LOCK_DATE BETWEEN TO_DATE(?, 'dd/mm/yyyy')-1 AND TO_DATE(?, 'dd/mm/yyyy')+1) " +
" OR(t.RELEASE_DATE BETWEEN TO_DATE(?, 'dd/mm/yyyy')-1 AND TO_DATE(?, 'dd/mm/yyyy')+1))) ";

//end
public static final String VIEW_LOCK_DATE=    "SELECT TO_CHAR(LOCK_DATE,'dd/MM/yyyy') FROM IGRS_PROP_LOCK_TXN_DETLS WHERE PROPERTY_LOCK_ID=? AND LOCK_STATUS_ID =?";
public static final String VIEW_RELEASE_DATE= "SELECT TO_CHAR(RELEASE_DATE,'dd/MM/yyyy') FROM IGRS_PROP_LOCK_TXN_DETLS WHERE PROPERTY_LOCK_ID=? AND LOCK_STATUS_ID =?";





public static final String GETLOCKSTATUS=" SELECT LOCK_STATUS_ID, PROPERTY_LOCK_ID  FROM IGRS_PROP_LOCK_TXN_DETLS WHERE REGISTRATION_NUMBER =? AND PROPERTY_TXN_ID =? AND STATUS_FLAG='A'";


public static final String STATUS_FLAG_UPDATE  = "UPDATE IGRS_PROP_LOCK_TXN_DETLS SET STATUS_FLAG='D',UPDATE_BY=?, UPDATE_DATE=SYSDATE "+
                                                "WHERE REGISTRATION_NUMBER=? AND PROPERTY_TXN_ID=? AND LOCK_STATUS_ID=1 AND STATUS_FLAG='A'";

public static final String STATUS_FLAG_UPDATE_REL  = "UPDATE IGRS_PROP_LOCK_TXN_DETLS SET STATUS_FLAG='D',UPDATE_BY=?, UPDATE_DATE=SYSDATE "+
                                                     "WHERE REGISTRATION_NUMBER=? AND PROPERTY_TXN_ID=? AND PROPERTY_LOCK_ID=? AND LOCK_STATUS_ID=2 AND STATUS_FLAG='A'";


public static final String LOCK_TXN_TBL_INSERT_REL = "INSERT INTO IGRS_PROP_LOCK_TXN_DETLS (PROPERTY_LOCK_ID,REGISTRATION_NUMBER,REGISTRATION_DATE,PROPERTY_TXN_ID,POA_REGISTRATION_ID,POA_REGISTRATION_DATE, "+
                                                     "LOCK_STATUS_ID,PURPOSE,STATUS_FLAG,CREATED_BY,CREATED_DATE,OFFICE_ID,RELEASE_DATE,RELEASE_REMARKS,RELEASER_TYPE_ID) "+
                                                     "VALUES(?,?,to_date(?,'dd/mm/yyyy'),?,?,to_date(?,'dd/mm/yyyy'),1,?,'A',?,SYSDATE,?,SYSDATE,?,?)";



public static final String LOCK_TXN_TBL_INSERT_REL_P = "INSERT INTO IGRS_PROP_LOCK_TXN_DETLS (PROPERTY_LOCK_ID,REGISTRATION_NUMBER,REGISTRATION_DATE,PROPERTY_TXN_ID,POA_REGISTRATION_ID,POA_REGISTRATION_DATE, "+
                                                       "LOCK_STATUS_ID,PURPOSE,STATUS_FLAG,CREATED_BY,CREATED_DATE,OFFICE_ID,RELEASE_REMARKS,RELEASER_TYPE_ID) "+
                                                       "VALUES(?,?,to_date(?,'dd/mm/yyyy'),?,?,to_date(?,'dd/mm/yyyy'),4,?,'A',?,SYSDATE,?,?,?)";

public static final String LOCK_REL_TBL_INSERT = "INSERT INTO IGRS_PROP_LOCK_RELATIVE_DETLS "+
                                                 "(PROP_REL_DTLS_ID,PROPERTY_LOCK_ID,RELATIVE_NAME,RELATIVE_TYPE_ID,RELATIVE_FATHERNAME,RELATIVE_MOTHERNAME, "+
                                                 "COUNTRY_ID,STATE_ID,DISTRICT_ID,RELATIVE_ADDRESS,RELATIVE_MOB,RELATIVE_PHONE,RELATIVE_EMAIL,DEATH_CERTIFICATE_NAME, "+
                                                 "RELATIVE_PHOTO_NAME,RELATIVE_THUMB_NAME,RELATIVE_SIGNATURE_NAME,DEATH_CERTIFICATE_PATH,RELATIVE_PHOTO_PATH,RELATIVE_THUMB_PATH, "+
                                                 "RELATIVE_SIGNATURE_PATH,CREATED_BY,CREATED_DATE) "+
                                                 "VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,SYSDATE)";



public static final String LOCK_TXN_TBL_INSERT = "INSERT INTO IGRS_PROP_LOCK_TXN_DETLS (PROPERTY_LOCK_ID,REGISTRATION_NUMBER,REGISTRATION_DATE,PROPERTY_TXN_ID,POA_REGISTRATION_ID,POA_REGISTRATION_DATE, "+
                                                 "LOCK_STATUS_ID,PURPOSE,STATUS_FLAG,CREATED_BY,CREATED_DATE,OFFICE_ID,LOCK_DATE) "+
                                                 "VALUES(?,?,to_date(?,'dd/mm/yyyy'),?,?,to_date(?,'dd/mm/yyyy'),2,?,'A',?,SYSDATE,?,SYSDATE)";

public static final String LOCK_TXN_TBL_INSERTP = "INSERT INTO IGRS_PROP_LOCK_TXN_DETLS (PROPERTY_LOCK_ID,REGISTRATION_NUMBER,REGISTRATION_DATE,PROPERTY_TXN_ID,POA_REGISTRATION_ID,POA_REGISTRATION_DATE, "+
                                                  "LOCK_STATUS_ID,PURPOSE,STATUS_FLAG,CREATED_BY,CREATED_DATE,OFFICE_ID) "+
                                                  "VALUES(?,?,to_date(?,'dd/mm/yyyy'),?,?,to_date(?,'dd/mm/yyyy'),3,?,'A',?,SYSDATE,?)";


public static final String LOCK_PARTY_TBL_INSERT = "INSERT INTO IGRS_PROP_LOCK_TXN_PARTY_DETLS "+
                                                   "(PARTY_TXN_ID,PROPERTY_LOCK_ID,APPELLATE_TYPE_ID,PARTY_FIRST_NAME,PARTY_MIDDLE_NAME,PARTY_LAST_NAME,PARTY_GENDER, "+
                                                   "PARTY_AGE,COUNTRY_ID,STATE_ID,DISTRICT_ID,PARTY_ADDRESS,POSTAL_CODE,PHONE_NUMBER,MOBILE_NUMBER,EMAIL_ID, "+
                                                   "PHOTO_PROOF_TYPE_ID,PHOTO_PROOF_NUMBER,BANK_NAME,BANK_ADDRESS,GUARDIAN_NAME,MOTHER_NAME,PHOTO_NAME,THUMB_NAME, "+
                                                   "SIGNATURE_NAME,PHOTO_PATH,THUMB_PATH,SIGNATURE_PATH,CREATED_BY,CREATED_DATE) "+
                                                   "VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,SYSDATE)";

public static final String LOCK_PARTY_TBL_INSERT1 = "INSERT INTO IGRS_PROP_LOCK_TXN_PARTY_DETLS "+
                                                    "(PARTY_TXN_ID,PROPERTY_LOCK_ID,APPELLATE_TYPE_ID,COUNTRY_ID,STATE_ID,DISTRICT_ID,PARTY_ADDRESS,PHONE_NUMBER,MOBILE_NUMBER, "+
                                                    "ORGANIZATION_NAME, AUTHRZD_PERSN_NAME, PHOTO_NAME,THUMB_NAME,SIGNATURE_NAME,PHOTO_PATH,THUMB_PATH,SIGNATURE_PATH,CREATED_BY,CREATED_DATE) "+
                                                    "VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,SYSDATE)";



public static final String TXN_DETL = "SELECT t.PROPERTY_LOCK_ID,t.REGISTRATION_NUMBER,TO_CHAR(t.REGISTRATION_DATE,'dd/MM/yyyy'),t.PROPERTY_TXN_ID, "+
                                      "t.POA_REGISTRATION_ID,TO_CHAR(t.POA_REGISTRATION_DATE,'dd/MM/yyyy'),m.LOCK_STATUS_NAME,t.PURPOSE,TO_CHAR(t.LOCK_DATE,'dd/MM/yyyy')  "+
                                      "FROM IGRS_PROP_LOCK_TXN_DETLS t, IGRS_PROP_LOCK_STATUS_MASTER m "+
                                      "WHERE m.LOCK_STATUS_ID=t.LOCK_STATUS_ID AND t.REGISTRATION_NUMBER=? AND t.PROPERTY_TXN_ID=? "+
                                      "AND t.PROPERTY_LOCK_ID=? AND t.LOCK_STATUS_ID=2 AND t.STATUS_FLAG='A'";

//added by shruti
public static final String TXN_DETL_H = "SELECT t.PROPERTY_LOCK_ID,t.REGISTRATION_NUMBER,TO_CHAR(t.REGISTRATION_DATE,'dd/MM/yyyy'),t.PROPERTY_TXN_ID, "+
"t.POA_REGISTRATION_ID,TO_CHAR(t.POA_REGISTRATION_DATE,'dd/MM/yyyy'),m.H_LOCK_STATUS_NAME,t.PURPOSE,TO_CHAR(t.LOCK_DATE,'dd/MM/yyyy')  "+
"FROM IGRS_PROP_LOCK_TXN_DETLS t, IGRS_PROP_LOCK_STATUS_MASTER m "+
"WHERE m.LOCK_STATUS_ID=t.LOCK_STATUS_ID AND t.REGISTRATION_NUMBER=? AND t.PROPERTY_TXN_ID=? "+
"AND t.PROPERTY_LOCK_ID=? AND t.LOCK_STATUS_ID=2 AND t.STATUS_FLAG='A'";
//end

public static final String TXN_DETL_VIEW = "SELECT t.PROPERTY_LOCK_ID,t.REGISTRATION_NUMBER,TO_CHAR(t.REGISTRATION_DATE,'dd/MM/yyyy'),t.PROPERTY_TXN_ID, "+
                                           "t.POA_REGISTRATION_ID,TO_CHAR(t.POA_REGISTRATION_DATE,'dd/MM/yyyy'),m.LOCK_STATUS_NAME,t.PURPOSE,TO_CHAR(t.LOCK_DATE,'dd/MM/yyyy')  "+
                                           "FROM IGRS_PROP_LOCK_TXN_DETLS t, IGRS_PROP_LOCK_STATUS_MASTER m "+
                                           "WHERE m.LOCK_STATUS_ID=t.LOCK_STATUS_ID AND t.REGISTRATION_NUMBER=? AND t.PROPERTY_TXN_ID=? "+
                                           "AND t.PROPERTY_LOCK_ID=? AND t.LOCK_STATUS_ID=2";

public static final String TXN_DETL_VIEW_H = "SELECT t.PROPERTY_LOCK_ID,t.REGISTRATION_NUMBER,TO_CHAR(t.REGISTRATION_DATE,'dd/MM/yyyy'),t.PROPERTY_TXN_ID, "+
"t.POA_REGISTRATION_ID,TO_CHAR(t.POA_REGISTRATION_DATE,'dd/MM/yyyy'),m.H_LOCK_STATUS_NAME,t.PURPOSE,TO_CHAR(t.LOCK_DATE,'dd/MM/yyyy')  "+
"FROM IGRS_PROP_LOCK_TXN_DETLS t, IGRS_PROP_LOCK_STATUS_MASTER m "+
"WHERE m.LOCK_STATUS_ID=t.LOCK_STATUS_ID AND t.REGISTRATION_NUMBER=? AND t.PROPERTY_TXN_ID=? "+
"AND t.PROPERTY_LOCK_ID=? AND t.LOCK_STATUS_ID=2";

public static final String TXN_DETL_REL ="SELECT t.PROPERTY_LOCK_ID,t.REGISTRATION_NUMBER,TO_CHAR(t.REGISTRATION_DATE,'dd/MM/yyyy'),t.PROPERTY_TXN_ID, "+
                                         "t.POA_REGISTRATION_ID,TO_CHAR(t.POA_REGISTRATION_DATE,'dd/MM/yyyy'),m.LOCK_STATUS_NAME,t.PURPOSE,TO_CHAR(t.RELEASE_DATE,'dd/MM/yyyy'),t.RELEASE_REMARKS,t.RELEASER_TYPE_ID  "+
                                         "FROM IGRS_PROP_LOCK_TXN_DETLS t, IGRS_PROP_LOCK_STATUS_MASTER m "+
                                         "WHERE m.LOCK_STATUS_ID=t.LOCK_STATUS_ID AND t.REGISTRATION_NUMBER=? AND t.PROPERTY_TXN_ID=? "+
                                         "AND t.PROPERTY_LOCK_ID=? AND t.LOCK_STATUS_ID=1 AND t.STATUS_FLAG='A'";

//added by shruti
public static final String TXN_DETL_REL_H ="SELECT t.PROPERTY_LOCK_ID,t.REGISTRATION_NUMBER,TO_CHAR(t.REGISTRATION_DATE,'dd/MM/yyyy'),t.PROPERTY_TXN_ID, "+
"t.POA_REGISTRATION_ID,TO_CHAR(t.POA_REGISTRATION_DATE,'dd/MM/yyyy'),m.H_LOCK_STATUS_NAME,t.PURPOSE,TO_CHAR(t.RELEASE_DATE,'dd/MM/yyyy'),t.RELEASE_REMARKS,t.RELEASER_TYPE_ID  "+
"FROM IGRS_PROP_LOCK_TXN_DETLS t, IGRS_PROP_LOCK_STATUS_MASTER m "+
"WHERE m.LOCK_STATUS_ID=t.LOCK_STATUS_ID AND t.REGISTRATION_NUMBER=? AND t.PROPERTY_TXN_ID=? "+
"AND t.PROPERTY_LOCK_ID=? AND t.LOCK_STATUS_ID=1 AND t.STATUS_FLAG='A'";
//end

public static final String TXN_DETL_REL_VIEW ="SELECT t.PROPERTY_LOCK_ID,t.REGISTRATION_NUMBER,TO_CHAR(t.REGISTRATION_DATE,'dd/MM/yyyy'),t.PROPERTY_TXN_ID, "+
                                              "t.POA_REGISTRATION_ID,TO_CHAR(t.POA_REGISTRATION_DATE,'dd/MM/yyyy'),m.LOCK_STATUS_NAME,t.PURPOSE,TO_CHAR(t.RELEASE_DATE,'dd/MM/yyyy'),t.RELEASE_REMARKS,t.RELEASER_TYPE_ID  "+
                                              "FROM IGRS_PROP_LOCK_TXN_DETLS t, IGRS_PROP_LOCK_STATUS_MASTER m "+
                                              "WHERE m.LOCK_STATUS_ID=t.LOCK_STATUS_ID AND t.REGISTRATION_NUMBER=? AND t.PROPERTY_TXN_ID=? "+
                                              "AND t.PROPERTY_LOCK_ID=? AND t.LOCK_STATUS_ID=1";


public static final String TXN_DETL_REL_P ="SELECT t.PROPERTY_LOCK_ID,t.REGISTRATION_NUMBER,TO_CHAR(t.REGISTRATION_DATE,'dd/MM/yyyy'),t.PROPERTY_TXN_ID, "+
                                           "t.POA_REGISTRATION_ID,TO_CHAR(t.POA_REGISTRATION_DATE,'dd/MM/yyyy'),m.LOCK_STATUS_NAME,t.PURPOSE,TO_CHAR(t.CREATED_DATE,'dd/MM/yyyy'),t.RELEASE_REMARKS,t.RELEASER_TYPE_ID  "+
                                           "FROM IGRS_PROP_LOCK_TXN_DETLS t, IGRS_PROP_LOCK_STATUS_MASTER m "+
                                           "WHERE m.LOCK_STATUS_ID=t.LOCK_STATUS_ID AND t.REGISTRATION_NUMBER=? AND t.PROPERTY_TXN_ID=? "+
                                           "AND t.PROPERTY_LOCK_ID=? AND t.LOCK_STATUS_ID=4 AND t.STATUS_FLAG='A'";

//added by shruti

public static final String TXN_DETL_REL_P_H ="SELECT t.PROPERTY_LOCK_ID,t.REGISTRATION_NUMBER,TO_CHAR(t.REGISTRATION_DATE,'dd/MM/yyyy'),t.PROPERTY_TXN_ID, "+
                                           "t.POA_REGISTRATION_ID,TO_CHAR(t.POA_REGISTRATION_DATE,'dd/MM/yyyy'),m.H_LOCK_STATUS_NAME,t.PURPOSE,TO_CHAR(t.CREATED_DATE,'dd/MM/yyyy'),t.RELEASE_REMARKS,t.RELEASER_TYPE_ID  "+
                                           "FROM IGRS_PROP_LOCK_TXN_DETLS t, IGRS_PROP_LOCK_STATUS_MASTER m "+
                                           "WHERE m.LOCK_STATUS_ID=t.LOCK_STATUS_ID AND t.REGISTRATION_NUMBER=? AND t.PROPERTY_TXN_ID=? "+
                                           "AND t.PROPERTY_LOCK_ID=? AND t.LOCK_STATUS_ID=4 AND t.STATUS_FLAG='A'";
//end
public static final String TXN_DETL_AP = "SELECT t.PROPERTY_LOCK_ID,t.REGISTRATION_NUMBER,TO_CHAR(t.REGISTRATION_DATE,'dd/MM/yyyy'),t.PROPERTY_TXN_ID, "+
                                         "t.POA_REGISTRATION_ID,TO_CHAR(t.POA_REGISTRATION_DATE,'dd/MM/yyyy'),m.LOCK_STATUS_NAME,t.PURPOSE,TO_CHAR(t.LOCK_DATE,'dd/MM/yyyy')  "+
                                         "FROM IGRS_PROP_LOCK_TXN_DETLS t, IGRS_PROP_LOCK_STATUS_MASTER m "+
                                         "WHERE m.LOCK_STATUS_ID=t.LOCK_STATUS_ID AND t.REGISTRATION_NUMBER=? AND t.PROPERTY_TXN_ID=? "+
                                         "AND t.PROPERTY_LOCK_ID=? AND t.LOCK_STATUS_ID=2 AND t.STATUS_FLAG='A'";

//added by shruti
public static final String TXN_DETL_AP_H = "SELECT t.PROPERTY_LOCK_ID,t.REGISTRATION_NUMBER,TO_CHAR(t.REGISTRATION_DATE,'dd/MM/yyyy'),t.PROPERTY_TXN_ID, "+
"t.POA_REGISTRATION_ID,TO_CHAR(t.POA_REGISTRATION_DATE,'dd/MM/yyyy'),m.H_LOCK_STATUS_NAME,t.PURPOSE,TO_CHAR(t.LOCK_DATE,'dd/MM/yyyy')  "+
"FROM IGRS_PROP_LOCK_TXN_DETLS t, IGRS_PROP_LOCK_STATUS_MASTER m "+
"WHERE m.LOCK_STATUS_ID=t.LOCK_STATUS_ID AND t.REGISTRATION_NUMBER=? AND t.PROPERTY_TXN_ID=? "+
"AND t.PROPERTY_LOCK_ID=? AND t.LOCK_STATUS_ID=2 AND t.STATUS_FLAG='A'";
//end
public static final String TXN_DETLP = "SELECT t.PROPERTY_LOCK_ID,t.REGISTRATION_NUMBER,TO_CHAR(t.REGISTRATION_DATE,'dd/MM/yyyy'),t.PROPERTY_TXN_ID, "+
                                       "t.POA_REGISTRATION_ID,TO_CHAR(t.POA_REGISTRATION_DATE,'dd/MM/yyyy'),m.LOCK_STATUS_NAME,t.PURPOSE,TO_CHAR(t.CREATED_DATE,'dd/MM/yyyy')  "+
                                       "FROM IGRS_PROP_LOCK_TXN_DETLS t, IGRS_PROP_LOCK_STATUS_MASTER m "+
                                       "WHERE m.LOCK_STATUS_ID=t.LOCK_STATUS_ID AND t.REGISTRATION_NUMBER=? AND t.PROPERTY_TXN_ID=? "+
                                       "AND t.PROPERTY_LOCK_ID=? AND t.LOCK_STATUS_ID=3 AND t.STATUS_FLAG='A'";
//added by shruti

public static final String TXN_DETLP_H = "SELECT t.PROPERTY_LOCK_ID,t.REGISTRATION_NUMBER,TO_CHAR(t.REGISTRATION_DATE,'dd/MM/yyyy'),t.PROPERTY_TXN_ID, "+
"t.POA_REGISTRATION_ID,TO_CHAR(t.POA_REGISTRATION_DATE,'dd/MM/yyyy'),m.H_LOCK_STATUS_NAME,t.PURPOSE,TO_CHAR(t.CREATED_DATE,'dd/MM/yyyy')  "+
"FROM IGRS_PROP_LOCK_TXN_DETLS t, IGRS_PROP_LOCK_STATUS_MASTER m "+
"WHERE m.LOCK_STATUS_ID=t.LOCK_STATUS_ID AND t.REGISTRATION_NUMBER=? AND t.PROPERTY_TXN_ID=? "+
"AND t.PROPERTY_LOCK_ID=? AND t.LOCK_STATUS_ID=3 AND t.STATUS_FLAG='A'";

//end
/*public static final String PARTY_DETL ="SELECT t.APPELLATE_TYPE_ID,a.APPELLATE_TYPE_NAME, t.PARTY_FIRST_NAME, t.PARTY_MIDDLE_NAME, t.PARTY_LAST_NAME, t.PARTY_GENDER, t.PARTY_AGE, "+
                                       "c.COUNTRY_NAME,s.STATE_NAME,d.DISTRICT_NAME,t.PARTY_ADDRESS,t.POSTAL_CODE,t.PHONE_NUMBER,t.MOBILE_NUMBER,t.EMAIL_ID, "+
                                       "p.PHOTO_PROOF_TYPE_NAME,t.PHOTO_PROOF_NUMBER,t.BANK_NAME, t.BANK_ADDRESS,t.ORGANIZATION_NAME,t.AUTHRZD_PERSN_NAME, "+
                                       "t.GUARDIAN_NAME,t.MOTHER_NAME,t.PHOTO_NAME,t.THUMB_NAME,t.SIGNATURE_NAME,t.PHOTO_PATH,t.THUMB_PATH,t.SIGNATURE_PATH " +
		                               "FROM IGRS_PROP_LOCK_TXN_PARTY_DETLS t, IGRS_APPELLATE_TYPE_MASTER a, IGRS_COUNTRY_MASTER c, IGRS_STATE_MASTER s, "+
                                       "IGRS_DISTRICT_MASTER d, IGRS_PHOTOID_PROOF_TYPE_MASTER p "+
                                       "WHERE t.APPELLATE_TYPE_ID=a.APPELLATE_TYPE_ID AND t.COUNTRY_ID=c.COUNTRY_ID AND t.STATE_ID=s.STATE_ID AND t.DISTRICT_ID=d.DISTRICT_ID "+
                                       "AND t.PHOTO_PROOF_TYPE_ID=p.PHOTO_PROOF_TYPE_ID AND t.PROPERTY_LOCK_ID=?";
*/



public static final String PARTY_DETL="SELECT t.APPELLATE_TYPE_ID,a.APPELLATE_TYPE_NAME, t.PARTY_FIRST_NAME, t.PARTY_MIDDLE_NAME, t.PARTY_LAST_NAME, t.PARTY_GENDER, "+ 
	                                  "t.PARTY_AGE, c.COUNTRY_NAME,s.STATE_NAME,d.DISTRICT_NAME,t.PARTY_ADDRESS,t.POSTAL_CODE,t.PHONE_NUMBER,t.MOBILE_NUMBER,t.EMAIL_ID," +
	                                  "	  t.BANK_NAME, t.BANK_ADDRESS,t.ORGANIZATION_NAME,t.AUTHRZD_PERSN_NAME, t.GUARDIAN_NAME," +
	                                  "	  t.MOTHER_NAME,t.PHOTO_NAME,t.THUMB_NAME,t.SIGNATURE_NAME,t.PHOTO_PATH,t.THUMB_PATH,t.SIGNATURE_PATH," +
	                                  "   t.COUNTRY_ID,t.STATE_ID,t.DISTRICT_ID"+
	                                  "	  FROM IGRS_PROP_LOCK_TXN_PARTY_DETLS t, IGRS_APPELLATE_TYPE_MASTER a, IGRS_COUNTRY_MASTER c, IGRS_STATE_MASTER s, IGRS_DISTRICT_MASTER d" +
	                                  "	  WHERE a.APPELLATE_TYPE_ID=t.APPELLATE_TYPE_ID AND c.COUNTRY_ID=t.COUNTRY_ID AND s.STATE_ID=t.STATE_ID" +
	                                  "	  AND d.DISTRICT_ID=t.DISTRICT_ID AND t.PROPERTY_LOCK_ID=? AND a.APPELLATE_TYPE_ID IN(1,2)";

//added by shruti
public static final String PARTY_DETL_H="SELECT t.APPELLATE_TYPE_ID,a.H_APPELLATE_TYPE_NAME, t.PARTY_FIRST_NAME, t.PARTY_MIDDLE_NAME, t.PARTY_LAST_NAME, t.PARTY_GENDER, "+ 
"t.PARTY_AGE, c.H_COUNTRY_NAME,s.H_STATE_NAME,d.H_DISTRICT_NAME,t.PARTY_ADDRESS,t.POSTAL_CODE,t.PHONE_NUMBER,t.MOBILE_NUMBER,t.EMAIL_ID," +
"	  t.BANK_NAME, t.BANK_ADDRESS,t.ORGANIZATION_NAME,t.AUTHRZD_PERSN_NAME, t.GUARDIAN_NAME," +
"	  t.MOTHER_NAME,t.PHOTO_NAME,t.THUMB_NAME,t.SIGNATURE_NAME,t.PHOTO_PATH,t.THUMB_PATH,t.SIGNATURE_PATH," +
"   t.COUNTRY_ID,t.STATE_ID,t.DISTRICT_ID"+
"	  FROM IGRS_PROP_LOCK_TXN_PARTY_DETLS t, IGRS_APPELLATE_TYPE_MASTER a, IGRS_COUNTRY_MASTER c, IGRS_STATE_MASTER s, IGRS_DISTRICT_MASTER d" +
"	  WHERE a.APPELLATE_TYPE_ID=t.APPELLATE_TYPE_ID AND c.COUNTRY_ID=t.COUNTRY_ID AND s.STATE_ID=t.STATE_ID" +
"	  AND d.DISTRICT_ID=t.DISTRICT_ID AND t.PROPERTY_LOCK_ID=? AND a.APPELLATE_TYPE_ID IN(1,2)";
//end

public static final String RELATIVE_DETL= "SELECT t.RELATIVE_NAME,a.RELATIVE_TYPE_NAME, t.RELATIVE_FATHERNAME, t.RELATIVE_MOTHERNAME, "+ 
                                          "c.COUNTRY_NAME,s.STATE_NAME,d.DISTRICT_NAME,t.RELATIVE_ADDRESS,t.RELATIVE_MOB,t.RELATIVE_PHONE,t.RELATIVE_EMAIL," +
                                          "	t.DEATH_CERTIFICATE_NAME,t.RELATIVE_PHOTO_NAME,t.RELATIVE_THUMB_NAME,t.RELATIVE_SIGNATURE_NAME,t.DEATH_CERTIFICATE_PATH,t.RELATIVE_PHOTO_PATH,t.RELATIVE_THUMB_PATH,t.RELATIVE_SIGNATURE_PATH," +
                                          " t.COUNTRY_ID,t.STATE_ID,t.DISTRICT_ID"+
                                          "	  FROM IGRS_PROP_LOCK_RELATIVE_DETLS t, IGRS_RELATIVE_TYPE_MASTER a, IGRS_COUNTRY_MASTER c, IGRS_STATE_MASTER s, IGRS_DISTRICT_MASTER d" +
                                          "	  WHERE a.RELATIVE_TYPE_ID=t.RELATIVE_TYPE_ID AND c.COUNTRY_ID=t.COUNTRY_ID AND s.STATE_ID=t.STATE_ID" +
                                          "	  AND d.DISTRICT_ID=t.DISTRICT_ID AND t.PROPERTY_LOCK_ID=?";
//added by shruti
public static final String RELATIVE_DETL_H= "SELECT t.RELATIVE_NAME,a.H_RELATIVE_TYPE_NAME, t.RELATIVE_FATHERNAME, t.RELATIVE_MOTHERNAME, "+ 
"c.H_COUNTRY_NAME,s.H_STATE_NAME,d.H_DISTRICT_NAME,t.RELATIVE_ADDRESS,t.RELATIVE_MOB,t.RELATIVE_PHONE,t.RELATIVE_EMAIL," +
"	t.DEATH_CERTIFICATE_NAME,t.RELATIVE_PHOTO_NAME,t.RELATIVE_THUMB_NAME,t.RELATIVE_SIGNATURE_NAME,t.DEATH_CERTIFICATE_PATH,t.RELATIVE_PHOTO_PATH,t.RELATIVE_THUMB_PATH,t.RELATIVE_SIGNATURE_PATH," +
" t.COUNTRY_ID,t.STATE_ID,t.DISTRICT_ID"+
"	  FROM IGRS_PROP_LOCK_RELATIVE_DETLS t, IGRS_RELATIVE_TYPE_MASTER a, IGRS_COUNTRY_MASTER c, IGRS_STATE_MASTER s, IGRS_DISTRICT_MASTER d" +
"	  WHERE a.RELATIVE_TYPE_ID=t.RELATIVE_TYPE_ID AND c.COUNTRY_ID=t.COUNTRY_ID AND s.STATE_ID=t.STATE_ID" +
"	  AND d.DISTRICT_ID=t.DISTRICT_ID AND t.PROPERTY_LOCK_ID=?";
//end

public static final String PHOTO_DETL="SELECT t.PHOTO_PROOF_NUMBER,p.PHOTO_PROOF_TYPE_NAME,t.PHOTO_PROOF_TYPE_ID FROM IGRS_PROP_LOCK_TXN_PARTY_DETLS t,IGRS_PHOTOID_PROOF_TYPE_MASTER p" +
		                              "	  WHERE p.PHOTO_PROOF_TYPE_ID=t.PHOTO_PROOF_TYPE_ID AND t.PROPERTY_LOCK_ID=?";

//added by shruti
public static final String PHOTO_DETL_H="SELECT t.PHOTO_PROOF_NUMBER,p.H_PHOTO_PROOF_TYPE_NAME,t.PHOTO_PROOF_TYPE_ID FROM IGRS_PROP_LOCK_TXN_PARTY_DETLS t,IGRS_PHOTOID_PROOF_TYPE_MASTER p" +
"	  WHERE p.PHOTO_PROOF_TYPE_ID=t.PHOTO_PROOF_TYPE_ID AND t.PROPERTY_LOCK_ID=?";
//end
public static final String GET_REGINIT_ID ="SELECT REG_TXN_ID FROM IGRS_REG_TXN_DETLS WHERE REGISTRATION_NUMBER=?";

//added by shruti---14 may 2014
public static final String GET_INSTRUMENT_FLAG ="SELECT PROP_VAL_REQ_FLAG FROM IGRS_DEED_INSTRUMENT_MASTER I,IGRS_REG_TXN_DETLS R WHERE I.INSTRUMENT_ID=R.INSTRUMENTS_ID AND R.REG_TXN_ID=?";

//end
public static final String GET_PAY_DTLS = "SELECT PAYMENT_DETL_ID, PAYABLE_AMOUNT, PAID_AMOUNT, PAYMENT_FLAG FROM IGRS_PROP_LOCK_PAYMENT_DETLS "+
                                          "WHERE PROPERTY_LOCK_ID = ? AND CREATED_DATE = (SELECT MAX(CREATED_DATE)FROM IGRS_PROP_LOCK_PAYMENT_DETLS WHERE PROPERTY_LOCK_ID = ?)";

public static final String PAY_TABLE_INSERT = "INSERT INTO IGRS_PROP_LOCK_PAYMENT_DETLS"+
                                              " (PAYMENT_DETL_ID, PROPERTY_LOCK_ID, PAYABLE_AMOUNT,"+
                                              "  PAYMENT_FLAG, CREATED_BY, CREATED_DATE,FUNCTION_ID)"+
                                              " VALUES(?,?,?,?,?, SYSDATE,?)";

public static final String GET_MAIN_ID = "SELECT PROPERTY_LOCK_ID FROM IGRS_PROP_LOCK_PAYMENT_DETLS WHERE PAYMENT_DETL_ID = ? ";

public static final String PAY_FLAG_UPDTAE = "UPDATE IGRS_PROP_LOCK_PAYMENT_DETLS SET PAYMENT_FLAG='C',UPDATE_BY=?, UPDATE_DATE=SYSDATE "+ 
                                             "WHERE PROPERTY_LOCK_ID=? AND PAYMENT_FLAG='P'";

public static final String TXN_STATUS_UPDATE = "UPDATE IGRS_PROP_LOCK_TXN_DETLS SET LOCK_STATUS_ID=2,UPDATE_BY=?,UPDATE_DATE=SYSDATE, LOCK_DATE=SYSDATE,OFFICE_ID=? "+ 
                                               "WHERE PROPERTY_LOCK_ID=? AND LOCK_STATUS_ID=3 AND STATUS_FLAG='A'";


public static final String TXN_STATUS_UPDATE_REL = "UPDATE IGRS_PROP_LOCK_TXN_DETLS SET LOCK_STATUS_ID=1,UPDATE_BY=?,UPDATE_DATE=SYSDATE, RELEASE_DATE=SYSDATE,OFFICE_ID=? "+ 
                                                   "WHERE PROPERTY_LOCK_ID=? AND LOCK_STATUS_ID=4 AND STATUS_FLAG='A'";

public static final String PENDING_DETL = "SELECT t.PROPERTY_LOCK_ID,t.PROPERTY_TXN_ID,t.REGISTRATION_NUMBER,TO_CHAR(t.REGISTRATION_DATE,'dd/MM/yyyy'), m.LOCK_STATUS_NAME "+
	                                      "FROM IGRS_PROP_LOCK_TXN_DETLS t, IGRS_PROP_LOCK_STATUS_MASTER m "+
	                                      "WHERE t.LOCK_STATUS_ID=m.LOCK_STATUS_ID AND t.LOCK_STATUS_ID=3 AND t.STATUS_FLAG='A' AND t.CREATED_BY=?";

//added by shruti
public static final String PENDING_DETL_H = "SELECT t.PROPERTY_LOCK_ID,t.PROPERTY_TXN_ID,t.REGISTRATION_NUMBER,TO_CHAR(t.REGISTRATION_DATE,'dd/MM/yyyy'), m.H_LOCK_STATUS_NAME "+
"FROM IGRS_PROP_LOCK_TXN_DETLS t, IGRS_PROP_LOCK_STATUS_MASTER m "+
"WHERE t.LOCK_STATUS_ID=m.LOCK_STATUS_ID AND t.LOCK_STATUS_ID=3 AND t.STATUS_FLAG='A' AND t.CREATED_BY=?";
//end

public static final String PENDING_DETL_R = "SELECT t.PROPERTY_LOCK_ID,t.PROPERTY_TXN_ID,t.REGISTRATION_NUMBER,TO_CHAR(t.REGISTRATION_DATE,'dd/MM/yyyy'), m.LOCK_STATUS_NAME "+
                                            "FROM IGRS_PROP_LOCK_TXN_DETLS t, IGRS_PROP_LOCK_STATUS_MASTER m "+
                                            "WHERE t.LOCK_STATUS_ID=m.LOCK_STATUS_ID AND t.LOCK_STATUS_ID=4 AND t.STATUS_FLAG='A' AND t.CREATED_BY=?";

//added by shruti

public static final String PENDING_DETL_R_H = "SELECT t.PROPERTY_LOCK_ID,t.PROPERTY_TXN_ID,t.REGISTRATION_NUMBER,TO_CHAR(t.REGISTRATION_DATE,'dd/MM/yyyy'), m.H_LOCK_STATUS_NAME "+
                                            "FROM IGRS_PROP_LOCK_TXN_DETLS t, IGRS_PROP_LOCK_STATUS_MASTER m "+
                                            "WHERE t.LOCK_STATUS_ID=m.LOCK_STATUS_ID AND t.LOCK_STATUS_ID=4 AND t.STATUS_FLAG='A' AND t.CREATED_BY=?";
//end
public static final String GET_PAY_DTLS_V="SELECT SUM(PAID_AMOUNT), SUM(PAYABLE_AMOUNT) FROM IGRS_PROP_LOCK_PAYMENT_DETLS "+
                                          "WHERE PROPERTY_LOCK_ID =?";

public static final String REQ_DETL_QRY= "SELECT m.OFFICE_NAME, m.DISTRICT_ID, d.DISTRICT_NAME FROM IGRS_OFFICE_MASTER m, IGRS_DISTRICT_MASTER d " +
		                                 "WHERE  m.OFFICE_ID=? AND m.DISTRICT_ID =d.DISTRICT_ID";

}
