package com.wipro.igrs.guideline.sql;

public class GuidelineNewSQL {
	
	public static String SUB_AREA_NAME_EN="SELECT SUB_AREA_TYPE_ID,SUB_AREA_TYPE_NAME FROM IGRS_SUB_AREA_TYPE_MASTER WHERE AREA_TYPE_ID=? AND SUB_AREA_TYPE_STATUS='A' ORDER BY SUB_AREA_TYPE_NAME";
	
	public static String SUB_AREA_NAME_HI="SELECT SUB_AREA_TYPE_ID,H_SUB_AREA_TYPE_NAME FROM IGRS_SUB_AREA_TYPE_MASTER WHERE AREA_TYPE_ID=? AND SUB_AREA_TYPE_STATUS='A' ORDER BY H_SUB_AREA_TYPE_NAME";

	public static String SUB_AREA_NAME_EN_UR_FIRST="SELECT distinct SUB_AREA_TYPE_ID,SUB_AREA_TYPE_NAME FROM IGRS_SUB_AREA_TYPE_MASTER WHERE AREA_TYPE_ID=? AND SUB_AREA_TYPE_STATUS='A' AND TEHSIL_ID=? ORDER BY SUB_AREA_TYPE_NAME";
	
	public static String SUB_AREA_NAME_EN_UR="SELECT distinct IGRS_SUB_AREA_TYPE_MASTER.SUB_AREA_TYPE_ID,IGRS_SUB_AREA_TYPE_MASTER.SUB_AREA_TYPE_NAME FROM IGRS_SUB_AREA_TYPE_MASTER,IGRS_GUIDELINE_STATUS WHERE AREA_TYPE_ID=? AND SUB_AREA_TYPE_STATUS='A' AND IGRS_GUIDELINE_STATUS.TEHSIL_ID=? AND " +
			"IGRS_SUB_AREA_TYPE_MASTER.SUB_AREA_TYPE_ID = IGRS_GUIDELINE_STATUS.SUB_AREA_ID AND IGRS_GUIDELINE_STATUS.GUIDELINE_ID = ? AND IGRS_GUIDELINE_STATUS.MAKER_STATUS IN(1,3) ORDER BY IGRS_SUB_AREA_TYPE_MASTER.SUB_AREA_TYPE_NAME";
	
	public static String SUB_AREA_NAME_HI_UR="SELECT distinct IGRS_SUB_AREA_TYPE_MASTER.SUB_AREA_TYPE_ID,IGRS_SUB_AREA_TYPE_MASTER.H_SUB_AREA_TYPE_NAME FROM IGRS_SUB_AREA_TYPE_MASTER,IGRS_GUIDELINE_STATUS WHERE AREA_TYPE_ID=? AND SUB_AREA_TYPE_STATUS='A' AND IGRS_GUIDELINE_STATUS.TEHSIL_ID=? AND " +
	"IGRS_SUB_AREA_TYPE_MASTER.SUB_AREA_TYPE_ID = IGRS_GUIDELINE_STATUS.SUB_AREA_ID AND IGRS_GUIDELINE_STATUS.GUIDELINE_ID = ? AND IGRS_GUIDELINE_STATUS.MAKER_STATUS IN(1,3) ORDER BY IGRS_SUB_AREA_TYPE_MASTER.H_SUB_AREA_TYPE_NAME";

	
	public static String SUB_AREA_NAME_HI_UR_FIRST="SELECT distinct SUB_AREA_TYPE_ID,H_SUB_AREA_TYPE_NAME FROM IGRS_SUB_AREA_TYPE_MASTER WHERE AREA_TYPE_ID=? AND SUB_AREA_TYPE_STATUS='A' AND TEHSIL_ID=? ORDER BY H_SUB_AREA_TYPE_NAME";
	
	public static String WARD_PATWARI_NAME_EN_FIRST="SELECT distinct WPM.WARD_PATWARI_ID,WPM.WARD_PATWARI_NAME,WM.SUBAREA_WARD_MAPPING_ID FROM IGRS_WARD_PATWARI_MASTER WPM,IGRS_SUBAREA_WARD_MAPPING WM WHERE WM.WARD_PATWARI_ID=WPM.WARD_PATWARI_ID AND WM.SUB_AREA_TYPE_ID=? AND TEHSIL_ID =? AND WARD_PATWARI_STATUS='A' ORDER BY WPM.WARD_PATWARI_NAME";
	
	public static String WARD_PATWARI_NAME_EN= "SELECT distinct WPM.WARD_PATWARI_ID,WPM.WARD_PATWARI_NAME,WM.SUBAREA_WARD_MAPPING_ID FROM IGRS_WARD_PATWARI_MASTER WPM,IGRS_SUBAREA_WARD_MAPPING WM ,IGRS_GUIDELINE_STATUS st WHERE WM.WARD_PATWARI_ID=WPM.WARD_PATWARI_ID AND WPM.WARD_PATWARI_ID = st.WARD_PATWARI_ID AND WM.SUB_AREA_TYPE_ID=? AND  st.TEHSIL_ID = ? AND st.GUIDELINE_ID = ?  AND st.MAKER_STATUS IN(1,3)  AND WPM.WARD_PATWARI_STATUS = 'A' ORDER BY WPM.WARD_PATWARI_NAME";
	
	public static String WARD_PATWARI_NAME_HI_FIRST="SELECT distinct WPM.WARD_PATWARI_ID ,WPM.H_WARD_PATWARI_NAME,WM.SUBAREA_WARD_MAPPING_ID FROM IGRS_WARD_PATWARI_MASTER WPM,IGRS_SUBAREA_WARD_MAPPING WM WHERE WM.WARD_PATWARI_ID=WPM.WARD_PATWARI_ID AND WM.SUB_AREA_TYPE_ID=? AND TEHSIL_ID =? AND WARD_PATWARI_STATUS='A' ORDER BY WPM.H_WARD_PATWARI_NAME";
	
	public static String WARD_PATWARI_NAME_HI= "SELECT distinct WPM.WARD_PATWARI_ID,WPM.H_WARD_PATWARI_NAME,WM.SUBAREA_WARD_MAPPING_ID FROM IGRS_WARD_PATWARI_MASTER WPM,IGRS_SUBAREA_WARD_MAPPING WM ,IGRS_GUIDELINE_STATUS st WHERE WM.WARD_PATWARI_ID=WPM.WARD_PATWARI_ID AND WPM.WARD_PATWARI_ID = st.WARD_PATWARI_ID AND WM.SUB_AREA_TYPE_ID=? AND st.TEHSIL_ID = ? AND st.GUIDELINE_ID = ?  AND st.MAKER_STATUS IN(1,3)  AND WPM.WARD_PATWARI_STATUS = 'A' ORDER BY WPM.H_WARD_PATWARI_NAME";
	
	public static String COLONY_NAME_EN_FIRST="SELECT distinct C.COLONY_ID, C.COLONY_NAME,M.COLONY_WARD_MAPPING_ID,C.APPLICABLE_SUBCLAUSE_ID FROM IGRS_COLONY_MASTER C ,IGRS_COLONY_WARD_MAPPING M WHERE M.COLONY_ID=C.COLONY_ID AND C.COLONY_STATUS='A' AND M.SUBAREA_WARD_MAPPING_ID=? ORDER BY C.COLONY_NAME";
	
	public static String COLONY_NAME_EN="SELECT distinct C.COLONY_ID, C.COLONY_NAME,M.COLONY_WARD_MAPPING_ID,C.APPLICABLE_SUBCLAUSE_ID FROM IGRS_COLONY_MASTER C ,IGRS_COLONY_WARD_MAPPING M,IGRS_GUIDELINE_STATUS st WHERE M.COLONY_ID=C.COLONY_ID AND C.COLONY_STATUS='A' AND st.COLONY_ID = C.COLONY_ID AND st.GUIDELINE_ID = ? AND st.MAKER_STATUS IN(1,3) AND M.SUBAREA_WARD_MAPPING_ID = ? ORDER BY C.COLONY_NAME";
	
	public static String COLONY_NAME_HI_FIRST="SELECT distinct C.COLONY_ID, C.H_COLONY_NAME,M.COLONY_WARD_MAPPING_ID,C.APPLICABLE_SUBCLAUSE_ID FROM IGRS_COLONY_MASTER C ,IGRS_COLONY_WARD_MAPPING M WHERE M.COLONY_ID=C.COLONY_ID AND C.COLONY_STATUS='A' AND M.SUBAREA_WARD_MAPPING_ID=? ORDER BY C.H_COLONY_NAME";
	
	public static String COLONY_NAME_HI="SELECT distinct C.COLONY_ID, C.H_COLONY_NAME,M.COLONY_WARD_MAPPING_ID,C.APPLICABLE_SUBCLAUSE_ID FROM IGRS_COLONY_MASTER C ,IGRS_COLONY_WARD_MAPPING M,IGRS_GUIDELINE_STATUS st WHERE M.COLONY_ID=C.COLONY_ID AND C.COLONY_STATUS='A' AND st.COLONY_ID = C.COLONY_ID AND st.GUIDELINE_ID = ? AND st.MAKER_STATUS IN(1,3) AND M.SUBAREA_WARD_MAPPING_ID = ? ORDER BY C.H_COLONY_NAME";
	
	public static final String GET_PROPERTY_DETAILS_FOR_PV = "(SELECT IGRS_PROPERTY_TYPE_MASTER.property_type_id ,IGRS_PROP_TYPE_L1_MASTER_DUMMY.prop_type_l1_id,IGRS_PROP_TYPE_L2_MASTER_DUMMY.property_type_l2_id,IGRS_PROP_TYPE_L1_MASTER_DUMMY.COMPUTATION_LOGIC,IGRS_PROP_TYPE_L2_MASTER_DUMMY.COMPUTATION_LOGIC "
			+ "FROM ((IGRS_PROPERTY_TYPE_MASTER LEFT OUTER JOIN IGRS_PROP_TYPE_L1_MASTER_DUMMY ON " 
			+ "(IGRS_PROP_TYPE_L1_MASTER_DUMMY.property_type_id=IGRS_PROPERTY_TYPE_MASTER.property_type_id  ))  "
			+ "LEFT OUTER JOIN IGRS_PROP_TYPE_L2_MASTER_DUMMY ON (IGRS_PROP_TYPE_L2_MASTER_DUMMY.property_type_l1_id=IGRS_PROP_TYPE_L1_MASTER_DUMMY.PROP_TYPE_L1_ID )) LEFT OUTER JOIN "
			+ "igrs_uom_master ON (IGRS_PROP_TYPE_L1_MASTER_DUMMY.uom_id = igrs_uom_master.uom_id) WHERE  "
			+ "IGRS_PROPERTY_TYPE_MASTER.PROPERTY_TYPE_STATUS = 'A' AND IGRS_PROP_TYPE_L1_MASTER_DUMMY.PROP_TYPE_L1_STATUS = 'A' AND  "
			+ "IGRS_PROP_TYPE_L2_MASTER_DUMMY.PROPERTY_TYPE_L2_STATUS ='A' OR IGRS_PROP_TYPE_L2_MASTER_DUMMY.PROPERTY_TYPE_L2_STATUS IS NULL MINUS "
			+ "SELECT IGRS_PROPERTY_TYPE_MASTER.property_type_id,IGRS_PROP_TYPE_L1_MASTER_DUMMY.prop_type_l1_id, IGRS_PROP_TYPE_L2_MASTER_DUMMY.property_type_l2_id,IGRS_PROP_TYPE_L1_MASTER_DUMMY.COMPUTATION_LOGIC,IGRS_PROP_TYPE_L2_MASTER_DUMMY.COMPUTATION_LOGIC "
			+ "FROM ((IGRS_PROPERTY_TYPE_MASTER LEFT OUTER JOIN IGRS_PROP_TYPE_L1_MASTER_DUMMY ON  "
			+ "(IGRS_PROP_TYPE_L1_MASTER_DUMMY.property_type_id=IGRS_PROPERTY_TYPE_MASTER.property_type_id AND IGRS_PROP_TYPE_L1_MASTER_DUMMY.DISPLAY_FLAG_GUIDLN = 'Y' ))  "
			+ "LEFT OUTER JOIN IGRS_PROP_TYPE_L2_MASTER_DUMMY ON (IGRS_PROP_TYPE_L2_MASTER_DUMMY.property_type_l1_id=IGRS_PROP_TYPE_L1_MASTER_DUMMY.PROP_TYPE_L1_ID AND "
			+ " (IGRS_PROP_TYPE_L2_MASTER_DUMMY.DISPLAY_FLAG = 'G' OR IGRS_PROP_TYPE_L2_MASTER_DUMMY.DISPLAY_FLAG = 'B'))) LEFT OUTER JOIN "
			+ " igrs_uom_master ON (IGRS_PROP_TYPE_L1_MASTER_DUMMY.uom_id = igrs_uom_master.uom_id) WHERE  "
			+ "IGRS_PROPERTY_TYPE_MASTER.PROPERTY_TYPE_STATUS = 'A' AND IGRS_PROP_TYPE_L1_MASTER_DUMMY.PROP_TYPE_L1_STATUS = 'A' AND  "
			+ "IGRS_PROP_TYPE_L2_MASTER_DUMMY.PROPERTY_TYPE_L2_STATUS ='A' OR IGRS_PROP_TYPE_L2_MASTER_DUMMY.PROPERTY_TYPE_L2_STATUS IS NULL)";
	
	public static String SUB_AREA_NAME_EN_RURAL="select count(*) from (SELECT distinct SUB_AREA_ID " +
	"FROM IGRS_GUIDELINE_STATUS " +
	"WHERE IGRS_GUIDELINE_STATUS.TEHSIL_ID            =? "+
	"AND IGRS_GUIDELINE_STATUS.GUIDELINE_ID         = ? "+
	"AND IGRS_GUIDELINE_STATUS.MAKER_STATUS        IN(1,3) "+
	"AND IGRS_GUIDELINE_STATUS.SUB_AREA_ID IN (5,6)) ";
	
	public static String SUB_AREA_NAME_EN_URBAN="select count(*) from (SELECT distinct SUB_AREA_ID " +
	"FROM IGRS_GUIDELINE_STATUS " +
	"WHERE IGRS_GUIDELINE_STATUS.TEHSIL_ID            =? "+
	"AND IGRS_GUIDELINE_STATUS.GUIDELINE_ID         = ? "+
	"AND IGRS_GUIDELINE_STATUS.MAKER_STATUS        IN(1,3) "+
	"AND IGRS_GUIDELINE_STATUS.SUB_AREA_ID NOT IN (5,6)) ";
	
	public static String SUB_AREA_NAME_EN_GIDCNT="select count(*) from (SELECT distinct MAKER_STATUS " +
	"FROM IGRS_GUIDELINE_STATUS " +
	"WHERE IGRS_GUIDELINE_STATUS.GUIDELINE_ID         = ? "+
	"AND IGRS_GUIDELINE_STATUS.MAKER_STATUS        IN(1,3))";

	
}
