package com.wipro.igrs.visitBooking.sql;

/**
 * ===========================================================================
 * File           :   CommonSQL.java
 * Description    :   Represents the SQL Class

 * Author         :   Pavani  Param
 * Created Date   :   Dec  20, 2007

 * ===========================================================================
 */
public class CommonSQL {

   ///--START----PARTY DETAILS
   public static final String VISIT_DET_INSERT = "INSERT INTO IGRS_VISIT_BOOKING_TXN(VISIT_TXN_ID," +
   		"APP_FIRST_NAME,APP_MIDDLE_NAME,APP_LAST_NAME,APP_GENDER,APP_AGE,APP_GUARDIAN_NAME," +
   		"APP_MOTHER_NAME,APP_COUNTRY_ID,APP_STATE_ID,APP_DISTRICT_ID,APP_ADDRESS,APP_POSTAL_CODE," +
   		"APP_PHONE_NUMBER,APP_MOBILE_NUMBER,APP_EMAIL,PHOTO_PROOF_TYPE_ID,PHOTO_PROOF_ID,BANK_NAME," +
   		"BANK_ADDRESS,REQ_FIRST_NAME,REQ_MIDDLE_NAME,REQ_LAST_NAME,REQUEST_PURPOSE," +
   		"REG_INITIATION_ID,REQ_DATE,REQ_TIME,REQ_PHONE_NUMBER,REQ_MOBILE_NUMBER,REQ_DISTRICT_ID," +
   		"REQ_ADDRESS,REQ_POSTAL_CODE,TOTAL_AMOUNT,FEE,OTHERS,PAYMENT_TXN_ID,VISIT_STATUS,CREATED_BY,CREATED_DATE)" +
   		" VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,'A','user',SYSDATE)" ;
	   
   
   
   public static final String VISIT_REF_ID_SELECT = "SELECT REG_INITIATION_ID,VISIT_TXN_ID  " +
   		"FROM IGRS_VISIT_BOOKING_TXN ORDER BY VISIT_TXN_ID DESC"; 
   
   
   public static final String VISIT_PRINT_DET="SELECT IVBT.REG_INITIATION_ID,IVBT.VISIT_TXN_ID," +
   		"  TO_CHAR(IVBT.CREATED_DATE,'dd/mm/yyyy'),IVBT.APP_FIRST_NAME,IVBT.APP_MIDDLE_NAME,IVBT.APP_LAST_NAME,IVBT.REQ_FIRST_NAME," +
   		"  IVBT.REQ_MIDDLE_NAME ,IVBT.REQ_LAST_NAME,IVBT.REQUEST_PURPOSE,TO_CHAR(IVBT.REQ_DATE,'dd/mm/yyyy')," +
   		"  IVBT.REQ_TIME,IVBT.REQ_ADDRESS,IDM.DISTRICT_NAME,IVBT.REQ_POSTAL_CODE,IVBT.TOTAL_AMOUNT" +
   		"  FROM IGRS_VISIT_BOOKING_TXN IVBT,IGRS_DISTRICT_MASTER IDM " +
   		"  WHERE IVBT.REQ_DISTRICT_ID= IDM.DISTRICT_ID AND  VISIT_TXN_ID=?";   

      public static final String VISIT_VIEW_REFID_QUERY="SELECT VISIT_TXN_ID,TO_CHAR(CREATED_DATE,'dd/mm/yyyy'),REG_INITIATION_ID, " +
      		"TO_CHAR(REQ_DATE,'dd/mm/yyyy'),VISIT_STATUS FROM IGRS_VISIT_BOOKING_TXN WHERE VISIT_TXN_ID=?";
     
      public static final String VISIT_VIEW_STATUS_QUERY="SELECT VISIT_TXN_ID,TO_CHAR(CREATED_DATE,'dd/mm/yyyy'),REG_INITIATION_ID, " +
		"TO_CHAR(REQ_DATE,'dd/mm/yyyy'),VISIT_STATUS FROM IGRS_VISIT_BOOKING_TXN WHERE VISIT_STATUS=?";
      
      public static final String VISIT_VIEW_DATE_QUERY="SELECT VISIT_TXN_ID,TO_CHAR(CREATED_DATE,'dd/mm/yyyy'),REG_INITIATION_ID, " +
		"TO_CHAR(REQ_DATE,'dd/mm/yyyy'),VISIT_STATUS FROM IGRS_VISIT_BOOKING_TXN WHERE CREATED_DATE BETWEEN ? AND ?";
      
      
      
   public static final String VISIT_VIEW_DET="SELECT IVBT.VISIT_TXN_ID,IVBT.APP_FIRST_NAME,IVBT.APP_MIDDLE_NAME,IVBT.APP_LAST_NAME,IVBT.APP_GENDER,IVBT.APP_AGE,IVBT.APP_GUARDIAN_NAME,IVBT.APP_MOTHER_NAME,IVBT.APP_ADDRESS,ICM.COUNTRY_NAME ,ISM.STATE_NAME,IDM.DISTRICT_NAME,IVBT.APP_POSTAL_CODE ,IVBT.APP_PHONE_NUMBER,IVBT.APP_MOBILE_NUMBER,IVBT.APP_EMAIL,IP.PHOTO_PROOF_TYPE_NAME,IVBT.PHOTO_PROOF_ID,IVBT.BANK_NAME,IVBT.BANK_ADDRESS,IVBT.REG_INITIATION_ID,IVBT.REQ_FIRST_NAME,IVBT.REQ_MIDDLE_NAME ,IVBT.REQ_LAST_NAME,IVBT.REQ_PHONE_NUMBER,IVBT.REQ_MOBILE_NUMBER, IVBT.REQUEST_PURPOSE,TO_CHAR(IVBT.REQ_DATE,'dd/mm/yyyy'),IVBT.REQ_TIME,IVBT.REQ_ADDRESS,IDM.DISTRICT_NAME,IVBT.REQ_POSTAL_CODE,IVBT.TOTAL_AMOUNT,IVBT.FEE,IVBT.OTHERS FROM IGRS_VISIT_BOOKING_TXN IVBT,IGRS_DISTRICT_MASTER IDM ,IGRS_COUNTRY_MASTER ICM,IGRS_STATE_MASTER ISM,IGRS_PHOTOID_PROOF_TYPE_MASTER IP WHERE IVBT.APP_DISTRICT_ID = IDM.DISTRICT_ID AND IVBT.APP_COUNTRY_ID = ICM.COUNTRY_ID AND IVBT.APP_STATE_ID = ISM.STATE_ID AND IVBT.PHOTO_PROOF_TYPE_ID=IP.PHOTO_PROOF_TYPE_ID AND VISIT_TXN_ID like ";  

      
      
      public static final String VISIT_REM_DET="SELECT    VISIT_TXN_ID,COMMENTS FROM IGRS_VISIT_BOOKING_COMMENTS  WHERE   VISIT_TXN_ID =";
      


      public static final String VISIT_BOOK_FEE_QUERY=" SELECT IMAP.FUNCTION_ID,IMAP.PARAM_VALUE,IMAS.PARAM_NAME" +
 		" FROM IGRS_SERVICE_FEE_PARAM_MAPPING IMAP,IGRS_SERVICE_FEE_PARAM_MASTER IMAS" +
 		" WHERE PARENT_ID IS NULL  AND IMAS.PARAM_ID = IMAP.PARAM_ID AND FUNCTION_ID=";
   
  
   public static final String VISIT_REM_INSERT="INSERT INTO IGRS_VISIT_BOOKING_COMMENTS(VISIT_TXN_ID," +
   		"OFFICE_ID,USER_ID,COMMENTS,COMMENT_DATE)  VALUES(?,?,?,?,SYSDATE)";
  
  
   /**
	 * @author Madan Mohan
	 */
	public static final String SERVICE_FEE_PROCEDURE = "CALL " 
			+"IGRS_SERVICE_FEE_PKG.IGRS_SERVICE_FEE_PROC(?,?,?,?,?,?)";

   public static final String PHOTO_ID_DET = "SELECT PHOTO_PROOF_TYPE_ID,PHOTO_PROOF_TYPE_NAME FROM" +
   		" IGRS_PHOTOID_PROOF_TYPE_MASTER";
   
}