/*
 * Generated by MyEclipse Struts Template path: templates/java/JavaClass.vtl
 */


package com.wipro.igrs.hrpayroll.hrp.form;


import com.wipro.igrs.baseaction.form.BaseForm;
import com.wipro.igrs.hrpayroll.hrp.dto.CadreDTO;
import com.wipro.igrs.hrpayroll.hrp.dto.GradeCadreDTO;
import com.wipro.igrs.hrpayroll.hrp.dto.GradeDTO;
import com.wipro.igrs.hrpayroll.hrp.dto.LeaveDTO;
import com.wipro.igrs.hrpayroll.hrp.dto.SalaryDTO;


public class HrForm extends BaseForm {
	
	private CadreDTO		cadreDTO	= new CadreDTO();
	
	private GradeDTO		gradeDTO	= new GradeDTO();
	
	private LeaveDTO		leaveDTO	= new LeaveDTO();
	
	private GradeCadreDTO	gcDTO		= new GradeCadreDTO();
	
	private SalaryDTO		salaryDTO	= new SalaryDTO();
	
	// private ArrayList salaryDTOList = new ArrayList();
	
	private String			pageName	= null;
	
	private String			pageAction	= null;
	
	private String          pageReset ;
	
	/**
	 * 
	 */
	public HrForm() {
		super();
		// TODO Auto-generated constructor stub
	}
	
	/**
	 * @return the cadreDTO
	 */
	public CadreDTO getCadreDTO() {
		return cadreDTO;
	}
	
	/**
	 * @param cadreDTO
	 *            the cadreDTO to set
	 */
	public void setCadreDTO(CadreDTO cadreDTO) {
		this.cadreDTO = cadreDTO;
	}
	
	/**
	 * @return the gradeDTO
	 */
	public GradeDTO getGradeDTO() {
		return gradeDTO;
	}
	
	/**
	 * @param gradeDTO
	 *            the gradeDTO to set
	 */
	public void setGradeDTO(GradeDTO gradeDTO) {
		this.gradeDTO = gradeDTO;
	}
	
	/**
	 * @return the leaveDTO
	 */
	public LeaveDTO getLeaveDTO() {
		return leaveDTO;
	}
	
	/**
	 * @param leaveDTO
	 *            the leaveDTO to set
	 */
	public void setLeaveDTO(LeaveDTO leaveDTO) {
		this.leaveDTO = leaveDTO;
	}
	
	/**
	 * @return the gcDTO
	 */
	public GradeCadreDTO getGcDTO() {
		return gcDTO;
	}
	
	/**
	 * @param gcDTO
	 *            the gcDTO to set
	 */
	public void setGcDTO(GradeCadreDTO gcDTO) {
		this.gcDTO = gcDTO;
	}
	
	/**
	 * @return the salaryDTO
	 */
	public SalaryDTO getSalaryDTO() {
		return salaryDTO;
	}
	
	/**
	 * @param salaryDTO
	 *            the salaryDTO to set
	 */
	public void setSalaryDTO(SalaryDTO salaryDTO) {
		this.salaryDTO = salaryDTO;
	}
	
	/**
	 * @return the pageName
	 */
	public String getPageName() {
		return pageName;
	}
	
	/**
	 * @param pageName
	 *            the pageName to set
	 */
	public void setPageName(String pageName) {
		this.pageName = pageName;
	}
	
	/**
	 * @return the pageAction
	 */
	public String getPageAction() {
		return pageAction;
	}
	
	/**
	 * @param pageAction
	 *            the pageAction to set
	 */
	public void setPageAction(String pageAction) {
		this.pageAction = pageAction;
	}

	/**
	 * @return the pageReset
	 */
	public String getPageReset() {
		return pageReset;
	}

	/**
	 * @param pageReset the pageReset to set
	 */
	public void setPageReset(String pageReset) {
		this.pageReset = pageReset;
	}
	
}