package com.wipro.igrs.publicOff.sql;

/**
 * ===========================================================================
 * File           :   CommonSQL.java
 * Description    :   Represents the SQL Class

 * Author         :   Pavani  Param
 * Created Date   :   Aug 23, 2008

 * ===========================================================================
 */
public class CommonSQL {

public static final String PO_DEPT_DET_QUERY = "SELECT PO_DEPT_ID,PO_DEPT_NAME FROM IGRS_PUBLIC_OFFICE_DEPT_MASTER" +
		" WHERE  PO_DEPT_STATUS='A'";  

public static final String PO_USER_DET_QUERY = "SELECT UD.FIRST_NAME,UD.MIDDLE_NAME,UD.LAST_NAME,UD.GENDER," +
		"UD.GUARDIAN_NAME,UD.MOTHER_NAME,UD.ADDRESS,CM.COUNTRY_NAME,SM.STATE_NAME,DM.DISTRICT_NAME,UD.POSTAL_CODE," +
		"UD.PHONE_NUMBER,UD.MOBILE_NUMBER,UD.EMAIL_ID,UD.PHOTO_PROOF_TYPE_ID,UD.PHOTO_PROOF_ID, UD.BANK_NAME," +
		"UD.BANK_ADDRESS FROM IGRSUSER.IGRS_USER_REG_DETAILS UD,IGRS_COUNTRY_MASTER CM,IGRS_STATE_MASTER SM," +
		"IGRS_DISTRICT_MASTER DM WHERE UD.COUNTRY_ID  = CM.COUNTRY_ID AND UD.STATE_ID = SM.STATE_ID AND " +
		"UD.DISTRICT_ID = DM.DISTRICT_ID AND UD.USER_ID=";

public static final String PO_DET_INSERT = "INSERT  INTO  IGRS_PUBLIC_OFFICE_DETAILS (PUBLIC_OFFICER_ID," +
		" PO_DEPT_ID, PO_DESIGNATION, PO_SUPVSR_FIRST_NAME, PO_SUPVSR_MIDDLE_NAME,PO_SUPVSR_LAST_NAME," +
		" DR_REMARKS, DR_APPROVAL_STATUS,ACTIVATION_STATUS,USER_ID_START_DATE,USER_ID_EXPIRY_DATE," +
		" ACTIVATION_DATE,DR_APPROVAL_DATE) VALUES(?,?,?,?,?,?,?,?,?,?,?,SYSDATE,SYSDATE)";

public static final String PO_OTHER_DET_QUERY = " SELECT PO_DESIGNATION,PO_DEPT_ID,PO_SUPVSR_FIRST_NAME," +
		" PO_SUPVSR_MIDDLE_NAME, PO_SUPVSR_LAST_NAME,TO_CHAR(USER_ID_START_DATE ,'DD/MM/YYYY')," +
		" TO_CHAR(USER_ID_EXPIRY_DATE,'DD/MM/YYYY'),ACTIVATION_STATUS,DR_REMARKS FROM " +
		" IGRSUSER.IGRS_PUBLIC_OFFICE_DETAILS WHERE PUBLIC_OFFICER_ID=";

public static final String ACT_DET_UPDATE = "UPDATE IGRS_PUBLIC_OFFICE_DETAILS SET ACTIVATION_STATUS=?," +
		"DR_REMARKS = ? WHERE PUBLIC_OFFICER_ID = ?";
  
}