/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */

package com.wipro.igrs.sp.form;

import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;

/**
 * MyEclipse Struts Creation date: 06-26-2008
 * 
 * XDoclet definition:
 * 
 * @struts.form name="serviceProviderUploadForm"
 */
public class ServiceProviderUploadForm extends ActionForm {
	
	private FormFile theFile = null;
	private ArrayList formFiles = null;
	private int index;
	private String attachAction;
	private String removeAction;
	private ArrayList listUploadDTO;
	private int sizeOfFile;
	private String documentType;

	private String documentname;

	/**
	 * @return the documentname
	 */
	public String getDocumentname() {
		return documentname;
	}

	/**
	 * @param documentname
	 *            the documentname to set
	 */
	public void setDocumentname(String documentname) {
		this.documentname = documentname;
	}

	public ArrayList getFormFiles() {
		return formFiles;
	}

	public void setFormFiles(ArrayList formFiles) {
		this.formFiles = formFiles;
	}

	public int getIndex() {
		return index;
	}

	public void setIndex(int index) {
		this.index = index;
	}

	public String getDocumentType() {
		return documentType;
	}

	public void setDocumentType(String documentType) {
		this.documentType = documentType;
	}

	public void reset(ActionMapping mapping, HttpServletRequest request) {

		// Reset values are provided as samples only. Change as appropriate.

		theFile = null;

	}

	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {

		ActionErrors errors = new ActionErrors();
		return errors;

	}

	public String getAttachAction() {
		return attachAction;
	}

	public void setAttachAction(String attachAction) {
		this.attachAction = attachAction;
	}

	public String getRemoveAction() {
		return removeAction;
	}

	public void setRemoveAction(String removeAction) {
		this.removeAction = removeAction;
	}

	public ArrayList getListUploadDTO() {
		return listUploadDTO;
	}

	public void setListUploadDTO(ArrayList listUploadDTO) {
		this.listUploadDTO = listUploadDTO;
	}

	public FormFile getTheFile() {
		return theFile;
	}

	public void setTheFile(FormFile theFile) {
		this.theFile = theFile;
	}

	public int getSizeOfFile() {
		return sizeOfFile;
	}

	public void setSizeOfFile(int sizeOfFile) {
		this.sizeOfFile = sizeOfFile;
	}

}