package com.wipro.igrs.auditinspection.sql;

public class AddComplianceSQL {
public static final String GET_ROLE="SELECT TYP.OFFICE_TYPE_NAME FROM IGRS_OFFICE_TYPE_MASTER TYP,IGRS_OFFICE_MASTER MAST WHERE MAST.OFFICE_TYPE_ID=TYP.OFFICE_TYPE_ID AND MAST.OFFICE_ID=?";

public static final String GET_SR_DASHBOARD="SELECT DET.TRANSACTION_ID,TO_CHAR(DET.INSPECTION_ENTRY_DATE,'DD/MM/YYYY'),DIST.DISTRICT_NAME,DIST.H_DISTRICT_NAME FROM IGRS_SRO_INSP_DETAILS DET,IGRS_OFFICE_MASTER MAST,IGRS_DISTRICT_MASTER DIST WHERE MAST.OFFICE_ID=DET.INSPECTED_OFFICE_ID AND DIST.DISTRICT_ID= MAST.DISTRICT_ID AND DET.INSPECTED_OFFICE_ID=? AND COMPLINACE_FLAG=1";

public static final String GET_DRO_DASHBOARD_DR="SELECT DET.TRANSACTION_ID,TO_CHAR(DET.INSPECTION_ENTRY_DATE,'DD/MM/YYYY'),DIST.DISTRICT_NAME,DIST.H_DISTRICT_NAME FROM IGRS_DRO_INSP_DETAILS DET,IGRS_OFFICE_MASTER MAST,IGRS_DISTRICT_MASTER DIST  WHERE MAST.OFFICE_ID=DET.INSPECTED_OFFICE_ID AND DIST.DISTRICT_ID= MAST.DISTRICT_ID AND DET.INSPECTED_OFFICE_ID=? AND COMPLIANCE_FLAG=1";

public static final String GET_SRO_DASHBOARD_DR="SELECT DET.TRANSACTION_ID,TO_CHAR(DET.INSPECTION_ENTRY_DATE,'DD/MM/YYYY'),DIST.DISTRICT_NAME,DIST.H_DISTRICT_NAME FROM IGRS_SRO_INSP_DETAILS DET,IGRS_OFFICE_MASTER MAST,IGRS_DISTRICT_MASTER DIST  WHERE MAST.OFFICE_ID=DET.INSPECTED_OFFICE_ID AND DIST.DISTRICT_ID= MAST.DISTRICT_ID AND DET.INSPECTED_OFFICE_ID=MAST.OFFICE_ID AND MAST.PARENT_ID=? AND COMPLINACE_FLAG=2";

//modified by shruti---28th nov 2013
//public static final String GET_DRO_DASHBOARD_DIG="SELECT DET.TRANSACTION_ID,DET.INSPECTION_ENTRY_DATE,DIST.DISTRICT_NAME FROM IGRS_DRO_INSP_DETAILS DET,IGRS_OFFICE_MASTER MAST,IGRS_DISTRICT_MASTER DIST  WHERE MAST.OFFICE_ID=DET.INSPECTED_OFFICE_ID AND DIST.DISTRICT_ID= MAST.DISTRICT_ID AND DET.INSPECTED_OFFICE_ID=MAST.OFFICE_ID AND MAST.PARENT_ID=? AND COMPLIANCE_FLAG=2";

	public static final String GET_DRO_DASHBOARD_DIG="SELECT distinct DET.TRANSACTION_ID,TO_CHAR(DET.INSPECTION_ENTRY_DATE,'DD/MM/YYYY'),DIST.DISTRICT_NAME,DIST.H_DISTRICT_NAME"
		+" FROM IGRS_DRO_INSP_DETAILS DET,IGRS_OFFICE_MASTER MAST,IGRS_DISTRICT_MASTER DIST"
		+" WHERE MAST.OFFICE_ID=DET.INSPECTED_OFFICE_ID and DIST.DISTRICT_ID= MAST.DISTRICT_ID and DET.INSPECTED_OFFICE_ID in"
		+" (select office_id from igrs_office_master where parent_id in"
		+" ((select office_id from igrs_office_master where office_id "
		+" in(select office_id from igrs_office_master where parent_id =?"
		+" ))) or parent_id =?) AND COMPLIANCE_FLAG=2 ";
	
//COMMENTED BY SHRUTI---28TH NOV 2013
public static final String GET_SRO_DASHBOARD_DIG="SELECT distinct DET.TRANSACTION_ID,TO_CHAR(DET.INSPECTION_ENTRY_DATE,'DD/MM/YYYY'),DIST.DISTRICT_NAME,DIST.H_DISTRICT_NAME"
+" FROM IGRS_SRO_INSP_DETAILS DET,IGRS_OFFICE_MASTER MAST,IGRS_DISTRICT_MASTER DIST"
+" WHERE MAST.OFFICE_ID=DET.INSPECTED_OFFICE_ID and DIST.DISTRICT_ID= MAST.DISTRICT_ID and DET.INSPECTED_OFFICE_ID in"
+" (select office_id from igrs_office_master where parent_id in"
+" ((select office_id from igrs_office_master where office_id "
+" in(select office_id from igrs_office_master where parent_id =?"
+" ))) or parent_id =? ) AND COMPLINACE_FLAG=3 ";

//public static final String GET_SRO_DASHBOARD_DIG="SELECT DET.TRANSACTION_ID,DET.INSPECTION_ENTRY_DATE,DIST.DISTRICT_NAME FROM IGRS_SRO_INSP_DETAILS DET,IGRS_OFFICE_MASTER MAST,IGRS_DISTRICT_MASTER DIST  WHERE MAST.OFFICE_ID=DET.INSPECTED_OFFICE_ID AND DIST.DISTRICT_ID= MAST.DISTRICT_ID AND DET.INSPECTED_OFFICE_ID=MAST.OFFICE_ID AND MAST.PARENT_ID IN (SELECT PARENT_ID FROM IGRS_OFFICE_MASTER WHERE OFFICE_ID=? ) AND COMPLINACE_FLAG=3";


public static final String GET_DRO_DASHBOARD_IG="SELECT DET.TRANSACTION_ID,TO_CHAR(DET.INSPECTION_ENTRY_DATE,'DD/MM/YYYY'),DIST.DISTRICT_NAME,DIST.H_DISTRICT_NAME FROM IGRS_DRO_INSP_DETAILS DET,IGRS_OFFICE_MASTER MAST,IGRS_DISTRICT_MASTER DIST  WHERE MAST.OFFICE_ID=DET.INSPECTED_OFFICE_ID AND DIST.DISTRICT_ID= MAST.DISTRICT_ID  AND COMPLIANCE_FLAG=3";

public static final String GET_SRO_DASHBOARD_IG="SELECT DET.TRANSACTION_ID,TO_CHAR(DET.INSPECTION_ENTRY_DATE,'DD/MM/YYYY'),DIST.DISTRICT_NAME,DIST.H_DISTRICT_NAME FROM IGRS_SRO_INSP_DETAILS DET,IGRS_OFFICE_MASTER MAST,IGRS_DISTRICT_MASTER DIST WHERE MAST.OFFICE_ID=DET.INSPECTED_OFFICE_ID AND DIST.DISTRICT_ID= MAST.DISTRICT_ID AND COMPLINACE_FLAG=4";
public static final String RETRIEVE_CHKLIST_ITEMS="SELECT  ITEM_NAME,ITEM_ID FROM IGRS_INSP_CHECK_LIST_MASTER WHERE ITEM_CHECK_REMARKS = ?";

public static final String RETRIEVE_CHKLIST_ITEMS_H="SELECT  H_ITEM_NAME,ITEM_ID FROM IGRS_INSP_CHECK_LIST_MASTER WHERE ITEM_CHECK_REMARKS = ?";
public static final String RETRIEVE_PENDING_ITEMS=
	"SELECT PENDING_ITEM,TO_CHAR(PENDING_FROM,'DD/MM/YYYY'),PENDING_TASK_NO FROM IGRS_INSPECTION_PENDING_ITEMS WHERE  INSP_TXN_ID = ?";
public static final String RETRRIEVE_INSP_EMP_DETAILS=
	"SELECT MAST.FIRST_NAME,cad.cadre_name,to_char(OFFI.DATE_OF_JOINING, 'DD/MM/YYYY'),"+
	" to_char(OFFI.DATE_OF_SEPARATION, 'DD/MM/YYYY'),MAST.EMP_ID FROM "+
	" IGRS_SRO_INSP_EMP_MAP EMP,IGRS_EMP_MASTER MAST,"+
	" IGRS_EMP_OFFICIAL_DETAILS OFFI ,IGRS_EMP_CADRE_MASTER CAD"+
	" WHERE EMP.EMP_ID = MAST.EMP_ID AND EMP.EMP_ID = OFFI.EMP_ID"+ 
	" AND CAD.cadre_id=OFFI.EMP_DESIGNATION_ID AND EMP.INSP_TXN_ID =?";

public static final String RETRIEVE_SRO_DETAILS=
	"SELECT INSP.TRANSACTION_ID,to_char(INSP.INSPECTION_START_DATE, 'DD/MM/YYYY'),to_char(INSP.INSPECTION_END_DATE, 'DD/MM/YYYY'),INSP.LFY_ANNUAL_TARGETS,INSP.LFY_ANNUAL_RECEIPTS," +
	"INSP.LFY_PCT_COMPLETED,INSP.LFY_PCT_INCREASE,INSP.CFY_ANNUAL_INCOME,INSP.CFY_ANNUAL_RECEIPTS,INSP.LFY_INCOME,INSP.INCOME_UNACCOM_REASON_CFY," +
	"INSP.INCOME_UNACCOM_REASON_LFY,INSP.CASH_DEPOSIT_BANK,INSP.NO_RTI_REQUEST_CFY,INSP.NO_DISPOSED_RTI_REQ_CFY,INSP.REASON_FOR_PENDING_REQ," +
	"INSP.INSPECTION_STATUS,INSP.INSP_AUTHORITY_NAME,INSP.SR_NAME,INSP.CFY_INCOME_TO,INSP.CFY_INCOME_FROM,INSP.CFY_RECIEPT_TO,INSP.CFY_RECIEPT_FROM,INSP.LFY_INCOME_TO,INSP.LFY_INCOME_FROM,to_char(INSP.INSPECTION_DUE_DATE,'dd/mm/yyyy'),to_char(INSP.OBJECTED_ENTRY_DATE,'dd/mm/yyyy'),INSP.PAST_INSPECTION_DETAILS,to_char(INSP.INSPECTION_ENTRY_DATE,'dd/mm/yyyy'),to_char(INSP.INSPECTION_DATE,'dd/mm/yyyy'),OFFC.OFFICE_NAME,DISTT.DISTRICT_NAME,INSP.TENURE,INSP.COMPLINACE_FLAG,INSP.SR_COMPLIANCE,INSP.DR_COMPLIANCE,INSP.DIG_COMPLIANCE,INSP.IG_COMPLIANCE FROM IGRS_SRO_INSP_DETAILS INSP,IGRS_OFFICE_MASTER OFFC,IGRS_DISTRICT_MASTER DISTT WHERE INSP.INSPECTED_OFFICE_ID=OFFC.OFFICE_ID AND OFFC.DISTRICT_ID=DISTT.DISTRICT_ID AND INSP.TRANSACTION_ID=?";
public static final String RETRIEVE_SRO_DETAILS_H=
	"SELECT INSP.TRANSACTION_ID,to_char(INSP.INSPECTION_START_DATE, 'DD/MM/YYYY'),to_char(INSP.INSPECTION_END_DATE, 'DD/MM/YYYY'),INSP.LFY_ANNUAL_TARGETS,INSP.LFY_ANNUAL_RECEIPTS," +
	"INSP.LFY_PCT_COMPLETED,INSP.LFY_PCT_INCREASE,INSP.CFY_ANNUAL_INCOME,INSP.CFY_ANNUAL_RECEIPTS,INSP.LFY_INCOME,INSP.INCOME_UNACCOM_REASON_CFY," +
	"INSP.INCOME_UNACCOM_REASON_LFY,INSP.CASH_DEPOSIT_BANK,INSP.NO_RTI_REQUEST_CFY,INSP.NO_DISPOSED_RTI_REQ_CFY,INSP.REASON_FOR_PENDING_REQ," +
	"INSP.INSPECTION_STATUS,INSP.INSP_AUTHORITY_NAME,INSP.SR_NAME,INSP.CFY_INCOME_TO,INSP.CFY_INCOME_FROM,INSP.CFY_RECIEPT_TO,INSP.CFY_RECIEPT_FROM,INSP.LFY_INCOME_TO,INSP.LFY_INCOME_FROM,to_char(INSP.INSPECTION_DUE_DATE,'dd/mm/yyyy'),to_char(INSP.OBJECTED_ENTRY_DATE,'dd/mm/yyyy'),INSP.PAST_INSPECTION_DETAILS,to_char(INSP.INSPECTION_ENTRY_DATE,'dd/mm/yyyy'),to_char(INSP.INSPECTION_DATE,'dd/mm/yyyy'),OFFC.H_OFFICE_NAME,DISTT.H_DISTRICT_NAME,INSP.TENURE,INSP.COMPLINACE_FLAG,INSP.SR_COMPLIANCE,INSP.DR_COMPLIANCE,INSP.DIG_COMPLIANCE,INSP.IG_COMPLIANCE FROM IGRS_SRO_INSP_DETAILS INSP,IGRS_OFFICE_MASTER OFFC,IGRS_DISTRICT_MASTER DISTT WHERE INSP.INSPECTED_OFFICE_ID=OFFC.OFFICE_ID AND OFFC.DISTRICT_ID=DISTT.DISTRICT_ID AND INSP.TRANSACTION_ID=?";

public static final String RETRIEVE_SRO_COMMENTS=
	"SELECT USER_COMMENTS FROM IGRS_SRO_INSP_COMMENTS WHERE INSP_TXN_ID= ?";

public static final String RETRIEVE_DOC_NAME=
	"SELECT DOCUMENT_NAME,DOCUMENT_PATH FROM IGRS_SRO_INSP_DOC_MAP WHERE INSP_TXN_ID = ?";

public static final String RETRIEVE_SELECTED_CHK_ITEMS=
	"SELECT e3.ITEM_NAME FROM IGRS_SRO_INSP_DETAILS e1,IGRS_INSP_CHECK_LIST_MAP e2,IGRS_INSP_CHECK_LIST_MASTER e3 " +
	"WHERE e1.TRANSACTION_ID = e2.INSP_TXN_ID AND e2.ITEM_ID = e3.ITEM_ID AND e3.ITEM_CHECK_REMARKS = 'Y' " +
	"AND e1.TRANSACTION_ID = ? ";

public static final String RETRIEVE_SELECTED_CHK_ITEMS_H=
	"SELECT e3.H_ITEM_NAME FROM IGRS_SRO_INSP_DETAILS e1,IGRS_INSP_CHECK_LIST_MAP e2,IGRS_INSP_CHECK_LIST_MASTER e3 " +
	"WHERE e1.TRANSACTION_ID = e2.INSP_TXN_ID AND e2.ITEM_ID = e3.ITEM_ID AND e3.ITEM_CHECK_REMARKS = 'Y' " +
	"AND e1.TRANSACTION_ID = ? ";
public static final String RETRIEVE_SELECTED_CHK_OTHERS_ITEMS=
	"SELECT e3.ITEM_NAME,e2.ITEM_REMARKS FROM IGRS_SRO_INSP_DETAILS e1,IGRS_INSP_CHECK_LIST_MAP e2,IGRS_INSP_CHECK_LIST_MASTER e3 " +
	"WHERE e1.TRANSACTION_ID = e2.INSP_TXN_ID AND e2.ITEM_ID = e3.ITEM_ID AND e3.ITEM_CHECK_REMARKS = 'N' " +
	"AND e1.TRANSACTION_ID = ? ";
public static final String RETRIEVE_SELECTED_CHK_OTHERS_ITEMS_H=
	"SELECT e3.H_ITEM_NAME,e2.ITEM_REMARKS FROM IGRS_SRO_INSP_DETAILS e1,IGRS_INSP_CHECK_LIST_MAP e2,IGRS_INSP_CHECK_LIST_MASTER e3 " +
	"WHERE e1.TRANSACTION_ID = e2.INSP_TXN_ID AND e2.ITEM_ID = e3.ITEM_ID AND e3.ITEM_CHECK_REMARKS = 'N' " +
	"AND e1.TRANSACTION_ID = ? ";
public static final String RETRIEVE_DRO_INSP_DETAILS=
	"SELECT DRO.OFFICE_NAME,DIS.DISTRICT_NAME,INSP.INSP_AUTHORITY_NAME,INSP.TRANSACTION_ID," +
	"INSP.INSPECTION_START_DATE,INSP.INSPECTION_END_DATE,INSP.INSPECTION_DATE,INSP.SR_NAME," +
	"INSP.LFY_ANNUAL_TARGETS,INSP.LFY_ANNUAL_RECEIPTS,INSP.LFY_PCT_COMPLETED,INSP.LFY_PCT_INCREASE," +
	"INSP.CFY_ANNUAL_INCOME,INSP.CFY_ANNUAL_RECEIPTS,INSP.LFY_INCOME,INSP.INSPECTION_STATUS, " +
	"TO_CHAR(INSP.INSPECTION_ENTRY_DATE,'DD/MM/YYYY'),TO_CHAR(INSP.INSPECTION_DUE_DATE,'DD/MM/YYYY'),INSP.TENURE,INSP.CFY_INCOME_FROM,INSP.CFY_INCOME_TO,"+
	"INSP.CFY_RECIEPTS_FROM,INSP.CFY_RECIEPTS_TO,INSP.LFY_INCOME_FROM,INSP.LFY_INCOME_TO,INSP.IG_COMMENTS,INSP.PAST_DETAILS,TO_CHAR(INSP.OBJECTED_ENTRY_DATE,'MM/DD/YYYY'),"+
	"INSP.STAMP_DETAILS,INSP.PENDING_DETAILS,INSP.RRC_DETAILS,INSP.DE_DETAILS,INSP.PENSION_DETAILS, "+
	" INSP.COMPLIANCE_FLAG,INSP.DR_COMPLIANCE,INSP.DIG_COMPLIANCE,INSP.IG_COMPLIANCE "+
	" FROM IGRS_DRO_INSP_DETAILS INSP,IGRS_OFFICE_MASTER DRO,IGRS_DISTRICT_MASTER DIS " +
	"WHERE INSP.INSPECTED_OFFICE_ID = DRO.OFFICE_ID AND DRO.DISTRICT_ID = DIS.DISTRICT_ID AND " +
	"TRANSACTION_ID=?";
public static final String RETRIEVE_DRO_INSP_DETAILS_H=
	"SELECT DRO.H_OFFICE_NAME,DIS.H_DISTRICT_NAME,INSP.INSP_AUTHORITY_NAME,INSP.TRANSACTION_ID," +
	"INSP.INSPECTION_START_DATE,INSP.INSPECTION_END_DATE,INSP.INSPECTION_DATE,INSP.SR_NAME," +
	"INSP.LFY_ANNUAL_TARGETS,INSP.LFY_ANNUAL_RECEIPTS,INSP.LFY_PCT_COMPLETED,INSP.LFY_PCT_INCREASE," +
	"INSP.CFY_ANNUAL_INCOME,INSP.CFY_ANNUAL_RECEIPTS,INSP.LFY_INCOME,INSP.INSPECTION_STATUS, " +
	"TO_CHAR(INSP.INSPECTION_ENTRY_DATE,'DD/MM/YYYY'),TO_CHAR(INSP.INSPECTION_DUE_DATE,'DD/MM/YYYY'),INSP.TENURE,INSP.CFY_INCOME_FROM,INSP.CFY_INCOME_TO,"+
	"INSP.CFY_RECIEPTS_FROM,INSP.CFY_RECIEPTS_TO,INSP.LFY_INCOME_FROM,INSP.LFY_INCOME_TO,INSP.IG_COMMENTS,INSP.PAST_DETAILS,TO_CHAR(INSP.OBJECTED_ENTRY_DATE,'MM/DD/YYYY'),"+
	"INSP.STAMP_DETAILS,INSP.PENDING_DETAILS,INSP.RRC_DETAILS,INSP.DE_DETAILS,INSP.PENSION_DETAILS, "+
	" INSP.COMPLIANCE_FLAG,INSP.DR_COMPLIANCE,INSP.DIG_COMPLIANCE,INSP.IG_COMPLIANCE "+
	" FROM IGRS_DRO_INSP_DETAILS INSP,IGRS_OFFICE_MASTER DRO,IGRS_DISTRICT_MASTER DIS " +
	"WHERE INSP.INSPECTED_OFFICE_ID = DRO.OFFICE_ID AND DRO.DISTRICT_ID = DIS.DISTRICT_ID AND " +
	"TRANSACTION_ID=?";
public static final String RETRIEVE_DRO_EMP_DETAILS=
	"SELECT MAST.EMP_ID,MAST.FIRST_NAME,DES.CADRE_NAME,OFFI.DATE_OF_JOINING,OFFI.DATE_OF_SEPARATION " +
	"FROM IGRS_DRO_INSP_EMP_MAP EMP,IGRS_EMP_MASTER MAST,IGRS_EMP_CADRE_MASTER DES," +
	"IGRS_EMP_OFFICIAL_DETAILS OFFI WHERE EMP.EMP_ID = MAST.EMP_ID AND EMP.EMP_ID = OFFI.EMP_ID " +
	"AND OFFI.EMP_DESIGNATION_ID = DES.CADRE_ID AND EMP.INSP_TXN_ID = ?";
public static final String RETRIEVE_DRO_REASON_DETAILS=
	"SELECT UNACCOMPLISHED_REASON FROM IGRS_DRO_INSP_REASON_MAP WHERE DRO_INSP_TXN_ID = ?";
public static final String RETRIEVE_DRO_DOCUMENTS=
	"SELECT DOCUMENT_NAME,DOCUMENT_PATH FROM IGRS_DRO_INSP_DOC_MAP WHERE INSP_TXN_ID = ? ";//and DOC_TYPE_ID=(select DOCUMENT_TYPE_ID from IGRS_DOCUMENT_TYPE_MASTER where DOCUMENT_NAME=?)";
public static final String UPDATE_SRO_SR_COMPLIANCE="UPDATE IGRS_SRO_INSP_DETAILS SET SR_COMPLIANCE=?,COMPLINACE_FLAG=2 WHERE TRANSACTION_ID=?";

public static final String UPDATE_SRO_DR_COMPLIANCE="UPDATE IGRS_SRO_INSP_DETAILS SET DR_COMPLIANCE=?,COMPLINACE_FLAG=3 WHERE TRANSACTION_ID=?";

public static final String UPDATE_SRO_DIG_COMPLIANCE="UPDATE IGRS_SRO_INSP_DETAILS SET DIG_COMPLIANCE=?,COMPLINACE_FLAG=4 WHERE TRANSACTION_ID=?";

public static final String UPDATE_SRO_IG_COMPLIANCE="UPDATE IGRS_SRO_INSP_DETAILS SET IG_COMPLIANCE=?,COMPLINACE_FLAG=5 WHERE TRANSACTION_ID=?";

public static final String UPDATE_DRO_DR_COMPLIANCE="UPDATE IGRS_DRO_INSP_DETAILS SET DR_COMPLIANCE=?,COMPLIANCE_FLAG=2 WHERE TRANSACTION_ID=?";

public static final String UPDATE_DRO_DIG_COMPLIANCE="UPDATE IGRS_DRO_INSP_DETAILS SET DIG_COMPLIANCE=?,COMPLIANCE_FLAG=3 WHERE TRANSACTION_ID=?";

public static final String UPDATE_DRO_IG_COMPLIANCE="UPDATE IGRS_DRO_INSP_DETAILS SET IG_COMPLIANCE=?,COMPLIANCE_FLAG=4 WHERE TRANSACTION_ID=?";

// for add audit compliance

public static final String SEARCH_AUDIT_REPORT_SR="SELECT R.TRANSACTION_ID,TO_CHAR(R.AUDIT_DATE,'DD/MM/YYYY'),TO_CHAR(R.CREATED_DATE,'DD/MM/YYYY'),AUDIT_REPORT_STATUS"+
												" FROM  IGRS_RAUDIT_TXN_DETAILS R  WHERE  R.DRS_OFFICE_ID=? AND R.COMPLIANCE_FLAG=1";

public static final String SEARCH_AUDIT_REPORT_DR="SELECT R.TRANSACTION_ID,TO_CHAR(R.AUDIT_DATE,'DD/MM/YYYY'),TO_CHAR(R.CREATED_DATE,'DD/MM/YYYY'),AUDIT_REPORT_STATUS"+
" FROM  IGRS_RAUDIT_TXN_DETAILS R,IGRS_OFFICE_MASTER MAST  WHERE MAST.OFFICE_ID=R.DRS_OFFICE_ID and R.DRS_OFFICE_ID in"
+" (select office_id from igrs_office_master where parent_id in (?))" 
+" AND R.COMPLIANCE_FLAG=2";

public static final String SEARCH_AUDIT_REPORT_DIG="SELECT R.TRANSACTION_ID,TO_CHAR(R.AUDIT_DATE,'DD/MM/YYYY'),TO_CHAR(R.CREATED_DATE,'DD/MM/YYYY'),AUDIT_REPORT_STATUS"+
" FROM  IGRS_RAUDIT_TXN_DETAILS R,IGRS_OFFICE_MASTER MAST  "
+" WHERE MAST.OFFICE_ID=R.DRS_OFFICE_ID  and R.DRS_OFFICE_ID in"
+" (select office_id from igrs_office_master where parent_id in" 
+" ((select office_id from igrs_office_master where office_id " 
+" in(select office_id from igrs_office_master where parent_id =?"
+" ))) or parent_id =?" +
		") AND R.COMPLIANCE_FLAG=3 ";

public static final String SEARCH_AUDIT_REPORT_IG="SELECT R.TRANSACTION_ID,TO_CHAR(R.AUDIT_DATE,'DD/MM/YYYY'),TO_CHAR(R.CREATED_DATE,'DD/MM/YYYY'),AUDIT_REPORT_STATUS"+
" FROM  IGRS_RAUDIT_TXN_DETAILS R where COMPLIANCE_FLAG=? ";


public static final String ADD_COMPLIANCE_SR="UPDATE IGRS_RAUDIT_TXN_DETAILS SET COMPLIANCE_FLAG=2,SR_COMPLIANCE=? WHERE TRANSACTION_ID=?";

public static final String ADD_COMPLIANCE_DR="UPDATE IGRS_RAUDIT_TXN_DETAILS SET COMPLIANCE_FLAG=3 ,DR_COMPLIANCE=? WHERE TRANSACTION_ID=?";

public static final String ADD_COMPLIANCE_DIG="UPDATE IGRS_RAUDIT_TXN_DETAILS SET COMPLIANCE_FLAG=4 , DIG_COMPLIANCE=? WHERE TRANSACTION_ID=?";

public static final String ADD_COMPLIANCE_IG="UPDATE IGRS_RAUDIT_TXN_DETAILS SET COMPLIANCE_FLAG=5, IG_COMPLIANCE=? WHERE TRANSACTION_ID=?";

}
