package com.wipro.igrs.auditinspection.sql;

/*
* Copyright Notice
*==============================================================================
* This file contains proprietary information of IGRS Bhopal Madhya Pradesh .
* Copying or reproduction without prior written approval is prohibited.
* Copyright (c) 2007-08
*==============================================================================
*
* File Name   :   
 * Author      :   
 * Description :   
 * ----------------------------------------------------------------------------
* Version         Modified By     Modified On           Modification
* ----------------------------------------------------------------------------
* 1.0             SHRUTI          xxxxx              
 * --------------------------------------------------------------------------------
*/

public class CommonSQL {
 
	 public static final String insert_IGRS_RCPT_AUDIT_TXN="INSERT INTO IGRS_RAUDIT_TXN_DETAILS \n"+
         "(AUDIT_FROM_DATE,AUDIT_TO_DATE,AUDIT_DATE,AUDIT_REPORT_STATUS,CREATED_BY,\n"+
         " UPDATE_BY,PHYSICAL_REPORT_ID,DISPATCH_DATE,AUDIT_BODY_TYPE,FINAL_COMMENTS,\n" +
         " DISTRICT_ID,DRS_OFFICE_ID,DRS_USER_ID,ENTRY_DATE,TRANSACTION_ID,CREATED_DATE,UPDATE_DATE)\n"+
         " VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,SYSDATE,SYSDATE)";   

    public static final String REQUISITE_FEE_QUERY = 
        "SELECT AMOUNT FROM IGR_REQUISITE_FEE_MASTER WHERE REQUISITE_NAME='WILL_DEPOSIT'";
    
    public static final String REQUISITE_OTHER_FEE_QUERY = 
        "SELECT AMOUNT FROM IGR_REQUISITE_FEE_MASTER WHERE REQUISITE_NAME='WILL_OTHER'";
    
    public static final String WILL_DEPOSIT_INSERT = 
        "INSERT INTO IGRS_WILL_DEPOSIT_TXN(WILL_ID,DR_ID," + 
        "DEPOSITOR_TYPE,FIRST_NAME,MID_NAME,LAST_NAME,GENDER,AGE," + 
        "FATHER_NAME,MOTHER_NAME,SPOUSE_NAME,ADDRESS,CITY,STATE," + 
        "COUNTRY,PIN,PHONE,MOBILE,EMAIL,ID_PROOF,PHOTO_FLAG,THUMB_FLAG," + 
        "SIGN_FLAG,FEE,OTHER,PAYMENT_MODE,DEPOSIT_DATE,WILL_TYPE_FLAG)" + 
        "VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,SYSDATE,?) ";
    
    public static final String WILL_DEPOST_AGENT_INSERT = 
        "INSERT INTO IGRS_WILL_AGENT_TXN(WILL_ID,FIRST_NAME," + 
        "MID_NAME,LAST_NAME,GENDER,AGE,FATHER_NAME,MOTHER_NAME," + 
        "SPOUSE_NAME,ADDRESS,CITY,STATE,COUNTRY,PIN,PHONE,MOBILE,EMAIL,IDPROOFNO) " + 
        "VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
    
    public static final String WILL_DEPOSIT_QUERY = 
        "SELECT FIRST_NAME,MID_NAME,LAST_NAME,GENDER,AGE," + 
        "FATHER_NAME,MOTHER_NAME,SPOUSE_NAME,ADDRESS,CITY,STATE," + 
        "COUNTRY,PIN,PHONE,MOBILE,EMAIL,ID_PROOF,PHOTO_FLAG,THUMB_FLAG," + 
        "SIGN_FLAG,DEPOSIT_DATE,WILL_ID FROM  IGRS_WILL_DEPOSIT_TXN WHERE WILL_ID=? AND WILL_TYPE_FLAG=?";


    public static final String WILL_WITHDRAWAL_INSERT = 
        "UPDATE IGRS_WILL_DEPOSIT_TXN SET WILL_TYPE_FLAG=?,EXE_TFLAG=?,EXE_SFLAG=?,REASON=?,REMARKS=? WHERE WILL_ID=?";


    public static final String WILL_RETRIEVE_QUERY = 
        "SELECT FIRST_NAME,MID_NAME,LAST_NAME, ADDRESS,DEPOSIT_DATE,WILL_ID FROM  IGRS_WILL_DEPOSIT_TXN WHERE WILL_ID LIKE 'MP%' ";

    public static final String WILL_CHALLAN_PAYMENT_INSERT = 
                    "INSERT INTO IGRS_PAYMENT_CHALLAN_DETAILS (CHALLAN_ID,CHALLAN_AMOUNT,CHALLAN_DATE) VALUES(?,?,SYSDATE)";
        
        
    public static final String WILL_RETRIEVE_CITIZEN_INSERT = 
        "INSERT INTO IGRS_WILL_RETRIEVE_TXN(WILL_ID,FIRST_NAME," + 
        "MID_NAME,LAST_NAME,GENDER,AGE,FATHER_NAME,MOTHER_NAME," + 
        "SPOUSE_NAME,ADDRESS,CITY,STATE,COUNTRY,PIN,PHONE,MOBILE,EMAIL," + 
        "IDPROOFNO,PHOTO_FLG,THUMB_FLG,SIGN_FLG,DEATH_FLG,WILL_RET_ID) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";

    
    public static final String WILL_RETRIEVE_UPDATE = 
        "UPDATE IGRS_WILL_DEPOSIT_TXN SET WILL_TYPE_FLAG=?,WILL_RET_TYPE_FLAG=?,REASON=?,REMARKS=? WHERE WILL_ID=?";

    
    public static final String WILL_RETRIEVE_COURT_INSERT = 
        "INSERT IGRS_WILL_COURT_TXN(WILL_ID,COURT_NAME,REP_NAME,DESG,THUMB_FLAG,SIGN_FLAG,ADDRESS,CITY,STATE,COUNTRY,PIN,PHONE)VALUES(?,?,?,?,?,?,?,?,?,?,?,?)";
    public static final String insert_IGRS_AUDIT_DOC_MAPPING=
    	"insert into IGRS_RAUDIT_DOCUMENT_DETAILS(DOCUMENT_TXN_ID,DOCUMENT_FILE_NAME,DOCUMENT_FILE,DOCUMENT_STATUS,CREATED_BY,CREATED_DATE,UPDATE_BY,UPDATE_DATE) VALUES(?,?,?,?,?,SYSDATE,?,SYSDATE)";
    public static final String insert_IGRS_RAUDIT_DOC_MAPPING=
    	"insert into IGRS_RAUDIT_DOCUMENT_DETAILS(DOCUMENT_FILE_NAME,DOCUMENT_FILE,DOCUMENT_STATUS,CREATED_BY,CREATED_DATE,UPDATE_BY,UPDATE_DATE) VALUES(?,?,?,?,SYSDATE,?,SYSDATE)";

    //modified by shruti-2nd sep 2013
  /*  public static final String REG_RETRIEVE_QUERY=
    	"SELECT REGISTRATION_ID,to_char(CREATED_DATE,'DD/MM/YYYY') FROM IGRS_REG_COMPLETION_DETAILS where REGISTRATION_ID like ?";
   */
    public static final String REG_RETRIEVE_QUERY=
    	"SELECT REGISTRATION_NUMBER,to_char(CREATED_DATE,'DD/MM/YYYY') FROM IGRS_REG_TXN_DETLS where REGISTRATION_NUMBER =?";
   
    public static final String REG_OTHERS_RETRIEVE_QRY_LIKE=
    	"select estamp_doc_id,to_char(created_date,'DD/MM/YYYY') from igrs_estamp_document_details where estamp_doc_id =?";
  
    //modified by shruti---19th oct 2013
   /* public static final String REG_OTHERS_RETRIEVE_QRY_EXCT=
    	"select t1.estamp_doc_id,to_char(t1.created_date,'DD/MM/YYYY'),t2.estamp_duty,t2.estamp_other_fees,"+
    	"t3.party_first_name_h,t3.party_middle_name_h,t3.party_last_name_h,t3.party_gender,"+
    	"t3.party_age,t3.postal_code,t3.phone_number,t3.party_address,t3.bank_name,"+
    	"t3.bank_address,t4.district_name,t5.state_name,t6.country_name "+
    	"from igrs_estamp_document_details t1,igrs_estamp_txn_details t2,"+
    	"igrs_reg_txn_party_details t3,igrs_district_master t4,igrs_state_master t5,"+
    	"igrs_country_master t6 Where t1.estamp_txn_id=t2.transaction_id "+
    	"and t1.estamp_txn_id=t3.reg_txn_id and t3.district_id=t4.district_id "+
    	"and t3.state_id=t5.state_id and t3.country_id=t6.country_id and t1.estamp_doc_id=?";*/
    
    public static final String REG_OTHERS_RETRIEVE_QRY_EXCT="SELECT FILING_NUMBER,TO_CHAR(CREATED_DATE,'DD/MM/YYYY'),SR_NAME,STAMP_DUTY_NOW,'0','0',REFERENCE_ID"
    +" FROM IGRS_SUPPLI_MASTER_TABLE WHERE FILING_NUMBER=?";
    
    //modified as per new db-SHRUTI- 18 OCT 2013
    
    public static final String REG_DETAILS_RETRIEVE_QRY ="SELECT A.REGISTRATION_NUMBER,to_char(A.CREATED_DATE,'dd/mm/yyyy'),(SELECT B.FIRST_NAME || B.LAST_NAME FROM IGRS_EMP_MASTER" 
+" B WHERE b.EMP_ID=A.CREATED_BY),D.STAMP_DUTY,D.REG_FEE,D.FINAL_MARKET_VALUE,A.REG_TXN_ID FROM IGRS_REG_TXN_DETLS A,IGRS_REG_CHK_STAMP_DUTY_DTLS D WHERE" 
+" D.REG_TXN_ID=A.REG_TXN_ID AND A.REGISTRATION_NUMBER=?";
    
    //commented by shruti
    /*public static final String REG_DETAILS_RETRIEVE_QRY =
    	"SELECT A.REGISTRATION_ID,trunc(A.CREATED_DATE),(SELECT B.FIRST_NAME || B.LAST_NAME FROM IGRS_EMP_MASTER B WHERE b.EMP_ID=A.CREATED_BY),d.estamp_duty,d.ESTAMP_OTHER_FEES " +
    	"FROM IGRS_REG_COMPLETION_DETAILS a,IGRS_REG_INITN_TXN_DETAILS C,IGRS_ESTAMP_TXN_DETAILS D" +
    	" WHERE A.TRANSACTION_ID = C.TRANSACTION_ID AND C.ESTAMP_TXN_ID=D.TRANSACTION_ID " +
    	"AND A.REGISTRATION_ID=? and A.CREATED_BY=?";*/
    //end
    
    
    
    	/*" select t1.REGISTRATION_ID,t1.CREATED_DATE,t1.SR_NAME,t2.ESTAMP_DUTY,t2.ESTAMP_OTHER_FEES \n"+
        " from IGRS_REG_COMPLETION_DETAILS t1,IGRS_ESTAMP_TXN_DETAILS t2\n"+
        " where t1.TRANSACTION_ID=t2.TRANSACTION_ID and t1.REGISTRATION_ID=?";*/


    public static final String INSERT_IGRS_RAUDIT_TXN_DETAILS=
    	"INSERT INTO IGRS_RAUDIT_TXN_DETAILS VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
    public static final String INSERT_IGRS_RAUDIT_PARA_OBJ=
    	"INSERT INTO IGRS_RAUDIT_PARA_OBJ_DETAILS(OBJECTION_TXN_ID,OBJECTION_DETAILS,OBJECTION_DATE,VALUATION_FROM_AGMP,DEFICIENT_STAMP_DUTY,DEFICIENT_REG_FEE,DOCUMENT_ID,CASE_TXN_ID,OBJECTION_STATUS,VALUATION_AT_REG_TIME) VALUES(?,?,SYSDATE,?,?,?,?,?,?,?)";
    
    //modified by shruti-2/sep/2013
    
  /*  public static final String INSERT_IGRS_RAUDIT_PARA_DETAILS=
    	"INSERT INTO IGRS_RAUDIT_PARA_DETAILS VALUES(?,?,?,?,SYSDATE,?)";*/
    public static final String INSERT_IGRS_RAUDIT_PARA_DETAILS="INSERT INTO IGRS_RAUDIT_PARA_DETAILS(PARA_TXN_ID,PARA_TYPE_ID,PARA_NAME,PARA_COMMENTS,PARA_COMMENTS_DATE,PARA_STATUS,PARA_NUMBER) VALUES(?,?,?,?,SYSDATE,?,?)";
    
    
    //modified bt shruti-3rd sep 2013
    /*public static final String RETRIEVE_DOC_STATUS=
    	"SELECT ESTAMP_DOC_ID,ESTAMP_DOC_STATUS FROM IGRS_ESTAMP_DOCUMENT_DETAILS WHERE ESTAMP_DOC_ID=?";*/
    
    //modified by shruti 16/oct/2013----creation query--- ist time status will be open
    public static final String RETRIEVE_DOC_STATUS=
    	"SELECT REG_INIT_ID,'OPEN' FROM IGRS_ESTAMP_DETLS IED,IGRS_REG_TXN_DETLS RTD WHERE RTD.REG_TXN_ID=IED.REG_INIT_ID AND RTD.REGISTRATION_NUMBER=?";
    
    
    //modified by shruti-3rd sep 2013
   /* public static final String RETRIEVE_REG_STATUS=
    	"SELECT REGISTRATION_ID,REGISTRATION_STATUS FROM IGRS_REG_COMPLETION_DETAILS where REGISTRATION_ID =?";*/
    
    //modified by shruti-16/10/2013--creation query--- ist time status will be open
    public static final String RETRIEVE_REG_STATUS="SELECT REGISTRATION_NUMBER,'OPEN' FROM IGRS_REG_TXN_DETLS where REGISTRATION_NUMBER =?";
    
    
    public static final String RETRIEVE_EXISTING_DETAILS=
    	"SELECT TRANSACTION_ID,to_char(AUDIT_DATE, 'DD/MM/YYYY'),to_char(DISPATCH_DATE, 'DD/MM/YYYY'),"+
    	"AUDIT_REPORT_STATUS FROM  IGRS_RAUDIT_TXN_DETAILS WHERE (AUDIT_DATE BETWEEN(?) AND (?)) AND AUDIT_BODY_TYPE=? AND DRS_OFFICE_ID = ?";
    
    //added by shruti---20 june 2014
    public static final String RETRIEVE_EXISTING_DETAILS_AGMP_RCPT=
    	"SELECT TRANSACTION_ID,to_char(AUDIT_DATE, 'DD/MM/YYYY'),to_char(DISPATCH_DATE, 'DD/MM/YYYY'),"+
    	"AUDIT_REPORT_STATUS FROM  IGRS_RAUDIT_TXN_DETAILS WHERE (AUDIT_DATE BETWEEN(?) AND (?)) AND AUDIT_BODY_TYPE=? AND DRS_OFFICE_ID = ? and TRANSACTION_ID like 'AGR%'";
    
    public static final String RETRIEVE_EXISTING_DETAILS_AGMP_EXP=
    	"SELECT TRANSACTION_ID,to_char(AUDIT_DATE, 'DD/MM/YYYY'),to_char(DISPATCH_DATE, 'DD/MM/YYYY'),"+
    	"AUDIT_REPORT_STATUS FROM  IGRS_RAUDIT_TXN_DETAILS WHERE (AUDIT_DATE BETWEEN(?) AND (?)) AND AUDIT_BODY_TYPE=? AND DRS_OFFICE_ID = ? and TRANSACTION_ID like 'AGE%'";
    
    public static final String RETRIEVE_EXISTING_DETAILS_INTERNAL_RCPT=
    	"SELECT TRANSACTION_ID,to_char(AUDIT_DATE, 'DD/MM/YYYY'),to_char(DISPATCH_DATE, 'DD/MM/YYYY'),"+
    	"AUDIT_REPORT_STATUS FROM  IGRS_RAUDIT_TXN_DETAILS WHERE (AUDIT_DATE BETWEEN(?) AND (?)) AND AUDIT_BODY_TYPE=? AND DRS_OFFICE_ID = ? and TRANSACTION_ID like 'IA%'";
    
    public static final String RETRIEVE_EXISTING_DETAILS_INTERNAL_EXP=
    	"SELECT TRANSACTION_ID,to_char(AUDIT_DATE, 'DD/MM/YYYY'),to_char(DISPATCH_DATE, 'DD/MM/YYYY'),"+
    	"AUDIT_REPORT_STATUS FROM  IGRS_RAUDIT_TXN_DETAILS WHERE (AUDIT_DATE BETWEEN(?) AND (?)) AND AUDIT_BODY_TYPE=? AND DRS_OFFICE_ID = ? and TRANSACTION_ID like 'IE%'";
    //end
    
    public static final String INSERT_RAUDIT_COMMENTS=
    	"INSERT INTO IGRS_RAUDIT_COMMENT_DETAILS(COMMENT_TXN_ID,AUDITOR_BODY_NAME,AUDITOR_LOCATION,DRS_USER_COMMENTS,COMMENTS_DATE) VALUES(?,?,?,?,SYSDATE)";
    public static final String RETRIEVE_SEQ_TXN_IDS=
    	"SELECT MAX(TRANSACTION_ID),MAX(COMMENT_TXN_id),MAX(PARA_TXN_id),MAX(OBJECTION_TXN_ID) from IGRS_RAUDIT_TXN_DETAILS,IGRS_RAUDIT_COMMENT_DETAILS,IGRS_RAUDIT_PARA_DETAILS,IGRS_RAUDIT_PARA_OBJ_DETAILS";
    
    //MODIFIED BY SHRUTI-2ND SEP 2013
    /*public static final String INSERT_IGRS_RAUDIT_COMMENT_MAPPING=
    	"INSERT INTO IGRS_RAUDIT_COMMENTS_MAPPING VALUES(?,?,?,?)";*/
    
    public static final String INSERT_IGRS_RAUDIT_COMMENT_MAPPING="INSERT INTO IGRS_RAUDIT_COMMENTS_MAPPING(AUDIT_TXN_ID,COMMENT_TXN_ID,PARA_TXN_ID,OBJECTION_TXN_ID) VALUES(?,?,?,?)";
    
    
    
    public static final String INSERT_IGRS_RAUDIT_DOC_MAPPING=
    	"INSERT INTO IGRS_RAUDIT_DOC_MAPPING(AUDIT_TXN_ID,DOCUMENT_TXN_ID,PARA_TXN_ID,OBJECTION_TXN_ID) VALUES(?,?,?,?)";
    public static final String INSERT_IGRS_RAUDIT_PARA_MAPPING=
    	"INSERT INTO IGRS_RAUDIT_PARA_MAPPING(AUDIT_TXN_ID,PARA_TXN_ID) VALUES(?,?)";
    
    public static final String INSERT_IGRS_RAUDIT_PARA_OBJ_MAPPING=
    	"INSERT INTO IGRS_RAUDIT_PARA_OBJ_MAPPING(PARA_TXN_ID,OBJECTION_TXN_ID) VALUES(?,?)";
    
    public static final String RETRIEVE_REGISTERED_DOC_STATUS=
    	"SELECT REGISTRATION_ID,REGISTRATION_STATUS FROM IGRS_REG_COMPLETION_DETAILS WHERE REGISTRATION_ID=?";
    public static final String INSERT_IGRS_RAUDIT_PARA_AGMP_COMMENT=
    	"INSERT INTO IGRS_RAUDIT_COMMENT_DETAILS(COMMENT_TXN_ID,DRS_USER_COMMENTS,AUDITOR_BODY_NAME,AUDITOR_LOCATION) VALUES(?,?,?,?)";
    public static final String RETRIEVE_EXISTING_RECORD=
    	"SELECT ircd.AUDITOR_BODY_NAME"
       +",ircd.AUDITOR_LOCATION"
       +",to_char(irtd.AUDIT_FROM_DATE, 'DD/MM/YYYY')"
       +",to_char(irtd.AUDIT_TO_DATE, 'DD/MM/YYYY')"
       +",irtd.TRANSACTION_ID"
       +",irtd.PHYSICAL_REPORT_ID"
       +",to_char(irtd.AUDIT_DATE, 'DD/MM/YYYY')"
       +",to_char(irtd.DISPATCH_DATE, 'DD/MM/YYYY')"
       +",to_char(irtd.ENTRY_DATE, 'DD/MM/YYYY')"
       +",irtd.FINAL_COMMENTS"
       +",iom.OFFICE_NAME" 
       +" FROM   IGRS_RAUDIT_TXN_DETAILS irtd"
       +",IGRS_RAUDIT_COMMENT_DETAILS ircd"
       +",IGRS_RAUDIT_COMMENTS_MAPPING ircm"
       +",IGRS_OFFICE_MASTER iom"
       +" WHERE  irtd.TRANSACTION_ID = ircm.AUDIT_TXN_ID(+)"
       +" AND    ircm.COMMENT_TXN_ID = ircd.COMMENT_TXN_ID(+)"
       +" AND    irtd.DRS_OFFICE_ID  = iom.OFFICE_ID(+)"
       +" AND    irtd.TRANSACTION_ID = ?";
    //ADDED BY SHRUTI
    public static final String RETRIEVE_EXISTING_RECORD_H=
    	"SELECT ircd.AUDITOR_BODY_NAME"
       +",ircd.AUDITOR_LOCATION"
       +",to_char(irtd.AUDIT_FROM_DATE, 'DD/MM/YYYY')"
       +",to_char(irtd.AUDIT_TO_DATE, 'DD/MM/YYYY')"
       +",irtd.TRANSACTION_ID"
       +",irtd.PHYSICAL_REPORT_ID"
       +",to_char(irtd.AUDIT_DATE, 'DD/MM/YYYY')"
       +",to_char(irtd.DISPATCH_DATE, 'DD/MM/YYYY')"
       +",to_char(irtd.ENTRY_DATE, 'DD/MM/YYYY')"
       +",irtd.FINAL_COMMENTS"
       +",iom.H_OFFICE_NAME" 
       +" FROM   IGRS_RAUDIT_TXN_DETAILS irtd"
       +",IGRS_RAUDIT_COMMENT_DETAILS ircd"
       +",IGRS_RAUDIT_COMMENTS_MAPPING ircm"
       +",IGRS_OFFICE_MASTER iom"
       +" WHERE  irtd.TRANSACTION_ID = ircm.AUDIT_TXN_ID(+)"
       +" AND    ircm.COMMENT_TXN_ID = ircd.COMMENT_TXN_ID(+)"
       +" AND    irtd.DRS_OFFICE_ID  = iom.OFFICE_ID(+)"
       +" AND    irtd.TRANSACTION_ID = ?";
    //END
    
    //modified by shruti----28 march 2014
    /*public static final String RETRIEVE_SEQ_RAUDIT_TXN_DETAILS=
    	"SELECT 'AGR'||TO_CHAR(SYSDATE,'DD')||TO_CHAR(SYSDATE,'MM')||TO_CHAR(SYSDATE,'RRRR')||"+
         "LPAD(IGRS_RCPT_AUDIT_TXN_SEQ.NEXTVAL,4,0)"+ 
         "FROM DUAL";*/
    public static final String RETRIEVE_SEQ_RAUDIT_TXN_DETAILS=
    	"SELECT 'AGR'||TO_CHAR(SYSDATE,'MM')||TO_CHAR(SYSDATE,'RRRR')||"+
         "LPAD(IGRS_RCPT_AUDIT_TXN_SEQ.NEXTVAL,4,0)"+ 
         "FROM DUAL";
    
    //added by shruti---13 june 2014
    public static final String GET_INTERNAL_EXP_SEQ=
    	"SELECT TO_CHAR(SYSDATE,'MM')||TO_CHAR(SYSDATE,'RRRR')||"+
         "LPAD(IGRS_INTERNAL_EXP_SEQ.NEXTVAL,4,0)"+ 
         "FROM DUAL";
    
    public static final String GET_INTERNAL_RCPT_SEQ=
    	"SELECT TO_CHAR(SYSDATE,'MM')||TO_CHAR(SYSDATE,'RRRR')||"+
         "LPAD(IGRS_INTERNAL_RCPT_SEQ.NEXTVAL,4,0)"+ 
         "FROM DUAL";
    
    public static final String GET_AGMP_EXP_SEQ=
    	"SELECT TO_CHAR(SYSDATE,'MM')||TO_CHAR(SYSDATE,'RRRR')||"+
         "LPAD(IGRS_AGMP_EXP_SEQ.NEXTVAL,4,0)"+ 
         "FROM DUAL";
    public static final String GET_AGMP_RCPT_SEQ=
    	"SELECT TO_CHAR(SYSDATE,'MM')||TO_CHAR(SYSDATE,'RRRR')||"+
         "LPAD(IGRS_AGMP_RCPT_SEQ.NEXTVAL,4,0)"+ 
         "FROM DUAL";
    //end
    
    public static final String RETRIEVE_SEQ_RAUDIT_DOC_DETAILS=
    	"SELECT 'DOC'||LPAD(IGRS_RAUDIT_DOC_DTL_SEQ.NEXTVAL,4,0)"+ 
        "FROM DUAL";
    public static final String RETRIEVE_SEQ_RAUDIT_OBJECTION_DETAILS=
    	"SELECT 'POBJ'||LPAD(IGRS_RAUDIT_PARA_OBJ_DTL_SEQ.NEXTVAL,4,0) FROM DUAL";
    public static final String RETRIEVE_SEQ_RAUDIT_PARA_DETAILS=
    	"SELECT 'PTXN'||LPAD(IGRS_RAUDIT_PARA_OBJ_DTL_SEQ.NEXTVAL,4,0)FROM DUAL";
    public static final String RETRIEVE_SEQ_COMMENT_DETAILS=
    	"SELECT 'CMT'||LPAD(IGRS_RAUDIT_COMMENT_DTL_SEQ.NEXTVAL,4,0)FROM DUAL";
    public static final String RETRIEVE_SRO_INSP_SEQ=
        	"SELECT LPAD(IGRS_SRO_INSP_DETAILS_SEQ.NEXTVAL,4,0) FROM dual";
    public static final String RETRIEVE_INSP_DOC_MAP_SEQ=
    	"SELECT 'DOCTXN' || LPAD(IGRS_SRO_INSP_DOC_MAP_SEQ.NEXTVAL,4,0) FROM dual";
   /* public static final String RETRIEVE_ITEM_ID=
    	"SELECT ITEM_ID FROM IGRS_INSP_CHECK_LIST_MASTER WHERE ITEM_NAME= ? OR H_ITEM_NAME=?";*/
    public static final String RETRIEVE_ITEM_ID=
    	"SELECT ITEM_ID FROM IGRS_INSP_CHECK_LIST_MASTER WHERE ITEM_ID IN(?)";
    public static final String INSERT_CHECK_MAP_DETAILS=
    	"INSERT INTO IGRS_INSP_CHECK_LIST_MAP(INSP_TXN_ID,ITEM_ID,CHECK_LIST_COMMENTS,ITEM_CHECKED_DATE) VALUES(?,?,?,SYSDATE)";
    
    public static final String INSERT_PENDING_ITEMS=
        	"INSERT INTO IGRS_INSPECTION_PENDING_ITEMS(INSP_TXN_ID,PENDING_ITEM,PENDING_FROM,PENDING_TASK_NO,PENDING_COMMENTS) VALUES(?,?,?,?,?)";
     
    public static final String INSERT_SRO_COMMENTS=
    	"INSERT INTO IGRS_SRO_INSP_COMMENTS(USER_ID,USER_COMMENTS,INSP_TXN_ID,SRO_INSP_COMMENT_ID,USER_COMMENTS_DATE) VALUES(?,?,?,?,SYSDATE)";
    
    public static final String INSERT_SRO_EMP_MAP=
    	"INSERT INTO IGRS_SRO_INSP_EMP_MAP(INSP_TXN_ID,EMP_ID) VALUES(?,?)";
    
    public static final String RETRIEVE_CHKLIST_ITEMS=
    	"SELECT  ITEM_NAME,ITEM_ID FROM IGRS_INSP_CHECK_LIST_MASTER WHERE ITEM_CHECK_REMARKS = ?";
    
    public static final String RETRIEVE_CHKLIST_ITEMS_HI=
    	"SELECT  H_ITEM_NAME,ITEM_ID FROM IGRS_INSP_CHECK_LIST_MASTER WHERE ITEM_CHECK_REMARKS = ?";
    
    
    public static final String RETRIEVE_CHKLIST_NAMES=
    	"SELECT  ITEM_ID FROM IGRS_INSP_CHECK_LIST_MASTER WHERE ITEM_ID in(";
    public static final String RETRIEVE_CHKLIST_NAMES1=")";
   
    public static final String RETRIEVE_CHKLIST_NAMES_HI=
    	"SELECT  H_ITEM_ID FROM IGRS_INSP_CHECK_LIST_MASTER WHERE ITEM_Id in(";
    
    public static final String RETRIEVE_CHKLIST_NAMES_HI1=")";
    
    
    
   /* public static final String GET_CHKLIST_ITEMS=
    	"SELECT  ITEM_NAME,ITEM_ID FROM IGRS_INSP_CHECK_LIST_MASTER WHERE ITEM_NAME IN (";*/
    public static final String GET_CHKLIST_ITEMS=
    	"SELECT  ITEM_NAME,ITEM_ID FROM IGRS_INSP_CHECK_LIST_MASTER WHERE ITEM_ID IN (";
    public static final String GET_CHKLIST_ITEMS1=")";
    
   /* public static final String GET_CHKLIST_ITEMS_HI=
    	"SELECT  H_ITEM_NAME,ITEM_ID FROM IGRS_INSP_CHECK_LIST_MASTER WHERE H_ITEM_NAME IN (";*/
    public static final String GET_CHKLIST_ITEMS_HI=
    	"SELECT  H_ITEM_NAME,ITEM_ID FROM IGRS_INSP_CHECK_LIST_MASTER WHERE ITEM_ID IN (";
    
    public static final String GET_CHKLIST_ITEMS_HI1=")";
    
    public static final String INSERT_SRO_INSP_DETAILS=
    	"INSERT INTO IGRS_SRO_INSP_DETAILS(INSPECTION_DATE,INSPECTED_BY,INSPECTED_OFFICE_ID,INSPECTION_START_DATE," +
    	"INSPECTION_END_DATE,OFFICE_USER_ID,LFY_ANNUAL_TARGETS,LFY_ANNUAL_RECEIPTS,LFY_PCT_COMPLETED,LFY_PCT_INCREASE," +
    	"CFY_ANNUAL_INCOME,CFY_ANNUAL_RECEIPTS,LFY_INCOME,INCOME_UNACCOM_REASON_CFY,INCOME_UNACCOM_REASON_LFY,CASH_DEPOSIT_BANK," +
    	"NO_RTI_REQUEST_CFY,NO_DISPOSED_RTI_REQ_CFY,REASON_FOR_PENDING_REQ,INSPECTION_STATUS,CREATED_BY,INSP_AUTHORITY_NAME,SR_NAME,UPDATE_BY,TRANSACTION_ID,CFY_INCOME_FROM,CFY_INCOME_TO,CFY_RECIEPT_FROM,CFY_RECIEPT_TO,LFY_INCOME_FROM,LFY_INCOME_TO,OBJECTED_ENTRY_DATE,PAST_INSPECTION_DETAILS,CREATED_DATE,INSPECTION_ENTRY_DATE,UPDATE_DATE,INSPECTION_DUE_DATE,TENURE) " +
    	"VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,SYSDATE,SYSDATE,SYSDATE,SYSDATE+15,?)";
    
    public static final String INSERT_SRO_DOC_MAP=
    	"INSERT INTO IGRS_SRO_INSP_DOC_MAP VALUES(?,?,?,?)";
    
    public static final String RETRIEVE_SELECTED_CHK_ITEMS=
    	"SELECT e3.ITEM_NAME FROM IGRS_SRO_INSP_DETAILS e1,IGRS_INSP_CHECK_LIST_MAP e2,IGRS_INSP_CHECK_LIST_MASTER e3 " +
    	"WHERE e1.TRANSACTION_ID = e2.INSP_TXN_ID AND e2.ITEM_ID = e3.ITEM_ID AND e3.ITEM_CHECK_REMARKS = 'Y' " +
    	"AND e1.TRANSACTION_ID = ? ";
    public static final String RETRIEVE_SELECTED_CHK_ITEMS_H=
    	"SELECT e3.H_ITEM_NAME FROM IGRS_SRO_INSP_DETAILS e1,IGRS_INSP_CHECK_LIST_MAP e2,IGRS_INSP_CHECK_LIST_MASTER e3 " +
    	"WHERE e1.TRANSACTION_ID = e2.INSP_TXN_ID AND e2.ITEM_ID = e3.ITEM_ID AND e3.ITEM_CHECK_REMARKS = 'Y' " +
    	"AND e1.TRANSACTION_ID = ? ";
    
    public static final String RETRIEVE_SELECTED_CHK_OTHERS_ITEMS=
    	"SELECT e3.ITEM_NAME,e2.ITEM_REMARKS FROM IGRS_SRO_INSP_DETAILS e1,IGRS_INSP_CHECK_LIST_MAP e2,IGRS_INSP_CHECK_LIST_MASTER e3 " +
    	"WHERE e1.TRANSACTION_ID = e2.INSP_TXN_ID AND e2.ITEM_ID = e3.ITEM_ID AND e3.ITEM_CHECK_REMARKS = 'N' " +
    	"AND e1.TRANSACTION_ID = ? ";
    public static final String RETRIEVE_SELECTED_CHK_OTHERS_ITEMS_H=
    	"SELECT e3.H_ITEM_NAME,e2.ITEM_REMARKS FROM IGRS_SRO_INSP_DETAILS e1,IGRS_INSP_CHECK_LIST_MAP e2,IGRS_INSP_CHECK_LIST_MASTER e3 " +
    	"WHERE e1.TRANSACTION_ID = e2.INSP_TXN_ID AND e2.ITEM_ID = e3.ITEM_ID AND e3.ITEM_CHECK_REMARKS = 'N' " +
    	"AND e1.TRANSACTION_ID = ? ";
    //modified by vinay
    public static final String RETRIEVE_SRO_DETAILS=
    	"SELECT INSP.TRANSACTION_ID,to_char(INSP.INSPECTION_START_DATE, 'DD/MM/YYYY'),to_char(INSP.INSPECTION_END_DATE, 'DD/MM/YYYY'),INSP.LFY_ANNUAL_TARGETS,INSP.LFY_ANNUAL_RECEIPTS," +
    	"INSP.LFY_PCT_COMPLETED,INSP.LFY_PCT_INCREASE,INSP.CFY_ANNUAL_INCOME,INSP.CFY_ANNUAL_RECEIPTS,INSP.LFY_INCOME,INSP.INCOME_UNACCOM_REASON_CFY," +
    	"INSP.INCOME_UNACCOM_REASON_LFY,INSP.CASH_DEPOSIT_BANK,INSP.NO_RTI_REQUEST_CFY,INSP.NO_DISPOSED_RTI_REQ_CFY,INSP.REASON_FOR_PENDING_REQ," +
    	"INSP.INSPECTION_STATUS,INSP.INSP_AUTHORITY_NAME,INSP.SR_NAME,INSP.CFY_INCOME_TO,INSP.CFY_INCOME_FROM,INSP.CFY_RECIEPT_TO,INSP.CFY_RECIEPT_FROM,INSP.LFY_INCOME_TO,INSP.LFY_INCOME_FROM,to_char(INSP.INSPECTION_DUE_DATE,'dd/mm/yyyy'),to_char(INSP.OBJECTED_ENTRY_DATE,'dd/mm/yyyy'),INSP.PAST_INSPECTION_DETAILS,to_char(INSP.INSPECTION_ENTRY_DATE,'dd/mm/yyyy'),to_char(INSP.INSPECTION_DATE,'dd/mm/yyyy'),OFFC.OFFICE_NAME,DISTT.DISTRICT_NAME,INSP.TENURE,"+
    	" INSP.SR_COMPLIANCE,INSP.DR_COMPLIANCE,INSP.DIG_COMPLIANCE,INSP.IG_COMPLIANCE FROM IGRS_SRO_INSP_DETAILS INSP,IGRS_OFFICE_MASTER OFFC,IGRS_DISTRICT_MASTER DISTT WHERE INSP.INSPECTED_OFFICE_ID=OFFC.OFFICE_ID AND OFFC.DISTRICT_ID=DISTT.DISTRICT_ID AND INSP.TRANSACTION_ID=?";
    
    public static final String RETRIEVE_SRO_DETAILS_H=
    	"SELECT INSP.TRANSACTION_ID,to_char(INSP.INSPECTION_START_DATE, 'DD/MM/YYYY'),to_char(INSP.INSPECTION_END_DATE, 'DD/MM/YYYY'),INSP.LFY_ANNUAL_TARGETS,INSP.LFY_ANNUAL_RECEIPTS," +
    	"INSP.LFY_PCT_COMPLETED,INSP.LFY_PCT_INCREASE,INSP.CFY_ANNUAL_INCOME,INSP.CFY_ANNUAL_RECEIPTS,INSP.LFY_INCOME,INSP.INCOME_UNACCOM_REASON_CFY," +
    	"INSP.INCOME_UNACCOM_REASON_LFY,INSP.CASH_DEPOSIT_BANK,INSP.NO_RTI_REQUEST_CFY,INSP.NO_DISPOSED_RTI_REQ_CFY,INSP.REASON_FOR_PENDING_REQ," +
    	"INSP.INSPECTION_STATUS,INSP.INSP_AUTHORITY_NAME,INSP.SR_NAME,INSP.CFY_INCOME_TO,INSP.CFY_INCOME_FROM,INSP.CFY_RECIEPT_TO,INSP.CFY_RECIEPT_FROM,INSP.LFY_INCOME_TO,INSP.LFY_INCOME_FROM,to_char(INSP.INSPECTION_DUE_DATE,'dd/mm/yyyy'),to_char(INSP.OBJECTED_ENTRY_DATE,'dd/mm/yyyy'),INSP.PAST_INSPECTION_DETAILS,to_char(INSP.INSPECTION_ENTRY_DATE,'dd/mm/yyyy'),to_char(INSP.INSPECTION_DATE,'dd/mm/yyyy'),OFFC.H_OFFICE_NAME,DISTT.H_DISTRICT_NAME,INSP.TENURE,"+
    	" INSP.SR_COMPLIANCE,INSP.DR_COMPLIANCE,INSP.DIG_COMPLIANCE,INSP.IG_COMPLIANCE FROM IGRS_SRO_INSP_DETAILS INSP,IGRS_OFFICE_MASTER OFFC,IGRS_DISTRICT_MASTER DISTT WHERE INSP.INSPECTED_OFFICE_ID=OFFC.OFFICE_ID AND OFFC.DISTRICT_ID=DISTT.DISTRICT_ID AND INSP.TRANSACTION_ID=?";
   
    //modified by shruti---2 march 2014
    /*public static final String RETRRIEVE_INSP_EMP_DETAILS=
    		"SELECT MAST.FIRST_NAME,cad.cadre_name,to_char(OFFI.DATE_OF_JOINING, 'DD/MM/YYYY'),"+
    		" to_char(OFFI.DATE_OF_SEPARATION, 'DD/MM/YYYY') FROM "+
    		" IGRS_SRO_INSP_EMP_MAP EMP,IGRS_EMP_MASTER MAST,"+
    		" IGRS_EMP_OFFICIAL_DETAILS OFFI ,IGRS_EMP_CADRE_MASTER CAD"+
    		" WHERE EMP.EMP_ID = MAST.EMP_ID AND EMP.EMP_ID = OFFI.EMP_ID"+ 
    		" AND CAD.cadre_id=OFFI.EMP_DESIGNATION_ID AND EMP.INSP_TXN_ID =?";*/
    
    public static final String RETRRIEVE_INSP_EMP_DETAILS=
		"SELECT MAST.FIRST_NAME,cad.cadre_name,to_char(OFFI.DATE_OF_JOINING, 'DD/MM/YYYY'),"+
		" to_char(OFFI.DATE_OF_SEPARATION, 'DD/MM/YYYY'),MAST.EMP_ID FROM "+
		" IGRS_SRO_INSP_EMP_MAP EMP,IGRS_EMP_MASTER MAST,"+
		" IGRS_EMP_OFFICIAL_DETAILS OFFI ,IGRS_EMP_CADRE_MASTER CAD"+
		" WHERE EMP.EMP_ID = MAST.EMP_ID AND EMP.EMP_ID = OFFI.EMP_ID"+ 
		" AND CAD.cadre_id=OFFI.EMP_DESIGNATION_ID AND EMP.INSP_TXN_ID =?";
   
    public static final String RETRIEVE_PENDING_ITEMS=
    	"SELECT PENDING_ITEM,TO_CHAR(PENDING_FROM,'DD/MM/YYYY'),PENDING_TASK_NO FROM IGRS_INSPECTION_PENDING_ITEMS WHERE  INSP_TXN_ID = ?";
    //end
    public static final String RETRRIEVE_EMP_DETAILS=
    	"SELECT e3.DESIG_NAME,to_char(e2.DATE_OF_JOINING, 'DD/MM/YYYY'),to_char(e2.DATE_OF_SEPARATION, 'DD/MM/YYYY'),e1.FIRST_NAME,e1.EMP_ID  FROM IGRS_EMP_MASTER e1,"+
    	"IGRS_EMP_OFFICIAL_DETAILS e2,IGRS_EMP_DESIGNATION_MASTER e3 WHERE e1.EMP_ID = e2.EMP_ID AND e2.EMP_DESIGNATION_ID = e3.DESIG_ID "+
    	"AND e1.EMP_ID = ?";
    
    /*public static final String RETRIEVE_INSP_IDS=
    	"SELECT TRANSACTION_ID,INSPECTION_START_DATE,INSPECTION_END_DATE,INSPECTION_STATUS FROM IGRS_SRO_INSP_DETAILS"; */
    
    public static final String RETRIEVE_INSP_IDS=
    	"SELECT INSP.TRANSACTION_ID,to_char(INSP.INSPECTION_START_DATE, 'DD/MM/YYYY'),to_char(INSP.INSPECTION_END_DATE, 'DD/MM/YYYY'),INSP.INSPECTION_STATUS FROM IGRS_SRO_INSP_DETAILS INSP" +
    	" WHERE 1=1 ";//INSP.INSPECTION_START_DATE  BETWEEN ? AND ? AND INSP.OFFICE_USER_ID = ? OR INSP.TRANSACTION_ID=?";
    
    public static final String RETRIEVE_SRO_COMMENTS=
    	"SELECT USER_COMMENTS FROM IGRS_SRO_INSP_COMMENTS WHERE INSP_TXN_ID= ?";
    
    public static final String RETRIEVE_DOC_NAME=
    	"SELECT DOCUMENT_NAME,DOCUMENT_PATH FROM IGRS_SRO_INSP_DOC_MAP WHERE INSP_TXN_ID = ?";
    
	public static final String RETRIVE_EMPLOYEE_DETAILS="select emp.FIRST_NAME ||' '|| LAST_NAME,"
		+ " iecm.CADRE_NAME,"
		+ " to_char(IEOD.DATE_OF_JOINING, 'DD/MM/YYYY'),"
		+ " to_char(IEOD.DATE_OF_SEPARATION, 'DD/MM/YYYY')"		
		+ " FROM IGRS_EMP_MASTER emp,IGRS_EMP_CADRE_MASTER iecm,"		
		+ "IGRS_EMP_OFFICIAL_DETAILS IEOD"
		+ " WHERE emp.EMP_ID=IEOD.EMP_ID AND "
		+ " IEOD.EMP_DESIGNATION_ID=iecm.CADRE_ID AND emp.EMP_ID=? ";
	
	public static final String RETRIEVE_CHECK_ITEMS=
    	"SELECT ITEM_NAME FROM IGRS_DRO_INSP_ITEM_MASTER WHERE ITEM_GROUP_ID = ? AND ITEM_CHECK = ?";
    
    public static final String RETRIEVE_GROUP_NAME=
    	"SELECT GROUP_NAME,GROUP_ID FROM IGRS_DRO_INSP_GROUP_MASTER WHERE GROUP_ID = ?";
    
    public static final String RETRIEVE_TEXT_ITEM_NAMES=
    	"SELECT ITEM_NAME,TRUNC(TO_DATE('01-APR-'||TO_CHAR(TRUNC(ADD_MONTHS(TRUNC(SYSDATE),CASE WHEN TO_CHAR(TRUNC(SYSDATE),'MM')>=4 " +
    	"THEN 0 ELSE -12 END),'YY'),'YY'),'DD-MON-YY')) AS FROM_DATE,TRUNC(TO_DATE('31-MAR-'||TO_CHAR(TRUNC(ADD_MONTHS(TRUNC(SYSDATE),CASE " +
    	"WHEN TO_CHAR(TRUNC(SYSDATE),'MM')>=4 THEN 12 ELSE 0 END),'YY'),'YY'),'DD-MON-YY'))  AS TO_DATE FROM IGRS_DRO_INSP_ITEM_MASTER " +
    	"WHERE ITEM_GROUP_ID =? AND ITEM_TEXTBOX= ?";
    
    public static final String RETRIEVE_REMARKS_ITEM_NAMES=
    	"SELECT ITEM_NAME FROM IGRS_DRO_INSP_ITEM_MASTER WHERE ITEM_GROUP_ID = ? AND ITEM_REMARKS = ?";
    
    public static final String RETRIEVE_CHK_RADIO_ITEMS=
    	"SELECT ITEM_NAME FROM IGRS_DRO_INSP_ITEM_MASTER WHERE ITEM_GROUP_ID = ? AND ITEM_CHECK_RADIO = ?";
    
    public static final String RETRIEVE_DOC_ITEMS=
    	"SELECT ITEM_NAME FROM IGRS_DRO_INSP_ITEM_MASTER WHERE ITEM_GROUP_ID = ? AND ITEM_DOCUMENT = ?";
    
    public static final String RETRIEVE_DRO_NAMES=
    	"select OFFICE_ID,OFFICE_NAME from IGRS_OFFICE_MASTER where OFFICE_TYPE_ID=(select distinct OFFICE_TYPE_ID from IGRS_OFFICE_TYPE_MASTER where OFFICE_TYPE_NAME='DRO') and PARENT_ID=?";
    
    public static final String RETRIEVE_DRO_NAMES_H=
    	"select OFFICE_ID,H_OFFICE_NAME from IGRS_OFFICE_MASTER where OFFICE_TYPE_ID=(select distinct OFFICE_TYPE_ID from IGRS_OFFICE_TYPE_MASTER where OFFICE_TYPE_NAME='DRO') and PARENT_ID=?";
    public static final String INSERT_DRO_INSP_DETAILS=
    	"INSERT INTO IGRS_DRO_INSP_DETAILS(INSPECTION_DATE,INSPECTED_BY,INSPECTED_OFFICE_ID," +
    	"INSPECTION_START_DATE,INSPECTION_END_DATE,OFFICE_USER_ID,LFY_ANNUAL_TARGETS,LFY_ANNUAL_RECEIPTS," +
    	"LFY_PCT_COMPLETED,LFY_PCT_INCREASE,CFY_ANNUAL_INCOME,CFY_ANNUAL_RECEIPTS,LFY_INCOME,INSPECTION_STATUS," +
    	"CREATED_BY,UPDATE_BY,TRANSACTION_ID,IG_COMMENTS,CFY_INCOME_FROM,CFY_INCOME_TO,CFY_RECIEPTS_FROM,CFY_RECIEPTS_TO,LFY_INCOME_FROM,LFY_INCOME_TO,SR_NAME,INSPECTION_ENTRY_DATE,CREATED_DATE," +
    	"UPDATE_DATE,INSPECTION_DUE_DATE,TENURE,INSP_AUTHORITY_NAME,OBJECTED_ENTRY_DATE,PAST_DETAILS,STAMP_DETAILS,PENDING_DETAILS,RRC_DETAILS,DE_DETAILS,PENSION_DETAILS) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,SYSDATE,SYSDATE,SYSDATE,SYSDATE+15,?,?,?,?,?,?,?,?,?)";
    
    public static final String INSERT_DRO_EMP_MAP=
    	"INSERT INTO IGRS_DRO_INSP_EMP_MAP(INSP_TXN_ID,EMP_ID,CREATED_DATE,CREATED_BY) VALUES(?,?,SYSDATE,'1')";
    
    public static final String INSERT_DRO_PENDING_ITEMS=
    	"INSERT INTO IGRS_DRO_INSP_PENDING_ITEMS(INSP_TXN_ID,PENDING_ITEM,PENDING_FROM,PENDING_TASK_NO) VALUES(?,?,?,?)";
    
    public static final String INSERT_DRO_ITEM_MAP=
    	"INSERT INTO IGRS_DRO_INSP_ITEM_MAP(DRO_INSP_TXN_ID,INSP_ITEM_ID,INSP_ITEM_REMARKS,INSP_ITEM_VALUE) VALUES(?,?,?,?)";
    
    public static final String INSERT_DRO_REASON_MAP=
    	"INSERT INTO IGRS_DRO_INSP_REASON_MAP(DRO_INSP_TXN_ID,UNACCOMPLISHED_REASON) VALUES(?,?)";
    
    public static final String RETRIEVE_DRO_ITEM_ID=
    	"SELECT ITEM_ID FROM IGRS_DRO_INSP_ITEM_MASTER WHERE ITEM_NAME = ?";
    
    public static final String RETRIVE_DISTRICT_NAME="select DISTRICT_NAME from IGRS_DISTRICT_MASTER " +
    		"where DISTRICT_ID=(select distinct DISTRICT_ID from IGRS_OFFICE_MASTER where OFFICE_ID=?)";
    
    public static final String RETRIVE_DISTRICT_NAME_H="select H_DISTRICT_NAME from IGRS_DISTRICT_MASTER " +
	"where DISTRICT_ID=(select distinct DISTRICT_ID from IGRS_OFFICE_MASTER where OFFICE_ID=?)";
    public static final String RETRIEVE_SEQ_DOC_TXN=
    	"SELECT 'DOCTXN' || IGRS_DRO_INSP_DOC_MAP_SEQ.NEXTVAL FROM dual";
    
    public static final String RETRIEVE_SEQ_DRO_TXN=
    	"SELECT 'DROTXN' || IGRS_DRO_INSP_DETAILS_SEQ.NEXTVAL FROM dual";
    
   // modified by vinay
    public static final String RETRIEVE_DRO_INSP_IDS=
    	"SELECT INSP.TRANSACTION_ID,INSP.INSPECTION_START_DATE,INSP.INSPECTION_END_DATE,INSP.INSPECTION_STATUS " +
    	"FROM IGRS_DRO_INSP_DETAILS INSP WHERE 1=1 ";//INSP.INSPECTION_START_DATE  BETWEEN ? AND ? " +
    	//"AND INSP.INSPECTED_OFFICE_ID = ? OR INSP.TRANSACTION_ID=?";
    
    public static final String RETRIEVE_DRO_INSP_DETAILS=
    	"SELECT DRO.OFFICE_NAME,DIS.DISTRICT_NAME,INSP.INSP_AUTHORITY_NAME,INSP.TRANSACTION_ID," +
    	"INSP.INSPECTION_START_DATE,INSP.INSPECTION_END_DATE,INSP.INSPECTION_DATE,INSP.SR_NAME," +
    	"INSP.LFY_ANNUAL_TARGETS,INSP.LFY_ANNUAL_RECEIPTS,INSP.LFY_PCT_COMPLETED,INSP.LFY_PCT_INCREASE," +
    	"INSP.CFY_ANNUAL_INCOME,INSP.CFY_ANNUAL_RECEIPTS,INSP.LFY_INCOME,INSP.INSPECTION_STATUS, " +
    	"TO_CHAR(INSP.INSPECTION_ENTRY_DATE,'DD/MM/YYYY'),TO_CHAR(INSP.INSPECTION_DUE_DATE,'DD/MM/YYYY'),INSP.TENURE,INSP.CFY_INCOME_FROM,INSP.CFY_INCOME_TO,"+
    	"INSP.CFY_RECIEPTS_FROM,INSP.CFY_RECIEPTS_TO,INSP.LFY_INCOME_FROM,INSP.LFY_INCOME_TO,INSP.IG_COMMENTS,INSP.PAST_DETAILS,TO_CHAR(INSP.OBJECTED_ENTRY_DATE,'MM/DD/YYYY'),"+
    	"INSP.STAMP_DETAILS,INSP.PENDING_DETAILS,INSP.RRC_DETAILS,INSP.DE_DETAILS,INSP.PENSION_DETAILS, "+
    	"INSP.DR_COMPLIANCE,INSP.DIG_COMPLIANCE,INSP.IG_COMPLIANCE FROM IGRS_DRO_INSP_DETAILS INSP,IGRS_OFFICE_MASTER DRO,IGRS_DISTRICT_MASTER DIS " +
    	"WHERE INSP.INSPECTED_OFFICE_ID = DRO.OFFICE_ID AND DRO.DISTRICT_ID = DIS.DISTRICT_ID AND " +
    	"TRANSACTION_ID=?";
    public static final String RETRIEVE_DRO_INSP_DETAILS_H=
    	"SELECT DRO.H_OFFICE_NAME,DIS.H_DISTRICT_NAME,INSP.INSP_AUTHORITY_NAME,INSP.TRANSACTION_ID," +
    	"INSP.INSPECTION_START_DATE,INSP.INSPECTION_END_DATE,INSP.INSPECTION_DATE,INSP.SR_NAME," +
    	"INSP.LFY_ANNUAL_TARGETS,INSP.LFY_ANNUAL_RECEIPTS,INSP.LFY_PCT_COMPLETED,INSP.LFY_PCT_INCREASE," +
    	"INSP.CFY_ANNUAL_INCOME,INSP.CFY_ANNUAL_RECEIPTS,INSP.LFY_INCOME,INSP.INSPECTION_STATUS, " +
    	"TO_CHAR(INSP.INSPECTION_ENTRY_DATE,'DD/MM/YYYY'),TO_CHAR(INSP.INSPECTION_DUE_DATE,'DD/MM/YYYY'),INSP.TENURE,INSP.CFY_INCOME_FROM,INSP.CFY_INCOME_TO,"+
    	"INSP.CFY_RECIEPTS_FROM,INSP.CFY_RECIEPTS_TO,INSP.LFY_INCOME_FROM,INSP.LFY_INCOME_TO,INSP.IG_COMMENTS,INSP.PAST_DETAILS,TO_CHAR(INSP.OBJECTED_ENTRY_DATE,'MM/DD/YYYY'),"+
    	"INSP.STAMP_DETAILS,INSP.PENDING_DETAILS,INSP.RRC_DETAILS,INSP.DE_DETAILS,INSP.PENSION_DETAILS, "+
    	"INSP.DR_COMPLIANCE,INSP.DIG_COMPLIANCE,INSP.IG_COMPLIANCE FROM IGRS_DRO_INSP_DETAILS INSP,IGRS_OFFICE_MASTER DRO,IGRS_DISTRICT_MASTER DIS " +
    	"WHERE INSP.INSPECTED_OFFICE_ID = DRO.OFFICE_ID AND DRO.DISTRICT_ID = DIS.DISTRICT_ID AND " +
    	"TRANSACTION_ID=?";
    public static final String RETRIEVE_DRO_EMP_DETAILS=
    	"SELECT MAST.EMP_ID,MAST.FIRST_NAME,DES.CADRE_NAME,OFFI.DATE_OF_JOINING,OFFI.DATE_OF_SEPARATION " +
    	"FROM IGRS_DRO_INSP_EMP_MAP EMP,IGRS_EMP_MASTER MAST,IGRS_EMP_CADRE_MASTER DES," +
    	"IGRS_EMP_OFFICIAL_DETAILS OFFI WHERE EMP.EMP_ID = MAST.EMP_ID AND EMP.EMP_ID = OFFI.EMP_ID " +
    	"AND OFFI.EMP_DESIGNATION_ID = DES.CADRE_ID AND EMP.INSP_TXN_ID = ?";
    
    public static final String RETRIEVE_DRO_REASON_DETAILS=
    	"SELECT UNACCOMPLISHED_REASON FROM IGRS_DRO_INSP_REASON_MAP WHERE DRO_INSP_TXN_ID = ?";
    
    public static final String RETRIEVE_DRO_PENDING_DETAILS=
    	"SELECT PENDING_ITEM,PENDING_FROM,PENDING_TASK_NO FROM IGRS_DRO_INSP_PENDING_ITEMS " +
    	"WHERE INSP_TXN_ID = ?";
    
    public static final String RETRIEVE_DRO_DOCUMENTS=
    	"SELECT DOCUMENT_NAME,DOCUMENT_PATH FROM IGRS_DRO_INSP_DOC_MAP WHERE INSP_TXN_ID = ?";// and DOC_TYPE_ID=(select DOCUMENT_TYPE_ID from IGRS_DOCUMENT_TYPE_MASTER where DOCUMENT_NAME=?)";

	public static final String SELECT_PARA_DETAILS = "select PARA_TYPE_ID,PARA_TYPE_NAME from IGRS_AUDIT_PARA_TYPE_MASTER where PARA_TYPE_STATUS='A' AND AUDIT_TYPE='R'";

	//added by shruti
	public static final String SELECT_PARA_DETAILS_H = "select PARA_TYPE_ID,H_PARA_TYPE_NAME from IGRS_AUDIT_PARA_TYPE_MASTER where PARA_TYPE_STATUS='A' AND AUDIT_TYPE='R'";

	
	//end
	
	//modified by shruti-16th oct 2013
	
	//added by shruti-9th 10th sep 2013
	/*public static final String GET_AUDIT_PARA_LIST="select PARA_TYPE_ID,PARA_NAME,PARA_NUMBER,PARA_STATUS from IGRS_RAUDIT_PARA_DETAILS irpd,IGRS_RAUDIT_PARA_MAPPING"
 +" irpm where irpd.PARA_TXN_ID=irpm.PARA_TXN_ID and irpm.AUDIT_TXN_ID=?"; */
	//end
	
	public static final String GET_AUDIT_PARA_LIST="select irpd.PARA_TYPE_ID,irpd.PARA_TXN_ID,irpd.PARA_STATUS from IGRS_RAUDIT_PARA_DETAILS irpd,"
	+" IGRS_RAUDIT_PARA_MAPPING irpm where irpd.PARA_TXN_ID=irpm.PARA_TXN_ID and irpm.AUDIT_TXN_ID=?";
	
	public static final String SELECT_EXP_PARA_DETAILS = "select PARA_TYPE_ID,PARA_TYPE_NAME from IGRS_AUDIT_PARA_TYPE_MASTER where PARA_TYPE_STATUS='A' AND AUDIT_TYPE='E'"; 
	//added by shruti-4th sep 2013
	public static final String GETPARTYDETAILS="SELECT PARTY_FIRST_NAME,PARTY_MIDDLE_NAME,PARTY_LAST_NAME,( SELECT PARTY_TYPE_NAME FROM "
				+" IGRS_PARTY_TYPE_MASTER WHERE PARTY_TYPE_STATUS='A' AND  PARTY_TYPE_ID=rtpd.PARTY_TYPE_ID) PARTY_TYPE_NAME, "
				+" PARTY_GENDER,PARTY_AGE,NATIONALITY,(SELECT COUNTRY_NAME FROM IGRS_COUNTRY_MASTER WHERE COUNTRY_STATUS='A' "
				+" AND COUNTRY_ID=rtpd.COUNTRY_ID) COUNTRY_NAME,(SELECT STATE_NAME FROM IGRS_STATE_MASTER WHERE "
				+" STATE_STATUS='A' AND STATE_ID=RTPD.STATE_ID) STATE_NAME, (SELECT DISTRICT_NAME FROM IGRS_DISTRICT_MASTER  WHERE DISTRICT_STATUS='A' AND  "
				+" DISTRICT_ID= RTPD.DISTRICT_ID) DISTRICT_NAME,PARTY_ADDRESS,POSTAL_CODE,PHONE_NUMBER,MOBILE_NUMBER,EMAIL_ID, "
				+" APPELLATE_TYPE_ID,GUARDIAN_NAME, MOTHER_NAME,ORGANIZATION_NAME,AUTHRZD_PERSN_NAME from IGRS_REG_TXN_PARTY_DETLS rtpd,IGRS_REG_TXN_DETLS irtd" 
				+" where rtpd.REG_TXN_ID=irtd.REG_TXN_ID and irtd.REGISTRATION_NUMBER=? order by PARTY_TYPE_ID";
	
	public static final String GETPARTYDETAILS_H="SELECT PARTY_FIRST_NAME,PARTY_MIDDLE_NAME,PARTY_LAST_NAME,( SELECT H_PARTY_TYPE_NAME FROM "
		+" IGRS_PARTY_TYPE_MASTER WHERE PARTY_TYPE_STATUS='A' AND  PARTY_TYPE_ID=rtpd.PARTY_TYPE_ID) PARTY_TYPE_NAME, "
		+" PARTY_GENDER,PARTY_AGE,NATIONALITY,(SELECT H_COUNTRY_NAME FROM IGRS_COUNTRY_MASTER WHERE COUNTRY_STATUS='A' "
		+" AND COUNTRY_ID=rtpd.COUNTRY_ID) COUNTRY_NAME,(SELECT H_STATE_NAME FROM IGRS_STATE_MASTER WHERE "
		+" STATE_STATUS='A' AND STATE_ID=RTPD.STATE_ID) STATE_NAME, (SELECT H_DISTRICT_NAME FROM IGRS_DISTRICT_MASTER  WHERE DISTRICT_STATUS='A' AND  "
		+" DISTRICT_ID= RTPD.DISTRICT_ID) DISTRICT_NAME,PARTY_ADDRESS,POSTAL_CODE,PHONE_NUMBER,MOBILE_NUMBER,EMAIL_ID, "
		+" APPELLATE_TYPE_ID,GUARDIAN_NAME, MOTHER_NAME,ORGANIZATION_NAME,AUTHRZD_PERSN_NAME from IGRS_REG_TXN_PARTY_DETLS rtpd,IGRS_REG_TXN_DETLS irtd" 
		+" where rtpd.REG_TXN_ID=irtd.REG_TXN_ID and irtd.REGISTRATION_NUMBER=? order by PARTY_TYPE_ID";

	public static final String GETPROPERTYDETAILS="SELECT  a.REG_TXN_ID, a.PROPERTY_ID,(SELECT b.property_type_name  FROM igrs_property_type_master b"+
	" WHERE b.property_type_status = 'A' AND b.property_type_id= a.PROP_TYPE_ID) PROPERTY_TYPE_NAME,(SELECT c.district_name"+
	" FROM igrs_district_master c WHERE c.district_status = 'A'  AND c.district_id=a.DISTRICT_ID) DISTRICT_NAME,(SELECT d.tehsil_name FROM igrs_tehsil_master d"+
	" WHERE d.tehsil_status = 'A' AND d.tehsil_id=a.TEHSIL_ID) TEHSIL_NAME,(SELECT e.WARD_PATWARI_NAME FROM IGRS_WARD_PATWARI_MASTER"+
	" e WHERE e.WARD_PATWARI_STATUS='A' AND e.WARD_PATWARI_ID=a.WARD_ID) WARD_PATWARI_NAME,(SELECT f.MOHALLA_VILLAGE_NAME  FROM"+
	" IGRS_MOHALLA_VILLAGE_MASTER f WHERE f.MOHALLA_VILLAGE_STATUS='A' AND f.MOHALLA_VILLAGE_ID=a.MOHALLA_ID) MOHALLA_VILLAGE_NAME,"+
	" (SELECT g.AREA_TYPE_NAME FROM IGRS_AREA_TYPE_MASTER g WHERE  g.AREA_TYPE_STATUS='A'  AND  g.AREA_TYPE_ID=a.AREA_TYPE_ID) AREA_TYPE_NAME,"+
	" (SELECT h.MUNICIPAL_BODY_NAME  FROM IGRS_MUNICIPAL_BODY_MASTER h WHERE  h.MUNICIPAL_BODY_STATUS='A'  AND  h.MUNICIPAL_BODY_ID=a.GOV_BODY_ID)"+
	" MUNICIPAL_BODY_NAME,a.VIKAS_KHAND,RI_CIRCLE,a.LAYOUT_DETAIL,a.NAZOOL_SHEET_NUMBER,"+
	" a.PROPERTY_ADDRESS,a.EAST_BOUNDARY,a.WEST_BOUNDARY,a.NORTH_BOUNDARY,a.SOUTH_BOUNDARY,a.AREA FROM IGRS_REG_PROPRTY_DTLS a,IGRS_REG_TXN_DETLS b"+
	" where  a.REG_TXN_ID =b.REG_TXN_ID and b.REGISTRATION_NUMBER=?";
	
	public static final String GETPROPERTYDETAILS_H="SELECT  a.REG_TXN_ID, a.PROPERTY_ID,(SELECT b.h_property_type_name  FROM igrs_property_type_master b"+
	" WHERE b.property_type_status = 'A' AND b.property_type_id= a.PROP_TYPE_ID) PROPERTY_TYPE_NAME,(SELECT c.h_district_name"+
	" FROM igrs_district_master c WHERE c.district_status = 'A'  AND c.district_id=a.DISTRICT_ID) DISTRICT_NAME,(SELECT d.h_tehsil_name FROM igrs_tehsil_master d"+
	" WHERE d.tehsil_status = 'A' AND d.tehsil_id=a.TEHSIL_ID) TEHSIL_NAME,(SELECT e.h_WARD_PATWARI_NAME FROM IGRS_WARD_PATWARI_MASTER"+
	" e WHERE e.WARD_PATWARI_STATUS='A' AND e.WARD_PATWARI_ID=a.WARD_ID) WARD_PATWARI_NAME,(SELECT f.H_MOHALLA_VILLAGE_NAME  FROM"+
	" IGRS_MOHALLA_VILLAGE_MASTER f WHERE f.MOHALLA_VILLAGE_STATUS='A' AND f.MOHALLA_VILLAGE_ID=a.MOHALLA_ID) MOHALLA_VILLAGE_NAME,"+
	" (SELECT g.H_AREA_TYPE_NAME FROM IGRS_AREA_TYPE_MASTER g WHERE  g.AREA_TYPE_STATUS='A'  AND  g.AREA_TYPE_ID=a.AREA_TYPE_ID) AREA_TYPE_NAME,"+
	" (SELECT h.H_MUNICIPAL_BODY_NAME  FROM IGRS_MUNICIPAL_BODY_MASTER h WHERE  h.MUNICIPAL_BODY_STATUS='A'  AND  h.MUNICIPAL_BODY_ID=a.GOV_BODY_ID)"+
	" MUNICIPAL_BODY_NAME,a.VIKAS_KHAND,RI_CIRCLE,a.LAYOUT_DETAIL,a.NAZOOL_SHEET_NUMBER,"+
	" a.PROPERTY_ADDRESS,a.EAST_BOUNDARY,a.WEST_BOUNDARY,a.NORTH_BOUNDARY,a.SOUTH_BOUNDARY,a.AREA FROM IGRS_REG_PROPRTY_DTLS a,IGRS_REG_TXN_DETLS b"+
	" where  a.REG_TXN_ID =b.REG_TXN_ID and b.REGISTRATION_NUMBER=?";
	
	public static final String GETOFFICENAME="SELECT iom.office_name FROM igrs_office_master iom where iom.office_id=?";
	
	
	    public static final String CASE_RETRIEVE_QUERY=
	    	"SELECT distinct CASE_TXN_ID,to_char(CREATED_DATE,'DD/MM/YYYY') FROM IGRS_CASE_TXN_DETAILS where CASE_TXN_ID=?";
	    
	    
	    public static final String CASE_DETAILS_RETRIEVE_QRY ="SELECT distinct CASE_TXN_ID,to_char(CREATED_DATE,'dd/mm/yyyy'),CASE_STATUS from IGRS_CASE_TXN_DETAILS where case_txn_id=?";
	    	    
	    public static final String GETCASESTATUS="SELECT CASE_TXN_ID,CASE_STATUS FROM IGRS_CASE_TXN_DETAILS WHERE CASE_TXN_ID=?";
	    public static final String GETRRCCASESTATUS="SELECT RRC_CASE,CASE_STATUS FROM IGRS_CASE_TXN_DETAILS WHERE RRC_CASE=?";
	    //added by ashima
	    public static final String GET_DOC_DETAILS="SELECT PD.PARA_TYPE_ID, PD.PARA_TXN_ID,PD.PARA_STATUS,PT.AUDIT_TXN_ID FROM IGRS_RAUDIT_PARA_DETAILS PD,IGRS_RAUDIT_PARA_MAPPING PT WHERE PD.PARA_TXN_ID=PT.PARA_TXN_ID AND PT.AUDIT_TXN_ID =?";

	    // added by vinay
	    
	    public static final String GETCOMMNTID="SELECT IGRS_SRO_INSP_COMMENT_ID_SEQ.NEXTVAL FROM DUAL";

	    public static final String GETDISTRICTID="SELECT DISTRICT_ID FROM IGRS_OFFICE_MASTER WHERE UPPER(OFFICE_ID)=?";

	    public static final String GETDISTRICTNAME="SELECT DM.DISTRICT_NAME FROM IGRS_DISTRICT_MASTER DM,IGRS_OFFICE_MASTER OM WHERE OM.DISTRICT_ID=DM.DISTRICT_ID AND UPPER(OM.OFFICE_ID)=?";
	    
	    public static final String GETDISTRICTNAME_H="SELECT DM.H_DISTRICT_NAME FROM IGRS_DISTRICT_MASTER DM,IGRS_OFFICE_MASTER OM WHERE OM.DISTRICT_ID=DM.DISTRICT_ID AND UPPER(OM.OFFICE_ID)=?";

	    
	    public static final String GETCURRENTDATE="SELECT TO_CHAR(SYSDATE,'DDMMYYYY') FROM DUAL";
	    
	    //added by shruti---2 march 2014
	    public static final String GETCURRENTDATENEWFORMAT="SELECT TO_CHAR(SYSDATE,'MMYYYY') FROM DUAL";
	    //added by ShreeRajKhare
	    
	   // public static final String GET_OFFICE_TYPE="SELECT OFFICE_TYPE_ID,OFFICE_TYPE_NAME FROM IGRS_OFFICE_TYPE_MASTER WHERE OFFICE_TYPE_ID IN(1,2,3) and OFFICE_TYPE_STATUS='A' ORDER BY OFFICE_TYPE_ID ASC";
//vinay
	    public static final String GET_OFFICE_TYPE="SELECT OFFICE_TYPE_ID,OFFICE_TYPE_NAME,OFFICE_TYPE_NAME_H FROM IGRS_OFFICE_TYPE_MASTER WHERE OFFICE_TYPE_ID =3 and OFFICE_TYPE_STATUS='A' ORDER BY OFFICE_TYPE_ID ASC";

	    
	    public static final String GET_DROSROHO_OFFICE_LIST="select a.OFFICE_ID,a.OFFICE_NAME,a.H_OFFICE_NAME from IGRS_OFFICE_MASTER a where a.OFFICE_TYPE_ID=? and a.OFFICE_STATUS='A'";

	    public static final String GET_OFFICE_LIST_SRO="select a.OFFICE_ID,a.OFFICE_NAME,a.H_OFFICE_NAME from IGRS_OFFICE_MASTER a where a.OFFICE_TYPE_ID=3 and a.OFFICE_STATUS='A' AND A.OFFICE_ID=?";

	    public static final String GET_OFFICE_LIST_DRO="select a.OFFICE_ID,a.OFFICE_NAME,a.H_OFFICE_NAME from IGRS_OFFICE_MASTER a where a.OFFICE_TYPE_ID=3 and a.OFFICE_STATUS='A' AND A.PARENT_ID=?";

	    public static final String GET_OFFICE_LIST_DIG="select a.OFFICE_ID,a.OFFICE_NAME,a.H_OFFICE_NAME from IGRS_OFFICE_MASTER a where a.OFFICE_TYPE_ID=3 and a.OFFICE_STATUS='A' AND A.PARENT_ID IN(SELECT OFFICE_ID FROM IGRS_OFFICE_MASTER WHERE PARENT_ID=?)";

	    public static final String GET_PARA_TYPE_LIST="SELECT PARA_TYPE_ID,PARA_TYPE_NAME FROM IGRS_AUDIT_PARA_TYPE_MASTER WHERE PARA_TYPE_ID IN('P01','P02','P03')";

	    public static final String GET_PARA_STATUS_LIST="SELECT PARA_STATUS_ID,PARA_STATUS_NAME FROM IGRS_AUDIT_PARA_STATUS_MASTER ORDER BY PARA_STATUS_ID ASC";

	    public static final String GET_AGMP_REPORT_SEARCH_LIST="SELECT DISTINCT S.TRANSACTION_ID,S.AUDIT_DATE,S.ENTRY_DATE, S.AUDIT_REPORT_STATUS "+
	    														"FROM IGRS_RAUDIT_TXN_DETAILS S, IGRS_OFFICE_MASTER T, IGRS_RAUDIT_PARA_DETAILS U, "+
	    														"IGRS_RAUDIT_PARA_MAPPING V ,IGRS_AUDIT_PARA_TYPE_MASTER W WHERE "+
	    														"S.TRANSACTION_ID=V.AUDIT_TXN_ID AND V.PARA_TXN_ID=U.PARA_TXN_ID  "+
	    														/*"AND U.PARA_TYPE_ID=(SELECT PARA_TYPE_NAME FROM  IGRS_AUDIT_PARA_TYPE_MASTER "+
	    														"WHERE PARA_TYPE_ID=?)*/ /*" AND S.DRS_OFFICE_ID=? AND U.PARA_STATUS= "+
	    														"(SELECT PARA_STATUS_NAME FROM IGRS_AUDIT_PARA_STATUS_MASTER WHERE "+
	    														"PARA_STATUS_ID=?  ) AND S.AUDIT_REPORT_STATUS=? " +*/
	    														"AND S.DRS_OFFICE_ID=? AND S.AUDIT_BODY_TYPE='AGMP'" +
	    														" AND TRUNC(S.AUDIT_DATE) BETWEEN TO_DATE(?,'dd/mm/yyyy')AND TO_DATE(?,'dd/mm/yyyy')";

	    public static final String GET_AGMP_SEARCH_RESULT="SELECT AUDIT_DATE,ENTRY_DATE,AUDIT_REPORT_STATUS,AUDIT_BODY_TYPE,COMPLIANCE_FLAG,SR_COMPLIANCE,DR_COMPLIANCE,DIG_COMPLIANCE,IG_COMPLIANCE FROM IGRS_RAUDIT_TXN_DETAILS WHERE TRANSACTION_ID=?";

	    public static final String GET_AGMP_SEARCH_PARA_RESULT=" SELECT A.PARA_NAME,A.PARA_COMMENTS,A.PARA_STATUS,A.PARA_NUMBER,A.PARA_TXN_ID FROM IGRS_RAUDIT_PARA_DETAILS A,IGRS_RAUDIT_PARA_MAPPING B WHERE A.PARA_TXN_ID=B.PARA_TXN_ID  AND B.AUDIT_TXN_ID=?";

	    public static final String GET_INTERNAL_REPORT_SEARCH_LIST="SELECT DISTINCT S.TRANSACTION_ID,S.AUDIT_DATE,S.ENTRY_DATE, S.AUDIT_REPORT_STATUS "+
	    														"FROM IGRS_RAUDIT_TXN_DETAILS S, IGRS_OFFICE_MASTER T, IGRS_RAUDIT_PARA_DETAILS U, "+
	    														"IGRS_RAUDIT_PARA_MAPPING V ,IGRS_AUDIT_PARA_TYPE_MASTER W WHERE "+
	    														"S.TRANSACTION_ID=V.AUDIT_TXN_ID AND V.PARA_TXN_ID=U.PARA_TXN_ID  "+
	    														//"AND U.PARA_TYPE_ID=(SELECT PARA_TYPE_NAME FROM  IGRS_AUDIT_PARA_TYPE_MASTER "+
	    														//"WHERE PARA_TYPE_ID=?) 
	    														
	    														/*" AND U.PARA_STATUS= "+
	    														"(SELECT PARA_STATUS_NAME FROM IGRS_AUDIT_PARA_STATUS_MASTER WHERE "+
	    														"PARA_STATUS_ID=?  ) AND S.AUDIT_REPORT_STATUS=? " +*/
	    														" AND S.DRS_OFFICE_ID=? AND S.AUDIT_BODY_TYPE='INTERNAL'" +
	    														" AND TRUNC(S.AUDIT_DATE) BETWEEN TO_DATE(?,'dd/mm/yyyy')AND TO_DATE(?,'dd/mm/yyyy')";
	    
public static final String GETPARADTLS="select irpd.PARA_TXN_ID,irpd.PARA_TYPE_ID,irpd.PARA_NAME,irpd.PARA_COMMENTS,irpd.PARA_STATUS,irpd.PARA_NUMBER,"
+" irpm.AUDIT_TXN_ID,irpm.PARA_TXN_ID,irpom.OBJECTION_TXN_ID ,irpod.DOCUMENT_ID,irpod.OBJECTION_DATE,irpod.OBJECTION_DETAILS,"
+" irpod.DEFICIENT_REG_FEE,irpod.DEFICIENT_STAMP_DUTY,irpod.VALUATION_AT_REG_TIME,irpod.VALUATION_FROM_AGMP,irpod.CASE_TXN_ID"
+" FROM IGRS_RAUDIT_PARA_DETAILS irpd,IGRS_RAUDIT_PARA_MAPPING irpm,IGRS_RAUDIT_PARA_OBJ_MAPPING irpom,"
+" IGRS_RAUDIT_PARA_OBJ_DETAILS irpod WHERE irpd.PARA_TXN_ID=irpm.PARA_TXN_ID and irpd.PARA_TXN_ID=irpom.PARA_TXN_ID" 
+" and irpom.OBJECTION_TXN_ID=irpod.OBJECTION_TXN_ID and irpd.PARA_TXN_ID=?";

public static final String GETPARADTLS1="select irpd.PARA_TXN_ID,irpd.PARA_TYPE_ID,irpd.PARA_NAME,irpd.PARA_COMMENTS,irpd.PARA_STATUS,irpd.PARA_NUMBER,"
+" irpm.AUDIT_TXN_ID,irpm.PARA_TXN_ID,irpom.OBJECTION_TXN_ID ,irpod.DOCUMENT_ID,irpod.OBJECTION_DATE,irpod.OBJECTION_DETAILS,"
+"irpod.DEFICIENT_REG_FEE,irpod.DEFICIENT_STAMP_DUTY,irpod.VALUATION_AT_REG_TIME,irpod.VALUATION_FROM_AGMP,irpod.CASE_TXN_ID"
+" FROM IGRS_RAUDIT_PARA_DETAILS irpd,IGRS_RAUDIT_PARA_MAPPING irpm,IGRS_RAUDIT_PARA_OBJ_MAPPING irpom,"
 +"IGRS_RAUDIT_PARA_OBJ_DETAILS irpod WHERE irpd.PARA_TXN_ID=irpm.PARA_TXN_ID and irpd.PARA_TXN_ID=irpom.PARA_TXN_ID"
 +" and irpom.OBJECTION_TXN_ID=irpod.OBJECTION_TXN_ID and irpom.OBJECTION_TXN_ID=?";

public static final String GETPARASTATUSLIST="select para_status_name,para_status_id from igrs_audit_para_status_master where" 
+" order_id >=(select order_id+1 from igrs_audit_para_status_master where para_status_name=?)";

public static final String GETPARASTATUSLISTWHENCLOSE="select para_status_name,para_status_id from igrs_audit_para_status_master where para_status_id='6'";

public static final String UPDATEPARADETAILS="UPDATE IGRS_RAUDIT_PARA_DETAILS SET PARA_STATUS=?,PARA_COMMENTS=? WHERE PARA_TXN_ID=?";

//added by shruti-after audit points closure
public static final String GETCOMMENTID="SELECT 'CMT'||LPAD(IGRS_RAUDIT_COMMENT_DTL_SEQ.NEXTVAL,4,0) FROM DUAL";
public static final String GETOBJECTIONID="SELECT 'POBJ'||LPAD(IGRS_RAUDIT_PARA_OBJ_DTL_SEQ.NEXTVAL,4,0) FROM DUAL";
public static final String GETDOCUMENTTXNID="SELECT 'DOC'||LPAD(IGRS_RAUDIT_DOC_DTL_SEQ.NEXTVAL,4,0) FROM DUAL";
public static final String GETPARAID="SELECT 'PTXN'||LPAD(IGRS_RAUDIT_PARA_OBJ_DTL_SEQ.NEXTVAL,4,0) FROM DUAL";
public static final String GETDISTRICT="select A.DISTRICT_ID from IGRS_OFFICE_MASTER A,IGRS_EMP_OFFICE_MAPPING B where B.OFFICE_ID=A.OFFICE_ID and B.EMP_ID=?";

public static final String GETSRO="SELECT iom.office_id,iom.office_name FROM igrs_office_master iom,"
	+ "igrs_emp_office_mapping ieom WHERE iom.office_id=ieom.office_id"
	+ " AND ieom.emp_id=?";

public static final String GETOFFICEDISTRICT="Select idm.DISTRICT_ID, idm.DISTRICT_NAME from IGRS_DISTRICT_MASTER idm,IGRS_OFFICE_MASTER iom " +
"where idm.DISTRICT_ID=iom.DISTRICT_ID and iom.OFFICE_ID=?";
public static final String GETOFFICEDISTRICT_HI="Select idm.DISTRICT_ID, idm.H_DISTRICT_NAME from IGRS_DISTRICT_MASTER idm,IGRS_OFFICE_MASTER iom " +
"where idm.DISTRICT_ID=iom.DISTRICT_ID and iom.OFFICE_ID=?";

public static final String GETOBJECTIONDETAILS="select IRPOB.OBJECTION_TXN_ID,IRPOB.DOCUMENT_ID,IRPOB.OBJECTION_STATUS,IRPOB.CASE_TXN_ID FROM IGRS_RAUDIT_PARA_OBJ_DETAILS IRPOB, IGRS_RAUDIT_PARA_OBJ_MAPPING IRPOM"
+" WHERE IRPOB.OBJECTION_TXN_ID=IRPOM.OBJECTION_TXN_ID AND IRPOM.PARA_TXN_ID=?";

public static final String GETOBJECTIONPARADETAILS="select OBJECTION_DETAILS,OBJECTION_STATUS,DOCUMENT_ID,VALUATION_AT_REG_TIME,VALUATION_FROM_AGMP,DEFICIENT_STAMP_DUTY,"
+"DEFICIENT_REG_FEE,CASE_TXN_ID,to_char(CREATED_DATE,'dd/mm/yyyy') from IGRS_RAUDIT_PARA_OBJ_DETAILS where OBJECTION_TXN_ID=?";

public static final String UPDATEOBJPARADETAILS="UPDATE IGRS_RAUDIT_PARA_OBJ_DETAILS SET OBJECTION_STATUS=?,FINAL_COMMENTS=? WHERE OBJECTION_TXN_ID=?";

public static final String GETJURISDICTIONSRO="SELECT OFFICE_ID,OFFICE_NAME FROM IGRS_OFFICE_MASTER WHERE OFFICE_TYPE_ID=3 AND PARENT_ID=?";

public static final String GETJURISDICTIONSRO_HI="SELECT OFFICE_ID,H_OFFICE_NAME FROM IGRS_OFFICE_MASTER WHERE OFFICE_TYPE_ID=3 AND PARENT_ID=?";

public static final String GETOFFICENAME_H="SELECT iom.h_office_name FROM igrs_office_master iom"
	+" where iom.office_id=?";
public static final String GETOFFICETYPEID="SELECT OFFICE_TYPE_ID FROM IGRS_OFFICE_MASTER WHERE OFFICE_ID=?";

//added by shruti
public static final String RETRIEVE_VIEW_DRO_NAMES=
	"select OFFICE_ID,OFFICE_NAME from IGRS_OFFICE_MASTER where OFFICE_TYPE_ID=(select distinct OFFICE_TYPE_ID from IGRS_OFFICE_TYPE_MASTER where OFFICE_TYPE_NAME='DRO')";

public static final String RETRIEVE_VIEW_DRO_NAMES_H=
	"select OFFICE_ID,H_OFFICE_NAME from IGRS_OFFICE_MASTER where OFFICE_TYPE_ID=(select distinct OFFICE_TYPE_ID from IGRS_OFFICE_TYPE_MASTER where OFFICE_TYPE_NAME='DRO')";

//ADDED BY SHRUTI---
public static final String GETALLSRO="SELECT OFFICE_ID,OFFICE_NAME FROM IGRS_OFFICE_MASTER WHERE OFFICE_TYPE_ID=3";

public static final String GETALLSRO_HI="SELECT OFFICE_ID,H_OFFICE_NAME FROM IGRS_OFFICE_MASTER WHERE OFFICE_TYPE_ID=3";

public static final String GETLOGGEDINSRO="SELECT OFFICE_ID,OFFICE_NAME FROM IGRS_OFFICE_MASTER WHERE OFFICE_TYPE_ID=3 and OFFICE_ID=?";

public static final String GETLOGGEDINSRO_H="SELECT OFFICE_ID,H_OFFICE_NAME FROM IGRS_OFFICE_MASTER WHERE OFFICE_TYPE_ID=3 and OFFICE_ID=?";


public static final String GETSROFORDIG="SELECT OFFICE_ID,OFFICE_NAME FROM IGRS_OFFICE_MASTER WHERE OFFICE_TYPE_ID=3 and PARENT_ID in(select OFFICE_ID from IGRS_OFFICE_MASTER where PARENT_ID=?)";

public static final String GETSROFORDIG_H="SELECT OFFICE_ID,H_OFFICE_NAME FROM IGRS_OFFICE_MASTER WHERE OFFICE_TYPE_ID=3 and PARENT_ID in(select OFFICE_ID from IGRS_OFFICE_MASTER where PARENT_ID=?)";

public static final String GETLOGGEDINDRO="SELECT OFFICE_ID,OFFICE_NAME FROM IGRS_OFFICE_MASTER WHERE OFFICE_TYPE_ID=2 and OFFICE_ID=?";

public static final String GETLOGGEDINDRO_H="SELECT OFFICE_ID,H_OFFICE_NAME FROM IGRS_OFFICE_MASTER WHERE OFFICE_TYPE_ID=2 and OFFICE_ID=?";

public static final String GETOBJECTIONDETAILS_VIEW="select IRPOB.OBJECTION_TXN_ID,IRPOB.OBJECTION_DETAILS,IRPOB.OBJECTION_STATUS,TO_CHAR(OBJECTION_DATE,'dd/mm/yyyy'),IRPOB.DOCUMENT_ID,IRPOB.VALUATION_AT_REG_TIME,IRPOB.VALUATION_FROM_AGMP,IRPOB.DEFICIENT_STAMP_DUTY,IRPOB.DEFICIENT_REG_FEE,IRPOB.CASE_TXN_ID FROM IGRS_RAUDIT_PARA_OBJ_DETAILS IRPOB, IGRS_RAUDIT_PARA_OBJ_MAPPING IRPOM"
	+" WHERE IRPOB.OBJECTION_TXN_ID=IRPOM.OBJECTION_TXN_ID AND IRPOM.PARA_TXN_ID=?";

// ADDED BY SIMRAN FOR STATUS OF REPORT,PARA AND oBJECTION

public static final String GET_PARA_STATUS = "SELECT PARA_STATUS FROM IGRS_RAUDIT_PARA_DETAILS PARA, IGRS_RAUDIT_PARA_MAPPING MAP WHERE" +
		" map.audit_txn_id = ? " +
		"AND MAP.PARA_TXN_ID = PARA.PARA_TXN_ID";

public static final String GET_OBJECTION_STATUS = "SELECT OBJECTION_STATUS FROM IGRS_RAUDIT_PARA_OBJ_DETAILS PARA, IGRS_RAUDIT_PARA_OBJ_MAPPING MAP " +
		"WHERE map.PARA_TXN_ID = ? AND MAP.OBJECTION_TXN_ID = PARA.OBJECTION_TXN_ID";

}
