package com.wipro.igrs.empfund.sql;

public class EmpFundCommonSQL {

	public static final String GET_ALL_FUND_TYPES = "SELECT FUND_TYPE_ID, FUND_NAME" +
			" FROM IGRS_EMP_FUND_TYPE_MASTER " +
			" WHERE FUND_STATUS = 'A'";
	
	
	final public static  String EDIT_EMP_FUND = "UPDATE IGRS_EMP_FUND_DETAILS SET FUND_AMOUNT = ? WHERE EMP_ID = ? and FUND_TYPE_ID = ?";
	
	final public static String GET_EMP_FUND = "SELECT IGRS_EMP_FUND_DETAILS.FUND_ACCOUNT_NO ,IGRS_EMP_FUND_DETAILS.FUND_LOCATION,IGRS_EXP_DETAILED_HEAD_MASTER.DETAILED_HEAD_NAME_E,FUND_AMOUNT,FIRST_NAME||' '||MIDDLE_NAME||' '||LAST_NAME,NOMINEE_NAME,NOMINEE_RELATIONSHIP,NOMINEE_ADDRESS,NOMINEE_AGE,NOMINEE_SHARE_PCT FROM IGRS_EMP_FUND_DETAILS join IGRS_EMP_FUND_NOMINEE_DETAILS on IGRS_EMP_FUND_DETAILS.FUND_ACCOUNT_NO = IGRS_EMP_FUND_NOMINEE_DETAILS.FUND_ACCOUNT_NO join IGRS_EXP_DETAILED_HEAD_MASTER on IGRS_EMP_FUND_NOMINEE_DETAILS.COMPONENT_ID = IGRS_EXP_DETAILED_HEAD_MASTER.DETAILED_HEAD_ID join IGRS_EMP_MASTER on IGRS_EMP_FUND_DETAILS.EMP_ID = IGRS_EMP_MASTER.EMP_ID WHERE IGRS_EMP_FUND_DETAILS.EMP_ID = ? and IGRS_EMP_FUND_DETAILS.FUND_TYPE_ID = ? ";

	final public static String GET_EMP_BASIC_SALARY = "SELECT COMPONENT_VALUE FROM IGRS_EMP_SALARY_BASIC_DTLS join IGRS_EMP_FUND_DETAILS on IGRS_EMP_SALARY_BASIC_DTLS.EMP_ID = IGRS_EMP_FUND_DETAILS.EMP_ID  WHERE IGRS_EMP_FUND_DETAILS.EMP_ID = ? and IGRS_EMP_FUND_DETAILS.FUND_TYPE_ID = ?";
	
	final public static String GET_FUND_TYPE = "SELECT FUND_TYPE_ID, FUND_NAME " +
			" FROM IGRS_EMP_FUND_TYPE_MASTER " +
			" WHERE FUND_TYPE_ID = ?";
	
}
