package com.wipro.igrs.commonEfiling.sql;

public class CommonSQL {

	public static final String GET_PLOT_EN_VIEW_DETAILS = "SELECT DISTINCT D.DISTRICT_NAME,T.TEHSIL_NAME,A.AREA_TYPE_NAME,SA.SUB_AREA_TYPE_NAME, "+
		 										  " WP.WARD_PATWARI_NAME,C.COLONY_NAME,P.TOTAL_AREA,P.RESIDENTIAL_AREA,P.COMMERCIAL_AREA,P.INDUSTRIAL_AREA,P.EDUCATION_AREA,P.HEALTH_AREA,P.OTHER_AREA,P.EDUCATION_TCP,P.HEALTH_TCP, M.AREA_TYPE_ID,P.RESICUMM_FLAG,P.RESICUMM_AREA "+
		 										  " FROM IGRS_PROP_VAL_TXN_DETLS M,IGRS_PROP_PLOT_DETLS P,IGRS_DISTRICT_MASTER D,IGRS_TEHSIL_MASTER T,IGRS_AREA_TYPE_MASTER A,IGRS_SUB_AREA_TYPE_MASTER SA,IGRS_WARD_PATWARI_MASTER WP,IGRS_COLONY_MASTER C "+
		 										  " WHERE D.DISTRICT_ID =M.DIST_ID AND T.TEHSIL_ID=M.TEHSIL_ID  AND P.VAL_TXN_ID = M.VAL_TXN_ID AND A.AREA_TYPE_ID = M.AREA_TYPE_ID AND SA.SUB_AREA_TYPE_ID = M.SUB_AREA_TYPE_ID AND WP.WARD_PATWARI_ID = M.WARD_PATWARI_ID AND C.COLONY_ID = M.COLONY_ID AND P.VAL_TXN_ID=?";

	
	public static final String GET_PLOT_HI_VIEW_DETAILS ="SELECT DISTINCT D.H_DISTRICT_NAME,T.H_TEHSIL_NAME,A.H_AREA_TYPE_NAME,SA.H_SUB_AREA_TYPE_NAME,WP.H_WARD_PATWARI_NAME,C.H_COLONY_NAME,P.TOTAL_AREA,P.RESIDENTIAL_AREA,P.COMMERCIAL_AREA,P.INDUSTRIAL_AREA,P.EDUCATION_AREA,P.HEALTH_AREA,P.OTHER_AREA,P.EDUCATION_TCP,P.HEALTH_TCP,M.AREA_TYPE_ID,P.RESICUMM_FLAG,P.RESICUMM_AREA "+
														 "FROM IGRS_PROP_VAL_TXN_DETLS M,IGRS_PROP_PLOT_DETLS P,IGRS_DISTRICT_MASTER D,IGRS_TEHSIL_MASTER T,IGRS_AREA_TYPE_MASTER A,IGRS_SUB_AREA_TYPE_MASTER SA,IGRS_WARD_PATWARI_MASTER WP,IGRS_COLONY_MASTER C "+
														 "WHERE D.DISTRICT_ID=M.DIST_ID AND T.TEHSIL_ID=M.TEHSIL_ID AND P.VAL_TXN_ID = M.VAL_TXN_ID AND A.AREA_TYPE_ID= M.AREA_TYPE_ID AND SA.SUB_AREA_TYPE_ID = M.SUB_AREA_TYPE_ID AND WP.WARD_PATWARI_ID  = M.WARD_PATWARI_ID AND C.COLONY_ID= M.COLONY_ID AND P.VAL_TXN_ID = ?";
	
	
	public static final String GET_EN_SUB_CLAUSES_LIST="SELECT m.SUB_CLAUSE_NAME,sm.SUB_CLAUSE_ID FROM igrs_sub_clause_master m ,igrs_prop_subclause_map sm WHERE sm.SUB_CLAUSE_ID=m.sub_clause_id AND sm.VAL_TXN_ID=?";
	
	
	public static final String GET_HI_SUB_CLAUSES_LIST="SELECT m.H_SUB_CLAUSE_DESC,sm.SUB_CLAUSE_ID FROM igrs_sub_clause_master m ,igrs_prop_subclause_map sm WHERE sm.SUB_CLAUSE_ID=m.sub_clause_id AND sm.VAL_TXN_ID=?";
	
	
	public static final String GET_AGRI_EN_VIEW_AREA_DETAILS ="SELECT DISTINCT D.DISTRICT_NAME,T.TEHSIL_NAME,A.AREA_TYPE_NAME,SA.SUB_AREA_TYPE_NAME,WP.WARD_PATWARI_NAME,C.COLONY_NAME,M.SINGLE_BUYER,M.SAME_FAMILY,M.BUYER_COUNT,M.TREE_PRESENT,M.DISCLOSE_SHARE,M.AREA_TYPE_ID "+
														  	" FROM IGRS_PROP_VAL_TXN_DETLS M,IGRS_DISTRICT_MASTER D,IGRS_TEHSIL_MASTER T, "+
														  " IGRS_AREA_TYPE_MASTER A,IGRS_SUB_AREA_TYPE_MASTER SA,IGRS_WARD_PATWARI_MASTER WP,IGRS_COLONY_MASTER C WHERE D.DISTRICT_ID=M.DIST_ID AND T.TEHSIL_ID =M.TEHSIL_ID "+
														  " AND A.AREA_TYPE_ID = M.AREA_TYPE_ID AND SA.SUB_AREA_TYPE_ID = M.SUB_AREA_TYPE_ID AND WP.WARD_PATWARI_ID= M.WARD_PATWARI_ID AND C.COLONY_ID= M.COLONY_ID AND M.VAL_TXN_ID=?";


	public static final String GET_AGRI_HI_VIEW_AREA_DETAILS ="SELECT DISTINCT D.H_DISTRICT_NAME,T.H_TEHSIL_NAME,A.H_AREA_TYPE_NAME,SA.H_SUB_AREA_TYPE_NAME,WP.H_WARD_PATWARI_NAME,C.H_COLONY_NAME,M.SINGLE_BUYER,M.SAME_FAMILY,M.BUYER_COUNT,M.TREE_PRESENT,M.DISCLOSE_SHARE,M.AREA_TYPE_ID "+
															  " FROM IGRS_PROP_VAL_TXN_DETLS M,IGRS_DISTRICT_MASTER D,IGRS_TEHSIL_MASTER T, "+
															  " IGRS_AREA_TYPE_MASTER A,IGRS_SUB_AREA_TYPE_MASTER SA,IGRS_WARD_PATWARI_MASTER WP,IGRS_COLONY_MASTER C WHERE D.DISTRICT_ID=M.DIST_ID AND T.TEHSIL_ID =M.TEHSIL_ID "+
															  " AND A.AREA_TYPE_ID = M.AREA_TYPE_ID AND SA.SUB_AREA_TYPE_ID = M.SUB_AREA_TYPE_ID AND WP.WARD_PATWARI_ID= M.WARD_PATWARI_ID AND C.COLONY_ID= M.COLONY_ID AND M.VAL_TXN_ID=?";


	

	/*public static final String GET_AGRI_EN_VIEW_PROP_DETAILS = "SELECT DISTINCT A.AGRI_TXN_ID,A.AGRI_SUB_TYPE_ID,A.TOTAL_AREA,A.UNIRRIGATED_1_CROP_AREA,A.UNIRRIGATED_2_CROP_AREA,A.IRRIGATED_AREA,A.CONSTRUCTION_DONE, "+
	  															" A.TOTAL_DIVERTED_AREA,A.RESIDENTIAL_AREA,A.COMMERCIAL_AREA,A.INDUSTRIAL_AREA,A.EDUCATION_AREA,A.HEALTH_AREA,A.OTHER_AREA,A.EDUCATION_TCP,A.HEALTH_TCP,SB.PROP_SUB_TYPE_NAME,B.FLOOR_AREA, "+
	  															" B.PROP_AT_FLOOR,B.PROP_OLD_20,B.PROP_OLD_50,B.LIFT_PRESENT,B.TRANSACT_OPEN_TERRACE,B.TERRACE_USAGE,B.TERRACE_AREA,B.MULTISTOREY_SUB_TYPE,B.TOTAL_AREA,B.BUILD_UP_AREA,B.COMMON_AREA, "+
	  															" B.COMMERCIAL_PROP_TYPE,B.PROP_IN_MALL, B.PROP_NEAR_ROAD,B.RESIDENTIAL_AREA,B.COMMERCIAL_AREA,B.INDUSTRIAL_AREA,B.EDUCATION_AREA,B.HEALTH_AREA,B.OTHER_AREA,B.EDUCATION_TCP,B.HEALTH_TCP,B.AGRI_TXN_ID "+
	  															" FROM IGRS_PROP_AGRI_DETLS A,IGRS_PROP_BUILDING_DETLS B,IGRS_PROP_SUB_TYPE_MASTER SB WHERE A.AGRI_TXN_ID=B.AGRI_TXN_ID AND B.BUILDING_SUB_TYPE_ID=SB.PROP_SUB_TYPE_ID AND A.VAL_TXN_ID=?";

*/




	public static final String GET_BUILDING_VIEW_DETAILS= "SELECT DISTINCT D.DISTRICT_NAME,T.TEHSIL_NAME,A.AREA_TYPE_NAME,SA.SUB_AREA_TYPE_NAME, "+
	  														" WP.WARD_PATWARI_NAME,C.COLONY_NAME,B.BUILDING_TXN_ID,B.BUILDING_SUB_TYPE_ID,B.FLOOR_AREA,F.FLOOR_NAME,B.PROP_OLD_20,B.PROP_OLD_50,B.LIFT_PRESENT,"+
	  														" B.TRANSACT_OPEN_TERRACE,(SELECT PROP_TYPE_L1_NAME FROM IGRS_PROP_TYPE_L1_MASTER_DUMMY WHERE PROP_TYPE_L1_ID=B.TERRACE_USAGE),B.TERRACE_AREA,"+
	  														" (SELECT PROP_TYPE_L1_NAME FROM IGRS_PROP_TYPE_L1_MASTER_DUMMY WHERE PROP_TYPE_L1_ID=B.MULTISTOREY_SUB_TYPE),B.TOTAL_AREA,"+
	  														" B.BUILD_UP_AREA,B.COMMON_AREA,(SELECT PROPERTY_TYPE_L2_NAME FROM IGRS_PROP_TYPE_L2_MASTER_DUMMY WHERE PROPERTY_TYPE_L2_ID=B.COMMERCIAL_PROP_TYPE)"+
	  														",B.PROP_IN_MALL,B.PROP_NEAR_ROAD,B.RESIDENTIAL_AREA,B.COMMERCIAL_AREA,B.INDUSTRIAL_AREA,B.EDUCATION_AREA,B.HEALTH_AREA,B.OTHER_AREA,B.EDUCATION_TCP,B.HEALTH_TCP,B.IS_CONSTRUCTION,B.IS_AKVN,B.IS_HOUSING_BOARD,B.MULTISTOREY_SUB_TYPE,B.RESI_COMM_AREA"+
	  														" FROM IGRS_PROP_BUILDING_DETLS B,IGRS_FLOOR_MASTER F,IGRS_DISTRICT_MASTER D,IGRS_PROP_VAL_TXN_DETLS M,IGRS_TEHSIL_MASTER T,IGRS_AREA_TYPE_MASTER A,IGRS_SUB_AREA_TYPE_MASTER SA,IGRS_WARD_PATWARI_MASTER WP,IGRS_COLONY_MASTER C "+
	  														" WHERE D.DISTRICT_ID =M.DIST_ID AND T.TEHSIL_ID=M.TEHSIL_ID  AND B.VAL_TXN_ID = M.VAL_TXN_ID AND A.AREA_TYPE_ID = M.AREA_TYPE_ID AND SA.SUB_AREA_TYPE_ID = M.SUB_AREA_TYPE_ID AND WP.WARD_PATWARI_ID = M.WARD_PATWARI_ID AND C.COLONY_ID = M.COLONY_ID AND F.FLOOR_ID = NVL(B.PROP_AT_FLOOR,3) AND B.VAL_TXN_ID=?";
	
	
	public static final String GET_BUILDING_VIEW_DETAILS_HINDI= "SELECT DISTINCT D.H_DISTRICT_NAME,T.H_TEHSIL_NAME,A.H_AREA_TYPE_NAME,SA.H_SUB_AREA_TYPE_NAME, "+
		" WP.H_WARD_PATWARI_NAME,C.H_COLONY_NAME,B.BUILDING_TXN_ID,B.BUILDING_SUB_TYPE_ID,B.FLOOR_AREA,F.H_FLOOR_NAME,B.PROP_OLD_20,B.PROP_OLD_50,B.LIFT_PRESENT,"+
		" B.TRANSACT_OPEN_TERRACE,(SELECT H_PROP_TYPE_L1_NAME FROM IGRS_PROP_TYPE_L1_MASTER_DUMMY WHERE PROP_TYPE_L1_ID=B.TERRACE_USAGE),B.TERRACE_AREA,"+
		"(SELECT H_PROP_TYPE_L1_NAME FROM IGRS_PROP_TYPE_L1_MASTER_DUMMY WHERE PROP_TYPE_L1_ID=B.MULTISTOREY_SUB_TYPE),B.TOTAL_AREA,"+
		" B.BUILD_UP_AREA,B.COMMON_AREA,(SELECT H_PROPERTY_TYPE_L2_NAME FROM IGRS_PROP_TYPE_L2_MASTER_DUMMY WHERE PROPERTY_TYPE_L2_ID=B.COMMERCIAL_PROP_TYPE)"+
		",B.PROP_IN_MALL,B.PROP_NEAR_ROAD,B.RESIDENTIAL_AREA,B.COMMERCIAL_AREA,B.INDUSTRIAL_AREA,B.EDUCATION_AREA,B.HEALTH_AREA,B.OTHER_AREA,B.EDUCATION_TCP,B.HEALTH_TCP,B.IS_CONSTRUCTION,B.IS_AKVN,B.IS_HOUSING_BOARD,B.MULTISTOREY_SUB_TYPE,B.RESI_COMM_AREA"+
		" FROM IGRS_PROP_BUILDING_DETLS B,IGRS_FLOOR_MASTER F,IGRS_DISTRICT_MASTER D,IGRS_PROP_VAL_TXN_DETLS M,IGRS_TEHSIL_MASTER T,IGRS_AREA_TYPE_MASTER A,IGRS_SUB_AREA_TYPE_MASTER SA,IGRS_WARD_PATWARI_MASTER WP,IGRS_COLONY_MASTER C "+
		" WHERE D.DISTRICT_ID =M.DIST_ID AND T.TEHSIL_ID=M.TEHSIL_ID  AND B.VAL_TXN_ID = M.VAL_TXN_ID AND A.AREA_TYPE_ID = M.AREA_TYPE_ID AND SA.SUB_AREA_TYPE_ID = M.SUB_AREA_TYPE_ID AND WP.WARD_PATWARI_ID = M.WARD_PATWARI_ID AND C.COLONY_ID = M.COLONY_ID  AND F.FLOOR_ID = NVL(B.PROP_AT_FLOOR,3) AND B.VAL_TXN_ID=?";




	  
	public static final String GET_PROP_TYPE_ID ="SELECT PROP_TYPE_ID FROM IGRS_PROP_VAL_TXN_DETLS WHERE VAL_TXN_ID=?";
	
	
	public static final String GET_EN_AGRI_TREE_DETAILS ="SELECT M.TREE_NAME,TREE_COUNT FROM IGRS_AGRI_TREE_MAP T,IGRS_TREE_MASTER M WHERE T.TREE_ID=m.tree_id AND VAL_TXN_ID=?";
	
	
	
	public static final String GET_HI_AGRI_TREE_DETAILS ="SELECT M.H_TREE_NAME,TREE_COUNT FROM IGRS_AGRI_TREE_MAP T,IGRS_TREE_MASTER M WHERE T.TREE_ID=m.tree_id AND VAL_TXN_ID=?";
	
	
	
	public static final String GET_AGRI_HI_VIEW_PROP_DETAILS="SELECT A.AGRI_TXN_ID,A.AGRI_SUB_TYPE_ID,SB.H_PROP_SUB_TYPE_NAME,A.TOTAL_AREA,A.UNIRRIGATED_1_CROP_AREA, "+
	 														" A.UNIRRIGATED_2_CROP_AREA,A.IRRIGATED_AREA,A.CONSTRUCTION_DONE,A.TOTAL_DIVERTED_AREA,A.RESIDENTIAL_AREA,A.COMMERCIAL_AREA,A.INDUSTRIAL_AREA,A.EDUCATION_AREA,A.HEALTH_AREA,A.OTHER_AREA,A.EDUCATION_TCP,A.HEALTH_TCP "+
	 														" FROM IGRS_PROP_AGRI_DETLS A,IGRS_PROP_SUB_TYPE_MASTER SB WHERE A.AGRI_SUB_TYPE_ID=SB.PROP_SUB_TYPE_ID AND A.VAL_TXN_ID=?";
	
	public static final String GET_AGRI_EN_VIEW_PROP_DETAILS="SELECT A.AGRI_TXN_ID,A.AGRI_SUB_TYPE_ID,SB.PROP_SUB_TYPE_NAME,A.TOTAL_AREA,A.UNIRRIGATED_1_CROP_AREA, "+
															 " A.UNIRRIGATED_2_CROP_AREA,A.IRRIGATED_AREA,A.CONSTRUCTION_DONE,A.TOTAL_DIVERTED_AREA,A.RESIDENTIAL_AREA,A.COMMERCIAL_AREA,A.INDUSTRIAL_AREA,A.EDUCATION_AREA,A.HEALTH_AREA,A.OTHER_AREA,A.EDUCATION_TCP,A.HEALTH_TCP "+
															 " FROM IGRS_PROP_AGRI_DETLS A,IGRS_PROP_SUB_TYPE_MASTER SB WHERE A.AGRI_SUB_TYPE_ID=SB.PROP_SUB_TYPE_ID AND A.VAL_TXN_ID=?";

	public static final String GET_BUILDING_VIEW_DETAILS_AGRI= "SELECT DISTINCT D.DISTRICT_NAME,T.TEHSIL_NAME,A.AREA_TYPE_NAME,SA.SUB_AREA_TYPE_NAME, "+
		" WP.WARD_PATWARI_NAME,C.COLONY_NAME,B.BUILDING_TXN_ID,B.BUILDING_SUB_TYPE_ID,B.FLOOR_AREA,F.FLOOR_NAME,B.PROP_OLD_20,B.PROP_OLD_50,B.LIFT_PRESENT,"+
		" B.TRANSACT_OPEN_TERRACE,(SELECT PROP_TYPE_L1_NAME FROM IGRS_PROP_TYPE_L1_MASTER_DUMMY WHERE PROP_TYPE_L1_ID=B.TERRACE_USAGE),B.TERRACE_AREA,"+
		"(SELECT PROP_TYPE_L1_NAME FROM IGRS_PROP_TYPE_L1_MASTER_DUMMY WHERE PROP_TYPE_L1_ID=B.MULTISTOREY_SUB_TYPE),B.TOTAL_AREA,"+
		" B.BUILD_UP_AREA,B.COMMON_AREA,(SELECT PROPERTY_TYPE_L2_NAME FROM IGRS_PROP_TYPE_L2_MASTER_DUMMY WHERE PROPERTY_TYPE_L2_ID=B.COMMERCIAL_PROP_TYPE)"+
		",B.PROP_IN_MALL,B.PROP_NEAR_ROAD,B.RESIDENTIAL_AREA,B.COMMERCIAL_AREA,B.INDUSTRIAL_AREA,B.EDUCATION_AREA,B.HEALTH_AREA,B.OTHER_AREA,B.EDUCATION_TCP,B.HEALTH_TCP,B.IS_CONSTRUCTION,B.IS_AKVN,B.IS_HOUSING_BOARD,B.MULTISTOREY_SUB_TYPE,B.RESI_COMM_AREA"+
		" FROM IGRS_PROP_BUILDING_DETLS B,IGRS_FLOOR_MASTER F,IGRS_DISTRICT_MASTER D,IGRS_PROP_VAL_TXN_DETLS M,IGRS_TEHSIL_MASTER T,IGRS_AREA_TYPE_MASTER A,IGRS_SUB_AREA_TYPE_MASTER SA,IGRS_WARD_PATWARI_MASTER WP,IGRS_COLONY_MASTER C "+
		" WHERE D.DISTRICT_ID =M.DIST_ID AND T.TEHSIL_ID=M.TEHSIL_ID  AND B.VAL_TXN_ID = M.VAL_TXN_ID AND A.AREA_TYPE_ID = M.AREA_TYPE_ID AND SA.SUB_AREA_TYPE_ID = M.SUB_AREA_TYPE_ID AND WP.WARD_PATWARI_ID = M.WARD_PATWARI_ID AND C.COLONY_ID = M.COLONY_ID AND  F.FLOOR_ID = NVL(B.PROP_AT_FLOOR,3) AND B.AGRI_TXN_ID=?";
	
	public static final String GET_BUILDING_VIEW_DETAILS_AGRI_HINDI= "SELECT DISTINCT D.H_DISTRICT_NAME,T.H_TEHSIL_NAME,A.H_AREA_TYPE_NAME,SA.H_SUB_AREA_TYPE_NAME, "+
	" WP.H_WARD_PATWARI_NAME,C.H_COLONY_NAME,B.BUILDING_TXN_ID,B.BUILDING_SUB_TYPE_ID,B.FLOOR_AREA,F.H_FLOOR_NAME,B.PROP_OLD_20,B.PROP_OLD_50,B.LIFT_PRESENT,"+
	" B.TRANSACT_OPEN_TERRACE,(SELECT H_PROP_TYPE_L1_NAME FROM IGRS_PROP_TYPE_L1_MASTER_DUMMY WHERE PROP_TYPE_L1_ID=B.TERRACE_USAGE),B.TERRACE_AREA,"+
	"(SELECT H_PROP_TYPE_L1_NAME FROM IGRS_PROP_TYPE_L1_MASTER_DUMMY WHERE PROP_TYPE_L1_ID=B.MULTISTOREY_SUB_TYPE),B.TOTAL_AREA,"+
	" B.BUILD_UP_AREA,B.COMMON_AREA,(SELECT H_PROPERTY_TYPE_L2_NAME FROM IGRS_PROP_TYPE_L2_MASTER_DUMMY WHERE PROPERTY_TYPE_L2_ID=B.COMMERCIAL_PROP_TYPE)"+
	",B.PROP_IN_MALL,B.PROP_NEAR_ROAD,B.RESIDENTIAL_AREA,B.COMMERCIAL_AREA,B.INDUSTRIAL_AREA,B.EDUCATION_AREA,B.HEALTH_AREA,B.OTHER_AREA,B.EDUCATION_TCP,B.HEALTH_TCP,B.IS_CONSTRUCTION,B.IS_AKVN,B.IS_HOUSING_BOARD,B.MULTISTOREY_SUB_TYPE,B.RESI_COMM_AREA"+
	" FROM IGRS_PROP_BUILDING_DETLS B,IGRS_FLOOR_MASTER F,IGRS_DISTRICT_MASTER D,IGRS_PROP_VAL_TXN_DETLS M,IGRS_TEHSIL_MASTER T,IGRS_AREA_TYPE_MASTER A,IGRS_SUB_AREA_TYPE_MASTER SA,IGRS_WARD_PATWARI_MASTER WP,IGRS_COLONY_MASTER C "+
	" WHERE D.DISTRICT_ID =M.DIST_ID AND T.TEHSIL_ID=M.TEHSIL_ID  AND B.VAL_TXN_ID = M.VAL_TXN_ID AND A.AREA_TYPE_ID = M.AREA_TYPE_ID AND SA.SUB_AREA_TYPE_ID = M.SUB_AREA_TYPE_ID AND WP.WARD_PATWARI_ID = M.WARD_PATWARI_ID AND C.COLONY_ID = M.COLONY_ID AND F.FLOOR_ID = NVL(B.PROP_AT_FLOOR,3) AND B.AGRI_TXN_ID=?";

	public static final String GET_BUILDING_FLOOR_DETAILS="SELECT B.SUB_PROP_TYPE_ID,C.FLOOR_NAME, B.RCC_AREA,B.RBC_AREA,B.TIN_AREA,B.KACHA_AREA,B.SHOP_AREA,B.OFFICE_AREA,B.GODOWN_AREA FROM IGRS_FLOOR_AREA_DETLS B,IGRS_FLOOR_TXN_DETLS A,IGRS_FLOOR_MASTER C WHERE A.FLOOR_TXN_ID=B.FLOOR_TXN_ID and A.FLOOR_TYPE_ID=C.FLOOR_ID AND A.building_txn_id=?";

	public static final String GET_BUILDING_FLOOR_DETAILS_HINDI="SELECT B.SUB_PROP_TYPE_ID,C.H_FLOOR_NAME, B.RCC_AREA,B.RBC_AREA,B.TIN_AREA,B.KACHA_AREA,B.SHOP_AREA,B.OFFICE_AREA,B.GODOWN_AREA FROM IGRS_FLOOR_AREA_DETLS B,IGRS_FLOOR_TXN_DETLS A,IGRS_FLOOR_MASTER C WHERE A.FLOOR_TXN_ID=B.FLOOR_TXN_ID and A.FLOOR_TYPE_ID=C.FLOOR_ID AND A.building_txn_id=?";

	public static final String GET_EN_SUB_CLAUSES_LIST_BUILD="SELECT DISTINCT m.SUB_CLAUSE_NAME,sm.SUB_CLAUSE_ID FROM igrs_sub_clause_master m ,igrs_prop_subclause_map sm WHERE sm.SUB_CLAUSE_ID=m.sub_clause_id AND sm.AGRI_TXN_ID=?";
	
	
	public static final String GET_HI_SUB_CLAUSES_LIST_BUILD="SELECT DISTINCT m.H_SUB_CLAUSE_DESC,sm.SUB_CLAUSE_ID FROM igrs_sub_clause_master m ,igrs_prop_subclause_map sm WHERE sm.SUB_CLAUSE_ID=m.sub_clause_id AND sm.AGRI_TXN_ID=?";
	
	

}