package com.wipro.igrs.hrandpayrollform.sql;

public class HrAndPayrollSQL {

	
	 public static final String SELECT_ALL_COUNTRY_MASTER =
	    	"SELECT COUNTRY_ID, COUNTRY_NAME " +
	    	"FROM IGRS_COUNTRY_MASTER";
	 public static final String SELECT_ALL_DISTRICT_MASTER =
	    	"SELECT DISTRICT_ID, DISTRICT_NAME " +
	    	"FROM IGRS_DISTRICT_MASTER";
	 public static final String SELECT_DISTRICT_BY_STATE_ID =
	    	"SELECT DISTRICT_ID, DISTRICT_NAME " +
	    	"FROM IGRS_DISTRICT_MASTER WHERE STATE_ID=?";
	 public static final String SELECT_ALL_STATE_MASTER =
	    	"SELECT STATE_ID, STATE_NAME " +
	    	"FROM IGRS_STATE_MASTER";
	 public static final String SELECT_STATE_BY_COUNTRY_ID =
	    	"SELECT STATE_ID, STATE_NAME " +
	    	"FROM IGRS_STATE_MASTER WHERE COUNTRY_ID=?";
	 public static final String SELECT_ALL_PAYMENT_TYPE_MASTER =
	    	"SELECT PAYMENT_TYPE_ID, PAYMENT_TYPE_NAME " +
	    	"FROM IGRS_PAYMENT_TYPE_MASTER";
	 
	  public static final String INSERT_HR_AND_PAYROLL = 
	        "INSERT INTO IGRS_EMP_RENT_PAID_DTLS (START_DATE, LEASE_PERIOD, LEASE_AMOUNT, PAYMENT_TYPE, PROPERTY_COUNTRY_ID, PROPERTY_STATE_ID, PROPERTY_DISTRICT_ID, PROPDERTY_ADDRESS, PROPERTY_POSTAL_CODE, LAND_LORD_F_NAME, LAND_LORD_M_NAME, LAND_LORD_L_NAME, LAND_LORD_COUNTRY_ID, LAND_LORD_STATE_ID, LAND_LORD_DISTRICT_ID, LAND_LORD_ADDRESS, LAND_POSTAL_CODE, LAND_LORD_GENDER ) " + 
	        "VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";

}
