package com.wipro.igrs.pinverification.sql;
/* Copyright (c) 2006-2008 WIPRO. All Rights Reserved.
 * 
 *  This software is the confidential and proprietary information of WIPRO
 *  ("Confidential Information"). You shall not
 *  disclose such Confidential Information and shall use it only in
 *  accordance with the terms of the license agreement you entered into
 *  with WIPRO.
 *  
 * WIPRO MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE 
 * SUITABILITY OF THE SOFTWARE, EITHER EXPRESS OR IMPLIED, 
 * INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF 
 * MERCHANTABILITY, FITNESS FOR A
 * PARTICULAR PURPOSE, OR NON-INFRINGEMENT. WIPRO SHALL NOT BE 
 * LIABLE FOR ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF 
 * USING, MODIFYING OR DISTRIBUTING THIS SOFTWARE OR ITS 
 * DERIVATIVES.
 * 
 */


/**
 * @author Madan Mohan
 *
 */
public class CommonSQL {

	public static final String PROPERTYDETAILS_QUERY = "SELECT DISTINCT "
		+"IGRS_REG_PROPERTY_DETAILS.PROPERTY_TYPE_ID,"
		+"IGRS_REG_PROPERTY_DETAILS.DISTRICT_ID,"
        +"IGRS_DISTRICT_MASTER.DISTRICT_NAME,"
        +"IGRS_REG_PROPERTY_DETAILS.TEHSIL_ID,"
        +"IGRS_TEHSIL_MASTER.TEHSIL_NAME,"
        +"IGRS_REG_PROPERTY_DETAILS.WARD_PATWARI_ID,"
        +"IGRS_WARD_PATWARI_MASTER.WARD_PATWARI_NAME,"
        +"IGRS_REG_PROPERTY_DETAILS.MOHALLA_VILLAGE_ID,"
        +"IGRS_MOHALLA_VILLAGE_MASTER.MOHALLA_VILLAGE_NAME,"
        +"IGRS_REG_PROPERTY_DETAILS.AREA_TYPE_ID,"
        +"IGRS_AREA_TYPE_MASTER.AREA_TYPE_NAME, "
        +"IGRS_REG_PROPERTY_DETAILS.PROPERTY_ADDRESS,"
        +"IGRS_REG_PROPERTY_DETAILS.SOUTH_BOUNDARY, "
        +"IGRS_REG_PROPERTY_DETAILS.NORTH_BOUNDARY,"
        +"IGRS_REG_PROPERTY_DETAILS.WEST_BOUNDARY, "
        +"IGRS_REG_PROPERTY_DETAILS.EAST_BOUNDARY "
        +" FROM IGRS_REG_COMPLIANCE_DETAILS,"
        +"IGRS_REG_COMPLIANCE_TXN_DTLS,IGRS_REG_TXN_PARTY_DETAILS,"
        +"IGRS_REG_PROPERTY_DETAILS,IGRS_DISTRICT_MASTER,"
        +"IGRS_MOHALLA_VILLAGE_MASTER,IGRS_TEHSIL_MASTER,"
        +"IGRS_WARD_PATWARI_MASTER,IGRS_AREA_TYPE_MASTER "
        +" WHERE (IGRS_REG_COMPLIANCE_DETAILS.COMPLIANCE_ID = "
        +"IGRS_REG_COMPLIANCE_TXN_DTLS.COMPLIANCE_ID) "
        +" AND (IGRS_REG_COMPLIANCE_TXN_DTLS.REG_TXN_ID = "
        +"IGRS_REG_TXN_PARTY_DETAILS.REG_TXN_ID) "
        +" AND (IGRS_REG_PROPERTY_DETAILS.PROPERTY_TXN_ID= "
        +"IGRS_REG_TXN_PARTY_DETAILS.PROPERTY_TXN_ID) "
        +" AND (IGRS_DISTRICT_MASTER.DISTRICT_ID = "
        +" IGRS_REG_PROPERTY_DETAILS.DISTRICT_ID) "
        +" AND (IGRS_MOHALLA_VILLAGE_MASTER.MOHALLA_VILLAGE_ID = "
        +" IGRS_REG_PROPERTY_DETAILS.MOHALLA_VILLAGE_ID) "
        +" AND (IGRS_TEHSIL_MASTER.TEHSIL_ID = "
        +" IGRS_REG_PROPERTY_DETAILS.TEHSIL_ID) "
        +" AND (IGRS_WARD_PATWARI_MASTER.WARD_PATWARI_ID = "
        +" IGRS_REG_PROPERTY_DETAILS.WARD_PATWARI_ID) "
        +" AND (IGRS_AREA_TYPE_MASTER.AREA_TYPE_ID = "
        +" IGRS_REG_PROPERTY_DETAILS.AREA_TYPE_ID) "
        +" AND ( IGRS_REG_PROPERTY_DETAILS.PROPERTY_TXN_ID  = ?)";
	
	
	public static final String USER_DETAILS_QUERY = 
		"SELECT DISTINCT IGRS_REG_PIN_DETAILS.USER_ID, "
		+"(SELECT  CASE WHEN (U1.USER_TYPE_ID = 'I') "
		+"THEN (SELECT CONCAT(CONCAT(CONCAT(CONCAT(FIRST_NAME, ' '), "
		+"MIDDLE_NAME ),' '),LAST_NAME) FROM IGRS_EMP_MASTER "
		+" WHERE EMP_ID=IGRS_REG_PIN_DETAILS.USER_ID) "
		+" ELSE (SELECT CONCAT(CONCAT(CONCAT(CONCAT(FIRST_NAME, ' '), "
		+" MIDDLE_NAME ),' '),LAST_NAME) FROM IGRS_USER_REG_DETAILS "
		+" WHERE USER_ID=IGRS_REG_PIN_DETAILS.USER_ID) END "
		+" FROM IGRS_USERS_LIST U1 WHERE USER_ID=IGRS_REG_PIN_DETAILS.USER_ID)"
		+" USERNAME FROM IGRS_REG_COMPLIANCE_DETAILS, "
		+" IGRS_REG_COMPLIANCE_TXN_DTLS,IGRS_REG_TXN_PARTY_DETAILS,"
		+" IGRS_REG_PROPERTY_DETAILS,IGRS_REG_PIN_DETAILS "
		+" WHERE (IGRS_REG_COMPLIANCE_DETAILS.COMPLIANCE_ID = "
		+" IGRS_REG_COMPLIANCE_TXN_DTLS.COMPLIANCE_ID) AND "
		+" (IGRS_REG_COMPLIANCE_TXN_DTLS.REG_TXN_ID = "
		+" IGRS_REG_TXN_PARTY_DETAILS.REG_TXN_ID) "
        +" AND (IGRS_REG_TXN_PARTY_DETAILS.PROPERTY_TXN_ID = "
        +" IGRS_REG_PROPERTY_DETAILS.PROPERTY_TXN_ID) "
        +" AND ( IGRS_REG_PROPERTY_DETAILS.PROPERTY_TXN_ID ="
        +" IGRS_REG_PIN_DETAILS.PROPERTY_TXN_ID) "
        +" AND ( IGRS_REG_PROPERTY_DETAILS.PROPERTY_TXN_ID  = ?)";
	
	public static final String VERIFIED_PIN_QUERY = 
		"SELECT COUNT(*) FROM IGRS_REG_PIN_DETAILS WHERE "
		+"PIN_NUMBER =? AND USER_ID=? AND PROPERTY_TXN_ID=? "
		+"AND ACTIVE_FLAG=?";
}
