/*
* Copyright Notice
*==============================================================================
* This file contains proprietary information of IGRS Bhopal Madhya Pradesh .
* Copying or reproduction without prior written approval is prohibited.
* 
*==============================================================================
*
* File Name   :  CommonSQL.java 
 * Author      :  Roopam Mehta 
 * Description :   
*/


/**
 * File Name: CommonSQL.java
 * @author Roopam Mehta
 * Created on 26 Feb 2014
 *
 */
package com.wipro.igrs.newdutycalculation.sql;


/**
 * 
 * @author Vinay Sharma
 *
 */
public class CommonSQL {

	public static final String GET_PROP_VAL_FLAG = "SELECT PROP_VAL_REQ_FLAG FROM IGRS_DEED_INSTRUMENT_MASTER WHERE INSTRUMENT_ID=?";
	
	public static final String GET_MARKET_VALUE_EN = "SELECT P.FINAL_MV,N.PROPERTY_TYPE_NAME,P.PROP_TYPE_ID,P.DIST_ID,P.SINGLE_BUYER,P.PROPERTY_TYPE_L1_ID,P.COLONY_ID FROM IGRS_PROP_VAL_TXN_DETLS P,IGRS_PROPERTY_TYPE_MASTER N WHERE P.VAL_TXN_ID=? AND P.PROP_TYPE_ID=N.PROPERTY_TYPE_ID";
	
	public static final String GET_MARKET_VALUE_HI = "SELECT P.FINAL_MV,N.H_PROPERTY_TYPE_NAME,P.PROP_TYPE_ID,P.DIST_ID,P.SINGLE_BUYER,P.PROPERTY_TYPE_L1_ID,P.COLONY_ID FROM IGRS_PROP_VAL_TXN_DETLS P,IGRS_PROPERTY_TYPE_MASTER N WHERE P.VAL_TXN_ID=? AND P.PROP_TYPE_ID=N.PROPERTY_TYPE_ID";

	public static final String GET_VALUATION_ID_AGI = "SELECT VAL_TXN_ID FROM IGRS_PROP_VAL_TXN_DETLS WHERE VAL_TXN_ID=?";

	public static final String GET_VALUATION_ID_PLOT_BUILD = "SELECT VAL_TXN_ID FROM IGRS_PROP_VAL_TXN_DETLS WHERE VAL_TXN_ID=?";

	//added new column MOVABLE_PROP_FLAG  by ankit for plant and machinery
	public static final String GET_USER_ENTERABLe_FIELD_EN="SELECT INST_FIELD_MAP_ID,FIELD_NAME,AS_CONSIDERATION,IN_STAMP_DUTY_CALC,MAPPING_STATUS,REF_FEE_ALREADY_PAID,DUTY_ALREADY_PAID,MOVABLE_PROP_FLAG FROM IGRS_INST_FIELD_MAPPING WHERE DEED_ID=? AND INSTRUMENT_ID=? and MAPPING_STATUS!='D' order by INST_FIELD_MAP_ID  ";
		
	//added new column MOVABLE_PROP_FLAG  by ankit for plant and machinery
	public static final String GET_USER_ENTERABLe_FIELD_ESTAMMP_EN="SELECT INST_FIELD_MAP_ID,FIELD_NAME,AS_CONSIDERATION,IN_STAMP_DUTY_CALC,MAPPING_STATUS,REF_FEE_ALREADY_PAID,DUTY_ALREADY_PAID,MOVABLE_PROP_FLAG FROM IGRS_INST_FIELD_MAPPING WHERE DEED_ID=? AND INSTRUMENT_ID=? and MAPPING_STATUS!='D' AND FIELD_NAME not like'%Total Stamp Duty Already Paid (INR)%' order by INST_FIELD_MAP_ID  ";
	
	//added new column MOVABLE_PROP_FLAG  by ankit for plant and machinery
	public static final String GET_USER_ENTERABLe_FIELD_HI="SELECT INST_FIELD_MAP_ID,FIELD_NAME_H,AS_CONSIDERATION,IN_STAMP_DUTY_CALC,MAPPING_STATUS,REF_FEE_ALREADY_PAID,DUTY_ALREADY_PAID,MOVABLE_PROP_FLAG FROM IGRS_INST_FIELD_MAPPING WHERE DEED_ID=? AND INSTRUMENT_ID=? and MAPPING_STATUS!='D' order by INST_FIELD_MAP_ID";
	
	//added new column MOVABLE_PROP_FLAG  by ankit for plant and machinery
	public static final String GET_USER_ENTERABLe_FIELD_ESTAMP_HI="SELECT INST_FIELD_MAP_ID,FIELD_NAME_H,AS_CONSIDERATION,IN_STAMP_DUTY_CALC,MAPPING_STATUS,REF_FEE_ALREADY_PAID,DUTY_ALREADY_PAID,MOVABLE_PROP_FLAG FROM IGRS_INST_FIELD_MAPPING WHERE DEED_ID=? AND INSTRUMENT_ID=? and MAPPING_STATUS!='D' AND FIELD_NAME not like'%Total Stamp Duty Already Paid (INR)%' order by INST_FIELD_MAP_ID";
	

	public static final String GET_STAMP_DUTY_DETAILS="SELECT INST_OPERATION_MAP_ID,OPERATION_ID,OPERATION_VALUE,UNIT_FRACTION_VALUE,MAX_VALUE,MIN_VALUE FROM IGRS_STAMP_DUTY_FORMULA_MASTER WHERE DEED_ID=? AND INSTRUMENT_ID=? AND STATUS_FLAG='A'";
	
	public static final String GET_REG_FEE_DETAILS="SELECT INST_OPERATION_MAP_ID,OPERATION_ID,OPERATION_VALUE,MAX_VALUE,MIN_VALUE FROM IGRS_REG_FEE_FORMULA_MASTER WHERE DEED_ID=? AND INSTRUMENT_ID=? AND STATUS_FLAG='A'";

	public static final String GET_PROPERTY_NAME_EN="SELECT PROPERTY_TYPE_NAME FROM IGRS_PROPERTY_TYPE_MASTER WHERE PROPERTY_TYPE_ID=?";

	public static final String GET_PROPERTY_NAME_HI="SELECT H_PROPERTY_TYPE_NAME FROM IGRS_PROPERTY_TYPE_MASTER WHERE PROPERTY_TYPE_ID=?";

	public static final String GET_UPKAR_FLAG="SELECT UPKAR_FLAG FROM IGRS_DEED_INSTRUMENT_MASTER WHERE INSTRUMENT_ID=?";
	
	public static final String GET_UPKAR_VALUE="SELECT ATTRIBUTE_VALUE FROM IGRS_CONFIG_PARAM_LIST WHERE ATTRIBUTE_ID='ATT_167'";
	
	public static final String GET_JANPAD_DETAILS="SELECT S.OPERATION_ID,J.NAGAR_NIGAM,J.NAGAR_PALIKA,J.CANTONMENT_NN,J.PLANNING_NN,J.JANPAD FROM IGRS_MUN_BLOCK_FORMULA_MASTER J,IGRS_STAMP_DUTY_FORMULA_MASTER S WHERE S.DEED_ID=J.DEED_ID AND S.INSTRUMENT_ID=J.INSTRUMENT_ID AND J.DEED_ID=? AND J.INSTRUMENT_ID=?   ";

	public static final String GET_MUNICIPAL_ID="SELECT P.SUB_AREA_TYPE_ID,P.IS_MUNICIPAL,(SELECT MUNICIPAL_BODY_ID FROM IGRS_MUNICIPAL_BODY_MASTER WHERE MUNICIPAL_BODY_ID=S.MUNICIPAL_BODY_ID) FROM IGRS_PROP_VAL_TXN_DETLS P,IGRS_SUB_AREA_TYPE_MASTER S WHERE P.SUB_AREA_TYPE_ID=S.SUB_AREA_TYPE_ID AND P.VAL_TXN_ID=?";

	public static final String GET_MAIN_DUTY_ID="SELECT IGRS_MAIN_DUTY_TXN_SEQ.NEXTVAL FROM DUAL";
	public static final String GET_PROP_DUTY_ID="SELECT IGRS_PROP_DUTY_SEQ .NEXTVAL FROM DUAL";
	
	public static final String INSERT_DUTY_MAIN="INSERT INTO IGRS_DUTY_TXN_DETLS(DUTY_TXN_ID,STAMP_DUTY,MUNICIPAL_DUTY,BLOCK_DUTY,UPKAR_DUTY,REG_FEE,TOTAL,DEED_ID,INSTRUMENT_ID,REG_FEE_PAID,DUTY_ALREADY_PAID,CREATED_BY,CREATED_DATE,CANCELLATION_FLAG,CANCELLATION_INST_ID,REF_MARKET_VALUE,TOTAL_AFTER_EXEMP,REG_FEE_AFTER_EXEMP,EXEMP_STAMP,EXEMP_REG,FAMILY_FLAG,GOV_FAVOUR,GOV_VALUE,TYPE_OF_TRANSACTION,EWS_APPLIED) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,SYSDATE,?,?,?,?,?,?,?,?,?,?,?,?) ";
	
	public static final String INSERT_FIELD_VALUE="INSERT INTO IGRS_PROP_DUTY_FIELD_DETLS(DUTY_FIELD_ID,DUTY_TXN_ID,PROP_DUTY_ID,INST_FIELD_MAP_ID,FIELD_VALUE,CREATED_BY,CREATED_DATE) VALUES(IGRS_DUTY_FIELD_SEQ.NEXTVAL,?,?,?,?,?,SYSDATE)";

	public static final String INSERT_PROP_DUTY_DETAILS="INSERT INTO IGRS_PROP_DUTY_DETLS(PROP_DUTY_ID,STAMP_DUTY,MUNICIPAL_DUTY,BLOCK_DUTY,UPKAR_DUTY,TOTAL,REG_FEE,REG_ALREADY_PAID,DUTY_ALREADY_PAID,CREATED_BY,CREATED_DATE,VAL_TXN_ID,DUTY_TXN_ID,MARKET_VALUE,PARTY_TYPE,PAYABLE_DUTY,PAYABLE_REG,GOV_VALUE) VALUES(?,?,?,?,?,?,?,?,?,?,SYSDATE,?,?,?,?,?,?,?) ";

	public static final String GET_VALUATION_ID_AGRI = "SELECT VAL_TXN_ID FROM IGRS_PROP_VAL_TXN_DETLS WHERE REF_VAL_TXN_ID=?";
	
	public static final String GET_MUNICIPAL_CHECK_BOX = "SELECT MUNICIPAL_FLAG_NPV FROM IGRS_DEED_INSTRUMENT_MASTER WHERE INSTRUMENT_ID=?";
	
	public static final String GET_FAMILY_CHECK_BOX = "SELECT FAVOUR_FAMILY FROM IGRS_DEED_INSTRUMENT_MASTER WHERE INSTRUMENT_ID=?";

	//public static final String GET_EXEMPTIONS="SELECT E.EXEMPTION_ID,E.EXEMPTION_NAME,E.EXEMPTION_DESC,E.APPLICABLE_ON,E.EXEMPTED_PERCENT FROM IGRS_EXEMPTION_MASTER E,IGRS_INST_EXEMPTION_MAPPING M WHERE M.EXEMPTION_ID=E.EXEMPTION_ID AND M.DEED_ID=? AND M.INSTRUMENT_ID=? AND M.MAPPING_STATUS='A' AND E.EXEMPTION_STATUS='A' AND E.APPLICABLE_ON='S'";
	public static final String GET_EXEMPTIONS="SELECT E.EXEMPTION_ID,E.EXEMPTION_NAME,E.EXEMPTION_DESC,E.APPLICABLE_ON,E.EXEMPTED_PERCENT,E.EXEMPTION_ESTAMP FROM IGRS_EXEMPTION_MASTER E,IGRS_INST_EXEMPTION_MAPPING M WHERE M.EXEMPTION_ID=E.EXEMPTION_ID AND M.DEED_ID=? AND M.INSTRUMENT_ID=? AND M.MAPPING_STATUS='A' AND E.EXEMPTION_STATUS='A' AND E.APPLICABLE_ON='S'";
	//public static final String GET_EXEMPTIONS_H="SELECT E.EXEMPTION_ID,E.H_EXEMPTION_NAME,E.H_EXEMPTION_DESC,E.APPLICABLE_ON,E.EXEMPTED_PERCENT FROM IGRS_EXEMPTION_MASTER E,IGRS_INST_EXEMPTION_MAPPING M WHERE M.EXEMPTION_ID=E.EXEMPTION_ID AND M.DEED_ID=? AND M.INSTRUMENT_ID=? AND M.MAPPING_STATUS='A' AND E.EXEMPTION_STATUS='A' AND E.APPLICABLE_ON='S'";
	public static final String GET_EXEMPTIONS_H="SELECT E.EXEMPTION_ID,E.H_EXEMPTION_NAME,E.H_EXEMPTION_DESC,E.APPLICABLE_ON,E.EXEMPTED_PERCENT,E.EXEMPTION_ESTAMP FROM IGRS_EXEMPTION_MASTER E,IGRS_INST_EXEMPTION_MAPPING M WHERE M.EXEMPTION_ID=E.EXEMPTION_ID AND M.DEED_ID=? AND M.INSTRUMENT_ID=? AND M.MAPPING_STATUS='A' AND E.EXEMPTION_STATUS='A' AND E.APPLICABLE_ON='S'";
	public static final String GET_EXEMPTIONS_REG="SELECT E.EXEMPTION_ID,E.EXEMPTION_NAME,E.EXEMPTION_DESC,E.APPLICABLE_ON,E.EXEMPTED_PERCENT,E.EXEMPTION_ESTAMP FROM IGRS_EXEMPTION_MASTER E,IGRS_INST_EXEMPTION_MAPPING M WHERE M.EXEMPTION_ID=E.EXEMPTION_ID AND M.DEED_ID=? AND M.INSTRUMENT_ID=? AND M.MAPPING_STATUS='A' AND E.EXEMPTION_STATUS='A' AND E.APPLICABLE_ON='R'";

	public static final String GET_EXEMPTIONS_REG_H="SELECT E.EXEMPTION_ID,E.H_EXEMPTION_NAME,E.H_EXEMPTION_DESC,E.APPLICABLE_ON,E.EXEMPTED_PERCENT,E.EXEMPTION_ESTAMP FROM IGRS_EXEMPTION_MASTER E,IGRS_INST_EXEMPTION_MAPPING M WHERE M.EXEMPTION_ID=E.EXEMPTION_ID AND M.DEED_ID=? AND M.INSTRUMENT_ID=? AND M.MAPPING_STATUS='A' AND E.EXEMPTION_STATUS='A' AND E.APPLICABLE_ON='R'";

	
	public static final String GET_DEED_DISCRIPTION="SELECT DEED_TYPE_DESCRIPTION FROM IGRS_DEED_TYPE_MASTER WHERE DEED_TYPE_ID=?";
	
	public static final String GET_DEED_DISCRIPTION_H="SELECT H_DEED_TYPE_DISC FROM IGRS_DEED_TYPE_MASTER WHERE DEED_TYPE_ID=?";

	public static final String GET_INST_DISCRIPTION="SELECT INSTRUMENT_DESCRIPTION FROM IGRS_DEED_INSTRUMENT_MASTER WHERE INSTRUMENT_ID=?";
	
	public static final String GET_INST_DISCRIPTION_H="SELECT H_INSTRUMENT_DESCRIPTION FROM IGRS_DEED_INSTRUMENT_MASTER WHERE INSTRUMENT_ID=?";

	public static final String DEED_CATEGORY="SELECT DEED_CATEGORY_ID,DEED_CATEGORY_NAME FROM IGRS_DEED_CATEGORY_MASTER WHERE STATUS='A' ";
		
	public static final String DEED_CATEGORY_HI="SELECT DEED_CATEGORY_ID,DEED_CATEGORY_NAME_H FROM IGRS_DEED_CATEGORY_MASTER WHERE STATUS='A'";
	
	public static final String CANCELATION_DEED_LIST="SELECT DEED_TYPE_ID,DEED_TYPE_NAME FROM IGRS_DEED_TYPE_MASTER WHERE DEED_STATUS='A' AND DEED_CATEGORY_ID='5'";
	public static final String CANCELATION_DEED_LIST_HI="SELECT DEED_TYPE_ID,H_DEED_TYPE_NAME FROM IGRS_DEED_TYPE_MASTER WHERE DEED_STATUS='A' AND DEED_CATEGORY_ID='5'";
	public static final String DEED_QUERY_DC_COMMON = "SELECT DEED_TYPE_ID, "
		+"DEED_TYPE_NAME FROM IGRS_DEED_TYPE_MASTER "
		+"WHERE DEED_STATUS='A' AND DEED_CATEGORY_ID=? ORDER BY DEED_TYPE_NAME ASC";
	public static final String DEED_QUERY_DC_COMMON_HI = "SELECT DEED_TYPE_ID, "
		+"H_DEED_TYPE_NAME FROM IGRS_DEED_TYPE_MASTER "
		+"WHERE DEED_STATUS='A' AND DEED_CATEGORY_ID=? ORDER BY DEED_TYPE_NAME ASC";
	public static final String DEED_QUERY_DC_COMMON_CANCEL="SELECT DISTINCT D.DEED_TYPE_ID,D.DEED_TYPE_NAME FROM IGRS_DEED_TYPE_MASTER D,IGRS_DEED_INSTRUMENT_MASTER E WHERE D.DEED_STATUS   ='A' AND D.DEED_CATEGORY_ID=? AND D.DEED_TYPE_ID=E.DEED_TYPE_ID AND E.CANCEL_DEED_APP_FLAG='Y' ORDER BY DEED_TYPE_NAME ASC";
	
	public static final String DEED_QUERY_DC_COMMON_CANCEL_HI="SELECT DISTINCT D.DEED_TYPE_ID,D.H_DEED_TYPE_NAME FROM IGRS_DEED_TYPE_MASTER D,IGRS_DEED_INSTRUMENT_MASTER E WHERE D.DEED_STATUS   ='A' AND D.DEED_CATEGORY_ID=? AND D.DEED_TYPE_ID=E.DEED_TYPE_ID AND E.CANCEL_DEED_APP_FLAG='Y' ORDER BY H_DEED_TYPE_NAME ASC";

	public static final String DEED_QUERY_DEEDCATEGORY_COMMON = "SELECT DEED_CATEGORY_ID, "
		+"DEED_CATEGORY_NAME FROM IGRS_DEED_CATEGORY_MASTER "
		+"WHERE STATUS='A' ORDER BY DEED_CATEGORY_NAME ASC";
	public static final String DEED_QUERY_DEEDCATEGORY_COMMON_HINDI = "SELECT DEED_CATEGORY_ID, "
		+"DEED_CATEGORY_NAME_H FROM IGRS_DEED_CATEGORY_MASTER "
		+"WHERE STATUS='A' ORDER BY DEED_CATEGORY_NAME ASC";
	public static final String DEED_QUERY_PROPERTY = "SELECT DEED_TYPE_ID, "
		+"DEED_TYPE_NAME FROM IGRS_DEED_TYPE_MASTER "
		+"WHERE DEED_STATUS='A' AND PROPERTY_RELATED_DEED='Y'  ORDER BY DEED_TYPE_NAME ASC";
	
	/**
	 * 	/**
	 * @author RISHAB
	 */
	public static final String DEED_QUERY_REGISTRATION = "SELECT DEED_TYPE_ID, "
		+"DEED_TYPE_NAME FROM IGRS_DEED_TYPE_MASTER "
		+"WHERE DEED_STATUS='A' AND PROPERTY_RELATED_DEED='Y' AND ROR_REQUIRED='R' ORDER BY DEED_TYPE_NAME ASC";
	public static final String INSTRUMENTS_QUERY_HINDI = "SELECT "
		+ "INSTRUMENT_ID,"
		+ "INSTRUMENT_NAME,Label_Amount,Label_Value_Required,H_LABEL_AMOUNT,H_INSTRUMENT_NAME "
		+ "FROM IGRS_DEED_INSTRUMENT_MASTER "
		+ "WHERE DEED_TYPE_ID=? AND "
		+ "INSTRUMENT_STATUS='A' ORDER BY "
		+ "INSTRUMENT_ID ASC";
	public static final String INSTRUMENTS_QUERY_HINDI_CANCEL = "SELECT "
		+ "INSTRUMENT_ID,"
		+ "INSTRUMENT_NAME,Label_Amount,Label_Value_Required,H_LABEL_AMOUNT,H_INSTRUMENT_NAME "
		+ "FROM IGRS_DEED_INSTRUMENT_MASTER "
		+ "WHERE DEED_TYPE_ID=? AND "
		+ "INSTRUMENT_STATUS='A' AND CANCEL_DEED_APP_FLAG='Y' ORDER BY "
		+ "INSTRUMENT_ID ASC";
	public static final String CANCEL_STAMP_VALUE="SELECT CANCEL_STAMP_VALUE FROM IGRS_DEED_INSTRUMENT_MASTER WHERE DEED_TYPE_ID =? AND INSTRUMENT_ID=?";
	public static final String CANCEL_REG_VALUE="SELECT CANCEL_REG_FEE_VALUE FROM IGRS_DEED_INSTRUMENT_MASTER WHERE DEED_TYPE_ID =? AND INSTRUMENT_ID=?";

	public static final String AGRI_AREA="SELECT TOTAL_AREA FROM IGRS_PROP_AGRI_DETLS WHERE VAL_TXN_ID=?";
	public static final String GET_MIN_STAMP_DUTY="SELECT MIN_VALUE FROM IGRS_STAMP_DUTY_FORMULA_MASTER WHERE DEED_ID=? AND INSTRUMENT_ID=? AND STATUS_FLAG='A'";
	public static final String GET_MIN_REG_FEE="SELECT MIN_VALUE FROM IGRS_REG_FEE_FORMULA_MASTER WHERE DEED_ID=? AND INSTRUMENT_ID=? AND STATUS_FLAG='A'";
	
	public static final String INSERT_DUTY_PREMIUM_DETAILS="INSERT INTO IGRS_DUTY_RENT_DETLS(RENT_ID,DUTY_TXN_ID,PROP_VAL_ID,DEVELOPMENT_CHARGES,ADITTIONAL,PERMIUM,OTHER_CHARGES,RENT_PREMIUM_FLAG,CREATED_BY,CREATED_DATE) VALUES(IGRS_DUTY_RENT_SEQ.NEXTVAL,?,?,?,?,?,?,'P',?,SYSDATE)";
	public static final String INSERT_DUTY_RENT_DETAILS="INSERT INTO IGRS_DUTY_RENT_DETLS(RENT_ID,DUTY_TXN_ID,PROP_VAL_ID,MONTHLY_RENT,MAINTENCE_CHARGES,YEAR,MONTH,RENT_PREMIUM_FLAG,CREATED_BY,CREATED_DATE) VALUES(IGRS_DUTY_RENT_SEQ.NEXTVAL,?,?,?,?,?,?,'R',?,SYSDATE)";
	public static final String   INSERT_EXEMPTION_DETAILS="INSERT INTO IGRS_DUTY_EXEMPTION_DETLS(EXEMPTION_TXN_ID,DUTY_TXN_ID,EXEMPTION_ID,CREATED_BY,CREATED_DATE) VALUES(IGRS_EXEMPTION_SEQ.NEXTVAL,?,?,?,SYSDATE)";
	public static final String DEED_QUERY_DC_ESTAMP="SELECT DISTINCT D.DEED_TYPE_ID,D.DEED_TYPE_NAME FROM IGRS_DEED_TYPE_MASTER D,IGRS_DEED_INSTRUMENT_MASTER E WHERE D.DEED_STATUS   ='A' AND D.DEED_CATEGORY_ID=? AND D.DEED_TYPE_ID=E.DEED_TYPE_ID AND E.INSTRUMENT_TYPE='O' and E.INSTRUMENT_STATUS='A' ORDER BY DEED_TYPE_NAME ASC";
	public static final String DEED_QUERY_DC_ESTAMP_HI="SELECT DISTINCT D.DEED_TYPE_ID,D.H_DEED_TYPE_NAME FROM IGRS_DEED_TYPE_MASTER D,IGRS_DEED_INSTRUMENT_MASTER E WHERE D.DEED_STATUS   ='A' AND D.DEED_CATEGORY_ID=? AND D.DEED_TYPE_ID=E.DEED_TYPE_ID AND E.INSTRUMENT_TYPE='O' and E.INSTRUMENT_STATUS='A' ORDER BY D.H_DEED_TYPE_NAME ASC";
	public static final String INSTRUMENTS_QUERY_HINDI_ESTAMP = "SELECT "
		+ "INSTRUMENT_ID,"
		+ "INSTRUMENT_NAME,Label_Amount,Label_Value_Required,H_LABEL_AMOUNT,H_INSTRUMENT_NAME "
		+ "FROM IGRS_DEED_INSTRUMENT_MASTER "
		+ "WHERE DEED_TYPE_ID=? AND "
		+ "INSTRUMENT_STATUS='A' AND INSTRUMENT_TYPE='O' ORDER BY "
		+ "INSTRUMENT_ID ASC";
	public static final String INSTRUMENTS_QUERY_ESTAMP = "SELECT "
		+ "INSTRUMENT_ID,"
		+ "INSTRUMENT_NAME,Label_Amount,Label_Value_Required,H_LABEL_AMOUNT,H_INSTRUMENT_NAME "
		+ "FROM IGRS_DEED_INSTRUMENT_MASTER "
		+ "WHERE DEED_TYPE_ID=? AND "
		+ "INSTRUMENT_STATUS='A' AND INSTRUMENT_TYPE='O' ORDER BY "
		+ "INSTRUMENT_ID ASC";
	public static final String CURRENT_YEAR = "select to_char(sysdate,'yyyy') from dual";
	public static final String CURRENT_DATE = "select to_char(sysdate,'dd/mm/yyyy') from dual";
	public static final String DEED_INSTRUMENT_REG="SELECT R.DEED_ID,R.INSTRUMENTS_ID,R.CANCELLATION_FLAG,D.FAMILY_FLAG,D.DUTY_TXN_ID,D.MUNICIPAL_DUTY FROM IGRS_REG_TXN_DETLS R,IGRS_DUTY_TXN_DETLS D WHERE REG_TXN_ID=? AND D.DUTY_TXN_ID=R.DUTY_TXN_ID";
	public static final String CONSNTER_DETAILS_DUTY="SELECT CONSENTER_TXN_NUM,WITH_CONSIDERATION,CONSIDERATION_AMOUNT FROM IGRS_REG_CONSENTER_DETAILS WHERE REG_TXN_ID=?";
	public static final String CONSENTER_FIXED_DUTIES="SELECT STAMP,JANPAD,MUNICIPAL,UPKAR,REG_FEE FROM IGRS_CONST_DUTY_MASTER WHERE INSTRUMENT_ID=?"; 
	public static final String	CONS_EXEMPTION ="SELECT E.EXEMPTED_PERCENT,E.EXEMPTION_ID FROM IGRS_EXEMPTION_MASTER E,IGRS_DUTY_EXEMPTION_DETLS D WHERE E.EXEMPTION_ID=D.EXEMPTION_ID AND E.APPLICABLE_ON=? AND D.DUTY_TXN_ID=? "; 
	public static final String	GET_APPLY_EWS ="SELECT EWS_APPLIED FROM IGRS_DUTY_TXN_DETLS WHERE DUTY_TXN_ID=? ";
	public static final String CONS_DUTY_UPDATE="UPDATE IGRS_DUTY_TXN_DETLS SET STAMP_DUTY=STAMP_DUTY+?,BLOCK_DUTY=BLOCK_DUTY+?,MUNICIPAL_DUTY=MUNICIPAL_DUTY+?,UPKAR_DUTY=UPKAR_DUTY+?,TOTAL=TOTAL+?,TOTAL_AFTER_EXEMP=TOTAL_AFTER_EXEMP+?,REG_FEE=REG_FEE+?,REG_FEE_AFTER_EXEMP=REG_FEE_AFTER_EXEMP+?,EXEMP_STAMP=EXEMP_STAMP+?,EXEMP_REG=EXEMP_REG+? where DUTY_TXN_ID=? ";
	public static final String CONS_DUTY_INSERT="INSERT INTO IGRS_CONSENTER_DUTY_DETAILS (CON_DUTY_TXN_ID,STAMP_DUTY,JANPAD_DUTY,MUNICIPAL_DUTY,UPKAR_DUTY,TOTAL,REG_FEE,TOTAL_AFTER_EXEMP,REG_FEE_AFTER_EXEMP,EXEMPTED_DUTY,EXEMPTED_REG_FEE,CONSENTER_TXN_NUM,REG_TXN_ID) VALUES(IGRS_CONSENTER_DUTY_SEQ.NEXTVAL,?,?,?,?,?,?,?,?,?,?,?,?)";
	
	public static final String GET_APP_SUBCLAUSE = "select NVL(APPLICABLE_SUBCLAUSE_ID,'') from IGRS_COLONY_MASTER WHERE COLONY_ID=?";
	public static final String GET_PROP_TYPE = "select PROP_TYPE_ID from IGRS_PROP_VAL_TXN_DETLS WHERE VAL_TXN_ID=?";
	
	public static final String GET_PROP_TYPE_FURTHER_DETLS = "select BUILDING_SUB_TYPE_ID,FLOOR_AREA,MULTISTOREY_SUB_TYPE,BUILD_UP_AREA,IS_HOUSING_BOARD from IGRS_PROP_BUILDING_DETLS WHERE VAL_TXN_ID=?";
	public static final String GET_PROP_TYPE_FURTHER_FLOOR_DETLS="SELECT (nvl(RCC_AREA,0)+nvl(RBC_AREA,0)+nvl(TIN_AREA,0)+nvl(KACHA_AREA,0)) "+
																 "FROM IGRS_FLOOR_AREA_DETLS, "+
																 "IGRS_FLOOR_TXN_DETLS, "+
																 "IGRS_PROP_BUILDING_DETLS "+
															     "WHERE IGRS_FLOOR_TXN_DETLS.FLOOR_TXN_ID=IGRS_FLOOR_AREA_DETLS.FLOOR_TXN_ID "+
																 "AND IGRS_FLOOR_TXN_DETLS.FLOOR_TYPE_ID='3' "+ //ground floor
																 "AND IGRS_FLOOR_AREA_DETLS.SUB_PROP_TYPE_ID='7' "+  //residential
																 "AND IGRS_PROP_BUILDING_DETLS.BUILDING_TXN_ID=IGRS_FLOOR_TXN_DETLS.BUILDING_TXN_ID "+
																 "AND IGRS_PROP_BUILDING_DETLS.VAL_TXN_ID=?";
	
	public static final String GET_RESI_FLOOR_COUNT="SELECT count(FLOOR_AREA_TXN_ID) "+
	 												"FROM IGRS_FLOOR_AREA_DETLS, "+
	 												"IGRS_FLOOR_TXN_DETLS, "+
	 												"IGRS_PROP_BUILDING_DETLS "+
	 												"WHERE IGRS_FLOOR_TXN_DETLS.FLOOR_TXN_ID=IGRS_FLOOR_AREA_DETLS.FLOOR_TXN_ID "+
	 												"AND IGRS_FLOOR_TXN_DETLS.FLOOR_TYPE_ID='3' "+ //ground floor
	 												"AND IGRS_PROP_BUILDING_DETLS.BUILDING_TXN_ID=IGRS_FLOOR_TXN_DETLS.BUILDING_TXN_ID "+
	 												"AND IGRS_PROP_BUILDING_DETLS.VAL_TXN_ID=?";

	
	//added by akansha
	
	public static final String MAJOR_LIST_En="SELECT MINERAL_ID,MAJOR_MINERAL_NAME_EN FROM IGRS_MINERAL_MASTER WHERE MINERAL_TYPE=? AND STATUS_FLAG='A' order by mineral_id asc";
	public static final String MAJOR_LIST_Hn="SELECT MINERAL_ID,MAJOR_MINERAL_NAME_HN FROM IGRS_MINERAL_MASTER WHERE MINERAL_TYPE=? AND STATUS_FLAG='A' order by mineral_id asc";

	public static final String MINOR_LIST_En="SELECT MINERAL_ID,MINOR_MINERAL_NAME_EN FROM IGRS_MINERAL_MASTER WHERE MINERAL_TYPE=? AND STATUS_FLAG='A'";
	public static final String MINOR_LIST_Hn="SELECT MINERAL_ID,MINOR_MINERAL_NAME_HN FROM IGRS_MINERAL_MASTER WHERE MINERAL_TYPE=? AND STATUS_FLAG='A'";

	public static String GET_RIN_PUSTIKA_CLR="select distinct RIN_PUSHTIKA_NUMBER from IGRS_REG_PROP_KHASRA_CLR_DETLS where VAL_TXN_ID=?";
	public static String GET_COLONY_ID_CLR="select distinct COLONY_ID from igrs_prop_val_txn_detls where VAL_TXN_ID=?";

	public static String GET_ALL_KHASRA_LIST_WRT_VALTXNID="select khasra_no from igrs_reg_prop_khasra_clr_detls where val_txn_id=?";
	
	
	//added by Ankit 
	public static String GET_DUTY_DETAILS = "SELECT INST_OPERATION_MAP_ID,OPERATION_ID,OPERATION_VALUE,UNIT_FRACTION_VALUE,MAX_VALUE,MIN_VALUE FROM IGRS_MV_PR_DUTY_FORMULA_MASTER WHERE DEED_ID=? AND INSTRUMENT_ID=? AND DUTY_TYPE = ? AND STATUS_FLAG='A'";
	public static String INSERT_MV_PR_DUTY_TXN_DETAILS = "INSERT INTO IGRS_MV_PR_DUTY_TXN_DETLS(TXN_ID,DUTY_TXN_ID,STAMP_DUTY,MUNICIPAL_DUTY,UPKAR_DUTY,JANPAD_DUTY,REG_FEE,TOTAL_DUTY,MV_PV_VALUE,CREATED_BY,CREATED_DATE) VALUES(IGRS_MV_PR_DUTY_TXN_SEQ.NEXTVAL,?,?,?,?,?,?,?,?,?,SYSDATE)";
}
