package com.wipro.igrs.Seals.sql;

public class SealsSQL {

	
	public static final String GET_SUB_SEALS = "SELECT SEAL_SUB_ID,SEAL_SUB_NAME FROM IGRS_REG_SEALS_MASTER " +
			"WHERE SEAL_ID = ?";
	
	public static final String GET_SUB_SEALS_HI = "SELECT SEAL_SUB_ID,H_SEAL_SUB_NAME FROM IGRS_REG_SEALS_MASTER " +
	"WHERE SEAL_ID = ?";
	
	/*public static final String GET_PRESENTATION_PARTY_DETAILS = "SELECT distinct b.REG_TXN_ID,b.PARTY_FIRST_NAME,b.PARTY_LAST_NAME, " +
			"b.PARTY_TYPE_ID,b.PARTY_TXN_ID,b.PHOTO_PROOF_TYPE_ID,b.PHOTO_PROOF_ID, " +
			"b.AUTHRZD_PERSN_NAME,b.APPELLATE_TYPE_ID,b.NAME_OF_OFFICIAL FROM IGRS_REG_TXN_PARTY_DETLS b WHERE b.REG_TXN_ID=? AND (IS_APPLICANT='Y' OR IS_APPLICANT='N' OR IS_APPLICANT='C')";
	*/
	//Above commented and Modified - Minor Guardian and for will deed  - Rahul 
	/*public static final String GET_PRESENTATION_PARTY_DETAILS = "SELECT distinct b.REG_TXN_ID,b.PARTY_FIRST_NAME,b.PARTY_LAST_NAME, " +
	"b.PARTY_TYPE_ID,b.PARTY_TXN_ID,b.PHOTO_PROOF_TYPE_ID,b.PHOTO_PROOF_ID, " +
	"b.AUTHRZD_PERSN_NAME,b.APPELLATE_TYPE_ID,b.NAME_OF_OFFICIAL,b.PARTY_AGE,b.GUARDIAN_NAME,b.party_middle_name,b.MINOR_GUARDIAN,e.relation_type_name,b.UNIVERSAL_DEED_CLAIMANT_FLAG,e.H_RELATION_TYPE_NAME  FROM IGRS_REG_TXN_PARTY_DETLS b,IGRS_RELATION_TYPE_MASTER e WHERE b.REG_TXN_ID=? AND (IS_APPLICANT='Y' OR IS_APPLICANT='N' OR IS_APPLICANT='C')AND e.relation_type_id =b.relation_type_id";
	*/
	// Modified for Gov official - Rahul
/*	public static final String GET_PRESENTATION_PARTY_DETAILS = "SELECT  REG_TXN_ID,PARTY_FIRST_NAME,PARTY_LAST_NAME, " +
	"PARTY_TYPE_ID,PARTY_TXN_ID,PHOTO_PROOF_TYPE_ID,PHOTO_PROOF_ID, " +
	"AUTHRZD_PERSN_NAME,APPELLATE_TYPE_ID,NAME_OF_OFFICIAL,PARTY_AGE,GUARDIAN_NAME,party_middle_name,MINOR_GUARDIAN,relation_type_name,UNIVERSAL_DEED_CLAIMANT_FLAG,H_RELATION_TYPE_NAME  FROM "+
	 "(SELECT distinct b.REG_TXN_ID,b.PARTY_FIRST_NAME,b.PARTY_LAST_NAME, " +
	"b.PARTY_TYPE_ID,b.PARTY_TXN_ID,b.PHOTO_PROOF_TYPE_ID,b.PHOTO_PROOF_ID, " +
	"b.AUTHRZD_PERSN_NAME,b.APPELLATE_TYPE_ID,b.NAME_OF_OFFICIAL,b.PARTY_AGE,b.GUARDIAN_NAME,b.party_middle_name,b.MINOR_GUARDIAN,e.relation_type_name,b.UNIVERSAL_DEED_CLAIMANT_FLAG,e.H_RELATION_TYPE_NAME  FROM IGRS_REG_TXN_PARTY_DETLS b,IGRS_RELATION_TYPE_MASTER e WHERE b.REG_TXN_ID=? AND (IS_APPLICANT='Y' OR IS_APPLICANT='N' OR IS_APPLICANT='C')AND e.relation_type_id =b.relation_type_id" +
	" UNION "+
	"SELECT distinct b.REG_TXN_ID,b.PARTY_FIRST_NAME,b.PARTY_LAST_NAME, " +
	"b.PARTY_TYPE_ID,b.PARTY_TXN_ID,b.PHOTO_PROOF_TYPE_ID,b.PHOTO_PROOF_ID, " +
	"b.AUTHRZD_PERSN_NAME,b.APPELLATE_TYPE_ID,b.NAME_OF_OFFICIAL,b.PARTY_AGE,b.GUARDIAN_NAME,b.party_middle_name,b.MINOR_GUARDIAN,' ' AS relation_type_name,b.UNIVERSAL_DEED_CLAIMANT_FLAG,' ' AS H_RELATION_TYPE_NAME  " +
	"FROM IGRS_REG_TXN_PARTY_DETLS b,IGRS_RELATION_TYPE_MASTER e WHERE b.REG_TXN_ID=? AND (IS_APPLICANT='Y' OR IS_APPLICANT='N' OR IS_APPLICANT='C')AND b.relation_type_id IS NULL)" ;
	*/
	
	public static final String GET_PRESENTATION_PARTY_DETAILS ="SELECT REG_TXN_ID,PARTY_FIRST_NAME,PARTY_LAST_NAME, PARTY_TYPE_ID,PARTY_TXN_ID,PHOTO_PROOF_TYPE_ID,PHOTO_PROOF_ID,AUTHRZD_PERSN_NAME,APPELLATE_TYPE_ID, "+
  " NAME_OF_OFFICIAL,PARTY_AGE,GUARDIAN_NAME,party_middle_name, MINOR_GUARDIAN, relation_type_id, UNIVERSAL_DEED_CLAIMANT_FLAG "+

" FROM "+
 " (SELECT DISTINCT b.REG_TXN_ID, b.PARTY_FIRST_NAME,b.PARTY_LAST_NAME,b.PARTY_TYPE_ID,b.PARTY_TXN_ID,b.PHOTO_PROOF_TYPE_ID, b.PHOTO_PROOF_ID, "+
 "   b.AUTHRZD_PERSN_NAME, b.APPELLATE_TYPE_ID,b.NAME_OF_OFFICIAL,b.PARTY_AGE,b.GUARDIAN_NAME,b.party_middle_name, b.MINOR_GUARDIAN, b.relation_type_id, "+
 "   b.UNIVERSAL_DEED_CLAIMANT_FLAG "+
 " FROM IGRS_REG_TXN_PARTY_DETLS b "+
 " WHERE b.REG_TXN_ID     =? AND (IS_APPLICANT      ='Y'OR IS_APPLICANT        ='N' OR IS_APPLICANT        ='C') "+
 " UNION SELECT DISTINCT b.REG_TXN_ID,b.PARTY_FIRST_NAME, b.PARTY_LAST_NAME, b.PARTY_TYPE_ID,b.PARTY_TXN_ID,b.PHOTO_PROOF_TYPE_ID, b.PHOTO_PROOF_ID, "+
  "  b.AUTHRZD_PERSN_NAME, b.APPELLATE_TYPE_ID, b.NAME_OF_OFFICIAL, b.PARTY_AGE, b.GUARDIAN_NAME,b.party_middle_name, b.MINOR_GUARDIAN, "+
 " b. relation_type_id,b.UNIVERSAL_DEED_CLAIMANT_FLAG "+
 " FROM IGRS_REG_TXN_PARTY_DETLS b WHERE b.REG_TXN_ID      =? AND (IS_APPLICANT       ='Y' "+
 " OR IS_APPLICANT         ='N' OR IS_APPLICANT         ='C') AND b.relation_type_id IS NULL)" ;
	
	
		public static final String GET_PARTY_ROLE_FROM_ID = "SELECT PARTY_TYPE_NAME FROM IGRS_PARTY_TYPE_MASTER WHERE PARTY_TYPE_ID =?";
	
	public static final String GET_PARTY_ROLE_FROM_ID_HI = "SELECT H_PARTY_TYPE_NAME FROM IGRS_PARTY_TYPE_MASTER WHERE PARTY_TYPE_ID =?";
	
	public static final String GET_PARTY_ROLE = "SELECT ROLE_NAME FROM IGRS_REG_TXN_PARTY_DETLS WHERE PARTY_TXN_ID = ?";
	
	public static final String GET_SR_DETAILS = "SELECT (FIRST_NAME ||' ' || LAST_NAME)SR_NAME FROM IGRS_USER_REG_DETAILS WHERE  USER_ID = ?";
	
	public static final String GET_SEALS_SEQ = "SELECT IGRS_REG_SEALS_PARENT_SEQ.NEXTVAL FROM DUAL";
	
	public static final String INSERT_PRSENTATION_SEAL_DATA = "INSERT ALL INTO IGRS_REG_SEALS_PARENT_TXN" +
			"(SEAL_TXN_ID,REG_TXN_ID,SEAL_SUB_ID,SEAL_DATE,SR_NAME,DESIGNATION,SRO,DISTRICT,TEHSIL_NAME,FINAL_CONTENT)VALUES" +
			"(?,?,?,SYSDATE,?,?,OFFICE_NAME,DISTRICT_NAME,TEHSIL_NAME,?)" +
			"(SELECT OFC.OFFICE_NAME, DISTT.DISTRICT_NAME, TEHS.TEHSIL_NAME FROM IGRS_OFFICE_MASTER OFC,IGRS_DISTRICT_MASTER DISTT, " +
			"IGRS_TEHSIL_MASTER TEHS WHERE OFC.OFFICE_ID = ? AND OFC.DISTRICT_ID = DISTT.DISTRICT_ID AND " +
			"TEHS.TEHSIL_ID = OFC.TEHSIL_ID)"; 
	
	public static final String INSERT_PARTY_DETAILS_PRESENTATION = "INSERT INTO IGRS_REG_SEALS_CHILD_TXN(REG_CHILD_ID,SEAL_TXN_ID,PARTY_TYPE,PARTY_ID)" +
			"VALUES(IGRS_REG_SEALS_CHILD_SEQ.NEXTVAL,?,'P',?)";
	
	public static final String GET_SYS_DATE = "SELECT TO_CHAR(SYSDATE,'DD/MM/YYYY') FROM DUAL";
	
	public static final String GET_PRESENTATION_DATE = "SELECT TO_CHAR(MIN(P.UPDATED_DATE),'DD/MM/YYYY') FROM IGRS_REG_TXN_PARTY_OTHER_DTLS P,IGRS_REG_TXN_PARTY_DETLS R where R.PARTY_TXN_ID IN(";

	public static final String GET_EXECUTION_DATE = "SELECT TO_CHAR(MAX(P.UPDATED_DATE),'DD/MM/YYYY') FROM IGRS_REG_TXN_PARTY_OTHER_DTLS P,IGRS_REG_TXN_PARTY_DETLS R where R.PARTY_TXN_ID IN(";

	public static final String GET_SEAL_DATE_MAX = "SELECT TO_CHAR(MAX(P.UPDATED_DATE),'DD/MM/YYYY') FROM IGRS_REG_TXN_PARTY_OTHER_DTLS P,IGRS_REG_TXN_PARTY_DETLS R where P.PARTY_OTHER_DETLS_ID=R.PARTY_OTHER_DETLS_ID and R.reg_txn_id=?";

	public static final String GET_SEAL_WITNESS_MAX = "SELECT TO_CHAR(MAX(P.UPDATED_DATE),'DD/MM/YYYY') FROM IGRS_REG_TXN_PARTY_OTHER_DTLS P,IGRS_REG_TXN_WITNESS_DTLS R where P.PARTY_OTHER_DETLS_ID=R.PARTY_OTHER_DETLS_ID and R.reg_txn_id=?";

	public static final String GET_PRESENTATION_DATE_REMAING=" )AND P.PARTY_OTHER_DETLS_ID=R.PARTY_OTHER_DETLS_ID ";
	//public static final String GET_SYS_DATE = "SELECT TO_CHAR(SYSTEMDATE,'DD/MM/YYYY') FROM IGRS_TEMP_DATE";
	
	public static final String UPADTE_CHECKER_PARTY_PRESENT= "update IGRS_REG_TXN_PARTY_DETLS SET PARTY_PRESENT_AT_CHECKER ='Y' WHERE PARTY_TXN_ID IN ("; 
	
	public static final String GET_PRESENTATION_TIME = "SELECT TO_CHAR(MIN(P.UPDATED_DATE),'hh:mi:ss') FROM IGRS_REG_TXN_PARTY_OTHER_DTLS P,IGRS_REG_TXN_PARTY_DETLS R where R.PARTY_TXN_ID IN(";

	public static final String GET_REG_DATE = "SELECT TO_CHAR(UPDATE_DATE,'DD/MM/YYYY') FROM IGRS_REG_TXN_DETLS WHERE REG_TXN_ID = ?";
	
	public static final String GET_SYS_TIME = "SELECT TO_CHAR(SYSDATE,'hh:mi:ss') FROM DUAL";
//	public static final String GET_SYS_TIME = "SELECT TO_CHAR(SYSTEMDATE,'hh:mi:ss') FROM IGRS_TEMP_DATE";
	
	public static final String GET_OFFICE_NAME = "SELECT OFC.OFFICE_NAME, DISTT.H_DISTRICT_NAME, TEHS.H_TEHSIL_NAME FROM IGRS_OFFICE_MASTER OFC,IGRS_DISTRICT_MASTER DISTT, " +
			"IGRS_TEHSIL_MASTER TEHS WHERE OFC.OFFICE_ID = ? AND OFC.DISTRICT_ID = DISTT.DISTRICT_ID AND OFC.TEHSIL_ID = TEHS.TEHSIL_ID";
	
	public static final String GET_OFFICE_NAME_HI = "SELECT OFC.H_OFFICE_NAME, DISTT.H_DISTRICT_NAME, TEHS.H_TEHSIL_NAME FROM IGRS_OFFICE_MASTER OFC,IGRS_DISTRICT_MASTER DISTT, " +
	"IGRS_TEHSIL_MASTER TEHS WHERE OFC.OFFICE_ID = ? AND OFC.DISTRICT_ID = DISTT.DISTRICT_ID AND OFC.TEHSIL_ID = TEHS.TEHSIL_ID";
	
	public static final String INSERT_EXECUTION_SEAL_1 = "INSERT ALL INTO IGRS_REG_SEALS_PARENT_TXN (SEAL_TXN_ID,REG_TXN_ID,SEAL_SUB_ID,SEAL_DATE,SR_NAME,DESIGNATION,SRO,DISTRICT," +
			"TEHSIL_NAME,FINAL_CONTENT,TYPE_OF_AMOUNT_RECIEVED,CONSIDERATION_AMOUNT," +
			"AMOUNT_PAID_IN_SR_PRESENCE,AMOUNT_TO_BE_PAID)VALUES " +
			"(?,?,?,SYSDATE,?,?,OFFICE_NAME,DISTRICT_NAME,TEHSIL_NAME,?,?,?,?,?) " +
			"(SELECT OFC.OFFICE_NAME, DISTT.DISTRICT_NAME, TEHS.TEHSIL_NAME FROM IGRS_OFFICE_MASTER OFC," +
			"IGRS_DISTRICT_MASTER DISTT,IGRS_TEHSIL_MASTER TEHS WHERE OFC.OFFICE_ID = ? AND " +
			"OFC.DISTRICT_ID = DISTT.DISTRICT_ID AND TEHS.TEHSIL_ID = OFC.TEHSIL_ID)";
	
	public static final String GET_WITNESS_DETAILS = "SELECT distinct b.REG_TXN_ID,b.WITNESS_FIRST_NAME,b.WITNESS_LAST_NAME," +
			"b.WITNESS_TXN_NUM FROM IGRS_REG_TXN_WITNESS_DTLS b WHERE b.REG_TXN_ID=? AND DELETED_FLAG = '0' ";
	
	public static final String GET_CONSENTER_DETAILS = "SELECT distinct b.REG_TXN_ID,b.CONSENTER_FIRST_NAME,b.CONSENTER_LAST_NAME," +
	"b.CONSENTER_TXN_NUM FROM IGRS_REG_CONSENTER_DETAILS b WHERE b.REG_TXN_ID=? AND DELETED_FLAG = '0' ";
	
	public static final String INSERT_WITNESS_DETAILS_PRESENTATION = "INSERT INTO IGRS_REG_SEALS_CHILD_TXN(REG_CHILD_ID,SEAL_TXN_ID,PARTY_TYPE,PARTY_ID)" +
	"VALUES(IGRS_REG_SEALS_CHILD_SEQ.NEXTVAL,?,'W',?)";
	
	public static final String INSERT_CONSENTER_DETAILS_PRESENTATION = "INSERT INTO IGRS_REG_SEALS_CHILD_TXN(REG_CHILD_ID,SEAL_TXN_ID,PARTY_TYPE,PARTY_ID)" +
	"VALUES(IGRS_REG_SEALS_CHILD_SEQ.NEXTVAL,?,'C',?)";
	
	public static final String GET_DEED_DUTY_DETAILS = "SELECT c.DEED_TYPE_NAME,b.STAMP_DUTY,c.H_DEED_TYPE_NAME FROM IGRS_REG_TXN_DETLS a,IGRS_REG_CHK_STAMP_DUTY_DTLS b,IGRS_DEED_TYPE_MASTER c" +
			" WHERE a.REG_TXN_ID = ? and a.REG_TXN_ID = b.REG_TXN_ID and c.DEED_TYPE_ID = a.DEED_ID";
	
	public static final String INSERT_ADJUDICATION_SEAL_DETAILS = "INSERT ALL INTO IGRS_REG_SEALS_PARENT_TXN (SEAL_TXN_ID,REG_TXN_ID,SEAL_SUB_ID,SEAL_DATE,SR_NAME," +
			"DESIGNATION,SRO,DISTRICT, TEHSIL_NAME,FINAL_CONTENT,NAME_OF_PAKASHKAAR,OTHER_DETAILS, " +
			"DEED_TYPE)VALUES (?,?,?,SYSDATE,?,?,OFFICE_NAME,DISTRICT_NAME,TEHSIL_NAME,?,?,?,?) " +
			"(SELECT OFC.OFFICE_NAME, DISTT.DISTRICT_NAME, TEHS.TEHSIL_NAME FROM " +
			"IGRS_OFFICE_MASTER OFC, IGRS_DISTRICT_MASTER DISTT,IGRS_TEHSIL_MASTER TEHS WHERE" +
			" OFC.OFFICE_ID = ? AND OFC.DISTRICT_ID = DISTT.DISTRICT_ID AND TEHS.TEHSIL_ID = OFC.TEHSIL_ID)";
	
	public static final String INSERT_POA_DETAILS = "INSERT ALL INTO IGRS_REG_SEALS_PARENT_TXN (SEAL_TXN_ID,REG_TXN_ID,SEAL_SUB_ID,SEAL_DATE," +
			"SR_NAME, DESIGNATION,SRO,DISTRICT, TEHSIL_NAME,FINAL_CONTENT,NAME_PERSON_AT_MAUZA,ADDRESS_PERSON_AT_MAUZA)" +
			"VALUES(?,?,?,SYSDATE,?,?,OFFICE_NAME,DISTRICT_NAME,TEHSIL_NAME,?,?,?)" +
			"(SELECT OFC.OFFICE_NAME, DISTT.DISTRICT_NAME, TEHS.TEHSIL_NAME FROM IGRS_OFFICE_MASTER OFC, " +
			"IGRS_DISTRICT_MASTER DISTT,IGRS_TEHSIL_MASTER TEHS WHERE OFC.OFFICE_ID = ? AND " +
			"OFC.DISTRICT_ID = DISTT.DISTRICT_ID AND TEHS.TEHSIL_ID = OFC.TEHSIL_ID)";
	
	public static final String INSERT_POA_VISIT_DETAILS = "INSERT ALL INTO IGRS_REG_SEALS_PARENT_TXN (SEAL_TXN_ID,REG_TXN_ID,SEAL_SUB_ID," +
			"SEAL_DATE, SR_NAME, DESIGNATION,SRO,DISTRICT, TEHSIL_NAME,FINAL_CONTENT,NAME_PRINCIPAL,ADDRESS_PRINCIPAL," +
			"SERIAL_NO) VALUES" +
			"(?,?,?,SYSDATE,?,?,OFFICE_NAME,DISTRICT_NAME,TEHSIL_NAME,?,?,?,?)" +
			"(SELECT OFC.OFFICE_NAME, DISTT.DISTRICT_NAME, TEHS.TEHSIL_NAME FROM IGRS_OFFICE_MASTER OFC," +
			"IGRS_DISTRICT_MASTER DISTT,IGRS_TEHSIL_MASTER TEHS " +
			"WHERE OFC.OFFICE_ID = ? AND OFC.DISTRICT_ID = DISTT.DISTRICT_ID AND TEHS.TEHSIL_ID = OFC.TEHSIL_ID)";
	
	public static final String INSERT_POA_COMM_DETAILS = "INSERT ALL INTO IGRS_REG_SEALS_PARENT_TXN (SEAL_TXN_ID,REG_TXN_ID,SEAL_SUB_ID,SEAL_DATE," +
			" SR_NAME, DESIGNATION,SRO,DISTRICT, TEHSIL_NAME,FINAL_CONTENT,COMMISSIONER_NAME," +
			"COMMISSIONER_ADDRESS,POA_NAME,SERIAL_NO) VALUES" +
			"(?,?,?,SYSDATE,?,?,OFFICE_NAME,DISTRICT_NAME,TEHSIL_NAME,?,?,?,?,?)" +
			"(SELECT OFC.OFFICE_NAME, DISTT.DISTRICT_NAME, TEHS.TEHSIL_NAME FROM IGRS_OFFICE_MASTER OFC," +
			"IGRS_DISTRICT_MASTER DISTT,IGRS_TEHSIL_MASTER TEHS WHERE OFC.OFFICE_ID = ? AND " +
			"OFC.DISTRICT_ID = DISTT.DISTRICT_ID AND TEHS.TEHSIL_ID = OFC.TEHSIL_ID)";
	
	public static final String INSERT_POA_DETAILS_FINAL = "INSERT ALL INTO IGRS_REG_SEALS_PARENT_TXN (SEAL_TXN_ID,REG_TXN_ID,SEAL_SUB_ID,SEAL_DATE," +
			"SR_NAME, DESIGNATION,SRO,DISTRICT, TEHSIL_NAME,FINAL_CONTENT,POA_NUMBER) VALUES" +
			" (?,?,?,SYSDATE,?,?,OFFICE_NAME,DISTRICT_NAME,TEHSIL_NAME,?,?)" +
			"(SELECT OFC.OFFICE_NAME, DISTT.DISTRICT_NAME, TEHS.TEHSIL_NAME FROM IGRS_OFFICE_MASTER OFC," +
			"IGRS_DISTRICT_MASTER DISTT,IGRS_TEHSIL_MASTER TEHS WHERE OFC.OFFICE_ID = ? " +
			"AND OFC.DISTRICT_ID = DISTT.DISTRICT_ID AND TEHS.TEHSIL_ID = OFC.TEHSIL_ID)";
	
	public static final String INSERT_EXECUTION_SEAL_7 = "INSERT ALL INTO IGRS_REG_SEALS_PARENT_TXN " +
			"(SEAL_TXN_ID,REG_TXN_ID,SEAL_SUB_ID,SEAL_DATE,SR_NAME,DESIGNATION,SRO,DISTRICT, TEHSIL_NAME," +
			"FINAL_CONTENT,COMMISSIONER_NAME,ORDER_NUMBER,DATE_OF_ORDER)VALUES" +
			" (?,?,?,SYSDATE,?,?,OFFICE_NAME,DISTRICT_NAME,TEHSIL_NAME,?,?,?,to_date(?,'dd/mm/yyyy'))" +
			"(SELECT OFC.OFFICE_NAME, DISTT.DISTRICT_NAME, TEHS.TEHSIL_NAME FROM IGRS_OFFICE_MASTER OFC, " +
			"IGRS_DISTRICT_MASTER DISTT,IGRS_TEHSIL_MASTER TEHS WHERE OFC.OFFICE_ID = ? AND " +
			"OFC.DISTRICT_ID = DISTT.DISTRICT_ID AND TEHS.TEHSIL_ID = OFC.TEHSIL_ID)";
	
	public static final String INSERT_REPORT_COMMISSIONER = "INSERT ALL INTO IGRS_REG_SEALS_PARENT_TXN " +
			"(SEAL_TXN_ID,REG_TXN_ID,SEAL_SUB_ID,SEAL_DATE,SR_NAME,DESIGNATION,SRO,DISTRICT, TEHSIL_NAME, " +
			"FINAL_CONTENT,COMMISSIONER_NAME)VALUES (?,?,?,SYSDATE,?,?,OFFICE_NAME,DISTRICT_NAME,TEHSIL_NAME,?,?)" +
			"(SELECT OFC.OFFICE_NAME, DISTT.DISTRICT_NAME, TEHS.TEHSIL_NAME FROM " +
			"IGRS_OFFICE_MASTER OFC,IGRS_DISTRICT_MASTER DISTT,IGRS_TEHSIL_MASTER TEHS WHERE" +
			" OFC.OFFICE_ID = ? AND OFC.DISTRICT_ID = DISTT.DISTRICT_ID AND TEHS.TEHSIL_ID = OFC.TEHSIL_ID)";
	
	public static final String GET_STAMP_DUTY_DETLS = "SELECT STAMP_DUTY,GRAM_DUTY,NAGAR_DUTY,UPKAR,TOTAL FROM " +
			"IGRS_REG_CHK_STAMP_DUTY_DTLS WHERE REG_TXN_ID = ?";
	
	public static final String INSERT_EXECUTION_SEAL_WILL = "INSERT ALL INTO IGRS_REG_SEALS_PARENT_TXN " +
			"(SEAL_TXN_ID,REG_TXN_ID,SEAL_SUB_ID,SEAL_DATE,SR_NAME,DESIGNATION,SRO,DISTRICT,TEHSIL_NAME," +
			"FINAL_CONTENT,PAGE_OF_MINUTE_BOOK)VALUES " +
			"(?,?,?,SYSDATE,?,?,OFFICE_NAME,DISTRICT_NAME,TEHSIL_NAME,?,?)" +
			"(SELECT OFC.OFFICE_NAME, DISTT.DISTRICT_NAME, TEHS.TEHSIL_NAME FROM " +
			"IGRS_OFFICE_MASTER OFC,IGRS_DISTRICT_MASTER DISTT,IGRS_TEHSIL_MASTER TEHS" +
			" WHERE OFC.OFFICE_ID = ? AND OFC.DISTRICT_ID = DISTT.DISTRICT_ID AND " +
			"TEHS.TEHSIL_ID = OFC.TEHSIL_ID)";
	
	public static final String GET_REG_SEAL_DETAILS = "SELECT TOTAL, REG_FEE FROM IGRS_REG_CHK_STAMP_DUTY_DTLS WHERE REG_TXN_ID = ?";
	
	//Modified for Minor Guardian, POA , deed flag for Will Authenticaed POA- Rahul
	
	/*public static final String GET_PARTY_DETAILS_FOR_PRESENTATION_SEAL = "SELECT PARTY_FIRST_NAME,PARTY_MIDDLE_NAME,PARTY_LAST_NAME," +
			"AUTHRZD_PERSN_NAME,ORGANIZATION_NAME,GUARDIAN_NAME,PHOTO_FILEPATH,SIGN_FILE_PATH,FIMGER_PRINT_FILE_PATH,PARTY_ADDRESS,(select relation_type_name from IGRS_RELATION_TYPE_MASTER where RELATION_TYPE_ID=PT.RELATION_TYPE_ID),APPELLATE_TYPE_ID,NAME_OF_OFFICIAL,ADRS_OF_OFFICIAL,PT.PARTY_TXN_ID, PARTY_AGE,GUARDIAN_NAME  FROM " +
			"IGRS_REG_TXN_PARTY_DETLS PT,IGRS_REG_TXN_PARTY_OTHER_DTLS PO WHERE PT.PARTY_TXN_ID IN(";*/
	public static final String GET_PARTY_DETAILS_FOR_PRESENTATION_SEAL = "SELECT PARTY_FIRST_NAME,PARTY_MIDDLE_NAME,PARTY_LAST_NAME," +
	"AUTHRZD_PERSN_NAME,ORGANIZATION_NAME,GUARDIAN_NAME,PHOTO_FILEPATH,SIGN_FILE_PATH,FIMGER_PRINT_FILE_PATH,PARTY_ADDRESS,RELATION_TYPE_ID,APPELLATE_TYPE_ID,NAME_OF_OFFICIAL,ADRS_OF_OFFICIAL,PT.PARTY_TXN_ID, PARTY_AGE,GUARDIAN_NAME,PT.MINOR_GUARDIAN,PT.PARTY_TYPE_ID,PT.UNIVERSAL_DEED_CLAIMANT_FLAG   FROM " +
	"IGRS_REG_TXN_PARTY_DETLS PT,IGRS_REG_TXN_PARTY_OTHER_DTLS PO WHERE PT.PARTY_TXN_ID IN(";
	
	/*public static final String GET_PARTY_DETAILS_FOR_PRESENTATION_SEAL_HI = "SELECT PARTY_FIRST_NAME,PARTY_MIDDLE_NAME,PARTY_LAST_NAME," +
	"AUTHRZD_PERSN_NAME,ORGANIZATION_NAME,GUARDIAN_NAME,PHOTO_FILEPATH,SIGN_FILE_PATH,FIMGER_PRINT_FILE_PATH,PARTY_ADDRESS,(select h_relation_type_name from IGRS_RELATION_TYPE_MASTER where RELATION_TYPE_ID=PT.RELATION_TYPE_ID),APPELLATE_TYPE_ID,NAME_OF_OFFICIAL,ADRS_OF_OFFICIAL,PT.PARTY_TXN_ID, PARTY_AGE,GUARDIAN_NAME FROM " +
	"IGRS_REG_TXN_PARTY_DETLS PT,IGRS_REG_TXN_PARTY_OTHER_DTLS PO WHERE PT.PARTY_TXN_ID IN(";*/
	// Above commented and modified for POA , deed flag for Authenticated POA - RAhul
	public static final String GET_PARTY_DETAILS_FOR_PRESENTATION_SEAL_HI = "SELECT PARTY_FIRST_NAME,PARTY_MIDDLE_NAME,PARTY_LAST_NAME," +
	"AUTHRZD_PERSN_NAME,ORGANIZATION_NAME,GUARDIAN_NAME,PHOTO_FILEPATH,SIGN_FILE_PATH,FIMGER_PRINT_FILE_PATH,PARTY_ADDRESS,RELATION_TYPE_ID,APPELLATE_TYPE_ID,NAME_OF_OFFICIAL,ADRS_OF_OFFICIAL,PT.PARTY_TXN_ID, PARTY_AGE,GUARDIAN_NAME,PT.MINOR_GUARDIAN,PT.PARTY_TYPE_ID,PT.UNIVERSAL_DEED_CLAIMANT_FLAG  FROM " +
	"IGRS_REG_TXN_PARTY_DETLS PT,IGRS_REG_TXN_PARTY_OTHER_DTLS PO WHERE PT.PARTY_TXN_ID IN(";
	
	public static final String GET_PARTY_DETAILS_FOR_PRESENTATION_SEAL_SECOND = " ) AND PT.PARTY_OTHER_DETLS_ID = PO.PARTY_OTHER_DETLS_ID ";
	
	public static final String GET_SEAL_DETAILS_FOR_REGISTRATION = "SELECT DISTINCT SEAL_SUB_ID FROM IGRS_REG_SEALS_PARENT_TXN WHERE REG_TXN_ID = ? AND SEAL_APPLIED='Y'";
	
	public static final String GET_WITNESS_DETL_FOR_THUMB_SEAL = "SELECT WITNESS_FIRST_NAME,WITNESS_MIDDLE_NAME,WITNESS_LAST_NAME, " +
			"FATHER_NAME,WITNESS_ADDRESS,PHOTO_FILEPATH,SIGN_FILE_PATH,FIMGER_PRINT_FILE_PATH,RL.relation_type_name,PT.WITNESS_TXN_NUM FROM IGRS_REG_TXN_WITNESS_DTLS PT,IGRS_REG_TXN_PARTY_OTHER_DTLS PO,  IGRS_RELATION_TYPE_MASTER RL  " +
			"WHERE PT.WITNESS_TXN_NUM IN(";
	
	public static final String GET_WITNESS_DETL_FOR_THUMB_SEAL_HI = "SELECT WITNESS_FIRST_NAME,WITNESS_MIDDLE_NAME,WITNESS_LAST_NAME, " +
	"FATHER_NAME,WITNESS_ADDRESS,PHOTO_FILEPATH,SIGN_FILE_PATH,FIMGER_PRINT_FILE_PATH,RL.h_relation_type_name,PT.WITNESS_TXN_NUM FROM IGRS_REG_TXN_WITNESS_DTLS PT,IGRS_REG_TXN_PARTY_OTHER_DTLS PO,  IGRS_RELATION_TYPE_MASTER RL  " +
	"WHERE PT.WITNESS_TXN_NUM IN(";
	
	public static final String GET_WITNESS_DETL_FOR_THUMB_SEAL_SEC = " ) AND PT.PARTY_OTHER_DETLS_ID = PO.PARTY_OTHER_DETLS_ID AND PT.RELATION_TYPE_ID = RL.RELATION_TYPE_ID";
	
	public static final String GET_CONSENTER_DETL_FOR_THUMB_SEAL = "SELECT CONSENTER_FIRST_NAME,CONSENTER_MIDDLE_NAME,CONSENTER_LAST_NAME," +
			" FATHER_NAME,CONSENTER_ADDRESS,PHOTO_FILEPATH,SIGN_FILE_PATH,FIMGER_PRINT_FILE_PATH,RL.relation_type_name,PT.CONSENTER_TXN_NUM FROM IGRS_REG_CONSENTER_DETAILS PT," +
			"IGRS_REG_TXN_PARTY_OTHER_DTLS PO,IGRS_RELATION_TYPE_MASTER RL WHERE PT.CONSENTER_TXN_NUM IN( ";
	
	public static final String GET_CONSENTER_DETL_FOR_THUMB_SEAL_HI = "SELECT CONSENTER_FIRST_NAME,CONSENTER_MIDDLE_NAME,CONSENTER_LAST_NAME," +
	" FATHER_NAME,CONSENTER_ADDRESS,PHOTO_FILEPATH,SIGN_FILE_PATH,FIMGER_PRINT_FILE_PATH,RL.h_relation_type_name,PT.CONSENTER_TXN_NUM FROM IGRS_REG_CONSENTER_DETAILS PT," +
	"IGRS_REG_TXN_PARTY_OTHER_DTLS PO,IGRS_RELATION_TYPE_MASTER RL WHERE PT.CONSENTER_TXN_NUM IN( ";

	public static final String GET_CONSENTER_DETL_FOR_THUMB_SEAL_SEC = " ) AND PT.PARTY_OTHER_DETLS_ID = PO.PARTY_OTHER_DETLS_ID AND PT.RELATION_TYPE_ID = RL.RELATION_TYPE_ID";
	
	public static final String GET_OFFICE_DETAIL = "SELECT OFFICE_NAME FROM IGRS_OFFICE_MASTER WHERE OFFICE_ID = ?";
	
	public static final String GET_STAMP_DUTY = "SELECT STAMP_DUTY FROM IGRS_REG_CHK_STAMP_DUTY_DTLS WHERE REG_TXN_ID = ?";
	
	public static final String INSERT_COMMON_SEAL_DATA = "INSERT  INTO IGRS_REG_SEALS_PARENT_TXN" +
	"(SEAL_TXN_ID,REG_TXN_ID,SEAL_SUB_ID,SEAL_DATE)VALUES" +
	"(IGRS_REG_SEALS_PARENT_SEQ.NEXTVAL,?,?,SYSDATE)";
	public static final String UPDATE_COMMON_SEAL_DATA="UPDATE IGRS_REG_SEALS_PARENT_TXN set SERIAL_NO=? where REG_TXN_ID=? and SEAL_SUB_ID=? "; 
	
	public static final String GET_DESIGNATION_DETLS = "select cadre_name from igrs_emp_cadre_master C where " +
			"C.cadre_id=(select emp_designation_id from igrs_emp_official_details where emp_id=?)";
	
	public static final String GET_PROP_IMAGES = "SELECT ANGLE_1_PATH , ANGLE_2_PATH, ANGLE_3_PATH, MAP_PATH FROM IGRS_REG_PROPRTY_DTLS PROP, IGRS_REG_TXN_DETLS REG " +
			"WHERE REG.REG_TXN_ID = PROP.REG_TXN_ID AND REG.REG_TXN_ID = ?";
	
	public static final String GET_OFFC_NAME = "select office_name from igrs_office_master where office_id = ?";
	
	public static final String GET_OFFC_NAME_HI = "select h_office_name from igrs_office_master where office_id = ?";

	public static final String UPDATE_APPLY_SEAL="UPDATE IGRS_REG_SEALS_PARENT_TXN set SEAL_APPLIED=? where REG_TXN_ID=? and SEAL_SUB_ID=?"; 

	public static final String UPDATE_APPLY_SEAL_DATA="UPDATE IGRS_REG_TXN_DETLS set LATEST_SEAL_TYPE=? where REG_TXN_ID=?"; 
	
	public static final String UPDATE_BOOK_TYPE_DATA="UPDATE IGRS_REG_TXN_DETLS R set R.BOOK_TYPE_ID=(SELECT BOOK_TYPE_ID FROM IGRS_DEED_INSTRUMENT_MASTER WHERE INSTRUMENT_ID=R.INSTRUMENTS_ID ) where REG_TXN_ID=?"; 

	public static final String UPDATE_BOOK_TYPE_DATA_RULE="UPDATE IGRS_REG_TXN_DETLS R set R.BOOK_TYPE_ID=? where R.REG_TXN_ID=?"; 

	public static final String UPDATE_COMP_DATA="UPDATE IGRS_REG_TXN_DETLS R set R.REG_COMP_DATE=systimestamp where R.REG_TXN_ID=?"; 

	public static final String GET_SEALS_FLAG = "SELECT LATEST_SEAL_TYPE FROM IGRS_REG_TXN_DETLS where REG_TXN_ID=?";

	public static final String GET_SEAL_WITNESS_THUMB_DATE = "SELECT TO_CHAR(P.THUMB_TIME,'DD/MM/YYYY') FROM IGRS_REG_TXN_PARTY_OTHER_DTLS P,IGRS_REG_TXN_WITNESS_DTLS R where P.PARTY_OTHER_DETLS_ID=R.PARTY_OTHER_DETLS_ID and R.WITNESS_TXN_NUM=?";

	public static final String GET_SEAL_PARTY_THUMB_DATE = "SELECT TO_CHAR(P.THUMB_TIME,'DD/MM/YYYY') FROM IGRS_REG_TXN_PARTY_OTHER_DTLS P,IGRS_REG_TXN_PARTY_DETLS R where P.PARTY_OTHER_DETLS_ID=R.PARTY_OTHER_DETLS_ID and R.PARTY_TXN_ID=?";

	public static final String GET_SEAL_CONSENTER_THUMB_DATE = "SELECT TO_CHAR(P.THUMB_TIME,'DD/MM/YYYY') FROM IGRS_REG_TXN_PARTY_OTHER_DTLS P,IGRS_REG_CONSENTER_DETAILS R where P.PARTY_OTHER_DETLS_ID=R.PARTY_OTHER_DETLS_ID and R.CONSENTER_TXN_NUM=?";

}
