package com.wipro.igrs.conReport.sql;


/**
 * ===========================================================================
 * File           :   CommonSQL.java
 * Description    :   Represents the Common SQL Class ECR
 * @author        :   Imran Shaik
 * Created Date   :   September 08, 2008
 * ===========================================================================
 */


public class CommonSQL {
	public static final String SELECT_FISCAL_YEAR =
		"SELECT FISCAL_YEAR_ID,FISCAL_YEAR FROM IGRS_FISCAL_YEAR";
	public static final String SELECT_EMP_DETAILS =
		"SELECT FIRST_NAME,MIDDLE_NAME,LAST_NAME,TO_CHAR(TO_DATE(trunc(DATE_OF_JOINING),'DD-MM-RRRR'),'DD-MM-RRRR'),TO_CHAR(TO_DATE(trunc(DATE_OF_BIRTH),'DD-MM-RRRR'),'DD-MM-RRRR'),GENDER FROM IGRS_EMP_MASTER WHERE EMP_ID='";
	public static final String SELECT_SUPER_DETAILS =
		"SELECT RPT.EMP_SUPERVISOR_ID FROM IGRS_EMP_RPTMGR_MASTER RPT WHERE RPT.EMP_ID=?";
	public static final String SELECT_REVIEWER_DETAILS =
		"SELECT RPT.EMP_REVIEWER_ID FROM  IGRS_EMP_RPTMGR_MASTER RPT WHERE RPT.EMP_ID=?";
    public static final String INSERT_EMP_CON_REPORT = 
        "INSERT INTO IGRS_EMP_CONFIDENTIAL_RPT_DTLS DT (DT.CON_REPORT_ID,DT.EMP_ID,DT.FISCAL_YEAR_ID,DT.REPORT_STATUS,DT.SUPERVISOR_ID,DT.REVIEWER_ID) VALUES(?,?,?,?,?,?)";
    public static final String INSERT_EMP_CON_REPORT_MAP = 
    	"INSERT INTO IGRS_EMP_CONFIDENTIAL_RPT_MAP M (M.CON_REPORT_ID,M.EMP_COMMENTS,M.EMP_COMMENTS_DATE)VALUES(?,?,SYSDATE)";
    public static final String UPDATE_EMP_CON_REPORT = 
        "UPDATE IGRS_EMP_CONFIDENTIAL_RPT_DTLS DT SET DT.REPORT_STATUS=?,DT.FISCAL_YEAR_ID=? WHERE DT.CON_REPORT_ID=?";
    public static final String UPDATE_EMP_CON_REPORT_MAP = 
    	"UPDATE IGRS_EMP_CONFIDENTIAL_RPT_MAP M SET M.EMP_COMMENTS=?,M.EMP_COMMENTS_DATE=SYSDATE WHERE M.CON_REPORT_ID=?";
    public static final String SELECT_EMP_CON_REP_BY_EMP =
    	"SELECT DT.CON_REPORT_ID,DT.EMP_ID,F.FISCAL_YEAR,DT.REPORT_STATUS FROM IGRS_EMP_CONFIDENTIAL_RPT_DTLS DT,IGRS_FISCAL_YEAR F WHERE F.FISCAL_YEAR_ID=DT.FISCAL_YEAR_ID AND DT.EMP_ID=?";
    public static final String SELECT_EMP_CON_REP_BY_SUSERVISOR =
    	//"SELECT DT.CON_REPORT_ID,DT.EMP_ID,F.FISCAL_YEAR,DT.REPORT_STATUS FROM IGRS_EMP_CONFIDENTIAL_RPT_DTLS DT,IGRS_EMP_RPTMGR_MASTER RPT,IGRS_FISCAL_YEAR F WHERE DT.EMP_ID=RPT.EMP_ID AND F.FISCAL_YEAR_ID=DT.FISCAL_YEAR_ID AND  RPT.EMP_SUPERVISOR_ID=?";
    	"SELECT DT.CON_REPORT_ID,DT.EMP_ID,F.FISCAL_YEAR,DT.REPORT_STATUS FROM IGRS_EMP_CONFIDENTIAL_RPT_DTLS DT,IGRS_FISCAL_YEAR F WHERE F.FISCAL_YEAR_ID=DT.FISCAL_YEAR_ID AND DT.SUPERVISOR_ID=?";
    public static final String SELECT_EMP_CON_REP_BY_REVIEWER =
    	"SELECT DT.CON_REPORT_ID,DT.EMP_ID,F.FISCAL_YEAR,DT.REPORT_STATUS FROM IGRS_EMP_CONFIDENTIAL_RPT_DTLS DT,IGRS_FISCAL_YEAR F WHERE F.FISCAL_YEAR_ID=DT.FISCAL_YEAR_ID AND DT.REVIEWER_ID=?";
    public static final String SELECT_CON_DETAILS =
    	"SELECT DT.CON_REPORT_ID,DT.EMP_ID,F.FISCAL_YEAR,DT.REPORT_STATUS,M.EMP_COMMENTS FROM IGRS_EMP_CONFIDENTIAL_RPT_MAP M,IGRS_EMP_CONFIDENTIAL_RPT_DTLS DT,IGRS_EMP_RPTMGR_MASTER RPT,IGRS_FISCAL_YEAR F WHERE DT.EMP_ID=RPT.EMP_ID AND F.FISCAL_YEAR_ID=DT.FISCAL_YEAR_ID AND DT.CON_REPORT_ID=M.CON_REPORT_ID AND DT.CON_REPORT_ID=?";
    public static final String INSERT_SUPER_CON_REPORT =
        //"UPDATE IGRS_EMP_CONFIDENTIAL_RPT_MAP M,IGRS_EMP_CONFIDENTIAL_RPT_DTLS DT SET DT.REPORT_STATUS=?,DT.REMARKS_DATE=SYSDATE,M.SUPERVISOR_COMMENTS=?,M.SUPERVISOR_COMMENTS_DATE=SYSDATE,DT.SUPERVISOR_REMARKS=?,M.SUPERVISOR_ID=? WHERE DT.CON_REPORT_ID=M.CON_REPORT_ID AND DT.CON_REPORT_ID=?";
    	"UPDATE IGRS_EMP_CONFIDENTIAL_RPT_DTLS DT SET DT.REPORT_STATUS=?,DT.REMARKS_DATE=SYSDATE,DT.SUPERVISOR_REMARKS=? WHERE DT.CON_REPORT_ID=?";
    public static final String INSERT_SUPER_CON_REPORT_MAP =
    	"UPDATE IGRS_EMP_CONFIDENTIAL_RPT_MAP M SET M.SUPERVISOR_COMMENTS=?,M.SUPERVISOR_COMMENTS_DATE=SYSDATE,M.SUPERVISOR_ID=? WHERE M.CON_REPORT_ID=?";
    public static final String INSERT_REVIEWER_CON_REPORT =
    	"UPDATE IGRS_EMP_CONFIDENTIAL_RPT_DTLS DT SET DT.REPORT_STATUS=?,DT.REVIEWER_REMARKS_DATE=SYSDATE,DT.REVIEWER_REMARKS=? WHERE DT.CON_REPORT_ID=?";
    public static final String INSERT_REVIEWER_CON_REPORT_MAP =
    	"UPDATE IGRS_EMP_CONFIDENTIAL_RPT_MAP M SET M.REVIEWER_COMMENTS=?,M.REVIEWER_COMMENTS_DATE=SYSDATE,M.REVIEWER_ID=? WHERE M.CON_REPORT_ID=?";
    public static final String SELECT_EMP_CON_REPORT =
    	"SELECT DT.REPORT_STATUS,M.EMP_COMMENTS_DATE,M.EMP_COMMENTS,DT.FISCAL_YEAR_ID FROM IGRS_EMP_CONFIDENTIAL_RPT_DTLS DT,IGRS_EMP_CONFIDENTIAL_RPT_MAP M WHERE DT.CON_REPORT_ID=M.CON_REPORT_ID AND DT.CON_REPORT_ID=?";
    public static final String SELECT_SUPER_CON_REPORT =
    	"SELECT DT.REPORT_STATUS,DT.SUPERVISOR_REMARKS,M.SUPERVISOR_COMMENTS FROM IGRS_EMP_CONFIDENTIAL_RPT_DTLS DT,IGRS_EMP_CONFIDENTIAL_RPT_MAP M WHERE DT.CON_REPORT_ID=M.CON_REPORT_ID AND DT.CON_REPORT_ID=?";
    public static final String SELECT_REVIEWER_CON_REPORT =
    	"SELECT DT.REPORT_STATUS,DT.REVIEWER_REMARKS,M.REVIEWER_COMMENTS FROM IGRS_EMP_CONFIDENTIAL_RPT_DTLS DT,IGRS_EMP_CONFIDENTIAL_RPT_MAP M WHERE DT.CON_REPORT_ID=M.CON_REPORT_ID AND DT.CON_REPORT_ID=?";
}
