/* 
* File Name:- CommonSQL.java
* Copyright (c) 2006-2008 WIPRO. All Rights Reserved.
*
*  This software is the confidential and proprietary information of WIPRO
*  ("Confidential Information"). You shall not
*  disclose such Confidential Information and shall use it only in
*  accordance with the terms of the license agreement you entered into
*  with WIPRO.
*
* WIPRO MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE
* SUITABILITY OF THE SOFTWARE, EITHER EXPRESS OR IMPLIED,
* INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
* MERCHANTABILITY, FITNESS FOR A
* PARTICULAR PURPOSE, OR NON-INFRINGEMENT. WIPRO SHALL NOT BE
* LIABLE FOR ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF
* USING, MODIFYING OR DISTRIBUTING THIS SOFTWARE OR ITS
* DERIVATIVES.
*
*/


package com.wipro.igrs.commonEfiling;


/**
 * 
 * @author madhaty
 *
 */
public class CommonSQL {

	/**
	 * @author Madan Mohan
	 */
	public static final String COUNTRY_QUERY = "Select COUNTRY_ID, "
        		+ "COUNTRY_NAME from IGRS_COUNTRY_MASTER "
        		+"WHERE COUNTRY_STATUS='A' ORDER BY COUNTRY_NAME ASC";
	/**
	 * @author Madan Mohan
	 */
	public static final String STATE_QUERY = "Select STATE_ID, "
				+"STATE_NAME from IGRS_STATE_MASTER "
				+"Where  STATE_STATUS='A' AND COUNTRY_ID=? ORDER BY STATE_NAME ASC";
	/**
	 * @author Madan Mohan
	 */
	public static final String DISTRICT_QUERY = "Select DISTRICT_ID, "
				+"DISTRICT_NAME from IGRS_DISTRICT_MASTER "
				+" Where STATE_ID=? AND DISTRICT_STATUS='A' "
				+"ORDER BY DISTRICT_NAME ASC";
	
	//added by shruti 25 nov 2014
	
	public static final String REG_DISTRICT_QUERY = "Select DISTRICT_ID, "
		+"DISTRICT_NAME from IGRS_DISTRICT_MASTER "
		+" Where STATE_ID=? AND DISTRICT_STATUS='A' "
		+"ORDER BY DISTRICT_NAME ASC";
	
	public static final String REG_DISTRICT_QUERY_H = "Select DISTRICT_ID, "
		+"H_DISTRICT_NAME from IGRS_DISTRICT_MASTER "
		+" Where STATE_ID=? AND DISTRICT_STATUS='A' "
		+"ORDER BY DISTRICT_NAME ASC";
	
	/**
	 * @author Madan Mohan
	 */
	public static final String ZONE_QUERY = "Select ZONE_ID, "
				+"ZONE_NAME from IGRS_ZONE_MASTER "
				+" Where STATE_ID=? AND ZONE_STATUS='A' "
				+"ORDER BY ZONE_NAME ASC";
	/**
	 * @author Madan Mohan
	 */
	public static final String TEHSIL_QUERY = "Select  TEHSIL_ID, "
			    +"TEHSIL_NAME from IGRS_TEHSIL_MASTER "
			    +"Where DISTRICT_ID=? AND TEHSIL_STATUS='A' "
			    +"ORDER BY TEHSIL_NAME ASC";
	
	//added by shruti--25 nov 2014
	public static final String REG_TEHSIL_QUERY = "Select  TEHSIL_ID, "
	    +"TEHSIL_NAME from IGRS_TEHSIL_MASTER "
	    +"Where DISTRICT_ID=? AND TEHSIL_STATUS='A' "
	    +"ORDER BY TEHSIL_NAME ASC";
	
	public static final String REG_TEHSIL_QUERY_H = "Select  TEHSIL_ID, "
	    +"H_TEHSIL_NAME from IGRS_TEHSIL_MASTER "
	    +"Where DISTRICT_ID=? AND TEHSIL_STATUS='A' "
	    +"ORDER BY TEHSIL_NAME ASC";
	//end
	
	/**
	 * @author Madan Mohan
	 */
	public static final String GUIDELINE_DURATION = "Select DISTINCT to_date(DURATION_TO,'dd/mm/yy') " +
			" from IGRS_GUIDELINE_MASTER_PARENT " +
			"Where DISTRICT_ID=?";
	

	/**
	 * @author Madan Mohan
	 */
	public static final String GUIDELINE_VALUE_PROP =" SELECT g2.guideline_value "+
	"FROM IGRS_GUIDELINE_master_parent g,IGRS_GUIDELINE_master_CHILD1 g1 ,IGRS_GUIDElINE_master_CHILD2 g2 "+
	" WHERE g.district_id = ? "+
	" AND g.guideline_id = g1.guideline_id "+
	" AND g1.tehsil_id =? "+
	" AND g1.ward_patwari_id = ? "+
	" AND g1.mohalla_village_id =? "+
	" AND g1.guideline_child1_id = g2.guideline_child1_id "+ 
	" AND g2.property_type_id = ?  "+
	" AND g2.property_type_l1_id = ?"+
	" AND g2.property_type_l2_id IS NULL";

	/**
	 * @author Madan Mohan
	 */
	public static final String GUIDELINE_VALUE_PROP_B =" SELECT g2.guideline_value "+
	"FROM IGRS_GUIDELINE_master_parent g,IGRS_GUIDELINE_master_CHILD1 g1 ,IGRS_GUIDElINE_master_CHILD2 g2 "+
	" WHERE g.district_id = ? "+
	" AND g.guideline_id = g1.guideline_id "+
	" AND g1.tehsil_id =? "+
	" AND g1.ward_patwari_id = ? " +
	" AND g1.mohalla_village_id =? "+
	" AND g1.guideline_child1_id = g2.guideline_child1_id "+ 
	" AND g2.property_type_id = ?  "+
	" AND g2.property_type_l1_id = ? "+
	" AND g2.property_type_l2_id = ? ";	
	/**
	 * @author Madan Mohan
	 */
	public static final String WARD_QUERY = "Select WARD_PATWARI_ID, "
				+"WARD_PATWARI_NAME from IGRS_WARD_PATWARI_MASTER "
				+"Where TEHSIL_ID=? AND WARD_PATWARI_STATUS='A' "
				+"AND AREA_TYPE_ID=? AND WARD_OR_PATWARI=? "
				+"ORDER BY WARD_PATWARI_NAME ASC";
	/**
	 * @author Madan Mohan
	 */
	public static final String MOHALLA_QUERY = "Select MOHALLA_VILLAGE_ID, "
				+"MOHALLA_VILLAGE_NAME from IGRS_MOHALLA_VILLAGE_MASTER "
				+"Where WARD_PATWARI_ID=? AND MOHALLA_VILLAGE_STATUS='A' "
				+"ORDER BY MOHALLA_VILLAGE_NAME ASC";
	/**
	 * @author Madan Mohan
	 */
	public static final String COMMON_QUERY = "Select TYPE_ID, "
		+"TYPE_NAME, H_TYPE_NAME from IGRS_COMMON_MASTER Where "
		+"PARENT_TYPE_ID=? AND TYPE_STATUS='A' "
		+"ORDER BY TYPE_NAME DESC";
	/**
	 * @author Madan Mohan
	 */
	public static final String CURRENT_YEAR = "select to_char(sysdate,'yyyy') from dual";
	
	/**
	 * @author madhaty
	 */
	public static final String DEED_QUERY = "SELECT DEED_TYPE_ID, "
				+"DEED_TYPE_NAME FROM IGRS_DEED_TYPE_MASTER "
				+"WHERE DEED_STATUS='A' AND PROPERTY_RELATED_DEED!='Y'  ORDER BY DEED_TYPE_NAME ASC";
	

	
	/**
	 * @author RISHAB
	 */
	public static final String DEED_QUERY_PROPERTY = "SELECT DEED_TYPE_ID, "
		+"DEED_TYPE_NAME FROM IGRS_DEED_TYPE_MASTER "
		+"WHERE DEED_STATUS='A' AND PROPERTY_RELATED_DEED='Y'  ORDER BY DEED_TYPE_NAME ASC";
	
	/**
	 * 	/**
	 * @author RISHAB
	 */
	public static final String DEED_QUERY_REGISTRATION = "SELECT DEED_TYPE_ID, "
		+"DEED_TYPE_NAME FROM IGRS_DEED_TYPE_MASTER "
		+"WHERE DEED_STATUS='A' AND PROPERTY_RELATED_DEED='Y' AND ROR_REQUIRED='R' ORDER BY DEED_TYPE_NAME ASC";
	
	/**
	 * 	/**
	 * @author RISHAB
	 */
	public static final String DEED_QUERY_REGISTRATION_NON_PROPERTY = "SELECT DEED_TYPE_ID, "
		+"DEED_TYPE_NAME FROM IGRS_DEED_TYPE_MASTER "
		+"WHERE DEED_STATUS='A' AND PROPERTY_RELATED_DEED!='Y' AND ROR_REQUIRED='R' ORDER BY DEED_TYPE_NAME ASC";
	/**
	 
	
	 * @author Madan Mohan
	 */
	public static final String PROPERTY_TYPE_SELECT_QUERY =
		"SELECT PROPERTY_TYPE_ID,PROPERTY_TYPE_NAME "
		+"FROM IGRS_PROPERTY_TYPE_MASTER WHERE PROPERTY_TYPE_STATUS='A' "
		+"ORDER BY PROPERTY_TYPE_NAME ASC";
	/**
	 * @author Madan Mohan
	 */
	public static final String MUNICIPAL_BODY_SELECT_QUERY =
		 "SELECT MUNICIPAL_BODY_ID,MUNICIPAL_BODY_NAME  FROM "
		+"IGRS_MUNICIPAL_BODY_MASTER WHERE MUNICIPAL_BODY_STATUS='A' "
		+"ORDER BY MUNICIPAL_BODY_NAME ASC";
	/**
	 * @author Madan Mohan
	 */
	public static final String AREA_TYPE_QUERY =
		"SELECT AREA_TYPE_ID,AREA_TYPE_NAME FROM IGRS_AREA_TYPE_MASTER "
		+" WHERE AREA_TYPE_STATUS='A' ORDER BY AREA_TYPE_NAME ASC";
	/**
	 * @author Rishab
	 */
	public static final String LAND_TYPE_QUERY ="SELECT UOM_ID,UOM_NAME FROM IGRS_UOM_MASTER WHERE UOM_STATUS='A' ";
	/**
	 * @author Madan Mohan
	 */
	public static final String PLOT_USE_QUERY =
		"SELECT PROPERTY_TYPE_L1_ID, PROPERTY_TYPE_L1_NAME,"
		+" TYPE_OF_LABEL FROM IGRS_PROP_TYPE_L1_MASTER "
		+" WHERE PROPERTY_TYPE_L1_STATUS='A' "
		+" AND PROPERTY_TYPE_ID=? ORDER BY PROPERTY_TYPE_L1_NAME ASC";
	/**
	 * @author Madan Mohan
	 */
	public static final String FLOOR_MASTER_QUERY =
		" SELECT IGRS_PROP_L1_FLOOR_MAPPING.FLOOR_ID,"
		+" IGRS_FLOOR_MASTER.FLOOR_NAME, IGRS_FLOOR_MASTER.FLOOR_DESC"
		+" FROM IGRS_FLOOR_MASTER, IGRS_PROP_TYPE_L1_MASTER,"
		+" IGRS_PROP_L1_FLOOR_MAPPING WHERE ((IGRS_FLOOR_MASTER.FLOOR_ID"
		+" = IGRS_PROP_L1_FLOOR_MAPPING.FLOOR_ID) AND "
		+" (IGRS_PROP_TYPE_L1_MASTER.PROPERTY_TYPE_L1_ID ="
		+" IGRS_PROP_L1_FLOOR_MAPPING.PROPERTY_TYPE_L1_ID)) AND "
		+" IGRS_PROP_L1_FLOOR_MAPPING.PROPERTY_TYPE_L1_ID = ?"
		+ " AND IGRS_FLOOR_MASTER.FLOOR_STATUS='A' ORDER BY IGRS_FLOOR_MASTER.FLOOR_ID ASC";
	/**
	 * @author Madan Mohan
	 */
	public static final String PLOT_L2_USE_QUERY =
		"SELECT PROPERTY_TYPE_L2_ID,PROPERTY_TYPE_L2_NAME,"
		+"PROPERTY_TYPE_L2_DESC FROM IGRS_PROP_TYPE_L2_MASTER "
		+"WHERE PROPERTY_TYPE_L2_STATUS='A' AND PROPERTY_TYPE_L1_ID=? "
		+"ORDER BY PROPERTY_TYPE_L2_NAME ASC";
	/**
	 *  @author Madan Mohan
	 */
	public static final String INSTRUMENTS_QUERY = "SELECT "
										+ "INSTRUMENT_ID,"
										+ "INSTRUMENT_NAME,Label_Amount,Label_Value_Required "
										+ "FROM IGRS_DEED_INSTRUMENT_MASTER "
										+ "WHERE DEED_TYPE_ID=? AND "
										+ "INSTRUMENT_STATUS='A' ORDER BY "
										+ "INSTRUMENT_ID ASC";
	
	/**
	 *  @author Madan Mohan
	 */
	public static final String FLOOR_TYPE_CALC = "SELECT A.CALC_ID,A.CALC_DESC " +
			" FROM IGRS_FLOOR_CALCULATION_TYPE A,IGRS_FLOOR_CALCULATION_MAP B  "+
				" WHERE A.CALC_STATUS='A' AND  A.CALC_ID=B.CALC_ID  AND B.MAP_STATUS=? AND B.PROPERTY_TYPE_L1_ID=?  ";
	
	
	/**
	 * @author Madan Mohan
	 */
	public static final String EXEMPTIONS_QUERY = "SELECT "
										+ "EXEMPTION_ID,"
										+ "EXEMPTION_NAME "
										+ "FROM IGRS_DEED_EXEMPTION_MASTER "
										+ "WHERE DEED_TYPE_ID=? AND "
										+ "INSTRUMENT_ID=? AND "
										+ "EXEMPTION_STATUS='A' "
										+ "ORDER BY EXEMPTION_NAME ASC";
	
	/**
	 * @author Madan Mohan
	 */
	public static final String EXEMPTIONS_INST_LEVEL_QUERY = "SELECT "
										+ "EXEMPTION_ID,"
										+ "EXEMPTION_NAME "
										+ "FROM IGRS_DEED_EXEMPTION_MASTER "
										+ "WHERE DEED_TYPE_ID=? AND "
										+ "EXEMPTION_STATUS='A' "
										+ "ORDER BY EXEMPTION_NAME ASC";
	/**
	 * @author Madan Mohan
	 */
	public static final String DUTY_CALCULATION_PROCEDURE = "CALL "
				+ "IGRS_STAMP_DUTY_PKG.IGRS_STAMP_DUTY_PROC(?,?,?,?,?,?,?,?,?,?,?,?)";
	/**
	 * @author Madan Mohan
	 */
	public static final String REGISTRATION_FEE_PROCEDURE = "CALL "
				+ "IGRS_REGISTRATION_FEE_PKG.IGRS_REG_FEE_PROC"
				+ "(?,?,?,?,?,?,?,?)";
	/**
	 * @author Madan Mohan
	 */
	public static final String JUDICIAL_DUTY_CALCULATION_PROCEDURE =
		"CALL IGRS_STAMP_DUTY_JUDICIAL_CALC.IGRS_JUDICIAL_SDUTY_CALC(?,?,?,?)";
	/**
	 * @author Hari
	 */
	/*public static final String PROPERTY_VALUATION_PROCEDURE = 
		"CALL IGRS_PROPERTY_VALUATION_PKG." 
		+"IGRS_PROP_VAL_CALC_PROC(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";*/
	/**
	 * @author Imran Shaik
	 */
	
	public static final String PROPERTY_VALUATION_PROCEDURE = 
		"CALL IGRS_PROPERTY_VAL_PKG." 
		+"IGRS_PROP_VAL_CALC_PROC(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
	/**
	 * @author Madan Mohan
	 */
	public static final String PROPERTY_VALUATION_PROCEDURE_AGRI = 
		"CALL IGRS_PROP_VAL_AGRI_PLOT_PROC(?,?,?,?,?,?,?,?,?,?,?)";
	public static final String SUB_CLAUSE_DETAILS_QUERY ="Select DISTINCT  c.SUB_CLAUSE_ID,c.SUB_CLAUSE_NAME||' - '||c.SUB_CLAUSE_DESC, c.USER_DEFINED_FIELD , d.OPERAND  "+
	"from IGRS_SUB_CLAUSE_MASTER_FINAL a,IGRS_SUB_CLAUSE_MASTER c , IGRS_COMPUTATION_LOGIC_MASTER d "+
	" where a.DISTRICT_ID=? "+
	"and a.TEHSIL_ID=? "+
	"and a.WARD_PATWARI_ID=? "+
	"and a.MOHALLA_VILLAGE_ID=? "+
	"and a.PROPERTY_TYPE_ID=? "+
   " and a.PROPERTY_TYPE_L1_ID=? "+
   " and d.COMPUTATION_LOGIC_ID=c.COMPUTATION_LOGIC_ID and c.SUB_CLAUSE_STATUS ='A'  "+
	"and a.SUB_CLAUSE_ID=c.SUB_CLAUSE_ID order by c.SUB_CLAUSE_NAME||' - '||c.SUB_CLAUSE_DESC";
	/**
	 * @author Madan Mohan
	 */
	public static final String SUB_CLAUSE_BUILDING_QUERY =  
		"Select DISTINCT  c.SUB_CLAUSE_ID,c.SUB_CLAUSE_NAME||' - '||c.SUB_CLAUSE_DESC, c.USER_DEFINED_FIELD , d.OPERAND ,  C.PROP_TYPE_FLAG  "+
		"from IGRS_SUB_CLAUSE_MASTER_FINAL a,IGRS_SUB_CLAUSE_MASTER c , IGRS_COMPUTATION_LOGIC_MASTER d "+
		" where a.DISTRICT_ID=? "+
		"and a.TEHSIL_ID=? "+
		"and a.WARD_PATWARI_ID=? "+
		"and a.MOHALLA_VILLAGE_ID=? " +
		//"and a.PROPERTY_TYPE_ID=?  and a.PROPERTY_TYPE_L1_ID=? "+
		"and a.PROPERTY_TYPE_ID=? "+
		"and a.PROPERTY_TYPE_L1_ID=? and a.PROPERTY_TYPE_L2_ID=?"+
		"and d.COMPUTATION_LOGIC_ID=c.COMPUTATION_LOGIC_ID and c.SUB_CLAUSE_STATUS ='A' "+
		"and a.SUB_CLAUSE_ID=c.SUB_CLAUSE_ID ORDER BY C.PROP_TYPE_FLAG ASC ";

	public static final String SUB_CLAUSE_QUERY_500 =  
		"Select DISTINCT  c.SUB_CLAUSE_ID,c.SUB_CLAUSE_NAME||' - '||c.SUB_CLAUSE_DESC, c.USER_DEFINED_FIELD , d.OPERAND  "+
		"from IGRS_SUB_CLAUSE_MASTER_FINAL a,IGRS_SUB_CLAUSE_MASTER c , IGRS_COMPUTATION_LOGIC_MASTER d "+
		" where a.DISTRICT_ID=? "+
		"and a.TEHSIL_ID=? "+
		"and a.WARD_PATWARI_ID=? "+
		"and a.MOHALLA_VILLAGE_ID=? "+
		"and a.PROPERTY_TYPE_ID=? "+
	   " and a.PROPERTY_TYPE_L1_ID=? AND a.PROPERTY_TYPE_L2_ID=?"+
	   " and d.COMPUTATION_LOGIC_ID=c.COMPUTATION_LOGIC_ID and c.SUB_CLAUSE_STATUS ='A'  "+
		"and a.SUB_CLAUSE_ID=c.SUB_CLAUSE_ID order by c.SUB_CLAUSE_NAME||' - '||c.SUB_CLAUSE_DESC";
	
	/*
	public static final String SUB_CLAUSE_BUILDING_QUERY =
		"SELECT DISTINCT S.SUB_CLAUSE_ID,M.SUB_CLAUSE_NAME,M.UNIT_FLAG"
		+" FROM IGRS_SUB_CLAUSE_AREA_MAPPING S,IGRS_SUB_CLAUSE_MASTER M"
		+" WHERE S.SUB_CLAUSE_ID IN (SELECT SUB_CLAUSE_ID FROM "
		+" IGRS_SUB_CLAUSE_AREA_MAPPING WHERE SUB_CLAUSE_ID "
		+" IN (SELECT SUB_CLAUSE_ID FROM IGRS_SUB_CLAUSE_FLOOR_MAPPING "
		+" WHERE FLOOR_ID=?)) AND DISTRICT_ID=? AND TEHSIL_ID=? "
		+" AND WARD_PATWARI_ID=? AND MOHALLA_VILLAGE_ID=? AND "
		+" PROPERTY_TYPE_ID=? AND PROPERTY_TYPE_L1_ID=? AND "
		+" PROPERTY_TYPE_L2_ID=? AND S.SUB_CLAUSE_ID=M.SUB_CLAUSE_ID";*/
   /**
    * @author Madan Mohan
    */
	public static final String MUNICIPAL_DUTY_CALCULATION =
			"CALL IGRS_MUNC_PAN_DUTY_PKG."
			+"IGRS_MUNC_PAN_DUTY_PROC(?,?,?,?,?,?,?,?,?,?)";
	
	public static final String MUNICIPAL_DUTY_CALCULATION_NEW =
		"CALL IGRS_MUNC_PAN_DUTY_PKG_NEW."
		+"IGRS_MUNC_PAN_DUTY_PROC(?,?,?,?,?,?,?,?,?)";
	/**
	 * @author Madan Mohan
	 */
	public static final String NONJUDICIAL_DUTY_CALCULATION_PROCEDURE = 
		"CALL IGRS_STAMP_DUTY_PKG.IGRS_STAMP_DUTY_PROC"
		+"(?,?,?,?,?,?,?,?,?,?,?,?)";
	/**
	 * @author Madan Mohan
	 */
	public static final String SERVICE_FEE_PROCEDURE = "CALL " 
			+"IGRS_SERVICE_FEE_PKG.IGRS_SERVICE_FEE_PROC(?,?,?,?,?,?)";
	/**
	 * @author Madan Mohan
	 */
	public static final String REG_STAMPDUTY_PROCEDURE = 
		"CALL IGRS_STAMP_DUTY_PKG."
		+"IGRS_STAMP_DUTY_PROC(?,?,?,?,?,?,?,?,?,?,?,?)";
	/**
	 * @author Pavani Param
	 */
	public static final String MUN_DUTY_PROCEDURE = "CALL " 
			+"IGRS_MUNC_PAN_DUTY_PKG.IGRS_MUNC_PAN_DUTY_PROC"
			+"(?,?,?,?,?,?,?,?,?,?)";
	/**
	 *@ author Pavani Param
	 */
	public static final String REG_FEE_DUTY_PROCEDURE = 
		"CALL IGRS_REGISTRATION_FEE_PKG." 
		+"IGRS_REG_FEE_PROC(?,?,?,?,?,?,?)";
	/**
	 * @author Hari Krishna
	 */
	public static final String PROPERTY_FLOOR_VALUATION_PROCEDURE = 
		"CALL IGRS_PROPERTY_VALUATION_PKG1." 
		+"IGRS_PROP_VAL_CALC_PROC(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
	/**
	 * @author Hari Krishna
	 */
	public static final String INSERT_LOG_DETAILS = 
		"INSERT INTO IGRS_APPLICATION_LOG" 
		+"(TABLE_NAME,OPERATION_TYPE,OPEATION_STATUS, "
		+"OPERATED_BY,OPERATED_FUNCTION_ID," 
		+"OPERATED_ROLE_ID,OPERATION_DATE,APPL_LOG_ID)VALUES(?,?,?,?,?,?,SYSDATE,?)";

	//----ADDED BY SATBIR KUMAR
	
	public static final String INSERT_ACT_LOG_DETAILS = "insert into IGRS_ACTIVITY_LOG"+
														"(SEQUENCE_ID,USER_ID,OPERATED_ACTIVITY_ID,OPERATED_FUNCTION_ID,CREATED_DATE,LOG_STATUS_FLAG) values(?,?,?,?,sysdate,'A')";
	
	
	public static final String INSERT_TXN_LOG_DETAILS = "insert into IGRS_TRANSACTION_LOG"+
	"(TRANSACTION_LOG_ID,FUNCTION_ID,PAYMENT_TRANSACTION_ID,USER_ID,ACTIVITY_ID,PAYMENT_STATUS,LOG_FLAG,AMOUNT,ACTIVITY_DATE) values(?,?,?,?,?,?,'A',?,sysdate)";
	
    /**
     * @author Aakriti
     */
     public static final String FEE_QUERY = "Select FEE "
                       +" from IGRS_PURPOSE_MASTER "
                       +" Where PURPOSE_ID=? AND STATUS='A' ";


     public static final String ACT_SEQNC = "select IGRS_ACTLOG_ID_SEQ.NEXTVAL from dual";

     public static final String TXN_SEQNC = "select IGRS_TXNLOG_ID_SEQ.NEXTVAL from dual";
     
     public static final String GET_FUNCTN_ID = "SELECT FUNCTION_ID FROM IGRS_ACTIVITY_MASTER WHERE ACTIVITY_ID = ?";
     
     /**
     * @author Aakriti
     */
     public static final String PURPOSE_QUERY = "Select PURPOSE_ID, "
                 + "PURPOSE_NAME from IGRS_PURPOSE_MASTER "
                 +"WHERE STATUS='A' ORDER BY PURPOSE_NAME ASC";




	
	/**
	 * @author Rishab
	 */
	public static final String NEXT_USER_ID="SELECT USER_DETAILS.NEXTVAL from dual";
	/**
	 * @author Rishab
	 */
	public static final String INSERT_USER_DETAILS=
		"INSERT INTO IGRS_PROP_VAL_DETAILS "
		+"(VAL_TXN_ID, FIRST_NAME, MIDDLE_NAME, LAST_NAME, GENDER, DOB, " +
		"CONSIDER_AMOUNT, DISTRICT_ID, TEHSIL_ID, AREA_ID, WARD_PATWARI_ID,"+
		"MOHALLA_ID, GOV_BODY_ID, PROP_TYPE_ID, PROP_L1_TYPE__ID, PROP_L2_TYPE__ID,"+
		" AREA_UNIT_ID, MARKET_VALUE, CREATED_DATE, CREATED_BY,"+
		"AREA,SYSTEM_MV)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,SYSDATE,?,?,?)";
	
	
	
	/**
	 * @author Rishab
	 */

	public static final String INSERT_EXCHANGE_USER_DETAILS=
		"INSERT INTO IGRS_PROP_VAL_DETAILS "
		+"(VAL_TXN_ID,MARKET_VALUE, CREATED_DATE,CREATED_BY,"+
		"UPDATE_BY)VALUES(?,?,SYSDATE,?,?)";
	/**
	 * @author Rishab
	 */

	
	public static final String IGRS_STAMP_DUTY_DETAILS=
		" INSERT INTO IGRS_PROP_STAMP_DUTY_DETAILS (DUTY_TXN_ID,STAMP_DUTY,GRAM_DUTY,NAGAR_DUTY,UPKAR, REG_FEE, TOTAL,DEED_ID, "+
			"	INSTRUMENT_ID, EXEMPTION_ID,DUTY_ALREADY_PAID, REG_ALREADY_PAID, CREATED_DATE , CREATED_BY)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,SYSDATE,?)";
	
	public static final String IGRS_NEW_STAMP_DUTY_DETAILS=
		"INSERT INTO IGRS_STAMP_DUTY_DETAILS "
		+"(STAMP_TXN_ID,DUTY_TXN_ID,FIRST_NAME,MIDDLE_NAME,LAST_NAME,DOB,USER_ENTERED_VAL, CREATED_DATE "+
		",CREATED_BY)VALUES(?,?,?,?,?,to_date(?,'DD-MM-YYYY'),?,SYSDATE,?)";
	
	/**
	 * @author Rishab
	 */
	public static final String IGRS_EXEMPTION_DETAILS=
		"INSERT INTO IGRS_EXEMPTION_DETAILS "
		+"(EXEMPTION_TXN_ID,DUTY_TXN_ID,EXEMPTION_ID,CREATED_DATE)VALUES(?,?,?,SYSDATE)";
	
	public static final String IGRS_PROP_STAMP_DUTY_DETAILS=
		"INSERT INTO IGRS_PROP_STAMP_DUTY_DETAILS "
		+"(VAL_TXN_ID, DUTY_TXN_ID,STAMP_DUTY,GRAM_DUTY,NAGAR_DUTY,UPKAR, " +
		"REG_FEE, TOTAL, MARKET_VALUE, DEED_ID, INSTRUMENT_ID, "+
		" REG_ALREADY_PAID,DUTY_ALREADY_PAID, CREATED_DATE "+
		",SHARE_VALUE,CREATED_BY)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,SYSDATE,?,?)";
	/**
	 * @author Rishab
	 */
	public static final String IGRS_PROP_EXEMPTION_DETAILS=
		"INSERT INTO IGRS_PROP_EXEMPTION_DETAILS "
		+"(DUTY_TXN_ID,EXEMPTION_ID,CREATED_DATE "+
		",MODIFIED_DATE)VALUES(?,?,SYSDATE,SYSDATE)";
	/**
	 * @author Rishab
	 */
	public static final String INSERT_SUBCLAUSE_DETAILS=
		"INSERT INTO IGRS_PROP_SUBCLAUSE_VAL_DTLS "
		+"(SUBCLAUSE_TXN_ID,VAL_TXN_ID,FLOOR_TXN_ID ,SUB_CLAUSE_ID,USER_ENTERED_VALUE)"+
		"VALUES(?,?,?,?,?)";
	/**
	 * @author Rishab
	 */
	public static final String INSERT_FLOOR_DETAILS=
		"INSERT INTO IGRS_PROP_FLOOR_DETAILS "
		+"(VAL_TXN_ID,FLOOR_TXN_ID,CALCULATION_TYPE_ID ,CONSIDER_AMOUNT, PROP_L1_TYPE__ID, PROP_L2_TYPE__ID,"+
		" MARKET_VALUE, CREATED_DATE, "+
		" AREA,CONSTRUCTED_AREA,FLOOR_TYPE_ID,CREATED_BY,SYSTEM_MV)VALUES(?,?,?,?,?,?,?,SYSDATE,?,?,?,?,?)";
	/**
	 * @author Madan Mohan
	 */
    public static final  String ACCESS_TIME_PROCEDURE = 
    	"IGRS_EMP_LOGIN_DATETIME_CHECK(?,?,?)";

    public static final String PHOTOID_PROOF_QUERY = "Select PHOTO_PROOF_TYPE_ID, "
		+ "PHOTO_PROOF_TYPE_NAME from IGRS_PHOTOID_PROOF_TYPE_MASTER "
		+"WHERE PHOTO_PROOF_TYPE_STATUS='A' ORDER BY PHOTO_PROOF_TYPE_NAME ASC";
    
    //Added by rachita
    
    public static final String PHOTOID_PROOF_QUERY_H = "Select PHOTO_PROOF_TYPE_ID, "
		+ "H_PHOTO_PROOF_TYPE_NAME from IGRS_PHOTOID_PROOF_TYPE_MASTER "
		+"WHERE PHOTO_PROOF_TYPE_STATUS='A' ORDER BY PHOTO_PROOF_TYPE_NAME ASC";


    public static final String APPELLATE_QUERY = "Select APPELLATE_TYPE_ID, "
		+ "APPELLATE_TYPE_NAME from IGRS_APPELLATE_TYPE_MASTER"
		+ " WHERE APPELLATE_TYPE_STATUS='A' ORDER BY APPELLATE_TYPE_NAME ASC";
    
    //added by shruti
    public static final String APPELLATE_QUERY_H = "Select APPELLATE_TYPE_ID, "
		+ "H_APPELLATE_TYPE_NAME from IGRS_APPELLATE_TYPE_MASTER"
		+ " WHERE APPELLATE_TYPE_STATUS='A' ORDER BY APPELLATE_TYPE_NAME ASC";
    //end
    
    /**
	 * @author LAVI
	 */
	public static final String DEED_QUERY_OP = "SELECT DISTINCT D.DEED_TYPE_ID,D.DEED_TYPE_NAME "
		+ "FROM IGRS_DEED_TYPE_MASTER D, IGRS_DEED_INSTRUMENT_MASTER I WHERE D.DEED_STATUS='A' "
		+ "AND D.DEED_TYPE_ID=I.DEED_TYPE_ID AND I.INSTRUMENT_TYPE='O' ORDER BY D.DEED_TYPE_NAME ASC";
	/**
	 * 	/**
	 * @author LAVI
	 */
	public static final String DEED_QUERY_REGISTRATION_NON_PROPERTY_OP = "SELECT DISTINCT D.DEED_TYPE_ID, D.DEED_TYPE_NAME FROM IGRS_DEED_TYPE_MASTER D, IGRS_DEED_INSTRUMENT_MASTER I "
		+ "WHERE D.DEED_STATUS='A' AND D.DEED_TYPE_ID=I.DEED_TYPE_ID AND I.INSTRUMENT_TYPE='O' ORDER BY D.DEED_TYPE_NAME ASC";

	public static final String INSTRUMENTS_QUERY_OP = "SELECT "
		+ "INSTRUMENT_ID,"
		+ "INSTRUMENT_NAME,Label_Amount,Label_Value_Required "
		+ "FROM IGRS_DEED_INSTRUMENT_MASTER "
		+ "WHERE DEED_TYPE_ID=? AND "
		+ "INSTRUMENT_STATUS='A' AND INSTRUMENT_TYPE='O' ORDER BY "
		+ "INSTRUMENT_ID ASC";
	
	
	//added by shruti
	public static final String SRO_QUERY = "select OFFICE_NAME from IGRS_OFFICE_MASTER where OFFICE_TYPE_ID='3' and OFFICE_STATUS='A' and  DISTRICT_ID=? order by OFFICE_NAME asc";
	
	//added by shruti
	public static final String SRO_QUERY_H = "select H_OFFICE_NAME from IGRS_OFFICE_MASTER where OFFICE_TYPE_ID='3' and OFFICE_STATUS='A' and  DISTRICT_ID=? order by OFFICE_NAME asc";
	
	// added by Lavi
	/**
	 * 	/**
	 * @author LAVI
	 */
	public static final String GET_EXEMPTION_LEVEL = "SELECT exemption_level FROM IGRS_DEED_TYPE_MASTER "
				+"WHERE DEED_TYPE_ID=?";
	
	public static final String COUNTRY_QUERY_HINDI = "Select COUNTRY_ID, "
		+ "COUNTRY_NAME,H_COUNTRY_NAME from IGRS_COUNTRY_MASTER "
		+"WHERE COUNTRY_STATUS='A' ORDER BY COUNTRY_NAME ASC";
	
	public static final String STATE_QUERY_HINDI = "Select STATE_ID, "
		+"STATE_NAME,H_STATE_NAME from IGRS_STATE_MASTER "
		+"Where  STATE_STATUS='A' AND COUNTRY_ID=? ORDER BY STATE_NAME ASC";
	//added by ShreeraJ
	public static final String STATE_QUERY_HINDI_INDIA = "Select STATE_ID, "
		+"STATE_NAME,H_STATE_NAME from IGRS_STATE_MASTER "
		+"Where  STATE_STATUS='A' AND COUNTRY_ID='1' ORDER BY STATE_NAME ASC";
	//end
	//added by shruti
	public static final String DISTRICT_QUERY_H = "Select DISTRICT_ID, "
		+"H_DISTRICT_NAME from IGRS_DISTRICT_MASTER "
		+" Where STATE_ID=? AND DISTRICT_STATUS='A' "
		+"ORDER BY DISTRICT_NAME ASC";
	//end
	
	public static final String DISTRICT_QUERY_HINDI = "Select DISTRICT_ID, "
		+"DISTRICT_NAME,H_DISTRICT_NAME from IGRS_DISTRICT_MASTER "
		+" Where STATE_ID=? AND DISTRICT_STATUS='A' "
		+"ORDER BY DISTRICT_NAME ASC";
	
	//added by rachita
	
	public static final String DISTRICT_QUERY_HINDI_H = "Select DISTRICT_ID, "
		+"DISTRICT_NAME,H_DISTRICT_NAME from IGRS_DISTRICT_MASTER "
		+" Where STATE_ID=? AND DISTRICT_STATUS='A' "
		+"ORDER BY DISTRICT_NAME ASC";
	
	public static final String AREA_TYPE_QUERY_HINDI =
		"SELECT AREA_TYPE_ID,AREA_TYPE_NAME,H_AREA_TYPE_NAME FROM IGRS_AREA_TYPE_MASTER "
		+" WHERE AREA_TYPE_STATUS='A' ORDER BY AREA_TYPE_NAME ASC";
	//added by shruti
	public static final String AREA_TYPE_QUERY_H =
		"SELECT AREA_TYPE_ID,H_AREA_TYPE_NAME FROM IGRS_AREA_TYPE_MASTER "
		+" WHERE AREA_TYPE_STATUS='A' ORDER BY AREA_TYPE_NAME ASC";
	//end
	
	public static final String MUNICIPAL_BODY_SELECT_QUERY_HINDI =
		 "SELECT MUNICIPAL_BODY_ID,MUNICIPAL_BODY_NAME,H_MUNICIPAL_BODY_NAME  FROM "
		+"IGRS_MUNICIPAL_BODY_MASTER WHERE MUNICIPAL_BODY_STATUS='A' "
		+"ORDER BY MUNICIPAL_BODY_NAME ASC";
	
	public static final String PROPERTY_TYPE_SELECT_QUERY_HINDI =
		"SELECT PROPERTY_TYPE_ID,PROPERTY_TYPE_NAME,H_PROPERTY_TYPE_NAME "
		+"FROM IGRS_PROPERTY_TYPE_MASTER WHERE PROPERTY_TYPE_STATUS='A' "
		+"ORDER BY PROPERTY_TYPE_NAME ASC";
	
	public static final String TEHSIL_QUERY_HINDI = "Select  TEHSIL_ID, "
	    +"TEHSIL_NAME,H_TEHSIL_NAME from IGRS_TEHSIL_MASTER "
	    +"Where DISTRICT_ID=? AND TEHSIL_STATUS='A' "
	    +"ORDER BY TEHSIL_NAME ASC";
	
	//added by shruti
	public static final String TEHSIL_QUERY_H = "Select  TEHSIL_ID, "
	    +"H_TEHSIL_NAME from IGRS_TEHSIL_MASTER "
	    +"Where DISTRICT_ID=? AND TEHSIL_STATUS='A' "
	    +"ORDER BY TEHSIL_NAME ASC";
	//end
	
	public static final String WARD_QUERY_HINDI = "Select WARD_PATWARI_ID, "
		+"WARD_PATWARI_NAME,H_WARD_PATWARI_NAME from IGRS_WARD_PATWARI_MASTER "
		+"Where TEHSIL_ID=? AND WARD_PATWARI_STATUS='A' "
		+"AND AREA_TYPE_ID=? AND WARD_OR_PATWARI=? "
		+"ORDER BY WARD_PATWARI_NAME ASC";
	
	public static final String MOHALLA_QUERY_HINDI = "Select MOHALLA_VILLAGE_ID, "
		+"MOHALLA_VILLAGE_NAME,H_MOHALLA_VILLAGE_NAME from IGRS_MOHALLA_VILLAGE_MASTER "
		+"Where WARD_PATWARI_ID=? AND MOHALLA_VILLAGE_STATUS='A' "
		+"ORDER BY MOHALLA_VILLAGE_NAME ASC";
	
	public static final String PLOT_USE_QUERY_HINDI =
		"SELECT PROPERTY_TYPE_L1_ID, PROPERTY_TYPE_L1_NAME,"
		+" TYPE_OF_LABEL,H_PROPERTY_TYPE_L1_NAME FROM IGRS_PROP_TYPE_L1_MASTER "
		+" WHERE PROPERTY_TYPE_L1_STATUS='A' "
		+" AND PROPERTY_TYPE_ID=? ORDER BY PROPERTY_TYPE_L1_NAME ASC";
	
	public static final String PLOT_L2_USE_QUERY_HINDI =
		"SELECT PROPERTY_TYPE_L2_ID,PROPERTY_TYPE_L2_NAME,"
		+"PROPERTY_TYPE_L2_DESC,H_PROPERTY_TYPE_L2_NAME FROM IGRS_PROP_TYPE_L2_MASTER "
		+"WHERE PROPERTY_TYPE_L2_STATUS='A' AND PROPERTY_TYPE_L1_ID=? "
		+"ORDER BY PROPERTY_TYPE_L2_NAME ASC";
	
	public static final String LAND_TYPE_QUERY_HINDI ="SELECT UOM_ID,UOM_NAME,H_UOM_NAME FROM IGRS_UOM_MASTER WHERE UOM_STATUS='A' ";
	
	public static final String FLOOR_TYPE_CALC_HINDI = "SELECT A.CALC_ID,A.CALC_DESC,A.H_CALC_NAME " +
	" FROM IGRS_FLOOR_CALCULATION_TYPE A,IGRS_FLOOR_CALCULATION_MAP B  "+
		" WHERE A.CALC_STATUS='A' AND  A.CALC_ID=B.CALC_ID  AND B.MAP_STATUS=? AND B.PROPERTY_TYPE_L1_ID=?  ";
	
	/*public static final String FLOOR_MASTER_QUERY_HINDI =
		" SELECT IGRS_PROP_L1_FLOOR_MAPPING.FLOOR_ID,"
		+" IGRS_FLOOR_MASTER.FLOOR_NAME, IGRS_FLOOR_MASTER.FLOOR_DESC, IGRS_FLOOR_MASTER.H_FLOOR_NAME"
		+" FROM IGRS_FLOOR_MASTER, IGRS_PROP_TYPE_L1_MASTER,"
		+" IGRS_PROP_L1_FLOOR_MAPPING WHERE ((IGRS_FLOOR_MASTER.FLOOR_ID"
		+" = IGRS_PROP_L1_FLOOR_MAPPING.FLOOR_ID) AND "
		+" (IGRS_PROP_TYPE_L1_MASTER.PROPERTY_TYPE_L1_ID ="
		+" IGRS_PROP_L1_FLOOR_MAPPING.PROPERTY_TYPE_L1_ID)) AND "
		+" IGRS_PROP_L1_FLOOR_MAPPING.PROPERTY_TYPE_L1_ID = ?"
		+ " AND IGRS_FLOOR_MASTER.FLOOR_STATUS='A' ORDER BY IGRS_FLOOR_MASTER.FLOOR_ID ASC";*/
	
	public static final String FLOOR_MASTER_QUERY_HINDI ="SELECT F.FLOOR_ID,F.FLOOR_NAME,F.H_FLOOR_NAME FROM IGRS_FLOOR_MASTER F ,IGRS_PROP_L1_FLOOR_MAP_DUMMY M WHERE M.FLOOR_ID=F.FLOOR_ID AND M.PROPERTY_TYPE_L1_ID=?";
	
	
	
	public static final String INSTRUMENTS_QUERY_HINDI = "SELECT "
		+ "INSTRUMENT_ID,"
		+ "INSTRUMENT_NAME,Label_Amount,Label_Value_Required,H_LABEL_AMOUNT "
		+ "FROM IGRS_DEED_INSTRUMENT_MASTER "
		+ "WHERE DEED_TYPE_ID=? AND "
		+ "INSTRUMENT_STATUS='A' ORDER BY "
		+ "INSTRUMENT_ID ASC";
	
	public static final String EXEMPTIONS_INST_LEVEL_QUERY_HINDI = "SELECT "
		+ "EXEMPTION_ID,"
		+ "EXEMPTION_NAME "
		+ "FROM IGRS_DEED_EXEMPTION_MASTER "
		+ "WHERE DEED_TYPE_ID=? AND "
		+ "EXEMPTION_STATUS='A' "
		+ "ORDER BY EXEMPTION_NAME ASC";
	
	public static final String EXEMPTIONS_QUERY_HINDI = "SELECT "
		+ "EXEMPTION_ID,"
		+ "EXEMPTION_NAME "
		+ "FROM IGRS_DEED_EXEMPTION_MASTER "
		+ "WHERE DEED_TYPE_ID=? AND "
		+ "INSTRUMENT_ID=? AND "
		+ "EXEMPTION_STATUS='A' "
		+ "ORDER BY EXEMPTION_NAME ASC";
	//added by shruti
	public static final String GETWARDPATWARILIST="SELECT WARD_PATWARI_ID,WARD_PATWARI_NAME FROM IGRS_WARD_PATWARI_MASTER WHERE TEHSIL_ID=? "
		+ "and  WARD_PATWARI_STATUS='A' AND AREA_TYPE_ID=? AND  WARD_OR_PATWARI=?";
	
	public static final String GETWARDPATWARILIST_H="SELECT WARD_PATWARI_ID,H_WARD_PATWARI_NAME FROM IGRS_WARD_PATWARI_MASTER WHERE TEHSIL_ID=? "
		+ "and  WARD_PATWARI_STATUS='A' AND AREA_TYPE_ID=? AND  WARD_OR_PATWARI=?";
	
	public static final String GETMOHALLAVILLAGELIST="SELECT MOHALLA_VILLAGE_ID, MOHALLA_VILLAGE_NAME FROM IGRS_MOHALLA_VILLAGE_MASTER WHERE "
		+ " MOHALLA_VILLAGE_STATUS='A'  AND WARD_PATWARI_ID=?";
		
	public static final String GETMOHALLAVILLAGELIST_H="SELECT MOHALLA_VILLAGE_ID, H_MOHALLA_VILLAGE_NAME FROM IGRS_MOHALLA_VILLAGE_MASTER WHERE "
			+ " MOHALLA_VILLAGE_STATUS='A'  AND WARD_PATWARI_ID=?";
	
	//BELOW ADDED BY ROOPAM FOR NEW DUTY CALCULATION - 26 FEB 2014
	public static final String DEED_QUERY_DC_COMMON = "SELECT DEED_TYPE_ID, "
		+"DEED_TYPE_NAME FROM IGRS_DEED_TYPE_MASTER "
		+"WHERE DEED_STATUS='A' AND DEED_CATEGORY_ID=? ORDER BY DEED_TYPE_NAME ASC";
	
	public static final String DEED_QUERY_DEEDCATEGORY_COMMON = "SELECT DEED_CATEGORY_ID, "
		+"DEED_CATEGORY_NAME FROM IGRS_DEED_CATEGORY_MASTER "
		+"WHERE STATUS='A' ORDER BY DEED_CATEGORY_NAME ASC";
	public static final String DEED_QUERY_DEEDCATEGORY_COMMON_HINDI = "SELECT DEED_CATEGORY_ID, "
		+"DEED_CATEGORY_NAME_H FROM IGRS_DEED_CATEGORY_MASTER "
		+"WHERE STATUS='A' ORDER BY DEED_CATEGORY_NAME ASC";
		
	//added by shruti---26 may 2014
	public static String SUB_AREA_NAME_EN="SELECT SUB_AREA_TYPE_ID,SUB_AREA_TYPE_NAME FROM IGRS_SUB_AREA_TYPE_MASTER WHERE AREA_TYPE_ID=? AND SUB_AREA_TYPE_STATUS='A' ORDER BY SUB_AREA_TYPE_NAME";	
	public static String SUB_AREA_NAME_HI="SELECT SUB_AREA_TYPE_ID,H_SUB_AREA_TYPE_NAME FROM IGRS_SUB_AREA_TYPE_MASTER WHERE AREA_TYPE_ID=? AND SUB_AREA_TYPE_STATUS='A' ORDER BY H_SUB_AREA_TYPE_NAME";

	public static String WARD_PATWARI_NAME_EN="SELECT WPM.WARD_PATWARI_ID,WPM.WARD_PATWARI_NAME,WM.SUBAREA_WARD_MAPPING_ID FROM IGRS_WARD_PATWARI_MASTER WPM,IGRS_SUBAREA_WARD_MAPPING WM WHERE WM.WARD_PATWARI_ID=WPM.WARD_PATWARI_ID AND WM.SUB_AREA_TYPE_ID=? AND TEHSIL_ID =? AND WARD_PATWARI_STATUS='A' ORDER BY WPM.WARD_PATWARI_NAME";
	public static String WARD_PATWARI_NAME_HI="SELECT WPM.WARD_PATWARI_ID ,WPM.H_WARD_PATWARI_NAME,WM.SUBAREA_WARD_MAPPING_ID FROM IGRS_WARD_PATWARI_MASTER WPM,IGRS_SUBAREA_WARD_MAPPING WM WHERE WM.WARD_PATWARI_ID=WPM.WARD_PATWARI_ID AND WM.SUB_AREA_TYPE_ID=? AND TEHSIL_ID =? AND WARD_PATWARI_STATUS='A' ORDER BY WPM.H_WARD_PATWARI_NAME";
	
	public static String COLONY_NAME_EN="SELECT C.COLONY_ID, C.COLONY_NAME,M.COLONY_WARD_MAPPING_ID,C.APPLICABLE_SUBCLAUSE_ID FROM IGRS_COLONY_MASTER C ,IGRS_COLONY_WARD_MAPPING M WHERE M.COLONY_ID=C.COLONY_ID AND M.SUBAREA_WARD_MAPPING_ID=? and C.COLONY_STATUS='A' ORDER BY C.COLONY_NAME";
	public static String COLONY_NAME_HI="SELECT C.COLONY_ID, C.H_COLONY_NAME,M.COLONY_WARD_MAPPING_ID,C.APPLICABLE_SUBCLAUSE_ID FROM IGRS_COLONY_MASTER C ,IGRS_COLONY_WARD_MAPPING M WHERE M.COLONY_ID=C.COLONY_ID AND M.SUBAREA_WARD_MAPPING_ID=? and C.COLONY_STATUS='A' ORDER BY C.H_COLONY_NAME";
	
	
}
