/*
 * Copyright Notice
 *==============================================================================
 * This file contains proprietary information of Wipro Infotech, Bangalore.
 * Copying or reproduction without prior written approval is prohibited.
 * Copyright (c) 2007-08
 *==============================================================================
 *
 * File Name   :   CommonSQL.java
 * Author      :   Imran Shaik
 * Description :   Represents the SQL Class for Registration Initiation.
 * ----------------------------------------------------------------------------
 * Version         Last Modified By     Last Modified On           Modification
 * ----------------------------------------------------------------------------
 * 	0.0             Imran Shaik		     18th Mar, 2008	 		 
 * ----------------------------------------------------------------------------
 */


package com.wipro.igrs.igrsmaster.sql;


public class CommonSQL {
    public static final String INSERT_MODULE_MASTER = "INSERT INTO IGRS_MODULE_MASTER M (M.MODULE_ID,M.MODULE_NAME,M.MODULE_DESCRIPTION,M.MODULE_STATUS,M.CREATED_BY,M.CREATED_DATE) VALUES (IGRS_MODULE_MASTER_SEQ1.NEXTVAL,?,?,'A',?,SYSDATE)";
    public static final String SELECT_MODULES_LIST = "SELECT MODULE_ID,MODULE_NAME FROM IGRS_MODULE_MASTER WHERE MODULE_STATUS='A'";
    public static final String SELECT_SUB_MODULES_LIST = "SELECT SUB_MODULE_ID,SUB_MODULE_NAME FROM IGRS_SUB_MODULE_MASTER WHERE SUB_MODULE_STATUS='A'";
    public static final String SELECT_DEEDS_LIST = "SELECT M.DEED_TYPE_ID,M.DEED_TYPE_NAME,M.DEED_TYPE_DESCRIPTION FROM IGRS_DEED_TYPE_MASTER M WHERE M.DEED_STATUS='A'";
    public static final String SELECT_INSTRUMENTS_LIST = "SELECT INSTRUMENT_ID,INSTRUMENT_NAME,INSTRUMENT_DESCRIPTION FROM IGRS_DEED_INSTRUMENT_MASTER WHERE INSTRUMENT_STATUS='A'";
    public static final String INSERT_SUB_MODULE_MASTER = "INSERT INTO IGRS_SUB_MODULE_MASTER M (M.SUB_MODULE_ID,M.MODULE_ID,M.SUB_MODULE_NAME,M.SUB_MODULE_DESCRIPTION,M.SUB_MODULE_STATUS,M.CREATED_BY,M.CREATED_DATE) VALUES (IGRS_SUB_MODULE_MASTER_SEQ.NEXTVAL,?,?,?,'A',?,SYSDATE)";
    public static final String INSERT_FUNCTION_MASTER = "INSERT INTO IGRS_FUNCTION_MASTER M (M.FUNCTION_ID,M.SUB_MODULE_ID,M.FUNCTION_NAME,M.FUNCTION_DESC,M.PAYMENT_FLAG,M.INTIMATION_FLAG,M.FUNCTION_STATUS,M.CREATED_BY,M.CREATED_DATE) VALUES (IGRS_FUNCTION_MASTER_SEQ.NEXTVAL,?,?,?,?,?,'A',?,SYSDATE)";
    public static final String INSERT_DEED_TYPE_MASTER ="INSERT INTO IGRS_DEED_TYPE_MASTER (DEED_TYPE_ID, DEED_TYPE_NAME, DEED_TYPE_DESCRIPTION, DEED_STATUS, CREATED_BY,CREATED_DATE, DEED_CATEGORY, PIN_REQUIRED, PROPERTY_RELATED_DEED, ROR_REQUIRED) values (IGRS_DEED_TYPE_MASTER_SEQ.NEXTVAL,?,?,'A',?,SYSDATE,?,?,?,?)";
   //   "INSERT INTO IGRS_DEED_TYPE_MASTER M (M.DEED_TYPE_ID,M.DEED_TYPE_NAME,M.DEED_TYPE_DESCRIPTION,M.DEED_CATEGORY,M.DEED_STATUS,M.CREATED_BY,M.CREATED_DATE) VALUES (IGRS_DEED_TYPE_MASTER_SEQ.NEXTVAL,?,?,?,'A',?,SYSDATE)";
    public static final String INSERT_SUB_CLAUSE_MASTER = "INSERT INTO IGRS_SUB_CLAUSE_MASTER S (S.SUB_CLAUSE_ID,S.SUB_CLAUSE_NAME,S.SUB_CLAUSE_DESC,S.SUB_CLAUSE_STATUS,S.CREATED_BY,S.CREATED_DATE) VALUES (IGRS_SUB_CLAUSE_SEQ.NEXTVAL,?,?,'A',?,SYSDATE)"; 
    public static final String SELECT_SUB_CLAUSE = "SELECT S.SUB_CLAUSE_ID,S.SUB_CLAUSE_NAME,S.SUB_CLAUSE_DESC,S.SUB_CLAUSE_STATUS FROM IGRS_SUB_CLAUSE_MASTER S WHERE S.SUB_CLAUSE_ID=?";
    public static final String UPDATE_SUB_CLAUSE = "UPDATE IGRS_SUB_CLAUSE_MASTER S SET S.SUB_CLAUSE_NAME=?,S.SUB_CLAUSE_DESC=?,S.SUB_CLAUSE_STATUS=?,S.UPDATED_BY=?,S.UPDATED_DATE=SYSDATE WHERE S.SUB_CLAUSE_ID=?"; 
    public static final String SELECT_MODULE_MASTER_LIST = "SELECT MODULE_ID,MODULE_NAME,MODULE_DESCRIPTION FROM IGRS_MODULE_MASTER WHERE MODULE_STATUS='A'";
    public static final String SELECT_SUB_MODULE_MASTER_LIST = "SELECT SUB_MODULE_ID,SUB_MODULE_NAME,SUB_MODULE_DESCRIPTION FROM IGRS_SUB_MODULE_MASTER WHERE SUB_MODULE_STATUS='A'";
    public static final String SELECT_FUNCTION_MASTER_LIST = "SELECT FUNCTION_ID,FUNCTION_NAME,FUNCTION_DESC FROM IGRS_FUNCTION_MASTER WHERE FUNCTION_STATUS='A'";
    public static final String SELECT_SUB_CLAUSE_MASTER_LIST = "SELECT S.SUB_CLAUSE_ID,S.SUB_CLAUSE_NAME,S.SUB_CLAUSE_DESC FROM IGRS_SUB_CLAUSE_MASTER S WHERE S.SUB_CLAUSE_STATUS='A'";
    
    public static final String SELECT_DEED_TYPE_MASTER_LIST = "SELECT M.DEED_TYPE_ID,M.DEED_TYPE_NAME,M.DEED_TYPE_DESCRIPTION FROM IGRS_DEED_TYPE_MASTER M WHERE M.DEED_STATUS='A'";
    public static final String SELECT_INSTRUMENT_MASTER_LIST = "SELECT INSTRUMENT_ID,INSTRUMENT_NAME,INSTRUMENT_DESCRIPTION FROM IGRS_DEED_INSTRUMENT_MASTER WHERE INSTRUMENT_STATUS='A'";
    public static final String SELECT_EXEMPTION_MASTER_LIST = "SELECT E.EXEMPTION_ID,E.EXEMPTION_NAME,E.EXEMPTION_DESCRIPTION FROM IGRS_DEED_EXEMPTION_MASTER E WHERE E.EXEMPTION_STATUS='A'";
    public static final String SELECT_MODULE = "SELECT MODULE_ID,MODULE_NAME,MODULE_DESCRIPTION,MODULE_STATUS FROM IGRS_MODULE_MASTER WHERE MODULE_ID=?";
    public static final String SELECT_SUB_MODULE = "SELECT SUB_MODULE_ID,SUB_MODULE_NAME,SUB_MODULE_DESCRIPTION,SUB_MODULE_STATUS,MODULE_ID FROM IGRS_SUB_MODULE_MASTER WHERE SUB_MODULE_ID=?";
    public static final String SELECT_FUNCTION = "SELECT FUNCTION_ID,FUNCTION_NAME,FUNCTION_DESC,FUNCTION_STATUS,SUB_MODULE_ID,PAYMENT_FLAG,INTIMATION_FLAG FROM IGRS_FUNCTION_MASTER WHERE FUNCTION_ID=?";
    public static final String SELECT_DEED_TYPE = "SELECT M.DEED_TYPE_ID,M.DEED_TYPE_NAME,M.DEED_TYPE_DESCRIPTION,M.DEED_STATUS,M.DEED_CATEGORY FROM IGRS_DEED_TYPE_MASTER M WHERE M.DEED_TYPE_ID=?";
    public static final String SELECT_DEED_TYPE_SEARCH = "SELECT  DEED_TYPE_ID, DEED_TYPE_NAME, DEED_TYPE_DESCRIPTION,DEED_STATUS, CREATED_BY, CREATED_DATE,DEED_CATEGORY,PIN_REQUIRED, PROPERTY_RELATED_DEED, " +
    		"ROR_REQUIRED FROM IGRS_DEED_TYPE_MASTER where DEED_TYPE_ID=?";
    public static final String SELECT_DEED_TYPE_NAME = "SELECT DEED_TYPE_ID, DEED_TYPE_NAME,DEED_STATUS FROM IGRS_DEED_TYPE_MASTER where DEED_STATUS='A' order by DEED_TYPE_ID";
    public static final String UPDATE_MODULE = "UPDATE IGRS_MODULE_MASTER M SET M.MODULE_NAME=?,M.MODULE_DESCRIPTION=?,M.MODULE_STATUS=?,M.UPDATE_BY=?,M.UPDATE_DATE=SYSDATE WHERE M.MODULE_ID=?";
    public static final String UPDATE_SUB_MODULE = "UPDATE IGRS_SUB_MODULE_MASTER S SET S.SUB_MODULE_NAME=?,S.SUB_MODULE_DESCRIPTION=?,S.SUB_MODULE_STATUS=?,S.MODULE_ID=?,S.UPDATE_BY=?,S.UPDATE_DATE=SYSDATE WHERE S.SUB_MODULE_ID=?";
    public static final String UPDATE_FUNCTION = "UPDATE IGRS_FUNCTION_MASTER F SET F.FUNCTION_NAME=?,F.FUNCTION_DESC=?,F.FUNCTION_STATUS=?,F.PAYMENT_FLAG=?,F.INTIMATION_FLAG=?,F.SUB_MODULE_ID=?,F.UPDATE_BY=?,F.UPDATE_DATE=SYSDATE WHERE F.FUNCTION_ID=?";
    public static final String UPDATE_DEED_TYPE = "UPDATE igrs_deed_type_master SET deed_type_name = ?,  deed_type_description = ?,  deed_category = ?,  update_by = ?,  UPDATE_date = sysdate,  pin_required = ?,  property_related_deed = ?,  ror_required = ? WHERE deed_type_id = ?";
    public static final String INSERT_INSTRUMENT_MASTER = "INSERT INTO IGRS_DEED_INSTRUMENT_MASTER I (I.INSTRUMENT_ID,I.INSTRUMENT_NAME,I.INSTRUMENT_DESCRIPTION,I.DEED_TYPE_ID,I.INSTRUMENT_STATUS,I.CREATED_BY,I.CREATED_DATE) VALUES (IGRS_INSTRUMENT_MASTER_SEQ.NEXTVAL,?,?,?,'A',?,SYSDATE)";
    public static final String SELECT_INSTRUMENT = "SELECT I.INSTRUMENT_ID,I.INSTRUMENT_NAME,I.INSTRUMENT_DESCRIPTION,I.INSTRUMENT_STATUS,I.DEED_TYPE_ID FROM IGRS_DEED_INSTRUMENT_MASTER I WHERE I.INSTRUMENT_ID=?";
    public static final String UPDATE_INSTRUMENT = "UPDATE IGRS_DEED_INSTRUMENT_MASTER I SET I.INSTRUMENT_NAME=?,I.INSTRUMENT_DESCRIPTION=?,I.INSTRUMENT_STATUS=?,I.DEED_TYPE_ID=?,I.UPDATE_BY=?,I.UPDATE_DATE=SYSDATE WHERE I.INSTRUMENT_ID=?";
    public static final String INSERT_EXEMPTION_MASTER = "INSERT INTO IGRS_DEED_EXEMPTION_MASTER E (E.EXEMPTION_ID,E.EXEMPTION_NAME,E.EXEMPTION_DESCRIPTION,E.DEED_TYPE_ID,E.INSTRUMENT_ID,E.EXEMPTION_STATUS,E.CREATED_BY,E.CREATED_DATE) VALUES (IGRS_EXEMPTION_MASTER_SEQ.NEXTVAL,?,?,?,?,'A',?,SYSDATE)";
    public static final String SELECT_EXEMPTION = "SELECT E.EXEMPTION_ID,E.EXEMPTION_NAME,E.EXEMPTION_DESCRIPTION,E.DEED_TYPE_ID,E.INSTRUMENT_ID,E.EXEMPTION_STATUS FROM IGRS_DEED_EXEMPTION_MASTER E WHERE E.EXEMPTION_ID=?";
    public static final String UPDATE_EXEMPTION = "UPDATE IGRS_DEED_EXEMPTION_MASTER E SET E.EXEMPTION_NAME=?,E.EXEMPTION_DESCRIPTION=?,E.EXEMPTION_STATUS=?,E.DEED_TYPE_ID=?,E.INSTRUMENT_ID=?,E.UPDATE_BY,E.UPDATE_DATE=SYSDATE WHERE E.EXEMPTION_ID=?";

    //added by shruti
    public static final String INSERT_SUB_CLAUSE_MASTER_TEMP="INSERT INTO IGRS_SUB_CLAUSE_MASTER S(S.SUB_CLAUSE_ID,"
    		+" S.SUB_CLAUSE_NAME,S.SUB_CLAUSE_DESC,S.SUB_CLAUSE_STATUS,S.COMPUTATION_LOGIC_ID," 
    		+" S.DEFINE_FOR_ALL_DISTRICT,S.CREATED_BY,S.CREATED_DATE,S.UPDATED_BY,S.UPDATED_DATE,USER_DEFINED_FIELD,NORMAL_VAL,PROP_TYPE_FLAG)"
    		+" VALUES(?,UPPER(?),UPPER(?),'A',?,?,?,SYSDATE,?,SYSDATE,?,?,?)";
 
    public static final String SELECTOPERATORS="SELECT OPERATOR_ID,OPERATOR_NAME FROM IGRS_OPERATOR_MASTER" 
    		+" WHERE OPERATOR_STATUS='A' ORDER BY OPERATOR_ID ASC";
    
    public static final String SELECTPROPERTY="SELECT PROPERTY_TYPE_ID,PROPERTY_TYPE_NAME,H_PROPERTY_TYPE_NAME FROM IGRS_PROPERTY_TYPE_MASTER WHERE PROPERTY_TYPE_STATUS = 'A' ORDER BY PROPERTY_TYPE_NAME ASC";

    public static final String SELECTPROPTYPEL1="SELECT PROPERTY_TYPE_L1_ID,PROPERTY_TYPE_L1_NAME,H_PROPERTY_TYPE_L1_NAME FROM " 
    		+" IGRS_PROP_TYPE_L1_MASTER WHERE PROPERTY_TYPE_ID=? and PROPERTY_TYPE_L1_STATUS = 'A'";
    
    public static final String SELECTPROPTYPEL2="SELECT PROPERTY_TYPE_L2_ID,PROPERTY_TYPE_L2_NAME,H_PROPERTY_TYPE_L2_NAME" 
    		+" FROM IGRS_PROP_TYPE_L2_MASTER WHERE PROPERTY_TYPE_L1_ID=? and PROPERTY_TYPE_L2_STATUS = 'A'";
    
    public static final String SELECTCOMPUTATIONID="SELECT IGRS_COMPUTATION_LOGIC_ID_SEQ.NEXTVAL FROM DUAL";
    public static final String SELECTSUBCLAUSEID="SELECT IGRS_SUB_CLAUSE_SEQ1.NEXTVAL FROM DUAL";
    public static final String INSERT_COMPUTATION_LOGIC_MASTER="INSERT INTO IGRS_COMPUTATION_LOGIC_MASTER"
    		+" (COMPUTATION_LOGIC_ID,OPERATOR_ID,OPERAND,STATUS,APP_FACTOR_AREA,APP_FACTOR_VALUE,COMP_BASED_ON_L1,COMP_BASED_ON_L2,COMP_BASED_ON_L,SUB_CLAUSE_ID,AREA_BASED_DIV)"
    				+ "VALUES(?,?,?,'A',?,?,?,?,?,?,?)";
    
    public static final String SELECTSUBCLAUSEMAPPINGID="SELECT IGRS_SUBCLAUSE_MAPPING_ID.NEXTVAL FROM DUAL";
    
    public static final String SELECTSUBCLAUSEDISTRICTMAPPINGID="SELECT IGRS_SBCLAUSE_DISTRICT_MAP_ID.NEXTVAL FROM DUAL";
    public static final String SELECTSUBCLAUSEPROPMAPPINGID="SELECT IGRS_SBCLAUSE_PROP_MAP_ID.NEXTVAL FROM DUAL";
    
    public static final String INSERT_SUBCLAUSE_PROP_MAPPING_DETAILS="INSERT INTO IGRS_SUBCLAUSE_PROP_MAPPING" 
    		+" (PROP_MAPPING_ID,SUB_CLAUSE_ID,PROPERTY_TYPE_ID,PROPERTY_TYPE_L1_ID,PROPERTY_TYPE_L2_ID,STATUS)" 
    		+" VALUES(?,?,?,?,?,'A')";
    
    public static final String INSERT_SUBCLAUSE_PROP_MAPPING_DETAILS1="INSERT INTO IGRS_SUBCLAUSE_PROP_MAPPING" 
		+" (PROP_MAPPING_ID,SUB_CLAUSE_ID,PROPERTY_TYPE_ID,PROPERTY_TYPE_L1_ID,STATUS)" 
		+" VALUES(?,?,?,?,'A')";

    public static final String INSERT_SUBCLAUSE_DISTRICT_MAPPING="INSERT ALL INTO IGRS_SUBCLAUSE_DISTRCT_MAPPING"
+"(DISTRICT_MAPPING_ID,SUB_CLAUSE_ID,DISTRICT_ID,TEHSIL_ID,WARD_PATWARI_ID,MOHALLA_VILLAGE_ID) VALUES(IGRS_SBCLAUSE_DISTRICT_MAP_ID.NEXTVAL,?,DISTRICT_ID,TEHSIL_ID,WARD_PATWARI_ID,MOHALLA_VILLAGE_ID)" +
		" select DISTRICT_ID,TEHSIL_ID,WARD_PATWARI_ID,MOHALLA_VILLAGE_ID from IGRS_GUIDELINE_TEMPLATE";
    
    public static final String SUBCLAUSEPROPDISPLAY="SELECT iptmt.PROPERTY_TYPE_ID,iptmt.PROPERTY_TYPE_NAME,"
+" iptl1mt.PROPERTY_TYPE_L1_ID,iptl1mt.PROPERTY_TYPE_L1_NAME,"
+" iptl2mt.PROPERTY_TYPE_L2_ID,NVL(iptl2mt.PROPERTY_TYPE_L2_NAME,'-')" 
 +" FROM IGRS_PROPERTY_TYPE_MASTER iptmt"
   +" LEFT OUTER JOIN IGRS_PROP_TYPE_L1_MASTER iptl1mt ON"
    +" (iptl1mt.PROPERTY_TYPE_ID=iptmt.PROPERTY_TYPE_ID) and iptmt.PROPERTY_TYPE_STATUS='A'" 
    		+" AND iptl1mt.PROPERTY_TYPE_L1_STATUS='A'"
     +" LEFT OUTER JOIN IGRS_PROP_TYPE_L2_MASTER iptl2mt ON"
     +" (iptl2mt.PROPERTY_TYPE_L1_ID=iptl1mt.PROPERTY_TYPE_L1_ID) and iptl2mt.PROPERTY_TYPE_L2_STATUS='A'"
     +" WHERE iptmt.PROPERTY_TYPE_ID=? ORDER BY"
    +" iptl1mt.PROPERTY_TYPE_L1_ID,iptl2mt.PROPERTY_TYPE_L2_ID";
    
    public static final String SUBCLAUSEPROPDISPLAY_H="SELECT iptmt.PROPERTY_TYPE_ID,iptmt.H_PROPERTY_TYPE_NAME,"
    	+" iptl1mt.PROPERTY_TYPE_L1_ID,iptl1mt.H_PROPERTY_TYPE_L1_NAME,"
    	+" iptl2mt.PROPERTY_TYPE_L2_ID,NVL(iptl2mt.H_PROPERTY_TYPE_L2_NAME,'-')" 
    	 +" FROM IGRS_PROPERTY_TYPE_MASTER iptmt"
    	   +" LEFT OUTER JOIN IGRS_PROP_TYPE_L1_MASTER iptl1mt ON"
    	    +" (iptl1mt.PROPERTY_TYPE_ID=iptmt.PROPERTY_TYPE_ID) and iptmt.PROPERTY_TYPE_STATUS='A'" 
    	    		+" AND iptl1mt.PROPERTY_TYPE_L1_STATUS='A'"
    	     +" LEFT OUTER JOIN IGRS_PROP_TYPE_L2_MASTER iptl2mt ON"
    	     +" (iptl2mt.PROPERTY_TYPE_L1_ID=iptl1mt.PROPERTY_TYPE_L1_ID) and iptl2mt.PROPERTY_TYPE_L2_STATUS='A'"
    	     +" WHERE iptmt.PROPERTY_TYPE_ID=? ORDER BY"
    	    +" iptl1mt.PROPERTY_TYPE_L1_ID,iptl2mt.PROPERTY_TYPE_L2_ID";
 
    public static final String SELECT_SUB_CLAUSE_NEW="SELECT S.SUB_CLAUSE_ID,S.SUB_CLAUSE_NAME,S.SUB_CLAUSE_DESC,S.SUB_CLAUSE_STATUS FROM IGRS_SUB_CLAUSE_MASTER S WHERE S.SUB_CLAUSE_ID=?";
    
    public static final String SELECT_SUB_CLAUSE_NEW1="select distinct iscm.SUB_CLAUSE_ID,SUB_CLAUSE_NAME,SUB_CLAUSE_DESC,SUB_CLAUSE_STATUS," 
    		+" OPERATOR_NAME,OPERAND,DEFINE_FOR_ALL_DISTRICT,USER_DEFINED_FIELD,NORMAL_VAL,APP_FACTOR_AREA,APP_FACTOR_VALUE,AREA_BASED_DIV"
+" from IGRS_SUB_CLAUSE_MASTER iscm,IGRS_COMPUTATION_LOGIC_MASTER iclm right outer join IGRS_OPERATOR_MASTER iom"
+" on iom.OPERATOR_ID=iclm.OPERATOR_ID where iclm.SUB_CLAUSE_ID=iscm.SUB_CLAUSE_ID and iclm.SUB_CLAUSE_ID=?"; 
    
    public static final String VIEWPROPFORSUBCLAUSE="SELECT distinct iptmt.PROPERTY_TYPE_NAME," 
    		+" iptl1mt.PROPERTY_TYPE_L1_NAME,NVL(iptl2mt.PROPERTY_TYPE_L2_NAME,'-'),iptmt.H_PROPERTY_TYPE_NAME,iptl1mt.H_PROPERTY_TYPE_L1_NAME,NVL(iptl2mt.H_PROPERTY_TYPE_L2_NAME,'-')"
 +" FROM IGRS_SUB_CLAUSE_MASTER iscm,IGRS_SUBCLAUSE_PROP_MAPPING ispm" 
 +" left outer join IGRS_PROPERTY_TYPE_MASTER iptmt on (ispm.PROPERTY_TYPE_ID=iptmt.PROPERTY_TYPE_ID)" 
 +" left outer join IGRS_PROP_TYPE_L1_MASTER iptl1mt on (ispm.PROPERTY_TYPE_L1_ID=iptl1mt.PROPERTY_TYPE_L1_ID)" 
 +" left outer join IGRS_PROP_TYPE_L2_MASTER iptl2mt on (ispm.PROPERTY_TYPE_L2_ID=iptl2mt.PROPERTY_TYPE_L2_ID)" 
 +" where ispm.SUB_CLAUSE_ID=iscm.SUB_CLAUSE_ID and iscm.SUB_CLAUSE_ID=?"; 
    
    public static final String UPDATE_SUB_CLAUSE_NEW="UPDATE IGRS_SUB_CLAUSE_MASTER S SET S.SUB_CLAUSE_DESC=?,S.SUB_CLAUSE_STATUS=?,S.UPDATED_BY=?,S.UPDATED_DATE=SYSDATE WHERE S.SUB_CLAUSE_ID=?";
    public static final String SELECT_SUB_CLAUSE_MASTER_LIST_NEW="SELECT S.SUB_CLAUSE_ID,S.SUB_CLAUSE_NAME,S.SUB_CLAUSE_DESC FROM IGRS_SUB_CLAUSE_MASTER S WHERE S.SUB_CLAUSE_STATUS='A' ORDER BY SUB_CLAUSE_ID ";
    
    public static final String SELECT_COMPUTATION_DETAILS="select distinct iom.operator_name, iclm.OPERAND,"
+" iclm.APP_FACTOR_OPERATOR_ID ,iclm.APP_FACTOR_OPERAND,iclm.COMP_BASED_ON_L1,iclm.COMP_BASED_ON_L2"
+" from igrs_operator_master iom , igrs_computation_logic_master iclm,IGRS_SUB_CLAUSE_MASTER isclmt" 
+" where iom.operator_id=(select operator_id from igrs_computation_logic_master"
+" where computation_logic_id=(select computation_logic_id from IGRS_SUB_CLAUSE_MASTER" 
+" where sub_clause_id=?)) and iclm.computation_logic_id = (select computation_logic_id from"
+" IGRS_SUB_CLAUSE_MASTER  where sub_clause_id=?)"
+" and isclmt.COMPUTATION_LOGIC_ID=iclm.COMPUTATION_LOGIC_ID";
    //END OF CODE
    
    //ADDED BY SIMRAN - 11 MARCH
    
    public static final String GET_PROP_SUBTYPE_DETAILS = "SELECT p.PROPERTY_TYPE_ID,p.PROPERTY_TYPE_NAME,p.H_PROPERTY_TYPE_NAME,ps.PROP_SUB_TYPE_ID,ps.PROP_SUB_TYPE_NAME,ps.H_PROP_SUB_TYPE_NAME FROM IGRS_PROP_SUB_TYPE_MASTER ps,IGRS_PROPERTY_TYPE_MASTER p WHERE p.PROPERTY_TYPE_ID = ? AND p.PROPERTY_TYPE_ID = ps.PROPERTY_TYPE_ID";
    
    public static final String GET_PROP_TYPE_L1_DETAILS = "SELECT PROP_TYPE_L1_ID, PROP_TYPE_L1_NAME ,H_PROP_TYPE_L1_NAME FROM IGRS_PROP_TYPE_L1_MASTER_DUMMY WHERE PROP_SUB_TYPE_ID = ?";
    
    public static final String INSERT_SUBCLAUSE_MASTER_DETAILS = "INSERT INTO IGRS_SUB_CLAUSE_MASTER S(S.SUB_CLAUSE_ID, S.SUB_CLAUSE_NAME,S.SUB_CLAUSE_DESC,S.H_SUB_CLAUSE_DESC,S.SUB_CLAUSE_STATUS," +
    		"S.COMPUTATION_LOGIC_ID,S.DEFINE_FOR_ALL_DISTRICT,S.CREATED_BY,S.CREATED_DATE,PROP_TYPE_FLAG)VALUES" +
    		"(?,UPPER(?),UPPER(?),?,'A',?,'Y',?,SYSDATE,?)";
    
    public static final String INSERT_COMPUTATION_LOGIC_DETAILS = "INSERT INTO IGRS_COMPUTATION_LOGIC_MASTER(COMPUTATION_LOGIC_ID,OPERATOR_ID,OPERAND,STATUS,COMP_BASED_ON_L,BASE_APPLICABILITY,CREATED_BY,CREATED_DATE)" +
    		" VALUES(?,?,?,'A',?,?,?,sysdate)";
    
    public static final String INSERT_SUBCLAUSE_PROP_MAPPING_DETLS = "INSERT INTO IGRS_SUBCLAUSE_PROP_MAPPING" +
    		" (PROP_MAPPING_ID,SUB_CLAUSE_ID,PROPERTY_TYPE_ID,SUB_PROPERTY_TYPE,STATUS,CREATED_BY,CREATED_DATE)" +
    		" VALUES(?,?,?,?,'A',?,SYSDATE)";
    
    public static final String INSERT_SUBCLAUSE_PROP_MAPPING_DETLS_L1= "INSERT INTO IGRS_SUBCLAUSE_PROP_MAPPING" +
	" (PROP_MAPPING_ID,SUB_CLAUSE_ID,PROPERTY_TYPE_ID,SUB_PROPERTY_TYPE, STATUS,CREATED_BY,CREATED_DATE ,PROPERTY_TYPE_L1_ID)" +
	" VALUES(?,?,?,?,'A',?,SYSDATE,?)"; 
    
    public static final String SELECT_SUCLAUSE_DETLS_FOR_DASHBOARD = "SELECT S.SUB_CLAUSE_ID,S.SUB_CLAUSE_NAME,S.SUB_CLAUSE_DESC,S.H_SUB_CLAUSE_DESC FROM IGRS_SUB_CLAUSE_MASTER S WHERE S.SUB_CLAUSE_STATUS='A' ORDER BY SUB_CLAUSE_ID";
    
    public static final String GET_SUBCLAUSE_COMPLETE_DETLS = "SELECT DISTINCT iscm.SUB_CLAUSE_ID,SUB_CLAUSE_NAME,SUB_CLAUSE_DESC,H_SUB_CLAUSE_DESC," +
    		"SUB_CLAUSE_STATUS, OPERATOR_NAME,OPERAND,COMP_BASED_ON_L,BASE_APPLICABILITY,iom.OPERATOR_ID FROM" +
    		" IGRS_SUB_CLAUSE_MASTER iscm,IGRS_COMPUTATION_LOGIC_MASTER iclm RIGHT OUTER JOIN " +
    		"IGRS_OPERATOR_MASTER iom ON iom.OPERATOR_ID=iclm.OPERATOR_ID WHERE " +
    		"iclm.COMPUTATION_LOGIC_ID=iscm.COMPUTATION_LOGIC_ID AND iscm.SUB_CLAUSE_ID= ?";
    
    public static final String GET_SUBCLAUSE_PROP_DETLS = "SELECT DISTINCT pt.PROPERTY_TYPE_NAME, NVL(spt.PROP_SUB_TYPE_NAME,'-') ,NVL(ptl1.PROP_TYPE_L1_NAME,'-'),pt.H_PROPERTY_TYPE_NAME," +
    		"NVL(spt.H_PROP_SUB_TYPE_NAME,'-'),NVL(ptl1.H_PROP_TYPE_L1_NAME,'-'),ispm.PROPERTY_TYPE_ID,ispm.SUB_PROPERTY_TYPE,NVL(ispm.PROPERTY_TYPE_L1_ID,0) FROM " +
    		"IGRS_SUB_CLAUSE_MASTER iscm,IGRS_SUBCLAUSE_PROP_MAPPING ispm LEFT OUTER JOIN IGRS_PROPERTY_TYPE_MASTER pt ON " +
    		"(ispm.PROPERTY_TYPE_ID=pt.PROPERTY_TYPE_ID) LEFT OUTER JOIN IGRS_PROP_SUB_TYPE_MASTER spt ON " +
    		"(ispm.SUB_PROPERTY_TYPE=spt.PROP_SUB_TYPE_ID) LEFT OUTER JOIN IGRS_PROP_TYPE_L1_MASTER_DUMMY ptl1 ON" +
    		" (ispm.PROPERTY_TYPE_L1_ID=ptl1.PROP_TYPE_L1_ID) WHERE " +
    		"ispm.SUB_CLAUSE_ID=iscm.SUB_CLAUSE_ID AND iscm.SUB_CLAUSE_ID= ?";
    
    public static final String GET_PROPERTY_TYPE_ID_FOR_SUBCLAUSE = "SELECT DISTINCT PROP_TYPE_FLAG FROM IGRS_SUB_CLAUSE_MASTER WHERE SUB_CLAUSE_ID = ?";
    
    public static final String DEACTIVATE_SUBCLAUSE = "UPDATE IGRS_SUB_CLAUSE_MASTER SET SUB_CLAUSE_STATUS = 'D' WHERE SUB_CLAUSE_ID = ?";
}