package com.wipro.igrs.titlecertificate.sql;
/* Copyright (c) 2006-2008 WIPRO. All Rights Reserved.
 * 
 *  This software is the confidential and proprietary information of WIPRO
 *  ("Confidential Information"). You shall not
 *  disclose such Confidential Information and shall use it only in
 *  accordance with the terms of the license agreement you entered into
 *  with WIPRO.
 *  
 * WIPRO MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE 
 * SUITABILITY OF THE SOFTWARE, EITHER EXPRESS OR IMPLIED, 
 * INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF 
 * MERCHANTABILITY, FITNESS FOR A
 * PARTICULAR PURPOSE, OR NON-INFRINGEMENT. WIPRO SHALL NOT BE 
 * LIABLE FOR ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF 
 * USING, MODIFYING OR DISTRIBUTING THIS SOFTWARE OR ITS 
 * DERIVATIVES.
 * 
 */


/**
 * @author Madan Mohan
 *
 */
public class CommonSQL {

	 
	public static final String TITLE_DETAILS_QUERY = 
		"SELECT IGRS_REG_COMP_TITLE_CER_DTLS.TITLE_CERTIFICATE_ID,"
       +"IGRS_REG_COMP_TITLE_CER_DTLS.SUBJECT, "
       +"IGRS_REG_COMP_TITLE_CER_DTLS.TITLE_TYPE, "
       +"IGRS_REG_COMP_TITLE_CER_DTLS.LOCATION_PLAN, "
       +"IGRS_REG_COMP_TITLE_CER_DTLS.CHANGE_ENTRY_NUMBER,"
       +"IGRS_REG_COMP_TITLE_CER_DTLS.CHANGE_SPEC,"
       +"IGRS_REG_COMP_TITLE_CER_DTLS.REGISTRATION_DATE,"
       +"IGRS_REG_COMP_TITLE_CER_DTLS.BURDEN_ENTRY_NUMBER, "
       +"IGRS_REG_COMP_TITLE_CER_DTLS.REGISTRATION_NO, "
       +"IGRS_REG_COMP_TITLE_CER_DTLS.REGISTRATION_ID, "
       +"IGRS_REG_COMP_TITLE_CER_DTLS.BURDEN_SPEC, "
       +"IGRS_PROPERTY_TYPE_MASTER.PROPERTY_TYPE_NAME, "
       +"IGRS_DISTRICT_MASTER.DISTRICT_NAME, IGRS_TEHSIL_MASTER.TEHSIL_NAME, "
       +"IGRS_WARD_PATWARI_MASTER.WARD_PATWARI_NAME, "
       +"IGRS_MOHALLA_VILLAGE_MASTER.MOHALLA_VILLAGE_NAME, "
       +"IGRS_AREA_TYPE_MASTER.AREA_TYPE_NAME, "
       +"IGRS_GOV_BODY_MASTER.GOV_BODY_NAME, "
       +"IGRS_REG_PROPERTY_DETAILS.VIKAS_KHAND, "
       +"IGRS_REG_PROPERTY_DETAILS.RI_CIRCLE, "
       +"IGRS_REG_PROPERTY_DETAILS.LAYOUT_DETAIL, "
       +"IGRS_REG_PROPERTY_DETAILS.KHASRA_NUMBER, " 
       +"IGRS_REG_PROPERTY_DETAILS.NAZOOL_SHEET_NUMBER, "
       +"IGRS_REG_PROPERTY_DETAILS.PROPERTY_ADDRESS, "
       +"IGRS_REG_PROPERTY_DETAILS.EAST_BOUNDARY, "
       +"IGRS_REG_PROPERTY_DETAILS.WEST_BOUNDARY, "
       +"IGRS_REG_PROPERTY_DETAILS.NORTH_BOUNDARY, "
       +"IGRS_REG_PROPERTY_DETAILS.SOUTH_BOUNDARY, "
       +"IGRS_REG_PROPERTY_DETAILS.TOTAL_AREA, "
       +"IGRS_REG_PROPERTY_VALUE_DTLS.MARKET_VALUE, "
       +"IGRS_REG_PROPERTY_VALUE_DTLS.CONSIDERATION_VALUE, "
       +"IGRS_WARD_PATWARI_MASTER.WARD_PATWARI_STATUS, "
       +"IGRS_PROP_TYPE_L1_MASTER.PROPERTY_TYPE_L1_NAME, "
       +"IGRS_PROP_TYPE_L2_MASTER.PROPERTY_TYPE_L2_NAME "
       +"FROM IGRS_REG_COMP_TITLE_CER_DTLS, IGRS_REG_PROPERTY_DETAILS, "
       +"IGRS_PROPERTY_TYPE_MASTER,IGRS_DISTRICT_MASTER,IGRS_TEHSIL_MASTER," 
       +"IGRS_WARD_PATWARI_MASTER,IGRS_MOHALLA_VILLAGE_MASTER,"
       +"IGRS_AREA_TYPE_MASTER,IGRS_GOV_BODY_AREA_MAP,IGRS_GOV_BODY_MASTER,"
       +"IGRS_UOM_MASTER,IGRS_REG_PROPERTY_VALUE_DTLS,"
       +"IGRS_PROP_TYPE_L1_MASTER,IGRS_PROP_TYPE_L2_MASTER "
       +"WHERE ((IGRS_REG_COMP_TITLE_CER_DTLS.REGISTRATION_ID = "
       +"IGRS_REG_PROPERTY_DETAILS.REG_TXN_ID) "
       +"AND (IGRS_REG_PROPERTY_DETAILS.PROPERTY_TYPE_ID = "
       +"IGRS_PROPERTY_TYPE_MASTER.PROPERTY_TYPE_ID) AND "
       +"(IGRS_DISTRICT_MASTER.DISTRICT_ID = "
       +"IGRS_REG_PROPERTY_DETAILS.DISTRICT_ID) "
       +"AND (IGRS_DISTRICT_MASTER.DISTRICT_ID=IGRS_TEHSIL_MASTER.DISTRICT_ID) "
       +"AND (IGRS_TEHSIL_MASTER.TEHSIL_ID="
       +"IGRS_REG_PROPERTY_DETAILS.TEHSIL_ID) AND "
       +"(IGRS_TEHSIL_MASTER.TEHSIL_ID = IGRS_WARD_PATWARI_MASTER.TEHSIL_ID) "
       +"AND (IGRS_WARD_PATWARI_MASTER.WARD_PATWARI_ID = "
       +"IGRS_REG_PROPERTY_DETAILS.WARD_PATWARI_ID) "
       +"AND (IGRS_WARD_PATWARI_MASTER.WARD_PATWARI_ID = "
       +"IGRS_MOHALLA_VILLAGE_MASTER.WARD_PATWARI_ID) "
       +"AND (IGRS_MOHALLA_VILLAGE_MASTER.MOHALLA_VILLAGE_ID = "
       +"IGRS_REG_PROPERTY_DETAILS.MOHALLA_VILLAGE_ID ) " 
       +"AND (IGRS_AREA_TYPE_MASTER.AREA_TYPE_ID = " 
       +"IGRS_REG_PROPERTY_DETAILS.AREA_TYPE_ID) AND "
       +"(IGRS_AREA_TYPE_MASTER.AREA_TYPE_ID = "
       +"IGRS_PROPERTY_TYPE_MASTER.AREA_TYPE_ID) "
       +" AND (IGRS_AREA_TYPE_MASTER.AREA_TYPE_ID = "
       +"IGRS_WARD_PATWARI_MASTER.AREA_TYPE_ID ) "
       +"AND (IGRS_DISTRICT_MASTER.DISTRICT_ID = "
       +"IGRS_GOV_BODY_AREA_MAP.DISTRICT_ID) "
       +"AND (IGRS_TEHSIL_MASTER.TEHSIL_ID = "
       +"IGRS_GOV_BODY_AREA_MAP.TEHSIL_ID) "
       +"AND (IGRS_WARD_PATWARI_MASTER.WARD_PATWARI_ID = "
       +"IGRS_GOV_BODY_AREA_MAP.WARD_PATWARI_ID) "
       +"AND (IGRS_MOHALLA_VILLAGE_MASTER.MOHALLA_VILLAGE_ID = "
       +"IGRS_GOV_BODY_AREA_MAP.MOHALLA_VILLAGE_ID ) "
       +"AND (IGRS_GOV_BODY_MASTER.GOV_BODY_ID = "
       +"IGRS_GOV_BODY_AREA_MAP.BODY_TYPE_ID) "
       +"AND (IGRS_UOM_MASTER.UOM_ID = IGRS_REG_PROPERTY_DETAILS.UOM_ID) "
       +"AND (IGRS_REG_PROPERTY_DETAILS.PROPERTY_TXN_ID = "
       +"IGRS_REG_PROPERTY_VALUE_DTLS.PROPERTY_TXN_ID) "
       +"AND (IGRS_PROPERTY_TYPE_MASTER.PROPERTY_TYPE_ID = "
       +"IGRS_PROP_TYPE_L1_MASTER.PROPERTY_TYPE_ID) "
       +"AND (IGRS_PROP_TYPE_L1_MASTER.PROPERTY_TYPE_L1_ID = "
       +"IGRS_REG_PROPERTY_DETAILS.PROPERTY_L1_ID) "
       +"AND (IGRS_PROP_TYPE_L1_MASTER.PROPERTY_TYPE_L1_ID = "
       +"IGRS_PROP_TYPE_L2_MASTER.PROPERTY_TYPE_L1_ID) "
       +"AND (IGRS_PROP_TYPE_L2_MASTER.PROPERTY_TYPE_L2_ID = "
       +"IGRS_REG_PROPERTY_DETAILS.PROPERTY_L2_ID)) "
       + " AND IGRS_REG_COMP_TITLE_CER_DTLS.REGISTRATION_ID = ?";

	
	public static final String PROPRIETOR_NAME_QUERY =
		"SELECT PARTY_FIRST_NAME_H||PARTY_MIDDLE_NAME_H||PARTY_LAST_NAME_H "
		+"AS PARTYNAME FROM IGRS_REG_TXN_PARTY_DETAILS "
		+"WHERE REG_TXN_ID = ?";
}

