/*
* Copyright Notice
*==============================================================================
* This file contains proprietary information of IGRS Bhopal Madhya Pradesh .
* Copying or reproduction without prior written approval is prohibited.
* Copyright (c) 2007-08
*==============================================================================
*
* File Name   :   
 * Author      :   
 * Description :   
 * ----------------------------------------------------------------------------
* Version         Modified By     Modified On           Modification
* ----------------------------------------------------------------------------
* 1.0             SHRUTI           xxxxx              
 * --------------------------------------------------------------------------------
*/
package com.wipro.igrs.caseMonitoring.sql;

public class CommonSQL {

    //Revenue Module
    public static final String IGRS_REVENUE_TOTAL_ROWS=
        " SELECT COUNT(*) FROM IGRS_RCPT_AUDIT_TXN WHERE";
    
    public static final String IGRS_REVENUE_DOC_DETAILS = 
        " INSERT INTO IGRS_CASE_TXN_DOC_DETAILS(CASE_TXN_ID, DOC_TYPE_ID,"+
        " DOC_EXTN, DOC_LOCATION, DOC_OBJECT, DOC_STATUS, CREATED_BY,"+
        " CREATED_DATE, UPDATE_BY, UPDATE_DATE, CASE_ACTION_TXN_ID)"+
        " VALUES(?,?,?,?,?,?,?,SYSDATE,?,?,?)";

    public static final String IGRS_REVENUE_DOCUMENT_MASTER = 
        " INSERT INTO IGRS_DOCUMENT_TYPE_MASTER(DOCUMENT_TYPE_ID,"+
        " DOCUMENT_NAME, DOCUMENT_DESCRIPTION, DOCUMENT_STATUS,"+
        " CREATED_BY, CREATED_DATE, UPDATE_BY, UPDATE_DATE)"+
        " VALUES(?,?,?,?,?,SYSDATE,?,?)";

    public static final String IGRS_REVENUE_TXN_COMMENTS = 
        " INSERT INTO IGRS_CASE_TXN_COMMENTS (SR_NO,CASE_TXN_ID,"+
        " CASE_ACTION_TXN_ID,USER_COMMENTS,CREATED_BY,CREATED_DATE)"+
        " VALUES(?,?,?,?,?,SYSDATE)";

    //added by shruti----10 july 2014
    public static final String UPDATE_IGRS_SP_DETLS ="update IGRS_SP_DETLS set CASE_ELIGIBILITY='N' WHERE LICENSE_NUMBER=?";  
    //end
    
  //added by roopam----9 feb 2015
    public static final String UPDATE_POT_DETLS ="update IGRS_PUBLIC_OFFICER_TOOL_TXN set CASE_ID=? WHERE TRANSACTION_ID=?";  
    //end
    
  /*  public static final String IGRS_REVENUE_ACTION_MAP = 
        " INSERT INTO IGRS_CASE_ACTION_MAP (CASE_TXN_ID, CASE_ACTION_ID,"+
        " CASE_ACTION_BY, CASE_ACTION_DATE, CASE_ACTION_REMARKS,"+
        " CREATED_DATE, CASE_ACTION_TXN_ID,PARTY_RESPONSE_FLAG)"+
        " VALUES(?,?,?,?,?,SYSDATE,?,?)";*/
    
    public static final String IGRS_REVENUE_ACTION_MAP = 
        " INSERT INTO IGRS_CASE_ACTION_MAP (SR_NO,CASE_ACTION_TXN_ID,CASE_TXN_ID, CASE_ACTION_ID,"+
        " CASE_ACTION_REMARKS, PARTY_RESPONSE_FLAG,CREATED_BY,CREATED_DATE)"+
        " VALUES(?,?,?,?,?,?,?,SYSDATE)";

    //commented- 14th june 2013
    
    /*public static final String IGRS_REVENUE_TXN_DETAILS = 
        " INSERT INTO IGRS_CASE_TXN_DETAILS (CASE_TXN_ID, CASE_HEAD_ID,"+
        " CASE_TYPE_ID, REVENUE_HEAD_ID, SECTION_HEAD_ID,"+
        " REGISTERED_DISTRICT_ID, REGISTERED_OFFICE_ID, REGISTERED_SR_ID,"+
        " REPORT_ID, REGISTRATION_ID, VALUATION_BY_DR, PROPOSED_STAMP_DUTY,"+
        " PROPOSED_REG_FEE, CASE_STATUS, CASE_CLOSED_DATE, SPOT_INSP_TXN_ID,"+
        " NEXT_HEARING_DATE, CASE_FINAL_COMMENTS, RRC_CASE, SP_USER_ID,"+
        " SP_LICENSE_NO, RULE_120, CASE_ACTION_ID, CREATED_BY,"+
        " CREATED_DATE, UPDATE_BY, UPDATE_DATE, PENALTY_AMOUNT, ESTAMP_CODE,"+
        " DOC_ID, COMPLIANCE_DETAILS, COMPLIANCE_DATE, COMPLIANCE_BY) VALUES"+
        "(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,SYSDATE,"+
        "?,?,?,?,?,?,?,?)";*/
    public static final String IGRS_REVENUE_TXN_DETAILS_IMPOUND = 
        " INSERT INTO IGRS_CASE_TXN_DETAILS (SR_NO,CASE_TXN_ID, CASE_HEAD_ID,"+
        " CASE_TYPE_ID, REVENUE_HEAD_ID, SECTION_HEAD_ID,"+
        " REPORT_ID, REGISTRATION_ID, VALUATION_BY_DR, PROPOSED_STAMP_DUTY,"+
        " PROPOSED_REG_FEE, CASE_STATUS, SPOT_INSP_DETAILS,"+
        " NEXT_HEARING_DATE, CASE_FINAL_COMMENTS, RRC_CASE,"+
        " RULE_120, CREATED_BY,CREATED_DATE, ESTAMP_CODE,CASE_ACTION_ID,DUE_DATE,FINAL_RECOVERABLE_AMT) VALUES"+
        "(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,SYSDATE,?,?,?,?)";
    
   
    public static final String IGRS_REVENUE_TXN_DETAILS = 
        " INSERT INTO IGRS_CASE_TXN_DETAILS (SR_NO,CASE_TXN_ID, CASE_HEAD_ID,"+
        " CASE_TYPE_ID, REVENUE_HEAD_ID, SECTION_HEAD_ID,"+
        " REPORT_ID, REGISTRATION_ID, VALUATION_BY_DR, PROPOSED_STAMP_DUTY,"+
        " PROPOSED_REG_FEE, CASE_STATUS, SPOT_INSP_DETAILS,"+
        " NEXT_HEARING_DATE, CASE_FINAL_COMMENTS, RRC_CASE,"+
        " RULE_120, CREATED_BY,CREATED_DATE, ESTAMP_CODE,CASE_ACTION_ID,DUE_DATE,OFFICE_ID,FINAL_RECOVERABLE_AMT) VALUES"+
        "(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,SYSDATE,?,?,?,?,?)";
    
    public static final String IGRS_REFUND_TXN_DETAILS="INSERT INTO IGRS_CASE_REFUND_TXN_DTLS"
    	+"(SR_NO,CASE_TXN_ID,CASE_HEAD_ID,CASE_TYPE_ID,REVENUE_HEAD_ID,SECTION_HEAD_ID,CASE_STATUS,CASE_FINAL_COMMENTS,"
    	+"RRC_CASE,RULE_120,RECOVERABLE_AMT,REFUND_BILL_NO,REFUND_BILL_DATE,PARTY_NAME,PARTY_ADDRESS,SR_NAME,SRO_NAME,CREATED_BY,CREATED_DATE,CASE_ACTION_ID,ESTAMP_REQ_ID,OFFICE_ID,ESTAMP_TYPE) VALUES"
    	+"(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,SYSDATE,?,?,?,?)";
    
    public static final String 	IGRS_PENALTY_TXN_DTLS="INSERT INTO IGRS_CASE_REV_PNLTY_TXN_DTLS(SR_NO," +
    		"CASE_TXN_ID,CASE_STATUS,CASE_FINAL_COMMENTS,STAMP_AMOUNT,REG_FEE,SR_NAME,SRO_NAME," +
    		"PARTY_FIRST_NAME,PARTY_LAST_NAME,PARTY_ADDRESS,CREATED_BY,CREATED_DATE,CASE_ACTION_ID," +
    		"PENALTY_ID,REVISION_NUMBER) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,SYSDATE,?,?,?)";
    
    public static final String 	IGRS_PENALTY_SEC70_TXN_DTLS="INSERT INTO IGRS_CASE_PNLTY70_TXN_DTLS(SR_NO," +
	"CASE_TXN_ID,CASE_STATUS,CASE_FINAL_COMMENTS,REG_FEE,SR_NAME,SRO_NAME," +
	"PARTY_FIRST_NAME,PARTY_LAST_NAME,PARTY_ADDRESS,CREATED_BY,CREATED_DATE,CASE_ACTION_ID," +
	"PENALTY_ID,REVISION_NUMBER) VALUES(?,?,?,?,?,?,?,?,?,?,?,SYSDATE,?,?,?)";

        

    public static final String IGRS_REV_TXN_CMT=
        " UPDATE IGRS_CASE_TXN_COMMENTS SET CASE_ACTION_TXN_ID=?, USER_ID=?"+
        " WHERE CASE_TXN_ID=?";

    public static final String IGRS_CASE_REVENUE_REPORT = 
        " SELECT * FROM (SELECT A.PARA_COMMENTS, B.PHYSICAL_REPORT_ID,"+
        " C.DOCUMENT_ID, ROW_NUMBER() OVER(ORDER BY B.PHYSICAL_REPORT_ID)"+ 
        " RN FROM IGRS_AUDIT_PARA_MAPPING A, IGRS_RCPT_AUDIT_TXN B,"+ 
        " IGRS_AUDIT_PARA_OBJ_MAP C WHERE A.TRANSACTION_ID=B.TRANSACTION_ID"+
        " AND A.PARA_TXN_ID=C.PARA_TXN_ID";
    //added by shruti---22nd oct 2013
    public static final String IGRS_CASE_REVENUE_REPORT_NEW ="select a.transaction_id,b.PARA_TXN_ID,c.OBJECTION_TXN_ID,d.DOCUMENT_ID,d.OBJECTION_DETAILS,to_char(a.CREATED_DATE,'dd/mm/yyyy')"
 +" from IGRS_RAUDIT_TXN_DETAILS a,IGRS_RAUDIT_PARA_MAPPING b,"
+"IGRS_RAUDIT_PARA_OBJ_MAPPING c,IGRS_RAUDIT_PARA_OBJ_DETAILS d"
 +" where d.document_id is not null and d.objection_status='OPEN' and a.audit_report_status='O' and b.audit_txn_id=a.transaction_id"
  +" and c.para_txn_id=b.para_txn_id and d.objection_txn_id=c.objection_txn_id"; 
    
    public static final String IGRS_REVENUE_CLOSE_CASE = 
        " UPDATE IGRS_CASE_TXN_DETAILS SET CASE_STATUS=?,"+
        " CASE_FINAL_COMMENTS=? WHERE CASE_TXN_ID=? AND CASE_ACTION_ID=?";

    public static final String IGRS_REV_HRDATE = 
        " UPDATE IGRS_CASE_TXN_DETAILS SET NEXT_HEARING_DATE=?,"+
        " CASE_ACTION_ID=? WHERE CASE_TXN_ID=? AND CASE_ACTION_ID=?";

    public static final String IGRS_REV_ORDER_ID = "INSERT INTO"+
        " IGRS_CASE_ACTION_MAP (CASE_TXN_ID, CASE_ACTION_ID, CASE_ACTION_BY,"+
        " CASE_ACTION_DATE, CASE_ACTION_REMARKS, CREATED_DATE,"+
        " CASE_ACTION_TXN_ID) VALUES(?,?,?,?,?,?,?)";

    public static final String IGRS_REVENUE_INSERT_DRCMTONLY= "INSERT INTO"+
        " IGRS_CASE_TXN_COMMENTS (CASE_TXN_ID, CASE_ACTION_TXN_ID, USER_ID,"+
        " USER_COMMENTS, USER_COMMENTS_DATE) VALUES(?,?,?,?,SYSDATE)";

    public static final String IGRS_REVENUE_DR_LASTCMT= "SELECT CASE_TXN_ID,"+
        " CASE_ACTION_TXN_ID, USER_ID, USER_COMMENTS, USER_COMMENTS_DATE FROM"+
        " IGRS_CASE_TXN_COMMENTS WHERE CASE_TXN_ID=?"; 

    public static final String IGRS_REVENUE_ORDER= "SELECT A.CASE_TXN_ID,"+
        " A.CASE_STATUS, B.REVENUE_HEAD_NAME, C.SECTION_HEAD_NAME,"+
        " A.SPOT_INSP_TXN_ID, A.VALUATION_BY_DR,"+
        " TO_CHAR(A.NEXT_HEARING_DATE,'DD/MM/YY'),"+
        " A.PROPOSED_REG_FEE, A.PROPOSED_STAMP_DUTY, D.USER_COMMENTS FROM"+
        " IGRS_CASE_TXN_DETAILS A, IGRS_REVENUE_HEAD_MASTER B,"+
        " IGRS_SECTION_HEAD_MASTER C, IGRS_CASE_TXN_COMMENTS D WHERE"+
        " A.REVENUE_HEAD_ID=B.REVENUE_HEAD_ID AND"+
        " A.SECTION_HEAD_ID=C.SECTION_HEAD_ID AND D.CASE_TXN_ID=A.CASE_TXN_ID"+ 
        " AND A.CASE_TXN_ID=? AND A.CASE_ACTION_ID=?";

    public static final String IGRS_CASE_REVENUE_TOTAL_ROWS = 
        "SELECT COUNT(*) FROM IGRS_CASE_TXN_DETAILS WHERE";        

    public static final String IGRS_CASE_REVENUE_NOTICE=
        " SELECT * FROM (SELECT A.CASE_TXN_ID, A.DOC_ID,"+
        " C.CASE_ACTION_ID, TO_CHAR(A.CREATED_DATE,'DD/MM/YY'),"+
        " ROW_NUMBER() OVER(ORDER BY A.CASE_TXN_ID) RN FROM"+
        " IGRS_CASE_TXN_DETAILS A,"+
        " IGRS_CASE_ACTION_MASTER C WHERE";

    //Refund Module
    public static final String IGRS_REFUND_NOTICE=    
	"SELECT * FROM (SELECT A.CASE_TXN_ID, A.ESTAMP_ID, A.CASE_LAST_ACTION, TO_CHAR(A.CREATED_DATE,'DD/MM/YY'), ROW_NUMBER()"+
	" OVER(ORDER BY A.CASE_TXN_ID) RN FROM IGRS_CASE_REFUND_TXN A WHERE";
	
    public static final String NOTICE_DR_CMT=
    "SELECT CASE_TXN_ID,USER_ID,VALUATION_BY_DR,NEXT_HEARING_DATE,PROP_REG_FEE,PROP_STAMP_DUTY, SPOT_INSP_COMMENTS FROM IGRS_CASE_COMMENTS WHERE CASE_TXN_ID=?";

    public static final String NOTICE_DR_CMT_INSERT=
    "INSERT INTO IGRS_CASE_COMMENTS(CASE_TXN_ID,USER_ID,USER_COMMENTS,COMMENT_DATE,VALUATION_BY_DR,NEXT_HEARING_DATE,PROP_REG_FEE,PROP_STAMP_DUTY, SPOT_INSP_COMMENTS) VALUES(?,?,?,SYSDATE,?,?,?,?,?)";

    
    public static final String NOTICE_INSERT =
    "INSERT INTO  IGRS_CASE_REFUND_NOTICE_TXN (CASE_TXN_ID,NOTICE_DESCRIPTION,ISSUE_DATE,DR_USER_ID,CREATED_BY,CREATED_DATE,UPDATE_BY,UPDATE_DATE,NOTICE_TXN_ID,NOTICE_ID,CASE_NOTICE_STATUS,HEARING_DATE,RECEIVING_DATE) VALUES(?,?,?,?,?,SYSDATE,?,?,?,?,?,?,?) ";

    public static final String CASE_STATUS =
    "UPDATE IGRS_CASE_REFUND_TXN SET CASE_LAST_ACTION=? WHERE CASE_TXN_ID=?";
    
	public static final String IGRS_DRPROCESS_LASTACTION_TOTAL_ROWS = 
	"SELECT COUNT(*) FROM IGRS_CASE_REFUND_TXN WHERE ";            

	public static final String IGRS_DRPROCESS_LASTACTION_TOTAL_ROW = 
	"SELECT COUNT(*) FROM IGRS_CASE_TXN_DETAILS WHERE ";  
	
	public static final String IGRS_TOTAL_ROW = 
	"SELECT COUNT(*) FROM IGRS_CASE_TXN_DETAILS A,IGRS_CASE_TXN_DOC_DETAILS B, IGRS_CASE_ACTION_MASTER C,IGRS_AUDIT_PARA_OBJ_MAP D WHERE"+
	" A.CASE_TXN_ID=B.CASE_TXN_ID AND A.CASE_ACTION_ID=C.CASE_ACTION_ID  AND A.CASE_TXN_ID=D.CASE_ID AND";  
	
    public static final String IGRS_NOTICE_ONE=
    "SELECT A.CASE_TXN_ID, A.CASE_STATUS, F.REVENUE_HEAD_NAME, G.SECTION_HEAD_NAME," +
    " A.ESTAMP_ID, C.ESTAMP_TOTAL, B.PAYMENT_TYPE_ID, TO_CHAR(C.ESTAMP_DATE,'DD/MM/YY'), TO_CHAR(C.ESTAMP_VALIDITY_DATE,'DD/MM/YY')," + 
    " D.DEED_TYPE_NAME, E.PARTY_FIRST_NAME, E.PARTY_MIDDLE_NAME, E.PARTY_LAST_NAME, E.PARTY_ADDRESS, H.USER_COMMENTS " +    
    " FROM IGRS_CASE_REFUND_TXN A,IGRS_PAYMENT_MODE_DETAILS B,IGRS_ESTAMP_TXN_DETAILS C," +
    " IGRS_DEED_TYPE_MASTER D,IGRS_ESTAMP_TXN_PARTY_DETAILS E,IGRS_REVENUE_HEAD_MASTER F,"+
    " IGRS_SECTION_HEAD_MASTER G,IGRS_CASE_COMMENTS H, IGRS_ESTAMP_DEED_DETAILS I , IGRS_PAYMENT_TXN_DETAILS J WHERE D.DEED_TYPE_ID=I.ESTAMP_DEED_TYPE_ID " +
    " AND E.ESTAMP_TXN_ID = C.TRANSACTION_ID AND I.ESTAMP_TXN_ID=C.TRANSACTION_ID "  +
    " AND C.TRANSACTION_ID =A.ESTAMP_ID AND C.TRANSACTION_ID = J.TRANSACTION_ID AND J.PAY_MODE_TXN_ID = B.TRANSACTION_ID " +
    " AND A.REVENUE_HEAD_ID=F.REVENUE_HEAD_ID AND A.SECTION_HEAD_ID=G.SECTION_HEAD_ID AND A.CASE_TXN_ID=H.CASE_TXN_ID AND A.CASE_TXN_ID = ? ";

    public static final String IGRS_CASE_NOTICE_DRPROCESS= 
	"SELECT A.CASE_TXN_ID, A.CASE_STATUS, F.REVENUE_HEAD_NAME, G.SECTION_HEAD_NAME," +
	" A.ESTAMP_ID, C.ESTAMP_TOTAL, B.PAYMENT_TYPE_ID, TO_CHAR(C.ESTAMP_DATE,'DD/MM/YY'), TO_CHAR(C.ESTAMP_VALIDITY_DATE,'DD/MM/YY')," + 
	" D.DEED_TYPE_NAME, E.PARTY_FIRST_NAME, E.PARTY_MIDDLE_NAME, E.PARTY_LAST_NAME, E.PARTY_ADDRESS, H.USER_COMMENTS, " + 
	" K.NOTICE_TXN_ID, TO_CHAR(K.CREATED_DATE,'DD/MM/YY'),B.GROSS_AMOUNT"+   
	" FROM IGRS_CASE_REFUND_TXN A,IGRS_PAYMENT_MODE_DETAILS B,IGRS_ESTAMP_TXN_DETAILS C," +
	" IGRS_DEED_TYPE_MASTER D,IGRS_ESTAMP_TXN_PARTY_DETAILS E,IGRS_REVENUE_HEAD_MASTER F,"+
	" IGRS_SECTION_HEAD_MASTER G,IGRS_CASE_COMMENTS H, IGRS_ESTAMP_DEED_DETAILS I, IGRS_PAYMENT_TXN_DETAILS J,IGRS_CASE_REFUND_NOTICE_TXN k WHERE D.DEED_TYPE_ID=I.ESTAMP_DEED_TYPE_ID " +
	" AND E.ESTAMP_TXN_ID = C.TRANSACTION_ID AND I.ESTAMP_TXN_ID=C.TRANSACTION_ID "  +
	" AND C.TRANSACTION_ID =A.ESTAMP_ID AND C.TRANSACTION_ID = J.TRANSACTION_ID AND J.PAY_MODE_TXN_ID = B.TRANSACTION_ID " +
	" AND A.REVENUE_HEAD_ID=F.REVENUE_HEAD_ID AND A.SECTION_HEAD_ID=G.SECTION_HEAD_ID AND A.CASE_TXN_ID=H.CASE_TXN_ID AND K.CASE_TXN_ID=A.CASE_TXN_ID AND A.CASE_TXN_ID = ? ";
 
    public static final String IGRS_ORDER_ONE=
	"SELECT A.CASE_TXN_ID, A.CASE_STATUS, F.REVENUE_HEAD_NAME, G.SECTION_HEAD_NAME," +
	" A.ESTAMP_ID, C.ESTAMP_TOTAL, B.PAYMENT_TYPE_ID, TO_CHAR(C.ESTAMP_DATE,'DD/MM/YY'), TO_CHAR(C.ESTAMP_VALIDITY_DATE,'DD/MM/YY')," + 
	" D.DEED_TYPE_NAME, E.PARTY_FIRST_NAME, E.PARTY_MIDDLE_NAME, E.PARTY_LAST_NAME, E.PARTY_ADDRESS, H.USER_COMMENTS, " + 
	" K.NOTICE_TXN_ID, TO_CHAR(K.CREATED_DATE,'DD/MM/YY'),TO_CHAR(K.RECEIVING_DATE,'DD/MM/YY'),L.ORDER_TXN_ID, TO_CHAR(L.CREATED_DATE,'DD/MM/YY'), B.GROSS_AMOUNT "+   
	" FROM IGRS_CASE_REFUND_TXN A,IGRS_PAYMENT_MODE_DETAILS B,IGRS_ESTAMP_TXN_DETAILS C," +
	" IGRS_DEED_TYPE_MASTER D,IGRS_ESTAMP_TXN_PARTY_DETAILS E,IGRS_REVENUE_HEAD_MASTER F,"+
	" IGRS_SECTION_HEAD_MASTER G,IGRS_CASE_COMMENTS H, IGRS_ESTAMP_DEED_DETAILS I, IGRS_PAYMENT_TXN_DETAILS J,IGRS_CASE_REFUND_NOTICE_TXN k,IGRS_CASE_REFUND_ORDER_TXN L"+	
	" WHERE D.DEED_TYPE_ID=I.ESTAMP_DEED_TYPE_ID AND E.ESTAMP_TXN_ID = C.TRANSACTION_ID AND I.ESTAMP_TXN_ID=C.TRANSACTION_ID "  +
	" AND C.TRANSACTION_ID =A.ESTAMP_ID AND C.TRANSACTION_ID = J.TRANSACTION_ID AND J.PAY_MODE_TXN_ID = B.TRANSACTION_ID " +
	" AND A.REVENUE_HEAD_ID=F.REVENUE_HEAD_ID AND A.SECTION_HEAD_ID=G.SECTION_HEAD_ID AND A.CASE_TXN_ID=H.CASE_TXN_ID AND K.CASE_TXN_ID=A.CASE_TXN_ID AND L.CASE_TXN_ID=A.CASE_TXN_ID AND A.CASE_TXN_ID = ? ";
  
    public static final String FINAL_COMMENT =
    "UPDATE IGRS_CASE_REFUND_TXN SET FINAL_COMMENTS=?, CASE_STATUS=? WHERE CASE_TXN_ID =?";
    
    public static final String DELIVERY_STATUS=
    "UPDATE IGRS_CASE_REFUND_VOUCHER_TXN SET VOUCHER_STATUS=? WHERE CASE_TXN_ID=?";

    public static final String REC_DATE=
    "UPDATE IGRS_CASE_REFUND_ORDER_TXN SET RECEIVING_DATE=? WHERE CASE_TXN_ID=?";

    public static final String IGRS_CASE_DR_RECDATE_UPDATE = 
	"UPDATE IGRS_CASE_REFUND_NOTICE_TXN SET RECEIVING_DATE=? WHERE CASE_TXN_ID=?";

    public static final String IGRS_CASE_DRCMT_UPDATE_INSERT = 
	"INSERT INTO IGRS_CASE_COMMENTS(USER_COMMENTS, COMMENT_DATE,"+
    " VALUATION_BY_DR, NEXT_HEARING_DATE, PROP_REG_FEE, PROP_STAMP_DUTY, SPOT_INSP_COMMENTS, CASE_TXN_ID, USER_ID) VALUES(?,SYSDATE,?,?,?,?,?,?,?)";

    public static final String IGRS_CASE_VOUCHER_ID = 
	"INSERT INTO IGRS_CASE_REFUND_VOUCHER_TXN(VOUCHER_TXN_ID,CASE_TXN_ID,REFUND_AMOUNT,DEDUCTED_AMOUNT,DEDUCTION_PCT,VOUCHER_STATUS,CREATED_BY,CREATED_DATE,UPDATE_BY,UPDATE_DATE,USER_ID,ESTAMP_ID,REGISTRATION_INIT_ID) VALUES(?,?,?,?,?,?,?,SYSDATE,?,?,?,?,?)"; 

    public static final String IGRS_CASE_SAVE_VOUCHER_DETAIL = 
	"UPDATE IGRS_CASE_REFUND_TXN SET REFUND_AUTHORITY=?, CASE_LAST_ACTION=? WHERE CASE_TXN_ID=?";    

    public static final String IGRS_CASE_ORDER_ID = 
	"INSERT INTO IGRS_CASE_REFUND_ORDER_TXN(CASE_TXN_ID,ORDER_TXN_ID,ORDER_DESCRIPTION,ORDER_DATE,ORDER_ID,CASE_ORDER_STATUS,CREATED_BY,CREATED_DATE,UPDATE_BY,UPDATE_DATE,DR_USER_ID,HEARING_DATE,RECEIVING_DATE) VALUES(?,?,?,?,?,?,?,SYSDATE,?,?,?,?,?)";     

    public static final String IGRS_REFUND_ORDER_ONE=
	"SELECT A.CASE_TXN_ID, A.CASE_STATUS, F.REVENUE_HEAD_NAME, G.SECTION_HEAD_NAME," +
	" A.ESTAMP_ID, C.ESTAMP_TOTAL, B.PAYMENT_TYPE_ID, TO_CHAR(C.ESTAMP_DATE,'DD/MM/YY'), TO_CHAR(C.ESTAMP_VALIDITY_DATE,'DD/MM/YY')," + 
	" D.DEED_TYPE_NAME, E.PARTY_FIRST_NAME, E.PARTY_MIDDLE_NAME, E.PARTY_LAST_NAME, E.PARTY_ADDRESS, H.USER_COMMENTS, " + 
	" K.NOTICE_TXN_ID, TO_CHAR(K.CREATED_DATE,'DD/MM/YY'),TO_CHAR(K.RECEIVING_DATE,'DD/MM/YY'),L.ORDER_TXN_ID, TO_CHAR(L.CREATED_DATE,'DD/MM/YY'),"+
	" TO_CHAR(L.RECEIVING_DATE,'DD/MM/YY'),L.ORDER_TXN_ID, TO_CHAR(L.CREATED_DATE,'DD/MM/YY'),TO_CHAR(L.RECEIVING_DATE,'DD/MM/YY'),M.VOUCHER_TXN_ID, TO_CHAR(M.CREATED_DATE,'DD/MM/YY'), M.REFUND_AMOUNT, B.GROSS_AMOUNT "+
   
	" FROM IGRS_CASE_REFUND_TXN A,IGRS_PAYMENT_MODE_DETAILS B,IGRS_ESTAMP_TXN_DETAILS C," +
	" IGRS_DEED_TYPE_MASTER D,IGRS_ESTAMP_TXN_PARTY_DETAILS E,IGRS_REVENUE_HEAD_MASTER F,"+
	" IGRS_SECTION_HEAD_MASTER G,IGRS_CASE_COMMENTS H, IGRS_ESTAMP_DEED_DETAILS I, IGRS_PAYMENT_TXN_DETAILS J,IGRS_CASE_REFUND_NOTICE_TXN k,IGRS_CASE_REFUND_ORDER_TXN L, IGRS_CASE_REFUND_VOUCHER_TXN M"+
	
	" WHERE D.DEED_TYPE_ID=I.ESTAMP_DEED_TYPE_ID AND E.ESTAMP_TXN_ID = C.TRANSACTION_ID AND I.ESTAMP_TXN_ID=C.TRANSACTION_ID "  +
	" AND C.TRANSACTION_ID =A.ESTAMP_ID AND C.TRANSACTION_ID = J.TRANSACTION_ID AND J.PAY_MODE_TXN_ID = B.TRANSACTION_ID " +
	" AND A.REVENUE_HEAD_ID=F.REVENUE_HEAD_ID AND A.SECTION_HEAD_ID=G.SECTION_HEAD_ID AND A.CASE_TXN_ID=H.CASE_TXN_ID AND K.CASE_TXN_ID=A.CASE_TXN_ID AND L.CASE_TXN_ID=A.CASE_TXN_ID AND M.CASE_TXN_ID=A.CASE_TXN_ID AND A.CASE_TXN_ID = ? ";
   
    public static final String REC_NOTICE_DATE=
    "UPDATE IGRS_CASE_REFUND_NOTICE_TXN SET RECEIVING_DATE=? WHERE CASE_TXN_ID=?";

    public static final String IGRS_CASE_PRINT_ORDER_ONLY = 
	"SELECT T1.CASE_TXN_ID, T1.CASE_STATUS, T2.NOTICE_TXN_ID, TO_CHAR(T2.CREATED_DATE,'DD/MM/YY'), TO_CHAR(T2.RECEIVING_DATE,'DD/MM/YY'), TO_CHAR(T3.CREATED_DATE,'DD/MM/YY'), T3.ORDER_TXN_ID"+ 
    " FROM IGRS_CASE_REFUND_TXN T1, IGRS_CASE_REFUND_NOTICE_TXN T2, IGRS_CASE_REFUND_ORDER_TXN T3"+
    " WHERE T3.CASE_TXN_ID=T1.CASE_TXN_ID AND T1.CASE_TXN_ID=? AND T3.ORDER_TXN_ID=? AND T2.NOTICE_TXN_ID=?";

    public static final String IGRS_CASE_PRINT_ORDER = 
	"SELECT T1.CASE_TXN_ID, T1.CASE_STATUS, T2.NOTICE_TXN_ID, TO_CHAR(T2.CREATED_DATE,'DD/MM/YY'),"+
    " TO_CHAR(T2.RECEIVING_DATE,'DD/MM/YY'), T4.GROSS_AMOUNT, T6.REFUND_AMOUNT, TO_CHAR(T3.CREATED_DATE,'DD/MM/YY'), T3.ORDER_TXN_ID FROM IGRS_CASE_REFUND_TXN T1,"+
    " IGRS_CASE_REFUND_NOTICE_TXN T2, IGRS_CASE_REFUND_ORDER_TXN T3, IGRS_PAYMENT_MODE_DETAILS T4, IGRS_PAYMENT_TXN_DETAILS T5, IGRS_CASE_REFUND_VOUCHER_TXN T6"+   
    " WHERE T3.CASE_TXN_ID=T1.CASE_TXN_ID AND T1.CASE_TXN_ID=T6.CASE_TXN_ID AND T1.ESTAMP_ID=T5.TRANSACTION_ID AND T4.TRANSACTION_ID=T5.PAY_MODE_TXN_ID AND"+
    " T1.CASE_TXN_ID=? AND T2.NOTICE_TXN_ID=? AND T3.ORDER_TXN_ID=? AND T6.VOUCHER_TXN_ID=?";

    public static final String IGRS_CASE_PRINT_VOUCHER =
    "SELECT T1.CASE_TXN_ID, T1.CASE_STATUS, T2.NOTICE_TXN_ID, TO_CHAR(T2.CREATED_DATE,'DD/MM/YY'), TO_CHAR(T2.RECEIVING_DATE,'DD/MM/YY'), T4.GROSS_AMOUNT, T3.REFUND_AMOUNT,"+
    " TO_CHAR(T3.CREATED_DATE,'DD/MM/YY'), T3.VOUCHER_TXN_ID FROM IGRS_CASE_REFUND_TXN T1, IGRS_CASE_REFUND_NOTICE_TXN T2, IGRS_CASE_REFUND_VOUCHER_TXN T3, IGRS_PAYMENT_MODE_DETAILS T4,"+
    " IGRS_PAYMENT_TXN_DETAILS T5 WHERE T3.CASE_TXN_ID=T1.CASE_TXN_ID AND T1.ESTAMP_ID=T5.TRANSACTION_ID AND T4.TRANSACTION_ID=T5.PAY_MODE_TXN_ID AND T1.CASE_TXN_ID=? AND T2.NOTICE_TXN_ID=? AND T3.VOUCHER_TXN_ID=?";

	public static final String IGRS_ESTAMP_SEARCH_QUERY = 
	"SELECT * FROM (SELECT TRANSACTION_ID, TO_CHAR(ESTAMP_DATE,'dd/mm/yy'), ROW_NUMBER()"+
	" OVER(ORDER BY TRANSACTION_ID) RN FROM IGRS_ESTAMP_TXN_DETAILS";
	
	public static final String IGRS_ESTAMPID_DETAIL_QUERY_ONE = 
	"SELECT T1.TRANSACTION_ID, T1.ESTAMP_DUTY, T1.ESTAMP_OTHER_FEES, T1.ESTAMP_TOTAL,"+
	" T2.PARTY_FIRST_NAME, T2.PARTY_MIDDLE_NAME, T2.PARTY_LAST_NAME, T2.PARTY_GENDER, T2.PARTY_AGE, T2.GUARDIAN_NAME, T2.MOTHER_NAME, T2.PARTY_ADDRESS,"+
	" T2.DISTRICT_ID, T2.COUNTRY_ID, T2.STATE_ID, T2.POSTAL_CODE, T2.PHONE_NUMBER, T2.MOBILE_NUMBER, T2.EMAIL_ID, T2.PHOTO_PROOF_TYPE_ID, T2.PHOTO_PROOF_ID,"+
	" T3.DEED_TYPE_DESCRIPTION, TO_CHAR(T1.ESTAMP_DATE, 'DD/MM/YY'), TO_CHAR(T1.ESTAMP_VALIDITY_DATE,'DD/MM/YY'), T1.SECURED_AMOUNT, T5.GROSS_AMOUNT, T7.PAYMENT_TYPE_NAME, T3.DEED_TYPE_NAME"+
	" FROM IGRS_ESTAMP_TXN_DETAILS T1, IGRS_ESTAMP_TXN_PARTY_DETAILS T2, IGRS_DEED_TYPE_MASTER T3, IGRS_ESTAMP_DEED_DETAILS T4, IGRS_PAYMENT_MODE_DETAILS T5,"+ 
	" IGRS_PAYMENT_TXN_DETAILS T6,IGRS_PAYMENT_TYPE_MASTER T7 WHERE T2.ESTAMP_TXN_ID= T1.TRANSACTION_ID AND T3.DEED_TYPE_ID=T4.ESTAMP_DEED_TYPE_ID AND T4.ESTAMP_TXN_ID=T1.TRANSACTION_ID"+
	" AND T6.TRANSACTION_ID=T1.TRANSACTION_ID AND T5.TRANSACTION_ID=T6.PAY_MODE_TXN_ID AND T5.PAYMENT_TYPE_ID=T7.PAYMENT_TYPE_ID AND T1.TRANSACTION_ID=?";
	
	public static final String IGRS_CASE_OPTIONAL_INSERT = 
	"INSERT INTO IGRS_CASE_REFUND_TXN(CASE_TXN_ID, FINAL_COMMENTS, CREATED_BY, CREATED_DATE,"+
	" UPDATE_BY, UPDATE_DATE, FUNCTION_ID, CASE_STATUS, CASE_LAST_ACTION, REFUND_AUTHORITY, STAMP_OR_FEE, REVENUE_HEAD_ID, SECTION_HEAD_ID, ESTAMP_ID) VALUES(?,?,?,SYSDATE,?,?,?,?,?,?,?,?,?,?)"; 

	
	public static final String IGRS_ESTAMP_SEARCH_TOTAL_SIZE = 
	"SELECT COUNT(*) FROM IGRS_ESTAMP_TXN_DETAILS";
	
	public static final String IGRS_VIEW=    
	"SELECT IGRS_CASE_TXN_DETAILS.CASE_TXN_ID,"
	+"IGRS_CASE_TXN_DOC_DETAILS.DOC_TYPE_ID,"
    +"IGRS_CASE_ACTION_MASTER.CASE_ACTION_NAME,"
    +"IGRS_CASE_TXN_DETAILS.CASE_STATUS, "
    +"IGRS_CASE_ACTION_MASTER.CASE_ACTION_ID "
    +"FROM IGRS_CASE_TXN_DETAILS, "
    +"IGRS_CASE_TXN_DOC_DETAILS,IGRS_CASE_ACTION_MASTER"
    +" WHERE (IGRS_CASE_TXN_DETAILS.CASE_TXN_ID = "
    +"IGRS_CASE_TXN_DOC_DETAILS.CASE_TXN_ID) "
    +"AND (IGRS_CASE_ACTION_MASTER.CASE_ACTION_ID = "
    +"IGRS_CASE_TXN_DETAILS.CASE_ACTION_ID) " ;
	
	public static final String VIEW_NOTICE=
	"SELECT A.USER_COMMENTS, B.CASE_ACTION_REMARKS ,TO_CHAR(C.NEXT_HEARING_DATE,'DD/MM/YYYY')  FROM IGRS_CASE_TXN_COMMENTS A, IGRS_CASE_ACTION_MAP B, IGRS_CASE_TXN_DETAILS C WHERE C.CASE_TXN_ID=A.CASE_TXN_ID AND A.CASE_ACTION_TXN_ID=B.CASE_ACTION_TXN_ID AND C.CASE_TXN_ID = B.CASE_TXN_ID "+
	" AND C.CASE_TXN_ID=? AND B.CASE_ACTION_ID=?";	
		
	public static final String VIEW_ORDER=
	"SELECT A.USER_COMMENTS, B.CASE_ACTION_REMARKS ,TO_CHAR(B.CREATED_DATE,'DD/MM/YYYY'), TO_CHAR(C.NEXT_HEARING_DATE,'DD/MM/YYYY')  "+
	"FROM IGRS_CASE_TXN_COMMENTS A, IGRS_CASE_ACTION_MAP B, IGRS_CASE_TXN_DETAILS C  "+
	"WHERE C.CASE_TXN_ID=A.CASE_TXN_ID AND A.CASE_ACTION_TXN_ID=B.CASE_ACTION_TXN_ID AND C.CASE_TXN_ID = B.CASE_TXN_ID AND "+
	"C.CASE_TXN_ID=? AND B.CASE_ACTION_ID=? ";
		
	public static final String EX_PARTY_ORDER=
	"SELECT A.USER_COMMENTS, B.CASE_ACTION_REMARKS ,TO_CHAR(B.CREATED_DATE,'DD/MM/YYYY'), TO_CHAR(C.NEXT_HEARING_DATE,'DD/MM/YYYY')  "+
	"FROM IGRS_CASE_TXN_COMMENTS A, IGRS_CASE_ACTION_MAP B, IGRS_CASE_TXN_DETAILS C  "+
	"WHERE C.CASE_TXN_ID=A.CASE_TXN_ID AND A.CASE_ACTION_TXN_ID=B.CASE_ACTION_TXN_ID AND C.CASE_TXN_ID = B.CASE_TXN_ID AND "+
	"C.CASE_TXN_ID=? AND B.CASE_ACTION_ID=? ";
			
	public static final String DEMAND_NOTICE=
	"SELECT A.USER_COMMENTS, B.CASE_ACTION_REMARKS ,TO_CHAR(B.CREATED_DATE,'DD/MM/YYYY'), TO_CHAR(C.NEXT_HEARING_DATE,'DD/MM/YYYY')  "+
	"FROM IGRS_CASE_TXN_COMMENTS A, IGRS_CASE_ACTION_MAP B, IGRS_CASE_TXN_DETAILS C "+
	"WHERE C.CASE_TXN_ID=A.CASE_TXN_ID AND A.CASE_ACTION_TXN_ID=B.CASE_ACTION_TXN_ID AND C.CASE_TXN_ID = B.CASE_TXN_ID AND "+
	"C.CASE_TXN_ID=? AND B.CASE_ACTION_ID=? ";
			

	public static final String ATTACHMENT_ORDER=
	"SELECT A.USER_COMMENTS, B.CASE_ACTION_REMARKS ,TO_CHAR(B.CREATED_DATE,'DD/MM/YYYY'), TO_CHAR(C.NEXT_HEARING_DATE,'DD/MM/YYYY')  "+
	"FROM IGRS_CASE_TXN_COMMENTS A, IGRS_CASE_ACTION_MAP B, IGRS_CASE_TXN_DETAILS C "+
	"WHERE C.CASE_TXN_ID=A.CASE_TXN_ID AND A.CASE_ACTION_TXN_ID=B.CASE_ACTION_TXN_ID AND C.CASE_TXN_ID = B.CASE_TXN_ID AND "+
	" C.CASE_TXN_ID=? AND B.CASE_ACTION_ID=?";
			

	public static final String AUCTION_ORDER=
	"SELECT A.USER_COMMENTS, B.CASE_ACTION_REMARKS ,TO_CHAR(B.CREATED_DATE,'DD/MM/YYYY'), TO_CHAR(C.NEXT_HEARING_DATE,'DD/MM/YYYY')  "+
	"FROM IGRS_CASE_TXN_COMMENTS A, IGRS_CASE_ACTION_MAP B, IGRS_CASE_TXN_DETAILS C  "+
	"WHERE C.CASE_TXN_ID=A.CASE_TXN_ID AND A.CASE_ACTION_TXN_ID=B.CASE_ACTION_TXN_ID AND C.CASE_TXN_ID = B.CASE_TXN_ID AND "+
	"  C.CASE_TXN_ID=? AND B.CASE_ACTION_ID=?";
			

	public static final String REVENUE_COMMISION=
	"SELECT A.USER_COMMENTS, B.CASE_ACTION_REMARKS ,TO_CHAR(B.CREATED_DATE,'DD/MM/YYYY'), TO_CHAR(C.NEXT_HEARING_DATE,'DD/MM/YYYY')  "+
	"FROM IGRS_CASE_TXN_COMMENTS A, IGRS_CASE_ACTION_MAP B, IGRS_CASE_TXN_DETAILS C "+
	"WHERE C.CASE_TXN_ID=A.CASE_TXN_ID AND A.CASE_ACTION_TXN_ID=B.CASE_ACTION_TXN_ID AND C.CASE_TXN_ID = B.CASE_TXN_ID AND "+
	"  C.CASE_TXN_ID=? AND B.CASE_ACTION_ID=?";
			

	public static final String REVENUE_BOARD=
	"SELECT A.USER_COMMENTS, B.CASE_ACTION_REMARKS ,TO_CHAR(B.CREATED_DATE,'DD/MM/YYYY'), TO_CHAR(C.NEXT_HEARING_DATE,'DD/MM/YYYY')  "+
	"FROM IGRS_CASE_TXN_COMMENTS A, IGRS_CASE_ACTION_MAP B, IGRS_CASE_TXN_DETAILS C "+
	"WHERE C.CASE_TXN_ID=A.CASE_TXN_ID AND A.CASE_ACTION_TXN_ID=B.CASE_ACTION_TXN_ID AND C.CASE_TXN_ID = B.CASE_TXN_ID AND "+
	"  C.CASE_TXN_ID=? AND B.CASE_ACTION_ID=?";
			

	public static final String HIGH_COURT=
	"SELECT A.USER_COMMENTS, B.CASE_ACTION_REMARKS ,TO_CHAR(B.CREATED_DATE,'DD/MM/YYYY'), TO_CHAR(C.NEXT_HEARING_DATE,'DD/MM/YYYY')  "+
	"FROM IGRS_CASE_TXN_COMMENTS A, IGRS_CASE_ACTION_MAP B, IGRS_CASE_TXN_DETAILS C  "+
	"WHERE C.CASE_TXN_ID=A.CASE_TXN_ID AND A.CASE_ACTION_TXN_ID=B.CASE_ACTION_TXN_ID AND C.CASE_TXN_ID = B.CASE_TXN_ID AND "+
	"  C.CASE_TXN_ID=? AND B.CASE_ACTION_ID=? ";
			

	public static final String SUPREME_COURT=	
	"SELECT A.USER_COMMENTS, B.CASE_ACTION_REMARKS ,TO_CHAR(B.CREATED_DATE,'DD/MM/YYYY'), TO_CHAR(C.NEXT_HEARING_DATE,'DD/MM/YYYY')  "+
	"FROM IGRS_CASE_TXN_COMMENTS A, IGRS_CASE_ACTION_MAP B, IGRS_CASE_TXN_DETAILS C "+
	"WHERE C.CASE_TXN_ID=A.CASE_TXN_ID AND A.CASE_ACTION_TXN_ID=B.CASE_ACTION_TXN_ID AND C.CASE_TXN_ID = B.CASE_TXN_ID AND "+
	"  C.CASE_TXN_ID=? AND B.CASE_ACTION_ID=? ";
			

	public static final String CLOSE_STATE=	
	"SELECT A.USER_COMMENTS, B.CASE_ACTION_REMARKS ,TO_CHAR(B.CREATED_DATE,'DD/MM/YYYY'), TO_CHAR(C.NEXT_HEARING_DATE,'DD/MM/YYYY'), C.CASE_FINAL_COMMENTS  "+
	"FROM IGRS_CASE_TXN_COMMENTS A, IGRS_CASE_ACTION_MAP B, IGRS_CASE_TXN_DETAILS C "+
	"WHERE C.CASE_TXN_ID=A.CASE_TXN_ID AND A.CASE_ACTION_TXN_ID=B.CASE_ACTION_TXN_ID AND C.CASE_TXN_ID = B.CASE_TXN_ID AND "+
	" C.CASE_TXN_ID=? AND C.CASE_STATUS=? ";
	
		
	public static final String IGRS_ADD_CMT=    
	"SELECT * FROM (SELECT A.CASE_TXN_ID, A.DOC_ID, C.CASE_ACTION_NAME,TO_CHAR(D.OBJECTION_DATE,'DD/MM/YYYY'), ROW_NUMBER()"+
	" OVER(ORDER BY A.CASE_TXN_ID) RN FROM IGRS_CASE_TXN_DETAILS A, IGRS_CASE_ACTION_MASTER C,IGRS_AUDIT_PARA_OBJ_MAP D WHERE"+
	" A.CASE_ACTION_ID=C.CASE_ACTION_ID  AND A.CASE_TXN_ID=D.CASE_ID AND ";		

	public static final String COMMENT_UPDATE=
	"SELECT A.CASE_TXN_ID, A.CASE_STATUS, B.REVENUE_HEAD_NAME, C.SECTION_HEAD_NAME, A.SPOT_INSP_TXN_ID, A.VALUATION_BY_DR, TO_CHAR(A.NEXT_HEARING_DATE,'DD/MM/YY'), A.PROPOSED_REG_FEE, A.PROPOSED_STAMP_DUTY, D.USER_COMMENTS "+
	"FROM IGRS_CASE_TXN_DETAILS A, IGRS_REVENUE_HEAD_MASTER B, IGRS_SECTION_HEAD_MASTER C, IGRS_CASE_TXN_COMMENTS D, IGRS_CASE_ACTION_MAP E "+ 
	"WHERE A.REVENUE_HEAD_ID=B.REVENUE_HEAD_ID AND A.SECTION_HEAD_ID=C.SECTION_HEAD_ID AND A.CASE_TXN_ID=D.CASE_TXN_ID AND A.CASE_TXN_ID=E.CASE_TXN_ID AND D.CASE_ACTION_TXN_ID=E.CASE_ACTION_TXN_ID  AND E.CASE_ACTION_ID='Initiate' AND A.CASE_TXN_ID=? ";		
			
	public static final String CMT_DETAIL =
	"SELECT A.CASE_ACTION_NAME, A.CASE_ACTION_DESC, TO_CHAR(B.NEXT_HEARING_DATE,'DD/MM/YYYY') FROM IGRS_CASE_ACTION_MASTER A, IGRS_CASE_TXN_DETAILS B"+
	" WHERE A.CASE_ACTION_ID=B.CASE_ACTION_ID AND B.CASE_TXN_ID=?";	
    
	public static final String ADD_COMPLIANCE =
	"UPDATE IGRS_CASE_TXN_DETAILS SET COMPLIANCE_DETAILS=? WHERE CASE_TXN_ID=?";	
	
	//added by shruti
	  public static final String SELECTDRDISTRICT ="select DISTRICT_ID,DISTRICT_NAME FROM IGRS_DISTRICT_MASTER"
		  +" WHERE DISTRICT_STATUS='A' AND DISTRICT_ID=(SELECT IGRS_OFFICE_MASTER.DISTRICT_ID FROM IGRS_OFFICE_MASTER,"
		  +" IGRS_EMP_OFFICE_MAPPING WHERE IGRS_OFFICE_MASTER.OFFICE_ID=IGRS_EMP_OFFICE_MAPPING.OFFICE_ID"
		  	  +" AND IGRS_EMP_OFFICE_MAPPING.EMP_ID=?)";
	  
	  public static final String GET_REG_ID ="select IGRS_REG_TXN_DETLS.REG_TXN_ID from IGRS_REG_TXN_DETLS,IGRS_CASE_TIME_BARRED_APP where IGRS_CASE_TIME_BARRED_APP.REG_TXN_ID=IGRS_REG_TXN_DETLS.REG_TXN_ID and IGRS_CASE_TIME_BARRED_APP.PENALTY_ID=?";
	  
	  
	  public static final String SELECTDRDISTRICTNEW ="select DISTRICT_ID,DISTRICT_NAME FROM IGRS_DISTRICT_MASTER"
		  +" WHERE DISTRICT_STATUS='A' AND DISTRICT_ID=(SELECT IGRS_OFFICE_MASTER.DISTRICT_ID FROM IGRS_OFFICE_MASTER"
		  + " WHERE OFFICE_ID=?)";
	  
/*	  public static final String SELECTCASEREGDET="select DISTRICT_NAME,TO_CHAR(SYSDATE,'DD/MM/YYYY') FROM IGRS_DISTRICT_MASTER"
		  +" WHERE DISTRICT_STATUS='A' AND DISTRICT_ID=(SELECT IGRS_OFFICE_MASTER.DISTRICT_ID FROM IGRS_OFFICE_MASTER,"
		  +" IGRS_EMP_OFFICE_MAPPING WHERE IGRS_OFFICE_MASTER.OFFICE_ID=IGRS_EMP_OFFICE_MAPPING.OFFICE_ID"
		  	  +" AND IGRS_EMP_OFFICE_MAPPING.EMP_ID=?)";*/
	  
	  public static final String SELECTCASEREGDET="select DISTRICT_NAME,TO_CHAR(SYSDATE,'DD/MM/YYYY') FROM IGRS_DISTRICT_MASTER"
	  +" WHERE DISTRICT_STATUS='A' AND DISTRICT_ID=(SELECT IGRS_OFFICE_MASTER.DISTRICT_ID FROM IGRS_OFFICE_MASTER" 
	  +" WHERE IGRS_OFFICE_MASTER.OFFICE_ID=?)";
	  
	  public static final String SELECTCASEREGDET_H="select H_DISTRICT_NAME,TO_CHAR(SYSDATE,'DD/MM/YYYY') FROM IGRS_DISTRICT_MASTER"
		  +" WHERE DISTRICT_STATUS='A' AND DISTRICT_ID=(SELECT IGRS_OFFICE_MASTER.DISTRICT_ID FROM IGRS_OFFICE_MASTER" 
		  +" WHERE IGRS_OFFICE_MASTER.OFFICE_ID=?)";
	  
	  public static final String INSERT_ACTION_MAP="INSERT INTO IGRS_CASE_ACTION_MAP(CASE_TXN_ID,CASE_ACTION_ID,CASE_ACTION_BY,CASE_ACTION_DATE,CASE_ACTION_REMARKS,CREATED_DATE,CASE_ACTION_TXN_ID,CREATED_BY,CREATED_DATE) VALUES (?,?,?,SYSDATE,?,SYSDATE,?,?,SYSDATE)";

	  public static final String GETAUDITINPECTIONDETAILS="SELECT (select first_name||' '||middle_name||' '||last_name from IGRS_EMP_MASTER iurd where iurd.EMP_ID=irat.SR_USER_ID),"
		  +"(select OFFICE_NAME FROM IGRS_OFFICE_MASTER iom WHERE iom.OFFICE_ID=irat.SRO_ID),"
		  +"to_char(irat.AUDIT_DATE,'dd/mm/yyyy'),irat.PHYSICAL_REPORT_ID"
	  		+",iapom.VALUATION_AT_REG_TIME,iapom.VALUATION_FROM_AGMP,iapom.DEFICIENT_STAMP_DUTY," 
	  		+"iapom.DEFICIENT_REG_FEE FROM IGRS_RCPT_AUDIT_TXN irat,IGRS_AUDIT_PARA_OBJ_MAP iapom," 
	  		+"IGRS_AUDIT_PARA_MAPPING iapm where iapm.TRANSACTION_ID=irat.TRANSACTION_ID " 
	  				+"and iapm.PARA_TXN_ID=iapom.PARA_TXN_ID and irat.PHYSICAL_REPORT_ID=?";
	  
	  //added---22nd oct 2013
	  public static final String GETAUDITINPECTIONDETAILSNEW="select to_char(a.audit_date,'dd/mm/yyyy'),a.transaction_id,b.document_id,"
	  +"b.VALUATION_AT_REG_TIME,b.DEFICIENT_STAMP_DUTY,b.DEFICIENT_REG_FEE,b.VALUATION_FROM_AGMP"
	   +" from IGRS_RAUDIT_TXN_DETAILS a,IGRS_RAUDIT_PARA_OBJ_DETAILS b where A.transaction_id=? and b.objection_txn_id=?";
	  //end
	  
	  public static final String GET_AUDIT_DATE=" SELECT to_char(to_date(INSP_DATE,'dd/mm/yyyy'),'dd/mm/yyyy'), PO_NAME FROM IGRS_POI_TXN_DTLS WHERE POI_TXN_ID=?";
	  public static final String GET_REG_STAMP_DUTY="SELECT DEFICIENT_STAMP_DUTY FROM IGRS_POI_PARA_OBJ_DTLS, IGRS_POI_COMMENT_MAP WHERE IGRS_POI_PARA_OBJ_DTLS.OBJ_TXN_ID=igrs_poi_comment_map.obj_txn_id AND igrs_poi_comment_map.poi_txn_id=? AND IGRS_POI_COMMENT_MAP.PARA_TXN_ID=?";
	  public static final String GETREGDETAILS="SELECT A.FINAL_MARKET_VALUE,  A.STAMP_DUTY,  A.REG_FEE,  nvl(B.SR_NAME,'-'),  nvl(B.SRO_NAME,'-'),  TO_CHAR(B.UPDATE_DATE,'DD/MM/YYYY') FROM IGRS_REG_CHK_STAMP_DUTY_DTLS A,  IGRS_REG_TXN_DETLS B WHERE A.REG_TXN_ID       =B.REG_TXN_ID AND B.REGISTRATION_NUMBER=?";
	  
	  public static final String GETREGDETAILSTIME_BARRED="SELECT A.FINAL_MARKET_VALUE,  A.STAMP_DUTY,  A.REG_FEE,  nvl(B.SR_NAME,'-'),  nvl(B.SRO_NAME,'-'),  TO_CHAR(B.UPDATE_DATE,'DD/MM/YYYY') FROM IGRS_REG_CHK_STAMP_DUTY_DTLS A,  IGRS_REG_TXN_DETLS B WHERE A.REG_TXN_ID       =B.REG_TXN_ID AND B.REG_TXN_ID=?";
	  
	  public static final String GETREGPARTYDETAILS="SELECT PARTY_FIRST_NAME,PARTY_LAST_NAME FROM IGRS_REG_TXN_PARTY_DETLS WHERE REG_TXN_ID =?";
	  
	  public static final String GETPOTDETAILS="SELECT pomain.PO_COMMENTS,  TO_CHAR(pomain.UPDATE_DATE,'dd/mm/yyyy'),  pomain.STAMP_FEE_REQUIRED,  pomain.SR,  pomain.SRO,  dist.DISTRICT_NAME,  dist.H_DISTRICT_NAME FROM IGRS_PUBLIC_OFFICER_TOOL_TXN pomain ,  IGRS_DISTRICT_MASTER dist WHERE pomain.DISTRICT_ID  =dist.DISTRICT_ID AND pomain.TRANSACTION_ID =?";
	  
	  public static final String GET_USERNAME="SELECT USER1.FIRST_NAME  ||' '  ||NVL(USER1.MIDDLE_NAME,'')  ||' '  ||USER1.LAST_NAME FROM   IGRS_USER_REG_DETAILS USER1 WHERE USER1.USER_ID  =?";
	  public static final String GET_OFCNAME="SELECT NVL(OFFC.OFFICE_NAME,'') FROM   IGRS_OFFICE_MASTER OFFC WHERE OFFC.OFFICE_ID =?";
	  public static final String GET_OFCNAME_hi="SELECT NVL(OFFC.H_OFFICE_NAME,'') FROM   IGRS_OFFICE_MASTER OFFC WHERE OFFC.OFFICE_ID =?";
	  
	  public static final String GET_POT_PHYSICAL_STAMP_DETAILS="SELECT PSTAMP_CODE FROM IGRS_POT_PSTAMP_DETAILS WHERE POT_ID=?";
	  
	  public static final String GET_ESTAMP_CODE_FOR_CASE_ID="SELECT ESTAMP_CODE FROM IGRS_PUBLIC_OFFICER_TOOL_TXN WHERE CASE_ID=?";
	  
	  public static final String GETESTAMPAMOUNTDETAILS="SELECT ESTAMP_AMOUNT FROM IGRS_ESTAMP_DETLS WHERE ESTAMP_CODE=?";
	 
	  //ADDED BY SHRUTI----14 OCT 2014
	  public static final String GETPENALTYAMOUNT="SELECT AMOUNT_TO_BE_PAID FROM IGRS_CASE_TIME_BARRED_APP WHERE PENALTY_ID=?";
	  //END
	  //GETPENALTYDURATIONCHK changed by roopam on 24Jan2015 for time barred duration chk
	//GETPENALTYDURATIONCHK again changed by roopam on 27Jan2015 for time barred duration chk day count
	  public static final String GETPENALTYDURATIONCHK="SELECT ((TRUNC((to_date(sysdate,'dd-Mon-yy')-to_date(to_char(DEED_EXECUTION_DATE,'dd-Mon-yy'),'dd-Mon-yy' ))))-120) final_months FROM igrs_case_time_barred_app,  IGRS_REG_TXN_DETLS WHERE penalty_id =? AND igrs_case_time_barred_app.REG_TXN_ID=IGRS_REG_TXN_DETLS.REG_TXN_ID";
	//  public static final String GETPENALTYDURATIONCHK="select (trunc(months_between(sysdate,DEED_EXECUTION_DATE))-4) final_months from igrs_case_time_barred_app,IGRS_REG_TXN_DETLS where penalty_id=? and igrs_case_time_barred_app.REG_TXN_ID=IGRS_REG_TXN_DETLS.REG_TXN_ID";
	  
	  public static final String GETREGDETAILSIMPOUNDCASE="SELECT A.TOTAL,A.STAMP_DUTY,A.REG_FEE,B.SR_NAME,B.SRO_NAME,to_char(B.created_DATE,'DD/MM/YYYY') FROM IGRS_REG_INIT_STAMP_DUTY_DETLS A,IGRS_REG_TXN_DETLS B WHERE A.REG_TXN_ID=B.REG_TXN_ID AND B.REG_TXN_ID=(SELECT REG_TXN_ID FROM IGRS_CASE_IMPOUND_DOCUMENT WHERE COMPLAINT_ID=?)";
	  
		public static final String IGRS_CASE_OPTIONAL_INSERT1 = 
			"INSERT INTO IGRS_CASE_TXN_DETAILS(CASE_TXN_ID, CREATED_BY, CREATED_DATE,"+
			" UPDATE_BY, UPDATE_DATE,ESTAMP_CODE,REVENUE_HEAD_ID, SECTION_HEAD_ID, CASE_STATUS,CASE_LAST_ACTION,CASE_HEAD_ID,CASE_TYPE_ID,CASE_ACTION_ID,PARTY_FIRST_NAME,PARTY_MID_NAME,PARTY_LAST_NAME,PARTY_ADDRESS,RULE_120) VALUES(?,?,SYSDATE,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"; 
		
		
		public static final String IGRS_VIEW1=    
		"SELECT IGRS_CASE_TXN_DETAILS.CASE_TXN_ID,'-'," 
		+"IGRS_CASE_ACTION_MASTER.CASE_ACTION_NAME,IGRS_CASE_TXN_DETAILS.CASE_STATUS," 
		+"IGRS_CASE_ACTION_MASTER.CASE_ACTION_ID,to_char(IGRS_CASE_TXN_DETAILS.CREATED_DATE,'dd/mm/yyyy') FROM IGRS_CASE_TXN_DETAILS,IGRS_CASE_ACTION_MASTER WHERE" 
		+" IGRS_CASE_ACTION_MASTER.CASE_ACTION_ID = IGRS_CASE_TXN_DETAILS.CASE_ACTION_ID";
		
		public static final String IGRS_VIEW2=    
			"SELECT IGRS_CASE_REFUND_TXN_DTLS.CASE_TXN_ID,'-'," 
			+"IGRS_CASE_ACTION_MASTER.CASE_ACTION_NAME,IGRS_CASE_REFUND_TXN_DTLS.CASE_STATUS," 
			+"IGRS_CASE_ACTION_MASTER.CASE_ACTION_ID,to_char(IGRS_CASE_REFUND_TXN_DTLS.CREATED_DATE,'dd/mm/yyyy') FROM IGRS_CASE_REFUND_TXN_DTLS,IGRS_CASE_ACTION_MASTER WHERE" 
			+" IGRS_CASE_ACTION_MASTER.CASE_ACTION_ID = IGRS_CASE_REFUND_TXN_DTLS.CASE_ACTION_ID";
		
		public static final String IGRS_VIEW3=    
			"SELECT IGRS_CASE_OTHERS_TXN_DTLS.CASE_TXN_ID,'-'," 
			+"IGRS_CASE_ACTION_MASTER.CASE_ACTION_NAME,IGRS_CASE_OTHERS_TXN_DTLS.CASE_STATUS," 
			+"IGRS_CASE_ACTION_MASTER.CASE_ACTION_ID,to_char(IGRS_CASE_OTHERS_TXN_DTLS.CREATED_DATE,'dd/mm/yyyy') FROM IGRS_CASE_OTHERS_TXN_DTLS,IGRS_CASE_ACTION_MASTER WHERE" 
			+" IGRS_CASE_ACTION_MASTER.CASE_ACTION_ID = IGRS_CASE_OTHERS_TXN_DTLS.CASE_ACTION_ID";
		
		public static final String IGRS_VIEW4=    
			"SELECT IGRS_CASE_REV_PNLTY_TXN_DTLS.CASE_TXN_ID,'-'," 
			+"IGRS_CASE_ACTION_MASTER.CASE_ACTION_NAME,IGRS_CASE_REV_PNLTY_TXN_DTLS.CASE_STATUS," 
			+"IGRS_CASE_ACTION_MASTER.CASE_ACTION_ID,to_char(IGRS_CASE_REV_PNLTY_TXN_DTLS.CREATED_DATE,'dd/mm/yyyy') FROM IGRS_CASE_REV_PNLTY_TXN_DTLS,IGRS_CASE_ACTION_MASTER WHERE" 
			+" IGRS_CASE_ACTION_MASTER.CASE_ACTION_ID = IGRS_CASE_REV_PNLTY_TXN_DTLS.CASE_ACTION_ID";
		
		public static final String IGRS_VIEW5=    
			"SELECT IGRS_CASE_PNLTY70_TXN_DTLS.CASE_TXN_ID,'-'," 
			+"IGRS_CASE_ACTION_MASTER.CASE_ACTION_NAME,IGRS_CASE_PNLTY70_TXN_DTLS.CASE_STATUS," 
			+"IGRS_CASE_ACTION_MASTER.CASE_ACTION_ID,to_char(IGRS_CASE_PNLTY70_TXN_DTLS.CREATED_DATE,'dd/mm/yyyy') FROM IGRS_CASE_PNLTY70_TXN_DTLS,IGRS_CASE_ACTION_MASTER WHERE" 
			+" IGRS_CASE_ACTION_MASTER.CASE_ACTION_ID = IGRS_CASE_PNLTY70_TXN_DTLS.CASE_ACTION_ID";
		
		
		public static final String CASE_DETAIL=
		"SELECT A.CASE_TXN_ID, A.CASE_STATUS, B.REVENUE_HEAD_NAME, C.SECTION_HEAD_NAME, A.SPOT_INSP_TXN_ID, A.VALUATION_BY_DR, TO_CHAR(A.NEXT_HEARING_DATE,'DD/MM/YY'), A.PROPOSED_REG_FEE, A.PROPOSED_STAMP_DUTY, D.USER_COMMENTS "+
		"FROM IGRS_CASE_TXN_DETAILS A, IGRS_REVENUE_HEAD_MASTER B, IGRS_SECTION_HEAD_MASTER C, IGRS_CASE_TXN_COMMENTS D, IGRS_CASE_ACTION_MAP E "+ 
		"WHERE A.REVENUE_HEAD_ID=B.REVENUE_HEAD_ID AND A.SECTION_HEAD_ID=C.SECTION_HEAD_ID AND A.CASE_TXN_ID=D.CASE_TXN_ID AND A.CASE_TXN_ID=E.CASE_TXN_ID AND D.CASE_ACTION_TXN_ID=E.CASE_ACTION_TXN_ID  AND A.CASE_TXN_ID=? AND E.CASE_ACTION_ID=? ";		
			
		
		public static final String CASE_DETAIL1=
			"SELECT A.CASE_TXN_ID, A.CASE_STATUS, B.REVENUE_HEAD_NAME, C.SECTION_HEAD_NAME, A.SPOT_INSP_DETAILS, A.VALUATION_BY_DR, TO_CHAR(A.NEXT_HEARING_DATE,'DD/MM/YY'), A.PROPOSED_REG_FEE, A.PROPOSED_STAMP_DUTY, D.USER_COMMENTS "+
			"FROM IGRS_CASE_TXN_DETAILS A, IGRS_CASE_REVENUE_HEAD_MASTER B, IGRS_CASE_SECTION_HEAD_MASTER C, IGRS_CASE_TXN_COMMENTS D, IGRS_CASE_ACTION_MAP E "+ 
			"WHERE A.REVENUE_HEAD_ID=B.REVENUE_HEAD_ID AND A.SECTION_HEAD_ID=C.SECTION_HEAD_ID AND A.CASE_TXN_ID=D.CASE_TXN_ID AND A.CASE_TXN_ID=E.CASE_TXN_ID AND D.CASE_ACTION_TXN_ID=E.CASE_ACTION_TXN_ID  AND A.CASE_TXN_ID=? AND E.CASE_ACTION_ID=? ";		
	  
		public static final String CLOSE_STATE1=	
			"SELECT A.USER_COMMENTS, B.CASE_ACTION_REMARKS ,TO_CHAR(B.CREATED_DATE,'DD/MM/YYYY'), TO_CHAR(C.NEXT_HEARING_DATE,'DD/MM/YYYY'), C.CASE_FINAL_COMMENTS  "+
			"FROM IGRS_CASE_TXN_COMMENTS A, IGRS_CASE_ACTION_MAP B, IGRS_CASE_TXN_DETAILS C "+
			"WHERE C.CASE_TXN_ID=A.CASE_TXN_ID AND A.CASE_ACTION_TXN_ID=B.CASE_ACTION_TXN_ID AND C.CASE_TXN_ID = B.CASE_TXN_ID AND "+
			" C.CASE_TXN_ID=? AND C.CASE_ACTION_ID=? ";	
		
	    public static final String INSERT_CASE_TXN_COMMENTS="INSERT INTO IGRS_CASE_TXN_COMMENTS(CASE_TXN_ID,CASE_ACTION_TXN_ID,USER_ID,USER_COMMENTS,USER_COMMENTS_DATE) VALUES(?,?,?,?,SYSDATE)";
	    //end
	    public static final String GETESTAMPTXNID="SELECT ESTAMP_TXN_ID FROM IGRS_ESTAMP_DEACTIVATION_DETLS WHERE DEACT_REQUEST_ID=?";
	  
	    public static final String GETESTAMPTXNDETAILS="select ied.ESTAMP_ISSUED_BY,ied.ESTAMP_ISSUED_OFFICE,iedd.PERSON_NAME,iedd.ADDRESS,ied.ESTAMP_AMOUNT,icpl.ATTRIBUTE_VALUE" 
	    	+" from IGRS_ESTAMP_DETLS  ied,IGRS_ESTAMP_DEACTIVATION_DETLS iedd,IGRS_CONFIG_PARAM_LIST icpl where ied.ESTAMP_TXN_ID=?"
	    	+" and iedd.ESTAMP_TXN_ID=? and icpl.ATTRIBUTE_NAME='ESTAMP REFUND PARAM'";
	    
	    public static final String GETPENALTYREVISION45="SELCT CASE_TXN_ID FROM IGRS_CASE_OTHERS_TXN_DTLS WHERE PENALTY_ID=? OR CASE_TXN_ID=?";
	    
	    public static final String GETCASENOSEQNO="SELECT IGRS_CASE_NO_SEQ.NEXTVAL FROM DUAL";
	    public static final String GETRRCCASENOSEQNO="SELECT IGRS_RRC_CASE_NO_SEQ.NEXTVAL FROM DUAL";
	    
	    public static final String GETREVISIONSEQNO="SELECT IGRS_REVISION_NO_SEQ.NEXTVAL FROM DUAL";
	    public static final String GETREVISIONSEC70SEQNO="SELECT IGRS_REVISION_SEC70_NO_SEQ.NEXTVAL FROM DUAL";
	    
	    public static final String GETREVENUEHEADNAME="SELECT REVENUE_HEAD_NAME FROM IGRS_CASE_REVENUE_HEAD_MASTER WHERE REVENUE_HEAD_ID=?";

	    public static final String IGRS_CASE_OTHERS_INSERT="INSERT INTO IGRS_CASE_OTHERS_TXN_DTLS (SR_NO, CASE_TXN_ID, CASE_HEAD_ID," 
   +"CASE_TYPE_ID, REVENUE_HEAD_ID, SECTION_HEAD_ID, CASE_STATUS, CASE_FINAL_COMMENTS, RRC_CASE," 
   +"PENALTY_AMOUNT, SR_NAME, SRO_NAME, CREATED_BY, CREATED_DATE, CASE_ACTION_ID, PENALTY_ID)" 
 +" VALUES ( ?,?,?,?,? ,? ,? ,?,? ,?,?,? ,? ,SYSDATE ,?,? )";
	    
	    public static final String IGRS_UPDATE_OPEN_CASE_TIME_BARRED="UPDATE IGRS_CASE_TIME_BARRED_APP SET STATUS='O' WHERE PENALTY_ID=?";

public static final String GETRRCCRITERIA="select ATTRIBUTE_VALUE from IGRS_CONFIG_PARAM_LIST where ATTRIBUTE_NAME='CM MONTH' and FUNCTION_ID='FUN_042'";

public static final String GETRRCDUEDETAILS="select to_char(created_date,'dd/mm/yyyy') from IGRS_CASE_ACTION_MAP where case_txn_id=? and case_action_id in('CASE_003','CASE_002')";

public static final String UPDATERRCCASENUMBER="update IGRS_CASE_TXN_DETAILS set RRC_CASE=? where case_txn_id=?";

public static final String UPDATERRCDTLS="insert into IGRS_CASE_TXN_COMMENTS(SR_NO,CASE_TXN_ID,CASE_ACTION_TXN_ID,CREATED_BY,CREATED_DATE,ACTION_DATE,ACTION_DESC) VALUES(?,?,?,?,SYSDATE,to_date(SYSDATE,'dd/mm/yyyy'),?)";
public static final String GETCASENUMBER="SELECT CASE_TXN_ID FROM IGRS_CASE_TXN_DETAILS WHERE RRC_CASE=?";
public static final String GETRRCID="SELECT RRC_CASE FROM IGRS_CASE_TXN_DETAILS WHERE CASE_TXN_ID=?";

public static final String GETREGTXNIDFORIMPONDEDDOC="select REG_TXN_ID from IGRS_CASE_IMPOUND_DOCUMENT where COMPLAINT_ID=?";

/*public static final String GETREGDATAFORIMPOUNDEDDOC= "SELECT created_by,REG_TXN_ID,PARTY_FIRST_NAME,PARTY_MIDDLE_NAME,PARTY_LAST_NAME,TO_CHAR(CREATED_DATE,'DD/MM/YYYY')" 
	 +" FROM(SELECT created_by,REG_TXN_ID,PARTY_FIRST_NAME,PARTY_MIDDLE_NAME,PARTY_LAST_NAME,CREATED_DATE FROM IGRS_REG_TXN_PARTY_DETLS T"
	 +" WHERE REG_TXN_ID=? ORDER BY CREATED_DATE ASC) where rownum<=1";*/

public static final String GETBUYERTXNPARTY="SELECT created_by,REG_TXN_ID,PARTY_FIRST_NAME,PARTY_MIDDLE_NAME,PARTY_LAST_NAME,ORGANIZATION_NAME,TO_CHAR(CREATED_DATE,'DD/MM/YYYY')" 
 +" FROM(SELECT created_by,REG_TXN_ID,PARTY_FIRST_NAME,PARTY_MIDDLE_NAME,PARTY_LAST_NAME,ORGANIZATION_NAME,CREATED_DATE" 
 +" FROM IGRS_REG_TXN_PARTY_DETLS T WHERE REG_TXN_ID=? AND (IS_APPLICANT='Y' OR IS_APPLICANT='N' OR IS_APPLICANT='C') and party_type_id in" +
 		"('50001','50004','50005','50009','50011','50014','50015')ORDER BY CREATED_DATE ASC) where rownum<=1";

public static final String GETSELLERTXNPARTY="SELECT created_by,REG_TXN_ID,PARTY_FIRST_NAME,PARTY_MIDDLE_NAME,PARTY_LAST_NAME,ORGANIZATION_NAME,TO_CHAR(CREATED_DATE,'DD/MM/YYYY')" 
 +" FROM(SELECT created_by,REG_TXN_ID,PARTY_FIRST_NAME,PARTY_MIDDLE_NAME,PARTY_LAST_NAME,ORGANIZATION_NAME,CREATED_DATE" 
 +" FROM IGRS_REG_TXN_PARTY_DETLS T"
 +" WHERE REG_TXN_ID=? AND (IS_APPLICANT='Y' OR IS_APPLICANT='N' OR IS_APPLICANT='C') and party_type_id in('50002','50003','50006','50008','50010','50012')"
 +" ORDER BY CREATED_DATE ASC) where rownum<=1";

public static final String GETCOUNTBUYERPARTY="select count(*) from(SELECT created_by,REG_TXN_ID,PARTY_FIRST_NAME,PARTY_MIDDLE_NAME,PARTY_LAST_NAME,ORGANIZATION_NAME,CREATED_DATE" 
 +" FROM IGRS_REG_TXN_PARTY_DETLS T WHERE REG_TXN_ID=? and party_type_id in('50001','50004','50005','50009','50011','50014','50015')"
  +" ORDER BY CREATED_DATE ASC)";

public static final String GETCOUNTSELLERPARTY="select count(*) from(SELECT created_by,REG_TXN_ID,PARTY_FIRST_NAME,PARTY_MIDDLE_NAME,PARTY_LAST_NAME,ORGANIZATION_NAME,CREATED_DATE" 
 +" FROM IGRS_REG_TXN_PARTY_DETLS T WHERE REG_TXN_ID=? and party_type_id in('50002','50003','50006','50008','50010','50012') ORDER BY CREATED_DATE ASC)";

public static final String GETTXNPARTYDETAILS="SELECT nvl(PARTY_FIRST_NAME,''),nvl(PARTY_MIDDLE_NAME,''),nvl(PARTY_LAST_NAME,''),(SELECT PARTY_TYPE_NAME FROM" 
						+" IGRS_PARTY_TYPE_MASTER WHERE PARTY_TYPE_STATUS='A' AND  PARTY_TYPE_ID=rtpd.PARTY_TYPE_ID) PARTY_TYPE_NAME," 
						+" ORGANIZATION_NAME,AUTHRZD_PERSN_NAME from IGRS_REG_TXN_PARTY_DETLS rtpd"
						+" where REG_TXN_ID=? order by PARTY_TYPE_ID"; 



public static final String GET_ESTAMP_BASEDPARTYDETAILS="SELECT nvl(PARTY_FIRST_NAME,''),nvl(PARTY_MIDDLE_NAME,''),nvl(PARTY_LAST_NAME,''),ORGANIZATION_NAME,AUTHRZD_PERSN_NAME from IGRS_ESTAMP_TXN_PARTY_DETLS rtpd,IGRS_ESTAMP_DETLS irtd where rtpd.ESTAMP_TXN_ID=irtd.ESTAMP_TXN_ID and irtd.ESTAMP_CODE=?";
public static final String GET_PSTAMP_BASEDPARTYDETAILS="SELECT NVL(PARTY_FIRST_NAME_H,''),  NVL(PARTY_MIDDLE_NAME_H,''),  NVL(PARTY_LAST_NAME_H,'') FROM IGRS_POT_PSTAMP_PARTY_DETAILS WHERE REFERENCE_ID=?";

public static final String GET_PARTY_DETAILS="SELECT case RTPD.PARTY_FIRST_NAME when null then '' else to_char(RTPD.PARTY_FIRST_NAME) end"+
"||' '|| case RTPD.PARTY_MIDDLE_NAME when null then '' else to_char(RTPD.PARTY_MIDDLE_NAME) end"+
"||' '|| case RTPD.PARTY_LAST_NAME when null then '' else to_char(RTPD.PARTY_LAST_NAME) end"+
"|| case RTPD.ORGANIZATION_NAME when null then '' else to_char(RTPD.ORGANIZATION_NAME) end"+
"|| case RTPD.NAME_OF_OFFICIAL when null then '' else to_char(RTPD.NAME_OF_OFFICIAL) end ||' '|| case RTPD.DESG_OF_OFFICIAL when null then '' else to_char(RTPD.DESG_OF_OFFICIAL) end  as partyname ,"+
"(SELECT PARTY_TYPE_NAME FROM "+
"	 IGRS_PARTY_TYPE_MASTER WHERE PARTY_TYPE_STATUS='A' AND  PARTY_TYPE_ID=rtpd.PARTY_TYPE_ID) PARTY_TYPE_NAME "+
"from IGRS_REG_TXN_PARTY_DETLS rtpd,IGRS_REG_TXN_DETLS irtd"+
"	 where rtpd.IS_APPLICANT!='O' AND  rtpd.REG_TXN_ID=irtd.REG_TXN_ID and irtd.REG_TXN_ID=? order by PARTY_TYPE_ID";

public static final String GET_PARTY_DETAILS_HI="SELECT case RTPD.PARTY_FIRST_NAME when null then '' else to_char(RTPD.PARTY_FIRST_NAME) end"+
"||' '|| case RTPD.PARTY_MIDDLE_NAME when null then '' else to_char(RTPD.PARTY_MIDDLE_NAME) end"+
"||' '|| case RTPD.PARTY_LAST_NAME when null then '' else to_char(RTPD.PARTY_LAST_NAME) end"+
"|| case RTPD.ORGANIZATION_NAME when null then '' else to_char(RTPD.ORGANIZATION_NAME) end"+
"|| case RTPD.NAME_OF_OFFICIAL when null then '' else to_char(RTPD.NAME_OF_OFFICIAL) end ||' '|| case RTPD.DESG_OF_OFFICIAL when null then '' else to_char(RTPD.DESG_OF_OFFICIAL) end as partyname ,"+
"(SELECT H_PARTY_TYPE_NAME FROM "+
"	 IGRS_PARTY_TYPE_MASTER WHERE PARTY_TYPE_STATUS='A' AND  PARTY_TYPE_ID=rtpd.PARTY_TYPE_ID) PARTY_TYPE_NAME "+
"from IGRS_REG_TXN_PARTY_DETLS rtpd,IGRS_REG_TXN_DETLS irtd"+
"	 where rtpd.IS_APPLICANT!='O' AND  rtpd.REG_TXN_ID=irtd.REG_TXN_ID and irtd.REG_TXN_ID=? order by PARTY_TYPE_ID";

public static final String GETREGNOBASEDPARTYDETAILS="SELECT nvl(PARTY_FIRST_NAME,''),nvl(PARTY_MIDDLE_NAME,''),nvl(PARTY_LAST_NAME,''),(SELECT PARTY_TYPE_NAME FROM" 
		+" IGRS_PARTY_TYPE_MASTER WHERE PARTY_TYPE_STATUS='A' AND  PARTY_TYPE_ID=rtpd.PARTY_TYPE_ID) PARTY_TYPE_NAME," 
		+" ORGANIZATION_NAME,AUTHRZD_PERSN_NAME from IGRS_REG_TXN_PARTY_DETLS rtpd,IGRS_REG_TXN_DETLS irtd"
		+" where rtpd.IS_APPLICANT NOT IN ('O') AND rtpd.REG_TXN_ID=irtd.REG_TXN_ID and irtd.REGISTRATION_NUMBER=? order by PARTY_TYPE_ID";

public static final String GETREGNOBASEDPARTYDETAILS_H="SELECT nvl(PARTY_FIRST_NAME,''),nvl(PARTY_MIDDLE_NAME,''),nvl(PARTY_LAST_NAME,''),(SELECT H_PARTY_TYPE_NAME FROM" 
	+" IGRS_PARTY_TYPE_MASTER WHERE PARTY_TYPE_STATUS='A' AND  PARTY_TYPE_ID=rtpd.PARTY_TYPE_ID) PARTY_TYPE_NAME," 
	+" ORGANIZATION_NAME,AUTHRZD_PERSN_NAME from IGRS_REG_TXN_PARTY_DETLS rtpd,IGRS_REG_TXN_DETLS irtd"
	+" where rtpd.REG_TXN_ID=irtd.REG_TXN_ID and irtd.REGISTRATION_NUMBER=? order by PARTY_TYPE_ID";
//added by shruti---24 oct 2013
public static final String GETAGMPREPORTIDBASEDDTLS="select a.transaction_id,b.PARA_TXN_ID,c.OBJECTION_TXN_ID,d.DOCUMENT_ID,d.OBJECTION_DETAILS,to_char(a.CREATED_DATE,'dd/mm/yyyy')"
+" from IGRS_RAUDIT_TXN_DETAILS a,IGRS_RAUDIT_PARA_MAPPING b,"
+"IGRS_RAUDIT_PARA_OBJ_MAPPING c,IGRS_RAUDIT_PARA_OBJ_DETAILS d"
 +" where d.document_id is not null and d.objection_status='OPEN' and a.audit_report_status='O' and b.audit_txn_id=a.transaction_id"
  +" and c.para_txn_id=b.para_txn_id and d.objection_txn_id=c.objection_txn_id and upper(a.transaction_id) like UPPER(?) and a.audit_body_type='AGMP' and a.transaction_id like 'AGR%'";

public static final String GETAGMPREPORTDURATIONBASEDDTLS="select a.transaction_id,b.PARA_TXN_ID,c.OBJECTION_TXN_ID,d.DOCUMENT_ID,d.OBJECTION_DETAILS,to_char(a.CREATED_DATE,'dd/mm/yyyy')"
	 +" from IGRS_RAUDIT_TXN_DETAILS a,IGRS_RAUDIT_PARA_MAPPING b,"
		+"IGRS_RAUDIT_PARA_OBJ_MAPPING c,IGRS_RAUDIT_PARA_OBJ_DETAILS d"
		 +" where d.document_id is not null and d.objection_status='OPEN' and a.audit_report_status='O' and b.audit_txn_id=a.transaction_id"
		  +" and c.para_txn_id=b.para_txn_id and d.objection_txn_id=c.objection_txn_id and trunc(a.created_date) between to_char(to_date(?,'dd/mm/yyyy')) and to_char(to_date(?,'dd/mm/yyyy')) and a.audit_body_type='AGMP' and a.transaction_id like 'AGR%'";

public static final String GETINTERNALREPORTIDBASEDDTLS="select a.transaction_id,b.PARA_TXN_ID,c.OBJECTION_TXN_ID,d.DOCUMENT_ID,d.OBJECTION_DETAILS,to_char(a.CREATED_DATE,'dd/mm/yyyy')"
	 +" from IGRS_RAUDIT_TXN_DETAILS a,IGRS_RAUDIT_PARA_MAPPING b,"
		+"IGRS_RAUDIT_PARA_OBJ_MAPPING c,IGRS_RAUDIT_PARA_OBJ_DETAILS d"
		 +" where d.document_id is not null and d.objection_status='OPEN' and a.audit_report_status='O' and b.audit_txn_id=a.transaction_id"
		  +" and c.para_txn_id=b.para_txn_id and d.objection_txn_id=c.objection_txn_id and upper(a.transaction_id) like UPPER(?) and a.audit_body_type='INTERNAL' and a.transaction_id like 'IA%'";

public static final String GETINTERNALREPORTDURATIONBASEDDTLS="select a.transaction_id,b.PARA_TXN_ID,c.OBJECTION_TXN_ID,d.DOCUMENT_ID,d.OBJECTION_DETAILS,to_char(a.CREATED_DATE,'dd/mm/yyyy')"
	 +" from IGRS_RAUDIT_TXN_DETAILS a,IGRS_RAUDIT_PARA_MAPPING b,"
		+"IGRS_RAUDIT_PARA_OBJ_MAPPING c,IGRS_RAUDIT_PARA_OBJ_DETAILS d"
		 +" where d.document_id is not null and d.objection_status='OPEN' and a.audit_report_status='O' and b.audit_txn_id=a.transaction_id and a.audit_body_type='INTERNAL' and a.transaction_id like 'IA%'"
		  +" and c.para_txn_id=b.para_txn_id and d.objection_txn_id=c.objection_txn_id and trunc(a.created_date) between to_char(to_date(?,'dd/mm/yyyy')) and to_char(to_date(?,'dd/mm/yyyy'))";

public static final String GETPOIREPORTIDBASEDDTLS="select a.POI_TXN_ID,b.PARA_TXN_ID,c.OBJ_TXN_ID,d.reg_doc_id,"
+"d.OBJ_DETAILS,to_char(a.CREATED_DATE,'dd/mm/yyyy')"
+" from IGRS_POI_TXN_DTLS a,IGRS_POI_PARA_MAP"
+" b,IGRS_POI_DOC_MAP c,IGRS_POI_PARA_OBJ_DTLS d where d.reg_doc_id"
+" is not null and d.obj_status='OPEN' and a.insp_report_status='O' and b.poi_txn_id=a.poi_txn_id"
+" and c.para_txn_id=b.para_txn_id and d.obj_txn_id=c.obj_txn_id and a.poi_txn_id=?";

public static final String GETPOIREPORTDURATIONBASEDDTLS="select a.POI_TXN_ID,b.PARA_TXN_ID,c.OBJ_TXN_ID,d.reg_doc_id,"
+"d.OBJ_DETAILS,to_char(a.CREATED_DATE,'dd/mm/yyyy')"
+" from IGRS_POI_TXN_DTLS a,IGRS_POI_PARA_MAP"
+" b,IGRS_POI_DOC_MAP c,IGRS_POI_PARA_OBJ_DTLS d where d.reg_doc_id"
+" is not null and d.obj_status='OPEN' and a.insp_report_status='O' and b.poi_txn_id=a.poi_txn_id"
+" and c.para_txn_id=b.para_txn_id and d.obj_txn_id=c.obj_txn_id and trunc(a.created_date) between to_char(to_date(?,'dd/mm/yyyy')) and to_char(to_date(?,'dd/mm/yyyy'))";

/*public static final String GETPOREPORTIDBASEDDTLS="select transaction_id,'-','-',registration_number,po_comments,to_char(created_date,'dd/mm/yyy')"
+" from igrs_public_officer_tool_txn where transaction_id=? and CASE_ELIGIBILITY='YES'";
public static final String GETPOREPORTDURATIONBASEDDTLS="select transaction_id,'-','-',registration_number,po_comments,to_char(created_date,'dd/mm/yyy')"
+" from igrs_public_officer_tool_txn where trunc(created_date) between to_char(to_date(?,'dd/mm/yyyy')) and to_char(to_date(?,'dd/mm/yyyy')) and CASE_ELIGIBILITY='YES'";*/
//below 2 queries modified by roopam on 28Jan2015 for case and pot new integration using ecode
public static final String GETPOREPORTIDBASEDDTLS="select transaction_id,'-','-',registration_number,nvl(po_comments,'-'),to_char(created_date,'dd/mm/yyy'),ESTAMP_CODE"
	+" from igrs_public_officer_tool_txn where transaction_id=? and FLAG='YES' AND CASE_ID IS NULL";
public static final String GETPOREPORTDURATIONBASEDDTLS="select transaction_id,'-','-',registration_number,nvl(po_comments,'-'),to_char(created_date,'dd/mm/yyy'),ESTAMP_CODE"
	+" from igrs_public_officer_tool_txn where trunc(created_date) between to_char(to_date(?,'dd/mm/yyyy')) and to_char(to_date(?,'dd/mm/yyyy')) and FLAG='YES' AND CASE_ID IS NULL";

public static final String GETSRIMPOUNDREPORTIDDTLS="SELECT 'IMPOUNDED DOCUMENT',COMPLAINT_ID,'-',ROW_NUMBER() OVER(ORDER BY d.COMPLAINT_ID) FROM IGRS_CASE_IMPOUND_DOCUMENT d "
	+ "WHERE STATUS='I' and UPPER(d.COMPLAINT_ID) " + "LIKE UPPER(?)";

public static final String GETSRIMPOUNDREPORTDURATIONDTLS="SELECT 'IMPOUNDED DOCUMENT',COMPLAINT_ID,'-',ROW_NUMBER() OVER(ORDER BY d.COMPLAINT_ID) FROM IGRS_CASE_IMPOUND_DOCUMENT d "
	+ "WHERE STATUS='I' AND TRUNC(CREATED_DATE) BETWEEN "
	+ "to_char(to_date(?,'dd/mm/yyyy')) AND to_char(to_date(?,'dd/mm/yyyy'))";

public static final String GETESTAMPREFUNDREPORTIDDTLS="SELECT 'ESTAMP REFUND',d.DEACT_REQUEST_ID,'-',ROW_NUMBER() OVER(ORDER BY d.DEACT_REQUEST_ID) FROM"
	 +" IGRS_ESTAMP_DEACTIVATION_DETLS d,IGRS_ESTAMP_DETLS ied where d.ESTAMP_CODE=ied.ESTAMP_CODE and ied.ESTAMP_CODE like '0102%'  AND d.CASE_ELIGIBILTY='A' and UPPER(d.DEACT_REQUEST_ID) LIKE UPPER(?)";

public static final String GETESTAMPREFUNDREPORTIDDTLS_H="SELECT 'ई स्टाम्प धन वापसी',d.DEACT_REQUEST_ID,'-',ROW_NUMBER() OVER(ORDER BY d.DEACT_REQUEST_ID) FROM"
	 +" IGRS_ESTAMP_DEACTIVATION_DETLS d,IGRS_ESTAMP_DETLS ied where d.ESTAMP_CODE=ied.ESTAMP_CODE and ied.ESTAMP_CODE like '0102%'  AND d.CASE_ELIGIBILTY='A' and UPPER(d.DEACT_REQUEST_ID) LIKE UPPER(?)";

public static final String GETESTAMPREFUNDNONJUDREPORTIDDTLS="SELECT 'ESTAMP REFUND',d.DEACT_REQUEST_ID,'-',ROW_NUMBER() OVER(ORDER BY d.DEACT_REQUEST_ID) FROM"
	 +" IGRS_ESTAMP_DEACTIVATION_DETLS d,IGRS_ESTAMP_DETLS ied where d.ESTAMP_CODE=ied.ESTAMP_CODE and ied.ESTAMP_CODE like '0101%'  AND d.CASE_ELIGIBILTY='A' and UPPER(d.DEACT_REQUEST_ID) LIKE UPPER(?)";


public static final String GETESTAMPREFUNDNONJUDREPORTIDDTLS_H="SELECT 'ई स्टाम्प धन वापसी',d.DEACT_REQUEST_ID,'-',ROW_NUMBER() OVER(ORDER BY d.DEACT_REQUEST_ID) FROM"
	 +" IGRS_ESTAMP_DEACTIVATION_DETLS d,IGRS_ESTAMP_DETLS ied where d.ESTAMP_CODE=ied.ESTAMP_CODE and ied.ESTAMP_CODE like '0101%' AND d.CASE_ELIGIBILTY='A'  and UPPER(d.DEACT_REQUEST_ID) LIKE UPPER(?)";


public static final String GETESTAMPREFUNDREPORTDURATIONDTLS="SELECT 'ESTAMP REFUND',d.DEACT_REQUEST_ID,'-',ROW_NUMBER() OVER(ORDER BY d.DEACT_REQUEST_ID) FROM"
	 +" IGRS_ESTAMP_DEACTIVATION_DETLS d,IGRS_ESTAMP_DETLS ied where d.ESTAMP_CODE=ied.ESTAMP_CODE and ied.ESTAMP_CODE like '0102%'  and TRUNC(d.CREATED_DATE) BETWEEN "
		+ "to_char(to_date(?,'dd/mm/yyyy')) AND to_char(to_date(?,'dd/mm/yyyy'))AND d.CASE_ELIGIBILTY='A'";

public static final String GETESTAMPREFUNDREPORTDURATIONDTLS_H="SELECT 'ई स्टाम्प धन वापसी',d.DEACT_REQUEST_ID,'-',ROW_NUMBER() OVER(ORDER BY d.DEACT_REQUEST_ID) FROM"
	 +" IGRS_ESTAMP_DEACTIVATION_DETLS d,IGRS_ESTAMP_DETLS ied where d.ESTAMP_CODE=ied.ESTAMP_CODE and ied.ESTAMP_CODE like '0102%'  and TRUNC(d.CREATED_DATE) BETWEEN "
		+ "to_char(to_date(?,'dd/mm/yyyy')) AND to_char(to_date(?,'dd/mm/yyyy'))AND d.CASE_ELIGIBILTY='A'";

public static final String GETESTAMPREFUNDNONJUDREPORTDURATIONDTLS="SELECT 'ESTAMP REFUND',d.DEACT_REQUEST_ID,'-',ROW_NUMBER() OVER(ORDER BY d.DEACT_REQUEST_ID) FROM"
	 +" IGRS_ESTAMP_DEACTIVATION_DETLS d,IGRS_ESTAMP_DETLS ied where d.ESTAMP_CODE=ied.ESTAMP_CODE and ied.ESTAMP_CODE like '0101%'  and TRUNC(d.CREATED_DATE) BETWEEN "
		+ "to_char(to_date(?,'dd/mm/yyyy')) AND to_char(to_date(?,'dd/mm/yyyy'))AND d.CASE_ELIGIBILTY='A'";

public static final String GETESTAMPREFUNDNONJUDREPORTDURATIONDTLS_H="SELECT 'ई स्टाम्प धन वापसी',d.DEACT_REQUEST_ID,'-',ROW_NUMBER() OVER(ORDER BY d.DEACT_REQUEST_ID) FROM"
	 +" IGRS_ESTAMP_DEACTIVATION_DETLS d,IGRS_ESTAMP_DETLS ied where d.ESTAMP_CODE=ied.ESTAMP_CODE and ied.ESTAMP_CODE like '0101%'  and TRUNC(d.CREATED_DATE) BETWEEN "
		+ "to_char(to_date(?,'dd/mm/yyyy')) AND to_char(to_date(?,'dd/mm/yyyy')) AND d.CASE_ELIGIBILTY='A'";

public static final String GETTIMEBARREDIDDTLS="SELECT 'TIME BARRED DOCUMENT',d.PENALTY_ID,'-',ROW_NUMBER() OVER(ORDER BY d.PENALTY_ID) FROM"
	 +" IGRS_CASE_TIME_BARRED_APP d where STATUS='I' and UPPER(d.PENALTY_ID) LIKE UPPER(?)";
	

public static final String GETTIMEBARREDDURATIONDTLS="SELECT 'TIME BARRED DOCUMENT',d.PENALTY_ID,'-',ROW_NUMBER() OVER(ORDER BY d.PENALTY_ID) FROM"
	 +" IGRS_CASE_TIME_BARRED_APP d where STATUS='I' and TRUNC(d.CREATED_DATE) BETWEEN "
		+ "to_char(to_date(?,'dd/mm/yyyy')) AND to_char(to_date(?,'dd/mm/yyyy'))";

public static final String GETLICENSECANCELLATIONIDDTLS="select 'LICENSED USERS',LICENSE_NUMBER,to_char(LICENSE_TO_DATE,'dd/mm/yyyy'),ROW_NUMBER() OVER(ORDER BY LICENSE_NUMBER) from"
	+ " IGRS_SP_DETLS where STATUS='A' AND (APPLCTN_STATUS='8' or APPLCTN_STATUS='11') and CASE_ELIGIBILITY IS NULL and UPPER(LICENSE_NUMBER)"
	+ "LIKE UPPER(?)";

public static final String GETLICENSECANCELLATIONIDDTLS_H="select 'लाइसेंस प्राप्त उपयोगकर्ता',LICENSE_NUMBER,to_char(LICENSE_TO_DATE,'dd/mm/yyyy'),ROW_NUMBER() OVER(ORDER BY LICENSE_NUMBER) from"
	+ " IGRS_SP_DETLS where STATUS='A' AND (APPLCTN_STATUS='8' or APPLCTN_STATUS='11') and CASE_ELIGIBILITY IS NULL and UPPER(LICENSE_NUMBER)"
	+ "LIKE UPPER(?)";

public static final String GETLICCANCLDURATIONDTLS="SELECT 'LICENSED_USERS',LICENSE_NUMBER,to_char(LICENSE_TO_DATE,'dd/mm/yyyy'),ROW_NUMBER() OVER(ORDER BY LICENSE_NUMBER) FROM"
+ " IGRS_SP_DETLS where STATUS='A' AND (APPLCTN_STATUS='8' or APPLCTN_STATUS='11') and CASE_ELIGIBILITY IS NULL AND TRUNC(CREATED_DATE) BETWEEN "
+ "to_char(to_date(?,'dd/mm/yyyy')) AND to_char(to_date(?,'dd/mm/yyyy'))";

public static final String GETLICCANCLDURATIONDTLS_H="SELECT 'लाइसेंस प्राप्त उपयोगकर्ता',LICENSE_NUMBER,to_char(LICENSE_TO_DATE,'dd/mm/yyyy'),ROW_NUMBER() OVER(ORDER BY LICENSE_NUMBER) FROM"
	+ " IGRS_SP_DETLS where STATUS='A' (APPLCTN_STATUS='8' or APPLCTN_STATUS='11') and CASE_ELIGIBILITY IS NULL AND TRUNC(CREATED_DATE) BETWEEN "
	+ "to_char(to_date(?,'dd/mm/yyyy')) AND to_char(to_date(?,'dd/mm/yyyy'))";

public static final String GETOTHERSPENALTYIDDTLS="SELECT 'REVISION OF PENALTY UNDER SEC 45',d.CASE_TXN_ID,d.PENALTY_ID,ROW_NUMBER() OVER(ORDER BY d.PENALTY_ID) FROM"
	+ " IGRS_CASE_OTHERS_TXN_DTLS d where CASE_STATUS='CLOSE' AND UPPER(d.PENALTY_ID) LIKE UPPER(?)";

public static final String GETOTHERSCASEIDDTLS="SELECT 'REVISION OF PENALTY UNDER SEC 45',d.CASE_TXN_ID,d.PENALTY_ID,ROW_NUMBER() OVER(ORDER BY d.CASE_TXN_ID) FROM"
+ " IGRS_CASE_OTHERS_TXN_DTLS d where CASE_STATUS='CLOSE' AND UPPER(d.CASE_TXN_ID) LIKE UPPER(?)";

public static final String GETOTHERSPENALTYDURATIONDTLS= "SELECT 'REVISION OF PENALTY UNDER SEC 45',d.CASE_TXN_ID,d.PENALTY_ID,ROW_NUMBER() OVER(ORDER BY d.PENALTY_ID) FROM"
	+ " IGRS_CASE_OTHERS_TXN_DTLS d where CASE_STATUS='CLOSE' AND TRUNC(d.CREATED_DATE) BETWEEN "
	+ "to_char(to_date(?,'dd/mm/yyyy')) AND to_char(to_date(?,'dd/mm/yyyy'))";

public static final String GETOTHERSPENALTY70IDDTLS="SELECT 'REVISION OF PENALTY UNDER SEC 70',d.CASE_TXN_ID,d.PENALTY_ID,ROW_NUMBER() OVER(ORDER BY d.PENALTY_ID) FROM"
	+ " IGRS_CASE_OTHERS_TXN_DTLS d where CASE_STATUS='CLOSE' AND UPPER(d.PENALTY_ID) "
	+ "LIKE UPPER(?)";

public static final String GETOTHERSCASE70IDDTLS="SELECT 'REVISION OF PENALTY UNDER SEC 70',d.CASE_TXN_ID,d.PENALTY_ID,ROW_NUMBER() OVER(ORDER BY d.CASE_TXN_ID) FROM"
	+ " IGRS_CASE_OTHERS_TXN_DTLS d where CASE_STATUS='CLOSE' AND UPPER(d.CASE_TXN_ID) "
	+ "LIKE UPPER(?)";


public static final String GETOTHERSPENALTY70DURATIONDTLS="SELECT 'REVISION OF PENALTY UNDER SEC 70',d.CASE_TXN_ID,d.PENALTY_ID,ROW_NUMBER() OVER(ORDER BY d.PENALTY_ID) FROM"
	+ " IGRS_CASE_OTHERS_TXN_DTLS d where CASE_STATUS='CLOSE' AND TRUNC(d.CREATED_DATE) BETWEEN "
	+ "to_char(to_date(?,'dd/mm/yyyy')) AND to_char(to_date(?,'dd/mm/yyyy'))";

//added by satbir kumar for case views


public static final String GETCASEVIEWDETAILS="SELECT ca.CASE_TXN_ID,ca.CASE_STATUS,rh.REVENUE_HEAD_NAME,sh.SECTION_HEAD_NAME,ca.SPOT_INSP_DETAILS,ca.VALUATION_BY_DR,to_char(ca.NEXT_HEARING_DATE,'dd/mm/yyyy'),ca.PROPOSED_REG_FEE, "
  											  +" ca.PROPOSED_STAMP_DUTY,nvl(ca.CASE_FINAL_COMMENTS,'-'),ca.CASE_HEAD_ID from igrs_case_txn_details ca, "
  											  +" IGRS_CASE_REVENUE_HEAD_MASTER rh,IGRS_CASE_SECTION_HEAD_MASTER sh "
											  +" where ca.REVENUE_HEAD_ID=rh.REVENUE_HEAD_ID and ca.SECTION_HEAD_ID=sh.SECTION_HEAD_ID "
											  +" and CASE_TXN_ID=?";

public static final String GETCASEREFUNDVIEWDETAILS="SELECT ca.CASE_TXN_ID,ca.CASE_STATUS,rh.REVENUE_HEAD_NAME,sh.SECTION_HEAD_NAME,'-',nvl(ca.REFUND_AMOUNT,'-'),nvl(ca.REFUND_BILL_DATE,'-'),nvl(REFUND_BILL_NO,'-'), "
	  +" '0',nvl(ca.CASE_FINAL_COMMENTS,'-'),ca.CASE_HEAD_ID from IGRS_CASE_REFUND_TXN_DTLS ca, "
	  +" IGRS_CASE_REVENUE_HEAD_MASTER rh,IGRS_CASE_SECTION_HEAD_MASTER sh "
	  +" where ca.REVENUE_HEAD_ID=rh.REVENUE_HEAD_ID and ca.SECTION_HEAD_ID=sh.SECTION_HEAD_ID "
	  +" and CASE_TXN_ID=?";

public static final String GETCASEPENALTYVIEWDETAILS="SELECT ca.CASE_TXN_ID,ca.CASE_STATUS,rh.REVENUE_HEAD_NAME,sh.SECTION_HEAD_NAME,'-','0','-','0', "
	  +" '0',nvl(ca.CASE_FINAL_COMMENTS,'-'),ca.CASE_HEAD_ID from IGRS_CASE_OTHERS_TXN_DTLS ca, "
	  +" IGRS_CASE_REVENUE_HEAD_MASTER rh,IGRS_CASE_SECTION_HEAD_MASTER sh "
	  +" where ca.REVENUE_HEAD_ID=rh.REVENUE_HEAD_ID and ca.SECTION_HEAD_ID=sh.SECTION_HEAD_ID "
	  +" and CASE_TXN_ID=?";

public static final String GETCASEPENALTY45VIEWDETAILS="SELECT ca.CASE_TXN_ID,ca.CASE_STATUS,rh.REVENUE_HEAD_NAME,sh.SECTION_HEAD_NAME,'-','0','-','0', "
	  +" '0',nvl(ca.CASE_FINAL_COMMENTS,'-'),ca.CASE_HEAD_ID from IGRS_CASE_REV_PNLTY_TXN_DTLS ca, "
	  +" IGRS_CASE_REVENUE_HEAD_MASTER rh,IGRS_CASE_SECTION_HEAD_MASTER sh "
	  +" where ca.REVENUE_HEAD_ID=rh.REVENUE_HEAD_ID and ca.SECTION_HEAD_ID=sh.SECTION_HEAD_ID "
	  +" and CASE_TXN_ID=?";

public static final String GETCASEPENALTY70VIEWDETAILS="SELECT ca.CASE_TXN_ID,ca.CASE_STATUS,rh.REVENUE_HEAD_NAME,sh.SECTION_HEAD_NAME,'-','0','-','0', "
	  +" '0',nvl(ca.CASE_FINAL_COMMENTS,'-'),ca.CASE_HEAD_ID from IGRS_CASE_PNLTY70_TXN_DTLS ca, "
	  +" IGRS_CASE_REVENUE_HEAD_MASTER rh,IGRS_CASE_SECTION_HEAD_MASTER sh "
	  +" where ca.REVENUE_HEAD_ID=rh.REVENUE_HEAD_ID and ca.SECTION_HEAD_ID=sh.SECTION_HEAD_ID "
	  +" and CASE_TXN_ID=?";

public static final String GETCASEVIEWOTHERDETAILS="SELECT b.CASE_ACTION_NAME,nvl(a.CASE_ACTION_REMARKS,'-'),to_char(a.CREATED_DATE,'dd/mm/yyyy'),a.PARTY_RESPONSE_FLAG,nvl(a.PARTY_PAY_DEC_FLAG,'-'),nvl(c.DOC_FILE_LOC,'-') "
												   +" from IGRS_CASE_ACTION_MAP a,IGRS_CASE_ACTION_MASTER b,igrs_case_txn_doc_details c "
												   +" where a.CASE_ACTION_ID=b.CASE_ACTION_ID and a.CASE_ACTION_TXN_ID=c.CASE_ACTION_TXN_ID(+) and a.CASE_TXN_ID=? and a.CREATED_DATE<sysdate ";

// end of addition

//---added by satbir kumar

public static final String IGRS_UPDATE_ELIGIBLITY_STATUS="UPDATE IGRS_ESTAMP_DEACTIVATION_DETLS SET CASE_ELIGIBILTY='D' WHERE DEACT_REQUEST_ID=?";

public static final String ESTAMP_RR_DEACTIVATE="SELECT 'ESTAMP REFUND',d.DEACT_REQUEST_ID,'-',ROW_NUMBER() OVER(ORDER BY d.DEACT_REQUEST_ID) FROM"
	 +" IGRS_ESTAMP_DEACTIVATION_DETLS d,IGRS_ESTAMP_DETLS ied where d.ESTAMP_CODE=ied.ESTAMP_CODE and ied.ESTAMP_CODE like '0101%'  AND d.CASE_ELIGIBILTY='A' and UPPER(d.DEACT_REQUEST_ID) LIKE UPPER(?)";

public static final String ESTAMP_RR_DEACTIVATE_H="SELECT 'ई स्टाम्प धन वापसी',d.DEACT_REQUEST_ID,'-',ROW_NUMBER() OVER(ORDER BY d.DEACT_REQUEST_ID) FROM"
	 +" IGRS_ESTAMP_DEACTIVATION_DETLS d,IGRS_ESTAMP_DETLS ied where d.ESTAMP_CODE=ied.ESTAMP_CODE and ied.ESTAMP_CODE like '0101%' AND d.CASE_ELIGIBILTY='A'  and UPPER(d.DEACT_REQUEST_ID) LIKE UPPER(?)";

public static final String ESTAMP_RR_DEACTIVATE_DURATIONDTLS="SELECT 'ESTAMP REFUND',d.DEACT_REQUEST_ID,'-',ROW_NUMBER() OVER(ORDER BY d.DEACT_REQUEST_ID) FROM"
	 +" IGRS_ESTAMP_DEACTIVATION_DETLS d,IGRS_ESTAMP_DETLS ied where d.ESTAMP_CODE=ied.ESTAMP_CODE and ied.ESTAMP_CODE like '0101%'  and TRUNC(d.CREATED_DATE) BETWEEN "
		+ "to_char(to_date(?,'dd/mm/yyyy')) AND to_char(to_date(?,'dd/mm/yyyy'))AND d.CASE_ELIGIBILTY='A'";

public static final String ESTAMP_RR_DEACTIVATE_DURATIONDTLS_H="SELECT 'ई स्टाम्प धन वापसी',d.DEACT_REQUEST_ID,'-',ROW_NUMBER() OVER(ORDER BY d.DEACT_REQUEST_ID) FROM"
	 +" IGRS_ESTAMP_DEACTIVATION_DETLS d,IGRS_ESTAMP_DETLS ied where d.ESTAMP_CODE=ied.ESTAMP_CODE and ied.ESTAMP_CODE like '0101%'  and TRUNC(d.CREATED_DATE) BETWEEN "
		+ "to_char(to_date(?,'dd/mm/yyyy')) AND to_char(to_date(?,'dd/mm/yyyy')) AND d.CASE_ELIGIBILTY='A'";

//----end of addition

}

