package com.wipro.igrs.deedparammapping.sql;

public class DeedParamSQL {

	public static final String SELECT_ALL_DEED_TYPE_MASTER =
    	"SELECT DEED_TYPE_ID, DEED_TYPE_NAME " +
    	"FROM IGRS_DEED_TYPE_MASTER ";
	
	public static final String SELECT_ALL_DEED_PARAM_MASTER =
    	"SELECT PARAM_ID, PARAM_NAME " +
    	"FROM IGRS_DEED_PARAM_MASTER ";
	
	public static final String SELECT_ALL_DEED_INSTRUMENT =
    	"SELECT INSTRUMENT_ID, INSTRUMENT_NAME " +
    	"FROM IGRS_DEED_INSTRUMENT_MASTER ";
	
	public static final String SELECT_ALL_DEED_EXEMPTION =
    	"SELECT EXEMPTION_ID, EXEMPTION_NAME " +
    	"FROM IGRS_DEED_EXEMPTION_MASTER ";
	
	public static final String SELECT_DEED_INSTRUMENT_BY_DEED_TYPR_ID =
    	"SELECT INSTRUMENT_ID, INSTRUMENT_NAME " +
    	"FROM IGRS_DEED_INSTRUMENT_MASTER";//  WHERE DEED_TYPE_ID=? ";
	
	public static final String SELECT_DEED_EXEMPTION_BY_DEED_TYPR_ID =
    	"SELECT EXEMPTION_ID, EXEMPTION_NAME " +
    	"FROM IGRS_DEED_EXEMPTION_MASTER";//WHERE DEED_TYPE_ID=? ";
	
	public static final String SELECT_DEED_EXEMPTION_BY_INSTRUMENT_ID =
    	"SELECT EXEMPTION_ID, EXEMPTION_NAME " +
    	"FROM IGRS_DEED_EXEMPTION_MASTER WHERE INSTRUMENT_ID=? ";
	
	public static final String SELECT_DEED_PARAM_MAPPING = 
		"SELECT m.DEED_TYPE_ID, m.INSTRUMENT_ID, m.EXEMPTION_ID, m.STATUS_FLAG, m.CREATED_BY, m.CREATED_DATE, m.UPDATE_BY, m.UPDATE_DATE, m.IGRS_DEED_PARAM_MAPPING_ID, t.DEED_TYPE_NAME, i.INSTRUMENT_NAME, e.EXEMPTION_NAME, p.PARAM_ID, p.PARAM_NAME " +
		"FROM IGRS_DEED_PARAM_MAPPING m, IGRS_DEED_TYPE_MASTER t, IGRS_DEED_INSTRUMENT_MASTER i, IGRS_DEED_EXEMPTION_MASTER e, IGRS_DEED_PARAM_MASTER p " +
		"WHERE m.DEED_TYPE_ID = t.DEED_TYPE_ID AND m.INSTRUMENT_ID = i.INSTRUMENT_ID AND m.EXEMPTION_ID = e.EXEMPTION_ID AND m.STATUS_FLAG = 'A' AND p.PARAM_ID = m.PARAM_ID " +
		"ORDER BY m.IGRS_DEED_PARAM_MAPPING_ID";
	
	

	public static final String SELECT_DEED_PARAM_MAPPING_BY_ID = 
		"SELECT m.DEED_TYPE_ID, m.INSTRUMENT_ID, m.EXEMPTION_ID, m.STATUS_FLAG, m.CREATED_BY, m.CREATED_DATE, m.UPDATE_BY, m.UPDATE_DATE, t.DEED_TYPE_NAME, i.INSTRUMENT_NAME, e.EXEMPTION_NAME, p.PARAM_ID, p.PARAM_NAME " +
		"FROM IGRS_DEED_PARAM_MAPPING m, IGRS_DEED_TYPE_MASTER t, IGRS_DEED_INSTRUMENT_MASTER i, IGRS_DEED_EXEMPTION_MASTER e, IGRS_DEED_PARAM_MASTER p  " +
		"WHERE m.DEED_TYPE_ID = t.DEED_TYPE_ID AND m.INSTRUMENT_ID = i.INSTRUMENT_ID AND m.EXEMPTION_ID = e.EXEMPTION_ID AND m.IGRS_DEED_PARAM_MAPPING_ID = ? AND m.STATUS_FLAG = 'A'  AND p.PARAM_ID = m.PARAM_ID";
	
	
	public static final String SELECT_DEED_PARAM_MAPPING_BY_COMPOSITE_KEY = 
		"SELECT * " +
		"FROM IGRS_DEED_PARAM_MAPPING  " +
		"WHERE DEED_TYPE_ID = ? AND INSTRUMENT_ID = ? AND EXEMPTION_ID = ? AND PARAM_ID = ? ";
	
	
	public static final String INSERT_DEED_PARAM_MAPPING = 
        "INSERT INTO IGRS_DEED_PARAM_MAPPING (DEED_TYPE_ID, INSTRUMENT_ID, EXEMPTION_ID, PARAM_ID, STATUS_FLAG, IGRS_DEED_PARAM_MAPPING_ID ) " + 
        "VALUES(?, ?, ?, ?, ?, IGRS_DEED_PARAM_MAPPING_SEQ.NEXTVAL||'DPMAP')";
	
	public static final String UPDATE_DEED_PARAM_MAPPING = 
        "UPDATE IGRS_DEED_PARAM_MAPPING SET DEED_TYPE_ID = ?, INSTRUMENT_ID = ?, EXEMPTION_ID = ?, PARAM_ID = ?, STATUS_FLAG = ? " + 
        "WHERE IGRS_DEED_PARAM_MAPPING_ID = ?";
	
	public static final String DELETE_DEED_PARAM_MAPPING = 
        "UPDATE IGRS_DEED_PARAM_MAPPING SET STATUS_FLAG = ? " + 
        "WHERE IGRS_DEED_PARAM_MAPPING_ID = ?";
	
}
