package com.wipro.igrs.pot.sql;

public class CommonSQL
{
	
	//public static final String SELECT_DISTRICTS = "select * from igrs_district_master where upper(DISTRICT_STATUS)='A' and  STATE_ID='1'";
	public static final String SELECT_DISTRICTS = "select DISTRICT_ID,DISTRICT_NAME from igrs_district_master where upper(DISTRICT_STATUS)='A' and STATE_ID=1";
	public static final String SELECT_DISTRICTS_hi= "select DISTRICT_ID,H_DISTRICT_NAME from igrs_district_master where upper(DISTRICT_STATUS)='A' and STATE_ID=1";
	public static final String SELECT_DISTRICTS_name= "SELECT po.DISTRICT_ID,dm.DISTRICT_NAME FROM IGRS_PUBLIC_OFFICER_TOOL_TXN po,IGRS_DISTRICT_MASTER dm WHERE po.DISTRICT_ID  =dm.DISTRICT_ID AND REGISTRATION_NUMBER=? ";

	public static final String SELECT_PO_NAME="select FIRST_NAME,MIDDLE_NAME,LAST_NAME,DISTRICT_ID FROM IGRS_USER_REG_DETAILS WHERE USER_ID=?";
	public static final String INSERT_POT_CREATE = "INSERT INTO IGRS_PUBLIC_OFFICER_TOOL_TXN(FIRST_NAME,MIDDLE_NAME,LAST_NAME,DISTRICT_ID,TRANSACTION_ID,OLD_NEW,REGISTRATION_NUMBER,ESTAMP_CODE,STAMP_FEE_IN_DOC,STAMP_FEE_REQUIRED,DOC_IMPOUNDED,PO_COMMENTS,STATUS_FLAG,DATE_OF_OBJECTION,CREATED_DATE)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,'A',?,SYSDATE)";

	public static final String INSERT_POT_CREATE_OLD = "INSERT INTO IGRS_POT_OLD_STAMP_MAPPING(STAMP_NUMBER,STAMP_FEE,PO_TXN_ID)VALUES(?,?,?)";
	public static final String INSERT_POT_OLD = "INSERT INTO IGRS_PUBLIC_OFFICER_TOOL_TXN(FIRST_NAME,MIDDLE_NAME,LAST_NAME,DISTRICT_ID,TRANSACTION_ID,OLD_NEW,STAMP_FEE_IN_DOC,STAMP_FEE_REQUIRED,OLD_REG_VOLUME_NO,OLD_REG_BOOK_NO,OLD_REG_NO,DOC_IMPOUNDED,PO_COMMENTS,STATUS_FLAG,DATE_OF_OBJECTION,OLD_REG_DATE)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,'A',?,?)";
//modified
	// START | POT Tool Changes | santosh
	public static final String SELECT_POT_LIST_hi = "select po.transaction_id,po.old_new,po.first_name,po.LAST_NAME,TO_CHAR(to_DATE(trunc(po.DATE_OF_OBJECTION),'DD-MM-RRRR'),'DD-MM-RRRR'),dm.H_DISTRICT_NAME from IGRS_PUBLIC_OFFICER_TOOL_TXN po,IGRS_DISTRICT_MASTER dm where po.DISTRICT_ID=dm.DISTRICT_ID and po.transaction_id=?";
	//public static final String SELECT_POT_LIST = "select transaction_id,old_new,first_name,LAST_NAME,TO_CHAR(to_DATE(trunc(DATE_OF_OBJECTION),'DD-MM-RRRR'),'DD-MM-RRRR'),dm.DISTRICT_NAME from IGRS_PUBLIC_OFFICER_TOOL_TXN po,IGRS_DISTRICT_MASTER dm where po.DISTRICT_ID=dm.DISTRICT_NAME and transaction_id=?";
	//public static final String SELECT_POT_LIST_hi = "select transaction_id,old_new,first_name,LAST_NAME,TO_CHAR(to_DATE(trunc(DATE_OF_OBJECTION),'DD-MM-RRRR'),'DD-MM-RRRR'),dm.H_DISTRICT_NAME from IGRS_PUBLIC_OFFICER_TOOL_TXN po,IGRS_DISTRICT_MASTER dm where po.DISTRICT_ID=dm.DISTRICT_NAME and transaction_id=?";

	public static final String SELECT_POT_LIST = "select po.transaction_id,po.old_new,po.first_name,po.LAST_NAME,TO_CHAR(to_DATE(trunc(po.DATE_OF_OBJECTION),'DD-MM-RRRR'),'DD-MM-RRRR'),dm.DISTRICT_NAME from IGRS_PUBLIC_OFFICER_TOOL_TXN po,IGRS_DISTRICT_MASTER dm where po.DISTRICT_ID=dm.DISTRICT_ID and po.transaction_id=?";
	//public static final String SELECT_POTLIST_BET_DATES = "select transaction_id,old_new,first_name,TO_CHAR(to_DATE(trunc(DATE_OF_OBJECTION),'DD-MM-RRRR'),'DD-MM-RRRR'),DISTRICT_NAME from igrs_public_officer_tool_txn po,IGRS_DISTRICT_MASTER dm where po.DISTRICT_ID=dm.DISTRICT_ID and DATE_OF_OBJECTION between to_date('"+data.getDurationFrom()+"','DD-MM-RRRR') and to_date('"+data.getDurationTo()+"','DD-MM-RRRR')";
//	public static final String SELECT_POTDETAILS = "select FIRST_NAME,MIDDLE_NAME,LAST_NAME,DISTRICT_NAME,to_char(to_date(DATE_OF_OBJECTION,'DD-MM-RRRR'),'DD-MM-RRRR'),TRANSACTION_ID,OLD_NEW,REGISTRATION_NUMBER,OLD_REG_VOLUME_NO,OLD_REG_BOOK_NO,OLD_REG_NO,ESTAMP_CODE,STAMP_FEE_IN_DOC,STAMP_FEE_REQUIRED,DOC_IMPOUNDED,PO_COMMENTS,CASE_ELIGIBILITY,DR_COMMENTS from igrs_public_officer_tool_txn po,IGRS_DISTRICT_MASTER dm where po.DISTRICT_ID=dm.DISTRICT_ID and TRANSACTION_ID='"+potId+"'";
	
	public static final String SELECT_POT_LIST_hi_U = "select po.transaction_id,po.old_new,po.first_name,po.LAST_NAME,TO_CHAR(to_DATE(trunc(po.DATE_OF_OBJECTION),'DD-MM-RRRR'),'DD-MM-RRRR'),dm.H_DISTRICT_NAME from IGRS_PUBLIC_OFFICER_TOOL_TXN po,IGRS_DISTRICT_MASTER dm where po.DISTRICT_ID=dm.DISTRICT_ID and po.transaction_id=? and po.DISTRICT_ID=?";
	//public static final String SELECT_POT_LIST = "select transaction_id,old_new,first_name,LAST_NAME,TO_CHAR(to_DATE(trunc(DATE_OF_OBJECTION),'DD-MM-RRRR'),'DD-MM-RRRR'),dm.DISTRICT_NAME from IGRS_PUBLIC_OFFICER_TOOL_TXN po,IGRS_DISTRICT_MASTER dm where po.DISTRICT_ID=dm.DISTRICT_NAME and transaction_id=?";
	//public static final String SELECT_POT_LIST_hi = "select transaction_id,old_new,first_name,LAST_NAME,TO_CHAR(to_DATE(trunc(DATE_OF_OBJECTION),'DD-MM-RRRR'),'DD-MM-RRRR'),dm.H_DISTRICT_NAME from IGRS_PUBLIC_OFFICER_TOOL_TXN po,IGRS_DISTRICT_MASTER dm where po.DISTRICT_ID=dm.DISTRICT_NAME and transaction_id=?";

	public static final String SELECT_POT_LIST_U = "select po.transaction_id,po.old_new,po.first_name,po.LAST_NAME,TO_CHAR(to_DATE(trunc(po.DATE_OF_OBJECTION),'DD-MM-RRRR'),'DD-MM-RRRR'),dm.DISTRICT_NAME from IGRS_PUBLIC_OFFICER_TOOL_TXN po,IGRS_DISTRICT_MASTER dm where po.DISTRICT_ID=dm.DISTRICT_ID and po.transaction_id=?  and po.DISTRICT_ID=?";
	// END | POT Tool Changes | santosh
	//public static final String SELECT_POTLIST_BET_DATES = "select transaction_id,old_new,first_name,TO_CHAR(to_DATE(trunc(DATE_OF_OBJECTION),'DD-MM-RRRR'),'DD-MM-RRRR'),DISTRICT_NAME from igrs_public_officer_tool_txn po,IGRS_DISTRICT_MASTER dm where po.DISTRICT_ID=dm.DISTRICT_ID and DATE_OF_OBJECTION between to_date('"+data.getDurationFrom()+"','DD-MM-RRRR') and to_date('"+data.getDurationTo()+"','DD-MM-RRRR')";
//	public static final String SELECT_POTDETAILS = "select FIRST_NAME,MIDDLE_NAME,LAST_NAME,DISTRICT_NAME,to_char(to_date(DATE_OF_OBJECTION,'DD-MM-RRRR'),'DD-MM-RRRR'),TRANSACTION_ID,OLD_NEW,REGISTRATION_NUMBER,OLD_REG_VOLUME_NO,OLD_REG_BOOK_NO,OLD_REG_NO,ESTAMP_CODE,STAMP_FEE_IN_DOC,STAMP_FEE_REQUIRED,DOC_IMPOUNDED,PO_COMMENTS,CASE_ELIGIBILITY,DR_COMMENTS from igrs_public_officer_tool_txn po,IGRS_DISTRICT_MASTER dm where po.DISTRICT_ID=dm.DISTRICT_ID and TRANSACTION_ID='"+potId+"'";
	
	//public static final String GET_POT_REGID="SELECT DISTINCT REGC.REGISTRATION_NUMBER, REGI.PARTY_FIRST_NAME,REGI.PARTY_MIDDLE_NAME,REGI.PARTY_LAST_NAME,ESP.ESTAMP_CODE,REGC.REG_TXN_ID,REGI.ORGANIZATION_NAME,REGI.AUTHRZD_PERSN_NAME FROM IGRS_REG_TXN_PARTY_DETLS REGI,IGRS_ESTAMP_DETLS ESP,IGRS_REG_TXN_DETLS REGC WHERE REGC.reg_txn_id = ESP.REG_INIT_ID AND REGC.reg_txn_id =REGI.reg_txn_id AND REGC.REGISTRATION_NUMBER=?";
	
	//public static final String GET_POT_DASHBOARD="SELECT DISTINCT REGC.REGISTRATION_NUMBER,REGI.REPORT_ID,REGI.CASE_TXN_ID,REGI.CASE_STATUS,REGC.REG_TXN_ID FROM IGRS_CASE_TXN_DETAILS REGI,IGRS_REG_TXN_DETLS REGC WHERE  REGC.reg_txn_id  =REGI.REGISTRATION_ID AND REGC.REGISTRATION_NUMBER=?";
	public static final String GET_POT_DASHBOARD="SELECT DISTINCT REGC.REGISTRATION_NUMBER,REGI.REPORT_ID,REGI.CASE_TXN_ID,REGI.CASE_STATUS,REGC.REG_TXN_ID FROM IGRS_CASE_TXN_DETAILS REGI,IGRS_REG_TXN_DETLS REGC WHERE  REGC.reg_txn_id  =REGI.REGISTRATION_ID AND REGC.REGISTRATION_NUMBER=?";
	public static final String GET_POT_REGID="SELECT DISTINCT REGC.REGISTRATION_NUMBER,"+
  "REGI.PARTY_FIRST_NAME, "+
  "REGI.PARTY_MIDDLE_NAME,"+
 " REGI.PARTY_LAST_NAME,"+
 " REG.CASE_TXN_ID,"+
 " REG.CASE_STATUS,"+
 " ESP.ESTAMP_CODE,"+
 " esp.estamp_amount"+
"  FROM IGRS_REG_TXN_PARTY_DETLS REGI,"+
 " IGRS_CASE_TXN_DETAILS REG,"+
 " IGRS_ESTAMP_DETLS ESP,"+
 " IGRS_REG_TXN_DETLS REGC"+
" WHERE REGC.reg_txn_id       = ESP.REG_INIT_ID"+
" AND REGC.reg_txn_id         =REGI.reg_txn_id"+
" AND REGC.REGISTRATION_NUMBER=REG.REGISTRATION_ID"+
" AND REGC.REGISTRATION_NUMBER=?";
		
	
	public static final String GET_POT_REG_ID = "SELECT DISTINCT REGC.REGISTRATION_NUMBER,"+
 " REGI.PARTY_FIRST_NAME,"+
 " REGI.PARTY_MIDDLE_NAME,"+
 " REGI.PARTY_LAST_NAME,"+
"  ESP.ESTAMP_CODE,"+
  " ESP.ESTAMP_AMOUNT"+
" FROM IGRS_REG_TXN_PARTY_DETLS REGI,"+
 " IGRS_ESTAMP_DETLS ESP,"+
 " IGRS_REG_TXN_DETLS REGC"+
" WHERE REGC.reg_txn_id       = ESP.REG_INIT_ID"+
" AND REGC.reg_txn_id         =REGI.reg_txn_id"+
" AND REGC.REGISTRATION_NUMBER=?";
	
	
}
