/**
 * CommonSQL.java
 */


package com.wipro.igrs.sp.sql;

public final class CommonSQL {
	public static final String SELECTSPUSERS = "select USER_ID from IGRS_USERS_LIST where USER_TYPE_ID='X'";

	public static final String SELECTSPUSERINFO = "SELECT iurd.ADDRESS,iurd.POSTAL_CODE,iurd.DISTRICT_ID,(SELECT idm.DISTRICT_NAME FROM IGRS_USER_REG_DETAILS iurd,IGRS_DISTRICT_MASTER idm WHERE idm.DISTRICT_ID=iurd.DISTRICT_ID AND iurd.USER_ID=?) FROM IGRS_USER_REG_DETAILS iurd,IGRS_DISTRICT_MASTER idm WHERE idm.DISTRICT_ID=iurd.DISTRICT_ID AND iurd.USER_ID=? AND USER_STATUS='A'";

	public static final String SELECTDROOFFICECODE = "select iotm.OFFICE_TYPE_ID from IGRS_OFFICE_MASTER iom,IGRS_OFFICE_TYPE_MASTER iotm where iom.DISTRICT_ID=? AND  iotm.OFFICE_TYPE_NAME = 'DRO' AND iom.OFFICE_TYPE_ID=iotm.OFFICE_TYPE_ID";

	public static final String INSERTSPLICENCEDETAILS = "insert into IGRS_SP_USER_LICENSE_DETAILS(LICENSE_TXN_ID,LICENSE_NO,SP_USER_ID,VALID_FROM,DISTRICT_ID,TEHSIL_ID,SP_OFFICE_ADDR,PINCODE,DR_COMMENTS,VALID_TO,LICENSE_STATUS,CREATED_BY,CREATED_DATE,UPDATE_BY,UPDATE_DATE)"
		+ "values(?,?,?,?,?,?,?,?,?,?,'A',?,sysdate,?,sysdate)";

	public static final String SELECT_LICENSE_TXN_ID_SEQ = "SELECT IGRS_SP_LICENSE_TXN_ID_SEQ.NEXTVAL FROM DUAL";
	
	public static final String SELECTSPBANKINFO = "select BANK_ADDRESS,BANK_PHONE_NUMBER from IGRS_BANK_MASTER where BANK_ID=? AND STATUS='A'";

	public static final String INSERTSPBANKLICENCEDETAILS = "insert into IGRS_SP_BANK_LICENSE_DETAILS(LICENSE_TXN_ID,LICENSE_NO,SP_BANK_USER_ID,VALID_FROM,DR_COMMENTS,VALID_TO,LICENSE_STATUS,CREATED_BY,CREATED_DATE,UPDATE_BY,UPDATE_DATE,BANK_ID,DISTRICT_ID)"
		+ "values(?,?,?,?,?,?,'A',?,sysdate,?,sysdate,?,?)";
	
	public static final String SELECT_LICENSE_ID_SEQ = "SELECT IGRS_SP_LICENCE_SEQ.NEXTVAL FROM DUAL";
	
	public static final String SELECT_LICENSE_ID_SEQ_1 = "SELECT IGRS_SP_LICENCE_SEQ_1.NEXTVAL FROM DUAL";

	/**
	 * Service Provider Account Management
	 */
	public static final String SELECTSPUSERTYPE = "select USER_TYPE_ID from IGRS_USERS_LIST where USER_ID=? ";

	
	public static final String SELECTSERVICEPROVIDERACCOUNTINFO = "select isuld.LICENSE_TXN_ID,isuld.LICENSE_NO,isuld.SP_OFFICE_ADDR,(select first_name||' '||middle_name||' '||last_name from IGRS_USER_REG_DETAILS where USER_ID=?),isuabd.SP_ACCT_BALANCE"
		+ " from IGRS_SP_USER_ACCT_BAL_DETAILS isuabd,IGRS_SP_USER_LICENSE_DETAILS isuld "
		+ "WHERE isuabd.SP_LICENCE_TXN_ID=isuld.LICENSE_TXN_ID AND isuabd.SP_LICENCE_NO=isuld.LICENSE_NO AND SP_USER_ID=?";

	public static final String SELECTSERVICEPROVIDERBANKACCOUNTINFO = "select isuld.LICENSE_TXN_ID,isuld.LICENSE_NO,isuld.SP_OFFICE_ADDR,(select first_name||' '||middle_name||' '||last_name from IGRS_USER_REG_DETAILS where USER_ID=?),isuabd.SP_ACCT_BALANCE"
		+ " from IGRS_SP_USER_ACCT_BAL_DETAILS isuabd,IGRS_SP_USER_LICENSE_DETAILS isuld "
		+ "WHERE isuabd.SP_LICENCE_TXN_ID=isuld.LICENSE_TXN_ID AND isuabd.SP_LICENCE_NO=isuld.LICENSE_NO AND SP_USER_ID=?";

	public static final String SELECTSERVICEPROVIDERACCOUNTSTMT = "select iptd.PAYMENT_DATE,ispmd.TRANSACTION_ID,iptm.PAYMENT_TYPE_NAME,iptd.PAYMENT_AMOUNT"
		+ " from IGRS_SP_PAYMENT_MODE_DETAILS ispmd,IGRS_PAYMENT_TXN_DETAILS iptd,IGRS_PAYMENT_TYPE_MASTER iptm"
		+ " where iptm.PAYMENT_TYPE_ID=iptd.PAYMENT_TYPE_ID"
		+ " AND iptm.PAYMENT_TYPE_ID=ispmd.PAYMENT_TYPE_ID"
		+ " AND ispmd.TRANSACTION_ID=ispmd.TRANSACTION_ID"
		+ " AND SP_USER_ID=? " + "AND iptd.PAYMENT_DATE BETWEEN ? AND ?";

	//added by shruti
	public static final String SELECTSERVICEPROVIDERACCOUNTSTMTNEW="select icltl.TRANSACTION_DATE," 
			+" icltl.TRANSACTION_ID,iptm.PAYMENT_TYPE_NAME,icltl.TRANSACTION_AMOUNT"
	 +" from IGRS_CREDIT_LIMIT_TXN_LOG icltl,IGRS_PAYMENT_TXN_DETAILS iptd,IGRS_PAYMENT_TYPE_MASTER iptm"
     +" where iptm.PAYMENT_TYPE_ID=iptd.PAYMENT_TYPE_ID"
	  +" and icltl.TRANSACTION_ID=iptd.TRANSACTION_ID"
	  +" and icltl.LICENSE_NO=? AND iptd.PAYMENT_DATE BETWEEN ? AND ?";
	
	public static final String SELECTSERVICEPROVIDERACCOUNTSTMTNEW1="select icltl.TRANSACTION_DATE,"
			+" icltl.TRANSACTION_ID,iptm.PAYMENT_TYPE_NAME,icltl.TRANSACTION_AMOUNT"
	  +" from IGRS_CREDIT_LIMIT_TXN_LOG icltl,IGRS_PAYMENT_TYPE_MASTER iptm"
    +" where iptm.PAYMENT_TYPE_ID=icltl.TRANSACTION_MODE"
	 +" and icltl.LICENSE_NO=? AND icltl.TRANSACTION_DATE BETWEEN ? AND ?";
	
	public static final String SELECTSERVICEPROVIDERACCOUNTSTMTNEW2="select TO_CHAR(TRANSACTION_DATE,'DD/MM/YYYY hh:mi:ss AM'),"
	+" PAYMENT_TXN_ID,iptm.PAYMENT_TYPE_NAME,CREDIT_OR_DEBIT ,ROUND(PAID_AMOUNT,2),"
	+" FUNCTION_NAME,round(ACCOUNT_BAL,2),nvl(round(SP_COMM,2),0) from IGRS_CREDIT_LIMIT_TXN_LOG icltl,"
	+" IGRS_FUNCTION_MASTER ifm,IGRS_PAYMENT_TYPE_MASTER iptm"
	+" where ifm.FUNCTION_ID=icltl.FUNCTION_ID and icltl.PAYMENT_MODE=iptm.PAYMENT_TYPE_ID"
	+" and icltl.LICENSE_NO=? AND icltl.PAYMENT_FLAG='C' AND to_date(icltl.TRANSACTION_DATE) BETWEEN"
	+" ? AND ? ORDER BY (icltl.UPDATE_DATE)";
	//end 
	public static final String SELECTSERVICEPROVIDERACCTSTMT = "select iptd.PAYMENT_DATE,ispmd.TRANSACTION_ID,iptm.PAYMENT_TYPE_NAME,iptd.PAYMENT_AMOUNT"
		+ " from IGRS_SP_PAYMENT_MODE_DETAILS ispmd,IGRS_PAYMENT_TXN_DETAILS iptd,IGRS_PAYMENT_TYPE_MASTER iptm"
		+ " where iptm.PAYMENT_TYPE_ID=iptd.PAYMENT_TYPE_ID"
		+ " AND iptm.PAYMENT_TYPE_ID=ispmd.PAYMENT_TYPE_ID"
		+ " AND ispmd.TRANSACTION_ID=ispmd.TRANSACTION_ID"
		+ " AND SP_USER_ID=? " + "AND trim(TO_CHAR(TO_DATE(iptd.PAYMENT_DATE),'MON'))= UPPER(?) AND trim(TO_CHAR(TO_DATE(iptd.PAYMENT_DATE),'RRRR'))=?";


	public static final String RETRIVE_SP_USER_DETAILS="select iurd.FIRST_NAME,iurd.MIDDLE_NAME,iurd.LAST_NAME,iurd.GENDER,"
                                                     + "  iurd.OCCUPATION,iurd.GUARDIAN_NAME,iurd.DOB,iurd.MOTHER_NAME,"
													 + "	iurd.SPOUSE_NAME,iurd.ADDRESS,icm.COUNTRY_NAME,idm.DISTRICT_NAME,"
													 + "	ism.STATE_NAME,iurd.POSTAL_CODE,iurd.PHONE_NUMBER,iurd.MOBILE_NUMBER,"
													 +	" iurd.EMAIL_ID,iurd.ALTERNATE_EMAIL_ID ,iurd.PHOTO_PROOF_TYPE_ID,iurd.PHOTO_PROOF_ID "
													 + " ,iurd.BANK_NAME,iurd.BANK_ADDRESS,"
                                                      +  " iurd.OLD_REG_VOLUME_NO,iurd.OLD_REG_BOOK_NO,iurd.OLD_REG_NUMBER"
													 + "	FROM IGRS_USER_REG_DETAILS iurd,"
													  +	"     IGRS_STATE_MASTER ism,"
														+ "     IGRS_DISTRICT_MASTER idm,"
														 + "    IGRS_COUNTRY_MASTER icm"
													+ "	WHERE iurd.COUNTRY_ID=icm.COUNTRY_ID AND"
														    + "  iurd.DISTRICT_ID=idm.DISTRICT_ID AND"
														     + "  iurd.STATE_ID=ism.STATE_ID AND"
														      + " iurd.USER_ID =?";
	
    public static final String INSERT_SP_USER_DETAILS="INSERT INTO IGRS_SP_USER_LICENSE_DETAILS(LICENSE_TXN_ID,LICENSE_NO,SP_USER_ID,VALID_FROM,DISTRICT_ID,TEHSIL_ID,SP_OFFICE_ADDR,PINCODE,DR_COMMENTS,VALID_TO,LICENSE_STATUS,CREATED_BY,CREATED_DATE,UPDATE_BY,UPDATE_DATE,DOCUMENT_OBJ,DOCUMENT_NAME,LICENSE_CER_TXN_ID)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,sysdate,?,sysdate,EMPTY_BLOB(),?,?)";

    public static final String RETRIVE_REFRENCE_ID_SP_VIEW="select LICENSE_TXN_ID,SP_USER_ID,LICENSE_NO"
    														+" from IGRS_SP_USER_LICENSE_DETAILS"
    														+" where LICENSE_STATUS='A' AND "
    														+" DISTRICT_ID=(SELECT IGRS_OFFICE_MASTER.DISTRICT_ID FROM IGRS_OFFICE_MASTER,"
    														+" IGRS_EMP_OFFICE_MAPPING WHERE IGRS_OFFICE_MASTER.OFFICE_ID=IGRS_EMP_OFFICE_MAPPING.OFFICE_ID"
    														+" AND IGRS_EMP_OFFICE_MAPPING.EMP_ID=?) AND"
    														+" (trunc(CREATED_DATE) BETWEEN ? AND ?) OR (LICENSE_TXN_ID=?"
    														+" OR LICENSE_NO=?) ORDER BY LICENSE_TXN_ID" ;

    public static final String RETRIVE_SP_VIEW_LICENCE_DETAILS="select IUSRD.USER_ID,IUSRD.FIRST_NAME,IUSRD.MIDDLE_NAME,IUSRD.LAST_NAME,IUSRD.GENDER,to_char(IUSRD.DOB,'DD/MM/YYYY'),IUSRD.GUARDIAN_NAME,IUSRD.MOTHER_NAME,"+
    															"IUSRD.SPOUSE_NAME,IUSRD.ADDRESS,IDM.DISTRICT_NAME,ICM.COUNTRY_NAME,ISM.STATE_NAME,"
    															+"IUSRD.POSTAL_CODE,IUSRD.PHONE_NUMBER,IUSRD.MOBILE_NUMBER,IUSRD.EMAIL_ID,"
    															+"IUSRD.ALTERNATE_EMAIL_ID,IUSRD.PHOTO_PROOF_ID,to_char(ISPULD.VALID_FROM,'DD/MM/YYYY'),to_char(ISPULD.VALID_TO,'DD/MM/YYYY'),to_char(ISPULD.CREATED_DATE,'DD/MM/YYYY'),"
    															+"ISPULD.LICENSE_NO,ISPULD.DOCUMENT_NAME,ISPULD.SP_OFFICE_ADDR,IDMA.DISTRICT_NAME,ISPULD.DR_COMMENTS,ISPULD.LICENSE_TXN_ID"
    															+" FROM IGRS_USER_REG_DETAILS IUSRD,"
    															+"IGRS_SP_USER_LICENSE_DETAILS ISPULD,"
    															+"IGRS_COUNTRY_MASTER ICM, "
    															+"IGRS_STATE_MASTER ISM,IGRS_DISTRICT_MASTER IDM,"
    															+"IGRS_DISTRICT_MASTER IDMA"
    															+" WHERE IUSRD.USER_ID=("
    															+"SELECT DISTINCT SP_USER_ID FROM IGRS_SP_USER_LICENSE_DETAILS WHERE LICENSE_TXN_ID=?)"
    															+" AND ISPULD.LICENSE_TXN_ID=?"
    															+" AND IUSRD.COUNTRY_ID=ICM.COUNTRY_ID AND IUSRD.STATE_ID=ISM.STATE_ID AND"
    															+" IUSRD.DISTRICT_ID=IDM.DISTRICT_ID AND ISPULD.DISTRICT_ID=IDMA.DISTRICT_ID";


    public static final String SELECTUSERTYPE ="select USER_TYPE_ID,USER_TYPE_NAME from IGRS_USER_TYPE_MASTER where USER_TYPE_NAME IN('SP','SPB')";
    public static final String SPUSERTYPEID="select USER_TYPE_ID from IGRS_USER_TYPE_MASTER where USER_TYPE_NAME='SP'";
    public static final String SPBUSERTYPEID="select USER_TYPE_ID from IGRS_USER_TYPE_MASTER where USER_TYPE_NAME='SPB'";
      
    public static final String RETRIVE_SP_USER_DETAILS_1="select iurd.FIRST_NAME,iurd.MIDDLE_NAME,iurd.LAST_NAME,iurd.GENDER,"
        + "  iurd.OCCUPATION,iurd.GUARDIAN_NAME,iurd.DOB,iurd.MOTHER_NAME,"
		 + "	iurd.SPOUSE_NAME,iurd.ADDRESS,icm.COUNTRY_NAME,idm.DISTRICT_NAME,"
		 + "	ism.STATE_NAME,iurd.POSTAL_CODE,iurd.PHONE_NUMBER,iurd.MOBILE_NUMBER,"
		 +	" iurd.EMAIL_ID,iurd.ALTERNATE_EMAIL_ID ,iurd.PHOTO_PROOF_TYPE_ID,iurd.PHOTO_PROOF_ID "
		 + " ,iurd.BANK_NAME,iurd.BANK_ADDRESS,"
         +  " iurd.OLD_REG_VOLUME_NO,iurd.OLD_REG_BOOK_NO,iurd.OLD_REG_NUMBER,iurd.USER_ID"
		 + "	FROM IGRS_USER_REG_DETAILS iurd,"
		  +	"     IGRS_STATE_MASTER ism,"
			+ "     IGRS_DISTRICT_MASTER idm,"
			 + "    IGRS_COUNTRY_MASTER icm"
		+ "	WHERE iurd.COUNTRY_ID=icm.COUNTRY_ID AND"
			    + "  iurd.DISTRICT_ID=idm.DISTRICT_ID AND"
			     + "  iurd.STATE_ID=ism.STATE_ID AND"
			      + " iurd.USER_ID =?";
    
    
   public static final String LICENCE_DETAILS="INSERT INTO IGRS_LICENSE(SERIAL_NUMBER,LICENCE_NUMBER,INSERTED_DATE)VALUES(IGRS_TMP_LICENSE_SEQ.NEXTVAL,?,SYSDATE)";
   
   public static final String MM_LICENCE_NUMBER="SELECT SUBSTR(LICENCE_NUMBER,9,2) FROM IGRS_LICENSE WHERE SERIAL_NUMBER=(SELECT MAX(SERIAL_NUMBER) FROM IGRS_LICENSE)";
    
   public static final String RESET_LICENSE_ID_SEQ_1 = "DROP SEQUENCE IGRS_SP_LICENCE_SEQ_1";
   
   public static final String RESTART_LICENSE_ID_SEQ_1="CREATE SEQUENCE IGRS_SP_LICENCE_SEQ_1 START WITH 1 INCREMENT BY 1 MAXVALUE 999999999999999999999999999  MINVALUE 0  NOCYCLE NOCACHE ORDER";
  
   //public static final String RESTART_LICENSE_ID_SEQ_1="CREATE SEQUENCE IGRS_SP_LICENCE_SEQ_1 START WITH 1 INCREMENT BY 1 MAXVALUE 99999 MINVALUE 1 CYCLE CACHE 20 ORDER";
	  
   
   public static final String SELECTSPBANKS = "SELECT BANK_ID,BANK_NAME from IGRS_BANK_MASTER WHERE STATUS='A' ORDER BY BANK_NAME ASC";
   
   public static final String SELECTUSERDISTRICT ="select DISTRICT_ID,DISTRICT_NAME FROM IGRS_DISTRICT_MASTER"
+" WHERE DISTRICT_STATUS='A' AND DISTRICT_ID=(SELECT IGRS_OFFICE_MASTER.DISTRICT_ID FROM IGRS_OFFICE_MASTER,"
+" IGRS_EMP_OFFICE_MAPPING WHERE IGRS_OFFICE_MASTER.OFFICE_ID=IGRS_EMP_OFFICE_MAPPING.OFFICE_ID"
	  +" AND IGRS_EMP_OFFICE_MAPPING.EMP_ID=?)";
   
   public static final String SELECTUSERTEHSILS= "Select TEHSIL_ID,TEHSIL_NAME from IGRS_TEHSIL_MASTER Where DISTRICT_ID=? AND TEHSIL_STATUS='A' ORDER BY TEHSIL_NAME ASC";
   
   public static final String SELECTPROOFNAME="SELECT ppm.PHOTO_PROOF_TYPE_NAME  FROM IGRS_PHOTOID_PROOF_TYPE_MASTER ppm ,IGRS_USER_REG_DETAILS ure WHERE"
	   +" ppm.PHOTO_PROOF_TYPE_ID=ure.PHOTO_PROOF_TYPE_ID and PHOTO_PROOF_TYPE_NAME in('PAN CARD','ELECTION CARD','DRIVING LICENSE') and USER_ID=?";
   
   public static final String SELECTPROOFIDNUMBER="SELECT ure.PHOTO_PROOF_ID  FROM IGRS_PHOTOID_PROOF_TYPE_MASTER ppm ,IGRS_USER_REG_DETAILS ure WHERE" 
+" ppm.PHOTO_PROOF_TYPE_ID=ure.PHOTO_PROOF_TYPE_ID and PHOTO_PROOF_TYPE_NAME in('PAN CARD','ELECTION CARD','DRIVING LICENSE') and USER_ID=?";

   public static final String RETRIVE_SP_USER_DETAILS_NEW="select iurd.FIRST_NAME,iurd.MIDDLE_NAME,iurd.LAST_NAME,iurd.GENDER,"
       + "  iurd.OCCUPATION,iurd.GUARDIAN_NAME,to_char(iurd.DOB,'DD/MM/YYYY'),iurd.MOTHER_NAME,"
		 + "	iurd.SPOUSE_NAME,iurd.ADDRESS,icm.COUNTRY_NAME,idm.DISTRICT_NAME,"
		 + "	ism.STATE_NAME,iurd.POSTAL_CODE,iurd.PHONE_NUMBER,iurd.MOBILE_NUMBER,"
		 +	" iurd.EMAIL_ID,iurd.ALTERNATE_EMAIL_ID ,iurd.PHOTO_PROOF_TYPE_ID,iurd.PHOTO_PROOF_ID "
		 + " ,iurd.BANK_NAME,iurd.BANK_ADDRESS,"
        +  " iurd.OLD_REG_VOLUME_NO,iurd.OLD_REG_BOOK_NO,iurd.OLD_REG_NUMBER,ippm.PHOTO_PROOF_TYPE_NAME"
		 + "	FROM IGRS_USER_REG_DETAILS iurd,"
		  +	"     IGRS_STATE_MASTER ism,"
			+ "     IGRS_DISTRICT_MASTER idm,"
			 + "    IGRS_COUNTRY_MASTER icm, IGRS_PHOTOID_PROOF_TYPE_MASTER ippm"
		+ "	WHERE iurd.COUNTRY_ID=icm.COUNTRY_ID AND"
			    + "  iurd.DISTRICT_ID=idm.DISTRICT_ID AND"
			     + "  iurd.STATE_ID=ism.STATE_ID AND ippm.PHOTO_PROOF_TYPE_ID=iurd.PHOTO_PROOF_TYPE_ID AND"
			      + " iurd.USER_ID =?";

   public static final String INSERTSPBANKLICENCEDETAILS_NEW="insert into IGRS_SP_BANK_LICENSE_DETAILS(LICENSE_TXN_ID,LICENSE_NO,SP_BANK_USER_ID,VALID_FROM,DR_COMMENTS,VALID_TO,LICENSE_STATUS,CREATED_BY,"
+" CREATED_DATE,UPDATE_BY,UPDATE_DATE,BANK_ID,DISTRICT_ID,DOCUMENT_OBJ,DOCUMENT_NAME,SP_BANK_OFFICE_ADDR,LICENSE_CER_TXN_ID,BANK_AUTH_PRSN,BANK_PRSN_DESIG,BANK_CONTACT_INFO)"
+"  values(?,?,?,?,?,?,?,?,sysdate,?,sysdate,?,?,EMPTY_BLOB(),?,?,?,?,?,?)";

   
   public static final String INSERTSPBANKLICENCEDETAILS_NEW1="insert into IGRS_SP_BANK_LICENSE_DETAILS(LICENSE_TXN_ID,LICENSE_NO,SP_BANK_USER_ID,VALID_FROM,DR_COMMENTS,VALID_TO,LICENSE_STATUS,CREATED_BY,"
	   +" CREATED_DATE,UPDATE_BY,UPDATE_DATE,BANK_ID,DISTRICT_ID,DOCUMENT_OBJ,DOCUMENT_NAME,SP_BANK_OFFICE_ADDR,LICENSE_CER_TXN_ID,BANK_AUTH_PRSN,BANK_PRSN_DESIG,BANK_CONTACT_INFO)"
	   +"  values(?,?,?,?,?,?,'R',?,sysdate,?,sysdate,?,?,EMPTY_BLOB(),?,?,?,?,?,?)";
   
   //
   public static final String SPUSER_LICENCE_VALIDATION_QUERY="select * from IGRS_SP_USER_LICENSE_DETAILS where SP_USER_ID=? AND (LICENSE_STATUS='A' or LICENSE_STATUS='C')";
   
   public static final String SPBANK_LICENCE_VALIDATION_QUERY="select * from IGRS_SP_BANK_LICENSE_DETAILS where SP_BANK_USER_ID=? AND (LICENSE_STATUS='A' or LICENSE_STATUS='C')";

public static final String USER_ROLE_INSERT="UPDATE IGRS_USER_ROLE_GROUP_MAPPING SET ROLE_GROUP_ID=(SELECT ROLE_GROUP_ID FROM IGRS_ROLE_GROUP_MASTER WHERE ROLE_GROUP_NAME=?),ROLE_ID=(SELECT ROLE_ID FROM IGRS_ROLE_MASTER WHERE ROLE_NAME=?) WHERE USER_ID=?";


public static final String RETRIVE_DEAC_LICENCE_DETAILS="select IUSRD.USER_ID,IUSRD.FIRST_NAME,IUSRD.MIDDLE_NAME,IUSRD.LAST_NAME,IUSRD.GENDER,to_char(IUSRD.DOB,'DD/MM/YYYY'),IUSRD.GUARDIAN_NAME,IUSRD.MOTHER_NAME,"
		+" IUSRD.SPOUSE_NAME,IUSRD.ADDRESS,"
		+" ICM.COUNTRY_NAME,ISM.STATE_NAME,IDM.DISTRICT_NAME,"
+" IUSRD.POSTAL_CODE,IUSRD.EMAIL_ID,"
+" IUSRD.ALTERNATE_EMAIL_ID,IUSRD.PHONE_NUMBER,IUSRD.MOBILE_NUMBER,IUSRD.PHOTO_PROOF_ID,to_char(ISPULD.VALID_FROM,'DD/MM/YYYY'),"
+" to_char(ISPULD.VALID_TO,'DD/MM/YYYY'),to_char(ISPULD.CREATED_DATE,'DD/MM/YYYY'),"
+" ISPULD.LICENSE_NO,ISPULD.DOCUMENT_NAME,ISPULD.SP_OFFICE_ADDR,ISPULD.DR_COMMENTS,"
+" to_char(ISPBLD.VALID_FROM,'DD/MM/YYYY'),to_char(ISPBLD.VALID_TO,'DD/MM/YYYY'),"
+" to_char(ISPBLD.CREATED_DATE,'DD/MM/YYYY')," 
+" ISPBLD.LICENSE_NO,ISPBLD.DOCUMENT_NAME,ISPBLD.DR_COMMENTS,ISPBLD.LICENSE_TXN_ID"
+" FROM IGRS_USER_REG_DETAILS IUSRD left outer join"
+" IGRS_SP_USER_LICENSE_DETAILS ISPULD on IUSRD.USER_ID=ISPULD.SP_USER_ID LEFT OUTER JOIN"
+ " IGRS_SP_BANK_LICENSE_DETAILS ISPBLD ON IUSRD.USER_ID=ISPBLD.SP_BANK_USER_ID LEFT OUTER JOIN"
+ " IGRS_COUNTRY_MASTER ICM ON IUSRD.COUNTRY_ID=ICM.COUNTRY_ID LEFT OUTER JOIN" 
+ " IGRS_STATE_MASTER ISM ON IUSRD.STATE_ID=ISM.STATE_ID LEFT OUTER JOIN"
+ " IGRS_DISTRICT_MASTER IDM ON IUSRD.DISTRICT_ID=IDM.DISTRICT_ID"
+ " WHERE IUSRD.USER_ID=?";

public static final String RETRIVE_DEAC_SP_LICENCE_DETAILS="select IUSRD.USER_ID,IUSRD.FIRST_NAME,"
	+" IUSRD.MIDDLE_NAME,IUSRD.LAST_NAME,IUSRD.GENDER,to_char(IUSRD.DOB,'DD/MM/YYYY'),"
+" IUSRD.GUARDIAN_NAME,IUSRD.MOTHER_NAME,IUSRD.SPOUSE_NAME,IUSRD.ADDRESS,"
+" ICM.COUNTRY_NAME,ISM.STATE_NAME,IDM.DISTRICT_NAME,IUSRD.POSTAL_CODE,IUSRD.EMAIL_ID,"
+" IUSRD.ALTERNATE_EMAIL_ID,IUSRD.PHONE_NUMBER,IUSRD.MOBILE_NUMBER,IUSRD.PHOTO_PROOF_ID,"
+" to_char(ISPULD.VALID_FROM,'DD/MM/YYYY'),"
+" to_char(ISPULD.VALID_TO,'DD/MM/YYYY'),to_char(ISPULD.CREATED_DATE,'DD/MM/YYYY'),"
+" ISPULD.LICENSE_NO,ISPULD.DOCUMENT_NAME,ISPULD.SP_OFFICE_ADDR,ISPULD.DR_COMMENTS,ippm.PHOTO_PROOF_TYPE_NAME,IDMA.DISTRICT_NAME"
+" FROM IGRS_USER_REG_DETAILS IUSRD right outer join"
+" IGRS_SP_USER_LICENSE_DETAILS ISPULD on IUSRD.USER_ID=ISPULD.SP_USER_ID left OUTER JOIN"
+" IGRS_COUNTRY_MASTER ICM ON IUSRD.COUNTRY_ID=ICM.COUNTRY_ID LEFT OUTER JOIN"
+" IGRS_STATE_MASTER ISM ON IUSRD.STATE_ID=ISM.STATE_ID LEFT OUTER JOIN"
+" IGRS_DISTRICT_MASTER IDM ON IUSRD.DISTRICT_ID=IDM.DISTRICT_ID LEFT OUTER JOIN"
+" IGRS_DISTRICT_MASTER IDMA ON ISPULD.DISTRICT_ID=IDMA.DISTRICT_ID LEFT OUTER JOIN"
+" IGRS_PHOTOID_PROOF_TYPE_MASTER ippm ON ippm.PHOTO_PROOF_TYPE_ID=IUSRD.PHOTO_PROOF_TYPE_ID WHERE IUSRD.USER_ID=? AND ISPULD.LICENSE_STATUS='A'";


public static final String RETRIVE_DEAC_SP_BANK_LICENCE_DETAILS="select IUSRD.USER_ID,IUSRD.FIRST_NAME,"
	+" IUSRD.MIDDLE_NAME,IUSRD.LAST_NAME,IUSRD.GENDER,to_char(IUSRD.DOB,'DD/MM/YYYY'),"
+" IUSRD.GUARDIAN_NAME,IUSRD.MOTHER_NAME,IUSRD.SPOUSE_NAME,IUSRD.ADDRESS,"
+" ICM.COUNTRY_NAME,ISM.STATE_NAME,IDM.DISTRICT_NAME,IUSRD.POSTAL_CODE,IUSRD.EMAIL_ID,"
+" IUSRD.ALTERNATE_EMAIL_ID,IUSRD.PHONE_NUMBER,IUSRD.MOBILE_NUMBER,IUSRD.PHOTO_PROOF_ID,"
+" to_char(ISPBLD.VALID_FROM,'DD/MM/YYYY'),to_char(ISPBLD.VALID_TO,'DD/MM/YYYY'),"
+" to_char(ISPBLD.CREATED_DATE,'DD/MM/YYYY'), ISPBLD.LICENSE_NO,ISPBLD.DOCUMENT_NAME," 
+" ISPBLD.SP_BANK_OFFICE_ADDR,ISPBLD.DR_COMMENTS,ippm.PHOTO_PROOF_TYPE_NAME,IDMA.DISTRICT_NAME"
+" FROM IGRS_USER_REG_DETAILS IUSRD right outer join"
+"  IGRS_SP_BANK_LICENSE_DETAILS ISPBLD on IUSRD.USER_ID=ISPBLD.SP_BANK_USER_ID left OUTER JOIN"
+" IGRS_COUNTRY_MASTER ICM ON IUSRD.COUNTRY_ID=ICM.COUNTRY_ID LEFT OUTER JOIN"
+" IGRS_STATE_MASTER ISM ON IUSRD.STATE_ID=ISM.STATE_ID LEFT OUTER JOIN"
+" IGRS_DISTRICT_MASTER IDM ON IUSRD.DISTRICT_ID=IDM.DISTRICT_ID LEFT OUTER JOIN"
+" IGRS_DISTRICT_MASTER IDMA ON ISPBLD.DISTRICT_ID=IDMA.DISTRICT_ID LEFT OUTER JOIN"
+" IGRS_PHOTOID_PROOF_TYPE_MASTER ippm ON ippm.PHOTO_PROOF_TYPE_ID=IUSRD.PHOTO_PROOF_TYPE_ID"
+" WHERE IUSRD.USER_ID=? AND ISPBLD.LICENSE_STATUS='A'";

public static final String RETRIVE_DEAC_SP_LICENCE_DETAILS1="select IUSRD.USER_ID,IUSRD.FIRST_NAME,"
	+" IUSRD.MIDDLE_NAME,IUSRD.LAST_NAME,IUSRD.GENDER,to_char(IUSRD.DOB,'DD/MM/YYYY'),"
	+" IUSRD.GUARDIAN_NAME,IUSRD.MOTHER_NAME,IUSRD.SPOUSE_NAME,IUSRD.ADDRESS,"
	+" ICM.COUNTRY_NAME,ISM.STATE_NAME,IDM.DISTRICT_NAME,IUSRD.POSTAL_CODE,IUSRD.EMAIL_ID,"
	+" IUSRD.ALTERNATE_EMAIL_ID,IUSRD.PHONE_NUMBER,IUSRD.MOBILE_NUMBER,IUSRD.PHOTO_PROOF_ID,"
	+" to_char(ISPULD.VALID_FROM,'DD/MM/YYYY'),"
	+" to_char(ISPULD.VALID_TO,'DD/MM/YYYY'),to_char(ISPULD.CREATED_DATE,'DD/MM/YYYY'),"
	+" ISPULD.LICENSE_NO,ISPULD.DOCUMENT_NAME,ISPULD.SP_OFFICE_ADDR,ISPULD.DR_COMMENTS,"
	+" ippm.PHOTO_PROOF_TYPE_NAME,IDMA.DISTRICT_NAME,ISPULD.DISTRICT_ID,ISPULD.TEHSIL_ID"
	+" FROM IGRS_USER_REG_DETAILS IUSRD right outer join"
	+" IGRS_SP_USER_LICENSE_DETAILS ISPULD on IUSRD.USER_ID=ISPULD.SP_USER_ID left OUTER JOIN"
	+" IGRS_COUNTRY_MASTER ICM ON IUSRD.COUNTRY_ID=ICM.COUNTRY_ID LEFT OUTER JOIN"
	+" IGRS_STATE_MASTER ISM ON IUSRD.STATE_ID=ISM.STATE_ID LEFT OUTER JOIN"
	+" IGRS_DISTRICT_MASTER IDM ON IUSRD.DISTRICT_ID=IDM.DISTRICT_ID LEFT OUTER JOIN"
	+" IGRS_DISTRICT_MASTER IDMA ON ISPULD.DISTRICT_ID=IDMA.DISTRICT_ID LEFT OUTER JOIN"
	+" IGRS_PHOTOID_PROOF_TYPE_MASTER ippm ON ippm.PHOTO_PROOF_TYPE_ID=IUSRD.PHOTO_PROOF_TYPE_ID WHERE IUSRD.USER_ID=? AND ISPULD.LICENSE_STATUS='A'";

public static final String RETRIVE_DEAC_SP_BANK_LICENCE_DETAILS1="select IUSRD.USER_ID,IUSRD.FIRST_NAME,"
	+" IUSRD.MIDDLE_NAME,IUSRD.LAST_NAME,IUSRD.GENDER,to_char(IUSRD.DOB,'DD/MM/YYYY'),"
	+" IUSRD.GUARDIAN_NAME,IUSRD.MOTHER_NAME,IUSRD.SPOUSE_NAME,IUSRD.ADDRESS,"
	+" ICM.COUNTRY_NAME,ISM.STATE_NAME,IDM.DISTRICT_NAME,IUSRD.POSTAL_CODE,IUSRD.EMAIL_ID,"
	+" IUSRD.ALTERNATE_EMAIL_ID,IUSRD.PHONE_NUMBER,IUSRD.MOBILE_NUMBER,IUSRD.PHOTO_PROOF_ID,"
	+" to_char(ISPBLD.VALID_FROM,'DD/MM/YYYY'),to_char(ISPBLD.VALID_TO,'DD/MM/YYYY'),"
	+" to_char(ISPBLD.CREATED_DATE,'DD/MM/YYYY'), ISPBLD.LICENSE_NO,ISPBLD.DOCUMENT_NAME," 
	+" ISPBLD.SP_BANK_OFFICE_ADDR,ISPBLD.DR_COMMENTS,ippm.PHOTO_PROOF_TYPE_NAME,IDMA.DISTRICT_NAME,"
	+" ISPBLD.DISTRICT_ID,ISPBLD.BANK_ID,ISPBLD.BANK_AUTH_PRSN,BANK_PRSN_DESIG,BANK_CONTACT_INFO"
	+" FROM IGRS_USER_REG_DETAILS IUSRD right outer join"
	+" IGRS_SP_BANK_LICENSE_DETAILS ISPBLD on IUSRD.USER_ID=ISPBLD.SP_BANK_USER_ID left OUTER JOIN"
	+" IGRS_COUNTRY_MASTER ICM ON IUSRD.COUNTRY_ID=ICM.COUNTRY_ID LEFT OUTER JOIN"
	+" IGRS_STATE_MASTER ISM ON IUSRD.STATE_ID=ISM.STATE_ID LEFT OUTER JOIN"
	+" IGRS_DISTRICT_MASTER IDM ON IUSRD.DISTRICT_ID=IDM.DISTRICT_ID LEFT OUTER JOIN"
	+" IGRS_DISTRICT_MASTER IDMA ON ISPBLD.DISTRICT_ID=IDMA.DISTRICT_ID LEFT OUTER JOIN"
	+" IGRS_PHOTOID_PROOF_TYPE_MASTER ippm ON ippm.PHOTO_PROOF_TYPE_ID=IUSRD.PHOTO_PROOF_TYPE_ID"
	+" WHERE IUSRD.USER_ID=? AND ISPBLD.LICENSE_STATUS='A'";

public static final String DEAC_SP_ACNT="UPDATE IGRS_SP_USER_LICENSE_DETAILS SET LICENSE_STATUS='D',DR_COMMENTS=? WHERE SP_USER_ID=? AND (LICENSE_STATUS='A' or LICENSE_STATUS='R')";

public static final String DEAC_USER_LIST_ROLE="UPDATE IGRS_USERS_LIST SET USER_TYPE_ID=" 
	+" (SELECT USER_TYPE_ID FROM IGRS_USER_TYPE_MASTER WHERE USER_TYPE_NAME='RU') WHERE USER_ID=?";

public static final String DEAC_SPBANK_ACNT="UPDATE IGRS_SP_BANK_LICENSE_DETAILS SET LICENSE_STATUS='D',DR_COMMENTS=? WHERE SP_BANK_USER_ID=? AND (LICENSE_STATUS='A'or LICENSE_STATUS='R')";

public static final String UPDATE_USER_ACNT="UPDATE IGRS_USER_ROLE_GROUP_MAPPING SET ROLE_GROUP_ID="
+" (SELECT ROLE_GROUP_ID FROM IGRS_ROLE_GROUP_MASTER WHERE ROLE_GROUP_NAME=?),"
+" ROLE_ID=(SELECT ROLE_ID FROM IGRS_ROLE_MASTER WHERE ROLE_NAME=?) WHERE USER_ID=?";
	
public static final String RETRIVE_SP_VIEW_LICENCE_DETAILS_NEW="select IUSRD.USER_ID,IUSRD.FIRST_NAME,IUSRD.MIDDLE_NAME,IUSRD.LAST_NAME,IUSRD.GENDER,"
+" to_char(IUSRD.DOB,'DD/MM/YYYY'),IUSRD.GUARDIAN_NAME,IUSRD.MOTHER_NAME,"
+" IUSRD.SPOUSE_NAME,IUSRD.ADDRESS,ICM.COUNTRY_NAME,ISM.STATE_NAME,IDM.DISTRICT_NAME,"
+" IUSRD.POSTAL_CODE,IUSRD.EMAIL_ID,"
+" IUSRD.ALTERNATE_EMAIL_ID,IUSRD.PHONE_NUMBER,IUSRD.MOBILE_NUMBER,IUSRD.PHOTO_PROOF_ID,"
+" to_char(ISPULD.VALID_FROM,'DD/MM/YYYY'),"
+" to_char(ISPULD.VALID_TO,'DD/MM/YYYY'),to_char(ISPULD.CREATED_DATE,'DD/MM/YYYY'),"
+" ISPULD.LICENSE_NO,ISPULD.DOCUMENT_NAME,ISPULD.SP_OFFICE_ADDR,IDMA.DISTRICT_NAME,"
+" ISPULD.DR_COMMENTS,ISPULD.LICENSE_TXN_ID"
+" FROM IGRS_USER_REG_DETAILS IUSRD left outer join  IGRS_SP_USER_LICENSE_DETAILS ISPULD on"
+" IUSRD.USER_ID=ISPULD.SP_USER_ID left outer join  IGRS_COUNTRY_MASTER ICM on"
+" IUSRD.COUNTRY_ID=ICM.COUNTRY_ID left outer join  IGRS_STATE_MASTER ISM on"
+" IUSRD.STATE_ID=ISM.STATE_ID left outer join  IGRS_DISTRICT_MASTER IDM on"
+" IUSRD.DISTRICT_ID=IDM.DISTRICT_ID left outer join IGRS_DISTRICT_MASTER IDMA on" 
+" ISPULD.DISTRICT_ID=IDMA.DISTRICT_ID" 
+" WHERE IUSRD.USER_ID=(SELECT DISTINCT SP_USER_ID FROM IGRS_SP_USER_LICENSE_DETAILS WHERE LICENSE_STATUS='A' AND LICENSE_TXN_ID=?)" 
+" AND ISPULD.LICENSE_TXN_ID=?";

public static final String RETRIVE_SP_BANK_VIEW_LICENCE_DETAILS="select IUSRD.USER_ID,IUSRD.FIRST_NAME,IUSRD.MIDDLE_NAME,IUSRD.LAST_NAME,IUSRD.GENDER,"
+" to_char(IUSRD.DOB,'DD/MM/YYYY'),IUSRD.GUARDIAN_NAME,IUSRD.MOTHER_NAME,"
+" IUSRD.SPOUSE_NAME,IUSRD.ADDRESS,ICM.COUNTRY_NAME,ISM.STATE_NAME,IDM.DISTRICT_NAME,"
+" IUSRD.POSTAL_CODE,IUSRD.EMAIL_ID,"
+" IUSRD.ALTERNATE_EMAIL_ID,IUSRD.PHONE_NUMBER,IUSRD.MOBILE_NUMBER,IUSRD.PHOTO_PROOF_ID,"
+" to_char(ISPBLD.VALID_FROM,'DD/MM/YYYY'),"
+" to_char(ISPBLD.VALID_TO,'DD/MM/YYYY'),to_char(ISPBLD.CREATED_DATE,'DD/MM/YYYY'),"
+" ISPBLD.LICENSE_NO,ISPBLD.DOCUMENT_NAME,ISPBLD.SP_BANK_OFFICE_ADDR,IDMA.DISTRICT_NAME,"
+" ISPBLD.DR_COMMENTS,ISPBLD.LICENSE_TXN_ID"
+" FROM IGRS_USER_REG_DETAILS IUSRD left outer join  IGRS_SP_BANK_LICENSE_DETAILS ISPBLD on"
+" IUSRD.USER_ID=ISPBLD.SP_BANK_USER_ID left outer join  IGRS_COUNTRY_MASTER ICM on"
+" IUSRD.COUNTRY_ID=ICM.COUNTRY_ID left outer join  IGRS_STATE_MASTER ISM on"
+" IUSRD.STATE_ID=ISM.STATE_ID left outer join  IGRS_DISTRICT_MASTER IDM on"
+" IUSRD.DISTRICT_ID=IDM.DISTRICT_ID left outer join IGRS_DISTRICT_MASTER IDMA on" 
+" ISPBLD.DISTRICT_ID=IDMA.DISTRICT_ID" 
+" WHERE IUSRD.USER_ID=(SELECT DISTINCT SP_BANK_USER_ID FROM IGRS_SP_BANK_LICENSE_DETAILS WHERE LICENSE_STATUS='A' AND LICENSE_TXN_ID=?)" 
+" AND ISPBLD.LICENSE_TXN_ID=?";


public static final String RETRIVE_REFRENCE_ID_SP_BANK_VIEW="select LICENSE_TXN_ID,SP_BANK_USER_ID,"
+" LICENSE_NO FROM IGRS_SP_BANK_LICENSE_DETAILS WHERE LICENSE_STATUS='A' AND"
+" DISTRICT_ID=(SELECT IGRS_OFFICE_MASTER.DISTRICT_ID FROM IGRS_OFFICE_MASTER,"
+" IGRS_EMP_OFFICE_MAPPING WHERE IGRS_OFFICE_MASTER.OFFICE_ID=IGRS_EMP_OFFICE_MAPPING.OFFICE_ID"
+"	AND IGRS_EMP_OFFICE_MAPPING.EMP_ID=?) AND"
+" (trunc(CREATED_DATE) BETWEEN ? AND ?) OR (LICENSE_TXN_ID=?"
+" OR LICENSE_NO=?) ORDER BY LICENSE_TXN_ID";

public static final String CERTIFICATE_TXN_ID="SELECT IGRS_LICENSE_CERTIFICATE_SEQ.NEXTVAL FROM DUAL";

public static final String RETRIVE_RENEW_SP_LICENCE_DETAILS="select IUSRD.USER_ID,IUSRD.FIRST_NAME,"
+" IUSRD.MIDDLE_NAME,IUSRD.LAST_NAME,IUSRD.GENDER,to_char(IUSRD.DOB,'DD/MM/YYYY'),"
+" IUSRD.GUARDIAN_NAME,IUSRD.MOTHER_NAME,IUSRD.SPOUSE_NAME,IUSRD.ADDRESS,"
+" ICM.COUNTRY_NAME,ISM.STATE_NAME,IDM.DISTRICT_NAME,IUSRD.POSTAL_CODE,IUSRD.EMAIL_ID,"
+" IUSRD.ALTERNATE_EMAIL_ID,IUSRD.PHONE_NUMBER,IUSRD.MOBILE_NUMBER,IUSRD.PHOTO_PROOF_ID,"
+" to_char(ISPULD.VALID_FROM,'DD/MM/YYYY'),"
+" to_char(ISPULD.VALID_TO,'DD/MM/YYYY'),to_char(ISPULD.CREATED_DATE,'DD/MM/YYYY'),"
+" ISPULD.LICENSE_NO,ISPULD.DOCUMENT_NAME,ISPULD.SP_OFFICE_ADDR,ISPULD.DR_COMMENTS,"
+" ippm.PHOTO_PROOF_TYPE_NAME,IDMA.DISTRICT_NAME,ISPULD.DISTRICT_ID,to_char(ISPULD.VALID_TO+1,'DD/MM/YYYY'),ISPULD.TEHSIL_ID"
+" FROM IGRS_USER_REG_DETAILS IUSRD right outer join"
+" IGRS_SP_USER_LICENSE_DETAILS ISPULD on IUSRD.USER_ID=ISPULD.SP_USER_ID left OUTER JOIN"
+" IGRS_COUNTRY_MASTER ICM ON IUSRD.COUNTRY_ID=ICM.COUNTRY_ID LEFT OUTER JOIN"
+" IGRS_STATE_MASTER ISM ON IUSRD.STATE_ID=ISM.STATE_ID LEFT OUTER JOIN"
+" IGRS_DISTRICT_MASTER IDM ON IUSRD.DISTRICT_ID=IDM.DISTRICT_ID LEFT OUTER JOIN"
+" IGRS_DISTRICT_MASTER IDMA ON ISPULD.DISTRICT_ID=IDMA.DISTRICT_ID LEFT OUTER JOIN"
+" IGRS_TEHSIL_MASTER TMA on ISPULD.TEHSIL_ID=TMA.TEHSIL_ID LEFT OUTER JOIN"
+" IGRS_PHOTOID_PROOF_TYPE_MASTER ippm ON ippm.PHOTO_PROOF_TYPE_ID=IUSRD.PHOTO_PROOF_TYPE_ID WHERE IUSRD.USER_ID=? AND LICENSE_STATUS='A'";


public static final String RETRIVE_RENEW_SP_BANK_LICENCE_DETAILS="select IUSRD.USER_ID,IUSRD.FIRST_NAME,"
+" IUSRD.MIDDLE_NAME,IUSRD.LAST_NAME,IUSRD.GENDER,to_char(IUSRD.DOB,'DD/MM/YYYY'),"
+" IUSRD.GUARDIAN_NAME,IUSRD.MOTHER_NAME,IUSRD.SPOUSE_NAME,IUSRD.ADDRESS,"
+" ICM.COUNTRY_NAME,ISM.STATE_NAME,IDM.DISTRICT_NAME,IUSRD.POSTAL_CODE,IUSRD.EMAIL_ID,"
+" IUSRD.ALTERNATE_EMAIL_ID,IUSRD.PHONE_NUMBER,IUSRD.MOBILE_NUMBER,IUSRD.PHOTO_PROOF_ID,"
+" to_char(ISPBLD.VALID_FROM,'DD/MM/YYYY'),to_char(ISPBLD.VALID_TO,'DD/MM/YYYY'),"
+" to_char(ISPBLD.CREATED_DATE,'DD/MM/YYYY'), ISPBLD.LICENSE_NO,ISPBLD.DOCUMENT_NAME,"
+" ISPBLD.SP_BANK_OFFICE_ADDR,ISPBLD.DR_COMMENTS,ippm.PHOTO_PROOF_TYPE_NAME,IDMA.DISTRICT_NAME,ISPBLD.DISTRICT_ID,to_char(ISPBLD.VALID_TO+1,'DD/MM/YYYY'),ISPBLD.BANK_ID"
+" FROM IGRS_USER_REG_DETAILS IUSRD right outer join"
+" IGRS_SP_BANK_LICENSE_DETAILS ISPBLD on IUSRD.USER_ID=ISPBLD.SP_BANK_USER_ID left OUTER JOIN"
+" IGRS_COUNTRY_MASTER ICM ON IUSRD.COUNTRY_ID=ICM.COUNTRY_ID LEFT OUTER JOIN"
+" IGRS_STATE_MASTER ISM ON IUSRD.STATE_ID=ISM.STATE_ID LEFT OUTER JOIN"
+" IGRS_DISTRICT_MASTER IDM ON IUSRD.DISTRICT_ID=IDM.DISTRICT_ID LEFT OUTER JOIN"
+" IGRS_DISTRICT_MASTER IDMA ON ISPBLD.DISTRICT_ID=IDMA.DISTRICT_ID LEFT OUTER JOIN"
+" IGRS_PHOTOID_PROOF_TYPE_MASTER ippm ON ippm.PHOTO_PROOF_TYPE_ID=IUSRD.PHOTO_PROOF_TYPE_ID"
+" WHERE IUSRD.USER_ID=? AND ISPBLD.LICENSE_STATUS='A'";

public static final String RETRIVE_RENEW_SP_BANK_LICENCE_DETAILS1=" select IUSRD.USER_ID,IUSRD.FIRST_NAME,"
+" IUSRD.MIDDLE_NAME,IUSRD.LAST_NAME,IUSRD.GENDER,to_char(IUSRD.DOB,'DD/MM/YYYY'),"
+" IUSRD.GUARDIAN_NAME,IUSRD.MOTHER_NAME,IUSRD.SPOUSE_NAME,IUSRD.ADDRESS, ICM.COUNTRY_NAME,ISM.STATE_NAME,IDM.DISTRICT_NAME,IUSRD.POSTAL_CODE,IUSRD.EMAIL_ID,"
+" IUSRD.ALTERNATE_EMAIL_ID,IUSRD.PHONE_NUMBER,IUSRD.MOBILE_NUMBER,IUSRD.PHOTO_PROOF_ID,"
+" to_char(ISPBLD.VALID_FROM,'DD/MM/YYYY'),to_char(ISPBLD.VALID_TO,'DD/MM/YYYY'),"
+" to_char(ISPBLD.CREATED_DATE,'DD/MM/YYYY'), ISPBLD.LICENSE_NO,ISPBLD.DOCUMENT_NAME,"
+" ISPBLD.SP_BANK_OFFICE_ADDR,ISPBLD.DR_COMMENTS,ippm.PHOTO_PROOF_TYPE_NAME,IDMA.DISTRICT_NAME,"
+" ISPBLD.DISTRICT_ID,to_char(ISPBLD.VALID_TO+1,'DD/MM/YYYY'),ISPBLD.BANK_ID,ISPBLD.BANK_AUTH_PRSN,BANK_PRSN_DESIG,BANK_CONTACT_INFO"
+" FROM IGRS_USER_REG_DETAILS IUSRD right outer join"
+" IGRS_SP_BANK_LICENSE_DETAILS ISPBLD on IUSRD.USER_ID=ISPBLD.SP_BANK_USER_ID left OUTER JOIN"
+" IGRS_COUNTRY_MASTER ICM ON IUSRD.COUNTRY_ID=ICM.COUNTRY_ID LEFT OUTER JOIN"
+" IGRS_STATE_MASTER ISM ON IUSRD.STATE_ID=ISM.STATE_ID LEFT OUTER JOIN"
+" IGRS_DISTRICT_MASTER IDM ON IUSRD.DISTRICT_ID=IDM.DISTRICT_ID LEFT OUTER JOIN"
+" IGRS_DISTRICT_MASTER IDMA ON ISPBLD.DISTRICT_ID=IDMA.DISTRICT_ID LEFT OUTER JOIN"
+" IGRS_PHOTOID_PROOF_TYPE_MASTER ippm ON ippm.PHOTO_PROOF_TYPE_ID=IUSRD.PHOTO_PROOF_TYPE_ID"
+" WHERE IUSRD.USER_ID=? AND ISPBLD.LICENSE_STATUS='A'";

public static final String LICENSE_STATUS_CHANGE_SPBANK="UPDATE IGRS_SP_BANK_LICENSE_DETAILS SET LICENSE_STATUS='D' WHERE SP_BANK_USER_ID=?"; 

public static final String LICENSE_STATUS_CHANGE_SP="UPDATE IGRS_SP_USER_LICENSE_DETAILS SET LICENSE_STATUS='D' WHERE SP_USER_ID=?";

public static final String SELECTSERVICEPROVIDERACCOUNTINFONEW="select iclt.LICENSE_NO,"
+" (select first_name||' '||middle_name||' '||last_name from IGRS_USER_REG_DETAILS"
+" where USER_ID=?) as ACNT_HOLDER_NAME,NVL(iclt.ACCOUNT_BAL,0) from"
+" IGRS_CREDIT_LIMIT_TXN_LOG iclt,IGRS_SP_USER_LICENSE_DETAILS iusd"
+" WHERE iclt.LICENSE_NO=iusd.LICENSE_NO and iusd.LICENSE_STATUS='A'";



/*public static final String SELECTSERVICEPROVIDERACCOUNTINFONEW1="SELECT distinct LICENSE_NO," 
		+" (select first_name||' '||middle_name||' '||last_name" 
		+" from IGRS_USER_REG_DETAILS where USER_ID=?) as ACNT_HOLDER_NAME"
				+ " FROM IGRS_CREDIT_LIMIT_TXN_LOG WHERE LICENSE_NO=? AND SR_NO=(SELECT MAX(SR_NO) FROM"
	+" IGRS_CREDIT_LIMIT_TXN_LOG where LICENSE_NO=?)";*/


public static final String SELECTSERVICEPROVIDERACCOUNTINFONEW1="SELECT distinct LICENSE_NO,"
		+"(select first_name||' '||middle_name||' '||last_name"
		+" from IGRS_USER_REG_DETAILS where USER_ID=?) as ACNT_HOLDER_NAME,nvl(ACCOUNT_BAL,0)"
		  +" FROM IGRS_CREDIT_LIMIT_TXN_LOG WHERE LICENSE_NO=? and  PAYMENT_FLAG='C'"
		  +" AND UPDATE_DATE=(SELECT MAX(UPDATE_DATE) FROM IGRS_CREDIT_LIMIT_TXN_LOG " 
		  		+" where LICENSE_NO=? and PAYMENT_FLAG='C')";

public static final String SELECTSPDETAILS="SELECT distinct iusd.LICENSE_NO,"
+" (select first_name||' '||middle_name||' '||last_name from IGRS_USER_REG_DETAILS"
+" where USER_ID=?) as ACNT_HOLDER_NAME,0 from"
+" IGRS_SP_USER_LICENSE_DETAILS iusd"
+" WHERE iusd.LICENSE_NO=(SELECT LICENSE_NO FROM"
+" IGRS_SP_USER_LICENSE_DETAILS WHERE SP_USER_ID=? and LICENSE_STATUS='A')";


public static final String SELECTSPBANKDETAILS="SELECT distinct iusd.LICENSE_NO,"
	+" (select first_name||' '||middle_name||' '||last_name from IGRS_USER_REG_DETAILS"
	+" where USER_ID=?) as ACNT_HOLDER_NAME,0 from"
	+" IGRS_SP_BANK_LICENSE_DETAILS iusd"
	+" WHERE iusd.LICENSE_NO=(SELECT LICENSE_NO FROM"
	+" IGRS_SP_BANK_LICENSE_DETAILS WHERE SP_BANK_USER_ID=? and LICENSE_STATUS='A')";

public static final String CREDIT_SP_ACNT="INSERT INTO IGRS_CREDIT_LIMIT_TXN_LOG(SR_NO,LICENSE_NO,"
+"CREDIT_OR_DEBIT,PAYMENT_FLAG,CREATED_BY,CREATED_DATE,FUNCTION_ID"
+") VALUES(?,?,'C','I',?,SYSDATE,?)";

public static final String SELECT_CRDT_LIMIT_TXN_SEQ = "SELECT IGRS_CRDT_LIMIT_TXN_SEQ.NEXTVAL FROM DUAL";

public static final String DEBIT_SP_ACNT="INSERT INTO IGRS_CREDIT_LIMIT_TXN_LOG(SR_NO,LICENSE_NO,"
+" TRANSACTION_DATE,TRANSACTION_MODE,CREDIT_OR_DEBIT,"
+" TRANSACTION_ID,TRANSACTION_AMOUNT,TRANSACTION_PURPOSE,ACCOUNT_BAL,SP_COMM) VALUES(?,?,sysdate,?,'D',?,?,?,?,?)";

public static final String UPDATE_USERS_LIST_SP_ROLE="UPDATE IGRS_USERS_LIST SET USER_TYPE_ID=" 
	+" (SELECT USER_TYPE_ID FROM IGRS_USER_TYPE_MASTER WHERE USER_TYPE_NAME='SP') WHERE USER_ID=?";

public static final String UPDATE_USERS_LIST_SPBANK_ROLE="UPDATE IGRS_USERS_LIST SET USER_TYPE_ID="
+" (SELECT USER_TYPE_ID FROM IGRS_USER_TYPE_MASTER WHERE USER_TYPE_NAME='SPB') WHERE USER_ID=?";

public static final String SELECTCREDITBALANCE="SELECT distinct ACCOUNT_BAL,LICENSE_NO FROM IGRS_CREDIT_LIMIT_TXN_LOG WHERE"
	+" LICENSE_NO=? AND SR_NO=(SELECT MAX(SR_NO) FROM IGRS_CREDIT_LIMIT_TXN_LOG where LICENSE_NO=?)";


public static final String SELECTLICENSENUMBER="select distinct  LICENSE_NO FROM IGRS_SP_USER_LICENSE_DETAILS WHERE SP_USER_ID=? and LICENSE_STATUS='A'"; 

public static final String SELECTLICENSENUMBER1="select distinct LICENSE_NO FROM IGRS_SP_BANK_LICENSE_DETAILS WHERE SP_BANK_USER_ID=? and LICENSE_STATUS='A'";

public static final String SELECTSPCOMMFACTOR="SELECT ATTRIBUTE_VALUE FROM  IGRS_CONFIG_PARAM_LIST WHERE ATTRIBUTE_NAME='SPCOMMISSIONFACTOR'";


public static final String SPPAYMENTFLAGSTATUS="SELECT PAYMENT_FLAG from IGRS_CREDIT_LIMIT_TXN_LOG where SR_NO=";

public static final String SETPAYMENTSTATUS="UPDATE IGRS_CREDIT_LIMIT_TXN_LOG SET PAYMENT_FLAG='C' WHERE SR_NO=?";

public static final String GETCREDITAMOUNT="select nvl(sum(PAID_AMOUNT),0) from IGRS_CREDIT_LIMIT_TXN_LOG where LICENSE_NO=?" 
+" and CREDIT_OR_DEBIT='C' and PAYMENT_FLAG='C'";

public static final String GETDEBITAMOUNT="select nvl(sum(PAID_AMOUNT),0) from IGRS_CREDIT_LIMIT_TXN_LOG where LICENSE_NO=?" 
+" and CREDIT_OR_DEBIT='D' and PAYMENT_FLAG='C'";

public static final String GETPAIDAMT="SELECT PAID_AMOUNT from IGRS_CREDIT_LIMIT_TXN_LOG where SR_NO=?";

public static final String UPDATESPAMT="UPDATE IGRS_CREDIT_LIMIT_TXN_LOG SET SP_AMOUNT=? WHERE SR_NO=?";


//added by shruti
public static final String CURRENT_DATE_TIME="select to_char(sysdate,'dd/MM/yyyy hh:mm:ss AM') from dual";
public static final String GETCURRENTDATE="SELECT TO_CHAR(SYSDATE,'dd/MM/yyyy') from dual";
public static final String SPCOMMISION_CALC="CALL "
	+"IGRS_SP_COMM_CALC_PKG.IGRS_SP_COMMISSION_CALC_PROC(?,?,?)";

//END
/*public static final String SPOPENINGBALANCE="select account_bal from igrs_credit_limit_txn_log" 
+" where license_no=? and payment_flag='C'and update_date=(select"
+" max(update_date) from igrs_credit_limit_txn_log where license_no=?" 
+" and payment_flag='C' and update_date not in(select max(update_date) from igrs_credit_limit_txn_log"
+" where license_no=? and payment_flag='C'))";*/
public static final String SPOPENINGBALANCE="SELECT distinct nvl(ACCOUNT_BAL,0) FROM IGRS_CREDIT_LIMIT_TXN_LOG WHERE LICENSE_NO=? and  PAYMENT_FLAG='C' AND UPDATE_DATE=(SELECT MAX(UPDATE_DATE) FROM IGRS_CREDIT_LIMIT_TXN_LOG " 
		  		+" where LICENSE_NO=? and PAYMENT_FLAG='C')";
public static final String SPUSER_LICENCE_RENEWED_VALIDATION_QUERY="select * from IGRS_SP_USER_LICENSE_DETAILS where SP_USER_ID=? AND LICENSE_STATUS='R'";

public static final String SPBANK_LICENCE_RENEWED_VALIDATION_QUERY="select * from IGRS_SP_BANK_LICENSE_DETAILS where SP_BANK_USER_ID=? AND LICENSE_STATUS='R'";
}