package com.wipro.igrs.applicationlog.sql;

public class ApplicationLogSQL {
	 

	public static final String SELECTED_FIELDS = "SELECT TABLE_NAME,OPERATION_TYPE,OPEATION_STATUS, " +
	"to_char(OPERATION_DATE,'DD/MM/YYYY')," +
	"nvl((SELECT FUNCTION_NAME FROM igrs_function_master WHERE function_id= IGRS_APPLICATION_LOG.OPERATED_BY),'-') AS OPERATED_BY," +
	"(SELECT FUNCTION_NAME FROM igrs_function_master WHERE function_id=IGRS_APPLICATION_LOG.OPERATED_FUNCTION_ID) AS OPERATED_FUNCTION_ID," +
	"(SELECT ROLE_NAME FROM IGRS_ROLE_MASTER WHERE ROLE_ID=OPERATED_ROLE_ID)AS OPERATED_ROLE_ID"+
	" FROM IGRS_APPLICATION_LOG WHERE ";
	

	public static final String SELECT_BY_DATE = SELECTED_FIELDS+"(OPERATION_DATE BETWEEN TO_DATE(?,'DD/MM/YYYY') AND TO_DATE(?,'DD/MM/YYYY')+1) ORDER BY CREATED_DATE DESC";
	
	
	public static final String SELECT_BY_DATE_TRANS ="SELECT " +
			" (SELECT FUNCTION_NAME FROM IGRS_FUNCTION_MASTER WHERE FUNCTION_ID=IGRS_PAYMENT_MODE_DETAILS.FUNCTION_ID) AS FUNCTION_NAME, " +
			" GROSS_AMOUNT, nvl(REMARKS,'-'),CREATED_BY,to_char(CREATED_DATE,'DD/MM/YYYY') " +
			" FROM IGRS_PAYMENT_MODE_DETAILS " +
			" WHERE (CREATED_DATE BETWEEN TO_DATE(?,'DD/MM/YYYY') AND TO_DATE(?,'DD/MM/YYYY')+1) AND STATUS_FLAG='D' ORDER BY CREATED_DATE DESC ";
	
	public static final String SELECT_APP_LOG = "SELECT T.ACTIVITY_NAME , M.MODULE_NAME, A.CREATED_DATE,A.USER_ID,T.H_ACTIVITY_NAME,M.H_MODULE_NAME FROM IGRS_ACTIVITY_LOG A, IGRS_ACTIVITY_MASTER T , IGRS_FUNCTION_MASTER F, " +
												" IGRS_MODULE_MASTER M, IGRS_SUB_MODULE_MASTER SB WHERE trunc(A.CREATED_DATE) " +
												" BETWEEN ? AND ? AND A.OPERATED_ACTIVITY_ID = T.ACTIVITY_ID " +
												" AND T.FUNCTION_ID = F.FUNCTION_ID AND F.SUB_MODULE_ID = SB.SUB_MODULE_ID AND SB.MODULE_ID = M.MODULE_ID AND  A.USER_ID =? AND A.LOG_STATUS_FLAG='A' " +
												" AND T.ACTIVITY_NAME IS NOT NULL AND M.MODULE_NAME IS NOT NULL  ORDER BY A.CREATED_DATE DESC ";
	
	public static final String DELETE_ACTIVITY_LOG = "UPDATE IGRS_ACTIVITY_LOG SET LOG_STATUS_FLAG='D' WHERE TRUNC(CREATED_DATE) BETWEEN TO_DATE(?,'DD/MM/YYYY') AND TO_DATE(?,'DD/MM/YYYY') AND USER_ID = ?";
	
	 public static final String DELETE_ADMIN_ACTIVITY_LOG = "UPDATE IGRS_ACTIVITY_LOG SET LOG_STATUS_FLAG='D' WHERE TRUNC(CREATED_DATE) BETWEEN TO_DATE(?,'DD/MM/YYYY') AND TO_DATE(?,'DD/MM/YYYY')";


	public static final String GET_ROLE_GROUP = "select RG.ROLE_GROUP_NAME from IGRS_ROLE_GROUP_MASTER RG," +
												" IGRS_USER_ROLE_GROUP_MAPPING URG where URG.USER_ID = ? AND URG.ROLE_GROUP_ID = RG.ROLE_GROUP_ID";

	
	public static final String SELECT_APP_LOG_FOR_ADMIN = "SELECT T.ACTIVITY_NAME,M.MODULE_NAME,A.CREATED_DATE,A.USER_ID,T.H_ACTIVITY_NAME,M.H_MODULE_NAME FROM IGRS_ACTIVITY_LOG A, IGRS_ACTIVITY_MASTER T , IGRS_FUNCTION_MASTER F, " +
															" IGRS_MODULE_MASTER M, IGRS_SUB_MODULE_MASTER SB WHERE trunc(A.CREATED_DATE) " +
															" BETWEEN ? AND ? AND A.OPERATED_ACTIVITY_ID = T.ACTIVITY_ID " +
															" AND T.FUNCTION_ID = F.FUNCTION_ID AND F.SUB_MODULE_ID = SB.SUB_MODULE_ID AND SB.MODULE_ID = M.MODULE_ID AND A.LOG_STATUS_FLAG='A' AND T.ACTIVITY_NAME IS NOT NULL AND M.MODULE_NAME IS NOT NULL " +
															" ORDER BY A.CREATED_DATE DESC ";

	
	public static final String SELECT_ADMIN_TRANSACTION_LOG_DETAILS = "SELECT T.ACTIVITY_NAME,M.MODULE_NAME,A.CREATED_DATE,A.USER_ID,T.H_ACTIVITY_NAME,M.H_MODULE_NAME,A.PAYMENT_STATUS,A.PAYMENT_TRANSACTION_ID,A.AMOUNT FROM IGRS_TRANSACTION_LOG A, IGRS_ACTIVITY_MASTER T , IGRS_FUNCTION_MASTER F, " +
																		" IGRS_MODULE_MASTER M, IGRS_SUB_MODULE_MASTER SB WHERE trunc(A.CREATED_DATE) " +
																		" BETWEEN ? AND ? AND A.ACTIVITY_ID = T.ACTIVITY_ID " +
																		" AND T.FUNCTION_ID = F.FUNCTION_ID AND F.SUB_MODULE_ID = SB.SUB_MODULE_ID AND SB.MODULE_ID = M.MODULE_ID AND A.LOG_FLAG='A' AND T.ACTIVITY_NAME IS NOT NULL AND M.MODULE_NAME IS NOT NULL " +
																		" ORDER BY A.CREATED_DATE DESC ";
	
	
	public static final String SELECT_TRANSACTION_LOG_DETAILS = "SELECT T.ACTIVITY_NAME,M.MODULE_NAME,A.CREATED_DATE,A.USER_ID,T.H_ACTIVITY_NAME,M.H_MODULE_NAME,A.PAYMENT_STATUS,A.PAYMENT_TRANSACTION_ID,A.AMOUNT FROM IGRS_TRANSACTION_LOG A, IGRS_ACTIVITY_MASTER T , IGRS_FUNCTION_MASTER F, " +
																" IGRS_MODULE_MASTER M, IGRS_SUB_MODULE_MASTER SB WHERE trunc(A.CREATED_DATE) " +
																" BETWEEN ? AND ? AND A.ACTIVITY_ID = T.ACTIVITY_ID " +
																" AND T.FUNCTION_ID = F.FUNCTION_ID AND F.SUB_MODULE_ID = SB.SUB_MODULE_ID AND SB.MODULE_ID = M.MODULE_ID  A.USER_ID =? AND A.LOG_FLAG='A' AND T.ACTIVITY_NAME IS NOT NULL AND M.MODULE_NAME IS NOT NULL " +
																" ORDER BY A.CREATED_DATE DESC ";

	
	
	
	public static final String DELETE_ADMIN_TXN_LOGS = "UPDATE IGRS_TRANSACTION_LOG SET LOG_FLAG ='D' WHERE TRUNC(CREATED_DATE) BETWEEN TO_DATE(?,'DD/MM/YYYY') AND TO_DATE(?,'DD/MM/YYYY')";
	
	public static final String DELETE_TXN_LOGS = "UPDATE IGRS_TRANSACTION_LOG SET LOG_FLAG ='D' WHERE TRUNC(CREATED_DATE) BETWEEN TO_DATE(?,'DD/MM/YYYY') AND TO_DATE(?,'DD/MM/YYYY') AND USER_ID = ?";


}
