package com.wipro.igrs.municipalbodymaster.sql;

/**
 * This class contains the SQL statements used in 
 * com.wipro.igrs.municipalbodymaster.dao.MunicipalBodyDAO class.
 * @author Mostafa Mahmoud
 * @version 1.0
 */
public class MunicipalBodyCommonSQL {
	 
	public static final String SELECT_MUNICIPAL_BODY_MASTER 	= "SELECT MUNICIPAL_BODY_ID, MUNICIPAL_BODY_NAME, MUNICIPAL_BODY_DESC, MUNICIPAL_BODY_STATUS, CREATED_BY, CREATED_DATE, UPDATE_BY, UPDATE_DATE FROM IGRS_GOV_MUNICIPAL_BODY_MASTER WHERE MUNICIPAL_BODY_STATUS NOT LIKE 'R'";
	
	public static final String SELECT_MUNICIPAL_BODY_MASTER_ID 	= "SELECT MUNICIPAL_BODY_NAME, MUNICIPAL_BODY_DESC, MUNICIPAL_BODY_STATUS FROM IGRS_GOV_MUNICIPAL_BODY_MASTER WHERE MUNICIPAL_BODY_ID =?";

	public static final String SELECT_MUNICIPAL_BODY_MASTER_NAME= "SELECT MUNICIPAL_BODY_ID, MUNICIPAL_BODY_DESC, MUNICIPAL_BODY_STATUS FROM IGRS_GOV_MUNICIPAL_BODY_MASTER WHERE MUNICIPAL_BODY_NAME LIKE ?";

	public static final String UPDATE_MUNICIPAL_BODY_MASTER		= "UPDATE IGRS_GOV_MUNICIPAL_BODY_MASTER SET MUNICIPAL_BODY_NAME=?,MUNICIPAL_BODY_DESC=?, MUNICIPAL_BODY_STATUS=?, UPDATE_BY=?, UPDATE_DATE=sysdate WHERE MUNICIPAL_BODY_ID=?";
	
	public static final String DELETE_MUNICIPAL_BODY_MASTER		= "UPDATE IGRS_GOV_MUNICIPAL_BODY_MASTER SET MUNICIPAL_BODY_STATUS='R' WHERE MUNICIPAL_BODY_ID=?";
	
	public static final String INSERT_MUNICIPAL_BODY_MASTER 	= "INSERT INTO IGRS_GOV_MUNICIPAL_BODY_MASTER(MUNICIPAL_BODY_ID,MUNICIPAL_BODY_NAME,MUNICIPAL_BODY_DESC,CREATED_BY, CREATED_DATE, UPDATE_BY, UPDATE_DATE, MUNICIPAL_BODY_STATUS) VALUES('MUN'||IGRS_GOV_MUNICIPAL_BODY_SEQ.nextval,?,?,?,sysdate,?,sysdate,'A')";

}