/**
 * Copyright (c) 2009-10 WIPRO INFOTECH. All Rights Reserved.
 *
 *  This software is the confidential and proprietary information of WIPRO
 *  ("Confidential Information"). You shall not
 *  disclose such Confidential Information and shall use it only in
 *  accordance with the terms of the license agreement you entered into
 *  with WIPRO.
 *
 * WIPRO MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE
 * SUITABILITY OF THE SOFTWARE, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A
 * PARTICULAR PURPOSE, OR NON-INFRINGEMENT. WIPRO SHALL NOT BE
 * LIABLE FOR ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF
 * USING, MODIFYING OR DISTRIBUTING THIS SOFTWARE OR ITS
 * DERIVATIVES.
 *
 * Customer specific copyright notice - NA
 */
package com.wipro.igrs.adminConfig.sql;

/**
* 
* CommonSQL.java <br>
* CommonSQL <br>
* 
* @version 1.0
* 
* @author <b>WIPRO JAVA TEAM</b> <br>
*         Created on 11-Apr-2007 <br>
*         Last Modified on 28-Mar-2013
*/
public class CommonSQL {
	/** * queries related to admin configuration* */

	/* QUERY FOR RETRIEVING ModuleIDS,NAMES */
	public static final String ADMIN_MODULE_LIST = "SELECT MODULE_ID,MODULE_NAME FROM "
			+ "IGRS_MODULE_MASTER WHERE MODULE_STATUS='A'";
	/* QUERY FOR RETRIEVING SUBMODULEIDS,NAMES */
	public static final String ADMIN_SUBMODULE_LIST = "SELECT  SUB_MODULE_ID,SUB_MODULE_NAME FROM "
			+ "IGRS_SUB_MODULE_MASTER WHERE SUB_MODULE_STATUS='A' AND MODULE_ID=";
	/* QUERY FOR RETRIEVING FUNCTIONIDS AND NAMES */
	public static final String ADMIN_FUNCTION_LIST = "SELECT  FUNCTION_ID,FUNCTION_NAME  FROM "
			+ "IGRS_FUNCTION_MASTER WHERE FUNCTION_STATUS='A' AND SUB_MODULE_ID=";

	/*
	 * QUERY FOR RETRIEVING aTTRIBUTE LIST BASED ON
	 * MODULEID,SUBMODULEID,FUNCTIONID
	 */
	public static final String DISPLAY_ATTRIBUTE_LIST = "SELECT  ATTRIBUTE_NAME,ATTRIBUTE_VALUE,REMARKS FROM "
			+ "IGRS_CONFIG_PARAM_LIST WHERE MODULE_ID=? AND SUB_MODULE_ID=? "
			+ " AND FUNCTION_ID=? AND ATTRIBUTE_STATUS='A'";
	public static final String DISPLAY_ALL_ATTRIBUTE_LIST = "SELECT CL.ATTRIBUTE_ID, CL.ATTRIBUTE_NAME, CL.ATTRIBUTE_VALUE, " +
			"CL.REMARKS, CL.ATTRIBUTE_STATUS AS STATUSVAL, DECODE(CL.ATTRIBUTE_STATUS,'A', 'Activated', 'D', 'Deactivated') AS STATUSLABEL, " +
			"MM.MODULE_ID, FM.FUNCTION_ID, MM.MODULE_NAME, FM.FUNCTION_NAME, " +
			"DECODE(CL.UPDATE_DATE,NULL,'NA', TO_CHAR(CL.UPDATE_DATE, 'DD/MM/YYYY')) AS UPDATE_DATE " +
			"FROM IGRS_CONFIG_PARAM_LIST CL, IGRS_MODULE_MASTER MM, IGRS_FUNCTION_MASTER FM " +
			"WHERE CL.MODULE_ID = MM.MODULE_ID AND CL.FUNCTION_ID = FM.FUNCTION_ID AND ATTRIBUTE_STATUS IN ('A', 'D') ORDER BY MM.MODULE_NAME, FM.FUNCTION_NAME";
	/* qUERY FOR ADDING ATTRIBUTE VALUES INTO DB */
	public static final String ADDING_ATTRIBUTE_LIST = "INSERT INTO IGRS_CONFIG_PARAM_LIST(ATTRIBUTE_ID, ATTRIBUTE_NAME,"
			+ "ATTRIBUTE_VALUE,ATTRIBUTE_STATUS,MODULE_ID,SUB_MODULE_ID,FUNCTION_ID,"
			+ "CREATED_BY,CREATED_DATE,REMARKS) VALUES(LPAD(IGRS_CONFIGPARAM_ATTBUTE_SEQ.NEXTVAL,7,'ATT_'),"
			+ " ?,?,'A',?,?,?,?,TRUNC(SYSDATE),?)";

	/*
	 * QUERY FOR RETRIEVING ATTRIBUTE LIST BASED ON
	 * MODULEID,SUBMODULEID,FUNCTIONID
	 */
	public static final String GETTING_ATTRIBUTE_LIST = "SELECT  ATTRIBUTE_ID,ATTRIBUTE_NAME,ATTRIBUTE_VALUE,REMARKS FROM "
			+ "IGRS_CONFIG_PARAM_LIST WHERE MODULE_ID=? AND SUB_MODULE_ID=? "
			+ " AND FUNCTION_ID=? AND ATTRIBUTE_STATUS='A'";
	public static final String GET_ALL_ATTRIBUTE_LIST = "SELECT  ATTRIBUTE_ID,ATTRIBUTE_NAME,ATTRIBUTE_VALUE,REMARKS FROM "
			+ "IGRS_CONFIG_PARAM_LIST WHERE ATTRIBUTE_STATUS='A'";
	/* QUERY FOR RETRIEVING ATTRIBUTE LIST BASED ON ID */
	public static final String ATTRIBUTE_LIST_BY_ID = "SELECT CL.ATTRIBUTE_ID, CL.ATTRIBUTE_NAME, CL.ATTRIBUTE_VALUE, CL.REMARKS, " +
			"CL.ATTRIBUTE_STATUS AS STATUSVAL, " +
			"DECODE(CL.ATTRIBUTE_STATUS,'A', 'Activated', 'D', 'Deactivated') AS STATUSLABEL, " +
			"MM.MODULE_ID, FM.FUNCTION_ID, MM.MODULE_NAME, FM.FUNCTION_NAME, " +
			"DECODE(CL.UPDATE_DATE,NULL,'NA', TO_CHAR(CL.UPDATE_DATE, 'DD/MM/YYYY')) AS UPDATE_DATE " +
			"FROM IGRS_CONFIG_PARAM_LIST CL, IGRS_MODULE_MASTER MM, IGRS_FUNCTION_MASTER FM " +
			"WHERE CL.MODULE_ID = MM.MODULE_ID AND CL.FUNCTION_ID = FM.FUNCTION_ID AND CL.ATTRIBUTE_ID = ?";

	/* QUERY FOR UPDATING ATTRIBUTE LIST BASED ON ID */
	public static final String UPDATE_ATTRIBUTE_LIST = "UPDATE IGRS_CONFIG_PARAM_LIST SET ATTRIBUTE_NAME=?,"
			+ "ATTRIBUTE_VALUE=?, REMARKS=?, ATTRIBUTE_STATUS = ?, UPDATE_DATE = SYSDATE WHERE ATTRIBUTE_ID=?";

	/* QUERY FOR UPDATING ATTRIBUTE STATUS BASED ON ID */
	public static final String UPDATE_ATTRIBUTE_STATUS = "UPDATE IGRS_CONFIG_PARAM_LIST SET ATTRIBUTE_STATUS='D'"
			+ " WHERE ATTRIBUTE_ID=?";

	/* QUERIES RELATED TO DEEDPARAMAPPING */
	/* QUERY FOR GETTING DEEDLIST OF IDS AND NAMES */
	public static final String MASTER_DEED_LIST = "SELECT DEED_TYPE_ID,DEED_TYPE_NAME FROM "
			+ "IGRS_DEED_TYPE_MASTER WHERE DEED_STATUS='A'";
	/* QUERY FRO GETTING INSTRUMENTID AND NAMES */
	public static final String MASTER_INSTRUMENT_LIST = "SELECT INSTRUMENT_ID,INSTRUMENT_NAME FROM IGRS_DEED_INSTRUMENT_MASTER "
			+ "WHERE INSTRUMENT_STATUS='A' AND DEED_TYPE_ID=";
	/* QUERY FOR GETTING EXEMPTIONID AND NAMES BASED ON INSTRUMENT */
	public static final String MASTER_EXEMPTION_LIST = "SELECT EXEMPTION_ID,EXEMPTION_NAME FROM IGRS_DEED_EXEMPTION_MASTER "
			+ "WHERE EXEMPTION_STATUS='A' AND INSTRUMENT_ID=";
	/* QUERY FOR GETTING EXEMPTIONID AND NAMES BASED ON DEED */
	public static final String MASTER_EXEMPTION_LIST_DEED = "SELECT EXEMPTION_ID,EXEMPTION_NAME FROM IGRS_DEED_EXEMPTION_MASTER"
			+ " WHERE EXEMPTION_STATUS='A' AND DEED_TYPE_ID=";
	/* QUERY FOR GETTING PARAMID AND NAMES */
	public static final String MASTER_PARAM_LIST = "SELECT PARAM_ID,PARAM_NAME FROM IGRS_DEED_PARAM_MASTER"
			+ " WHERE PARAM_STATUS='A'";
	/* QUERY FOR GETTING OPERATORID AND NAMES */
	public static final String MASTER_OPERATOR_LIST = "SELECT OPERATOR_ID,OPERATOR_NAME FROM IGRS_OPERATOR_MASTER"
			+ " WHERE OPERATOR_STATUS='A'";
	/* QUERY FOR ADDING ATTRIBUTE VALUES INTO DB */
	public static final String MASTER_SAVE_DATA = "INSERT INTO IGRS_DEED_PARAM_MAPPING(DEED_TYPE_ID , INSTRUMENT_ID,"
			+ "EXEMPTION_ID,PARAM_ID,PARAM_VALUE,STATUS_FLAG,PRIORITY,PARENT_ID,"
			+ "OPERATOR_ID,FUNC_OPERATOR) VALUES(?,?,?,?,?,?,?,?,?,?)";

	/* QUERIES RELATED TO SUBCLAUSEAREAMAPPING */
	/* QUERY FOR GETTING DISTRICTLIST OF IDS AND NAMES */
	public static final String MASTER_DISTRICT_LIST = "SELECT DISTRICT_ID,DISTRICT_NAME FROM "
			+ "IGRS_DISTRICT_MASTER WHERE  DISTRICT_STATUS='A'";
	/* QUERY FOR GETTING TEHSILID AND NAMES */
	public static final String MASTER_TEHSIL_LIST = "SELECT TEHSIL_ID,TEHSIL_NAME  FROM IGRS_TEHSIL_MASTER "
			+ "WHERE TEHSIL_STATUS='A' AND DISTRICT_ID=";
	/* QUERY FOR GETTING PATWARIID AND NAMES */
	public static final String MASTER_WARD_PATWARI_LIST = "SELECT WARD_PATWARI_ID,WARD_PATWARI_NAME FROM IGRS_WARD_PATWARI_MASTER "
			+ "WHERE WARD_PATWARI_STATUS='A' AND TEHSIL_ID=";

	/* QUERY FOR GETTING VILLAGEID AND NAMES */
	public static final String MASTER_MOHALLA_VILLAGE_LIST = "SELECT MOHALLA_VILLAGE_ID, MOHALLA_VILLAGE_NAME FROM IGRS_MOHALLA_VILLAGE_MASTER "
			+ "WHERE MOHALLA_VILLAGE_STATUS='A' AND WARD_PATWARI_ID=";
	/* QUERY FOR GETTING PROPERTYLIST OF IDS AND NAMES */
	public static final String MASTER_PROPERTY_TYPE_LIST = "SELECT PROPERTY_TYPE_ID,PROPERTY_TYPE_NAME FROM "
			+ "IGRS_PROPERTY_TYPE_MASTER WHERE  PROPERTY_TYPE_STATUS='A'";
	/* QUERY FOR GETTING PROPERTYTYPEL1ID AND NAMES */
	public static final String MASTER_PROPERTY_TYPEL1_LIST = "SELECT PROPERTY_TYPE_L1_ID,PROPERTY_TYPE_L1_NAME FROM "
			+ "IGRS_PROP_TYPE_L1_MASTER WHERE PROPERTY_TYPE_L1_STATUS='A'"
			+ "  AND PROPERTY_TYPE_ID =";
	/* QUERY FOR GETTING PROPERTYTYPEL2ID AND NAMES */
	public static final String MASTER_PROPERTY_TYPEL2_LIST = "SELECT PROPERTY_TYPE_L2_ID,PROPERTY_TYPE_L2_NAME  FROM "
			+ "IGRS_PROP_TYPE_L2_MASTER WHERE PROPERTY_TYPE_L2_STATUS='A'"
			+ "  AND PROPERTY_TYPE_L1_ID =";

	/* QUERY FOR GETTING SUBCLAUSELIST OF IDS AND NAMES */
	public static final String MASTER_SUBCLAUSE_LIST = "SELECT  SUB_CLAUSE_ID ,SUB_CLAUSE_NAME FROM "
			+ "IGRS_SUB_CLAUSE_MASTER WHERE  SUB_CLAUSE_STATUS ='A'";
	/* QUERY FOR SAVING DATA INTO SUBCLAUSE AREA MAPPING TABLE */
	public static final String SUBCLAUSE_AREA_MAP_SAVE = "INSERT INTO IGRS_SUB_CLAUSE_AREA_MAPPING(DISTRICT_ID ,TEHSIL_ID ,"
			+ "WARD_PATWARI_ID,MOHALLA_VILLAGE_ID ,PROPERTY_TYPE_ID,PROPERTY_TYPE_L1_ID,"
			+ "PROPERTY_TYPE_L2_ID,SUB_CLAUSE_ID,SUB_CLAUSE_VALUE,"
			+ "OPERATOR_ID, FN_OPERATOR_ID) VALUES(?,?,?,?,?,?,?,?,?,?,?)";

	/* QUERIES RELATED TO MohallaMasterScreen */
	/* QUERY FOR GETTING Patwari list OF IDS AND NAMES */
	public static final String MASTER_WARD_PATWARI_IDLIST = "SELECT WARD_PATWARI_ID,WARD_PATWARI_NAME FROM IGRS_WARD_PATWARI_MASTER "
			+ "WHERE WARD_PATWARI_STATUS='A'";
	/* QUERY FOR INSERTING MOHALLAMASTER SCREEN */
	public static final String MOHALLA_MASTER_SAVE_DATA = "INSERT INTO IGRS_MOHALLA_VILLAGE_MASTER(MOHALLA_VILLAGE_ID,"
			+ "MOHALLA_VILLAGE_NAME,MOHALLA_VILLAGE_DESC,MOHALLA_VILLAGE_STATUS,"
			+ "WARD_PATWARI_ID,CREATED_BY, CREATED_DATE ,MOHALLA_OR_VILLAGE) "
			+ "VALUES(IGRSUSER.IGRS_MOH_VIL_MAST_SEQ.nextval,?,?,?,?,?,TRUNC(SYSDATE),?)";
	/* QUERY FOR UPDATING MOHALLAMASTER SCREEN */
	public static final String MOHALLA_MASTER_UPDATE_DATA = "UPDATE IGRS_MOHALLA_VILLAGE_MASTER SET MOHALLA_VILLAGE_NAME=?,"
			+ "MOHALLA_VILLAGE_DESC=?,MOHALLA_VILLAGE_STATUS=?, "
			+ "UPDATE_BY =? ,UPDATE_DATE =TRUNC(SYSDATE) WHERE MOHALLA_VILLAGE_ID=? ";
	/* QUERY FOR GETTING MOHALLAMASTER DATA */
	public static final String MASTER_MOHALLA_VILLAGE_DATA = "SELECT MOHALLA_VILLAGE_ID , MOHALLA_VILLAGE_NAME,"
			+ " MOHALLA_VILLAGE_DESC,MOHALLA_VILLAGE_STATUS,"
			+ "MOHALLA_OR_VILLAGE  FROM IGRS_MOHALLA_VILLAGE_MASTER";
	/* QUERY FOR GETTING MOHALLAMASTER DATA based on villageid */
	public static final String MASTER_MOHALLA_VILLAGE_ID_DATA = "SELECT  MOHALLA_VILLAGE_ID,MOHALLA_VILLAGE_NAME,"
			+ " MOHALLA_VILLAGE_DESC,MOHALLA_VILLAGE_STATUS"
			+ " FROM IGRS_MOHALLA_VILLAGE_MASTER"
			+ " WHERE MOHALLA_VILLAGE_ID=?";

	/* QUERIES RELATED TO PartyTypeMasterScreen */
	/* QUERY FOR INSERTING PartyTypeMASTER SCREEN */
	public static final String PARTY_TYPE_MASTER_SAVE_DATA = "INSERT INTO IGRS_PARTY_TYPE_MASTER(PARTY_TYPE_ID ,"
			+ "PARTY_TYPE_NAME,PARTY_TYPE_DESC,PARTY_TYPE_STATUS,"
			+ "CREATED_BY,CREATED_DATE) VALUES(IGRS_PARTY_TYPE_SEQ.nextval,?,?,?,?,TRUNC(SYSDATE))";
	/* QUERY FOR UPDATING PARTYTYPEMASTER SCREEN */
	public static final String PARTY_TYPE_MASTER_UPDATE_DATA = "UPDATE IGRS_PARTY_TYPE_MASTER SET  PARTY_TYPE_NAME=?,"
			+ "PARTY_TYPE_DESC=?,PARTY_TYPE_STATUS=?,"
			+ "UPDATE_BY =? ,UPDATE_DATE =TRUNC(SYSDATE) WHERE"
			+ " PARTY_TYPE_ID =?";
	/* QUERY FOR GETTING PARTYMASTER DATA */
	public static final String MASTER_PARTY_TYPE_DATA = "SELECT PARTY_TYPE_ID  , PARTY_TYPE_NAME,"
			+ " PARTY_TYPE_DESC ,PARTY_TYPE_STATUS"
			+ "  FROM IGRS_PARTY_TYPE_MASTER";
	/* QUERY FOR GETTING PARTYMASTER DATA based on PARTYid */
	public static final String MASTER_PARTY_TYPE_ID_DATA = "SELECT PARTY_TYPE_ID ,PARTY_TYPE_NAME,"
			+ " PARTY_TYPE_DESC,PARTY_TYPE_STATUS"
			+ "  FROM IGRS_PARTY_TYPE_MASTER" + "  WHERE PARTY_TYPE_ID=?";

	/* QUERIES RELATED TO ServiceMasterScreen */
	/* QUERY FOR INSERTING ServiceMASTER SCREEN */
	public static final String SERVICE_MASTER_SAVE_DATA = "INSERT INTO IGRS_SERVICE_MASTER(SERVICE_ID  ,"
			+ "SERVICE_NAME,SERVICE_DESC,SERVICE_STATUS ,"
			+ "CREATED_BY,CREATED_DATE) VALUES(IGRS_SERVICE_MASTER_SEQ.nextval,?,?,?,?,TRUNC(SYSDATE))";
	/* QUERY FOR UPDATING PARTYTYPEMASTER SCREEN */
	public static final String SERVICE_MASTER_UPDATE_DATA = "UPDATE IGRS_SERVICE_MASTER SET  SERVICE_NAME=?,"
			+ "SERVICE_DESC=?,SERVICE_STATUS =?,"
			+ "UPDATE_BY   =? ,UPDATE_DATE =TRUNC(SYSDATE) WHERE"
			+ " SERVICE_ID =?";
	/* QUERY FOR GETTING PARTYMASTER DATA */
	public static final String MASTER_SERVICE_DATA = "SELECT SERVICE_ID   , SERVICE_NAME,"
			+ " SERVICE_DESC ,SERVICE_STATUS " + "  FROM IGRS_SERVICE_MASTER";
	/* QUERY FOR GETTING PARTYMASTER DATA based on PARTYid */
	public static final String MASTER_SERVICE_ID_DATA = "SELECT SERVICE_ID  ,SERVICE_NAME,"
			+ " SERVICE_DESC,SERVICE_STATUS "
			+ "  FROM IGRS_SERVICE_MASTER"
			+ "  WHERE SERVICE_ID =?";

	/* QUERIES RELATED TO DocumentTypeMasterScreen */
	/* QUERY FOR INSERTING DocumentTypeMASTER SCREEN */
	public static final String DOCUMENT_TYPE_MASTER_SAVE_DATA = "INSERT INTO IGRS_DOCUMENT_TYPE_MASTER(DOCUMENT_TYPE_ID ,"
			+ " DOCUMENT_NAME ,DOCUMENT_DESCRIPTION,DOCUMENT_STATUS,"
			+ "CREATED_BY,CREATED_DATE) VALUES(IGRS_DOCUMENT_TYPE_SEQ.nextval,?,?,?,?,TRUNC(SYSDATE))";
	/* QUERY FOR UPDATING dOCUMENTTYPEMASTER SCREEN */
	public static final String DOCUMENT_TYPE_MASTER_UPDATE_DATA = "UPDATE IGRS_DOCUMENT_TYPE_MASTER SET   DOCUMENT_NAME =?,"
			+ "DOCUMENT_DESCRIPTION=?,DOCUMENT_STATUS=?,"
			+ " UPDATE_BY=? ,UPDATE_DATE =TRUNC(SYSDATE) WHERE"
			+ " DOCUMENT_TYPE_ID =?";
	/* QUERY FOR GETTING DocumentMASTER DATA */
	public static final String MASTER_DOCUMENT_TYPE_DATA = "SELECT DOCUMENT_TYPE_ID  ,  DOCUMENT_NAME ,"
			+ " DOCUMENT_DESCRIPTION ,DOCUMENT_STATUS"
			+ "  FROM IGRS_DOCUMENT_TYPE_MASTER";
	/* QUERY FOR GETTING DocumentMASTER DATA based on Documentid */
	public static final String MASTER_DOCUMENT_TYPE_ID_DATA = "SELECT DOCUMENT_TYPE_ID , DOCUMENT_NAME ,"
			+ " DOCUMENT_DESCRIPTION,DOCUMENT_STATUS"
			+ "  FROM IGRS_DOCUMENT_TYPE_MASTER" + "  WHERE DOCUMENT_TYPE_ID=?";

	/* QUERIES RELATED TO PhotoId proof MasterScreen */
	/* QUERY FOR INSERTING PhotoIdProof MASTER SCREEN */
	public static final String PHOTOID_MASTER_SAVE_DATA = "INSERT INTO IGRS_PHOTOID_PROOF_TYPE_MASTER( PHOTO_PROOF_TYPE_ID  ,"
			+ " PHOTO_PROOF_TYPE_NAME ,PHOTO_PROOF_TYPE_STATUS,"
			+ "CREATED_BY ,CREATED_DATE) VALUES(IGRS_PHOTOID_PROOF_MASTER_SEQ.nextval,?,?,?,TRUNC(SYSDATE))";
	/* QUERY FOR UPDATING RELIGION MASTER SCREEN */
	public static final String PHOTOID_MASTER_UPDATE_DATA = "UPDATE IGRS_PHOTOID_PROOF_TYPE_MASTER SET  PHOTO_PROOF_TYPE_NAME=?,"
			+ "PHOTO_PROOF_TYPE_STATUS=?,"
			+ " UPDATE_BY=? ,UPDATE_DATE = TRUNC(SYSDATE) WHERE"
			+ "  PHOTO_PROOF_TYPE_ID=?";
	/* QUERY FOR GETTING RELIGION MASTER DATA */
	public static final String MASTER_PHOTOID_DATA = "SELECT  PHOTO_PROOF_TYPE_ID  ,PHOTO_PROOF_TYPE_NAME ,"
			+ " PHOTO_PROOF_TYPE_STATUS"
			+ "  FROM IGRS_PHOTOID_PROOF_TYPE_MASTER";
	/* QUERY FOR GETTING RELIGIONMASTER DATA based on RELIGIONid */
	public static final String MASTER_PHOTOID_ID_DATA = "SELECT  PHOTO_PROOF_TYPE_ID , PHOTO_PROOF_TYPE_NAME ,"
			+ " PHOTO_PROOF_TYPE_STATUS"
			+ "  FROM IGRS_PHOTOID_PROOF_TYPE_MASTER"
			+ "  WHERE PHOTO_PROOF_TYPE_ID=?";

	/* QUERIES RELATED TO PersonCategory MasterScreen */
	/* QUERY FOR INSERTING PersonCategory MASTER SCREEN */
	public static final String CATEGORY_MASTER_SAVE_DATA = "INSERT INTO IGRS_PERSON_CATEGORY_MASTER( CATEGORY_ID ,"
			+ " CATEGORY_NAME ,CATEGORY_STATUS,"
			+ "CREATED_BY ,CREATED_DATE) VALUES(IGRS_PERSONCATEGORY_MASTER_SEQ.nextval,?,?,?,TRUNC(SYSDATE))";
	/* QUERY FOR UPDATING RELIGION MASTER SCREEN */
	public static final String CATEGORY_MASTER_UPDATE_DATA = "UPDATE IGRS_PERSON_CATEGORY_MASTER SET   CATEGORY_NAME   =?,"
			+ "CATEGORY_STATUS=?,"
			+ " UPDATED_BY=? ,UPDATED_DATE = TRUNC(SYSDATE) WHERE"
			+ "  CATEGORY_ID =?";
	/* QUERY FOR GETTING RELIGION MASTER DATA */
	public static final String MASTER_CATEGORY_DATA = "SELECT  CATEGORY_ID ,CATEGORY_NAME,"
			+ " CATEGORY_STATUS" + "  FROM IGRS_PERSON_CATEGORY_MASTER";
	/* QUERY FOR GETTING RELIGIONMASTER DATA based on RELIGIONid */
	public static final String MASTER_CATEGORY_ID_DATA = "SELECT  CATEGORY_ID, CATEGORY_NAME,"
			+ " CATEGORY_STATUS"
			+ "  FROM IGRS_PERSON_CATEGORY_MASTER"
			+ "  WHERE CATEGORY_ID=?";

	/* QUERIES RELATED TO ReligionMasterScreen */
	/* QUERY FOR INSERTING ReligionMASTER SCREEN */
	public static final String RELIGION_MASTER_SAVE_DATA = "INSERT INTO IGRS_RELIGION_MASTER( RELIGION_ID ,"
			+ " RELIGION_NAME   ,RELIGION_DESCRIPTION,RELIGION_STATUS,"
			+ "CREATED_BY,CREATED_DATE) VALUES(IGRS_RELIGION_MASTER_SEQ.nextval,?,?,?,?,TRUNC(SYSDATE))";
	/* QUERY FOR UPDATING RELIGION MASTER SCREEN */
	public static final String RELIGION_MASTER_UPDATE_DATA = "UPDATE IGRS_RELIGION_MASTER SET   RELIGION_NAME   =?,"
			+ "RELIGION_DESCRIPTION=?,RELIGION_STATUS=?,"
			+ " UPDATE_BY=? , UPDATE_DATE = TRUNC(SYSDATE) WHERE"
			+ "  RELIGION_ID =?";
	/* QUERY FOR GETTING RELIGION MASTER DATA */
	public static final String MASTER_RELIGION_DATA = "SELECT  RELIGION_ID ,  RELIGION_NAME,"
			+ " RELIGION_DESCRIPTION ,RELIGION_STATUS"
			+ "  FROM IGRS_RELIGION_MASTER";
	/* QUERY FOR GETTING RELIGIONMASTER DATA based on RELIGIONid */
	public static final String MASTER_RELIGION_ID_DATA = "SELECT  RELIGION_ID, RELIGION_NAME,"
			+ " RELIGION_DESCRIPTION,RELIGION_STATUS"
			+ "  FROM IGRS_RELIGION_MASTER" + "  WHERE RELIGION_ID=?";

	/* QUERIES RELATED TO CasteMasterScreen */
	/* QUERY FOR INSERTING CasteMASTER SCREEN */
	public static final String CASTE_MASTER_SAVE_DATA = "INSERT INTO IGRS_CASTE_MASTER(CASTE_ID ,"
			+ " CASTE_NAME ,CATEGORY_ID,CASTE_STATUS,"
			+ "CREATED_BY,CREATED_DATE) VALUES(IGRS_CASTE_MASTER_SEQ.nextval,?,?,?,?,TRUNC(SYSDATE))";
	/* QUERY FOR UPDATING Caste MASTER SCREEN */
	public static final String CASTE_MASTER_UPDATE_DATA = "UPDATE IGRS_CASTE_MASTER SET   CASTE_NAME =?,"
			+ "CATEGORY_ID=?,CASTE_STATUS=?,"
			+ " UPDATED_BY=? ,UPDATED_DATE = TRUNC(SYSDATE) WHERE"
			+ "  CASTE_ID=?";
	/* QUERY FOR GETTING Caste MASTER DATA */
	public static final String MASTER_CASTE_DATA = "SELECT  CASTE_ID ,CASTE_NAME ,"
			+ " CATEGORY_ID ,CASTE_STATUS" + "  FROM IGRS_CASTE_MASTER";
	/* QUERY FOR GETTING CasteMASTER DATA based on Casteid */
	public static final String MASTER_CASTE_ID_DATA = "SELECT CASTE_ID, CASTE_NAME ,"
			+ " CATEGORY_ID,CASTE_STATUS"
			+ "  FROM IGRS_CASTE_MASTER"
			+ "  WHERE  CASTE_ID=?";
	/* QUERY FOR GETTING cATEGORY list OF IDS AND NAMES */
	public static final String MASTER_CATEGORY_IDLIST = "SELECT CATEGORY_ID ,CATEGORY_NAME FROM "
			+ " IGRS_PERSON_CATEGORY_MASTER " + " WHERE CATEGORY_STATUS='A'";

	/* QUERIES RELATED TO ServiceMappingScreen */
	/* QUERY FOR GETTING FUNCTION ID AND NAME LIST */
	public static final String GET_FUNCTION_ID_MAP = "SELECT FUNCTION_ID,FUNCTION_NAME"
			+ " FROM IGRS_FUNCTION_MASTER WHERE FUNCTION_STATUS='A'";
	/* QUERY FOR GETTING SERVICE ID AND NAME LIST */
	public static final String GET_SERVICE_ID_MAP = "SELECT SERVICE_ID,SERVICE_NAME "
			+ " FROM IGRS_SERVICE_MASTER WHERE SERVICE_STATUS='A'";
	/* QUERY FOR GETTING PARAMETERID AND NAME LIST */
	public static final String GET_SERVICEPARAM_ID_MAP = "SELECT PARAM_ID,PARAM_NAME "
			+ " FROM IGRS_SERVICE_FEE_PARAM_MASTER WHERE PARAM_STATUS='A'";
	/* QUERY FOR GETTING OPERATORID AND NAME LIST */
	public static final String GET_OPERATOR_ID_MAP = "SELECT OPERATOR_ID,OPERATOR_NAME "
			+ " FROM IGRS_OPERATOR_MASTER WHERE OPERATOR_STATUS='A'";
	/* QUERY FOR inserting ServiceFunction mapping screen */
	public static final String SERVICE_FUNC_MAP_ADDING = "INSERT INTO IGRS_SERVICE_FUNCTION_MAP(FUNCTION_ID,SERVICE_ID)"
			+ "  VALUES(?,?)";
	/* QUERY FOR inserting ServicePARAM mapping screen */
	public static final String SERVICE_PARAM_MAP_ADDING = "INSERT INTO IGRS_SERVICE_FEE_PARAM_MAPPING(FUNCTION_ID,"
			+ "PARAM_ID,PARAM_VALUE,PARAM_TYPE,PARENT_ID,"
			+ "OPERATOR_ID,PRIORITY,FUNC_OPERATOR_ID,SERVICE_ID )"
			+ "  VALUES(?,?,?,?,?,?,?,?,?)";
	public static final String DELETE_SERVICE_MASTER = "DELETE FROM IGRS_SERVICE_MASTER WHERE SERVICE_ID=?";
	
	public static final String GET_ONE_ROLE_ID_FOR_USER_ID = "SELECT RRG.ROLE_ID FROM IGRS_USER_ROLE_GROUP_MAPPING URG, IGRS_RGROUP_ROLE_MAPPING RRG WHERE URG.ROLE_GROUP_ID = RRG.ROLE_GROUP_ID AND URG.USER_ID = ? AND ROWNUM < 2";
	
	public static final String GET_MODULE_LISTING = "SELECT MODULE_ID, MODULE_NAME FROM IGRS_MODULE_MASTER where UPPER(MODULE_STATUS) = 'A'";
	
	public static final String GET_FUNCTION_LISTING_BY_MODULE = "SELECT FUNCTION_ID, FUNCTION_NAME FROM " +
			"IGRS_FUNCTION_MASTER WHERE UPPER(FUNCTION_STATUS) = 'A' AND " +
			"SUB_MODULE_ID IN ( SELECT SUB_MODULE_ID FROM IGRS_SUB_MODULE_MASTER WHERE MODULE_ID = ? ) ";
	public static final String GET_SUBMODULE_ID_BYFUNCTION = "SELECT SUB_MODULE_ID FROM IGRS_FUNCTION_MASTER WHERE FUNCTION_ID = ?";
	public static final String GET_UNIQUE_ATTRIB_NAME_CHECK = "SELECT COUNT(*) FROM IGRS_CONFIG_PARAM_LIST WHERE MODULE_ID = ? AND ATTRIBUTE_NAME = ?";
	
}
