package com.wipro.igrs.generatecertificate.sql;
/* Copyright (c) 2006-2008 WIPRO. All Rights Reserved.
 * 
 *  This software is the confidential and proprietary information of WIPRO
 *  ("Confidential Information"). You shall not
 *  disclose such Confidential Information and shall use it only in
 *  accordance with the terms of the license agreement you entered into
 *  with WIPRO.
 *  
 * WIPRO MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE 
 * SUITABILITY OF THE SOFTWARE, EITHER EXPRESS OR IMPLIED, 
 * INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF 
 * MERCHANTABILITY, FITNESS FOR A
 * PARTICULAR PURPOSE, OR NON-INFRINGEMENT. WIPRO SHALL NOT BE 
 * LIABLE FOR ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF 
 * USING, MODIFYING OR DISTRIBUTING THIS SOFTWARE OR ITS 
 * DERIVATIVES.
 * 
 */


/**
 * @author Madan Mohan
 *
 */
public class CommonSQL {

	 
	public static final String PROBATION_CONTENT_QUERY = 
		"SELECT TEMPLATE_HEADER,TEMPLATE_FOOTER,TEMPLATE_CONTENT "
		+"FROM IGRS_TEMPLATE_DICTIONARY WHERE TEMPLATE_NAME=? AND "
		+"TEMPLATE_STATUS='A'";

	
	public static final String EMP_DETAILS =
		"SELECT FIRST_NAME||MIDDLE_NAME||LAST_NAME,"
		+"TO_CHAR(SYSDATE,'DD/MM/YYYY') FROM "
		+"IGRS_EMP_MASTER, IGRS_EMP_OFFICIAL_DETAILS "
		+"WHERE IGRS_EMP_MASTER.EMP_ID=? AND (IGRS_EMP_MASTER.EMP_ID = "
		+"IGRS_EMP_OFFICIAL_DETAILS.EMP_ID) AND "
		+"(IGRS_EMP_OFFICIAL_DETAILS.EMP_STATUS = 'A') ";
	
	public static final String EMP_CONFIRM_DETAILS = 
		"SELECT IGRS_EMP_MASTER.FIRST_NAME||IGRS_EMP_MASTER.MIDDLE_NAME||"
		+"IGRS_EMP_MASTER.LAST_NAME,IGRS_EMP_MASTER.EMP_ID, "
		+"TO_CHAR(SYSDATE,'DD/MM/YYYY') FROM IGRS_EMP_MASTER, "
		+"IGRS_EMP_OFFICIAL_DETAILS WHERE "
		+"((IGRS_EMP_MASTER.EMP_ID = IGRS_EMP_OFFICIAL_DETAILS.EMP_ID) "
		+"AND (IGRS_EMP_OFFICIAL_DETAILS.EMP_OFFICIAL_STATUS = 'P') "
		+"OR (IGRS_EMP_OFFICIAL_DETAILS.EMP_STATUS = 'A')) ";
	
	public static final String EMP_CHECK = 
		"SELECT COUNT(*) FROM IGRS_EMP_MASTER," 
		+"IGRS_EMP_OFFICIAL_DETAILS WHERE "
		+"((IGRS_EMP_MASTER.EMP_ID = IGRS_EMP_OFFICIAL_DETAILS.EMP_ID) "
		+"AND (IGRS_EMP_OFFICIAL_DETAILS.EMP_STATUS = 'A'))  ";
		
}

