package com.wipro.igrs.empsalcomp.sql;

public class EmpSalarycreateCommonSQL {
	
//constants
	
	//public static final String GET_EMPL_DATA ="select FIRST_NAME,MIDDLE_NAME,LAST_NAME,EMP_ID from IGRS_EMP_MASTER where EMP_ID=?";
	public static final String IS_EMP_HAS_BASIC ="select * from IGRS_EMP_SALARY_BASIC_DTLS where EMP_ID=?";
	public static final String ADD_NEW_EMP_SALARY_BASIC="insert into IGRS_EMP_SALARY_BASIC_DTLS(EMP_ID,COMPONENT_VALUE,EFFECTIVE_DATE,INCREMENT_AMOUNT,EFFECTIVE_FLAG,SLAB_ID,NO_INCREMENTS) values(?,?,TO_DATE(?,'DD/MM/YYYY'),?,?,?,?)";
	public static final String UPDATE_BASIC_VALUE="UPDATE IGRS_EMP_SALARY_BASIC_DTLS SET COMPONENT_VALUE=?," +
													"EFFECTIVE_DATE=?,EFFECTIVE_FLAG=?,INCREMENT_AMOUNT=?," +
													"UPDATE_BY=?,UPDATE_DATE=sysdate,SLAB_ID=?,NO_INCREMENTS=? WHERE EMP_ID=?";
	
	public static final String CHECK_EMP = 
		"SELECT  COUNT(*) FROM IGRS_EMP_GRADE_MASTER, "
		+"IGRS_EMP_GRADE_CADRE_MAPPING, "
	    +"IGRS_EMP_MASTER,IGRS_EMP_SALARY_BASIC_DTLS "
	    +"WHERE ((IGRS_EMP_GRADE_MASTER.GRADE_ID = "
	    +"IGRS_EMP_GRADE_CADRE_MAPPING.GRADE_ID) AND "
	    +"(IGRS_EMP_MASTER.EMP_ID = IGRS_EMP_GRADE_CADRE_MAPPING.EMP_ID) "
	    +"AND (IGRS_EMP_MASTER.EMP_ID = IGRS_EMP_SALARY_BASIC_DTLS.EMP_ID(+)) "
	    +"AND ((IGRS_EMP_GRADE_CADRE_MAPPING.STATUS = 'A')) AND "
	    +"((IGRS_EMP_GRADE_MASTER.GRADE_STATUS = 'A')) AND "
	    +"((UPPER(IGRS_EMP_MASTER.EMP_ID) = UPPER(?)))) ";
	
	/*
	public static final String GET_EMPL_DATA = 
		"SELECT IGRS_EMP_MASTER.FIRST_NAME, IGRS_EMP_MASTER.MIDDLE_NAME,"
	    +"IGRS_EMP_MASTER.LAST_NAME, IGRS_EMP_MASTER.EMP_ID, "
	    +"IGRS_EMP_GRADE_MASTER.MIN_SALARY_SLAB, "
	    +"IGRS_EMP_GRADE_MASTER.MAX_SALARY_SLAB, "
	    +"IGRS_EMP_GRADE_MASTER.INCREMENT_AMOUNT, "
	    +"IGRS_EMP_SALARY_BASIC_DTLS.COMPONENT_VALUE, " 
	    +"TO_CHAR(IGRS_EMP_SALARY_BASIC_DTLS.EFFECTIVE_DATE,'MM/DD/YYYY')," 
	    +"IGRS_EMP_SALARY_BASIC_DTLS.SLAB_ID, IGRS_EMP_SALARY_BASIC_DTLS.EFFECTIVE_FLAG,"
	    +"IGRS_EMP_SALARY_BASIC_DTLS.NO_INCREMENTS "
	    +"FROM IGRS_EMP_GRADE_MASTER, IGRS_EMP_GRADE_CADRE_MAPPING, "
	    +"IGRS_EMP_MASTER,IGRS_EMP_SALARY_BASIC_DTLS "
	    +"WHERE ((IGRS_EMP_GRADE_MASTER.GRADE_ID = "
	    +"IGRS_EMP_GRADE_CADRE_MAPPING.GRADE_ID) AND "
	    +"(IGRS_EMP_MASTER.EMP_ID = IGRS_EMP_GRADE_CADRE_MAPPING.EMP_ID) "
	    +"AND (IGRS_EMP_MASTER.EMP_ID = IGRS_EMP_SALARY_BASIC_DTLS.EMP_ID) "
	    +"AND ((IGRS_EMP_GRADE_CADRE_MAPPING.STATUS = 'A')) AND "
	    +"((IGRS_EMP_GRADE_MASTER.GRADE_STATUS = 'A')) AND "
	    +"((UPPER(IGRS_EMP_MASTER.EMP_ID) = UPPER(?)))) ";
	*/
	public static final String GET_EMPL_DATA = 
	"SELECT IGRS_EMP_MASTER.FIRST_NAME, IGRS_EMP_MASTER.MIDDLE_NAME, "
		+"IGRS_EMP_MASTER.LAST_NAME, IGRS_EMP_MASTER.EMP_ID,  " 
		+"IGRS_EMP_GRADE_MASTER.MIN_SALARY_SLAB,  "
		+"IGRS_EMP_GRADE_MASTER.MAX_SALARY_SLAB,  "
		+"IGRS_EMP_GRADE_MASTER.INCREMENT_AMOUNT, " 
		+"DECODE(IGRS_EMP_SALARY_BASIC_DTLS.COMPONENT_VALUE,NULL,0,IGRS_EMP_SALARY_BASIC_DTLS.COMPONENT_VALUE) AS COMPONENT_VALUE ,  "
		+"DECODE(TO_CHAR(IGRS_EMP_SALARY_BASIC_DTLS.EFFECTIVE_DATE,'MM/DD/YYYY'),NULL,'', TO_CHAR(IGRS_EMP_SALARY_BASIC_DTLS.EFFECTIVE_DATE,'MM/DD/YYYY')) AS EFFECTIVE_DATE, " 
		+"DECODE(IGRS_EMP_SALARY_BASIC_DTLS.SLAB_ID,NULL,'',IGRS_EMP_SALARY_BASIC_DTLS.SLAB_ID) AS SLAB_ID, "
		+"DECODE(IGRS_EMP_SALARY_BASIC_DTLS.EFFECTIVE_FLAG,NULL,'',IGRS_EMP_SALARY_BASIC_DTLS.EFFECTIVE_FLAG) AS EFFECTIVE_FLAG, "
		+"DECODE(IGRS_EMP_SALARY_BASIC_DTLS.NO_INCREMENTS,NULL,'',IGRS_EMP_SALARY_BASIC_DTLS.NO_INCREMENTS) AS NO_INCREMENTS  "
		+"FROM IGRS_EMP_GRADE_MASTER, IGRS_EMP_GRADE_CADRE_MAPPING,  "
		+"IGRS_EMP_MASTER,IGRS_EMP_SALARY_BASIC_DTLS  "
		+"WHERE ((IGRS_EMP_GRADE_MASTER.GRADE_ID =  "
		+"IGRS_EMP_GRADE_CADRE_MAPPING.GRADE_ID) AND  "
		+"(IGRS_EMP_MASTER.EMP_ID = IGRS_EMP_GRADE_CADRE_MAPPING.EMP_ID)  "
		+"AND (IGRS_EMP_MASTER.EMP_ID = IGRS_EMP_SALARY_BASIC_DTLS.EMP_ID(+))  "
		+"AND ((IGRS_EMP_GRADE_CADRE_MAPPING.STATUS = 'A')) AND  "
		+"((IGRS_EMP_GRADE_MASTER.GRADE_STATUS = 'A')) AND  "
		+"((UPPER(IGRS_EMP_MASTER.EMP_ID) = UPPER(?))))  ";
	
	public static final String GET_ALL_SLABS="SELECT A.SLAB_ID, A.SLAB_MIN, " +
			"A.SLAB_INCREMENT,A.SLAB_MAX FROM IGRS_EMP_BASIC_SLAB_MASTER A, " +
			"IGRS_EMP_GRADE_BASIC_MAP B, IGRS_EMP_OFFICIAL_DETAILS C WHERE " +
			"A.SLAB_ID=B.BASIC_SLAB_ID AND B.SLAB_MAP_STATUS='A' AND	" +
			"B.GRADE_ID=C.EMP_CLASS_ID AND C.EMP_ID=?  ";
	
}
