package com.wipro.igrs.payment.sql;

/**
 * ===========================================================================
 * File : CommonSQL.java Description : Represents the SQL Class
 * 
 * Author : vengamamba.p * Created Date : Dec 16, 2007
 * 
 * ===========================================================================
 */
public class CommonSQL {
	/*** queries related to cash counter **/
	public static final String MINOR_HEAD_QUERY_NEW = "Select REVENUE_MINOR_HEAD, REVENUE_MINOR_HEAD_NAME from IGRS_REVENUE_MINOR_HEAD_MASTER " + "WHERE REVENUE_MINOR_HEAD_STATUS='A'";
	public static final String SUB_MAJOR_HEAD_QUERY_NEW = "Select REVENUE_SUB_MAJOR_HEAD, REVENUE_SUB_MAJOR_HEAD_NAME from IGRS_REVENUE_SBMJRHD_MASTER " + "WHERE REVENUE_SUB_MAJOR_HEAD_STATUS='A'";
	public static final String MAJOR_HEAD_QUERY = "Select REVENUE_MAJOR_HEAD, REVENUE_MAJOR_HEAD_NAME from IGRS_REVENUE_MAJOR_HEAD_MASTER " + "WHERE REVENUE_MAJOR_HEAD_STATUS='A'";

	/* QUERY FOR RETRIEVING PHOTOPROFFIDS */
	public static final String CASH_PHOTOID_LIST = "SELECT PHOTO_PROOF_TYPE_ID,PHOTO_PROOF_TYPE_NAME FROM " + "IGRS_PHOTOID_PROOF_TYPE_MASTER WHERE PHOTO_PROOF_TYPE_STATUS = 'A'";
	/* QUERY FOR RETRIEVING SERVICEIDS */
	public static final String CASH_FUNCTIONID_LIST = "SELECT FUNCTION_ID,FUNCTION_NAME FROM " + "IGRS_FUNCTION_MASTER WHERE PAYMENT_FLAG='Y' ORDER BY FUNCTION_NAME ";
	/* QUERY FOR RETRIEVING TRANSACTION DETAILS */
	public static final String PRINT_TRANS_DETAILS = "select P.FIRST_NAME||' '||P.MIDDLE_NAME||' '||P.LAST_NAME,  P.TRANSACTION_ID, P.GROSS_AMOUNT," + " to_char(to_date(P.CREATED_DATE,'DD/MM/RRRR'),'DD/MM/RRRR'), " + " F.FUNCTION_NAME  from  IGRS_PAYMENT_MODE_DETAILS P, IGRS_FUNCTION_MASTER F" + " where COMBINE_ID = ? AND P.FUNCTION_ID = F.FUNCTION_ID";
	/*
	 * query for checking challan is valid or not respective of
	 * scrollno,challan-online-date,amount and retrieving transactionid
	 */
	public static final String CHALLAN_VALID = " SELECT TRANSACTION_ID FROM IGRS_PAYMENT_MODE_DETAILS" + " WHERE STATUS_FLAG LIKE 'A' AND ";
	/* QUERY FOR GETTING OFFICEID BASED ON USERID */
	public static final String CASH_OFFICE_ID = "SELECT OFFICE_ID FROM IGRS_USER_OFFICE_MAPPING WHERE USER_ID=?";

	/* QUERY FOR GETTING empname BASED ON USERID */
	public static final String CASH_EMP_NAME = "select FIRST_NAME||' '||MIDDLE_NAME||' '||LAST_NAME from IGRS_USER_REG_DETAILS" + " where USER_ID =?";

	/* QUERY FOR GETTING SUM BASED ON OFFICEID */
	public static final String CASH_SUM = "SELECT SUM(GROSS_AMOUNT) from IGRS_PAYMENT_MODE_DETAILS where OFFICE_ID = ? AND TO_CHAR(CREATED_DATE, 'DD-MON-YY') = TO_CHAR(SYSDATE, 'DD-MON-YY')";
	/* QUERY FOR GETTING limit BASED ON OFFICEID */
	public static final String CASH_LIMIT = "SELECT CASH_LIMIT from IGRS_PAYMENT_OFFICE_LIMIT where OFFICE_ID =?";
	/* QUERY FOR GETTING Detailhead id BASED ON functionID */
	public static final String CASH_DETAILHEAD_ID = "SELECT DETAILED_HEAD_ID FROM IGRS_EXP_FUNCTION_DH_MAP WHERE FUNCTION_ID=?";

	/* QUERY FOR GETTING DISTRICT id BASED ON OFFICEID */
	/*
	 * public static final String CASH_DISTRICT_ID=
	 * "SELECT DISTRICT_ID FROM IGRS_OFFICE_AREA_JURISDICTION WHERE OFFICE_ID=";
	 */
	public static final String CASH_DISTRICT_ID = "SELECT DISTRICT_ID FROM IGRS_OFFICE_MASTER WHERE OFFICE_ID=?";
	public static final String CASH_DISTRICT_NAME = "SELECT DISTRICT_NAME FROM IGRS_DISTRICT_MASTER WHERE DISTRICT_ID=?";
	/* QUERY FOR GETTING Function Name BASED ON Function id */
	public static final String CASH_FUNCTION_NAME = "SELECT FUNCTION_NAME  FROM IGRS_FUNCTION_MASTER WHERE FUNCTION_ID=?";
	/* QUERY FOR GETTING payment mode name BASED ON paymentmode id */
	public static final String CASH_PAYMENT_MODE_NAME = "SELECT PAYMENT_TYPE_NAME FROM IGRS_PAYMENT_TYPE_MASTER WHERE PAYMENT_TYPE_ID=?";

	/* QUERY FOR GETTING poffice name BASED ON office id */
	public static final String Office_NAME = "SELECT OFFICE_NAME FROM IGRS_OFFICE_MASTER WHERE OFFICE_ID=?";
	/* QUERY FOR GETTING USER NAME BASED ON USER id */
	// public static final String CASH_USER_NAME=
	// "SELECT USER_ID  FROM IGRS_USERS_LIST WHERE FUNCTION_ID=";
	/* QUERY FOR INSERTING CASH PAYMENT DETAILS */
	public static final String COMMON_INSERT = "INSERT INTO IGRS_PAYMENT_COMBINE_DETAILS(COMBINE_ID," + "FIRST_NAME," + "MIDDLE_NAME,LAST_NAME,GENDER,NET_AMOUNT," + "CREATED_BY, TRANS_STATUS)" + "VALUES(?,?,?,?,?,round(?),?, 'I')";
	/* QUERY FOR INSERTING CASH PAYMENT DETAILS */
	public static final String CASH_INSERT = "INSERT INTO IGRS_PAYMENT_MODE_DETAILS(TRANSACTION_ID," + "GROSS_AMOUNT," + "NET_AMOUNT,CREATED_BY,UPDATE_BY,FIRST_NAME," + "MIDDLE_NAME,LAST_NAME,GENDER,AGE,PHOTO_PROOF_TYPE_ID,PHOTO_PROOF_ID," + "GUARDIAN_NAME,PAYMENT_TYPE_ID,BANK_NAME,BANK_ADDRESS,OFFICE_ID," + "REG_USER_ID,DISTRICT_ID,FUNCTION_ID,REMARKS,STATUS_FLAG,COMBINE_ID,CHALLAN_ONLINE_DATE,CREATED_DATE,UPDATE_DATE, MAJOR_HEAD_ID,MINOR_HEAD_ID,SUB_MAJOR_HEAD_ID,POS_REF_NO,SAMPADA_SERVICE)" + "VALUES(?,round(?), round(?)," + "?,?,?,?,?,?," + "?,?,?,?,?,?,?,?,?,?," + "?,?,?,?,SYSDATE,SYSDATE,SYSDATE,(select REVENUE_MAJOR_HEAD from IGRS_FUNCTION_SERVICE_MAPPING ac where ac.FUNCTION_ID=?),(select REVENUE_MINOR_HEAD from IGRS_FUNCTION_SERVICE_MAPPING ac where ac.FUNCTION_ID=?),(select REVENUE_SUB_MAJOR_HEAD from IGRS_FUNCTION_SERVICE_MAPPING ac where ac.FUNCTION_ID=?),?,?)";

	public static final String CASH_INSERT_New = "INSERT INTO IGRS_PAYMENT_MODE_DETAILS(TRANSACTION_ID," + "GROSS_AMOUNT," + "NET_AMOUNT,CREATED_BY,UPDATE_BY,FIRST_NAME," + "MIDDLE_NAME,LAST_NAME,GENDER,AGE,PHOTO_PROOF_TYPE_ID,PHOTO_PROOF_ID," + "GUARDIAN_NAME,PAYMENT_TYPE_ID,BANK_NAME,BANK_ADDRESS,OFFICE_ID," + "REG_USER_ID,DISTRICT_ID,FUNCTION_ID,REMARKS,STATUS_FLAG,COMBINE_ID,CHALLAN_ONLINE_DATE,CREATED_DATE,UPDATE_DATE, MAJOR_HEAD_ID,MINOR_HEAD_ID,SUB_MAJOR_HEAD_ID,POS_REF_NO,SAMPADA_SERVICE,CHECKER_REG_TXN_ID)" + "VALUES(?,round(?), round(?)," + "?,?,?,?,?,?," + "?,?,?,?,?,?,?,?,?,?," + "?,?,?,?,SYSDATE,SYSDATE,SYSDATE,(select REVENUE_MAJOR_HEAD from IGRS_FUNCTION_SERVICE_MAPPING ac where ac.FUNCTION_ID=?),(select REVENUE_MINOR_HEAD from IGRS_FUNCTION_SERVICE_MAPPING ac where ac.FUNCTION_ID=?),(select REVENUE_SUB_MAJOR_HEAD from IGRS_FUNCTION_SERVICE_MAPPING ac where ac.FUNCTION_ID=?),?,?,?)";

	/* QUERY FOR INSERTING MAPPING TABLE HAVING CHALLNIDS ALONG WITH CASH */
	public static final String Tid_INSERT = "INSERT INTO IGRS_PAYMENT_MODE_MAPPING(TXN_ID,DEPENDANT_TXN_ID) " + "VALUES(?,?)";
	/* QUERY FOR UPDATING CHALLAN STATUS AFTER USED */
	public static final String STATUS_UPDATE = "UPDATE IGRS_PAYMENT_MODE_DETAILS SET STATUS_FLAG='D'" + "WHERE TRANSACTION_ID=?";

	/* QUERY FOR UPDATING Combine id STATUS AFTER successful insertion */
	public static final String CASH_UPDATE = "UPDATE IGRS_PAYMENT_COMBINE_DETAILS SET TRANS_STATUS ='C'" + "WHERE COMBINE_ID=? AND TRANS_STATUS = 'I' ";
	/* QUERY FOR UPDATING EOD CHALLAN ID for cash collected */
	public static final String EOD_ID_UPDATE = "UPDATE IGRS_PAYMENT_MODE_DETAILS SET EOD_CHALLAN_ID=?" + "WHERE OFFICE_ID=? AND SUB_MAJOR_HEAD_ID=? AND MINOR_HEAD_ID=? and SAMPADA_SERVICE=? AND EOD_CHALLAN_ID IS NULL ";

	/** queries related to Challan Generation View **/
	/* QUERY FOR RETRIEVING OFFICENAMES */
	public static final String OFFICE_NAME_LIST = "SELECT OFFICE_ID,OFFICE_NAME FROM " + "IGRS_OFFICE_MASTER WHERE OFFICE_TYPE_ID='3' ORDER BY OFFICE_NAME";
	/* QUERY FOR GETTING STATUS AND TXNID OF CHALLANGEN */
	public static final String CHALLAN_STATUS_LIST = "SELECT TRANSACTION_ID,DELIVERY_STATUS FROM " + "IGRS_CHALLAN_GEN_DETAILS WHERE " + "GENERATED_OFFICE_ID=? AND CREATED_DATE=?";

	public static final String SERVICE_FEE_PROCEDURE = "CALL " + "IGRS_SERVICE_FEE_PKG.IGRS_SERVICE_FEE_PROC(?,?,?,?,?,?)";

	/* QUERY FOR GETTING Total Amount for EOD challan gen */
	/*
	 * public static final String CASH_AMOUNT= "SELECT SUM (NET_AMOUNT) FROM "+
	 * "IGRS_PAYMENT_MODE_DETAILS  WHERE " +
	 * "OFFICE_ID=? AND CREATED_DATE=? AND EOD_CHALLAN_ID IS NULL";
	 */
	/* QUERY FOR GETTING Total Amount for EOD challan gen */

	// commented by Anuj
	/*
	 * public static final String CASH_AMOUNT= "SELECT SUM (NET_AMOUNT) FROM "+
	 * "IGRS_PAYMENT_MODE_DETAILS  WHERE " +
	 * "OFFICE_ID=? AND TRUNC(CREATED_DATE)= TO_DATE(?, 'DD/MM/RRRR')AND EOD_CHALLAN_ID IS NULL"
	 * ;
	 */

	// added by Anuj
	/*
	 * public static final String CASH_AMOUNT=
	 * "SELECT SUM (NET_AMOUNT), TO_CHAR(MIN(CREATED_DATE), 'dd/MM/yyyy') FROM"
	 * + "	IGRS_PAYMENT_MODE_DETAILS  WHERE" +
	 * "	OFFICE_ID=? AND EOD_CHALLAN_ID IS NULL";
	 */
	public static final String CASH_AMOUNT = "SELECT SUM (NET_AMOUNT), TO_CHAR(MIN(CREATED_DATE), 'dd/MM/yyyy') FROM" + "	IGRS_PAYMENT_MODE_DETAILS  WHERE" + "	OFFICE_ID=? AND SUB_MAJOR_HEAD_ID=? AND MINOR_HEAD_ID=? AND SAMPADA_SERVICE=? AND EOD_CHALLAN_ID IS NULL";

	/* QUERY FOR VIEING CHALLAN GENERATION DETAILS */
	public static final String CHALLAN_GEN_LIST = "SELECT C.OFFICE_ID," + "TO_CHAR(C.CREATED_DATE,'DD/MM/YYYY')," + "O.OFFICE_NAME FROM IGRS_PAYMENT_MODE_DETAILS C," + "IGRS_OFFICE_MASTER O WHERE " + "O.OFFICE_ID=C.OFFICE_ID AND " + "C.OFFICE_ID=? AND TO_DATE(C.CREATED_DATE,'DD/MM/YYYY')= TO_DATE(?, 'DD/MM/YYYY')";

	// query to get latest eod challan detail
	public static final String LATEST_EOD_DTL = "SELECT TRANSACTION_ID, CREATED_BY  FROM IGRS_CHALLAN_GEN_DETAILS " + "WHERE GENERATED_OFFICE_ID = ? AND CREATED_DATE = (SELECT MAX(CREATED_DATE) " + "FROM IGRS_CHALLAN_GEN_DETAILS WHERE " + "GENERATED_OFFICE_ID = ?)";

	/** queries related to Challan UPDATION View **/
	/* QUERY FOR GETTING STATUS OF CHALLAN DELIVERED OR NOT */
	public static final String CHALLAN_GEN_UPDATE_STATUS = "SELECT DELIVERY_STATUS FROM IGRS_CHALLAN_GEN_DETAILS " + "WHERE TRANSACTION_ID=";
	/* QUERY FOR GETTING USERIDS */
	public static final String USER_ID_LIST = "SELECT USER_ID FROM IGRS_USERS_LIST";
	/* QUERY FOR GETTING BANKIDS */
	public static final String BANK_ID_LIST = "SELECT BANK_ID,BANK_NAME FROM IGRS_BANK_MASTER WHERE STATUS='A'";
	/* QUERY FOR UPDATING CHALLAN GENERATION AFTER DEPOSITED IN BANK */
	public static final String CHALLAN_GEN_UPDATE = "UPDATE IGRS_CHALLAN_GEN_DETAILS SET SCROLL_NUMBER=?," + "BANK_ID=?,DEPOSITED_DATE=?,DEPOSITED_BY=?,UPDATE_BY=?," + "UPDATE_DATE=TRUNC(SYSDATE),DELIVERY_STATUS='Y' WHERE TRANSACTION_ID=? " + "AND DELIVERY_STATUS='N'";
	/* QUERY FOR GETTING CHALLAN DETAILS AFTER UPDATING */
	public static final String CHALLAN_GEN_UPDATE_LIST = "SELECT C.TRANSACTION_ID,O.OFFICE_NAME," + "C.CREATED_BY,TO_CHAR(C.CREATED_DATE,'DD/MM/YYYY'),C.TOTAL_AMOUNT," + "C.SCROLL_NUMBER,TO_CHAR(C.DEPOSITED_DATE,'DD/MM/YYYY'),C.DEPOSITED_BY,C.BANK_ID " + "FROM IGRS_CHALLAN_GEN_DETAILS C,IGRS_OFFICE_MASTER O WHERE " + "O.OFFICE_ID=C.GENERATED_OFFICE_ID AND " + "TRANSACTION_ID=?";

	/*** QUERY RELATED TO fILEuPLOAD ****/
	/* QUERY FOR INSERTING CHALLAN DATA INTO TABLE */
	public static final String CHALLAN_INSERT = "INSERT INTO IGRS_PAYMENT_MODE_DETAILS(TRANSACTION_ID," + "TREASURY_ID,CHALLAN_ONLINE_NUMBER,CHALLAN_ONLINE_DATE," + "MAJOR_HEAD_ID,SUB_MAJOR_HEAD_ID,MINOR_HEAD_ID," + "SCHEME_HEAD_ID,OBJECT_HEAD_ID,GROSS_AMOUNT,NET_AMOUNT," + "BANK_ID,DEPOSITED_BY,SCROLL_NUMBER,CIN,PAYMENT_TYPE_ID," + "STATUS_FLAG,CREATED_BY,CREATED_DATE)" + " VALUES(?,?,?,?,?,?,?,?,?," + "?,?,?,?,?,?,'02','A',?,TRUNC(SYSDATE))";

	/* QUERY FOR INSERTING EOD CHALLAN DATA INTO TABLE */
	public static final String EOD_INSERT = "INSERT INTO IGRS_CHALLAN_GEN_DETAILS (TRANSACTION_ID," + "GENERATED_OFFICE_ID,CREATED_BY,TOTAL_AMOUNT," + "DELIVERY_STATUS,CREATED_DATE,CASH_COLLECTION_DATE,REV_MJR_HEAD,REV_SUBMJR_HEAD,REV_MINOR_HEAD,SAMPADA_SERVICE)" + " VALUES(?,?,?,?,'N',SYSDATE, to_date(?,'dd/mm/yyyy'),?,?,?,?)";
	/* QUERY FOR RETRIEVING INSERTING EXCEL DATA */
	public static final String CHALLAN_EXCEL_LIST = "SELECT C.TRANSACTION_ID,C.SCROLL_NUMBER,C.GROSS_AMOUNT,C.CIN," + "C.DEPOSITED_BY,TO_CHAR(C.CHALLAN_ONLINE_DATE,'DD/MM/YYYY')," + "T.TREASURY_NAME  FROM IGRS_PAYMENT_MODE_DETAILS C," + "IGRS_TREASURY_MASTER T " + "WHERE  C.CREATED_DATE=(TRUNC(SYSDATE)) " + "AND C.PAYMENT_TYPE_ID='02' AND C.TREASURY_ID=T.TREASURY_ID " + "AND C.CREATED_BY=";

	// added by Aakriti

	public static final String TRANS_QUERY = "select P.FIRST_NAME||' '||P.MIDDLE_NAME||' '||P.LAST_NAME,  P.TRANSACTION_ID, P.GROSS_AMOUNT," + " TO_CHAR(P.CREATED_DATE,'dd/MM/yyyy hh:mi:ss AM'), F.FUNCTION_NAME,P.MAJOR_HEAD_ID,P.SUB_MAJOR_HEAD_ID,P.MINOR_HEAD_ID from  IGRS_PAYMENT_MODE_DETAILS P, IGRS_FUNCTION_MASTER F" + " where COMBINE_ID = ? AND P.FUNCTION_ID = F.FUNCTION_ID";

	// BELOW ADDED BY ROOPAM ON 7 OCT 2013 FOR CAST AUDIT POINT CLOSURE.

	public static final String SELECT_TRANSACTION_ID = "SELECT COUNT(TRANSACTION_ID) FROM IGRS_CHALLAN_GEN_DETAILS WHERE TRUNC(CREATED_DATE)= TRUNC(SYSDATE)";
	/*
	 * public static final String
	 * DROP_PAYMENT_EOD_ID_SEQ="DROP SEQUENCE IGRS_PAYMENT_EOD_ID_SEQ"; public
	 * static final StringCREATE_PAYMENT_EOD_ID_SEQ=
	 * "CREATE SEQUENCE IGRS_PAYMENT_EOD_ID_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 999999 MINVALUE 1 NOCYCLE  NOCACHE ORDER"
	 * ;
	 */
	// public static final String GET_PAYMENT_EOD_ID_SEQ_NEXTVAL=
	// "select IGRS_PAYMENT_EOD_ID_SEQ.nextval from dual";
	public static final String GET_FULL_NAME_FROM_EMP_MASTER = "SELECT FIRST_NAME||' '||MIDDLE_NAME||' ' ||LAST_NAME FROM IGRS_EMP_MASTER where EMP_ID =?";
	// public static final String EOD_CHALLAN_DETAILS_VIEW=
	// "SELECT TRANSACTION_ID, to_char(CREATED_DATE, 'dd/MM/yyyy hh:mi:ss AM'), CREATED_BY FROM IGRS_CHALLAN_GEN_DETAILS WHERE TRANSACTION_ID=? OR CREATED_DATE BETWEEN ? AND ? AND GENERATED_OFFICE_ID = ?"
	// ;
	// public static final String EOD_CHALLAN_ALL_DETAILS_VIEW=
	// "SELECT C.TRANSACTION_ID, to_char(C.CREATED_DATE, 'dd/MM/yyyy hh:mi:ss AM'), C.TOTAL_AMOUNT, to_char(C.CASH_COLLECTION_DATE,'dd/MM/yyyy hh:mi:ss AM'), O.OFFICE_NAME, C.CREATED_BY, W.FIRST_NAME||' '||W.MIDDLE_NAME||' '||W.LAST_NAME, C.REV_MJR_HEAD||','||MJR.REVENUE_MAJOR_HEAD_NAME , C.REV_SUBMJR_HEAD||','||SBMJR.REVENUE_SUB_MAJOR_HEAD_NAME , C.REV_MINOR_HEAD||','||MNR.REVENUE_MINOR_HEAD_NAME FROM IGRS_CHALLAN_GEN_DETAILS C, IGRS_USER_REG_DETAILS W, IGRS_OFFICE_MASTER O, IGRS_REVENUE_MAJOR_HEAD_MASTER MJR, IGRS_REVENUE_SBMJRHD_MASTER SBMJR, IGRS_REVENUE_MINOR_HEAD_MASTER MNR WHERE O.OFFICE_ID=C.GENERATED_OFFICE_ID AND C.CREATED_BY=W.USER_ID AND C.REV_MJR_HEAD=MJR.REVENUE_MAJOR_HEAD AND C.REV_SUBMJR_HEAD=SBMJR.REVENUE_SUB_MAJOR_HEAD AND C.REV_MINOR_HEAD=MNR.REVENUE_MINOR_HEAD and MNR.REVENUE_MINOR_HEAD_STATUS='A' AND TRANSACTION_ID = ?"
	// ;
	public static final String EOD_CHALLAN_DETAILS_VIEW = "SELECT EPNR_NO,  TO_CHAR(CREATED_DATE, 'dd/MM/yyyy hh:mi:ss AM'),  CREATED_BY FROM IGRS_PAYMENT_ECHALLAN_DETAILS WHERE (EPNR_NO=? OR CREATED_DATE BETWEEN to_date(?,'dd-mon-yy') AND to_date(?,'dd-mon-yy')+1) AND OFFICE_ID = ? and PAYMENT_MODE_ID=1";
	public static final String EOD_CHALLAN_ALL_DETAILS_VIEW = "SELECT C.TRANSACTION_ID, to_char(C.CREATED_DATE, 'dd/MM/yyyy hh:mi:ss AM'), C.TOTAL_AMOUNT, to_char(C.CASH_COLLECTION_DATE,'dd/MM/yyyy hh:mi:ss AM'), O.OFFICE_NAME, C.CREATED_BY, W.FIRST_NAME||' '||W.MIDDLE_NAME||' '||W.LAST_NAME, C.REV_MJR_HEAD||','||MJR.REVENUE_MAJOR_HEAD_NAME , C.REV_SUBMJR_HEAD||','||SBMJR.REVENUE_SUB_MAJOR_HEAD_NAME , C.REV_MINOR_HEAD||','||MNR.REVENUE_MINOR_HEAD_NAME,d.EPNR_NO,C.SAMPADA_SERVICE FROM IGRS_CHALLAN_GEN_DETAILS C, IGRS_USER_REG_DETAILS W, IGRS_OFFICE_MASTER O, IGRS_REVENUE_MAJOR_HEAD_MASTER MJR, IGRS_REVENUE_SBMJRHD_MASTER SBMJR, IGRS_REVENUE_MINOR_HEAD_MASTER MNR,IGRS_PAYMENT_ECHALLAN_DETAILS d WHERE O.OFFICE_ID=C.GENERATED_OFFICE_ID AND C.CREATED_BY=W.USER_ID AND C.REV_MJR_HEAD=MJR.REVENUE_MAJOR_HEAD AND C.REV_SUBMJR_HEAD=SBMJR.REVENUE_SUB_MAJOR_HEAD AND C.REV_MINOR_HEAD=MNR.REVENUE_MINOR_HEAD and MNR.REVENUE_MINOR_HEAD_STATUS='A' and d.CHALLAN_SERIAL_NUMBER=TRANSACTION_ID AND d.EPNR_NO  = ?";

	// HINDI QUERIES BY ROOPAM
	public static final String CASH_PHOTOID_LIST_HINDI = "SELECT PHOTO_PROOF_TYPE_ID,PHOTO_PROOF_TYPE_NAME,H_PHOTO_PROOF_TYPE_NAME FROM " + "IGRS_PHOTOID_PROOF_TYPE_MASTER WHERE PHOTO_PROOF_TYPE_STATUS = 'A'";

	public static final String OFFICE_NAME_HINDI = "SELECT H_OFFICE_NAME FROM IGRS_OFFICE_MASTER WHERE OFFICE_ID=?";

	public static final String CASH_DISTRICT_NAME_HINDI = "SELECT H_DISTRICT_NAME FROM IGRS_DISTRICT_MASTER WHERE DISTRICT_ID=?";

	/*
	 * public static final String CASH_FUNCTIONID_LIST_HINDI=
	 * "SELECT FUNCTION_ID,FUNCTION_NAME,FUNCTION_NAME_H FROM "+
	 * "IGRS_FUNCTION_MASTER WHERE PAYMENT_FLAG='Y' ORDER BY FUNCTION_NAME ";
	 */

	public static final String TRANS_QUERY_HINDI = "select P.FIRST_NAME||' '||P.MIDDLE_NAME||' '||P.LAST_NAME,  P.TRANSACTION_ID, P.GROSS_AMOUNT," + " TO_CHAR(P.CREATED_DATE,'dd/MM/yyyy hh:mi:ss AM'), F.FUNCTION_NAME,P.MAJOR_HEAD_ID,P.SUB_MAJOR_HEAD_ID,P.MINOR_HEAD_ID, F.FUNCTION_NAME_H,P.POS_REF_NO,P.SAMPADA_SERVICE from  IGRS_PAYMENT_MODE_DETAILS P, IGRS_FUNCTION_MASTER F" + " where COMBINE_ID = ? AND P.FUNCTION_ID = F.FUNCTION_ID";

	// akansha
	public static final String TRANS_QUERY_NEW = "select P.TRANSACTION_ID" + "  from  IGRS_PAYMENT_MODE_DETAILS P, IGRS_FUNCTION_MASTER F" + " where COMBINE_ID = ? AND P.FUNCTION_ID = F.FUNCTION_ID";

	public static final String CombineID = "select COMBINE_ID" + "  from  IGRS_PAYMENT_MODE_DETAILS " + " where TRANSACTION_ID = ? ";
	// akansha
	public static final String CASH_FUNCTIONID_SERVICEEng = "SELECT A.FUNCTION_NAME FROM IGRS_FUNCTION_MASTER A, IGRS_FUNCTION_SERVICE_MAPPING B WHERE A.FUNCTION_ID=B.FUNCTION_ID AND B.MAPPING_STATUS='A' AND A.FUNCTION_STATUS='A' AND  A.FUNCTION_ID=? ORDER BY FUNCTION_NAME";

	// akansha
	public static final String CASH_FUNCTIONID_SERVICEHnd = "SELECT A.FUNCTION_NAME_H FROM IGRS_FUNCTION_MASTER A, IGRS_FUNCTION_SERVICE_MAPPING B WHERE A.FUNCTION_ID=B.FUNCTION_ID AND B.MAPPING_STATUS='A' AND A.FUNCTION_STATUS='A' AND  A.FUNCTION_ID=? ORDER BY FUNCTION_NAME";

	// akansha
	public static final String ACTIVE_CASH = "select TRANSACTION_ID" + "  from  IGRS_PAYMENT_MODE_DETAILS " + " where CHECKER_REG_TXN_ID = ? AND STATUS_FLAG =? AND FUNCTION_ID =? AND GROSS_AMOUNT =? and CREATED_BY = ?";

	public static final String Cash_receipt_new = "select TRANSACTION_ID" + "  from  IGRS_PAYMENT_MODE_DETAILS " + " where CHECKER_REG_TXN_ID = ? AND STATUS_FLAG =? AND FUNCTION_ID =? AND GROSS_AMOUNT =?";

	public static final String Cash_Amount = "select PAYABLE_AMOUNT" + " from  IGRS_REG_PAYMENT_DETLS " + " where REG_TXN_ID = ? AND PAYMENT_FLAG =? order by TXN_ID desc";

	public static final String REQ_DETL_QRY = "SELECT m.OFFICE_NAME, m.DISTRICT_ID, d.DISTRICT_NAME FROM IGRS_OFFICE_MASTER m, IGRS_DISTRICT_MASTER d " + "WHERE  m.OFFICE_ID=? AND m.DISTRICT_ID =d.DISTRICT_ID";

	public static final String REQ_DETL_QRY_HINDI = "SELECT m.H_OFFICE_NAME, m.DISTRICT_ID, d.DISTRICT_NAME FROM IGRS_OFFICE_MASTER m, IGRS_DISTRICT_MASTER d " + "WHERE  m.OFFICE_ID=? AND m.DISTRICT_ID =d.DISTRICT_ID";

	// public static final String GET_REV_HEAD_FEE=
	// "SELECT REVENUE_MAJOR_HEAD,REVENUE_SUB_MAJOR_HEAD,REVENUE_MINOR_HEAD,FEE_RU,FEE_SP,FEE_DR FROM IGRS_FUNCTION_SERVICE_MAPPING WHERE FUNCTION_ID=?"
	// ;

	public static final String DROP_PAYMENT_EOD_ID_SEQ = "DROP SEQUENCE IGRS_PAYMENT_ECHALLAN_ID_SEQ";
	public static final String CREATE_PAYMENT_EOD_ID_SEQ = "CREATE SEQUENCE IGRS_PAYMENT_ECHALLAN_ID_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 999999 MINVALUE 1 NOCYCLE  NOCACHE ORDER";
	public static final String GET_PAYMENT_EOD_ID_SEQ_NEXTVAL = "select IGRS_PAYMENT_ECHALLAN_ID_SEQ.nextval from dual";

	// added bu akansha
	public static final String CASH_FUNCTIONID_LIST_HINDI = "SELECT A.FUNCTION_ID,A.FUNCTION_NAME,A.FUNCTION_NAME_H FROM IGRS_FUNCTION_MASTER A, IGRS_FUNCTION_SERVICE_MAPPING B WHERE A.FUNCTION_ID=B.FUNCTION_ID AND B.MAPPING_STATUS='A' AND A.FUNCTION_STATUS='A' AND A.FUNCTION_ID != 'FUN_206' AND A.FUNCTION_ID != 'FUN_023' ORDER BY FUNCTION_NAME";

	public static final String GET_REV_HEAD_FEE = "SELECT REVENUE_MAJOR_HEAD,REVENUE_SUB_MAJOR_HEAD,REVENUE_MINOR_HEAD,FEE_RU,FEE_SP,FEE_DR,CAPTURE_FEE,FEE_BASED_ON,FEE_BASED_ON_H FROM IGRS_FUNCTION_SERVICE_MAPPING WHERE FUNCTION_ID=?";

	public static final String GET_EMP_NAME_DESIGNATION = "  SELECT C.FIRST_NAME,C.MIDDLE_NAME,C.LAST_NAME ,A.CADRE_NAME FROM IGRS_EMP_CADRE_MASTER A, IGRS_EMP_OFFICIAL_DETAILS B,IGRS_USER_REG_DETAILS C WHERE A.CADRE_ID=B.EMP_DESIGNATION_ID AND C.USER_ID=B.EMP_ID AND B.EMP_ID=?";

	public static final String CASH_DETAILS_VIEW = "SELECT TRANSACTION_ID,  TO_CHAR(CREATED_DATE, 'dd/MM/yyyy hh:mi:ss AM'),  GROSS_AMOUNT FROM IGRS_PAYMENT_MODE_DETAILS WHERE (TRANSACTION_ID=? OR CREATED_DATE BETWEEN to_date(?,'dd-mon-yy') AND to_date(?,'dd-mon-yy')+1) AND OFFICE_ID = ? ";
	public static final String CASH_DETAILS_VIEW_AND = "SELECT TRANSACTION_ID,  TO_CHAR(CREATED_DATE, 'dd/MM/yyyy hh:mi:ss AM'),  GROSS_AMOUNT FROM IGRS_PAYMENT_MODE_DETAILS WHERE (TRANSACTION_ID=? and CREATED_DATE BETWEEN to_date(?,'dd-mon-yy') AND to_date(?,'dd-mon-yy')+1) AND OFFICE_ID = ? ";

	public static final String TRANS_QUERY_HINDI_VIEW = "select P.FIRST_NAME||' '||P.MIDDLE_NAME||' '||P.LAST_NAME,  P.TRANSACTION_ID, P.GROSS_AMOUNT," + " TO_CHAR(P.CREATED_DATE,'dd/MM/yyyy hh:mi:ss AM'), F.FUNCTION_NAME,P.MAJOR_HEAD_ID,P.SUB_MAJOR_HEAD_ID,P.MINOR_HEAD_ID, F.FUNCTION_NAME_H,P.POS_REF_NO,P.SAMPADA_SERVICE from  IGRS_PAYMENT_MODE_DETAILS P, IGRS_FUNCTION_MASTER F" + " where TRANSACTION_ID = ? AND P.FUNCTION_ID = F.FUNCTION_ID";

	/*
	 * public static final StringPAYMENT_SERVICE_LIST=
	 * "SELECT A.FUNCTION_ID,  A.FUNCTION_NAME,  A.FUNCTION_NAME_H,fee_sp,fee_ru FROM IGRS_FUNCTION_MASTER A, "
	 * +
	 * "  IGRS_FUNCTION_SERVICE_MAPPING B WHERE A.FUNCTION_ID =B.FUNCTION_ID AND B.MAPPING_STATUS ='A' AND A.FUNCTION_STATUS='A' "
	 * + " AND PAYMENT_SERVICE_FLAG='Y' " + " UNION ALL " +
	 * " SELECT A.FUNCTION_ID,   A.FUNCTION_NAME,   A.FUNCTION_NAME_H,0,0 " +
	 * " FROM IGRS_FUNCTION_MASTER A WHERE A.FUNCTION_STATUS='A' AND PAYMENT_SERVICE_FLAG='Y' "
	 * + " AND A.FUNCTION_ID='FUN_028' ORDER BY FUNCTION_NAME ";
	 */
	public static final String PAYMENT_SERVICE_LIST = "SELECT B.FUNCTION_ID,  SERVICE_NAME,  SERVICE_NAME_H,    FEE_RU,  FEE_SP,  FEE_DR ,C.SERVICE_ID " + " FROM IGRS_FUNCTION_MASTER A,  IGRS_FUNCTION_SERVICE_MAPPING B,IGRS_SERVICE_MASTER C " + " WHERE A.FUNCTION_ID     =B.FUNCTION_ID AND b.service_id=C.service_id AND B.MAPPING_STATUS    ='A' AND A.FUNCTION_STATUS   ='A' " + " AND c.service_status='A' AND PAYMENT_SERVICE_FLAG='Y' order by SERVICE_NAME";

	public static final String PAYMENT_YEAR__RANGE_LIST = "SELECT YEAR_RANGE FROM IGRS_YEAR_MASTER";

	public static final String PAYMENT_SERVICE_MASTER = "SELECT PARENT_TABLE_NAME tableName,  PARENT_COLUMN_NAME columnName,  SOURCE_MOD_COLUMN srcColumn, " + "  PAYMENT_COLUMN_FLAG srcFlag,PARENT_KEY_COLUMN parentKey,PAYMENT_COLUMN_NAME,PARENT_SEQUENCE,PARENT_MOD_NAME,PARENT_FUN_NAME,PARENT_FUN_ID " + "  FROM igrs_payment_services_master WHERE service_id=? and STATUS_FLAG='A'";

	public static final String USER_TYPE_QUERY = "Select USER_TYPE_ID from IGRS_USERS_LIST where USER_ID =?";
	public static final String USER_DETAILS = "SELECT  SP.DISTRICT_ID,(SELECT DISTRICT_NAME FROM IGRS_DISTRICT_MASTER WHERE DISTRICT_ID = SP.DISTRICT_ID) FROM IGRS_SP_DETLS SP " + " WHERE SP.CREATED_BY =? AND SP.STATUS ='A' AND SP.APPLCTN_STATUS='8'";

	public static final String USER_RU_DETAILS = "select a.district_id,b.district_name " + "   from IGRS_USER_REG_DETAILS a,igrs_district_master b    where a.district_id=b.district_id    and a.user_id=?    and user_status='A'";

	public static final String USER_RU_DETAILS_HI = "select a.district_id,b.h_district_name " + "   from IGRS_USER_REG_DETAILS a,igrs_district_master b    where a.district_id=b.district_id    and a.user_id=?    and user_status='A'";
	public static final String PAYMENT_SERVICE_DETAILS = "SELECT PARENT_MOD_NAME,PARENT_FUN_NAME,PARENT_FUN_ID,PARENT_KEY_COLUMN,PARENT_TABLE_NAME " + "FROM igrs_payment_services_master WHERE service_id=? and STATUS_FLAG='A'";

	public static final String INSERT_PAYMENT_SERVICE = "INSERT INTO IGRS_PAYMENT_SERVICE_LOG VALUES (IGRS_PAYMENT_SERVICE_SEQUENCE.nextval, ?, ?, ?, ?, SYSTIMESTAMP,?)";

	public static final String PAYMENT_SERVICE_PROCEDURE = "CALL IGRS_PAYMENT_SERVICE_PROCEDURE(?,?,?,?,?,?)";

	public static final String PAYMENT_RECORD = "select distinct PAYMENT_MODE,amount_paid,payment_date,c.transaction_id,REFERENCE_ID,PAYMENT_MODE_H " + " from IGRS_PAYMENT_MODE_MASTER a,IGRS_PAYMENT_SERVICE_LOG b,igrs_payment_txn_details c " + " where a.PAYMENT_MODE_ID=c.PAYMENT_TYPE_ID and b.REFERENCE_ID=c.PARENT_REF_ID " + " and b.PARENT_FUNID=c.payment_purpose and b.REFERENCE_ID=? " + " and parent_key=PARENT_KEY_COL and c.payment_purpose=?";

	public static final String SELECT_SERVICE_ID = "SELECT DISTINCT SERVICE_ID FROM IGRS_PAYMENT_SERVICES_MASTER WHERE PARENT_FUN_ID=?";

	public static final String OFFLINE_PAYMENT_SERVICE = "SELECT SERVICE_ID,FUNCTION_ID, " + "  nvl(FEE_RU,'0'),   nvl(FEE_SP,'0'),   nvl(FEE_DR,'0'), SERVICE_NAME, " + "  H_SERVICE_NAME,USER_ENTERABLE_NAME,H_USER_ENTERABLE_NAME,MAPPING_DESC,REF_NAME,REF_NAME_H " + " FROM IGRS_OFFLINE_SERVICE_MAPPING A,IGRS_SERVICE_USER_ENTERABLE B " + " WHERE MAPPING_STATUS='A' AND A.USER_PARAM_ID=b.enterable_id(+) " + " ORDER BY SERVICE_NAME";
	public static final String OFFLINE_PAYMENT_SEQUENCE = "select TO_CHAR(SYSDATE,'DDMMYYYY'),IGRS_OFFLINE_PAYMENT_SEQ.nextval from dual";

	public static final String OFFLINE_PAYMENT_INSERT = "INSERT INTO IGRS_OFFLINE_PAYMENT_DETLS (PAYMENT_REF_ID, OFF_SERVICE_ID, USER_ENTERABLE, " + "   PAYABLE_AMOUNT, PAYMENT_FLAG, CREATED_BY, CREATED_DATE,CONSUMPTION_STATUS,REFERENCE_ID,PARTY_NAME,FROMYEAR,TOYEAR) VALUES " + "   (?,?,?,?,'I',?,SYSTIMESTAMP,'N',?,?,?,?) ";

	public static final String OFFLINE_OUTSIDE_SAMPADA = "SELECT A.PAYMENT_TXN_ID,    NVL(A.PAID_AMOUNT,0),    A.PAYMENT_REF_ID,    " + " c.first_name    ||' '    ||C.MIDDLE_NAME    ||' '    ||c.last_name, " + "    SERVICE_NAME,    H_SERVICE_NAME,    TO_CHAR(A.UPDATE_DATE,'dd-mm-yyyy hh:mi am'),    NVL(f.PAYMENT_MODE_H,'NA'), " + "    NVL(f.PAYMENT_MODE,'NA'),NVL(B.USER_ENTERABLE_NAME,'NA'), NVL(B.H_USER_ENTERABLE_NAME,'NA'),NVL(A.USER_ENTERABLE,'NA'),d.service_id, " + "	case A.CONSUMPTION_STATUS when 'N' THEN 'NOT CONSUMED' ELSE 'CONSUMED' END," + " A.CONSUMED_OFFCID,A.CONSUMPTION_USERID,A.CONSUMED_DATE " + "  FROM IGRS_OFFLINE_PAYMENT_DETLS A,  IGRS_SERVICE_USER_ENTERABLE B,    IGRS_USER_REG_DETAILS C,    IGRS_OFFLINE_SERVICE_MAPPING d, " + "    IGRS_PAYMENT_TXN_DETAILS e,    IGRS_PAYMENT_MODE_MASTER f " + "  WHERE A.CREATED_BY      =C.USER_ID  AND A.PAYMENT_TXN_ID  =E.TRANSACTION_ID " + "  AND f.PAYMENT_MODE_ID =e.PAYMENT_TYPE_ID  AND d.service_id      =A.OFF_service_id  AND A.PAYMENT_TXN_ID IS NOT NULL " + "  and paid_amount>0 AND A.PAYMENT_FLAG    ='P'  AND B.ENTERABLE_ID(+)=D.USER_PARAM_ID ";

	public static final String OFFLINE_OUTSIDE_SAMPADA_SERVICE = " AND d.service_id=? ";

	public static final String OFFLINE_OUTSIDE_SAMPADA_DURATION = " AND TRUNC(A.UPDATE_DATE) BETWEEN to_date(?,'dd-mm-yy') AND to_date(?,'dd-mm-yy') ";

	public static final String OFFLINE_OUTSIDE_SAMPADA_ORDER = " and a.created_by=? ORDER BY A.UPDATE_DATE desc";
	public static final String OFFLINE_OUTSIDE_SAMPADA_ORDERBY = " AND A.CONSUMPTION_STATUS = 'Y' AND A.CONSUMED_OFFCID=? ORDER BY A.UPDATE_DATE desc";
	public static final String GET_REPORT_DURATION = "SELECT ATTRIBUTE_VALUE FROM igrs_config_param_list WHERE attribute_id='137'";
	public static final String REPORT_DATE_DIFF = "select to_date(?,'dd-mm-yy')-to_date(?,'dd-mm-yy') from dual";

	/*
	 * public static final StringOFFLINE_CONSUMPTION_VALIDATE=
	 * "select A.SERVICE_NAME,	A.H_SERVICE_NAME,nvl(B.PAYMENT_TXN_ID,'--'),nvl(B.PAID_AMOUNT,0),nvl(C.USER_ENTERABLE_NAME,'NA'), "
	 * +
	 * "	nvl(C.H_USER_ENTERABLE_NAME,'NA'),NVL(B.USER_ENTERABLE,0),TO_CHAR(B.UPDATE_DATE,'dd-mm-yyyy hh:mi am'), "
	 * +
	 * "	 D.first_name    ||' '    ||D.MIDDLE_NAME    ||' '    ||D.last_name, "
	 * +
	 * "	 	case B.CONSUMPTION_STATUS when 'N' THEN 'NOT CONSUMED' ELSE 'CONSUMED' END, "
	 * +
	 * "	 NVL(B.CONSUMED_OFFCID,'NA'),NVL(B.CONSUMPTION_USERID,'NA'),NVL(TO_CHAR(B.CONSUMED_DATE,'dd-mm-yyyy hh:mi am'),'NA'), "
	 * +
	 * " OFFICE_NAME,H_OFFICE_NAME, F.first_name    ||' '    ||F.MIDDLE_NAME    ||' '    ||F.last_name "
	 * +
	 * "	from IGRS_OFFLINE_SERVICE_MAPPING A,IGRS_OFFLINE_PAYMENT_DETLS B,IGRS_SERVICE_USER_ENTERABLE C, "
	 * + "	IGRS_USER_REG_DETAILS D,IGRS_OFFICE_MASTER e,IGRS_EMP_MASTER F " +
	 * " WHERE C.ENTERABLE_ID(+)=A.USER_PARAM_ID AND B.CREATED_BY      =D.USER_ID "
	 * +
	 * " AND B.CONSUMPTION_USERID=F.EMP_ID  AND B.CONSUMED_OFFCID=E.OFFICE_ID "+
	 * "	AND B.OFF_SERVICE_ID=A.SERVICE_ID AND PAYMENT_REF_ID=?";
	 */

	public static final String OFFLINE_CONSUMPTION_VALIDATE = "SELECT A.SERVICE_NAME,	  A.H_SERVICE_NAME,	  NVL(B.PAYMENT_TXN_ID,'--'), " + "	  NVL(B.PAID_AMOUNT,0),	  NVL(C.USER_ENTERABLE_NAME,'NA'),	  NVL(C.H_USER_ENTERABLE_NAME,'NA'),	  NVL(B.USER_ENTERABLE,0), " + "	  nvl(TO_CHAR(B.UPDATE_DATE,'dd-mm-yyyy hh:mi am'),'--'),	  D.first_name	  ||' '	  ||D.MIDDLE_NAME	  ||' '	  ||D.last_name, " + "  CASE B.CONSUMPTION_STATUS	    WHEN 'N'	    THEN 'NOT CONSUMED'	    ELSE 'CONSUMED'	  END,  " + "	   case B.CONSUMPTION_STATUS	    WHEN 'N'then 'NA'	    else (select OFFICE_NAME	   from  IGRS_OFFICE_MASTER  where OFFICE_ID=B.CONSUMED_OFFCID)  end AS OFFICE_NAME, " + "    case B.CONSUMPTION_STATUS 	    WHEN 'N'then 'NA'	    else (select H_OFFICE_NAME	   from  IGRS_OFFICE_MASTER  where OFFICE_ID=B.CONSUMED_OFFCID)  end AS H_OFFICE_NAME, " + "	  case B.CONSUMPTION_STATUS	    WHEN 'N'then 'NA'	    else (select F.first_name	  ||' '	  ||F.MIDDLE_NAME	  ||' '	  ||F.last_name from  IGRS_EMP_MASTER F where F.emp_id=B.CONSUMPTION_USERID)  end AS EMMPNAME, " + "	   NVL(TO_CHAR(B.CONSUMED_DATE,'dd-mm-yyyy hh:mi am'),'NA'), 	" + "   (select PAYMENT_MODE from  IGRS_PAYMENT_MODE_MASTER where PAYMENT_MODE_ID=B.PAYMENT_MODE_ID) AS payment_mode, " + "   (select PAYMENT_MODE_H from  IGRS_PAYMENT_MODE_MASTER where PAYMENT_MODE_ID=B.PAYMENT_MODE_ID) AS h_payment_mode, " + " CASE B.CONSUMPTION_STATUS    WHEN 'N'    THEN 'NA'    ELSE      REFERENCE_ID  END AS REFERENCE_ID,nvl(REF_NAME,'--'),nvl(REF_NAME_H,'--'),NVL(B.REFERENCE_ID,'NA'),NVL(B.PARTY_NAME,'NA'),B.FROMYEAR,B.TOYEAR" + " FROM IGRS_OFFLINE_SERVICE_MAPPING A,	  IGRS_OFFLINE_PAYMENT_DETLS B,	  IGRS_SERVICE_USER_ENTERABLE C, " + "	  IGRS_USER_REG_DETAILS D	" + " WHERE C.ENTERABLE_ID(+) =A.USER_PARAM_ID	AND B.CREATED_BY        =D.USER_ID	AND B.OFF_SERVICE_ID    =A.SERVICE_ID " + "	AND PAYMENT_REF_ID      =? and A.SERVICE_ID=?";

	public static final String UPDATE_CONSUME_REFID = "UPDATE IGRS_OFFLINE_PAYMENT_DETLS SET CONSUMPTION_USERID = ?,CONSUMED_OFFCID=?, " + "CONSUMED_DATE=systimestamp,  REFERENCE_ID= ?,CONSUMPTION_STATUS='Y' WHERE PAYMENT_REF_ID=?";

	public static final String GET_EPRN_PAYMENT_DETAILS = "SELECT STATUS_FLAG,PAID_AMOUNT, TO_CHAR(CREATED_DATE, 'dd/mm/yyyy HH:mi:SS AM'), CREATED_BY FROM IGRS_PAYMENT_ECHALLAN_DETAILS WHERE EPNR_NO=?";
	public static final String GET_CRN_PAYMENT_DETAILS = "SELECT STATUS_FLAG,PAID_AMOUNT, TO_CHAR(CREATED_DATE, 'dd/mm/yyyy HH:mi:SS AM'), CREATED_BY FROM IGRS_PAYMENT_ECHALLAN_DETAILS WHERE CRN_NUMBER=?";
	public static final String GET_USER_TYPE = "SELECT USER_TYPE_ID FROM IGRS_USERS_LIST WHERE USER_ID=?";
	public static final String GET_PARENT_KEY_EFILE="SELECT PARENT_KEY FROM IGRS_PAYMENT_TXN_DETAILS where PARENT_REF_ID=?";
	public static final String EFILE_PAYMENT_CHECK="select nvl(payment_txn_id,'NA') from IGRS_EFILE_PAYMENT_DETLS where TXN_ID = ? AND PAID_AMOUNT= 500 and CREATED_BY=? and reg_txn_id=?";
	public static final String UPDATE_PAYMENT_EFILE="UPDATE IGRS_EFILE_PAYMENT_DETLS SET PAYMENT_FLAG='C' WHERE REG_TXN_ID=?  and PAYMENT_TXN_ID IS NOT NULL";
	public static final String CHANGE_EFILE_STATUS="UPDATE IGRS_EFILE_FINAL_DTLS SET PAYMENT_STATUS=? ,PRINT_FLAG=? where EFILE_TXN_ID=?";

	public static final String SELECT_DISTRICT_LIST="SELECT DISTRICT_ID, DISTRICT_NAME, H_DISTRICT_NAME from IGRS_DISTRICT_MASTER where STATE_ID=1 and DISTRICT_STATUS='A' order by DISTRICT_ID";
}
