package com.wipro.igrs.regcompletion.sql;


public class RegCommonSQL {
	//imran data
	public static final String SELECT_STAMP_DUTY = "SELECT E.ESTAMP_DUTY,E.ESTAMP_OTHER_FEES,E.PAYMENT_TXN_ID,E.ESTAMP_CODE FROM IGRS_ESTAMP_TXN_DETAILS E,IGRS_REG_INITN_TXN_DETAILS R WHERE E.TRANSACTION_ID=R.ESTAMP_TXN_ID AND R.TRANSACTION_ID=";
	//public static final String SELECT_APP_INFO = "SELECT R.REG_TXN_ID, T.PARTY_TYPE_NAME,R.PARTY_FIRST_NAME,R.PARTY_MIDDLE_NAME,R.PARTY_LAST_NAME,R.PARTY_GENDER,R.PARTY_AGE,R.NATIONALITY,C.COUNTRY_NAME,S.STATE_NAME,D.DISTRICT_NAME,R.PARTY_ADDRESS,R.POSTAL_CODE,R.PHONE_NUMBER,R.MOBILE_NUMBER,R.EMAIL_ID,P.PHOTO_PROOF_TYPE_NAME,R.PHOTO_PROOF_ID,R.BANK_NAME,R.BANK_ADDRESS,R.ORGANIZATION_NAME,R.GUARDIAN_NAME,R.MOTHER_NAME FROM IGRS_REG_INITN_TXN_PARTY_DTLS R,IGRS_PARTY_TYPE_MASTER T,IGRS_DISTRICT_MASTER D,IGRS_STATE_MASTER S,IGRS_COUNTRY_MASTER C,IGRS_PHOTOID_PROOF_TYPE_MASTER P WHERE T.PARTY_TYPE_ID=R.PARTY_TYPE_ID AND R.DISTRICT_ID=D.DISTRICT_ID AND R.STATE_ID=S.STATE_ID AND C.COUNTRY_ID=R.COUNTRY_ID AND R.PHOTO_PROOF_TYPE_ID=P.PHOTO_PROOF_TYPE_ID AND REG_TXN_ID=";
	public static final String SELECT_APP_INFO = "SELECT R.REG_TXN_ID,R.PARTY_FIRST_NAME,R.PARTY_MIDDLE_NAME,R.PARTY_LAST_NAME,R.PARTY_GENDER,R.PARTY_AGE,R.NATIONALITY,R.PARTY_ADDRESS,R.PHOTO_PROOF_TYPE_ID,R.POSTAL_CODE,R.PHONE_NUMBER,R.MOBILE_NUMBER,R.EMAIL_ID,R.PHOTO_PROOF_ID,R.BANK_NAME,R.BANK_ADDRESS,R.ORGANIZATION_NAME,R.GUARDIAN_NAME,R.MOTHER_NAME,P.PHOTO_PROOF_TYPE_NAME,C.COUNTRY_NAME,S.STATE_NAME,D.DISTRICT_NAME,T.PARTY_TYPE_NAME FROM IGRS_REG_INIT_TXN_PARTY_DTLS R,IGRS_PHOTOID_PROOF_TYPE_MASTER P,IGRS_COUNTRY_MASTER C,IGRS_DISTRICT_MASTER D,IGRS_STATE_MASTER S,IGRS_PARTY_TYPE_MASTER T WHERE C.COUNTRY_ID=R.COUNTRY_ID AND R.PHOTO_PROOF_TYPE_ID=P.PHOTO_PROOF_TYPE_ID AND T.PARTY_TYPE_ID=R.PARTY_ROLE_TYPE_ID AND REG_TXN_ID=";
	
	public static final String SELECT_CHECK_INFO = 
			"SELECT COUNT(*) FROM IGRS_REG_INITN_TXN_PARTY_DTLS R,"
			+"IGRS_PARTY_TYPE_MASTER T,IGRS_DISTRICT_MASTER D,"
			+"IGRS_STATE_MASTER S,IGRS_COUNTRY_MASTER C,"
			+"IGRS_PHOTOID_PROOF_TYPE_MASTER P WHERE "
			+"T.PARTY_TYPE_ID=R.PARTY_TYPE_ID AND "
			+"R.DISTRICT_ID=D.DISTRICT_ID AND "
			+"R.STATE_ID=S.STATE_ID AND C.COUNTRY_ID=R.COUNTRY_ID "
			+"AND R.PHOTO_PROOF_TYPE_ID=P.PHOTO_PROOF_TYPE_ID AND "
			+"REG_TXN_ID=";
	public static final String SELECT_SPOT_INSPECTION = 
		"SELECT COUNT(*) FROM IGRS_SPOT_INSPECTION_DETAILS WHERE "
		+"(SPOT_INSP_STATUS='A' OR SPOT_INSP_STATUS='D' OR "
		+"SPOT_INSP_STATUS='R' OR SPOT_INSP_STATUS='Y') AND REG_TXN_ID=";
	
	//public static final String SELECT_PARTY_DETAILS = "SELECT PARTY_FIRST_NAME, PARTY_MIDDLE_NAME, PARTY_LAST_NAME FROM IGRS_REG_INITN_TXN_PARTY_DTLS WHERE REG_TXN_ID=";
	
	public static final String SELECT_PARTY_DETAILS = "SELECT PARTY_FIRST_NAME, PARTY_MIDDLE_NAME, PARTY_LAST_NAME FROM IGRS_REG_INIT_TXN_PARTY_DTLS WHERE REG_TXN_ID=";
	public static final String SELECT_PAYMENT_DETAILS ="SELECT PM.CHALLAN_ONLINE_NUMBER,PM.CHALLAN_ONLINE_DATE,PM.NET_AMOUNT,B.BANK_NAME,B.BANK_ADDRESS  FROM IGRS_PAYMENT_TXN_DETAILS PT,IGRS_PAYMENT_MODE_DETAILS PM,IGRS_PAYMENT_TXN_MAP MP,IGRS_BANK_MASTER B WHERE PT.TRANSACTION_ID=MP.PAYMENT_TXN_ID AND MP.PAYMENT_MODE_TXN_ID=PM.TRANSACTION_ID AND PM.BANK_ID=B.BANK_ID AND PT.TRANSACTION_ID="; 
	    //"SELECT PM.CHALLAN_ONLINE_NUMBER,PM.CHALLAN_ONLINE_DATE,PM.NET_AMOUNT,PM.BANK_NAME,PM.BANK_ADDRESS  FROM IGRS_PAYMENT_TXN_DETAILS PT,IGRS_PAYMENT_MODE_DETAILS PM WHERE PT.PAY_MODE_TXN_ID=PM.TRANSACTION_ID AND PT.TRANSACTION_ID=";
	public static final String SELECT_SLOT_DETAILS = "SELECT SD.SLOT_TXN_ID,TO_CHAR(SD.SLOT_DATE,'dd/mm/yyyy'),TO_CHAR(SM.TIME_FROM,'HH24:MI')||' - '||TO_CHAR(SM.TIME_TO,'HH24:MI') FROM IGRS_REG_SLOT_BOOK_TXN_DTLS SD,IGRS_REG_SLOT_MASTER SM WHERE SD.SLOT_ID=SM.SLOT_ID AND SD.REG_TXN_ID=";
	public static final String SELECT_FORM_FIELDS = "SELECT AM.ATTRIBUTE_DATA_TYPE,DM.ATTRIBUTE_ID,LM.LABEL_NAME,AM.ATTRIBUTE_NAME FROM IGRS_DEED_FORM_LABEL_MAPPING DM,IGRS_FORM_LABEL_MASTER LM,IGRS_FORM_ATTRIBUTE_MASTER AM WHERE DM.LABEL_ID=LM.LABEL_ID AND DM.ATTRIBUTE_ID=AM.ATTRIBUTE_ID AND DM.DEED_TYPE_ID=";
	public static final String INSERT_DEED_DETAILS = "INSERT INTO IGRS_REG_COMP_DEED_DETAILS RD (RD.REG_DEED_TXN_ID,RD.REG_TXN_ID,RD.DEED_TYPE_ID,RD.DEED_EXECUTION_DATE,RD.DEED_PRESENTATION_DATE) VALUES (?,?,?,SYSDATE,SYSDATE)";
	public static final String INSERT_DEED_EXEM_DETAILS = "INSERT INTO IGRS_REG_COMP_DEED_EXEM_MAP EM (EM.REG_DEED_TXN_ID,EM.INSTRUMENT_ID,EM.EXEMPTION_ID) VALUES (?,?,?)";
	public static final String INSERT_DEED_ATTR_DETAILS = "INSERT INTO IGRS_REG_DEED_ATTR_MAP AM (AM.REG_DEED_TXN_ID,AM.ATTRIBUTE_ID,AM.ATTRIBUTE_VALUE) VALUES (?,?,?)";
	public static final String SELECT_REG_DEED_DETAIL = "SELECT REG_DEED_TXN_ID FROM  IGRS_REG_COMP_DEED_DETAILS WHERE REG_TXN_ID =?";
	public static final String SELECT_DEED_DETAILS = "SELECT RD.REG_TXN_ID,RD.DEED_TYPE_ID,DM.DEED_TYPE_NAME FROM IGRS_REG_COMP_DEED_DETAILS RD,IGRS_DEED_TYPE_MASTER DM WHERE RD.DEED_TYPE_ID=DM.DEED_TYPE_ID AND RD.REG_DEED_TXN_ID=";
	public static final String SELECT_DEED_EXEM_DETAILS = "SELECT EM.INSTRUMENT_ID,EM.EXEMPTION_ID FROM IGRS_REG_COMP_DEED_EXEM_MAP EM WHERE EM.REG_DEED_TXN_ID=";
	//public static final String SELECT_DEED_ATTR_DETAILS = "SELECT AM.ATTRIBUTE_ID,AM.ATTRIBUTE_VALUE FROM IGRS_REG_DEED_ATTR_MAP AM WHERE AM.REG_DEED_TXN_ID=";
	
	public static final String SELECT_DEED_ATTR_DETAILS = 
		"SELECT IGRS_FORM_LABEL_MASTER.LABEL_NAME," 
		+"IGRS_DEED_FORM_LABEL_MAPPING.ATTRIBUTE_ID,"
		+"IGRS_DEED_FORM_LABEL_MAPPING.ATTRIBUTE_SIZE, "
		+"IGRS_FORM_ATTRIBUTE_MASTER.ATTRIBUTE_DATA_TYPE,"
		+"IGRS_FORM_ATTRIBUTE_MASTER.ATTRIBUTE_NAME "
		+"FROM IGRS_FORM_ATTRIBUTE_MASTER,IGRS_FORM_LABEL_MASTER, "
		+"IGRS_DEED_FORM_LABEL_MAPPING WHERE "
		+"IGRS_FORM_ATTRIBUTE_MASTER.ATTRIBUTE_ID = "
        +"IGRS_DEED_FORM_LABEL_MAPPING.ATTRIBUTE_ID AND  "
        +"IGRS_FORM_LABEL_MASTER.LABEL_ID = "
        +"IGRS_DEED_FORM_LABEL_MAPPING.LABEL_ID  AND  "
        +"IGRS_FORM_ATTRIBUTE_MASTER.ATTRIBUTE_STATUS = 'A' "
        +"AND  IGRS_FORM_LABEL_MASTER.LABEL_STATUS = 'A' "
        +"AND IGRS_DEED_FORM_LABEL_MAPPING.DEED_TYPE_ID = ?";
	
	public static final String UPDATE_DEED_DETAILS = "UPDATE IGRS_REG_COMP_DEED_DETAILS RD SET RD.DEED_EXECUTION_DATE=SYSDATE,RD.DEED_PRESENTATION_DATE=SYSDATE WHERE RD.REG_DEED_TXN_ID=?";
	public static final String UPDATE_DEED_EXEM_DETAILS = "UPDATE IGRS_REG_COMP_DEED_EXEM_MAP EM  SET EM.INSTRUMENT_ID=?,EM.EXEMPTION_ID=? WHERE EM.REG_DEED_TXN_ID=?";
	public static final String UPDATE_DEED_ATTR_DETAILS = "UPDATE IGRS_REG_DEED_ATTR_MAP AM SET AM.ATTRIBUTE_ID=?,AM.ATTRIBUTE_VALUE=? WHERE AM.REG_DEED_TXN_ID=?";
	public static final String DELETE_DEED_ATTR_DETAILS = "DELETE IGRS_REG_DEED_ATTR_MAP WHERE REG_DEED_TXN_ID=?";
	public static final String DELETE_DEED_EXEM_DETAILS = "DELETE IGRS_REG_COMP_DEED_EXEM_MAP WHERE REG_DEED_TXN_ID=?";
	public static final String DELETE_DEED_DETAILS = "DELETE IGRS_REG_COMP_DEED_DETAILS WHERE REG_DEED_TXN_ID=?";
	
	public static final String SELECT_DEED_BY_REGID = "SELECT M.DEED_TYPE_ID, M.DEED_TYPE_NAME, CD.REG_DEED_TXN_ID FROM IGRS_REG_COMP_DEED_DETAILS CD,IGRS_DEED_TYPE_MASTER M WHERE M.DEED_TYPE_ID=CD.DEED_TYPE_ID AND CD.REG_TXN_ID=?";
	public static final String SELECT_PROP_BY_REGID_LIST = 
		"SELECT IP.PROPERTY_TXN_ID FROM IGRS_REG_PROPERTY_DETAILS "
		+"IP WHERE IP.REG_TXN_ID=?";
	public static final String SELECT_PROP_BY_REGID = 
		"SELECT DISTINCT C.PROPERTY_TXN_ID FROM "
		+"IGRS_REG_PROPERTY_DETAILS C, IGRS_REG_COMP_DEED_DETAILS B "
		+"WHERE B.REG_TXN_ID = C.REG_TXN_ID AND C.PROPERTY_TXN_ID NOT "
		+"IN (SELECT PROPERTY_TXN_ID FROM IGRS_REG_DEED_PROP_MAP "
		+"WHERE REG_DEED_TXN_ID =?) AND C.REG_TXN_ID=?";
	public static final String SELECT_PARTY_TYPE = 
		"SELECT IGRS_PARTY_TYPE_MASTER.PARTY_TYPE_NAME, "
		+"IGRS_PARTY_TYPE_DEED_MAP.PARTY_TYPE_ID,"
		+"IGRS_PARTY_TYPE_MASTER.OWNER_FLAG "
		+"FROM IGRS_REG_COMP_DEED_DETAILS, "
		+"IGRS_PARTY_TYPE_MASTER, IGRS_PARTY_TYPE_DEED_MAP,"
		+"IGRS_DEED_TYPE_MASTER WHERE "
		+"IGRS_PARTY_TYPE_MASTER.PARTY_TYPE_ID = "
		+"IGRS_PARTY_TYPE_DEED_MAP.PARTY_TYPE_ID AND "
		+"IGRS_DEED_TYPE_MASTER.DEED_TYPE_ID = "
		+"IGRS_PARTY_TYPE_DEED_MAP.DEED_TYPE_ID AND  "
		+"IGRS_DEED_TYPE_MASTER.DEED_TYPE_ID = "
		+"IGRS_REG_COMP_DEED_DETAILS.DEED_TYPE_ID AND "
		+"IGRS_REG_COMP_DEED_DETAILS.REG_TXN_ID =  ? AND "
		+"IGRS_REG_COMP_DEED_DETAILS.REG_DEED_TXN_ID =?";
	
	public static final String SELECT_NO_PROP_BY_DEED = "SELECT AP.ATTRIBUTE_VALUE FROM IGRS_REG_DEED_ATTR_MAP AP WHERE AP.ATTRIBUTE_ID=? AND AP.REG_DEED_TXN_ID=?";
	public static final String SELECT_PROP_DEED_ATTR = "SELECT ATTRIBUTE_VALUE FROM IGRS_CONFIG_PARAM_LIST WHERE ATTRIBUTE_ID = ? AND ATTRIBUTE_STATUS = ?";
	public static final String INSERT_DEED_PROP_WITH_REGID = "INSERT INTO IGRS_REG_DEED_PROP_MAP(REG_TXN_ID, REG_DEED_TXN_ID, PROPERTY_TXN_ID) VALUES   (?,?,?)";
	public static final String INSERT_DEED_TRAN_WITH_REGID = "INSERT INTO IGRS_REG_DEED_PROP_MAP(REG_TXN_ID, REG_DEED_TXN_ID, PARTY_TXN_ID) VALUES   (?,?,?)";
	public static final String SELECT_DEED_PROP_TAN_BY_REGID = "SELECT REG_TXN_ID, REG_DEED_TXN_ID, PROPERTY_TXN_ID,PARTY_TXN_ID FROM IGRS_REG_DEED_PROP_MAP WHERE REG_TXN_ID=?";
	/*public static final String SELECT_DEED_TAN_BY_REGID = "SELECT DISTINCT  REG_DEED_TXN_ID  FROM IGRS_REG_DEED_PROP_MAP WHERE REG_TXN_ID=?";*/
	
	public static final String SELECT_DEED_TAN_BY_REGID =
		       "  SELECT DISTINCT DPM.REG_DEED_TXN_ID,DTM.PROPERTY_RELATED_DEED" +
			   "  FROM IGRS_REG_DEED_PROP_MAP DPM,IGRS_DEED_TYPE_MASTER DTM,IGRS_REG_COMP_DEED_DETAILS RCDD "+
			   "  WHERE DTM.DEED_TYPE_ID=RCDD.DEED_TYPE_ID AND RCDD.REG_DEED_TXN_ID=DPM.REG_DEED_TXN_ID AND DPM.REG_TXN_ID=?";
	
	public static final String SELECT_PROP_TAN_BY_REGID = "SELECT  DISTINCT  PROPERTY_TXN_ID  FROM IGRS_REG_DEED_PROP_MAP WHERE REG_TXN_ID=? AND REG_DEED_TXN_ID=?";
	public static final String SELECT_PARTY_TAN_BY_REGID = "SELECT  DISTINCT  PARTY_TXN_ID FROM IGRS_REG_DEED_PROP_MAP WHERE REG_TXN_ID=? AND REG_DEED_TXN_ID=?";
	
	public static final String SELECT_PARTY_BY_REGID = "SELECT PARTY_TXN_ID FROM IGRS_REG_TXN_PARTY_DETAILS WHERE REG_TXN_ID=?";
	public static final String SELECT_DEED_BY_DEEDTXN_ID = "SELECT D.DEED_TYPE_ID FROM IGRS_REG_COMP_DEED_DETAILS D WHERE D.REG_DEED_TXN_ID=";
	public static final String SELECT_PARTY_BY_DEEDTXN_ID = "SELECT A.DEED_TYPE_NAME, B.PARTY_TYPE_NAME, B.PARTY_TYPE_ID FROM IGRS_DEED_TYPE_MASTER A, IGRS_PARTY_TYPE_MASTER B, IGRS_PARTY_TYPE_DEED_MAP C WHERE C.DEED_TYPE_ID=A.DEED_TYPE_ID AND C.PARTY_TYPE_ID=B.PARTY_TYPE_ID AND A.DEED_TYPE_ID=?";
	public static final String DELETE_DEED_MAP_BY_REGID = "DELETE IGRS_REG_DEED_PROP_MAP WHERE REG_TXN_ID=?";
	public static final String SAVE_MAPPING_DETAILS = "INSERT INTO IGRS_REG_DEED_PROP_MAP(REG_TXN_ID, REG_DEED_TXN_ID,PROPERTY_TXN_ID, PARTY_TXN_ID,PARTY_TYPE_ID) VALUES   (?,?,?,?,?)";
	
	/*public static final String SAVE_MAPPING_DETAILS = 
		"UPDATE IGRS_REG_DEED_PROP_MAP SET PARTY_TYPE_ID = ?, "
		+"PROPERTY_TXN_ID=? , PARTY_TXN_ID=? WHERE "
		+"REG_TXN_ID =? AND REG_DEED_TXN_ID=? AND "
		+"(PROPERTY_TXN_ID=? AND PARTY_TXN_ID=?)";*/
	
	public static final String SELECT_APPL_TYPE = "SELECT A.APPELLATE_TYPE_ID,A.APPELLATE_TYPE_NAME FROM IGRS_APPELLATE_TYPE_MASTER A WHERE A.APPELLATE_TYPE_STATUS='A' ORDER BY A.APPELLATE_TYPE_ID DESC";
	public static final String SELECT_COUNTRY = "SELECT C.COUNTRY_ID,C.COUNTRY_NAME FROM IGRS_COUNTRY_MASTER C WHERE C.COUNTRY_STATUS='A'";
	public static final String SELECT_STATE = "SELECT STATE_ID,STATE_NAME FROM IGRS_STATE_MASTER WHERE STATE_STATUS='A'";
	public static final String SELECT_DISTRICT = "SELECT DISTRICT_ID,DISTRICT_NAME FROM IGRS_DISTRICT_MASTER WHERE DISTRICT_STATUS='A'";
	public static final String SELECT_PHOTO_PROOF = "SELECT P.PHOTO_PROOF_TYPE_ID,P.PHOTO_PROOF_TYPE_NAME FROM IGRS_PHOTOID_PROOF_TYPE_MASTER P WHERE P.PHOTO_PROOF_TYPE_STATUS='A' ORDER BY P.PHOTO_PROOF_TYPE_ID ASC";
	public static final String SELECT_DEED_TYPE = "SELECT DEED_TYPE_ID,DEED_TYPE_NAME,PROPERTY_VAL_REQD,DUTY_CAL_REQD,PROPERTY_RELATED_DEED FROM IGRS_DEED_TYPE_MASTER WHERE DEED_STATUS='A'";
	//public static final String SELECT_DEED_TYPE_OPTIONAL = "SELECT DEED_TYPE_ID,DEED_TYPE_NAME,PROPERTY_VAL_REQD,DUTY_CAL_REQD,PROPERTY_RELATED_DEED FROM IGRS_DEED_TYPE_MASTER WHERE DEED_CATEGORY='O' AND DEED_STATUS='A'";
        public static final String SELECT_DEED_INSTRUMENT = "SELECT INSTRUMENT_ID,INSTRUMENT_NAME FROM IGRS_DEED_INSTRUMENT_MASTER WHERE INSTRUMENT_STATUS='A' AND DEED_TYPE_ID="; 
	public static final String SELECT_DEED_EXEMPTION = "SELECT EXEMPTION_ID,EXEMPTION_NAME FROM IGRS_DEED_EXEMPTION_MASTER WHERE EXEMPTION_STATUS='A' AND INSTRUMENT_ID=";
	public static final String SELECT_DEED_EXEMPTION_ONDEED = "SELECT EXEMPTION_ID,EXEMPTION_NAME FROM IGRS_DEED_EXEMPTION_MASTER WHERE EXEMPTION_STATUS='A' AND DEED_TYPE_ID=";
	public static final String SELECT_OTHER_FEE = "SELECT MP.PARAM_VALUE,MP.PARAM_TYPE,M.OPERATOR_NAME FROM IGRS_SERVICE_FEE_PARAM_MAPPING MP,IGRS_OPERATOR_MASTER M,IGRS_FUNCTION_MASTER F WHERE F.FUNCTION_ID=MP.FUNCTION_ID AND MP.OPERATOR_ID=M.OPERATOR_ID AND F.FUNCTION_ID=";
	public static final String INSERT_STAMP_DUTY = "INSERT INTO IGRS_ESTAMP_TXN_DETAILS (TRANSACTION_ID,ESTAMP_DUTY,ESTAMP_OTHER_FEES,ESTAMP_TOTAL,ESTAMP_STATUS,ESTAMP_PURPOSE,ESTAMP_DATE,ESTAMP_CODE) VALUES(?,?,?,?,'A',?,SYSDATE,?)";
	public static final String INSERT_REG_TXN = "INSERT INTO IGRS_REG_INITN_TXN_DETAILS IG (IG.TRANSACTION_ID,IG.ESTAMP_TXN_ID,IG.FUNCTION_ID,IG.APPLICATION_STATUS,IG.CREATED_BY,IG.CREATED_DATE) VALUES (?,?,?,'A','ADMIN',SYSDATE)";
	public static final String INSERT_REG_DEED = "INSERT INTO IGRS_REG_INITN_DEED_DETAILS ID (ID.REG_TXN_ID,ID.DEED_TYPE_ID,ID.INSTRUMENT_ID,ID.EXEMPTION_ID) VALUES (?,?,?,?)";
	public static final String INSERT_REG_DETAILS = "INSERT INTO IGRS_REG_COMPLETION_DETAILS (TRANSACTION_ID, REGISTRATION_ID,CREATED_BY, CREATED_DATE,REGISTRATION_STATUS, TOTAL_STAMP_DUTY,TOTAL_REG_FEE, PAYMENT_TXN_ID,TOTAL_FEE)VALUES(?,?,?,SYSDATE,?,?,?,?,?)";
	public static final String SELECT_USER_DIST_ID = "SELECT R.DISTRICT_ID FROM IGRS_USER_REG_DETAILS R,IGRS_USERS_LIST L WHERE L.USER_ID=R.USER_ID AND L.USER_ID=";
	public static final String SELECT_USER_OFFICE_ID = "SELECT R.OFFICE_ID FROM IGRS_USER_OFFICE_MAPPING R,IGRS_USERS_LIST L WHERE L.USER_ID=R.USER_ID AND L.USER_ID=";
	//public static final String UPDATE_REG_DETAILS = "UPDATE IGRS_REG_COMPLETION_DETAILS SET REGISTRATION_STATUS='REG_STAT_010' WHERE TRANSACTION_ID=";
	public static final String UPDATE_REG_DETAILS = "UPDATE IGRS_REG_COMPLETION_DETAILS SET REGISTRATION_STATUS=? WHERE TRANSACTION_ID=?";
	public static final String SELECT_REG_STATUS_ID = " SELECT REG_STATUS_ID FROM IGRS_REG_COMP_STATUS_MASTER WHERE REG_STATUS_NAME= ";
	public static final String UPDATE_DEED_DTS = " UPDATE IGRS_REG_COMP_DEED_DETAILS SET ROR_ID=? WHERE REG_DEED_TXN_ID=? ";
	public static final String ROR_SEQ_NUMBER = " SELECT ROR_SEQ.NEXTVAL FROM DUAL ";
	public static final String REG_INIT_DATE = " SELECT CREATED_DATE FROM IGRS_REG_INITN_TXN_DETAILS WHERE TRANSACTION_ID =? ";
	
	//from piyush data
    public static final String IGRS_COUNTRY_MASTER="SELECT COUNTRY_ID,COUNTRY_NAME FROM IGRS_COUNTRY_MASTER WHERE COUNTRY_STATUS='A'";
    public static final String IGRS_STATE_MASTER="SELECT STATE_ID,STATE_NAME FROM IGRS_STATE_MASTER WHERE COUNTRY_ID=? AND STATE_STATUS='A'";
    public static final String IGRS_DISTRICT_MASTER="SELECT DISTRICT_ID, DISTRICT_NAME FROM IGRS_DISTRICT_MASTER WHERE STATE_ID=? AND DISTRICT_STATUS='A'";
    public static final String IGRS_PHOTOID_PROOF_MASTER="SELECT PHOTO_PROOF_TYPE_ID,PHOTO_PROOF_TYPE_NAME FROM IGRS_PHOTOID_PROOF_TYPE_MASTER WHERE PHOTO_PROOF_TYPE_STATUS='A' ORDER BY PHOTO_PROOF_TYPE_NAME ";
    public static final String IGRS_CASTE_MASTER="SELECT CASTE_ID, CASTE_NAME FROM IGRS_CASTE_MASTER WHERE CASTE_STATUS='A' ORDER BY CASTE_NAME";
    public static final String IGRS_RELIGION_MASTER="SELECT RELIGION_ID, RELIGION_NAME FROM IGRS_RELIGION_MASTER WHERE RELIGION_STATUS='A' ORDER BY RELIGION_NAME";
    public static final String IGRS_REGCOMP_INSERT_PARTY="INSERT INTO IGRS_REG_TXN_PARTY_DETAILS (PARTY_TXN_ID,PARTY_TYPE_ID,PARTY_FIRST_NAME_H,PARTY_MIDDLE_NAME_H,PARTY_LAST_NAME_H,PARTY_GENDER,PARTY_AGE,NATIONALITY,COUNTRY_ID,STATE_ID,DISTRICT_ID,PARTY_ADDRESS,POSTAL_CODE,PHONE_NUMBER,MOBILE_NUMBER,EMAIL_ID,PHOTO_PROOF_TYPE_ID,PHOTO_PROOF_ID,BANK_NAME,BANK_ADDRESS,GUARDIAN_NAME,MOTHER_NAME,CASTE_ID,RELIGION_ID,ORGANIZATION_NAME,OCCUPATION,PHYSICALLY_CHALLENGED,REG_TXN_ID) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";    
    public static final String IGRS_REGCOMP_INSERT_ORGA_DETAILS="INSERT INTO IGRS_REG_TXN_PARTY_DETAILS (PARTY_TXN_ID,PARTY_TYPE_ID,ORGANIZATION_NAME,PARTY_FIRST_NAME_H,COUNTRY_ID,STATE_ID,DISTRICT_ID,PARTY_ADDRESS,POSTAL_CODE,PHONE_NUMBER,MOBILE_NUMBER,EMAIL_ID,REG_TXN_ID) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)";
    public static final String IGRS_REGCOMP_SELECT_PARTY_DETAILS=
    	"SELECT PARTY_TXN_ID,PARTY_FIRST_NAME_H,ORGANIZATION_NAME FROM IGRS_REG_TXN_PARTY_DETAILS WHERE REG_TXN_ID=?";
     
    public static final String IGRS_REGCOMP_SELECT_PARTY_LIST = 
    	"SELECT DISTINCT C.PARTY_TXN_ID,C.PARTY_FIRST_NAME_H,"
    	+"C.ORGANIZATION_NAME FROM IGRS_REG_TXN_PARTY_DETAILS C,"
    	+"IGRS_REG_COMP_DEED_DETAILS B WHERE B.REG_TXN_ID = C.REG_TXN_ID AND "
    	+"C.PARTY_TXN_ID NOT IN (SELECT PROPERTY_TXN_ID FROM "
    	+"IGRS_REG_DEED_PROP_MAP WHERE REG_DEED_TXN_ID =?) "
    	+"AND C.REG_TXN_ID=?";

    public static final String IGRS_REGCOMP_SELECT_VIEW_PARTY_DETAILS="SELECT PARTY_TXN_ID,PARTY_TYPE_ID,PARTY_FIRST_NAME_H,PARTY_MIDDLE_NAME_H,PARTY_LAST_NAME_H,PARTY_GENDER,PARTY_AGE,NATIONALITY,(SELECT COUNTRY_NAME FROM IGRS_COUNTRY_MASTER WHERE COUNTRY_ID=IGRS_REG_TXN_PARTY_DETAILS.COUNTRY_ID),(SELECT STATE_NAME FROM IGRS_STATE_MASTER WHERE STATE_ID=IGRS_REG_TXN_PARTY_DETAILS.STATE_ID),(SELECT DISTRICT_NAME FROM IGRS_DISTRICT_MASTER WHERE DISTRICT_ID=IGRS_REG_TXN_PARTY_DETAILS.DISTRICT_ID),PARTY_ADDRESS,POSTAL_CODE,PHONE_NUMBER,MOBILE_NUMBER,EMAIL_ID,(SELECT PHOTO_PROOF_TYPE_NAME FROM IGRS_PHOTOID_PROOF_TYPE_MASTER WHERE PHOTO_PROOF_TYPE_ID=IGRS_REG_TXN_PARTY_DETAILS.PHOTO_PROOF_TYPE_ID),PHOTO_PROOF_ID,BANK_NAME,BANK_ADDRESS,GUARDIAN_NAME,MOTHER_NAME,(SELECT CASTE_NAME FROM IGRS_CASTE_MASTER WHERE CASTE_ID=IGRS_REG_TXN_PARTY_DETAILS.CASTE_ID),(SELECT RELIGION_NAME FROM IGRS_RELIGION_MASTER WHERE RELIGION_ID=IGRS_REG_TXN_PARTY_DETAILS.RELIGION_ID),ORGANIZATION_NAME,OCCUPATION,PHYSICALLY_CHALLENGED FROM IGRS_REG_TXN_PARTY_DETAILS WHERE PARTY_TXN_ID=? ";
    public static final String IGRS_REGCOMP_RETRIEVE_PARTY_FOR_MODIFY_DETAILS="SELECT PARTY_TXN_ID,PARTY_TYPE_ID,PARTY_FIRST_NAME_H,PARTY_MIDDLE_NAME_H,PARTY_LAST_NAME_H,PARTY_GENDER,PARTY_AGE,NATIONALITY,COUNTRY_ID,STATE_ID,DISTRICT_ID,PARTY_ADDRESS,POSTAL_CODE,PHONE_NUMBER,MOBILE_NUMBER,EMAIL_ID,PHOTO_PROOF_TYPE_ID,PHOTO_PROOF_ID,BANK_NAME,BANK_ADDRESS,GUARDIAN_NAME,MOTHER_NAME,CASTE_ID,RELIGION_ID,ORGANIZATION_NAME,OCCUPATION,PHYSICALLY_CHALLENGED FROM IGRS_REG_TXN_PARTY_DETAILS WHERE PARTY_TXN_ID=? ";
    public static final String IGRS_REGCOMP_SELECT_DELETE_PARTY_DETAILS="DELETE FROM IGRS_REG_TXN_PARTY_DETAILS WHERE PARTY_TXN_ID=?";
    public static final String IGRS_REGCOMP_UPDATE_PARTY="UPDATE IGRS_REG_TXN_PARTY_DETAILS SET PARTY_FIRST_NAME_H=?,PARTY_MIDDLE_NAME_H=?,PARTY_LAST_NAME_H=?,PARTY_GENDER=?,PARTY_AGE=?,NATIONALITY=?,COUNTRY_ID=?,STATE_ID=?,DISTRICT_ID=?,PARTY_ADDRESS=?,POSTAL_CODE=?,PHONE_NUMBER=?,MOBILE_NUMBER=?,EMAIL_ID=?,PHOTO_PROOF_TYPE_ID=?,PHOTO_PROOF_ID=?,BANK_NAME=?,BANK_ADDRESS=?,GUARDIAN_NAME=?,MOTHER_NAME=?,CASTE_ID=?,RELIGION_ID=?,ORGANIZATION_NAME=?,OCCUPATION=?,PHYSICALLY_CHALLENGED=? WHERE PARTY_TXN_ID=?";
    public static final String IGRS_REGCOMP_UPDATE_ORGA="UPDATE IGRS_REG_TXN_PARTY_DETAILS SET PARTY_FIRST_NAME_H=?,COUNTRY_ID=?,STATE_ID=?,DISTRICT_ID=?,PARTY_ADDRESS=?,POSTAL_CODE=?,PHONE_NUMBER=?,MOBILE_NUMBER=?,EMAIL_ID=?,ORGANIZATION_NAME=? WHERE PARTY_TXN_ID=?";
	public static final String SELECT_DEED = "SELECT DEED_TYPE_ID,DEED_TYPE_NAME FROM IGRS_DEED_TYPE_MASTER WHERE DEED_STATUS='A' AND DEED_TYPE_ID=";
	public static final String COMPLIANCE_LIST_QUERY = "SELECT  COMPLIANCE_ID,COMPLAINCE_DESC  FROM IGRS_REG_COMPLIANCE_DETAILS ORDER BY COMPLIANCE_ID";
	public static final String COMPLIANCE_INS_QUERY = "INSERT INTO IGRS_REG_COMPLIANCE_TXN_DTLS(REG_TXN_ID,COMPLIANCE_ID,COMPLIANCE_STATUS,CREATED_BY,CREATED_DATE) VALUES (?,?,?,?,SYSDATE)";
	public static final String DEED_EXEM_LIST_QUERY = "SELECT  RD.DEED_TYPE_ID,RMAP.INSTRUMENT_ID," +
			"RMAP.EXEMPTION_ID FROM IGRS_REG_COMP_DEED_DETAILS RD,IGRS_REG_COMP_DEED_EXEM_MAP RMAP" +
			" WHERE RD.REG_DEED_TXN_ID = RMAP.REG_DEED_TXN_ID AND RD.REG_DEED_TXN_ID =";
	public static final String DEED_TYPE_LIST_QUERY = "SELECT  RD.DEED_TYPE_ID,DTM.DEED_TYPE_NAME FROM IGRS_REG_COMP_DEED_DETAILS RD," +
			"IGRS_DEED_TYPE_MASTER DTM WHERE RD.DEED_TYPE_ID = DTM.DEED_TYPE_ID  AND RD.REG_DEED_TXN_ID =";
	public static final String OLD_REG_IDS_INS_QUERY = "INSERT INTO IGRS_REG_COMP_OLD_REGID_MAP (OLD_REG_TXN_ID,NEW_REG_TXN_ID) VALUES(?,?)";
	// Edited By Aruna
	/*public static String PROP_DEED_LIST_QUERY = "SELECT RD.REG_TXN_ID,RD.REG_DEED_TXN_ID,RD.PROPERTY_TXN_ID,RD.PARTY_TXN_ID," +
			"RD.PARTY_TYPE_ID,RP.PARTY_FIRST_NAME_H,PMAS.PARTY_TYPE_NAME," +
			"RPD.PARTY_FIRST_NAME,RPD.PARTY_MIDDLE_NAME,RPD.PARTY_LAST_NAME FROM IGRS_REG_DEED_PROP_MAP RD,IGRS_REG_TXN_PARTY_DETAILS RP," +
			"IGRS_PARTY_TYPE_MASTER PMAS,IGRS_REG_INITN_TXN_PARTY_DTLS RPD WHERE RD.PARTY_TXN_ID = RP.PARTY_TXN_ID AND" +
			" RD.PARTY_TYPE_ID = PMAS.PARTY_TYPE_ID AND   RD.REG_TXN_ID =RPD.REG_TXN_ID AND  RD.REG_TXN_ID=";*/
	public static String PROP_DEED_LIST_QUERY = "SELECT RD.REG_TXN_ID,RD.REG_DEED_TXN_ID,RD.PROPERTY_TXN_ID,RD.PARTY_TXN_ID," +
	"RD.PARTY_TYPE_ID,RP.PARTY_FIRST_NAME_H,PMAS.PARTY_TYPE_NAME," +
	"RPD.PARTY_FIRST_NAME,RPD.PARTY_MIDDLE_NAME,RPD.PARTY_LAST_NAME,DTM.PROPERTY_RELATED_DEED,DTM.ROR_REQUIRED,DTM.DEED_TYPE_NAME  FROM IGRS_REG_DEED_PROP_MAP RD,IGRS_REG_TXN_PARTY_DETAILS RP," +
	"IGRS_PARTY_TYPE_MASTER PMAS,IGRS_REG_INITN_TXN_PARTY_DTLS RPD,IGRS_REG_COMP_DEED_DETAILS RCDD,IGRS_DEED_TYPE_MASTER DTM WHERE RD.PARTY_TXN_ID = RP.PARTY_TXN_ID AND" +
	" RD.PARTY_TYPE_ID = PMAS.PARTY_TYPE_ID AND   RD.REG_TXN_ID =RPD.REG_TXN_ID AND RD.REG_DEED_TXN_ID=RCDD.REG_DEED_TXN_ID AND RCDD.DEED_TYPE_ID=DTM.DEED_TYPE_ID AND  RD.REG_TXN_ID=";
	
	public static String INS_EXEM_LIST_QUERY="SELECT RMAP.INSTRUMENT_ID,RMAP.EXEMPTION_ID FROM  " +
			"IGRS_REG_COMP_DEED_EXEM_MAP RMAP WHERE RMAP.REG_DEED_TXN_ID=";
	public static final String SELECT_DUTY_PROP_DET = "SELECT  RPD.DISTRICT_ID,RPD.TEHSIL_ID," +
		"RPD.WARD_PATWARI_ID, RPD.MOHALLA_VILLAGE_ID FROM " +
		"IGRS_REG_PROPERTY_DETAILS RPD WHERE   RPD.PROPERTY_TXN_ID=";
	//property details insert queries
	public static final String INSERT_REG_PROPERTY_DETAILS = 
					"INSERT INTO  IGRS_REG_PROPERTY_DETAILS (" 
					+"PROPERTY_TYPE_ID,DISTRICT_ID,TEHSIL_ID,"
					+"WARD_PATWARI_ID,MOHALLA_VILLAGE_ID,"
					+"AREA_TYPE_ID,MUNCIPAL_BODY_TYPE_ID,"
					+"VIKAS_KHAND,RI_CIRCLE ,LAYOUT_DETAIL,"
					+"KHASRA_NUMBER,NAZOOL_SHEET_NUMBER,"
					+"RIN_PUSHTIKA_NUMBER,PROPERTY_ADDRESS,"
					+"EAST_BOUNDARY,WEST_BOUNDARY,NORTH_BOUNDARY,"
					+"SOUTH_BOUNDARY,PROPERTY_TXN_ID,UOM_ID,"
					+"PROPERTY_L1_ID,PROPERTY_L2_ID,TOTAL_AREA,"
					+"REG_TXN_ID) VALUES " 
					+"(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,"
					+"?,?,?,?,?,?)";
	public static final String INSERT_REG_PROPERTY_FLOOR_DTLS = 
					"INSERT INTO  IGRS_REG_PROPERTY_FLOOR_DTLS ("
					+"FLOOR_TXN_ID,PROPERTY_TXN_ID,FLOOR_ID,"
					+"TOTAL_AREA,CONSTRUCTED_AREA,PROPERTY_L1_ID,"
					+"PROPERTY_L2_ID) VALUES(?,?,?,?,?,?,?)";
	
	public static final String INSERT_REG_PROP_SUBCLAUSE_MAP = 
			"INSERT INTO  IGRS_REG_PROP_SUBCLAUSE_MAP (PROPERTY_TXN_ID,"
			+"SUBCLAUSE_ID,SUBCLAUSE_VALUE,FLOOR_TXN_ID) VALUES (?,?,?,?)";
	public static final String INSERT_REG_PROPERTY_VALUE_DTLS = 
			"INSERT INTO  IGRS_REG_PROPERTY_VALUE_DTLS( "
			+"PROPERTY_TXN_ID,FLOOR_TXN_ID,MARKET_VALUE,"
			+"CONSIDERATION_VALUE) VALUES (?,?,?,?)";
	public static final String SELECT_REG_PROPERTY_DETAILS="SELECT (SELECT DISTRICT_NAME FROM IGRS_DISTRICT_MASTER WHERE DISTRICT_STATUS='A' AND DISTRICT_ID= PROPDET.DISTRICT_ID) " +
	" DISTRICT_NAME, (SELECT  TEHSIL_NAME FROM IGRS_TEHSIL_MASTER WHERE TEHSIL_STATUS='A' AND  TEHSIL_ID=PROPDET.TEHSIL_ID) TEHSIL_NAME ," +
	"  (SELECT WARD_PATWARI_NAME FROM IGRS_WARD_PATWARI_MASTER WHERE  WARD_PATWARI_STATUS='A' AND  WARD_PATWARI_ID=PROPDET.WARD_PATWARI_ID) " +
	"  WARD_PATWARI_NAME ,  (SELECT  MOHALLA_VILLAGE_NAME FROM IGRS_MOHALLA_VILLAGE_MASTER WHERE MOHALLA_VILLAGE_STATUS='A' AND MOHALLA_VILLAGE_ID=" +
	"  PROPDET.MOHALLA_VILLAGE_ID) MOHALLA_VILLAGE_NAME,  (SELECT AREA_TYPE_NAME FROM IGRS_AREA_TYPE_MASTER WHERE AREA_TYPE_STATUS='A' AND AREA_TYPE_ID=PROPDET.AREA_TYPE_ID) AREA_TYPE_NAME," +
	"  (SELECT MUNICIPAL_BODY_NAME FROM IGRS_GOV_MUNICIPAL_BODY_MASTER WHERE MUNICIPAL_BODY_ID=PROPDET.MUNCIPAL_BODY_TYPE_ID)" +
	" MUNICIPAL_BODY_NAME, VIKAS_KHAND,  RI_CIRCLE,  LAYOUT_DETAIL,  KHASRA_NUMBER,  NAZOOL_SHEET_NUMBER,  RIN_PUSHTIKA_NUMBER,  PROPERTY_ADDRESS," +
	"  EAST_BOUNDARY ,  WEST_BOUNDARY,  NORTH_BOUNDARY,  SOUTH_BOUNDARY,  (SELECT PROPERTY_TYPE_L1_NAME  FROM IGRS_PROP_TYPE_L1_MASTER WHERE PROPERTY_TYPE_L1_ID=PROPDET.PROPERTY_L1_ID)" +
	"  PROPERTY_TYPE_L1_NAME,  (SELECT PROPERTY_TYPE_L2_NAME  FROM IGRS_PROP_TYPE_L2_MASTER WHERE PROPERTY_TYPE_L2_ID=PROPERTY_L2_ID) PROPERTY_TYPE_L2_NAME ,  TOTAL_AREA ,  DEED_TYPE_ID,  REG_TXN_ID  " +
	" FROM IGRS_REG_PROPERTY_DETAILS PROPDET WHERE PROPERTY_TXN_ID=";
	/*public static final String SELECT_REG_PROPERTY_DETAILS_TMP = 
		"SELECT (SELECT DISTRICT_NAME FROM IGRS_DISTRICT_MASTER "
		+"WHERE DISTRICT_STATUS='A' AND DISTRICT_ID= PROPDET.DISTRICT_ID) " 
		+" DISTRICT_NAME,DISTRICT_ID, (SELECT  TEHSIL_NAME FROM IGRS_TEHSIL_MASTER WHERE TEHSIL_STATUS='A' AND  TEHSIL_ID=PROPDET.TEHSIL_ID) TEHSIL_NAME ,TEHSIL_ID," +
     " (SELECT WARD_PATWARI_NAME FROM IGRS_WARD_PATWARI_MASTER WHERE  WARD_PATWARI_STATUS='A' AND  WARD_PATWARI_ID=PROPDET.WARD_PATWARI_ID) " +
    "  WARD_PATWARI_NAME ,WARD_PATWARI_ID,  (SELECT  MOHALLA_VILLAGE_NAME FROM IGRS_MOHALLA_VILLAGE_MASTER WHERE MOHALLA_VILLAGE_STATUS='A' AND MOHALLA_VILLAGE_ID=" +
   "   PROPDET.MOHALLA_VILLAGE_ID) MOHALLA_VILLAGE_NAME,MOHALLA_VILLAGE_ID,  (SELECT AREA_TYPE_NAME FROM IGRS_AREA_TYPE_MASTER WHERE AREA_TYPE_STATUS='A' AND AREA_TYPE_ID=PROPDET.AREA_TYPE_ID) AREA_TYPE_NAME,AREA_TYPE_ID," +
    "  (SELECT MUNICIPAL_BODY_NAME FROM IGRS_GOV_MUNICIPAL_BODY_MASTER WHERE MUNICIPAL_BODY_ID=PROPDET.MUNCIPAL_BODY_TYPE_ID)" +
   "  MUNICIPAL_BODY_NAME,MUNCIPAL_BODY_TYPE_ID, VIKAS_KHAND,  RI_CIRCLE,  LAYOUT_DETAIL,  KHASRA_NUMBER,  NAZOOL_SHEET_NUMBER,  RIN_PUSHTIKA_NUMBER,  PROPERTY_ADDRESS," +
    "  EAST_BOUNDARY ,  WEST_BOUNDARY,  NORTH_BOUNDARY,  SOUTH_BOUNDARY,  (SELECT PROPERTY_TYPE_L1_NAME  FROM IGRS_PROP_TYPE_L1_MASTER WHERE PROPERTY_TYPE_L1_ID=PROPDET.PROPERTY_L1_ID)" +
   "   PROPERTY_TYPE_L1_NAME,PROPERTY_L1_ID,  (SELECT PROPERTY_TYPE_L2_NAME  FROM IGRS_PROP_TYPE_L2_MASTER WHERE PROPERTY_TYPE_L2_ID=PROPDET.PROPERTY_L2_ID) PROPERTY_TYPE_L2_NAME ,PROPERTY_L2_ID,  TOTAL_AREA ,  DEED_TYPE_ID,  REG_TXN_ID, " +
   "  PROPERTY_TYPE_ID,(SELECT   PROPERTY_TYPE_NAME FROM IGRS_PROPERTY_TYPE_MASTER WHERE PROPERTY_TYPE_STATUS='A' AND  PROPERTY_TYPE_ID=PROPDET.PROPERTY_TYPE_ID) PROPERTY_TYPE_NAME "+
   "  FROM IGRS_REG_PROPERTY_DETAILS PROPDET WHERE PROPERTY_TXN_ID=";*/
	
	
	public static final String SELECT_PROPERTY_TYPE_ID = 
		"SELECT IGRS_PROPERTY_TYPE_MASTER.PROPERTY_TYPE_ID FROM "
        +"IGRS_AREA_TYPE_MASTER, IGRS_DISTRICT_MASTER,"
        +"IGRS_GOV_MUNICIPAL_BODY_MASTER, IGRS_MOHALLA_VILLAGE_MASTER, "
        +"IGRS_TEHSIL_MASTER,IGRS_WARD_PATWARI_MASTER, "
        +"IGRS_PROP_TYPE_L1_MASTER,IGRS_PROP_TYPE_L2_MASTER, " 
        +"IGRS_PROPERTY_TYPE_MASTER,IGRS_REG_PROPERTY_DETAILS "
        +"WHERE IGRS_DISTRICT_MASTER.DISTRICT_ID = "
        +"IGRS_REG_PROPERTY_DETAILS.DISTRICT_ID " 
		+"AND IGRS_GOV_MUNICIPAL_BODY_MASTER.MUNICIPAL_BODY_ID = "
		+"IGRS_REG_PROPERTY_DETAILS.MUNCIPAL_BODY_TYPE_ID " 
		+"AND IGRS_AREA_TYPE_MASTER.AREA_TYPE_ID = "
		+"IGRS_REG_PROPERTY_DETAILS.AREA_TYPE_ID " 
		+"AND IGRS_MOHALLA_VILLAGE_MASTER.MOHALLA_VILLAGE_ID = "
		+"IGRS_REG_PROPERTY_DETAILS.MOHALLA_VILLAGE_ID " 
		+"AND IGRS_TEHSIL_MASTER.TEHSIL_ID = "
		+"IGRS_REG_PROPERTY_DETAILS.TEHSIL_ID " 
		+"AND IGRS_WARD_PATWARI_MASTER.WARD_PATWARI_ID = "
		+"IGRS_REG_PROPERTY_DETAILS.WARD_PATWARI_ID " 
		+"AND IGRS_PROPERTY_TYPE_MASTER.PROPERTY_TYPE_ID = "
		+"IGRS_REG_PROPERTY_DETAILS.PROPERTY_TYPE_ID "
		+"AND IGRS_PROP_TYPE_L1_MASTER.PROPERTY_TYPE_L1_ID = "
		+"IGRS_REG_PROPERTY_DETAILS.PROPERTY_L1_ID "
		+"AND IGRS_PROP_TYPE_L2_MASTER.PROPERTY_TYPE_L2_ID(+) = "
		+"IGRS_REG_PROPERTY_DETAILS.PROPERTY_L2_ID "
		//+"AND IGRS_GOV_MUNICIPAL_BODY_MASTER.MUNICIPAL_BODY_STATUS='A' " 
		//+"AND IGRS_WARD_PATWARI_MASTER.WARD_PATWARI_STATUS = 'A' " 
		//+"AND IGRS_TEHSIL_MASTER.TEHSIL_STATUS = 'A' " 
		+"AND IGRS_REG_PROPERTY_DETAILS.PROPERTY_TXN_ID = ?";
	
	/*public static final String SELECT_REG_PROPERTY_DETAILS_TMP = 
		"SELECT IGRS_DISTRICT_MASTER.DISTRICT_NAME, "
		+"IGRS_TEHSIL_MASTER.TEHSIL_NAME,"
		+"IGRS_WARD_PATWARI_MASTER.WARD_PATWARI_NAME,"
		+"IGRS_MOHALLA_VILLAGE_MASTER.MOHALLA_VILLAGE_NAME,"
		+"IGRS_AREA_TYPE_MASTER.AREA_TYPE_NAME, "
		+"IGRS_GOV_MUNICIPAL_BODY_MASTER.MUNICIPAL_BODY_NAME,"
		+"IGRS_PROPERTY_TYPE_MASTER.PROPERTY_TYPE_NAME, "
		+"IGRS_PROP_TYPE_L1_MASTER.PROPERTY_TYPE_L1_NAME,"
		+"IGRS_PROP_TYPE_L2_MASTER.PROPERTY_TYPE_L2_NAME,"
		+"IGRS_REG_PROPERTY_DETAILS.VIKAS_KHAND, "
		+"IGRS_REG_PROPERTY_DETAILS.RI_CIRCLE,"
		+"IGRS_REG_PROPERTY_DETAILS.LAYOUT_DETAIL, "
		+"IGRS_REG_PROPERTY_DETAILS.KHASRA_NUMBER, "
		+"IGRS_REG_PROPERTY_DETAILS.NAZOOL_SHEET_NUMBER, "
		+"IGRS_REG_PROPERTY_DETAILS.RIN_PUSHTIKA_NUMBER, "
		+"IGRS_REG_PROPERTY_DETAILS.PROPERTY_ADDRESS, "
		+"IGRS_REG_PROPERTY_DETAILS.EAST_BOUNDARY, "
		+"IGRS_REG_PROPERTY_DETAILS.WEST_BOUNDARY, "
		+"IGRS_REG_PROPERTY_DETAILS.NORTH_BOUNDARY, "
        +"IGRS_REG_PROPERTY_DETAILS.SOUTH_BOUNDARY, "
        +"IGRS_REG_PROPERTY_DETAILS.TOTAL_AREA, "
        +"IGRS_REG_PROPERTY_DETAILS.PROPERTY_TXN_ID, "
        +"IGRS_PROPERTY_TYPE_MASTER.PROPERTY_TYPE_ID,"
        +"IGRS_DISTRICT_MASTER.DISTRICT_ID," 
        +"IGRS_REG_PROPERTY_DETAILS.MUNCIPAL_BODY_TYPE_ID,"
        +"IGRS_AREA_TYPE_MASTER.AREA_TYPE_ID FROM "
        +"IGRS_AREA_TYPE_MASTER, IGRS_DISTRICT_MASTER,"
        +"IGRS_GOV_MUNICIPAL_BODY_MASTER, IGRS_MOHALLA_VILLAGE_MASTER, "
        +"IGRS_TEHSIL_MASTER,IGRS_WARD_PATWARI_MASTER, "
        +"IGRS_PROP_TYPE_L1_MASTER,IGRS_PROP_TYPE_L2_MASTER, " 
        +"IGRS_PROPERTY_TYPE_MASTER,IGRS_REG_PROPERTY_DETAILS "
        +"WHERE IGRS_DISTRICT_MASTER.DISTRICT_ID = "
        +"IGRS_REG_PROPERTY_DETAILS.DISTRICT_ID " 
		+"AND IGRS_GOV_MUNICIPAL_BODY_MASTER.MUNICIPAL_BODY_ID = "
		+"IGRS_REG_PROPERTY_DETAILS.MUNCIPAL_BODY_TYPE_ID " 
		+"AND IGRS_AREA_TYPE_MASTER.AREA_TYPE_ID = "
		+"IGRS_REG_PROPERTY_DETAILS.AREA_TYPE_ID " 
		+"AND IGRS_MOHALLA_VILLAGE_MASTER.MOHALLA_VILLAGE_ID = "
		+"IGRS_REG_PROPERTY_DETAILS.MOHALLA_VILLAGE_ID " 
		+"AND IGRS_TEHSIL_MASTER.TEHSIL_ID = "
		+"IGRS_REG_PROPERTY_DETAILS.TEHSIL_ID " 
		+"AND IGRS_WARD_PATWARI_MASTER.WARD_PATWARI_ID = "
		+"IGRS_REG_PROPERTY_DETAILS.WARD_PATWARI_ID " 
		+"AND IGRS_PROPERTY_TYPE_MASTER.PROPERTY_TYPE_ID = "
		+"IGRS_REG_PROPERTY_DETAILS.PROPERTY_TYPE_ID "
		+"AND IGRS_PROP_TYPE_L1_MASTER.PROPERTY_TYPE_L1_ID = "
		+"IGRS_REG_PROPERTY_DETAILS.PROPERTY_L1_ID "
		+"AND IGRS_PROP_TYPE_L2_MASTER.PROPERTY_TYPE_L2_ID(+) = "
		+"IGRS_REG_PROPERTY_DETAILS.PROPERTY_L2_ID "
		+"AND IGRS_GOV_MUNICIPAL_BODY_MASTER.MUNICIPAL_BODY_STATUS='A' " 
		+"AND IGRS_WARD_PATWARI_MASTER.WARD_PATWARI_STATUS = 'A' " 
		+"AND IGRS_TEHSIL_MASTER.TEHSIL_STATUS = 'A' " 
		+"AND IGRS_REG_PROPERTY_DETAILS.PROPERTY_TXN_ID = ?";*/
	
	/*public static final String SELECT_REG_PROPERTY_DETAILS_TMP = 
		    "SELECT IGRS_DISTRICT_MASTER.DISTRICT_NAME, "
		    +"nvl(IGRS_TEHSIL_MASTER.TEHSIL_NAME,'NA'), "
			+"nvl(IGRS_WARD_PATWARI_MASTER.WARD_PATWARI_NAME,'NA'), "
			+"nvl(IGRS_MOHALLA_VILLAGE_MASTER.MOHALLA_VILLAGE_NAME,'NA'), "
			+"nvl(IGRS_AREA_TYPE_MASTER.AREA_TYPE_NAME,'NA'),  "
			+"nvl(IGRS_GOV_MUNICIPAL_BODY_MASTER.MUNICIPAL_BODY_NAME,'NA'), "
			+"nvl(IGRS_PROPERTY_TYPE_MASTER.PROPERTY_TYPE_NAME,'NA'),  "
			+"nvl(IGRS_PROP_TYPE_L1_MASTER.PROPERTY_TYPE_L1_NAME,'NA'), "
			+"nvl(IGRS_PROP_TYPE_L2_MASTER.PROPERTY_TYPE_L2_NAME,'NA'), "
			+"nvl(IGRS_REG_PROPERTY_DETAILS.VIKAS_KHAND,'NA'),  "
			+"nvl(IGRS_REG_PROPERTY_DETAILS.RI_CIRCLE,'NA'), "
			+"nvl(IGRS_REG_PROPERTY_DETAILS.LAYOUT_DETAIL,'NA'),  "
			+"nvl(IGRS_REG_PROPERTY_DETAILS.KHASRA_NUMBER,'NA'), "
			+"nvl(IGRS_REG_PROPERTY_DETAILS.NAZOOL_SHEET_NUMBER,'NA'), " 
			+"nvl(IGRS_REG_PROPERTY_DETAILS.RIN_PUSHTIKA_NUMBER,'NA'),  "
			+"nvl(IGRS_REG_PROPERTY_DETAILS.PROPERTY_ADDRESS,'NA'),  "
			+"nvl(IGRS_REG_PROPERTY_DETAILS.EAST_BOUNDARY,'NA'),  "
			+"nvl(IGRS_REG_PROPERTY_DETAILS.WEST_BOUNDARY,'NA'),  "
			+"nvl(IGRS_REG_PROPERTY_DETAILS.NORTH_BOUNDARY,'NA'),  "
	        +"nvl(IGRS_REG_PROPERTY_DETAILS.SOUTH_BOUNDARY,'NA'),  "
	        +"nvl(IGRS_REG_PROPERTY_DETAILS.TOTAL_AREA,0),  "
	        +"nvl(IGRS_REG_PROPERTY_DETAILS.PROPERTY_TXN_ID,'NA'), " 
	        +"nvl(IGRS_PROPERTY_TYPE_MASTER.PROPERTY_TYPE_ID,'NA'), "
	        +"nvl(IGRS_DISTRICT_MASTER.DISTRICT_ID,'NA'),  "
	        +"nvl(IGRS_REG_PROPERTY_DETAILS.MUNCIPAL_BODY_TYPE_ID,'NA'), "
	        +"nvl(IGRS_AREA_TYPE_MASTER.AREA_TYPE_ID,'NA'), "
		    +"nvl(IGRS_REG_PROPERTY_DETAILS.TEHSIL_ID,'NA'),  "
	        +"nvl(IGRS_WARD_PATWARI_MASTER.WARD_OR_PATWARI,'NA'), "
	        +"nvl(IGRS_REG_PROPERTY_DETAILS.WARD_PATWARI_ID,'NA'),  "
	        +"nvl(IGRS_REG_PROPERTY_DETAILS.MOHALLA_VILLAGE_ID ,'NA') "
			+"FROM "
	        +"IGRS_AREA_TYPE_MASTER, IGRS_DISTRICT_MASTER,"
	        +"IGRS_GOV_MUNICIPAL_BODY_MASTER, IGRS_MOHALLA_VILLAGE_MASTER, "
	        +"IGRS_TEHSIL_MASTER,IGRS_WARD_PATWARI_MASTER, "
	        +"IGRS_PROP_TYPE_L1_MASTER,IGRS_PROP_TYPE_L2_MASTER, " 
	        +"IGRS_PROPERTY_TYPE_MASTER,IGRS_REG_PROPERTY_DETAILS "
	        +"WHERE IGRS_DISTRICT_MASTER.DISTRICT_ID = "
	        +"IGRS_REG_PROPERTY_DETAILS.DISTRICT_ID " 
			+"AND IGRS_GOV_MUNICIPAL_BODY_MASTER.MUNICIPAL_BODY_ID = "
			+"IGRS_REG_PROPERTY_DETAILS.MUNCIPAL_BODY_TYPE_ID " 
			+"AND IGRS_AREA_TYPE_MASTER.AREA_TYPE_ID = "
			+"IGRS_REG_PROPERTY_DETAILS.AREA_TYPE_ID " 
			+"AND IGRS_MOHALLA_VILLAGE_MASTER.MOHALLA_VILLAGE_ID = "
			+"IGRS_REG_PROPERTY_DETAILS.MOHALLA_VILLAGE_ID " 
			+"AND IGRS_TEHSIL_MASTER.TEHSIL_ID = "
			+"IGRS_REG_PROPERTY_DETAILS.TEHSIL_ID " 
			+"AND IGRS_WARD_PATWARI_MASTER.WARD_PATWARI_ID = "
			+"IGRS_REG_PROPERTY_DETAILS.WARD_PATWARI_ID " 
			+"AND IGRS_PROPERTY_TYPE_MASTER.PROPERTY_TYPE_ID = "
			+"IGRS_REG_PROPERTY_DETAILS.PROPERTY_TYPE_ID "
			+"AND IGRS_PROP_TYPE_L1_MASTER.PROPERTY_TYPE_L1_ID = "
			+"IGRS_REG_PROPERTY_DETAILS.PROPERTY_L1_ID "
			+"AND IGRS_PROP_TYPE_L2_MASTER.PROPERTY_TYPE_L2_ID(+) = "
			+"IGRS_REG_PROPERTY_DETAILS.PROPERTY_L2_ID "
			//+"AND IGRS_GOV_MUNICIPAL_BODY_MASTER.MUNICIPAL_BODY_STATUS='A' " 
			//+"AND IGRS_WARD_PATWARI_MASTER.WARD_PATWARI_STATUS = 'A' " 
			//+"AND IGRS_TEHSIL_MASTER.TEHSIL_STATUS = 'A' " 
			+"AND IGRS_REG_PROPERTY_DETAILS.PROPERTY_TXN_ID = ?";*/
	
	public static final String SELECT_REG_PROPERTY_DETAILS_TMP =" SELECT IGRS_DISTRICT_MASTER.DISTRICT_NAME,    nvl(IGRS_TEHSIL_MASTER.TEHSIL_NAME,'NA'),   "+
 " nvl(IGRS_WARD_PATWARI_MASTER.WARD_PATWARI_NAME,'NA'),     nvl(IGRS_MOHALLA_VILLAGE_MASTER.MOHALLA_VILLAGE_NAME,'NA'),     "+
  " nvl(IGRS_AREA_TYPE_MASTER.AREA_TYPE_NAME,'NA'),     nvl(IGRS_GOV_MUNICIPAL_BODY_MASTER.MUNICIPAL_BODY_NAME,'NA'),   "+
   " nvl(IGRS_PROPERTY_TYPE_MASTER.PROPERTY_TYPE_NAME,'NA'),      nvl(IGRS_PROP_TYPE_L1_MASTER.PROPERTY_TYPE_L1_NAME,'NA'), "+   
	"  nvl(IGRS_PROP_TYPE_L2_MASTER.PROPERTY_TYPE_L2_NAME,'NA'),     nvl(IGRS_REG_PROPRTY_DTLS.VIKAS_KHAND,'NA'),   "+
	 "   nvl(IGRS_REG_PROPRTY_DTLS.RI_CIRCLE,'NA'),     nvl(IGRS_REG_PROPRTY_DTLS.LAYOUT_DETAIL,'NA'),   "+
		"     nvl(IGRS_REG_PROPRTY_DTLS.NAZOOL_SHEET_NUMBER,'NA'),  "+
		 " 		     nvl(IGRS_REG_PROPRTY_DTLS.PROPERTY_ADDRESS,'NA'), "+  
			"		     nvl(IGRS_REG_PROPRTY_DTLS.EAST_BOUNDARY,'NA'),      nvl(IGRS_REG_PROPRTY_DTLS.WEST_BOUNDARY,'NA'),   "+
			"			   nvl(IGRS_REG_PROPRTY_DTLS.NORTH_BOUNDARY,'NA'),     nvl(IGRS_REG_PROPRTY_DTLS.SOUTH_BOUNDARY,'NA'),   "+
			"			     nvl(IGRS_REG_PROPRTY_DTLS.AREA,0),    nvl(IGRS_REG_PROPRTY_DTLS.PROPERTY_ID,'0'),    "+
			"				  nvl(IGRS_REG_PROPRTY_DTLS.PROP_TYPE_ID,0),      nvl(IGRS_DISTRICT_MASTER.DISTRICT_ID,0), "+  
			"				      nvl(IGRS_REG_PROPRTY_DTLS.GOV_BODY_ID,'0'),     nvl(IGRS_AREA_TYPE_MASTER.AREA_TYPE_ID,0),  "+
			"					     nvl(IGRS_REG_PROPRTY_DTLS.TEHSIL_ID,0),     nvl(IGRS_WARD_PATWARI_MASTER.WARD_OR_PATWARI,'NA'),   "+
			"						   nvl(IGRS_REG_PROPRTY_DTLS.WARD_ID,'0'),     nvl(IGRS_REG_PROPRTY_DTLS.MOHALLA_ID ,'0')    "+
			"						    FROM IGRS_AREA_TYPE_MASTER, IGRS_DISTRICT_MASTER,IGRS_GOV_MUNICIPAL_BODY_MASTER,     "+
			"							IGRS_MOHALLA_VILLAGE_MASTER, IGRS_TEHSIL_MASTER,     IGRS_WARD_PATWARI_MASTER, "+
			"							IGRS_PROP_TYPE_L1_MASTER,IGRS_PROP_TYPE_L2_MASTER,   "+
			"							  IGRS_PROPERTY_TYPE_MASTER,IGRS_REG_PROPRTY_DTLS    WHERE "+    
" IGRS_REG_PROPRTY_DTLS .PROPERTY_ID = ? AND ROWNUM<2 " ;
 
	/*public static final String SELECT_REG_PROPERTY_FLOOR_DTLS="SELECT FLOOR_ID,(SELECT FLOOR_NAME FROM IGRS_FLOOR_MASTER where FLOOR_STATUS='A' and FLOOR_ID=FDTL.FLOOR_ID) FLOOR_NAME,(SELECT FLOOR_DESC FROM IGRS_FLOOR_MASTER where FLOOR_STATUS='A' and FLOOR_ID=FDTL.FLOOR_ID) FLOOR_DESC,TOTAL_AREA,CONSTRUCTED_AREA,(SELECT PROPERTY_TYPE_L1_NAME  FROM IGRS_PROP_TYPE_L1_MASTER WHERE PROPERTY_TYPE_L1_ID=FDTL.PROPERTY_L1_ID) PROPERTY_TYPE_L1_NAME,PROPERTY_L1_ID, " +
		" (SELECT PROPERTY_TYPE_L2_NAME  FROM IGRS_PROP_TYPE_L2_MASTER WHERE PROPERTY_TYPE_L2_ID=FDTL.PROPERTY_L2_ID) PROPERTY_TYPE_L2_NAME,PROPERTY_L2_ID,(SELECT PROPERTY_TYPE_L2_DESC  FROM IGRS_PROP_TYPE_L2_MASTER WHERE PROPERTY_TYPE_L2_ID=FDTL.PROPERTY_L2_ID) PROPERTY_TYPE_L2_DESC,(SELECT FLOOR_TXN_ID FROM IGRS_FLOOR_MASTER where FLOOR_STATUS='A' and FLOOR_ID=FDTL.FLOOR_ID) FLOOR_TXN_ID,(SELECT PROPERTY_TYPE_L1_DESC  FROM IGRS_PROP_TYPE_L1_MASTER WHERE PROPERTY_TYPE_L1_ID=FDTL.PROPERTY_L1_ID) PROPERTY_TYPE_L1_DESC FROM IGRS_REG_PROPERTY_FLOOR_DTLS FDTL WHERE ";*/
	
	public static final String SELECT_REG_PROPERTY_FLOOR_DTLS = 
		"SELECT  nvl(IGRS_REG_PROPERTY_FLOOR_DTLS.FLOOR_TXN_ID,'NA') , "
		+"nvl(IGRS_FLOOR_MASTER.FLOOR_NAME,'NA') , "
		+"nvl(IGRS_REG_PROPERTY_FLOOR_DTLS.TOTAL_AREA,0) , "
		+"nvl(IGRS_REG_PROPERTY_FLOOR_DTLS.CONSTRUCTED_AREA,0) , "
		+"nvl(IGRS_PROP_TYPE_L1_MASTER.PROPERTY_TYPE_L1_NAME,'NA') ,  "
		+"nvl(IGRS_PROP_TYPE_L2_MASTER.PROPERTY_TYPE_L2_NAME,'NA') ,  "
		+"nvl(IGRS_REG_PROPERTY_VALUE_DTLS.MARKET_VALUE,0) ,  "
		+"nvl(IGRS_REG_PROPERTY_VALUE_DTLS.CONSIDERATION_VALUE,0)  "			
		+"FROM "
		+"IGRS_FLOOR_MASTER, IGRS_REG_PROPERTY_FLOOR_DTLS, "
		+"IGRS_REG_PROPERTY_DETAILS, IGRS_PROP_TYPE_L1_MASTER, "
		+"IGRS_PROP_TYPE_L2_MASTER,IGRS_REG_PROPERTY_VALUE_DTLS WHERE "
		+"IGRS_REG_PROPERTY_FLOOR_DTLS.FLOOR_ID = IGRS_FLOOR_MASTER.FLOOR_ID "
		+"AND  IGRS_REG_PROPERTY_VALUE_DTLS.FLOOR_TXN_ID  = "
		+"IGRS_REG_PROPERTY_FLOOR_DTLS.FLOOR_TXN_ID AND  "
		+"IGRS_REG_PROPERTY_FLOOR_DTLS.PROPERTY_L1_ID = "
		+"IGRS_PROP_TYPE_L1_MASTER.PROPERTY_TYPE_L1_ID "
		+"AND  IGRS_REG_PROPERTY_FLOOR_DTLS.PROPERTY_L2_ID = "
		+"IGRS_PROP_TYPE_L2_MASTER.PROPERTY_TYPE_L2_ID(+) AND "
		+"IGRS_REG_PROPERTY_FLOOR_DTLS.PROPERTY_TXN_ID = "
		+"IGRS_REG_PROPERTY_DETAILS.PROPERTY_TXN_ID AND "
		+"IGRS_REG_PROPERTY_FLOOR_DTLS.PROPERTY_TXN_ID =  ? "
		+"AND IGRS_REG_PROPERTY_FLOOR_DTLS.FLOOR_TXN_ID = ? "
		+"AND IGRS_FLOOR_MASTER.FLOOR_STATUS = 'A'";

	public static final String SELECT_REG_PROPERTY_SUBCLAUSE_FLOOR_MAP = 
		"SELECT IGRS_SUB_CLAUSE_MASTER.SUB_CLAUSE_NAME "
		+" FROM IGRS_SUB_CLAUSE_MASTER, IGRS_REG_PROP_SUBCLAUSE_MAP "
		+" WHERE ((IGRS_SUB_CLAUSE_MASTER.SUB_CLAUSE_ID = "
		+"  IGRS_REG_PROP_SUBCLAUSE_MAP.SUBCLAUSE_ID) AND "
		+"((IGRS_SUB_CLAUSE_MASTER.SUB_CLAUSE_STATUS = 'A')) AND "
		+"((IGRS_REG_PROP_SUBCLAUSE_MAP.FLOOR_TXN_ID = ?)) AND "
		+"((IGRS_REG_PROP_SUBCLAUSE_MAP.PROPERTY_TXN_ID = ?)))";
	
	public static final String SELECT_REG_PROP_SUBCLAUSE_MAP = 
		"SELECT IGRS_SUB_CLAUSE_MASTER.SUB_CLAUSE_NAME "
		+" FROM IGRS_SUB_CLAUSE_MASTER, IGRS_REG_PROP_SUBCLAUSE_MAP "
		+" WHERE ((IGRS_SUB_CLAUSE_MASTER.SUB_CLAUSE_ID = "
		+"  IGRS_REG_PROP_SUBCLAUSE_MAP.SUBCLAUSE_ID) AND "
		+"((IGRS_SUB_CLAUSE_MASTER.SUB_CLAUSE_STATUS = 'A')) AND "
		+"((IGRS_REG_PROP_SUBCLAUSE_MAP.PROPERTY_TXN_ID = ?)))";
	
	
	//public static final String SELECT_REG_PROP_SUBCLAUSE_MAP="SELECT (SELECT SUB_CLAUSE_NAME FROM IGRS_SUB_CLAUSE_MASTER WHERE SUB_CLAUSE_ID=SUBMAP.SUBCLAUSE_ID) SUB_CLAUSE_NAME,SUBMAP.SUBCLAUSE_ID FROM IGRS_REG_PROP_SUBCLAUSE_MAP SUBMAP WHERE "; //";
	public static final String SELECT_REG_PROPERTY_VALUE_DTLS = 
		"SELECT nvl(MARKET_VALUE,'0'),nvl(CONSIDERATION_VALUE,'0'),nvl(FLOOR_TXN_ID,'NA') FROM "
		+"IGRS_REG_PROPERTY_VALUE_DTLS WHERE  PROPERTY_TXN_ID=?";
	
	// Edited By Aruna
	/*public static final String SELECT_REG_PROPERTY_FLOORID_DTLS = 
		"SELECT FLOOR_TXN_ID FROM "
		+"IGRS_REG_PROPERTY_VALUE_DTLS WHERE  PROPERTY_TXN_ID=?";*/
	public static final String SELECT_REG_PROPERTY_FLOORID_DTLS = 
		"SELECT FLOOR_TXN_ID,MARKET_VALUE,CONSIDERATION_VALUE FROM "
		+"IGRS_REG_PROPERTY_VALUE_DTLS WHERE  PROPERTY_TXN_ID=?";
	
	public static final String UPDATE_REG_PROPERTY_DETAILS = 
		"UPDATE IGRS_REG_PROPERTY_DETAILS SET " 
		+"DISTRICT_ID=?, TEHSIL_ID =?, WARD_PATWARI_ID=?,  "
		+"MOHALLA_VILLAGE_ID=?,AREA_TYPE_ID=?,  MUNCIPAL_BODY_TYPE_ID=?, "
		+"VIKAS_KHAND=?, RI_CIRCLE=?,  LAYOUT_DETAIL=?, KHASRA_NUMBER=?," 
		+"NAZOOL_SHEET_NUMBER=?, RIN_PUSHTIKA_NUMBER=?,PROPERTY_ADDRESS=?, "
		+"EAST_BOUNDARY=?, WEST_BOUNDARY=?, NORTH_BOUNDARY=?, "
		+"SOUTH_BOUNDARY=?,PROPERTY_L1_ID=?,PROPERTY_L2_ID=?, TOTAL_AREA=?" 
		+" WHERE PROPERTY_TXN_ID=? AND REG_TXN_ID=?";
	
	public static final String UPDATE_REG_PROPERTY_FLOOR_DTLS="UPDATE IGRS_REG_PROPERTY_FLOOR_DTLS SET FLOOR_ID=?,TOTAL_AREA=?,CONSTRUCTED_AREA=?,PROPERTY_L1_ID=?,PROPERTY_L2_ID=?   WHERE  PROPERTY_TXN_ID=?  AND FLOOR_TXN_ID=?";
	public static final String UPDATE_REG_PROP_SUBCLAUSE_MAP="UPDATE IGRS_REG_PROP_SUBCLAUSE_MAP SET  SUBCLAUSE_ID=?  WHERE PROPERTY_TXN_ID=?";// AND FLOOR_TXN_ID=?";
	public static final String UPDATE_REG_PROP_FLR_SUBCLAUSE_MAP="UPDATE IGRS_REG_PROP_SUBCLAUSE_MAP SET  SUBCLAUSE_ID=?  WHERE PROPERTY_TXN_ID=? AND FLOOR_TXN_ID=?";
	public static final String UPDATE_REG_PROPERTY_VALUE_DTLS="UPDATE IGRS_REG_PROPERTY_VALUE_DTLS SET   MARKET_VALUE=?,CONSIDERATION_VALUE=?   WHERE  PROPERTY_TXN_ID=? ";
	public static final String UPDATE_REG_PROPERTY_FLR_VALUE_DTLS="UPDATE IGRS_REG_PROPERTY_VALUE_DTLS SET   MARKET_VALUE=?,CONSIDERATION_VALUE=?   WHERE  PROPERTY_TXN_ID=? AND FLOOR_TXN_ID=?";
	public static final String DELETE_REG_PROPERTY_DETAILS="DELETE FROM IGRS_REG_PROPERTY_DETAILS PROPDET WHERE PROPERTY_TXN_ID=?";
	public static final String DELETE_REG_PROPERTY_FLOOR_DTLS="DELETE FROM IGRS_REG_PROPERTY_FLOOR_DTLS WHERE  PROPERTY_TXN_ID=? ";
	public static final String DELETE_REG_PROP_SUBCLAUSE_MAP="DELETE FROM IGRS_REG_PROP_SUBCLAUSE_MAP WHERE PROPERTY_TXN_ID=?";
	public static final String DELETE_REG_PROPERTY_VALUE_DTLS="DELETE FROM IGRS_REG_PROPERTY_VALUE_DTLS WHERE  PROPERTY_TXN_ID=?";
	public static final String SELECT_DUTY_PAID = "SELECT PT.AMOUNT_PAID  FROM IGRS_REG_INITN_TXN_DETAILS RI," +
			"IGRS_ESTAMP_TXN_DETAILS ET,IGRS_PAYMENT_TXN_DETAILS PT WHERE  RI.ESTAMP_TXN_ID = ET.TRANSACTION_ID " +
			"AND ET.PAYMENT_TXN_ID = PT.TRANSACTION_ID AND RI.TRANSACTION_ID =";
	
	public static final String IGRS_REG_PIN_VERIFY_PROC = 
			"IGRS_REG_PIN_VERIFY_PROC(?,?,?,?,?,?,?,?,?)";
	
	public static final String GET_COMPLETE_DEED_DTLS =" SELECT DIM1.INSTRUMENT_NAME"
														  +" FROM  IGRS_REG_COMP_DEED_EXEM_MAP DIE1,"														
														  +" IGRS_DEED_INSTRUMENT_MASTER DIM1"
														  +" WHERE"
														  +" DIE1.INSTRUMENT_ID=DIM1.INSTRUMENT_ID AND"														 
														  +" DIE1.REG_DEED_TXN_ID=?"
														  +" UNION "
														  +" SELECT DEM1.EXEMPTION_NAME"
														  +" FROM  IGRS_REG_COMP_DEED_EXEM_MAP DIE1,"														
														  +" IGRS_DEED_EXEMPTION_MASTER DEM1"
														  +" WHERE"
														  +" DIE1.EXEMPTION_ID=DEM1.EXEMPTION_ID AND"														 
														  +" DIE1.REG_DEED_TXN_ID=?";
														  
														  
	
	public static final String GET_DEED_ATTIBUTE_DTLS =" SELECT DISTINCT DAM1.ATTRIBUTE_VALUE , LM.LABEL_NAME "
														+"	FROM  IGRS_REG_DEED_ATTR_MAP DAM1, "
														+"	IGRS_DEED_FORM_LABEL_MAPPING DM,"
														+"	IGRS_FORM_LABEL_MASTER LM"														
														+"	WHERE DM.LABEL_ID=LM.LABEL_ID AND"
														+"  DAM1.ATTRIBUTE_ID=DM.ATTRIBUTE_ID AND "
														+"  DM.LABEL_ID=LM.LABEL_ID AND " 
														+"  DAM1.REG_DEED_TXN_ID=? "
														+ " ORDER BY LM.LABEL_NAME ";
	
	public static final String GET_PARTY_IDS=" SELECT A.PARTY_TXN_ID,B.PARTY_FIRST_NAME_H ,C.PARTY_TYPE_NAME "
		                                     + " FROM IGRS_REG_DEED_PROP_MAP A,IGRS_REG_TXN_PARTY_DETAILS B,IGRS_PARTY_TYPE_MASTER C " 
		                                     + " WHERE A.REG_TXN_ID=B.REG_TXN_ID"
		                                     + " AND A.PARTY_TXN_ID=B.PARTY_TXN_ID "
		                                     + " AND A.PARTY_TYPE_ID=C.PARTY_TYPE_ID "
		                                     + " AND A.REG_TXN_ID=? "
		                                     + " AND A.REG_DEED_TXN_ID=?"
		                                     + " AND A.PROPERTY_TXN_ID=?";
	public static final String GET_PARTY_IDS_WITH_NOPROPERTY=" SELECT A.PARTY_TXN_ID,B.PARTY_FIRST_NAME_H ,C.PARTY_TYPE_NAME "
									        + " FROM IGRS_REG_DEED_PROP_MAP A,IGRS_REG_TXN_PARTY_DETAILS B,IGRS_PARTY_TYPE_MASTER C " 
									        + " WHERE A.REG_TXN_ID=B.REG_TXN_ID"
									        + " AND A.PARTY_TXN_ID=B.PARTY_TXN_ID "
									        + " AND A.PARTY_TYPE_ID=C.PARTY_TYPE_ID "
									        + " AND A.REG_TXN_ID=? "
									        + " AND A.REG_DEED_TXN_ID=?";
	//following query for aakriti
	public static final String SELECT_DEED_TYPE_OPTIONAL = "SELECT DEED_TYPE_ID,DEED_TYPE_NAME,PROPERTY_VAL_REQD,DUTY_CAL_REQD,PROPERTY_RELATED_DEED FROM IGRS_DEED_TYPE_MASTER WHERE DEED_CATEGORY='O' AND DEED_STATUS='A'";

									   
       
}     
