package com.wipro.igrs.noEncumbrance.sql;

/**
 * ===========================================================================
 * File : NoEncumSQL.java Description : Represents the SQL Class
 * 
 * Author : Piyush Created Date : Aug 12, 2008
 * 
 * ===========================================================================
 */
public class NoEncumSQL {
	public static final String IGRS_NOENCUM_BUILD_FLOOR_DETAILS="INSERT INTO  IGRS_REG_INIT_PROP_FLOOR_DTLS (FLOOR_TXN_ID,PROPERTY_TXN_ID,FLOOR_ID,TOTAL_AREA,CONSTRUCTED_AREA) VALUES(?,?,?,?,?) ";
	public static final String IGRS_RELATION_MASTER="SELECT RELATIVE_TYPE_ID,RELATIVE_TYPE_NAME FROM IGRS_RELATIVE_TYPE_MASTER WHERE UPPER(STATUS)='A' order by RELATIVE_TYPE_NAME";  
    public static final String IGRS_COUNTRY_MASTER="SELECT COUNTRY_ID,COUNTRY_NAME FROM IGRS_COUNTRY_MASTER WHERE COUNTRY_STATUS='A'";
    public static final String IGRS_COUNTRY_MASTER_HINDI="SELECT COUNTRY_ID,H_COUNTRY_NAME FROM IGRS_COUNTRY_MASTER WHERE COUNTRY_STATUS='A'";
    public static final String IGRS_STATE_MASTER="SELECT STATE_ID,STATE_NAME FROM IGRS_STATE_MASTER WHERE COUNTRY_ID=? AND STATE_STATUS='A'";
    public static final String IGRS_STATE_MASTER_HINDI="SELECT STATE_ID,H_STATE_NAME FROM IGRS_STATE_MASTER WHERE COUNTRY_ID=? AND STATE_STATUS='A'";
    public static final String IGRS_DISTRICT_MASTER="SELECT DISTRICT_ID, DISTRICT_NAME FROM IGRS_DISTRICT_MASTER WHERE STATE_ID=? AND DISTRICT_STATUS='A'";
    public static final String IGRS_DISTRICT_MASTER_HINDI="SELECT DISTRICT_ID, H_DISTRICT_NAME FROM IGRS_DISTRICT_MASTER WHERE STATE_ID=? AND DISTRICT_STATUS='A'";
    public static final String IGRS_PHOTOID_PROOF_MASTER="SELECT PHOTO_PROOF_TYPE_ID,PHOTO_PROOF_TYPE_NAME FROM IGRS_PHOTOID_PROOF_TYPE_MASTER WHERE PHOTO_PROOF_TYPE_STATUS='A' ORDER BY PHOTO_PROOF_TYPE_NAME ";
    public static final String IGRS_PHOTOID_PROOF_MASTER_HINDI="SELECT PHOTO_PROOF_TYPE_ID,H_PHOTO_PROOF_TYPE_NAME FROM IGRS_PHOTOID_PROOF_TYPE_MASTER WHERE PHOTO_PROOF_TYPE_STATUS='A' ORDER BY PHOTO_PROOF_TYPE_NAME ";
    public static final String IGRS_CASTE_MASTER="SELECT CASTE_ID, CASTE_NAME FROM IGRS_CASTE_MASTER WHERE CASTE_STATUS='A' ORDER BY CASTE_NAME";
    public static final String IGRS_CASTE_MASTER_HINDI="SELECT CASTE_ID, CASTE_NAME FROM IGRS_CASTE_MASTER WHERE CASTE_STATUS='A' ORDER BY CASTE_NAME";
    public static final String IGRS_RELIGION_MASTER="SELECT RELIGION_ID, RELIGION_NAME FROM IGRS_RELIGION_MASTER WHERE RELIGION_STATUS='A' ORDER BY RELIGION_NAME";
    public static final String IGRS_RELIGION_MASTER_HINDI="SELECT RELIGION_ID, H_RELIGION_NAME FROM IGRS_RELIGION_MASTER WHERE RELIGION_STATUS='A' ORDER BY RELIGION_NAME";
    
    //public static final String IGRS_NOENCUM_REGID_SEARCH="SELECT REGISTRATION_ID,TO_CHAR(CREATED_DATE,'DD/MM/YYYY'),PROPERTY_LOCK_FLAG,CAVEAT_FLAG,CASE_FLAG,POA_FLAG,COURT_ORDER_FLAG FROM IGRS_REG_COMPLETION_DETAILS WHERE REGISTRATION_ID=?";
    public static final String IGRS_NOENCUM_REGID_SEARCH="SELECT REGC.REG_TXN_ID, REGI.PROPERTY_ID, REGI.PROP_TYPE_ID, TYP.PROPERTY_TYPE_NAME,TYP.H_PROPERTY_TYPE_NAME " +
    		"FROM IGRS_REG_PROPRTY_DTLS REGI, IGRS_PROPERTY_TYPE_MASTER TYP , IGRS_REG_TXN_DETLS REGC " +
    		"WHERE REGI.PROPERTY_ID IS NOT NULL AND " +
    		"REGI.PROP_TYPE_ID = TYP.PROPERTY_TYPE_ID AND " +
    		"REGI.REG_TXN_ID = REGC.REG_TXN_ID AND REGC.REGISTRATION_NUMBER = ?";

    //public static final String IGRS_NOENCUM_INSERT_CERTIDETAILS="INSERT INTO IGRS_CERTIFIED_COPY_TXN (TRANSACTION_ID,REGISTRATION_ID,CREATED_BY,CREATED_DATE,PAYMENT_TXN_ID)VALUES(?,?,?,TO_DATE(TO_CHAR(SYSDATE,'DD/MM/YYYY'),'DD/MM/YYYY'),?)"; //Ramesh commeted on 18 Jan 13
    public static final String IGRS_NOENCUM_INSERT_CERTIDETAILS="INSERT INTO IGRS_CERTIFIED_COPY_TXN (TRANSACTION_ID,CREATED_BY,CREATED_DATE,TYPE_REQ,TRANSACTION_STATUS,PURPOSE_OF_REQUEST,FUNCTION_ID,REGISTRATION_ID,FROM_DATE,TO_DATE)VALUES(?,?,SYSDATE,?,?,?,?,?,?,?)";
    public static final String IGRS_NOENCUM_INSERT_PARTY="INSERT INTO IGRS_CERCOPY_TXN_PARTY_DETAILS(CER_COPY_TXN_ID,PARTY_FIRST_NAME,PARTY_MIDDLE_NAME,PARTY_LAST_NAME,PARTY_GENDER,PARTY_AGE,NATIONALITY,COUNTRY_ID,STATE_ID,DISTRICT_ID,PARTY_ADDRESS,POSTAL_CODE,PHONE_NUMBER,MOBILE_NUMBER,EMAIL_ID,PHOTO_PROOF_TYPE_ID,PHOTO_PROOF_ID,BANK_NAME,BANK_ADDRESS,GUARDIAN_NAME,MOTHER_NAME,CASTE_ID,RELIGION_ID,CREATED_BY,TOTAL,OTHERS,FEE,APPLICANT_SPOUSE)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
    //public static final String IGRS_NOENCUM_VIEW_PDETAILS="SELECT CER_COPY_TXN_ID,REGISTRATION_ID,PARTY_FIRST_NAME||'  '||PARTY_MIDDLE_NAME||'  '||PARTY_LAST_NAME,TO_CHAR(CREATED_DATE,'DD/MM/YYYY') FROM IGRS_CERCOPY_TXN_PARTY_DETAILS PT,IGRS_CERTIFIED_COPY_TXN TXN WHERE CER_COPY_TXN_ID=TRANSACTION_ID AND (TRANSACTION_ID=? OR CREATED_DATE BETWEEN TO_DATE(?,'DD/MM/YYYY') AND TO_DATE(?,'DD/MM/YYYY'))";
    
    public static final String IGRS_NOENCUM_VIEW_PDETAILS="SELECT TXN.TRANSACTION_ID,TXN.REGISTRATION_ID, TXN.TRANSACTION_STATUS, "+
    " TO_CHAR(TXN.CREATED_DATE,'DD/MM/YYYY') FROM IGRS_CERCOPY_TXN_PARTY_DETAILS PT, "+
    " IGRS_CERTIFIED_COPY_TXN TXN  WHERE PT.CER_COPY_TXN_ID=TXN.TRANSACTION_ID "+
    " AND (TXN.TRANSACTION_ID=? OR TRUNC(TXN.CREATED_DATE) BETWEEN TO_DATE(?,'DD/MM/YYYY') AND TO_DATE(?,'DD/MM/YYYY')) AND UPPER(PAYMENT_FLAG)='C' AND TYPE_REQ='No-Encumbrance' ";
    //public static final String IGRS_NOENCUM_VIEW_ENTIRE_DETAILS="SELECT PARTY_FIRST_NAME,PARTY_MIDDLE_NAME,PARTY_LAST_NAME,PARTY_GENDER, decode(nvl(PARTY_AGE,0),0,' ',PARTY_AGE), COUNTRY_ID,(SELECT COUNTRY_NAME FROM IGRS_COUNTRY_MASTER WHERE COUNTRY_ID=TXN.COUNTRY_ID),STATE_ID,(SELECT STATE_NAME FROM IGRS_STATE_MASTER WHERE STATE_ID=TXN.STATE_ID), DISTRICT_ID,(SELECT DISTRICT_NAME FROM IGRS_DISTRICT_MASTER WHERE DISTRICT_ID=TXN.DISTRICT_ID),PARTY_ADDRESS,decode(nvl(POSTAL_CODE,0),0,' ',POSTAL_CODE),PHONE_NUMBER,MOBILE_NUMBER,EMAIL_ID, PHOTO_PROOF_TYPE_ID,(SELECT PHOTO_PROOF_TYPE_NAME FROM IGRS_PHOTOID_PROOF_TYPE_MASTER WHERE PHOTO_PROOF_TYPE_ID=TXN.PHOTO_PROOF_TYPE_ID),PHOTO_PROOF_ID,BANK_NAME,BANK_ADDRESS,GUARDIAN_NAME, MOTHER_NAME,CASTE_ID,(SELECT CASTE_NAME FROM IGRS_CASTE_MASTER WHERE CASTE_ID=TXN.CASTE_ID),RELIGION_ID,(SELECT RELIGION_NAME FROM IGRS_RELIGION_MASTER WHERE RELIGION_ID=TXN.RELIGION_ID),NATIONALITY,TO_CHAR(CREATED_DATE,'DD/MM/YYYY') FROM IGRS_CERTIFIED_COPY_TXN, IGRS_CERCOPY_TXN_PARTY_DETAILS TXN WHERE transaction_id=CER_COPY_TXN_ID and CER_COPY_TXN_ID=?";
    
    /*public static final String IGRS_NOENCUM_VIEW_ENTIRE_DETAILS="SELECT pd.PARTY_FIRST_NAME,pd.PARTY_MIDDLE_NAME,pd.PARTY_LAST_NAME,pd.PARTY_GENDER, "+
    " decode(nvl(pd.PARTY_AGE,0),0,' ',pd.PARTY_AGE), pd.COUNTRY_ID, "+
    " (SELECT COUNTRY_NAME FROM IGRS_COUNTRY_MASTER WHERE COUNTRY_ID=pd.COUNTRY_ID), "+
    " STATE_ID,(SELECT STATE_NAME FROM IGRS_STATE_MASTER WHERE STATE_ID=pd.STATE_ID),  "+
    " pd.DISTRICT_ID,(SELECT DISTRICT_NAME FROM IGRS_DISTRICT_MASTER  "+
    " WHERE DISTRICT_ID=pd.DISTRICT_ID),pd.PARTY_ADDRESS,decode(nvl(pd.POSTAL_CODE,0),0,' ',pd.POSTAL_CODE), "+
    " pd.PHONE_NUMBER,pd.MOBILE_NUMBER,pd.EMAIL_ID, pd.PHOTO_PROOF_TYPE_ID, "+
    " (SELECT PHOTO_PROOF_TYPE_NAME FROM IGRS_PHOTOID_PROOF_TYPE_MASTER "+
    " WHERE PHOTO_PROOF_TYPE_ID=pd.PHOTO_PROOF_TYPE_ID), "+
    " pd.PHOTO_PROOF_ID,pd.BANK_NAME,pd.BANK_ADDRESS,pd.GUARDIAN_NAME,  "+
    " pd.MOTHER_NAME,pd.CASTE_ID,(SELECT CASTE_NAME  "+
    " FROM IGRS_CASTE_MASTER WHERE CASTE_ID=pd.CASTE_ID), "+
    " pd.RELIGION_ID,(SELECT RELIGION_NAME FROM IGRS_RELIGION_MASTER  "+
    " WHERE RELIGION_ID=pd.RELIGION_ID),pd.NATIONALITY, "+
    " TO_CHAR(pd.CREATED_DATE,'DD/MM/YYYY'),txn.PURPOSE_OF_REQUEST FROM  "+
    " IGRS_CERTIFIED_COPY_TXN txn, IGRS_CERCOPY_TXN_PARTY_DETAILS pd  "+
    " WHERE txn.transaction_id=pd.CER_COPY_TXN_ID and CER_COPY_TXN_ID=?";*/
    
    public static final String IGRS_NOENCUM_VIEW_ENTIRE_DETAILS=" SELECT pd.PARTY_FIRST_NAME,pd.PARTY_MIDDLE_NAME," +
    		" pd.PARTY_LAST_NAME,pd.PARTY_GENDER,  decode(nvl(pd.PARTY_AGE,0),0,' ',pd.PARTY_AGE), pd.COUNTRY_ID,  " +
    		" (SELECT COUNTRY_NAME FROM IGRS_COUNTRY_MASTER WHERE COUNTRY_ID=pd.COUNTRY_ID),  STATE_ID," +
    		" (SELECT STATE_NAME FROM IGRS_STATE_MASTER WHERE STATE_ID=pd.STATE_ID),   pd.DISTRICT_ID," +
    		" (SELECT DISTRICT_NAME FROM IGRS_DISTRICT_MASTER   WHERE DISTRICT_ID=pd.DISTRICT_ID)," +
    		" pd.PARTY_ADDRESS,decode(nvl(pd.POSTAL_CODE,0),0,' ',pd.POSTAL_CODE),  " +
    		" pd.PHONE_NUMBER,pd.MOBILE_NUMBER,pd.EMAIL_ID, pd.PHOTO_PROOF_TYPE_ID,  " +
    		" (SELECT PHOTO_PROOF_TYPE_NAME FROM IGRS_PHOTOID_PROOF_TYPE_MASTER  WHERE PHOTO_PROOF_TYPE_ID=pd.PHOTO_PROOF_TYPE_ID),  " +
    		" pd.PHOTO_PROOF_ID,pd.BANK_NAME,pd.BANK_ADDRESS,pd.GUARDIAN_NAME,   pd.MOTHER_NAME,pd.CASTE_ID,(SELECT CASTE_NAME   " +  
    		" FROM IGRS_CASTE_MASTER WHERE CASTE_ID=pd.CASTE_ID),  pd.RELIGION_ID,  " +
    		" (SELECT RELIGION_NAME FROM IGRS_RELIGION_MASTER   WHERE RELIGION_ID=pd.RELIGION_ID),  " +
    		" pd.NATIONALITY,  TO_CHAR(pd.CREATED_DATE,'DD/MM/YYYY'),  " +
    		" txn.PURPOSE_OF_REQUEST ,  " +
    		" (SELECT PROPERTY_TYPE_NAME FROM IGRS_PROPERTY_TYPE_MASTER  WHERE PROPERTY_TYPE_ID=pr.PROPERTY_TYPE_ID) PROP_TYPE, " +
    		" pr.VIKAS_KHAND,  " +
    		" (SELECT DISTRICT_NAME FROM IGRS_DISTRICT_MASTER   WHERE DISTRICT_ID=pr.DISTRICT_ID) PROP_DIST,  " +
    		" (SELECT TEHSIL_NAME FROM IGRS_TEHSIL_MASTER  WHERE TEHSIL_ID=pr.TEHSIL_ID) PROP_TEHSIL,  " +
    		" (SELECT WARD_PATWARI_NAME FROM IGRS_WARD_PATWARI_MASTER  WHERE WARD_PATWARI_ID=pr.WARD_PATWARI_ID) PROP_PATWARI,  " +
    		" (SELECT MOHALLA_VILLAGE_NAME FROM IGRS_MOHALLA_VILLAGE_MASTER  WHERE MOHALLA_VILLAGE_ID=pr.MOHALLA_VILLAGE_ID) PROP_VILLAGE,  " +
    		" (SELECT MUNICIPAL_BODY_NAME FROM IGRS_MUNICIPAL_BODY_MASTER  WHERE MUNICIPAL_BODY_ID=pr.MUNCIPAL_BODY_TYPE_ID) PROP_MUNICIPALTY,  " +
    		" (SELECT AREA_TYPE_NAME FROM IGRS_AREA_TYPE_MASTER  WHERE AREA_TYPE_ID=pr.AREA_TYPE_ID) AREA_TYPE,  " +
    		" txn.REGISTRATION_ID ,  " +
    		" to_char(txn.CREATED_DATE,'DD/MM/YYYY'),  " +
    		" pr.RI_CIRCLE,  " +
    		" pr.LAYOUT_DETAIL,  " +
    		" pr.KHASRA_NUMBER,  " +
    		" pr.NAZOOL_SHEET_NUMBER,  " +
    		" pr.RIN_PUSHTIKA_NUMBER,  " +
    		" pr.EAST_BOUNDARY,  " +
    		" pr.WEST_BOUNDARY,  " +
    		" pr.NORTH_BOUNDARY,  " +
    		" pr.SOUTH_BOUNDARY,  " +
    		" pr.TOTAL_AREA,  " +
    		" pr.PLOTAREA,  " +
    		" pr.NO_OF_SHOPS,  " +
    		" pr.BUILDING_TYPE,  " +
    		" pr.NO_OF_CONST_FLOORS,  " +
    		" pr.SPLIT_WITH_ORIGINAL  " +
    		" FROM   IGRS_CERTIFIED_COPY_TXN txn, IGRS_CERCOPY_TXN_PARTY_DETAILS pd   " +
    		" ,IGRS_REG_INIT_PROPERTY_DETAILS pr  " +
    		" WHERE   " +
    		" txn.transaction_id=pd.CER_COPY_TXN_ID   " +
    		" AND txn.transaction_id=pr.PROPERTY_TXN_ID AND  " +
    		" CER_COPY_TXN_ID= ? ";
    
    public static final String IGRS_NOENCUM_CHECK_USERID="SELECT FUNCTION_TXN_ID,PARTY_FIRST_NAME,PARTY_MIDDLE_NAME,PARTY_LAST_NAME,PARTY_GENDER,PARTY_AGE, COUNTRY_ID,(SELECT COUNTRY_NAME FROM IGRS_COUNTRY_MASTER WHERE COUNTRY_ID=TXN.COUNTRY_ID),STATE_ID,(SELECT STATE_NAME FROM IGRS_STATE_MASTER WHERE STATE_ID=TXN.STATE_ID), DISTRICT_ID,(SELECT DISTRICT_NAME FROM IGRS_DISTRICT_MASTER WHERE DISTRICT_ID=TXN.DISTRICT_ID),PARTY_ADDRESS,POSTAL_CODE,PHONE_NUMBER,MOBILE_NUMBER,EMAIL_ID, PHOTO_PROOF_TYPE_ID,(SELECT PHOTO_PROOF_TYPE_NAME FROM IGRS_PHOTOID_PROOF_TYPE_MASTER WHERE PHOTO_PROOF_TYPE_ID=TXN.PHOTO_PROOF_TYPE_ID),PHOTO_PROOF_ID,BANK_NAME,BANK_ADDRESS,GUARDIAN_NAME, MOTHER_NAME,CASTE_ID,(SELECT CASTE_NAME FROM IGRS_CASTE_MASTER WHERE CASTE_ID=TXN.CASTE_ID),RELIGION_ID,(SELECT RELIGION_NAME FROM IGRS_RELIGION_MASTER WHERE RELIGION_ID=TXN.RELIGION_ID),NATIONALITY FROM IGRS_TXN_PARTY_DETAILS TXN WHERE PARTY_USER_ID=?";
    public static final String IGRS_PROPERTY_MASTER="SELECT PROPERTY_TYPE_ID,PROPERTY_TYPE_DESC FROM IGRS_PROPERTY_TYPE_MASTER WHERE PROPERTY_TYPE_STATUS='A' ORDER by  PROPERTY_TYPE_DESC";
    public static final String IGRS_PROPERTY_MASTER_HINDI="SELECT PROPERTY_TYPE_ID,H_PROPERTY_TYPE_NAME FROM IGRS_PROPERTY_TYPE_MASTER WHERE PROPERTY_TYPE_STATUS='A' ORDER by  PROPERTY_TYPE_DESC";

    public static final String IGRS_TEHESIL_MASTER="SELECT TEHSIL_ID,TEHSIL_NAME FROM IGRS_TEHSIL_MASTER WHERE DISTRICT_ID=? AND TEHSIL_STATUS='A' ORDER BY TEHSIL_NAME";
    public static final String IGRS_TEHESIL_MASTER_HINDI="SELECT TEHSIL_ID,H_TEHSIL_NAME FROM IGRS_TEHSIL_MASTER WHERE DISTRICT_ID=? AND TEHSIL_STATUS='A' ORDER BY TEHSIL_NAME";
    public static final String IGRS_PATWARI_MASTER="SELECT WARD_PATWARI_ID,WARD_PATWARI_NAME FROM IGRS_WARD_PATWARI_MASTER  WHERE TEHSIL_ID =? AND WARD_PATWARI_STATUS='A' ORDER BY WARD_PATWARI_NAME";

    public static final String IGRS_NOENCUM_PROPERTY_DETAILS="INSERT INTO IGRS_REG_INIT_PROPERTY_DETAILS (PROPERTY_TXN_ID,DISTRICT_ID,TEHSIL_ID,WARD_PATWARI_ID,MOHALLA_VILLAGE_ID,PROPERTY_TYPE_ID,VIKAS_KHAND,RI_CIRCLE,KHASRA_NUMBER,LAYOUT_DETAIL,RIN_PUSHTIKA_NUMBER,EAST_BOUNDARY,WEST_BOUNDARY,NORTH_BOUNDARY,SOUTH_BOUNDARY,TOTAL_AREA,REG_TXN_ID,SPLIT_WITH_ORIGINAL,PLOTAREA,NO_OF_SHOPS,BUILDING_TYPE,NO_OF_CONST_FLOORS,NAZOOL_SHEET_NUMBER,AREA_TYPE_ID,MUNCIPAL_BODY_TYPE_ID) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
    public static final String IGRS_NOENCUM_GRAM_DETAILS="SELECT MOHALLA_VILLAGE_ID,MOHALLA_VILLAGE_NAME FROM IGRS_MOHALLA_VILLAGE_MASTER WHERE WARD_PATWARI_ID= ? AND MOHALLA_VILLAGE_STATUS='A' ORDER BY MOHALLA_VILLAGE_NAME DESC ";
    public static final String IGRS_MUNICIPALITY_MASTER="SELECT MUNICIPAL_BODY_ID,MUNICIPAL_BODY_NAME  FROM IGRS_MUNICIPAL_BODY_MASTER WHERE UPPER(MUNICIPAL_BODY_STATUS)='A' ORDER BY  MUNICIPAL_BODY_NAME ";

    public static final String IGRS_AREA_TYPE_MASTER="SELECT AREA_TYPE_ID,AREA_TYPE_NAME FROM IGRS_AREA_TYPE_MASTER WHERE UPPER(AREA_TYPE_STATUS)='A' ";
    public static final String IGRS_AREA_TYPE_MASTER_HINDI="SELECT AREA_TYPE_ID,H_AREA_TYPE_NAME FROM IGRS_AREA_TYPE_MASTER WHERE UPPER(AREA_TYPE_STATUS)='A' ";
	
    public static final String GET_PENDING_APPLICATIONS_DETLS = "SELECT WT.TRANSACTION_ID,  WP.PAID_AMOUNT,(WP.PAYABLE_AMOUNT-WP.PAID_AMOUNT) DUE_AMOUNT,  WP.UPDATE_DATE,TO_CHAR((WT.CREATED_DATE),'dd/mm/yyyy') CREATED_DATE,WP.PAYABLE_AMOUNT"+
    		" FROM IGRS_CERTIFIED_COPY_TXN WT,(SELECT IGRS_CERT_COPY_PAYMENT_DTLS.CERT_TXN_ID,SUM(IGRS_CERT_COPY_PAYMENT_DTLS.PAID_AMOUNT) PAID_AMOUNT,MAX(IGRS_CERT_COPY_PAYMENT_DTLS.PAYABLE_AMOUNT) PAYABLE_AMOUNT,TO_CHAR(MAX(IGRS_CERT_COPY_PAYMENT_DTLS.UPDATE_DATE), 'dd/mm/yyyy') UPDATE_DATE"+
    		" FROM IGRS_CERT_COPY_PAYMENT_DTLS where IGRS_CERT_COPY_PAYMENT_DTLS.PAYMENT_FLAG !='C' GROUP BY IGRS_CERT_COPY_PAYMENT_DTLS.CERT_TXN_ID) WP WHERE WP.CERT_TXN_ID = WT.TRANSACTION_ID AND WT.TRANSACTION_STATUS = 'U' AND WT.TYPE_REQ='No-Encumbrance' AND WT.CREATED_BY='";
    		
    public static final String INSERT_PROPERTY_ID_MAP="INSERT INTO IGRS_NOECUM_PROPERTYID_MAPPING(TXN_PROP_MAPPING_ID,TXN_ID,PROPERTY_ID,CREATED_BY,CREATED_DATE) VALUES(?,?,?,?,SYSDATE)";
    
    public static final String POPERTY_MAP_SEQUENCE="SELECT IGRS_NOENC_PROP_MAP_SEQ.NEXTVAL FROM DUAL";

    public static final String INSERT_AGRI_PROPERTY_DETAILS="INSERT INTO IGRS_NOECUM_PROPERTY_DTLS(TXN_ID,COUNTRY_ID,STATE_ID,DISTRICT_ID,TEHSIL_ID,"+
			"WARD_PATWARI_ID,MOHALLA_VILLAGE_ID,PROPERTY_TYPE,MUNICIPALITY_GRAM,URBAN_RULAR,VIKAS_KHAND,RI_CIRCLE,"+
			"LAYOUT_DETAILS,EAST_DTLS,WEST_DTLS,NORTH_DTLS,SOUTH_DTLS,AREA_VALUE,SIZE_LENGTH,PART_ORIGINAL_LAND,IRRIGATED_UNIRRIGATED,CREATED_BY,SIZE_BREADTH,CREATED_DATE)"
			+"VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,SYSDATE)";
    		
   public static final String INSERT_KHASRA_DEATILS="INSERT INTO IGRS_NOECUM_KHASRA_DETAILS(KHASRA_DETAIL_ID,TXN_ID,KHASRA_NO,RIN_PUSTIKA,KHASRA_AREA,LAGAAN_PROVISION,CREATED_BY,CREATED_DATE) VALUES(?,?,?,?,?,?,?,SYSDATE)";
   
   public static final String KHASRA_SEQ_NEXT="SELECT IGRS_NOENC_PROP_KHS_SEQ .NEXTVAL FROM DUAL";
   public static final String INSERT_BUILD_PROPERTY_DETAILS="INSERT INTO IGRS_NOECUM_PROPERTY_DTLS(TXN_ID,COUNTRY_ID,STATE_ID,DISTRICT_ID,TEHSIL_ID,"+
			"WARD_PATWARI_ID,MOHALLA_VILLAGE_ID,PROPERTY_TYPE,MUNICIPALITY_GRAM,URBAN_RULAR,VIKAS_KHAND,RI_CIRCLE,"+
			"LAYOUT_DETAILS,PLOT_NUMBER,EAST_DTLS,WEST_DTLS,NORTH_DTLS,SOUTH_DTLS,AREA_VALUE,COLONY,CEILING_TYPE,BUILDING_NUMBER,RESIDENTIAL_COMMERCIAL,NAZOL_SHEET_NO,CREATED_BY,CREATED_DATE)"
			+"VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,SYSDATE)";		
    		
   public static final String INSERT_FLOOR_DETAILS="INSERT INTO IGRS_NOECUM_FLOOR_DETAILS(FLOOR_DETAIL_ID,TXN_ID,FLOOR_NO,SIZE_LENGTH,SIZE_BREADTH,AREA_VALUE,CREATED_BY,CREATED_DATE) VALUES(?,?,?,?,?,?,?,SYSDATE)";
		
   public static final String FLOOR_SEQ_NEXT="SELECT IGRS_NOENC_PROP_FLR_SEQ.NEXTVAL FROM DUAL";
   public static  final String INSERT_PLOT_PROPERTY_DETAILS="INSERT INTO IGRS_NOECUM_PROPERTY_DTLS(TXN_ID,COUNTRY_ID,STATE_ID,DISTRICT_ID,TEHSIL_ID,"+
			"WARD_PATWARI_ID,MOHALLA_VILLAGE_ID,PROPERTY_TYPE,MUNICIPALITY_GRAM,URBAN_RULAR,VIKAS_KHAND,RI_CIRCLE,"+
			"LAYOUT_DETAILS,PLOT_NUMBER,EAST_DTLS,WEST_DTLS,NORTH_DTLS,SOUTH_DTLS,AREA_VALUE,COLONY,PART_ORIGINAL_LAND,SIZE_LENGTH,CORNER_PLOT,RESIDENTIAL_COMMERCIAL,NAZOL_SHEET_NO,CREATED_BY,SIZE_BREADTH,CREATED_DATE)"
			+"VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,SYSDATE)";

   public static final String PENDING_NO_ENCUM_APP="select  cer_copy_txn_id,total,TO_CHAR((CREATED_DATE),'dd/mm/yyyy') CREATED_DATE from  igrs_cercopy_txn_party_details where cer_copy_txn_id not in (select cert_txn_id from igrs_cert_copy_payment_dtls) and cer_copy_txn_id like 'NEC%' and created_by=?";

   public static final String SELECT_PROPERTY=" SELECT OP.PROPERTY_ID, (SELECT TYP.PROPERTY_TYPE_DESC "+ 
			"FROM IGRS_REG_PROPRTY_DTLS REGI, IGRS_PROPERTY_TYPE_MASTER TYP , IGRS_REG_TXN_DETLS REGC"+ 
			" WHERE REGI.PROPERTY_ID IS NOT NULL AND "+ 
			" REGI.PROP_TYPE_ID = TYP.PROPERTY_TYPE_ID AND"+  
			" REGI.REG_TXN_ID = REGC.REG_TXN_ID AND REGI.PROPERTY_ID =OP.PROPERTY_ID ) PROPERTY_TYPE FROM IGRS_NOECUM_PROPERTYID_MAPPING OP WHERE OP.TXN_ID=?";

   public static final String GET_DETAILS_ON_ID="SELECT CP.CER_COPY_TXN_ID,ct.registration_id,CP.PARTY_FIRST_NAME,CP.PARTY_MIDDLE_NAME,CP.PARTY_LAST_NAME,CP.PARTY_GENDER,CP.PARTY_AGE,CP.NATIONALITY," +
			"(select country_name from igrs_country_master where country_id=cp.country_id ) country,(select state_name from igrs_state_master where state_id=cp.state_id) state,(select district_name from igrs_district_master where district_id=cp.district_id) district,CP.PARTY_ADDRESS,CP.POSTAL_CODE,"+
			"CP.PHONE_NUMBER,CP.MOBILE_NUMBER,CP.EMAIL_ID,(select PHOTO_PROOF_TYPE_NAME from igrs_photoid_proof_type_master where PHOTO_PROOF_TYPE_ID=CP.PHOTO_PROOF_TYPE_ID),CP.PHOTO_PROOF_ID,CP.GUARDIAN_NAME,CP.MOTHER_NAME,"+		
			"CP.CATEGORY_ID,(SELECT CASTE_NAME FROM IGRS_CASTE_MASTER WHERE CASTE_ID=CP.CASTE_ID),(SELECT RELIGION_NAME FROM IGRS_RELIGION_MASTER WHERE RELIGION_ID=CP.RELIGION_ID),CP.REMARKS,CP.TOTAL,CP.OTHERS,"+		
			"CP.FEE,CP.CREATED_BY,CP.CREATED_DATE,CP.VOLUME_NO,CP.BOOK_NUM,CP.OLD_REG_NUM,CP.OLD_REG_DT,"+
			"CT.PURPOSE_OF_REQUEST,CT.TYPE_REQ,CT.DOC_TYPE,CT.TRANSACTION_STATUS,TO_CHAR(CT.CREATED_DATE,'dd/mm/yyyy'),TO_CHAR(CT.DISPATCH_DT,'dd/mm/yyyy'),CT.POSTAL_TRACKING_NUMBER,CT.FROM_DATE,CT.TO_DATE,CP.DOC_PATH FROM IGRS_CERCOPY_TXN_PARTY_DETAILS CP,IGRS_CERTIFIED_COPY_TXN CT WHERE CP.cer_copy_txn_id=CT.transaction_id and CP.cer_copy_txn_id=?"; 
   
   public static final String GET_DETAILS_ON_ID_HINDI="SELECT CP.CER_COPY_TXN_ID,ct.registration_id,CP.PARTY_FIRST_NAME,CP.PARTY_MIDDLE_NAME,CP.PARTY_LAST_NAME,CP.PARTY_GENDER,CP.PARTY_AGE,CP.NATIONALITY," +
	"(select H_COUNTRY_NAME from igrs_country_master where country_id=cp.country_id ) country,(select H_STATE_NAME from igrs_state_master where state_id=cp.state_id) state,(select H_DISTRICT_NAME from igrs_district_master where district_id=cp.district_id) district,CP.PARTY_ADDRESS,CP.POSTAL_CODE,"+
	"CP.PHONE_NUMBER,CP.MOBILE_NUMBER,CP.EMAIL_ID,(select H_PHOTO_PROOF_TYPE_NAME from igrs_photoid_proof_type_master where PHOTO_PROOF_TYPE_ID=CP.PHOTO_PROOF_TYPE_ID),CP.PHOTO_PROOF_ID,CP.GUARDIAN_NAME,CP.MOTHER_NAME,"+		
	"CP.CATEGORY_ID,(SELECT H_CASTE_NAME FROM IGRS_CASTE_MASTER WHERE CASTE_ID=CP.CASTE_ID),(SELECT H_RELIGION_NAME FROM IGRS_RELIGION_MASTER WHERE RELIGION_ID=CP.RELIGION_ID),CP.REMARKS,CP.TOTAL,CP.OTHERS,"+		
	"CP.FEE,CP.CREATED_BY,CP.CREATED_DATE,CP.VOLUME_NO,CP.BOOK_NUM,CP.OLD_REG_NUM,CP.OLD_REG_DT,"+
	"CT.PURPOSE_OF_REQUEST,CT.TYPE_REQ,CT.DOC_TYPE,CT.TRANSACTION_STATUS,TO_CHAR(CT.CREATED_DATE,'dd/mm/yyyy'),TO_CHAR(CT.DISPATCH_DT,'dd/mm/yyyy'),CT.POSTAL_TRACKING_NUMBER,CT.FROM_DATE,CT.TO_DATE,CP.DOC_PATH FROM IGRS_CERCOPY_TXN_PARTY_DETAILS CP,IGRS_CERTIFIED_COPY_TXN CT WHERE CP.cer_copy_txn_id=CT.transaction_id and CP.cer_copy_txn_id=?"; 

   public static final String GET_ALL_PROPERTY_DETAILS="select * from igrs_noecum_property_dtls where txn_id=?";


   public static final String GET_KHASRA_DETAILS="select khasra_no,rin_pustika,khasra_area,lagaan_provision from igrs_noecum_khasra_details where txn_id=?";

   public static final String GET_FLOOR_DETAILS="select floor_no,size_length,size_breadth,area_value from igrs_noecum_floor_details where txn_id=?";

   public static final String TOTAL_PAYMENT="select total from igrs_cercopy_txn_party_details where cer_copy_txn_id=?";

   public static final String DELTE_CERCOPY_PARTY_DETAILS="delete from igrs_cercopy_txn_party_details where CER_COPY_TXN_ID='";
   public static final String DELTE_CERCOPY_TXN_DETAILS="delete from igrs_certified_copy_txn where TRANSACTION_ID='";
   public static final String DELTE_CERCOPY_FLOOR_DETAILS="delete from igrs_noecum_floor_details where TXN_ID='";
   public static final String DELTE_CERCOPY_KHASRA_DETAILS="delete from igrs_noecum_khasra_details where TXN_ID='";
   public static final String DELTE_CERCOPY_PROPERTY_DETAILS="delete from igrs_noecum_property_dtls where TXN_ID='";
   public static final String DELTE_CERCOPY_PROPERTY_MAP_DETAILS="delete from igrs_noecum_propertyid_mapping where TXN_ID='";

   public static final String GET_PAYMENT_PARAMETER="select wt.REGISTRATION_OFFICE_ID,(select office_name from igrs_office_master where office_id= upper(wt.REGISTRATION_OFFICE_ID)) name,(select district_id from igrs_office_master where office_id= upper(wt.REGISTRATION_OFFICE_ID)) district_id,(select district_name from igrs_district_master where district_id =(select district_id from igrs_office_master where office_id=upper(wt.REGISTRATION_OFFICE_ID))) from igrs_reg_txn_detls wt where registration_number=?";
   public static final String GET_PAYMENT_PARAMETER_HINDI="select wt.REGISTRATION_OFFICE_ID,(select h_office_name from igrs_office_master where office_id= upper(wt.REGISTRATION_OFFICE_ID)) name,(select district_id from igrs_office_master where office_id= upper(wt.REGISTRATION_OFFICE_ID)) district_id,(select h_district_name from igrs_district_master where district_id =(select district_id from igrs_office_master where office_id=upper(wt.REGISTRATION_OFFICE_ID))) from igrs_reg_txn_detls wt where registration_number=?";

   public static final String CHECK_DRO="select office_type_name from igrs_office_type_master where office_type_id=(select office_type_id from igrs_office_master where office_id =?";

   public static final String UPDATE_TRAN_STATUS="UPDATE IGRS_CERTIFIED_COPY_TXN SET TRANSACTION_STATUS='C',PURPOSE_DOWNLOAD=?,FROM_DATE=?,TO_DATE=? where TRANSACTION_ID =?";
   
   public static final String GET_REG_TXN_ID="select REG_TXN_ID from IGRS_REG_TXN_DETLS where REGISTRATION_NUMBER =?";

   public static final String GET_COLLECTION_OFFICE="select REGISTRATION_OFFICE_ID from IGRS_REG_TXN_DETLS where REGISTRATION_NUMBER =?";

// Hindi Queries
   public static final String IGRS_COUNTRY_MASTER_HI="SELECT COUNTRY_ID,H_COUNTRY_NAME FROM IGRS_COUNTRY_MASTER WHERE COUNTRY_STATUS='A'";
   public static final String IGRS_STATE_MASTER_HI="SELECT STATE_ID,H_STATE_NAME FROM IGRS_STATE_MASTER WHERE COUNTRY_ID=? AND STATE_STATUS='A'";
   public static final String IGRS_DISTRICT_MASTER_HI="SELECT DISTRICT_ID, H_DISTRICT_NAME FROM IGRS_DISTRICT_MASTER WHERE STATE_ID=? AND DISTRICT_STATUS='A'";

   public static final String GET_PROP_DETAILS="SELECT P.PROP_TYPE_ID,T.PROPERTY_TYPE_NAME||' '||P.PROPERTY_ADDRESS||' '||C.COLONY_NAME||' '||W.WARD_PATWARI_NAME||' '||S.SUB_AREA_TYPE_NAME||' '||A.AREA_TYPE_NAME||' '||TD.TEHSIL_NAME ,P.AREA,D.DISTRICT_NAME,P.EAST_BOUNDARY,P.WEST_BOUNDARY,P.NORTH_BOUNDARY,P.SOUTH_BOUNDARY,"+
   											"(SELECT SUM(NVL(AREA,0)) FROM IGRS_REG_FLOOR_DETAILS WHERE PROPERTY_ID=?),P.VAL_TXN_ID FROM IGRS_PROPERTY_TYPE_MASTER T,IGRS_REG_PROPRTY_DTLS P,IGRS_DISTRICT_MASTER D,IGRS_COLONY_MASTER C,IGRS_WARD_PATWARI_MASTER W,IGRS_SUB_AREA_TYPE_MASTER S,IGRS_AREA_TYPE_MASTER A,IGRS_TEHSIL_MASTER TD WHERE D.DISTRICT_ID=P.DISTRICT_ID AND T.PROPERTY_TYPE_ID=P.PROP_TYPE_ID AND TD.TEHSIL_ID=P.TEHSIL_ID AND W.WARD_PATWARI_ID=P.WARD_ID AND C.COLONY_ID=P.MOHALLA_ID AND S.SUB_AREA_TYPE_ID=P.GOV_BODY_ID AND A.AREA_TYPE_ID=P.AREA_TYPE_ID AND P.PROPERTY_ID=?";					

   public static final String GET_PROP_DETAILS_HI="SELECT P.PROP_TYPE_ID,T.PROPERTY_TYPE_NAME||' '||P.PROPERTY_ADDRESS||' '||C.COLONY_NAME||' '||W.WARD_PATWARI_NAME||' '||S.SUB_AREA_TYPE_NAME||' '||A.AREA_TYPE_NAME||' '||TD.TEHSIL_NAME ,P.AREA,D.DISTRICT_NAME,P.EAST_BOUNDARY,P.WEST_BOUNDARY,P.NORTH_BOUNDARY,P.SOUTH_BOUNDARY,"+
		"(SELECT SUM(NVL(AREA,0)) FROM IGRS_REG_FLOOR_DETAILS WHERE PROPERTY_ID=?),P.VAL_TXN_ID FROM IGRS_PROPERTY_TYPE_MASTER T,IGRS_REG_PROPRTY_DTLS P,IGRS_DISTRICT_MASTER D,IGRS_COLONY_MASTER C,IGRS_WARD_PATWARI_MASTER W,IGRS_SUB_AREA_TYPE_MASTER S,IGRS_AREA_TYPE_MASTER A,IGRS_TEHSIL_MASTER TD WHERE D.DISTRICT_ID=P.DISTRICT_ID AND T.PROPERTY_TYPE_ID=P.PROP_TYPE_ID AND TD.TEHSIL_ID=P.TEHSIL_ID AND W.WARD_PATWARI_ID=P.WARD_ID AND C.COLONY_ID=P.MOHALLA_ID AND S.SUB_AREA_TYPE_ID=P.GOV_BODY_ID AND A.AREA_TYPE_ID=P.AREA_TYPE_ID AND P.PROPERTY_ID=?";					

   public static final String GET_PLOT_AREA="SELECT TOTAL_AREA FROM IGRS_PROP_PLOT_DETLS WHERE VAL_TXN_ID=?";

   public static final String GET_AGRI_AREA="SELECT NVL(TOTAL_AREA,0),NVL(TOTAL_DIVERTED_AREA,0) FROM IGRS_PROP_AGRI_DETLS WHERE VAL_TXN_ID=?";

   public static final String GET_BUILD_AREA="SELECT BUILDING_SUB_TYPE_ID,NVL(TOTAL_AREA,0),NVL(FLOOR_AREA,0),NVL(TERRACE_AREA,0) FROM IGRS_PROP_BUILDING_DETLS WHERE VAL_TXN_ID=?";

   //--------added by satbir kumar---
   
   public static final String GET_SIGN_PATH="SELECT SIGNATURE_PATH FROM IGRS_USER_REG_DETAILS WHERE USER_ID=?";
public static final String GET_AREA_DETAILS = "SELECT NORTH_BOUNDARY,SOUTH_BOUNDARY,EAST_BOUNDARY,WEST_BOUNDARY  FROM IGRS_REG_PROP_KHASARA_DTLS WHERE PROPERTY_ID=?";
   
   
}