/**
 * CommonSQL.java
 */
package com.wipro.igrs.hrpayroll.payroll.sql;
/**
 * @author pranalk
 *
 */
public class CommonSQL
{
    public  static final  String PAYROLL_COMP_ID_LIST = "SELECT DETAILED_HEAD_ID,DETAILED_HEAD_NAME_E " +
    		"FROM IGRS_EXP_DETAILED_HEAD_MASTER ORDER BY DETAILED_HEAD_NAME_E";
    
    public  static final  String PAYROLL_OPR_ID_LIST = "SELECT OPERATOR_ID,OPERATOR_NAME FROM IGRS_OPERATOR_MASTER";
    
    public  static final  String PAYROLL_COMP_DET_INSERT ="INSERT INTO IGRS_EMP_SALARY_COMPONENTS " +
    		"(COMPONENT_ID,COMPONENT_TYPE,OPERATOR_ID,COMPONENT_PARENT_ID,FN_OPERATOR_ID) VALUES(?,?,?,?,?)"; 

    public  static final  String PAYROLL_COMP_DET_SELECT = "SELECT DM.DETAILED_HEAD_NAME_E,ES.COMPONENT_TYPE,OM.OPERATOR_NAME," +
	" OM.OPERATOR_NAME,ES.COMPONENT_ID FROM IGRS_EMP_SALARY_COMPONENTS ES," +
	"IGRS_EXP_DETAILED_HEAD_MASTER DM,IGRS_OPERATOR_MASTER OM WHERE ES.COMPONENT_ID = DM.DETAILED_HEAD_ID " +
	"AND ES.OPERATOR_ID = OM.OPERATOR_ID ";

    public  static final  String PAYROLL_COMP_ID_DELETE="DELETE FROM IGRS_EMP_SALARY_COMPONENTS WHERE COMPONENT_ID =";	
}

	

