/*
 * Copyright Notice
 *==============================================================================
 * This file contains proprietary information of Wipro Infotech, Bangalore.
 * Copying or reproduction without prior written approval is prohibited.
 * Copyright (c) 2007-08
 *==============================================================================
 *
 * File Name   :   ExpHeadMappingCommonSQL.java
 * Author      :   Hend M. ismail
 * Description :   Represents the CommonSQL Class for Exp. Head Mapping  Master.
 * ----------------------------------------------------------------------------
 * Version         Modified By     Modified On           Modification
 * ----------------------------------------------------------------------------
 * 1.0              Hend M. ismail  18th Augest, 2008	 		 
 * --------------------------------------------------------------------------------
 */
package com.wipro.igrs.expheadmapping.sql;

public class ExpHeadMappingCommonSQL {
	// Constants ---------------------------------------------------------------
	
	
	//IGRS_EXP_HEAD_MAPPING
	// Select Query
	public static final String SELECT_EXP_HEAD_MAPPING_JOIN = "SELECT T1.MAJOR_HEAD_ID,T2.MAJOR_HEAD_NAME_E,T1.SUB_MAJOR_HEAD_ID ,T3.SUB_MAJOR_HEAD_NAME_E,"+
															  "T1.MINOR_HEAD_ID,T4.MINOR_HEAD_NAME_E,T1.SCHEME_ID,T5.SCHEME_NAME_E,T1.SEGMENT_ID,T6.SEGMENT_NAME_E,"+
															  "T1.OBJECT_ID,T7.OBJECT_NAME_E,T1.DETAILED_HEAD_ID,T8.DETAILED_HEAD_NAME_E,T1.DRO_ID "+
															  "FROM IGRS_EXP_HEAD_MAPPING T1 "+
															  "LEFT OUTER JOIN IGRS_EXP_MAJOR_HEAD_MASTER T2 ON T1.MAJOR_HEAD_ID=T2.MAJOR_HEAD_ID "+
															  "LEFT OUTER JOIN IGRS_EXP_SUB_MAJOR_HEAD_MASTER T3 ON T1.SUB_MAJOR_HEAD_ID=T3.SUB_MAJOR_HEAD_ID "+ 
															  "LEFT OUTER JOIN IGRS_EXP_MINOR_HEAD_MASTER T4 ON T1.MINOR_HEAD_ID=T4.MINOR_HEAD_ID "+
															  "LEFT OUTER JOIN IGRS_EXP_SCHEME_MASTER T5 ON T1.SCHEME_ID=T5.SCHEME_ID "+
															  "LEFT OUTER JOIN IGRS_EXP_SEGMENT_MASTER T6 ON T1.SEGMENT_ID=T6.SEGMENT_ID "+
															  "LEFT OUTER JOIN IGRS_EXP_OBJECT_MASTER T7 ON T1.OBJECT_ID=T7.OBJECT_ID "+
															  "LEFT OUTER JOIN IGRS_EXP_DETAILED_HEAD_MASTER T8 ON T1.DETAILED_HEAD_ID=T8.DETAILED_HEAD_ID";
	
	public static final String SELECT_EXP_HEAD_MAPPING_MAJOR_ID="SELECT T1.MAJOR_HEAD_ID,T2.MAJOR_HEAD_NAME_E,T1.SUB_MAJOR_HEAD_ID ,T3.SUB_MAJOR_HEAD_NAME_E,"+
															    "T1.MINOR_HEAD_ID,T4.MINOR_HEAD_NAME_E,T1.SCHEME_ID,T5.SCHEME_NAME_E,T1.SEGMENT_ID,T6.SEGMENT_NAME_E,"+
																"T1.OBJECT_ID,T7.OBJECT_NAME_E,T1.DETAILED_HEAD_ID,T8.DETAILED_HEAD_NAME_E,T1.DRO_ID "+
																"FROM IGRS_EXP_HEAD_MAPPING T1 "+
																"LEFT OUTER JOIN IGRS_EXP_MAJOR_HEAD_MASTER T2 ON T1.MAJOR_HEAD_ID=T2.MAJOR_HEAD_ID "+
																"LEFT OUTER JOIN IGRS_EXP_SUB_MAJOR_HEAD_MASTER T3 ON T1.SUB_MAJOR_HEAD_ID=T3.SUB_MAJOR_HEAD_ID "+ 
																"LEFT OUTER JOIN IGRS_EXP_MINOR_HEAD_MASTER T4 ON T1.MINOR_HEAD_ID=T4.MINOR_HEAD_ID "+
																"LEFT OUTER JOIN IGRS_EXP_SCHEME_MASTER T5 ON T1.SCHEME_ID=T5.SCHEME_ID "+
																"LEFT OUTER JOIN IGRS_EXP_SEGMENT_MASTER T6 ON T1.SEGMENT_ID=T6.SEGMENT_ID "+
																"LEFT OUTER JOIN IGRS_EXP_OBJECT_MASTER T7 ON T1.OBJECT_ID=T7.OBJECT_ID "+
																"LEFT OUTER JOIN IGRS_EXP_DETAILED_HEAD_MASTER T8 ON T1.DETAILED_HEAD_ID=T8.DETAILED_HEAD_ID WHERE T1.MAJOR_HEAD_ID=?";
	
	//Insert Query
	public static final String INSERT_EXP_HEAD_MAPPING_MASTER="INSERT INTO IGRS_EXP_HEAD_MAPPING(MAJOR_HEAD_ID,SUB_MAJOR_HEAD_ID,MINOR_HEAD_ID,SCHEME_ID,SEGMENT_ID,OBJECT_ID,DETAILED_HEAD_ID,DRO_ID) VALUES (?,?,?,?,?,?,?,?)";
	
	//IGRS_EXP_MAJOR_HEAD_MASTER
	
	public static final String SELECT_EXP_MAJOR_HEAD_MASTER = "SELECT MAJOR_HEAD_ID, MAJOR_HEAD_NAME_E,MAJOR_HEAD_DESC ,MAJOR_HEAD_STATUS,CREATED_BY,CREATED_DATE,UPDATE_BY,UPDATE_DATE,MAJOR_HEAD_NAME_H FROM IGRS_EXP_MAJOR_HEAD_MASTER";
	public static final String SELECT_EXP_MAJOR_HEAD_MASTER_ID = "SELECT MAJOR_HEAD_ID, MAJOR_HEAD_NAME_E,MAJOR_HEAD_DESC ,MAJOR_HEAD_STATUS,CREATED_BY,CREATED_DATE,UPDATE_BY,UPDATE_DATE,MAJOR_HEAD_NAME_H FROM IGRS_EXP_MAJOR_HEAD_MASTER WHERE MAJOR_HEAD_ID=?";

	
	//IGRS_EXP_SUB_MAJOR_HEAD_MASTER
	
	public static final String SELECT_EXP_SUB_MAJOR_HEAD_MASTER = "SELECT SUB_MAJOR_HEAD_ID,SUB_MAJOR_HEAD_NAME_E,SUB_MAJOR_HEAD_DESC ,SUB_MAJOR_HEAD_STATUS,CREATED_BY,CREATED_DATE,UPDATE_BY,UPDATE_DATE,SUB_MAJOR_HEAD_NAME_H FROM IGRS_EXP_SUB_MAJOR_HEAD_MASTER";
	public static final String SELECT_EXP_SUB_MAJOR_HEAD_MASTER_ID = "SELECT SUB_MAJOR_HEAD_ID, SUB_MAJOR_HEAD_NAME_E,SUB_MAJOR_HEAD_DESC ,SUB_MAJOR_HEAD_STATUS,CREATED_BY,CREATED_DATE,UPDATE_BY,UPDATE_DATE,SUB_MAJOR_HEAD_NAME_H FROM IGRS_EXP_SUB_MAJOR_HEAD_MASTER WHERE SUB_MAJOR_HEAD_ID=?";

	//IGRS_EXP_MINOR_HEAD_MASTER
	public static final String SELECT_EXP_MINOR_HEAD_MASTER = "SELECT MINOR_HEAD_ID,MINOR_HEAD_NAME_E,MINOR_HEAD_DESC,MINOR_HEAD_STATUS,CREATED_BY,CREATED_DATE,UPDATE_BY,UPDATE_DATE,SUB_MAJOR_HEAD_ID,MINOR_HEAD_NAME_H FROM IGRS_EXP_MINOR_HEAD_MASTER";
	public static final String SELECT_EXP_MINOR_HEAD_MASTER_SUB_MAJOR_ID = "SELECT MINOR_HEAD_ID,MINOR_HEAD_NAME_E,MINOR_HEAD_DESC,MINOR_HEAD_STATUS,CREATED_BY,CREATED_DATE,UPDATE_BY,UPDATE_DATE,MINOR_HEAD_NAME_H FROM IGRS_EXP_MINOR_HEAD_MASTER WHERE SUB_MAJOR_HEAD_ID=?";
	
	//IGRS_EXP_OBJECT_MASTER
	public static final String SELECT_EXP_OBJECT_MASTER = "SELECT OBJECT_ID,OBJECT_NAME_E,OBJECT_DESC,OBJECT_STATUS,CREATED_BY,CREATED_DATE,UPDATE_BY,UPDATE_DATE,OBJECT_NAME_H FROM IGRS_EXP_OBJECT_MASTER";
	
	//IGRS_EXP_SCHEME_MASTER
	public static final String SELECT_EXP_SCHEME_MASTER= "SELECT SCHEME_ID,SCHEME_NAME_E ,SCHEME_DESC,SCHEME_STATUS,CREATED_BY,CREATED_DATE,UPDATE_BY,UPDATE_DATE,SCHEME_NAME_H FROM IGRS_EXP_SCHEME_MASTER";

	//IGRS_EXP_SEGMENT_MASTER
	public static final String SELECT_EXP_SEGMENT_MASTER= "SELECT SEGMENT_ID,SEGMENT_NAME_E,SEGMENT_DESC,SEGMENT_STATUS,CREATED_BY,CREATED_DATE,UPDATE_BY,UPDATE_DATE,SEGMENT_NAME_H FROM IGRS_EXP_SEGMENT_MASTER";
	
	//IGRS_EXP_DETAILED_HEAD_MASTER
	public static final String SELECT_EXP_DETAILED_HEAD_MASTER= "SELECT DETAILED_HEAD_ID,DETAILED_HEAD_NAME_E,DETAILED_HEAD_DESC,DETAILED_HEAD_STATUS,CREATED_BY,CREATED_DATE,UPDATE_BY,UPDATE_DATE,DETAILED_HEAD_NAME_H FROM IGRS_EXP_DETAILED_HEAD_MASTER";
	
	// Delete Query
	public static final String DELETE_EXP_HEAD_MASTER="DELETE FROM IGRS_EXP_HEAD_MAPPING WHERE MAJOR_HEAD_ID=?";
	
	//Update Query
	public static final String UPDATE_EXP_HEAD_MASTER = "UPDATE IGRS_EXP_HEAD_MAPPING SET SUB_MAJOR_HEAD_ID=?,MINOR_HEAD_ID=?, SCHEME_ID=?,SEGMENT_ID=?,OBJECT_ID=?,DETAILED_HEAD_ID=?,DRO_ID=? WHERE MAJOR_HEAD_ID=?";

	
}
