package com.wipro.igrs.salarygrademaster.sql;

public class SalaryGradeCommonSQL {
	
	//Select Query
	public static final String SELECT_ALL_SALARY_GRADE_MASTER = "SELECT IGRS_EMP_SAL_COMP_GRADE_MAP_ID,s.GRADE_ID,SAL_COMPONENT_ID,COMPONENT_VALUE,EMP_ID,g.GRADE_NAME FROM IGRS_EMP_SAL_COMP_GRADE_MAP s,IGRS_EMP_GRADE_MASTER g WHERE s.GRADE_ID=g.GRADE_ID";
	public static final String SELECT_SALARY_GRADE_MASTER_BY_ID = "SELECT IGRS_EMP_SAL_COMP_GRADE_MAP_ID,GRADE_ID,SAL_COMPONENT_ID FROM IGRS_EMP_SAL_COMP_GRADE_MAP WHERE IGRS_EMP_SAL_COMP_GRADE_MAP_ID=?";
	public static final String SELECT_SALARY_GRADE_MASTER_BY_IDS = "SELECT IGRS_EMP_SAL_COMP_GRADE_MAP_ID,GRADE_ID,SAL_COMPONENT_ID,COMPONENT_VALUE,EMP_ID FROM IGRS_EMP_SAL_COMP_GRADE_MAP WHERE GRADE_ID=? AND SAL_COMPONENT_ID=?";
	public static final String SELECT_ALL_GRADE_MASTER = "SELECT GRADE_ID,GRADE_NAME FROM IGRS_EMP_GRADE_MASTER";
	public static final String SELECT_ALL_SALARY_COMPONENTS = "SELECT COMPONENT_ID FROM IGRS_EMP_SALARY_COMPONENTS";
	//Update Query
	public static final String UPDATE_SALARY_GRADE_MASTER = "UPDATE IGRS_EMP_SAL_COMP_GRADE_MAP SET GRADE_ID=?,SAL_COMPONENT_ID=?,COMPONENT_VALUE=?,EMP_ID=? WHERE IGRS_EMP_SAL_COMP_GRADE_MAP_ID=?";
	//Insert Query
	public static final String INSERT_SALARY_GRADE_MASTER = "INSERT INTO IGRS_EMP_SAL_COMP_GRADE_MAP(IGRS_EMP_SAL_COMP_GRADE_MAP_ID,GRADE_ID,SAL_COMPONENT_ID,COMPONENT_VALUE,EMP_ID) VALUES('SAl_GRADE#'||IGRS_EMP_SAL_COMP_GRADE_MAP_SQ.nextval,?,?,?,?)";       
	//Delete Query
	public static final String DELETE_SALARY_GRADE_MASTER = "DELETE FROM IGRS_EMP_SAL_COMP_GRADE_MAP WHERE IGRS_EMP_SAL_COMP_GRADE_MAP_ID=?";

}
