package com.wipro.igrs.treasuryMaster.sql;

public class TreasuryCommonSql {

	// Constants ---------------------------------------------------------------
	// Select Query
	public static final String SELECT_TREASURY_MASTER = 
		"SELECT TREASURY_ID,TREASURY_NAME,TREASURY_ADDRESS,TREASURY_PHONE,STATUS,CREATED_BY,CREATED_DATE,UPDATE_BY,UPDATE_DATE FROM IGRS_TREASURY_MASTER WHERE status <> 'R'";
	
	// Select By Id
	public static final String SELECT_TREASURY_MASTER_ID = 
		"SELECT TREASURY_ID,TREASURY_NAME,TREASURY_ADDRESS,TREASURY_PHONE,STATUS FROM IGRS_TREASURY_MASTER " +
		"WHERE TREASURY_ID=?";

	// Update Query
	public static final String UPDATE_TREASURY_MASTER = 
		"UPDATE IGRS_TREASURY_MASTER SET TREASURY_NAME=?,TREASURY_ADDRESS=?,TREASURY_PHONE=?,STATUS=?,UPDATE_BY=?,UPDATE_DATE=sysdate " +
		"WHERE TREASURY_ID=?";

	// Insert Query
	public static final String INSERT_TREASURY_MASTER = 
		"INSERT INTO IGRS_TREASURY_MASTER(TREASURY_ID,TREASURY_NAME,TREASURY_ADDRESS,TREASURY_PHONE,STATUS,CREATED_BY,CREATED_DATE,UPDATE_BY,UPDATE_DATE) " +
		"VALUES(IGRS_TREASURY_MASTER_SEQ.NEXTVAL,?,?,?,'A',?,sysdate,?,sysdate)";
	
	//test existance of a record by name
	public static final String SELECT_TREASURY_MASTER_EXIST = 
		"SELECT * FROM IGRS_TREASURY_MASTER where TREASURY_NAME=?";
	
	public static final String SELECT_TREASURY_MASTER_EXIST_ID = 
		"SELECT * FROM IGRS_TREASURY_MASTER where TREASURY_ID=? AND TREASURY_NAME=?  ";
	
	public static final String DELETE_TREASURY_MASTER = 
		"UPDATE IGRS_TREASURY_MASTER SET STATUS='R',UPDATE_BY=?,UPDATE_DATE=sysdate WHERE TREASURY_ID=?";
}
