package com.wipro.igrs.etaal.sql;

public class EtaalSQL {

	public static final String	ESTAMP_COUNT							= "SELECT COUNT(*) FROM IGRS_ESTAMP_DOCUMENT_DETLS WHERE ESTAMP_TXN_ID IN(SELECT ESTAMP_TXN_ID "
																				+ "FROM IGRS_ESTAMP_PAYMENT_DETLS WHERE TRUNC(CREATED_DATE) = TO_DATE(?, 'DD/MM/YYYY'))";

	public static final String	REGISTRATION_INITIATION_COUNT			= "SELECT COUNT(*) FROM IGRS_REG_TXN_DETLS WHERE REGISTRATION_TXN_STATUS = '10' AND TRUNC(UPDATE_DATE) = TO_DATE(?,'DD/MM/YYYY')";

	public static final String	ONLINE_PAYMENT_ESTAMP_COUNT				= "SELECT COUNT(*) FROM IGRS_CREDIT_LIMIT_TXN_ESTAMP WHERE PAYMENT_MODE_ID = '4' AND TRUNC(UPDATE_DATE) = TO_DATE(?,'DD/MM/YYYY')";

	public static final String	ONLINE_PAYMENT_REGISTRATION_FEE_COUNT	= "SELECT COUNT(*) FROM IGRS_CREDIT_LIMIT_TXN_LOG WHERE PAYMENT_MODE_ID = '4' AND TRUNC(UPDATE_DATE) = TO_DATE(?,'DD/MM/YYYY')";

	public static final String	ONLINE_PREPARATION_OF_DEEDS_COUNT		= "SELECT COUNT(*) FROM IGRS_DEED_DRAFT_TXN_DTLS WHERE TO_CHAR(CREATED_DATE, 'DD/MM/YYYY') = ?";

	public static final String	EREGISTRATION_BY_SUB_REGISTRARS_COUNT	= "SELECT COUNT(*) FROM IGRS_REG_TXN_DETLS WHERE TRUNC(UPDATE_DATE) = TO_DATE(?,'DD/MM/YYYY') AND REGISTRATION_TXN_STATUS = '17' AND UPDATE_BY IN(SELECT USER_ID FROM IGRS_USERS_LIST WHERE USER_TYPE_ID = 'I')";

	public static final String	ONLINE_SEARCH_EREGISTERED_DOC_COUNT		= "SELECT COUNT(*) FROM IGRS_DOC_SEARCH_DETAILS WHERE FUNCTION_ID IN ('FUN_062','FUN_063','FUN_064') AND TRUNC(CREATED_DATE) = TO_DATE(?,'DD/MM/YYYY')";

	public static final String	REVENUE_GENERATION_STAMP_DUTY			= "SELECT SUM(A.STAMP_DUTY) FROM IGRS_REG_INIT_STAMP_DUTY_DETLS A, IGRS_REG_TXN_DETLS B WHERE A.REG_TXN_ID = B.REG_TXN_ID AND B.REGISTRATION_TXN_STATUS = '17' AND TRUNC(A.UPDATE_DATE) = TO_DATE(?,'DD/MM/YYYY')";

	public static final String	REVENUE_GENERATION_REGISTRATION_FEE		= "SELECT SUM(A.REG_FEE) FROM IGRS_REG_INIT_STAMP_DUTY_DETLS A, IGRS_REG_TXN_DETLS B WHERE A.REG_TXN_ID = B.REG_TXN_ID AND B.REGISTRATION_TXN_STATUS = '17' AND TRUNC(A.UPDATE_DATE) = TO_DATE(?,'DD/MM/YYYY')";

	public static final String	PROPERTY_VALUATION_COUNT				= "SELECT COUNT(*) FROM IGRS_PROP_VAL_TXN_DETLS WHERE TO_CHAR (CREATED_DATE,'DD/MM/YYYY') = ?";

	public static final String	DUTY_CALCULATION_COUNT					= "SELECT COUNT(*) FROM IGRS_DUTY_TXN_DETLS WHERE TO_CHAR (CREATED_DATE,'DD/MM/YYYY') = ?";

	public static final String	DOWNLOAD_EREGISTERED_DOC_COUNT			= "SELECT COUNT(*) FROM IGRS_DOC_SEARCH_DETAILS WHERE FUNCTION_ID IN ('FUN_062','FUN_063','FUN_064') AND DOC_SEARCH_STATUS = 'Y' AND TRUNC(CREATED_DATE) = TO_DATE(?,'DD/MM/YYYY')";

	public static final String	PIN_GENERATION_COUNT					= "SELECT COUNT(*) FROM IGRS_REG_PROPRTY_DTLS WHERE PIN_NO IS NOT NULL AND TRUNC(UPDATE_DATE) = TO_DATE(?,'DD-MM-YYYY')";

	public static final String	ACTIVE_SERVICE_PROVIDER_COUNT			= "SELECT COUNT(LICENSE_NUMBER) FROM IGRS_SP_DETLS WHERE APPLCTN_STATUS = 8 AND STATUS = 'A' "
																				+ "AND TRUNC(UPDATE_DATE) = TO_DATE(?, 'DD/MM/YYYY')";

	public static final String	SLOT_BOOK_COUNT							= "SELECT COUNT(*) FROM IGRS_REG_SLOT_BLOCK_DETAILS WHERE TO_CHAR(BLOCKED_DATE, 'DD/MM/YYYY') = ?";

	public static final String	INSERT_ETRANSACTION_DATA				= "INSERT INTO IGRS_ETAAL_ETRANX_DTLS (SERVICE_CODE, SERVICE_COUNT, URL_DATE, CREATED_DATE) VALUES (?, ? ,TO_DATE(?, 'DD/MM/YYYY'), TRUNC(SYSDATE))";
	
	public static final String	GET_ETRANSACTION_DATA					= "SELECT SERVICE_CODE, SERVICE_COUNT FROM IGRS_ETAAL_ETRANX_DTLS WHERE TO_CHAR (URL_DATE,'DD/MM/YYYY') = ?";

}
