package com.wipro.igrs.faqonlinequery.sql;

public class FaqOnlineQuerySQL {
	public static final String GET_FAQ_DETAILS_ENGLISH="SELECT QUESTION,ANSWER FROM IGRS_FAQ_DETAILS_MASTER WHERE UPPER(LANGUAGE_FLAG)='E' AND STATUS='A'";
    public static final String IGRS_COUNTRY_MASTER="SELECT COUNTRY_ID,COUNTRY_NAME FROM IGRS_COUNTRY_MASTER WHERE COUNTRY_STATUS='A'";
    public static final String IGRS_STATE_MASTER="SELECT STATE_ID,STATE_NAME FROM IGRS_STATE_MASTER WHERE COUNTRY_ID=? AND STATE_STATUS='A'";
    public static final String IGRS_DISTRICT_MASTER="SELECT DISTRICT_ID, DISTRICT_NAME FROM IGRS_DISTRICT_MASTER WHERE STATE_ID=? AND DISTRICT_STATUS='A'";
    public static final String SUBMIT_QUERY="INSERT INTO IGRS_ONLINE_QUERY_DETAILS(QUERY_TXN_ID,NAME,ADDRESS,EMAIL,COUNTRY,STATE,DISTRICT,CONATCT_NUMBER,MOBILE_NUMBER,QUERY,STATUS,CREATED_BY,CREATED_DATE) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,SYSDATE)";
    public static final String EMAIL_DATA="INSERT INTO IGRS_EMAIL_DATA_CONTENT(EMAIL_DISPATCH_ID, EMAIL_TO_ADDRESS,"+
    "EMAIL_SUBJECT, EMAIL_CONTENT, EMAIL_HEADER, EMAIL_FOOTER, EMAIL_SENT_FLAG, CREATED_BY,"+ 
	"CREATED_DATE, UPDATE_BY, UPDATE_DATE, EMAIL_FROM_ADDRESS)"+
    "VALUES(IGRS_EMAIL_SENT_SEQ1.NEXTVAL,?,?,"+
	"?,'Dear Sir/Madam','Thanks & Regards','N','System',SYSDATE,'System',SYSDATE,'igrs@mp.gov')";
    public static final String GET_REPLY_DAHBOARD="SELECT QUERY_TXN_ID,TO_CHAR(CREATED_DATE,'dd/mm/yyyy'),STATUS FROM IGRS_ONLINE_QUERY_DETAILS WHERE STATUS='A' ORDER BY CREATED_DATE DESC";
    public static final String GET_SEARCH_DAHBOARD="SELECT QUERY_TXN_ID,TO_CHAR(CREATED_DATE,'dd/mm/yyyy'),STATUS FROM IGRS_ONLINE_QUERY_DETAILS WHERE 1=1";
    public static final String GET_REPLY_DETAILS="SELECT Q.NAME,Q.ADDRESS,EMAIL,C.COUNTRY_NAME,D.DISTRICT_NAME,S.STATE_NAME,Q.CONATCT_NUMBER,Q.MOBILE_NUMBER,Q.QUERY,Q.ANSWER FROM" +
    		" IGRS_ONLINE_QUERY_DETAILS Q,IGRS_COUNTRY_MASTER C,IGRS_DISTRICT_MASTER D,IGRS_STATE_MASTER S WHERE Q.DISTRICT=D.DISTRICT_ID AND Q.COUNTRY=C.COUNTRY_ID AND Q.STATE=S.STATE_ID AND Q.QUERY_TXN_ID=?";

    public static final String UPDATE_REPLY="UPDATE IGRS_ONLINE_QUERY_DETAILS SET ANSWER=?,UPDATED_DATE=SYSDATE,STATUS='R',UPDATED_BY=? WHERE QUERY_TXN_ID=?";
    public static final String IGRS_COUNTRY_MASTER_HINDI="SELECT COUNTRY_ID,COUNTRY_NAME,H_COUNTRY_NAME FROM IGRS_COUNTRY_MASTER WHERE COUNTRY_STATUS='A' ORDER BY COUNTRY_NAME";
    public static final String IGRS_STATE_MASTER_HINDI="SELECT STATE_ID,STATE_NAME,H_STATE_NAME FROM IGRS_STATE_MASTER WHERE COUNTRY_ID=? AND STATE_STATUS='A' ORDER BY STATE_NAME";
    public static final String IGRS_DISTRICT_MASTER_HINDI="SELECT DISTRICT_ID, DISTRICT_NAME,H_DISTRICT_NAME FROM IGRS_DISTRICT_MASTER WHERE STATE_ID=? AND DISTRICT_STATUS='A' ORDER BY DISTRICT_NAME";
    public static final String GET_REPLY_DETAILS_HINDI="SELECT Q.NAME,Q.ADDRESS,EMAIL,C.COUNTRY_NAME,D.DISTRICT_NAME,S.STATE_NAME,Q.CONATCT_NUMBER,Q.MOBILE_NUMBER,Q.QUERY,Q.ANSWER,C.H_COUNTRY_NAME,S.H_STATE_NAME,D.H_DISTRICT_NAME FROM" +
	" IGRS_ONLINE_QUERY_DETAILS Q,IGRS_COUNTRY_MASTER C,IGRS_DISTRICT_MASTER D,IGRS_STATE_MASTER S WHERE Q.DISTRICT=D.DISTRICT_ID AND Q.COUNTRY=C.COUNTRY_ID AND Q.STATE=S.STATE_ID AND Q.QUERY_TXN_ID=?";
    public static final String GET_FAQ_DETAILS_HINDI="SELECT QUESTION,ANSWER FROM IGRS_FAQ_DETAILS_MASTER WHERE UPPER(LANGUAGE_FLAG)='H' AND STATUS='A'";


}
