package com.wipro.igrs.functiontorolemapping.sql;


public class FunToRoleMappingCommonSql 
{
	public static final String INSERT_FUN_TO_ROLE_MAPPING = 
		"INSERT INTO IGRS_ROLE_FN_ACTIVITY_MAPPING(IGRS_ROLE_FN_ACTIVITY_MAP_ID,FUNCTION_ID,ACTIVITY_ID,ROLE_ID,MODULE_ID,SUB_MODULE_ID) " +
		"VALUES('RFAM'||IGRS_ROLE_FN_ACTIVITY_MAP_SEQ.NEXTVAL,?,?,?,?,?)";
	
	// Update Query
	public static final String UPDATE_FUN_TO_ROLE_MAPPING = 
		"UPDATE IGRS_ROLE_FN_ACTIVITY_MAPPING SET FUNCTION_ID=?,ACTIVITY_ID=?,ROLE_ID=?,MODULE_ID=?,SUB_MODULE_ID=? " +
		"WHERE IGRS_ROLE_FN_ACTIVITY_MAP_ID=?";
	
	public static final String SELECT_FUN_TO_ROLE_MAPPING = 
		"SELECT FUNCTION_ID,ACTIVITY_ID,ROLE_ID,MODULE_ID,SUB_MODULE_ID,IGRS_ROLE_FN_ACTIVITY_MAP_ID FROM IGRS_ROLE_FN_ACTIVITY_MAPPING";
	
	public static final String SELECT_FUN_TO_ROLE_MAPPING_DETAILED = 
		"SELECT i.FUNCTION_ID,i.ACTIVITY_ID,i.ROLE_ID,i.MODULE_ID,i.SUB_MODULE_ID,i.IGRS_ROLE_FN_ACTIVITY_MAP_ID,MODULE_NAME,ACTIVITY_NAME,FUNCTION_NAME,ROLE_NAME,SUB_MODULE_NAME FROM IGRS_ROLE_FN_ACTIVITY_MAPPING i,IGRS_FUNCTION_MASTER f,IGRS_ACTIVITY_MASTER ac,IGRS_SUB_MODULE_MASTER sm,IGRS_MODULE_MASTER m,IGRS_ROLE_MASTER r WHERE i.MODULE_ID = m.MODULE_ID and i.SUB_MODULE_ID = sm.SUB_MODULE_ID and i.ACTIVITY_ID = ac.ACTIVITY_ID and i.FUNCTION_ID = f.FUNCTION_ID and i.ROLE_ID = r.ROLE_ID";
	
	public static final String SELECT_FUN_TO_ROLE_MAPPING_BY_ID = 
		"SELECT FUNCTION_ID,ACTIVITY_ID,ROLE_ID,MODULE_ID,SUB_MODULE_ID,IGRS_ROLE_FN_ACTIVITY_MAP_ID FROM IGRS_ROLE_FN_ACTIVITY_MAPPING " +
		"WHERE IGRS_ROLE_FN_ACTIVITY_MAP_ID=?";
	
	public static final String SELECT_FUN_TO_ROLE_MAPPING_EXISTS = 
		"SELECT * FROM IGRS_ROLE_FN_ACTIVITY_MAPPING " +
		"WHERE FUNCTION_ID=? AND ACTIVITY_ID=? AND ROLE_ID=? AND MODULE_ID=? AND SUB_MODULE_ID=?";
	
	public static final String SELECT_SUBMODULES_TO_THIS_MODULE = 
		"select SUB_MODULE_ID,SUB_MODULE_NAME from IGRS_SUB_MODULE_MASTER WHERE MODULE_ID=?";
	
	public static final String SELECT_FUNCTIONS_TO_THIS_SUBMODULE = 
		"select FUNCTION_ID,FUNCTION_NAME from IGRS_FUNCTION_MASTER WHERE SUB_MODULE_ID=?";
	
	public static final String DELETE_FUN_TO_ROLE_MAPPING = 
		"DELETE FROM IGRS_ROLE_FN_ACTIVITY_MAPPING WHERE IGRS_ROLE_FN_ACTIVITY_MAP_ID=?";
	
}
