/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */


package com.wipro.igrs.departmentalenquiry.form;


import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import com.wipro.igrs.baseaction.form.BaseForm;
import com.wipro.igrs.departmentalenquiry.dto.ChargeSheetReleaseDTO;


/** 
 * MyEclipse Struts
 * Creation date: 06-12-2008
 * 
 * XDoclet definition:
 * @struts.form name="chargesheetCloseForm"
 */
public class ChargesheetCloseForm extends BaseForm {
	/*
	 * Generated Methods
	 */
	private ChargeSheetReleaseDTO chargeSheetDTO = new ChargeSheetReleaseDTO();
	
	private String strComment;

	/**
     * @return the strComment
     */
    public String getStrComment() {
    	return strComment;
    }

	/**
     * @param strComment the strComment to set
     */
    public void setStrComment(String strComment) {
    	this.strComment = strComment;
    }

	/**
     * @return the chargeSheetDTO
     */
    public ChargeSheetReleaseDTO getChargeSheetDTO() {
    	return chargeSheetDTO;
    }

	/**
     * @param chargeSheetDTO the chargeSheetDTO to set
     */
    public void setChargeSheetDTO(ChargeSheetReleaseDTO chargeSheetDTO) {
    	this.chargeSheetDTO = chargeSheetDTO;
    }

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
	        HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
}