/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */

package com.wipro.igrs.departmentalenquiry.form;

import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;

import com.wipro.igrs.departmentalenquiry.dto.WitnessDTO;

/**
 * MyEclipse Struts Creation date: 06-09-2008
 * 
 * XDoclet definition:
 * 
 * @struts.form name="uploadWitnessForm"
 */
public class UploadWitnessForm extends ActionForm {
	/*
	 * Generated Methods
	 */
	private String attachAction;

	private String removeAction;

	private ArrayList listWitnessDTO;

	private FormFile theFile = null;

	private String strEnqOfficerName;

	private WitnessDTO witnessDTO = new WitnessDTO();

	/**
	 * @return the attachAction
	 */
	public String getAttachAction() {
		return attachAction;
	}

	/**
	 * @param attachAction
	 *            the attachAction to set
	 */
	public void setAttachAction(String attachAction) {
		this.attachAction = attachAction;
	}

	/**
	 * @return the removeAction
	 */
	public String getRemoveAction() {
		return removeAction;
	}

	/**
	 * @param removeAction
	 *            the removeAction to set
	 */
	public void setRemoveAction(String removeAction) {
		this.removeAction = removeAction;
	}

	/**
	 * Method validate
	 * 
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/**
	 * Method reset
	 * 
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/**
	 * @return the listWitnessDTO
	 */
	public ArrayList getListWitnessDTO() {
		return listWitnessDTO;
	}

	/**
	 * @param listWitnessDTO
	 *            the listWitnessDTO to set
	 */
	public void setListWitnessDTO(ArrayList listWitnessDTO) {
		this.listWitnessDTO = listWitnessDTO;
	}

	/**
	 * @return the theFile
	 */
	public FormFile getTheFile() {
		return theFile;
	}

	/**
	 * @param theFile
	 *            the theFile to set
	 */
	public void setTheFile(FormFile theFile) {
		this.theFile = theFile;
	}

	/**
	 * @return the witnessDTO
	 */
	public WitnessDTO getWitnessDTO() {
		return witnessDTO;
	}

	/**
	 * @param witnessDTO
	 *            the witnessDTO to set
	 */
	public void setWitnessDTO(WitnessDTO witnessDTO) {
		this.witnessDTO = witnessDTO;
	}

	/**
	 * @return the strEnqOfficerName
	 */
	public String getStrEnqOfficerName() {
		return strEnqOfficerName;
	}

	/**
	 * @param strEnqOfficerName
	 *            the strEnqOfficerName to set
	 */
	public void setStrEnqOfficerName(String strEnqOfficerName) {
		this.strEnqOfficerName = strEnqOfficerName;
	}
}