

package com.wipro.igrs.departmentalenquiry.sql;

public class DepartmentalEnquirySQL {
	public static final String	REG_USER_DETAILS	         = "SELECT TT1.USER_ID,T1.FIRST_NAME||' '||T1.MIDDLE_NAME||' '||T1.LAST_NAME AS NAME,T1.ADDRESS,T1.MOBILE_NUMBER,T1.EMAIL_ID,T2.DISTRICT_NAME"
		+ " FROM IGRS_USERS_LIST TT1,IGRS_USER_REG_DETAILS T1, IGRS_DISTRICT_MASTER T2"
		+ " WHERE TT1.USER_ID=T1.USER_ID AND T1.DISTRICT_ID=T2.DISTRICT_ID AND TT1.USER_ID LIKE ?";

	public static final String	EMP_DETAILS	                 = "SELECT T1.EMP_ID,T1.FIRST_NAME||' '||T1.MIDDLE_NAME||' '||T1.LAST_NAME AS NAME,"
		+ " T1.PRESENT_ADDRESS,T1.MOBILE_NUMBER,T1.EMAIL,T2.DISTRICT_NAME,T3.CADRE_NAME FROM"
		+ " IGRS_EMP_MASTER T1,IGRS_DISTRICT_MASTER T2,IGRS_EMP_CADRE_MASTER T3,IGRS_EMP_OFFICIAL_DETAILS T4"
		+ " WHERE T1.PRESENT_DISTRICT=T2.DISTRICT_ID AND T1.EMP_ID=T4.EMP_ID AND T4.EMP_DESIGNATION_ID=T3.CADRE_ID AND T1.EMP_ID LIKE ?";

	public static final String	COMPLAINER_REG_USER_DETAILS	 = "SELECT TT1.USER_ID,T1.FIRST_NAME||' '||T1.MIDDLE_NAME||' '||T1.LAST_NAME AS NAME,T1.ADDRESS,T1.MOBILE_NUMBER,T1.EMAIL_ID"
		+ " FROM IGRS_USERS_LIST TT1,IGRS_USER_REG_DETAILS T1 WHERE TT1.USER_ID=T1.USER_ID AND TT1.USER_ID LIKE ?";

	public static final String	COMPLAINER_EMP_DETAILS	     = "SELECT T1.EMP_ID,T1.FIRST_NAME||' '||T1.MIDDLE_NAME||' '||T1.LAST_NAME AS NAME,"
		+ " T1.PRESENT_ADDRESS,T1.MOBILE_NUMBER,T1.EMAIL,T2.DESIG_NAME FROM"
		+ " IGRS_EMP_MASTER T1,IGRS_EMP_DESIGNATION_MASTER T2,IGRS_EMP_OFFICIAL_DETAILS T3"
		+ " WHERE  T1.EMP_ID=T3.EMP_ID AND T3.EMP_DESIGNATION_ID=T2.DESIG_ID AND T1.EMP_ID LIKE ?";

	public static final String	SUBMIT_CRIMINAL_CASE	     = "INSERT INTO IGRS_EMP_COMPLAINT_DETAILS (COMPLAINER_USER_ID,COMPLAINEE_USER_ID,CRIMINAL_COMPLAINT,DETAILS_OF_COMPLAINT,"
		+ " CREATED_DATE,COMPLAINT_STATUS,DEPUTED_PE_USER_ID,DEPUTED_DATE,CREATED_BY,UPDATE_BY,UPDATE_DATE,MAJOR_STATUS,COMPLAINT_NO)"
		+ " VALUES(?,?,?,?,?,?,?,?,?,?,SYSDATE,?,?)";
	
	
	public static final String	SUBMIT_CRIMINAL_CASE_COMPLAINT	     = "INSERT INTO IGRS_EMP_COMPLAINT_STATUS_DTLS (COMPLAINT_NO,COMPLAINT_STATUS,COMPLAINT_STATUS_DATE)"
		+ " VALUES(?,?,?)";
	

	public static final String	COMPLAINT_DETAILS	         = "SELECT COMPLAINT_NO,CREATED_BY,COMPLAINT_STATUS,to_char(CREATED_DATE,'DD/MM/YYYY') FROM IGRS_EMP_COMPLAINT_DETAILS"
		+ " WHERE COMPLAINT_STATUS='Registered' AND COMPLAINT_NO LIKE ? ORDER BY CREATED_DATE";

	public static final String	COMPLAINT_COMPLAINEE_DETAILS	= "select T1.FIRST_NAME||' '||T1.MIDDLE_NAME||' '||T1.LAST_NAME AS NAME,T1.ADDRESS,T1.MOBILE_NUMBER,T1.EMAIL_ID,"
		+ " to_char(T2.CREATED_DATE,'DD/MM/YYYY'),T2.DETAILS_OF_COMPLAINT FROM IGRS_USER_REG_DETAILS T1,IGRS_EMP_COMPLAINT_DETAILS T2"
		+ " WHERE T2.COMPLAINEE_USER_ID = T1.USER_ID AND T2.COMPLAINT_NO=?";

	public static final String	COMPLAINT_COMPLAINER_DETAILS	= "select T1.FIRST_NAME||' '||T1.MIDDLE_NAME||' '||T1.LAST_NAME AS NAME,T1.ADDRESS,T1.MOBILE_NUMBER,T1.EMAIL_ID"
		+ " FROM IGRS_USER_REG_DETAILS T1,IGRS_EMP_COMPLAINT_DETAILS T2"
		+ " WHERE T2.COMPLAINER_USER_ID = T1.USER_ID AND T2.COMPLAINT_NO=?";

	public static final String	DE_INITIATE_SUBMIT	         = "UPDATE  IGRS_EMP_COMPLAINT_DETAILS SET DEPUTED_PE_USER_ID=?,"
		+ " DEPUTED_DATE=SYSDATE,UPDATE_BY=?,UPDATE_DATE=SYSDATE,COMPLAINT_STATUS=? WHERE COMPLAINT_NO=?";
	
	public static final String	DE_INITIATE_UPDATE_COMPLAINT  = "UPDATE IGRS_EMP_COMPLAINT_STATUS_DTLS SET COMPLAINT_STATUS=?,COMPLAINT_STATUS_DATE=SYSDATE"
			+" WHERE COMPLAINT_NO=?";
	
	public static final String GET_PRE_ENQUIRY_DETAILS =
		"SELECT iurd.first_name||' '||iurd.middle_name||' '||iurd.last_name"+
        ",iurd.address,iurd.mobile_number"+
        ",iurd.email_id,ird.first_name||' '||ird.middle_name||' '||ird.last_name"+
        ",ird.ADDRESS,ird.mobile_number,ird.email_id"+
        ",iud.first_name||' '||iud.middle_name||' '||iud.last_name,iud.ADDRESS"+
        ",iud.mobile_number,iud.email_id,iecd.details_of_complaint,to_char(iecd.created_date,'DD/MM/YYYY')"+
        " FROM igrs_emp_complaint_details iecd,igrs_user_reg_details iurd,igrs_user_reg_details ird,igrs_user_reg_details iud"+
        " WHERE iecd.complainee_user_id = ird.user_id AND iecd.complainer_user_id = iurd.user_id AND iecd.deputed_pe_user_id = iud.user_id"+
        " AND iecd.complaint_no = ?";
	
	public static final String	PRE_ENQUIRY_COMPLAINT_DETAILS	         = "SELECT COMPLAINT_NO,CREATED_BY,COMPLAINT_STATUS,to_char(CREATED_DATE,'DD/MM/YYYY') FROM IGRS_EMP_COMPLAINT_DETAILS"
		+ " WHERE COMPLAINT_STATUS='Initiated' AND COMPLAINT_NO LIKE ? ORDER BY CREATED_DATE DESC";
	
	public static final String	EMP_ACCEPT_UPDATE_DETAILS	         = "UPDATE IGRS_EMP_COMPLAINT_DETAILS SET COMPLAINT_STATUS=?,"
		+" UPDATE_BY=?,MAJOR_STATUS=? WHERE COMPLAINT_NO=?";
	
	public static final String	EMP_ACCEPT_COMPLAINT_ACTION_DETAILS	         = "INSERT INTO IGRS_EMP_COMPLAINT_ACTION_DTLS"
		+"(CHARGE_DETAILS,USER_REMARKS,COMPLAINT_NO) VALUES(?,?,?) ";
	
	public static final String	EMP_ACCEPT_COMPLAINT_COMMENT_DETAILS	         = "INSERT INTO IGRS_EMP_COMPLAINT_COMMENTS"
		+"(COMPLAINT_NO,USER_ID,PRE_ENQUIRY_DETAILS,USER_COMMENTS_DATE,COMPLAINT_ACTION_STATUS,USER_COMMENTS) VALUES(?,?,?,?,?,?)";
	
	public static final String	EMP_ACCEPT_COMPLAINT_STATUS_UPDATE	         = "UPDATE IGRS_EMP_COMPLAINT_STATUS_DTLS"
		+" SET COMPLAINT_STATUS=?, COMPLAINT_STATUS_DATE=? WHERE COMPLAINT_NO=?";
	
	public static final String	PRE_ENQUIRY_COMPLAINT_DOC_MAP	         = "INSERT INTO IGRS_EMP_COMPLAINT_DOC_MAP"
		+"(COMPLAINT_NO,DOCUMENT_NAME,DOCUMENT_OBJECT,DOCUMENT_TYPE,DOCUMENT_UPLOAD_DATE) VALUES(?,?,?,?,?)";
	
	// SAI
	public static final String  GET_DEPUTED_DETAILS = 
	"SELECT iurd.first_name||' '||iurd.middle_name||' '||iurd.last_name"+
    ",iurd.address,iurd.mobile_number"+
    ",iurd.email_id,ird.first_name||' '||ird.middle_name||' '||ird.last_name"+
    ",ird.ADDRESS,ird.mobile_number,ird.email_id"+
    ",iud.first_name||' '||iud.middle_name||' '||iud.last_name,iud.ADDRESS"+
    ",iud.mobile_number,iud.email_id,iecd.details_of_complaint,to_char(iecd.created_date,'DD/MM/YYYY')"+
    " FROM igrs_emp_complaint_details iecd,igrs_user_reg_details iurd,igrs_user_reg_details ird,igrs_user_reg_details iud"+
    " WHERE iecd.complainee_user_id = ird.user_id AND iecd.complainer_user_id = iurd.user_id AND iecd.deputed_pe_user_id = iud.user_id"+
    " AND iecd.complaint_no = ?";
	
	public static final String GET_SUSP_ACCEPTED_DETAILS = 
		"SELECT IECAD.FINAL_CHARGE, IECD.MAJOR_STATUS FROM IGRS_EMP_COMPLAINT_DETAILS IECD, IGRS_EMP_COMPLAINT_ACTION_DTLS IECAD"
       +" WHERE IECD.COMPLAINT_NO = IECAD.COMPLAINT_NO AND IECD.COMPLAINT_NO = ?";
	
	public static final String GET_SUSP_PRE_ENQ_DETAILS =
		 "SELECT IECC.PRE_ENQUIRY_DETAILS, IECC.USER_COMMENTS, to_char(IECD.DEPUTED_DATE,'DD/MM/YYYY'), IECDM.DOCUMENT_NAME ,IECDM.DOCUMENT_TYPE,IECDM.DOCUMENT_ID FROM"
		+" IGRS_EMP_COMPLAINT_DETAILS IECD, IGRS_EMP_COMPLAINT_COMMENTS IECC, IGRS_EMP_COMPLAINT_DOC_MAP IECDM"
        +" WHERE IECD.COMPLAINT_NO = IECC.COMPLAINT_NO AND IECD.COMPLAINT_NO = IECDM.COMPLAINT_NO"
        +" AND IECD.COMPLAINT_NO = ?";
	 
	public static final String GET_INITIAITED_ACCEPTED_COMPLAINT_DETAILS = "SELECT COMPLAINT_NO,CREATED_BY,COMPLAINT_STATUS,to_char(CREATED_DATE,'DD/MM/YYYY') FROM IGRS_EMP_COMPLAINT_DETAILS"
															+" WHERE COMPLAINT_NO LIKE ? AND COMPLAINT_STATUS='Suspension' OR COMPLAINT_STATUS='Initiated' ORDER BY CREATED_DATE DESC"; 
	
	//public static final String GET_EMPLOYEES_FOR_SUSPENSION_ORDER = "SELECT M.EMP_ID, M.FIRST_NAME||''||M.MIDDLE_NAME||''||M.LAST_NAME, M.GENDER, D.DESIG_NAME FROM IGRS_EMP_MASTER M, IGRS_EMP_DESIGNATION_MASTER D WHERE M.EMP_ID LIKE ?";
	
	public static final String	PRE_SUSPENSION_COMPLAINT_ACTION_DETAILS	         = "INSERT INTO  IGRS_EMP_COMPLAINT_ACTION_DTLS"
		+" (COMPLAINT_ACTION,CHARGE_DETAILS,ISSUED_AUTHORITY,DATE_OF_ISSUANCE,ISSUED_USER_ID,USER_REMARKS,FINAL_CHARGE,PLACE_OF_ISSUANCE,ADDRESS,COMPLAINT_NO)"
		+" VALUES(?,?,?,?,?,?,?,?,?,?)";
	
	public static final String	PRE_SUSPENSION_COMPLAINT_COMMENT_DETAILS	         = "INSERT INTO IGRS_EMP_COMPLAINT_COMMENTS"
		+" (USER_ID,PRE_ENQUIRY_DETAILS,USER_COMMENTS_DATE,COMPLAINT_ACTION_STATUS,USER_COMMENTS,COMPLAINT_NO)"
		+" VALUES(?,?,?,?,?,?)";
	
	public static final String GET_COMPLAINT_STATUS = "SELECT COMPLAINT_STATUS FROM IGRS_EMP_COMPLAINT_DETAILS WHERE COMPLAINT_NO = ? ORDER BY CREATED_DATE DESC";
	
	//SUSPENSION
	public static final String UPDATE_PE_COMMENTS = "UPDATE IGRS_EMP_COMPLAINT_COMMENTS SET  USER_ID = ?," 
													+" USER_COMMENTS_DATE = ?,  COMPLAINT_ACTION_STATUS = ? WHERE   COMPLAINT_NO = ?";
	
	public static final String UPDATE_COMPLAINT_DETAILS  = "UPDATE  IGRS_EMP_COMPLAINT_DETAILS SET COMPLAINT_STATUS = ?,  MAJOR_STATUS = ?,"
														   +" UPDATE_BY = ?,  UPDATE_DATE = ? WHERE COMPLAINT_NO = ?";
	
	public static final String INSERT_COMPLAINT_ACTION_DETAILS = "INSERT INTO IGRS_EMP_COMPLAINT_ACTION_DTLS " 
		  +"(ISSUED_AUTHORITY, DATE_OF_ISSUANCE, CHARGE_DETAILS, USER_REMARKS, COMPLAINT_ACTION, FINAL_CHARGE, PLACE_OF_ISSUANCE, ADDRESS,  COMPLAINT_NO, ISSUED_USER_ID)"
		  + " VALUES(?,?,?,?,?,?,?,?,?,?)";
	
	public static final String UPDATE_COMPLAINT_STATUS = "UPDATE IGRS_EMP_COMPLAINT_STATUS_DTLS SET COMPLAINT_STATUS=?, COMPLAINT_STATUS_DATE=?"
														 +"WHERE COMPLAINT_NO = ?";

	public static final String INSERT_PE_COMMENTS = "INSERT INTO IGRS_EMP_COMPLAINT_COMMENTS(USER_ID, USER_COMMENTS, USER_COMMENTS_DATE, COMPLAINT_ACTION_STATUS, PRE_ENQUIRY_DETAILS, COMPLAINT_NO)"
													+" VALUES(?, ?, ?, ?, ?, ?)";

	
	public static final String	CHARGESHEET_COMPLAINT_DETAILS	         = "SELECT COMPLAINT_NO, CREATED_BY,COMPLAINT_STATUS,to_char(CREATED_DATE,'DD/MM/YYYY') FROM IGRS_EMP_COMPLAINT_DETAILS"
		+ " WHERE COMPLAINT_STATUS='Suspension' AND COMPLAINT_NO LIKE ? ORDER BY CREATED_DATE DESC";
	
	
	
	public static final String CHARGESHEET_ENQUIRY_DETAILS =
		
		"SELECT iurd.first_name||' '||iurd.middle_name||' '||iurd.last_name,iurd.address,iurd.mobile_number,iurd.email_id" 
        +" FROM igrs_emp_complaint_details iecd,igrs_user_reg_details iurd"
        +" WHERE iecd.complainee_user_id = iurd.user_id AND iecd.complaint_no =?";
	
	public static final String UPDATE_COMPLAINT_ACTION_DETAILS = "UPDATE IGRS_EMP_COMPLAINT_ACTION_DTLS SET " 
		  +"ISSUED_AUTHORITY=?, DATE_OF_ISSUANCE=?, CHARGE_DETAILS=?, USER_REMARKS=?, COMPLAINT_ACTION=?, FINAL_CHARGE=?, PLACE_OF_ISSUANCE=?, ADDRESS=?, ISSUED_USER_ID=? WHERE  COMPLAINT_NO=?";
	
	public static final String GET_SUSPENDED_COMPLAINT_DETAILS = 
	"SELECT COMPLAINT_NO,CREATED_BY,COMPLAINT_STATUS,to_char(CREATED_DATE,'DD/MM/YYYY') FROM IGRS_EMP_COMPLAINT_DETAILS"
	+" WHERE COMPLAINT_NO LIKE ? AND COMPLAINT_STATUS='Suspension' ORDER BY CREATED_DATE DESC";
	
	public static final String GET_SUSPENSDED_RECORD_FOR_REVOKE ="SELECT iecc.pre_enquiry_details AS PE_Details,iecc.user_comments AS PE_Comments,iecad.FINAL_CHARGE AS FINAL_CHARGE,to_char(iecc.user_comments_date,'DD/MM/YYYY') AS PE_Date," +
			"iecd.major_status AS PE_Major_Status,iecad.issued_authority AS Issused_Authority,to_char(iecad.DATE_OF_ISSUANCE,'DD/MM/YYYY') AS ISSUE_DATE,iecad.place_of_issuance AS Place, iecad.address AS Address, iecad.charge_details AS Details," +
			"iecad.user_remarks AS Comments" +
			" FROM igrs_emp_complaint_details iecd,igrs_emp_complaint_comments iecc,igrs_emp_complaint_action_dtls iecad" +
			" WHERE iecd.complaint_no =iecad.complaint_no AND iecd.complaint_no = iecc.complaint_no AND iecd.complaint_no = ?";
		
	

	
	public static final String UPDATE_CHARGESHEET_COMP_DETAILS = "UPDATE IGRS_EMP_COMPLAINT_DETAILS SET  COMPLAINT_STATUS = ?," 
		+" UPDATE_BY = ?,  UPDATE_DATE = SYSDATE WHERE   COMPLAINT_NO = ?";
	
	public static final String UPDATE_CHARGESHEET_ACTION_DETAILS = "UPDATE IGRS_EMP_COMPLAINT_ACTION_DTLS SET " 
		  +"COMPLAINT_ACTION=?, CHARGE_DETAILS=?, ISSUED_AUTHORITY=?, DATE_OF_ISSUANCE=?, ISSUED_USER_ID=?, USER_REMARKS=?, PLACE_OF_ISSUANCE=? WHERE  COMPLAINT_NO=?";

	
	public static final String UPDATE_CHARGESHEET_COMMENT_DETAILS = "UPDATE IGRS_EMP_COMPLAINT_COMMENTS SET " 
		  +"USER_ID=?,COMPLAINT_ACTION_STATUS=? WHERE COMPLAINT_NO=?";
	
	
	public static final String UPDATE_CHARGESHEET_STATUS = "UPDATE IGRS_EMP_COMPLAINT_STATUS_DTLS SET COMPLAINT_STATUS=?, COMPLAINT_STATUS_DATE = SYSDATE WHERE COMPLAINT_NO = ?";
	
	public static final String INSERT_WITNESS_DETAILS = "INSERT INTO IGRS_EMP_COMPLAINT_WITNES_DTLS (COMPLAINT_NO,WITNESS_USER_ID,COMPLAINT_ACTION,"+
	 "COMPLAINT_ACTION_DATE,DOCUMENT_ID) VALUES(?,?,?,SYSDATE,?)";

	//revoke 
	public static final String UPDATE_ACTION_DTLS_REVOKE = 
					"UPDATE   IGRS_EMP_COMPLAINT_ACTION_DTLS SET COMPLAINT_ACTION = ?, ISSUED_USER_ID = ?" 
					+" WHERE  COMPLAINT_NO = ? AND  COMPLAINT_ACTION = ?";
	
	public static final String UPDATE_COMPLAINT_COMMENTS_REVOKE =
			"UPDATE   IGRS_EMP_COMPLAINT_COMMENTS SET COMPLAINT_ACTION_STATUS = ?, USER_COMMENTS_DATE = SYSDATE"
			+" WHERE  COMPLAINT_NO = ? AND  COMPLAINT_ACTION_STATUS = ?";
	
	public static final String UPDATE_COMPLAINT_DTLS_REVOKE =
			"UPDATE   IGRS_EMP_COMPLAINT_DETAILS SET COMPLAINT_STATUS = ?, UPDATE_BY = ?, UPDATE_DATE = SYSDATE"
			+" WHERE COMPLAINT_NO = ? AND COMPLAINT_STATUS = ?";
	
	public static final String UPDATE_ACTION_STATUS_REVOKE =
					"UPDATE IGRS_EMP_COMPLAINT_STATUS_DTLS SET COMPLAINT_STATUS = ?, COMPLAINT_STATUS_DATE = SYSDATE"
					+" WHERE  COMPLAINT_NO = ? AND COMPLAINT_STATUS = ?";
	 

	public static final String	CHARGESHEET_CLOSE_COMPLAINT_DETAILS	         = "SELECT COMPLAINT_NO, CREATED_BY,COMPLAINT_STATUS,to_char(CREATED_DATE,'DD/MM/YYYY') FROM IGRS_EMP_COMPLAINT_DETAILS"
		+ " WHERE COMPLAINT_STATUS='Chargesheet' AND COMPLAINT_NO LIKE ? ORDER BY CREATED_DATE DESC";
	
	
	public static final String CHARGESHEET_CLOSE_DETAILS =
		"select iurd.first_name||' '||iurd.middle_name||' '||iurd.last_name,iurd.address,"
        +"iurd.mobile_number,iurd.email_id,iecad.CHARGE_DETAILS,to_char(iecad.DATE_OF_ISSUANCE,'DD/MM/YYYY'),"
		+"iecad.ISSUED_AUTHORITY,iecad.PLACE_OF_ISSUANCE,iecad.USER_REMARKS,iecdm.DOCUMENT_NAME,iecdm.DOCUMENT_ID"
        +" FROM igrs_emp_complaint_details iecd,igrs_user_reg_details iurd,IGRS_EMP_COMPLAINT_ACTION_DTLS iecad,"
        +"IGRS_EMP_COMPLAINT_DOC_MAP iecdm WHERE iecd.complainee_user_id = iurd.user_id"
        +" AND iecad.COMPLAINT_NO=iecd.complaint_no AND iecdm.COMPLAINT_NO=iecad.complaint_no"
        +" AND iecdm.DOCUMENT_TYPE='ChargesheetProof' AND iecd.complaint_no =?";
	
	public static final String CHARGESHEET_CLOSE_WITNESS_DETAILS =
	"select DISTINCT iurd.first_name||' '||iurd.middle_name||' '||iurd.last_name,iecdm.DOCUMENT_NAME,iecdm.DOCUMENT_ID"
	+" from igrs_user_reg_details iurd, IGRS_EMP_COMPLAINT_WITNES_DTLS iecwd,IGRS_EMP_COMPLAINT_DOC_MAP iecdm"
	+" Where iecwd.WITNESS_USER_ID = iurd.USER_ID AND iecwd.COMPLAINT_NO = iecdm.COMPLAINT_NO "
	+" AND iecdm.DOCUMENT_TYPE='Witness' AND iecwd.DOCUMENT_ID = iecdm.DOCUMENT_ID "
	+" AND iecwd.COMPLAINT_NO = ?";
	
	public static final String UPDATE_CHARGESHEET_CLOSE_ACTION_DETAILS = "UPDATE IGRS_EMP_COMPLAINT_ACTION_DTLS SET " 
		  +"COMPLAINT_ACTION=?, ISSUED_USER_ID=?, USER_REMARKS=? WHERE  COMPLAINT_NO=?";
	
	
	public static final String UPDATE_CHARGESHEET_CLOSE_COMMENT_DETAILS = "UPDATE IGRS_EMP_COMPLAINT_COMMENTS SET " 
		  +"USER_ID=?, USER_COMMENTS=?, COMPLAINT_ACTION_STATUS=?, USER_COMMENTS_DATE=SYSDATE  WHERE COMPLAINT_NO=?";
	
	
	public static final String UPDATE_WITNESS_DETAILS = "UPDATE IGRS_EMP_COMPLAINT_WITNES_DTLS"
		+" SET COMPLAINT_ACTION=?, COMPLAINT_ACTION_DATE = SYSDATE  WHERE COMPLAINT_NO=?";

	public static final String SELECT_COMPLAINEE_USERTYPE = "select T1.FIRST_NAME FROM IGRS_EMP_MASTER T1,IGRS_EMP_COMPLAINT_DETAILS T2 WHERE T2.COMPLAINEE_USER_ID = T1.EMP_ID AND T2.COMPLAINT_NO=?";

	

	public static String SELECT_COMPLAINER_USERTYPE="select T1.FIRST_NAME FROM IGRS_EMP_MASTER T1,IGRS_EMP_COMPLAINT_DETAILS T2 WHERE T2.COMPLAINER_USER_ID = T1.EMP_ID AND T2.COMPLAINT_NO=?";

	public static String COMPLAINT_COMPLAINEE_EMP_DETAILS="select T1.FIRST_NAME||' '||T1.MIDDLE_NAME||' '||T1.LAST_NAME AS NAME,T1.PRESENT_ADDRESS,T1.MOBILE_NUMBER,T1.EMAIL" +
			",to_char(T2.CREATED_DATE,'DD/MM/YYYY')," +
			"T2.DETAILS_OF_COMPLAINT FROM IGRS_EMP_MASTER T1,IGRS_EMP_COMPLAINT_DETAILS T2 WHERE T2.COMPLAINEE_USER_ID = T1.EMP_ID " +
			"AND T2.COMPLAINT_NO=?";

	public static String COMPLAINT_COMPLAINER_EMP_DETAILS="select T1.FIRST_NAME||' '||T1.MIDDLE_NAME||' '||T1.LAST_NAME AS NAME,T1.PRESENT_ADDRESS,T1.MOBILE_NUMBER,T1.EMAIL" +
	",to_char(T2.CREATED_DATE,'DD/MM/YYYY')," +
	"T2.DETAILS_OF_COMPLAINT FROM IGRS_EMP_MASTER T1,IGRS_EMP_COMPLAINT_DETAILS T2 WHERE T2.COMPLAINER_USER_ID = T1.EMP_ID " +
	"AND T2.COMPLAINT_NO=?";

	public static String GET_DEPUTEDEMP_DETAILS="select T1.FIRST_NAME||' '||T1.MIDDLE_NAME||' '||T1.LAST_NAME AS NAME,T1.PRESENT_ADDRESS,T1.MOBILE_NUMBER,T1.EMAIL" +
	",T2.DETAILS_OF_COMPLAINT,to_char(T2.CREATED_DATE,'DD/MM/YYYY')" +
	" FROM IGRS_EMP_MASTER T1,IGRS_EMP_COMPLAINT_DETAILS T2 WHERE T2.DEPUTED_PE_USER_ID = T1.EMP_ID " +
	"AND T2.COMPLAINT_NO=?";

	public static String SELECT_DEPUTED_USERTYPE="select T1.FIRST_NAME FROM IGRS_EMP_MASTER T1,IGRS_EMP_COMPLAINT_DETAILS T2 WHERE T2.DEPUTED_PE_USER_ID = T1.EMP_ID AND T2.COMPLAINT_NO=?";

	public static String GET_DEPUTE_DETAILS="select T1.FIRST_NAME||' '||T1.MIDDLE_NAME||' '||T1.LAST_NAME AS NAME,T1.ADDRESS,T1.MOBILE_NUMBER,T1.EMAIL_ID,T2.DETAILS_OF_COMPLAINT,to_char(T2.CREATED_DATE,'DD/MM/YYYY')" 
		+ " FROM IGRS_USER_REG_DETAILS T1,IGRS_EMP_COMPLAINT_DETAILS T2"
		+ " WHERE T2.DEPUTED_PE_USER_ID = T1.USER_ID AND T2.COMPLAINT_NO=?";

	public static String GET_SUSPENSDED_DOCUMNETS="select iecdm.document_name AS PE_Document,iecdm.document_id AS PE_Document_id from igrs_emp_complaint_doc_map iecdm where  iecdm.complaint_no = ?";

	public static String SELECT_DE_USERTYPE="select T1.FIRST_NAME FROM IGRS_EMP_MASTER T1,IGRS_EMP_COMPLAINT_DETAILS T2 WHERE T2.DEPUTED_PE_USER_ID	= T1.EMP_ID AND T2.COMPLAINT_NO=?";
		
	
}

