package com.wipro.igrs.partytypemaster.sql;

public class PartyTypeSQL {
	
    public static final String INSERT_PARTY_TYPE = 
        "INSERT INTO IGRS_PARTY_TYPE_MASTER (PARTY_TYPE_ID,PARTY_TYPE_NAME, PARTY_TYPE_DESC, PARTY_TYPE_STATUS, CREATED_BY, CREATED_DATE, UPDATE_BY, UPDATE_DATE, FUNCTION_ID, DEPENDENCE_ID)" + 
        "VALUES(IGRS_PARTY_TYPE_SEQ.NEXTVAL,?,?,?,?,SYSDATE,?,SYSDATE,?,?)";

    public static final String UPDATE_PARTY_TYPE =
    	"UPDATE IGRS_PARTY_TYPE_MASTER SET PARTY_TYPE_NAME=?, PARTY_TYPE_DESC=?, PARTY_TYPE_STATUS=?, UPDATE_BY=?, UPDATE_DATE=SYSDATE, FUNCTION_ID=?, DEPENDENCE_ID=? WHERE PARTY_TYPE_ID=?";
    
    public static final String CHANGE_STATUS_PARTY_TYPE =
    	"UPDATE IGRS_PARTY_TYPE_MASTER SET PARTY_TYPE_STATUS=?, UPDATE_BY=?, UPDATE_DATE=SYSDATE WHERE PARTY_TYPE_ID=?";
    
    public static final String SELECT_ALL_PARTY_TYPE =
    	"SELECT PARTY_TYPE_ID, PARTY_TYPE_NAME, PARTY_TYPE_DESC, PARTY_TYPE_STATUS, t.CREATED_BY, t.CREATED_DATE, t.UPDATE_BY, t.UPDATE_DATE, t.FUNCTION_ID, FUNCTION_NAME, t.DEPENDENCE_ID, DEPENDENCE_NAME " +
    	"FROM IGRS_PARTY_TYPE_MASTER t, IGRS_FUNCTION_MASTER f, IGRS_DEPENDENCE_MASTER d WHERE t.FUNCTION_ID = f.FUNCTION_ID AND t.DEPENDENCE_ID = d.DEPENDENCE_ID AND t.PARTY_TYPE_STATUS <> 'R'";
    
    public static final String SELECT_ALL_FUNCTION = 
    	"SELECT FUNCTION_ID, FUNCTION_NAME FROM IGRS_FUNCTION_MASTER";
    
    public static final String SELECT_ALL_DEPENDENCE = 

    	"SELECT DEPENDENCE_ID, DEPENDENCE_NAME FROM IGRS_DEPENDENCE_MASTER";
    	
    public static final String SELECT_PARTY_TYPE_BY_ID =
    	"SELECT PARTY_TYPE_ID, PARTY_TYPE_NAME, PARTY_TYPE_DESC, PARTY_TYPE_STATUS, t.CREATED_BY, t.CREATED_DATE, t.UPDATE_BY, t.UPDATE_DATE, t.FUNCTION_ID, FUNCTION_NAME, t.DEPENDENCE_ID, DEPENDENCE_NAME " +
    	"FROM IGRS_PARTY_TYPE_MASTER t, IGRS_FUNCTION_MASTER f, IGRS_DEPENDENCE_MASTER d WHERE t.FUNCTION_ID = f.FUNCTION_ID AND t.DEPENDENCE_ID = d.DEPENDENCE_ID AND t.PARTY_TYPE_STATUS <> 'R'" + 
    	"AND PARTY_TYPE_ID=?";
    	
    
    public static final String SELECT_PARTY_TYPE_BY_NAME =
    	"SELECT * FROM IGRS_PARTY_TYPE_MASTER WHERE PARTY_TYPE_NAME=?";
}
