package com.wipro.igrs.empreportmgr.sql;

public class empReportMgrCommonSql 
{
	public static final String INSERT_EMP_REPORT_MGR = 
		"INSERT INTO IGRS_EMP_RPTMGR_MASTER(EMP_ID,EMP_SUPERVISOR_NAME,EMP_SUPERVISOR_DESIGNATION,EMP_SUPERVISOR_ID) " +
		"VALUES(?,?,?,?)";
	
	// Update Query
	public static final String UPDATE_EMP_REPORT_MGR = 
		"UPDATE IGRS_EMP_RPTMGR_MASTER SET EMP_SUPERVISOR_NAME=?,EMP_SUPERVISOR_DESIGNATION=?,EMP_SUPERVISOR_ID=? " +
		"WHERE EMP_ID=?";
	
	public static final String SELECT_ROLE_MASTER = 
		"SELECT ROLE_ID,ROLE_NAME,ROLE_DESCRIPTION,ROLE_STATUS FROM IGRS_ROLE_MASTER";
	
	public static final String SELECT_USER_MASTER = 
		" SELECT e.EMP_ID,FIRST_NAME,MIDDLE_NAME,LAST_NAME,ROLE_ID FROM " +
		"IGRS_EMP_MASTER e , IGRS_EMP_ROLE_CADRE_GRADE_MAP r " +
		"where e.EMP_ID = r.EMP_ID and ROLE_ID=? ";
	
	public static final String SELECT_EMP_REPORT_MGR_BY_ID = 
		"SELECT EMP_ID,EMP_SUPERVISOR_NAME,EMP_SUPERVISOR_DESIGNATION,EMP_SUPERVISOR_ID FROM IGRS_EMP_RPTMGR_MASTER " +
		"WHERE EMP_ID=?";
	
	public static final String SELECT_EMP_REPORT_MGR_EXISTS = 
		"SELECT * FROM IGRS_EMP_RPTMGR_MASTER " +
		"WHERE EMP_ID=?";
	
	public static final String SELECT_EMP_NAME_BY_ID =
		" SELECT FIRST_NAME,MIDDLE_NAME,LAST_NAME FROM " +
		"IGRS_EMP_MASTER where EMP_ID=? ";
}
