/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */

package com.wipro.igrs.empmgmt.action;

import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.wipro.igrs.baseaction.action.BaseAction;
import com.wipro.igrs.common.EmpmgmtConstant;
import com.wipro.igrs.empmgmt.bd.TransferBD;
import com.wipro.igrs.empmgmt.dto.TransferDTO;
import com.wipro.igrs.empmgmt.form.TransferForm;
import com.wipro.igrs.empmgmt.rule.EmpMgmtRule;

/**
 * MyEclipse Struts Creation date: 06-13-2008
 * 
 * XDoclet definition:
 * 
 * @struts.action validate="true"
 */
public class TransferAction extends BaseAction {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response,HttpSession session)
			throws Exception {
	//	HttpSession session = request.getSession();

		String actionpath = request.getParameter("name");
		String Forward_page = null;
		TransferDTO transferDTO = new TransferDTO();
		TransferBD transferBD = null;
		EmpMgmtRule rule = null;
		TransferForm transferForm = (TransferForm) form;
		
		String interType=request.getParameter("inter");	
		
		if(interType==null)
		{interType="";		
		}
		else
		{			
			session.setAttribute("transfertype", interType);			
		}
		String inter=(String)session.getAttribute("transfertype");
		//transferDTO.setTransferType(inter);
		
		
		if (transferForm.getActionType() != null
				&& transferForm.getActionType().equalsIgnoreCase("transfer")) {
			session.removeAttribute("transferDTO");

			transferBD = new TransferBD();
			transferDTO = new TransferDTO();

			transferDTO = transferForm.getTransferDTO();

			ArrayList locationList = new ArrayList();
			ArrayList errorList = null;
			rule = new EmpMgmtRule();
			locationList = transferBD.getnewLocation();

			errorList = rule.validatelocationlist(locationList);
			if (rule.isError()) {
				request.setAttribute(EmpmgmtConstant.EMP_MGMT_ERROR_FLAG,
						"true");
				request.setAttribute(EmpmgmtConstant.EMP_MGMT_ERROR_LIST,
						errorList);
				Forward_page = "transferedit";
			} else {
				if(inter.equalsIgnoreCase("inter"))
				{
					Forward_page = "transferedit";
				}
				else
				{
					Forward_page = "intratransferedit";
				}

				
			}
			if (locationList != null) {

				session.setAttribute("locationList", locationList);
				
				if(inter.equalsIgnoreCase("inter"))
				{
					Forward_page = "transferedit";
				}
				else
				{
					Forward_page = "intratransferedit";
				}

			}

		} else if (request.getParameter("name") != null) {

			transferBD = new TransferBD();
			rule = new EmpMgmtRule();
			transferDTO = transferForm.getTransferDTO();

			ArrayList errorList = new ArrayList();
			TransferDTO transferDTO1 = transferBD.displayEmpDetails(
					transferDTO, request);
			transferDTO.setEmployeeName(transferDTO1.getEmployeeName());
			transferDTO.setDesignation(transferDTO1.getDesignation());
			transferDTO.setOldLoc(transferDTO1.getOldLoc());
			transferDTO.setNewLoc(transferDTO1.getNewLoc());
			transferDTO.setDepartment(transferDTO1.getDepartment());

			// if(transferDTO1==null){

			// }

			session.setAttribute("transferDTO", transferDTO);
			
			if(inter.equalsIgnoreCase("inter"))
			{
				Forward_page = "transferedit";
			}
			else
			{
				Forward_page = "intratransferedit";
			}

		} else if (transferForm.getActionType() != null
				&& transferForm.getActionType()
						.equalsIgnoreCase("editTransfer")) {

			if (transferForm.getActionName() != null
					&& transferForm.getActionName().equalsIgnoreCase("clear")) {
				session.removeAttribute("transferDTO");
				
				if(inter.equalsIgnoreCase("inter"))
				{
					Forward_page = "transferedit";
				}
				else
				{
					Forward_page = "intratransferedit";
				}
				return mapping.findForward("transferedit");
			}

			ArrayList errorList = new ArrayList();
			rule = new EmpMgmtRule();
			transferDTO = transferForm.getTransferDTO();
			errorList = rule.validateEmployeeDetailsList(transferDTO);

			if (rule.isError()) {

				request.setAttribute(EmpmgmtConstant.EMP_MGMT_ERROR_FLAG,
						"true");
				request.setAttribute(EmpmgmtConstant.EMP_MGMT_ERROR_LIST,
						errorList);
				Forward_page = "transfer_edit";
			} else {

				session.setAttribute("transferDTO", transferDTO);
				
				if(inter.equalsIgnoreCase("inter"))
				{
					Forward_page = "transfer_save";
				}
				else
				{
					Forward_page = "intratransfer_save";
				}
				

			}
		} else if (transferForm.getActionType() != null
				&& transferForm.getActionType().equalsIgnoreCase(
						"editTransferDetails")) {
			
			if(inter.equalsIgnoreCase("inter"))
			{
				Forward_page = "transferedit";
			}
			else
			{
				Forward_page = "intratransferedit";
			}
			
		}

		else if (transferForm.getActionType() != null
				&& transferForm.getActionType().equalsIgnoreCase(
						"submitTransfer")) {
			transferBD = new TransferBD();
			rule = new EmpMgmtRule();
			// transferDTO=new TransferDTO();

			transferDTO = (TransferDTO) session.getAttribute("transferDTO");

			String strUserId = (String) session.getAttribute("UserId");
			ArrayList errorList = null;
			errorList = rule.validateEmployeeDetailsList(transferDTO);
			boolean submitTransfer=false;
			if(inter.equalsIgnoreCase("inter"))
			{
				 submitTransfer = transferBD.submitTransferDetails(
						transferDTO, strUserId);
			}
			else
			{
				 submitTransfer = transferBD.submitIntraTransferDetails(
						transferDTO, strUserId);
			}
		

			if (submitTransfer == false) {
				request.setAttribute(EmpmgmtConstant.EMP_MGMT_ERROR_FLAG,
						"true");
				request.setAttribute(EmpmgmtConstant.EMP_MGMT_ERROR_LIST,
						errorList);
				if(inter.equalsIgnoreCase("inter"))
				{
					Forward_page = "transfer_save";
				}
				else
				{
					Forward_page = "intratransfer_save";
				}
			} else {
				session.removeAttribute("transferDTO");
				
				if(inter.equalsIgnoreCase("inter"))
				{
					Forward_page = "transfer_submit";
				}
				else
				{
					Forward_page = "intratransfer_submit";
				}
				
			}

		}

		// TODO Auto-generated method stub
		return mapping.findForward(Forward_page);
	}
}