package com.wipro.igrs.lastcertificate.sql;
/* Copyright (c) 2006-2008 WIPRO. All Rights Reserved.
 * 
 *  This software is the confidential and proprietary information of WIPRO
 *  ("Confidential Information"). You shall not
 *  disclose such Confidential Information and shall use it only in
 *  accordance with the terms of the license agreement you entered into
 *  with WIPRO.
 *  
 * WIPRO MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE 
 * SUITABILITY OF THE SOFTWARE, EITHER EXPRESS OR IMPLIED, 
 * INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF 
 * MERCHANTABILITY, FITNESS FOR A
 * PARTICULAR PURPOSE, OR NON-INFRINGEMENT. WIPRO SHALL NOT BE 
 * LIABLE FOR ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF 
 * USING, MODIFYING OR DISTRIBUTING THIS SOFTWARE OR ITS 
 * DERIVATIVES.
 * 
 */


/**
 * @author Madan Mohan
 *
 */
public class CommonSQL {

	public static final String EMP_SALARY_DETAILS = 
		"SELECT DISTINCT IGRS_EMP_MASTER.FIRST_NAME||"
		+"IGRS_EMP_MASTER.MIDDLE_NAME||IGRS_EMP_MASTER.LAST_NAME,"
		+"IGRS_EMP_SALARY_MON_COMP.COMPONENT_NAME,"
		+"IGRS_EMP_SALARY_MON_COMP.COMPONENT_AMOUNT, "
		+"IGRS_EMP_FUND_DETAILS.FUND_ACCOUNT_NO,"
		+"IGRS_EMP_FUND_TYPE_MASTER.FUND_AUTHORITY,"
		+"TO_CHAR(SYSDATE,'DD/MM/YYYY') "
		+"FROM IGRS_EMP_SALARY_MONTHLY_DTL,IGRS_EMP_SALARY_MON_COMP," 
		+"IGRS_EMP_MASTER,IGRS_EMP_FUND_DETAILS, "
		+"IGRS_EMP_FUND_TYPE_MASTER "
		+"WHERE ((IGRS_EMP_SALARY_MONTHLY_DTL.EMP_SAL_ID = "
		+"IGRS_EMP_SALARY_MON_COMP.EMP_SAL_ID) AND "
		+"(IGRS_EMP_SALARY_MONTHLY_DTL.EMP_ID = "
		+"IGRS_EMP_MASTER.EMP_ID) AND (IGRS_EMP_MASTER.EMP_ID = "
		+"IGRS_EMP_FUND_DETAILS.EMP_ID) AND "
		+"(IGRS_EMP_FUND_TYPE_MASTER.FUND_TYPE_ID ="
        +"IGRS_EMP_FUND_DETAILS.FUND_TYPE_ID) "
        +"AND ((IGRS_EMP_SALARY_MON_COMP.COMPONENT_TYPE <> 'D')) "
        +"AND ((IGRS_EMP_SALARY_MONTHLY_DTL.EMP_ID = ?)) "
        +"AND ((UPPER (IGRS_EMP_FUND_TYPE_MASTER.FUND_NAME) = UPPER ('PF'))) "
        +"AND ((TO_CHAR(IGRS_EMP_SALARY_MONTHLY_DTL.SALARY_DATE,'MON') = "
        +"TO_CHAR(SYSDATE,'MON')))) ";
	
	public static final String EMP_SALARY_COUNT_DETAILS = 
		"SELECT COUNT(*) FROM IGRS_EMP_SALARY_MONTHLY_DTL,"
		+"IGRS_EMP_SALARY_MON_COMP," 
		+"IGRS_EMP_MASTER "
		+"WHERE ((IGRS_EMP_SALARY_MONTHLY_DTL.EMP_SAL_ID = "
		+"IGRS_EMP_SALARY_MON_COMP.EMP_SAL_ID) AND "
		+"(IGRS_EMP_SALARY_MONTHLY_DTL.EMP_ID = "
		+"IGRS_EMP_MASTER.EMP_ID) "
	    +"AND ((IGRS_EMP_SALARY_MON_COMP.COMPONENT_TYPE <> 'D')) "
        +"AND ((IGRS_EMP_SALARY_MONTHLY_DTL.EMP_ID = ?)) "
        +"AND ((TO_CHAR(IGRS_EMP_SALARY_MONTHLY_DTL.SALARY_DATE,'MON') = "
        +"TO_CHAR(SYSDATE,'MON')))) ";
     
	public static final String EMP_FUND_DETAILS =
		"SELECT COUNT(*) FROM IGRS_EMP_FUND_DETAILS WHERE "
		+"IGRS_EMP_FUND_DETAILS.EMP_ID=?";

	public static final String EMP_RECOVERY_DETAILS = 
		"SELECT   IGRS_EMP_LOAN_TYPE_MASTER.LOAN_NAME, "
		+" (SUM (IGRS_EMP_LOAN_TXN_HISTORY.EMI_AMOUNT)) EMI_AMOUNT, "
		+" (COUNT (IGRS_EMP_LOAN_TXN_HISTORY.EMI_STATUS)) EMI_COUNT "
		+" FROM IGRS_EMP_LOAN_TYPE_MASTER,IGRS_EMP_LOAN_TXN_HISTORY, "
		+" IGRS_EMP_LOAN_TXN_DETAILS WHERE " 
		+" ((IGRS_EMP_LOAN_TXN_DETAILS.LOAN_TXN_ID = "
		+" IGRS_EMP_LOAN_TXN_HISTORY.LOAN_TXN_ID) AND "
		+" (IGRS_EMP_LOAN_TYPE_MASTER.LOAN_TYPE_ID =  "
		+" IGRS_EMP_LOAN_TXN_DETAILS.LOAN_TYPE_ID) AND "
		+" ((IGRS_EMP_LOAN_TXN_DETAILS.EMP_ID =  ?)) "
		+" AND ((IGRS_EMP_LOAN_TXN_HISTORY.EMI_STATUS = 'U'))) "
		+" GROUP BY IGRS_EMP_LOAN_TYPE_MASTER.LOAN_NAME ";

	public static final String EMP_MONTHLY_DEDUCTION_DETAILS = 
		"SELECT TO_CHAR(SALARY_DATE,'DD/MM/YYYY'), "
		+"SAL_AMOUNT,COMPONENT_ID,COMPONENT_AMOUNT,COMPONENT_NAME FROM "
		+"IGRS_EMP_SALARY_MONTHLY_DTL JOIN IGRS_EMP_SALARY_MON_COMP "
		+"ON IGRS_EMP_SALARY_MONTHLY_DTL.EMP_SAL_ID="
		+"IGRS_EMP_SALARY_MON_COMP.EMP_SAL_ID WHERE EMP_ID=? "
		+"AND TRUNC(SALARY_DATE) BETWEEN DECODE(TO_CHAR(SYSDATE,'MM'), "
		+"01, ADD_MONTHS(TO_DATE('1-APR-'||TO_CHAR(SYSDATE,'YYYY'), "
		+"'DD-MON-YYYY'),-12),02, ADD_MONTHS(TO_DATE"
		+"('1-APR-'||TO_CHAR(SYSDATE,'YYYY'),'DD-MON-YYYY'),-12), "
		+"03, ADD_MONTHS(TO_DATE('1-APR-'||TO_CHAR(SYSDATE,'YYYY'), "
		+"'DD-MON-YYYY'),-12), TO_DATE('1-APR-'||TO_CHAR(SYSDATE,'YYYY'), "
		+"'DD-MON-YYYY')) AND TO_DATE('1-'||TO_CHAR(SYSDATE,'MON')||'-'|| "
		+"TO_CHAR(SYSDATE,'YYYY'),'DD-MON-YYYY') AND COMPONENT_ID IN "
		+"('DH008','DH018','DH012','DH020') GROUP BY SALARY_DATE,SAL_AMOUNT,"
		+"COMPONENT_ID,COMPONENT_AMOUNT,COMPONENT_NAME ORDER BY SALARY_DATE ";

}

