package com.wipro.igrs.documentsearch.sql;

public class CommonSQL {
	
	public static final String REQUISITE_FEE_QUERY = "SELECT AMOUNT FROM IGR_REQUISITE_FEE_MASTER WHERE REQUISITE_NAME='WILL_DEPOSIT'";
	public static final String REQUISITE_OTHER_FEE_QUERY = "SELECT AMOUNT FROM IGR_REQUISITE_FEE_MASTER WHERE REQUISITE_NAME='WILL_OTHER'";
	public static final String WILL_DEPOSIT_INSERT = "INSERT INTO IGRS_WILL_DEPOSIT_TXN(WILL_ID,DR_ID," + "DEPOSITOR_TYPE,FIRST_NAME,MID_NAME,LAST_NAME,GENDER,AGE," + "FATHER_NAME,MOTHER_NAME,SPOUSE_NAME,ADDRESS,CITY,STATE," + "COUNTRY,PIN,PHONE,MOBILE,EMAIL,ID_PROOF,PHOTO_FLAG,THUMB_FLAG," + "SIGN_FLAG,FEE,OTHER,PAYMENT_MODE,DEPOSIT_DATE,WILL_TYPE_FLAG)" + "VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,SYSDATE,?) ";
	public static final String WILL_DEPOST_AGENT_INSERT = "INSERT INTO IGRS_WILL_AGENT_TXN(WILL_ID,FIRST_NAME," + "MID_NAME,LAST_NAME,GENDER,AGE,FATHER_NAME,MOTHER_NAME," + "SPOUSE_NAME,ADDRESS,CITY,STATE,COUNTRY,PIN,PHONE,MOBILE,EMAIL,IDPROOFNO) " + "VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
	public static final String WILL_DEPOSIT_QUERY = "SELECT FIRST_NAME,MID_NAME,LAST_NAME,GENDER,AGE," + "FATHER_NAME,MOTHER_NAME,SPOUSE_NAME,ADDRESS,CITY,STATE," + "COUNTRY,PIN,PHONE,MOBILE,EMAIL,ID_PROOF,PHOTO_FLAG,THUMB_FLAG," + "SIGN_FLAG,DEPOSIT_DATE,WILL_ID FROM  IGRS_WILL_DEPOSIT_TXN WHERE WILL_ID=? AND WILL_TYPE_FLAG=?";
	
	public static final String WILL_WITHDRAWAL_INSERT = "UPDATE IGRS_WILL_DEPOSIT_TXN SET WILL_TYPE_FLAG=?,EXE_TFLAG=?,EXE_SFLAG=?,REASON=?,REMARKS=? WHERE WILL_ID=?";
	public static final String WILL_RETRIEVE_QUERY = "SELECT FIRST_NAME,MID_NAME,LAST_NAME, ADDRESS,DEPOSIT_DATE FROM  IGRS_WILL_DEPOSIT_TXN WHERE WILL_ID LIKE 'MP%' ";
	public static final String WILL_RETRIEVE_CITIZEN_INSERT = "INSERT INTO IGRS_WILL_RETRIEVE_TXN(WILL_ID,FIRST_NAME," + "MID_NAME,LAST_NAME,GENDER,AGE,FATHER_NAME,MOTHER_NAME," + "SPOUSE_NAME,ADDRESS,CITY,STATE,COUNTRY,PIN,PHONE,MOBILE,EMAIL," + "IDPROOFNO,PHOTO_FLG,THUMB_FLG,SIGN_FLG,DEATH_FLG,WILL_RET_ID) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
	public static final String WILL_RETRIEVE_UPDATE = "UPDATE IGRS_WILL_DEPOSIT_TXN SET WILL_TYPE_FLAG=?,WILL_RET_TYPE_FLAG=?,REASON=?,REMARKS=? WHERE WILL_ID=?";
	public static final String WILL_RETRIEVE_COURT_INSERT = "INSERT IGRS_WILL_COURT_TXN(WILL_ID,COURT_NAME,REP_NAME,DESG,THUMB_FLAG,SIGN_FLAG,ADDRESS,CITY,STATE,COUNTRY,PIN,PHONE)VALUES(?,?,?,?,?,?,?,?,?,?,?,?)";
	public static final String SLOTBOOK_DISTRICT_DROPDOWN_SELECT = "SELECT DIST_ID,DIST_NAME FROM IGRS_DISTRICT_MASTER ORDER BY DIST_NAME";
	public static final String SLOTBOOK_SRONAME_DROPDOWN_SELECT = "SELECT OFFICE_ID,OFFICE_LOCATION  FROM IGRS_OFFICE_MASTER WHERE OFFICE_TYPE='SRO' AND upper(OFFICE_LOCATION)=";
	public static final String SLOTBOOK_USER_TIMESLOT_SELECT = "SELECT SLOT_TIME_ID,SLOT_TIME_RANGE  FROM IGRS_SLOT_TIME_CONFIG_MASTER ORDER BY SLOT_TIME_ID";
	public static final String SLOTBOOK_SRNAME_DROPDOWN_SELECT = "SELECT OFFICE_ID,OFFICE_LOCATION  FROM IGRS_OFFICE_MASTER WHERE OFFICE_TYPE='SR'";
	public static final String SLOTBOOK_USER_INSERT = "INSERT INTO  IGRS_USER_SLOT_BOOKING(APPLICATION_ID,SLOT_DATE,CREATED_BY,CREATED_DATE,SLOT_REF_ID,DISTRICT_ID,SRO_ID,SR_ID)VALUES(?,?,?,?,?,?,?,?)";
	public static final String SLOTBOOK_USER_SLOT_INSERT = "INSERT INTO IGRS_SLOT_BOOKING_MASTER(DISTRICT_ID,SRO_ID,SR_ID,SLOT_DATE,CREATED_BY,CREATED_DATE,SLOT_ID ,SLOT_STATUS,SLOT_REF_ID,REMARKS) VALUES(?,?,?,?,?,?,?,?,?,?)";
	public static final String SLOTBOOK_SROSLOT_SELECT = "SELECT distinct SLOT_ID,SLOT_STATUS from IGRS_SLOT_BOOKING_MASTER where DISTRICT_ID='IGR_DST_001' and SRO_ID='SRO1' and SR_ID='SR1' and SLOT_REF_ID ='2712200700024'";
	public static final String SLOTBOOK_SROTIMESLOT_SELECT = "select  SLOT_TIME_RANGE  from IGRS_SLOT_TIME_CONFIG_MASTER where SLOT_TIME_ID=";
	public static final String SLOTBOOK_TIMESLOT_SELECT = "select  SLOT_TIME_ID,SLOT_TIME_RANGE  from IGRS_SLOT_TIME_CONFIG_MASTER";
	public static final String SLOTBOOK_SRO_BOOKED_SEARCH = "SELECT distinct SR_ID,SLOT_ID from IGRS_SLOT_BOOKING_MASTER where DISTRICT_ID=";
	public static final String DOC_SEARCH_SELECT_REGID = "SELECT a.REG_TXN_ID FROM IGRS_REG_TXN_DETLS a,IGRS_DEED_TYPE_MASTER b  WHERE a.DEED_ID=b.DEED_TYPE_ID and b.DOC_SRCH_FLAG='Y' and REGISTRATION_NUMBER LIKE ";
	public static final String DOC_SEARCH_KHASRA_DETAILS = "select KHASRA_NUMBER,KHASRA_AREA,LAGAAN,RIN_PUSHTIKA_NUMBER,irpkd.NORTH_BOUNDARY,irpkd.SOUTH_BOUNDARY,irpkd.EAST_BOUNDARY,irpkd.WEST_BOUNDARY from IGRS_REG_PROP_KHASARA_DTLS irpkd,IGRS_REG_PROPRTY_DTLS irpd,IGRS_REG_TXN_DETLS irtd where irpkd.PROPERTY_ID=irpd.PROPERTY_ID and irpd.REG_TXN_ID=irtd.REG_TXN_ID and irpkd.PROPERTY_ID=?";
	public static final String DOC_SEARCH_PAYTXN_INSERT = "INSERT INTO IGRS_SEARCH_PAYMENT_DETAILS  (TRANSACTION_ID,DOC_SEARCH_TXN_ID,PAYMENT_FLAG,FUNCTION_ID,CREATED_BY,CREATED_DATE,TOTAL_FEE)  VALUES (?,?,?,?,?,SYSDATE,?)";
	public static final String DOC_SEARCH_SELECT_OLD_REGID = "SELECT REG_TXN_ID FROM IGRS_REG_TXN_DETLS WHERE TRIM(SRO_NAME)=" + " TRIM((SELECT OFFICE_NAME FROM dea_office_mapping WHERE OFFICE_ID=(SELECT OFFICE_ID FROM IGRS_OFFICE_MASTER" + " WHERE OFFICE_NAME=?))) OR TRIM(SRO_NAME)=TRIM((SELECT H_OFFICE_NAME" + " FROM dea_office_mapping WHERE OFFICE_ID=(SELECT OFFICE_ID FROM IGRS_OFFICE_MASTER WHERE OFFICE_NAME=?)))" + " AND TRIM(SR_NAME) =TRIM(?) AND TRIM(BOOK_NUMBER)=TRIM(?) AND TRIM(VOLUME_NUMBER)=TRIM(?) AND TRIM(SERIAL_NUMBER)=TRIM(?) AND to_char(CREATED_DATE,'dd/mm/yyyy')=to_char(?,'dd/mm/yyyy')";
	// insert for new reg no
	public static final String DOC_SEARCH_BTXN_INSERT = "INSERT INTO IGRS_DOC_SEARCH_DATA  (TRANSACTION_ID,DOC_SEARCH_TXN_ID,DISTRICT_ID,TEHSIL_NAME,AREA_NAME,WARD_NAME,WARD_PATWARI_NAME,MOHALLA_NAME,DATE_FROM,DATE_TO,CREATED_BY,CREATED_DATE,TRANS_PARTY_FIRST_NAME,TRANS_PARTY_MIDD_NAME,TRANS_PARTY_LAST_NAME,TRANS_PARTY_GENDER,TRANS_PARTY_MOTHER_NAME,TRANS_PARTY_FATHER_NAME,TRANS_PARTY_ADDRESS,PROPERTY_ADDRESS,REGISTRATION_DATE,ORGANIZATION_NAME)  VALUES (?,?,?,?,?,?,?,?,?,?,?,SYSDATE,?,?,?,?,?,?,?,?,?,?)";
	// insert for old reg no
	public static final String DOC_SEARCH_BTXN_NEW_INSERT = "INSERT INTO IGRS_DOC_SEARCH_DATA  (TRANSACTION_ID,DOC_SEARCH_TXN_ID,DISTRICT_ID,TEHSIL_ID,AREA_TYPE_ID,WARD_ID,WARD_PATWARI_ID,MOHALLA_VILLAGE_ID,DATE_FROM,DATE_TO,CREATED_BY,CREATED_DATE,TRANS_PARTY_FIRST_NAME,TRANS_PARTY_MIDD_NAME,TRANS_PARTY_LAST_NAME,TRANS_PARTY_GENDER,TRANS_PARTY_MOTHER_NAME,TRANS_PARTY_FATHER_NAME,TRANS_PARTY_ADDRESS,PROPERTY_ADDRESS,REGISTRATION_DATE,ORGANIZATION_NAME,REGISTRATION_DISTRICT_NAME,REGISTRATION_TEHSIL_NAME,SEARCH_TYPE)  VALUES (?,?,?,?,?,?,?,?,?,?,?,SYSDATE,?,?,?,?,?,?,?,?,?,?,?,?,?)";
	// added by shruti
	public static final String DOC_SEARCH_A_DETAILS_INSERT = " INSERT into IGRS_DOC_SEARCH_DETAILS (DOC_SEARCH_TXN_ID, SEARCHED_USER_ID,E_REGISTRATION_NUMBER, CREATED_BY,FUNCTION_ID, CREATED_DATE,DISTRICT_NAME,SRO_NAME,SR_NAME,BOOK_NO,VOL_NO,SERIAL_NO,REG_DATE,AREA_TYPE_ID) Values (?,?,?,?,?,SYSDATE,?,?,?,?,?,?,to_date(?,'dd/mm/yyyy'),?)";
	// end
	public static final String DOC_SEARCH_DETAILS_INSERT = " INSERT into IGRS_DOC_SEARCH_DETAILS (DOC_SEARCH_TXN_ID, SEARCHED_USER_ID,E_REGISTRATION_NUMBER, CREATED_BY,FUNCTION_ID, CREATED_DATE) Values (?,?,?,?,?,SYSDATE)";
	public static final String DOC_OFFICE_SEARCH_DETAILS_INSERT = " Insert into IGRS_DOC_SEARCH_DETAILS (DOC_SEARCH_TXN_ID, SEARCHED_USER_ID,E_REGISTRATION_NUMBER, CREATED_BY,FUNCTION_ID,OFFICIAL_SEARCH_PURPOSE, CREATED_DATE) Values (?,?,?,?,?,?,SYSDATE)";
	public static final String DOC_OFFICE_SEARCH_DETAILS_UPDATE = "UPDATE IGRS_DOC_SEARCH_DETAILS set DOC_NAME=? ,DOC_PATH=? where DOC_SEARCH_TXN_ID=?";
	public static final String SEARCH_RESUME_QRY = "select FUNCTION_ID from IGRS_SEARCH_PAYMENT_DETAILS where DOC_SEARCH_TXN_ID=? and" + " created_date=(select max(created_date) from IGRS_SEARCH_PAYMENT_DETAILS" + " where DOC_SEARCH_TXN_ID=?)";
	public static final String CHECKUSERTYPE = "SELECT USER_TYPE_ID FROM IGRS_USERS_LIST WHERE USER_ID=?";
	public static final String GETRUDISTRICT = "SELECT idm.district_name,iurd.DISTRICT_ID FROM IGRS_USER_REG_DETAILS iurd ,IGRS_DISTRICT_MASTER idm WHERE iurd.district_id=idm.district_id and USER_ID=?";
	public static final String GETSPDISTRICT = "SELECT idm.district_name,isd.DISTRICT_ID FROM IGRS_SP_DETLS isd," + "igrs_district_master idm WHERE isd.district_id=idm.district_id" + " and isd.CREATED_BY=? AND isd.STATUS='A' AND isd.APPLCTN_STATUS='8'";
	public static final String GETOFFICENAME = "SELECT iom.office_name,iom.DISTRICT_ID,idm.district_name FROM igrs_office_master iom,igrs_district_master idm" + " where iom.district_id=idm.district_id and iom.office_id=?";
	
	// added by shruti-25th september
	/*
	 * public static final StringGETPROPERTYDTLS=
	 * "SELECT  a.REG_TXN_ID, a.PROPERTY_ID,(SELECT b.property_type_name  FROM igrs_property_type_master b  "
	 * +
	 * " WHERE b.property_type_status = 'A'  AND b.property_type_id= a.PROP_TYPE_ID) PROPERTY_TYPE_NAME,(SELECT c.district_name "
	 * +
	 * " FROM igrs_district_master c  WHERE c.district_status = 'A'  AND c.district_id=a.DISTRICT_ID) DISTRICT_NAME,(SELECT d.tehsil_name FROM igrs_tehsil_master d "
	 * +
	 * "   WHERE d.tehsil_status = 'A'   AND d.tehsil_id=a.TEHSIL_ID) TEHSIL_NAME,(SELECT e.WARD_PATWARI_NAME FROM IGRS_WARD_PATWARI_MASTER  "
	 * +
	 * "     e WHERE e.WARD_PATWARI_STATUS='A' AND e.WARD_PATWARI_ID=a.WARD_ID) WARD_PATWARI_NAME,(SELECT f.MOHALLA_VILLAGE_NAME  FROM  "
	 * +
	 * "    IGRS_MOHALLA_VILLAGE_MASTER f WHERE  f.MOHALLA_VILLAGE_STATUS='A' AND f.MOHALLA_VILLAGE_ID=a.MOHALLA_ID) MOHALLA_VILLAGE_NAME,  "
	 * +
	 * "  (SELECT g.AREA_TYPE_NAME FROM IGRS_AREA_TYPE_MASTER g WHERE  g.AREA_TYPE_STATUS='A'  AND  g.AREA_TYPE_ID=a.AREA_TYPE_ID) AREA_TYPE_NAME,  "
	 * +
	 * "   (SELECT h.MUNICIPAL_BODY_NAME  FROM IGRS_MUNICIPAL_BODY_MASTER h WHERE  h.MUNICIPAL_BODY_STATUS='A'  AND  h.MUNICIPAL_BODY_ID=a.GOV_BODY_ID) "
	 * +
	 * "	     MUNICIPAL_BODY_NAME,a.VIKAS_KHAND,RI_CIRCLE,a.LAYOUT_DETAIL,a.NAZOOL_SHEET_NUMBER,  "
	 * +
	 * "			  a.PROPERTY_ADDRESS,a.EAST_BOUNDARY,a.WEST_BOUNDARY,a.NORTH_BOUNDARY,a.SOUTH_BOUNDARY,a.AREA,MAP_PATH FROM IGRS_REG_PROPRTY_DTLS a "
	 * + "	 where  a.REG_TXN_ID in (?)";
	 */

	// modified by shruti---4 sep 2014
	public static final String GETPROPERTYDTLS = "SELECT  a.REG_TXN_ID, a.PROPERTY_ID,(SELECT b.property_type_name  FROM igrs_property_type_master b " + "WHERE b.property_type_status = 'A'  AND b.property_type_id= a.PROP_TYPE_ID) PROPERTY_TYPE_NAME,(SELECT c.district_name" + " FROM igrs_district_master c  WHERE c.district_status = 'A'  AND c.district_id=a.DISTRICT_ID) DISTRICT_NAME," + " (SELECT d.tehsil_name FROM igrs_tehsil_master d WHERE d.tehsil_status = 'A'   AND d.tehsil_id=a.TEHSIL_ID) TEHSIL_NAME," + " (SELECT e.WARD_PATWARI_NAME FROM IGRS_WARD_PATWARI_MASTER  e WHERE e.WARD_PATWARI_STATUS='A' AND e.WARD_PATWARI_ID=a.WARD_ID) WARD_PATWARI_NAME," + " (SELECT f.COLONY_NAME  FROM  IGRS_COLONY_MASTER f WHERE  f.COLONY_STATUS='A' AND f.COLONY_ID=a.MOHALLA_ID) MOHALLA_VILLAGE_NAME," + " (SELECT g.AREA_TYPE_NAME FROM IGRS_AREA_TYPE_MASTER g WHERE  g.AREA_TYPE_STATUS='A'  AND  g.AREA_TYPE_ID=a.AREA_TYPE_ID) AREA_TYPE_NAME," + "(SELECT h.SUB_AREA_TYPE_NAME  FROM IGRS_SUB_AREA_TYPE_MASTER h WHERE  h.SUB_AREA_TYPE_STATUS='A'  AND  h.SUB_AREA_TYPE_ID=a.GOV_BODY_ID)" + " MUNICIPAL_BODY_NAME,a.VIKAS_KHAND,RI_CIRCLE,a.LAYOUT_DETAIL,a.NAZOOL_SHEET_NUMBER," + " a.PROPERTY_ADDRESS,a.EAST_BOUNDARY,a.WEST_BOUNDARY,a.NORTH_BOUNDARY,a.SOUTH_BOUNDARY,a.AREA,MAP_PATH FROM IGRS_REG_PROPRTY_DTLS a" + " where  a.REG_TXN_ID in(?)";
	
	// added by shruti
	/*
	 * public static final StringGETPROPERTYDTLS_H=
	 * "SELECT  a.REG_TXN_ID, a.PROPERTY_ID,(SELECT b.H_property_type_name  FROM igrs_property_type_master b  "
	 * +
	 * " WHERE b.property_type_status = 'A'  AND b.property_type_id= a.PROP_TYPE_ID) PROPERTY_TYPE_NAME,(SELECT c.H_district_name "
	 * +
	 * " FROM igrs_district_master c  WHERE c.district_status = 'A'  AND c.district_id=a.DISTRICT_ID) DISTRICT_NAME,(SELECT d.H_tehsil_name FROM igrs_tehsil_master d "
	 * +
	 * "   WHERE d.tehsil_status = 'A'   AND d.tehsil_id=a.TEHSIL_ID) TEHSIL_NAME,(SELECT e.H_WARD_PATWARI_NAME FROM IGRS_WARD_PATWARI_MASTER  "
	 * +
	 * "     e WHERE e.WARD_PATWARI_STATUS='A' AND e.WARD_PATWARI_ID=a.WARD_ID) WARD_PATWARI_NAME,(SELECT f.H_MOHALLA_VILLAGE_NAME  FROM  "
	 * +
	 * "    IGRS_MOHALLA_VILLAGE_MASTER f WHERE  f.MOHALLA_VILLAGE_STATUS='A' AND f.MOHALLA_VILLAGE_ID=a.MOHALLA_ID) MOHALLA_VILLAGE_NAME,  "
	 * +
	 * "  (SELECT g.H_AREA_TYPE_NAME FROM IGRS_AREA_TYPE_MASTER g WHERE  g.AREA_TYPE_STATUS='A'  AND  g.AREA_TYPE_ID=a.AREA_TYPE_ID) AREA_TYPE_NAME,  "
	 * +
	 * "   (SELECT h.H_MUNICIPAL_BODY_NAME  FROM IGRS_MUNICIPAL_BODY_MASTER h WHERE  h.MUNICIPAL_BODY_STATUS='A'  AND  h.MUNICIPAL_BODY_ID=a.GOV_BODY_ID) "
	 * +
	 * "	     MUNICIPAL_BODY_NAME,a.VIKAS_KHAND,RI_CIRCLE,a.LAYOUT_DETAIL,a.NAZOOL_SHEET_NUMBER,  "
	 * +
	 * "			  a.PROPERTY_ADDRESS,a.EAST_BOUNDARY,a.WEST_BOUNDARY,a.NORTH_BOUNDARY,a.SOUTH_BOUNDARY,a.AREA,MAP_PATH FROM IGRS_REG_PROPRTY_DTLS a "
	 * + "	 where  a.REG_TXN_ID in (?)";
	 */
	// end
	// modified by shruti---4 sep 2014
	public static final String GETPROPERTYDTLS_H = "SELECT  a.REG_TXN_ID, a.PROPERTY_ID,(SELECT b.h_property_type_name  FROM igrs_property_type_master b " + "WHERE b.property_type_status = 'A'  AND b.property_type_id= a.PROP_TYPE_ID) PROPERTY_TYPE_NAME,(SELECT c.h_district_name" + " FROM igrs_district_master c  WHERE c.district_status = 'A'  AND c.district_id=a.DISTRICT_ID) DISTRICT_NAME," + " (SELECT d.h_tehsil_name FROM igrs_tehsil_master d WHERE d.tehsil_status = 'A'   AND d.tehsil_id=a.TEHSIL_ID) TEHSIL_NAME," + " (SELECT e.H_WARD_PATWARI_NAME FROM IGRS_WARD_PATWARI_MASTER  e WHERE e.WARD_PATWARI_STATUS='A' AND e.WARD_PATWARI_ID=a.WARD_ID) WARD_PATWARI_NAME," + " (SELECT f.H_COLONY_NAME  FROM  IGRS_COLONY_MASTER f WHERE  f.COLONY_STATUS='A' AND f.COLONY_ID=a.MOHALLA_ID) MOHALLA_VILLAGE_NAME," + " (SELECT g.H_AREA_TYPE_NAME FROM IGRS_AREA_TYPE_MASTER g WHERE  g.AREA_TYPE_STATUS='A'  AND  g.AREA_TYPE_ID=a.AREA_TYPE_ID) AREA_TYPE_NAME," + "(SELECT h.H_SUB_AREA_TYPE_NAME  FROM IGRS_SUB_AREA_TYPE_MASTER h WHERE  h.SUB_AREA_TYPE_STATUS='A'  AND  h.SUB_AREA_TYPE_ID=a.GOV_BODY_ID)" + " MUNICIPAL_BODY_NAME,a.VIKAS_KHAND,RI_CIRCLE,a.LAYOUT_DETAIL,a.NAZOOL_SHEET_NUMBER," + " a.PROPERTY_ADDRESS,a.EAST_BOUNDARY,a.WEST_BOUNDARY,a.NORTH_BOUNDARY,a.SOUTH_BOUNDARY,a.AREA,MAP_PATH FROM IGRS_REG_PROPRTY_DTLS a" + " where  a.REG_TXN_ID in(?)";
	
	public static final String GETPARTYDTLS = "SELECT PARTY_FIRST_NAME,PARTY_MIDDLE_NAME,PARTY_LAST_NAME,( SELECT PARTY_TYPE_NAME FROM " + " IGRS_PARTY_TYPE_MASTER WHERE PARTY_TYPE_STATUS='A' AND  PARTY_TYPE_ID=rtpd.PARTY_TYPE_ID) PARTY_TYPE_NAME, " + " PARTY_GENDER,PARTY_AGE,NATIONALITY,(SELECT COUNTRY_NAME FROM IGRS_COUNTRY_MASTER WHERE COUNTRY_STATUS='A' " + " AND COUNTRY_ID=rtpd.COUNTRY_ID) COUNTRY_NAME,(SELECT STATE_NAME FROM IGRS_STATE_MASTER WHERE " + " STATE_STATUS='A' AND STATE_ID=RTPD.STATE_ID) STATE_NAME, (SELECT DISTRICT_NAME FROM IGRS_DISTRICT_MASTER  WHERE DISTRICT_STATUS='A' AND  " + " DISTRICT_ID= RTPD.DISTRICT_ID) DISTRICT_NAME,PARTY_ADDRESS,POSTAL_CODE,PHONE_NUMBER,MOBILE_NUMBER,EMAIL_ID, " + " APPELLATE_TYPE_ID,GUARDIAN_NAME, MOTHER_NAME,ORGANIZATION_NAME,AUTHRZD_PERSN_NAME,SHARE_OF_PROPERTY,PHOTO_PROOF_ID,NAME_OF_OFFICIAL, DESG_OF_OFFICIAL, ADRS_OF_OFFICIAL from IGRS_REG_TXN_PARTY_DETLS rtpd" + " where REG_TXN_ID=? and rtpd.IS_APPLICANT not in('O') order by PARTY_TYPE_ID";
	
	// added by shruti
	public static final String GETPARTYDTLS_H = "SELECT PARTY_FIRST_NAME,PARTY_MIDDLE_NAME,PARTY_LAST_NAME,( SELECT H_PARTY_TYPE_NAME FROM " + " IGRS_PARTY_TYPE_MASTER WHERE PARTY_TYPE_STATUS='A' AND  PARTY_TYPE_ID=rtpd.PARTY_TYPE_ID) PARTY_TYPE_NAME, " + " PARTY_GENDER,PARTY_AGE,NATIONALITY,(SELECT H_COUNTRY_NAME FROM IGRS_COUNTRY_MASTER WHERE COUNTRY_STATUS='A' " + " AND COUNTRY_ID=rtpd.COUNTRY_ID) COUNTRY_NAME,(SELECT H_STATE_NAME FROM IGRS_STATE_MASTER WHERE " + " STATE_STATUS='A' AND STATE_ID=RTPD.STATE_ID) STATE_NAME, (SELECT H_DISTRICT_NAME FROM IGRS_DISTRICT_MASTER  WHERE DISTRICT_STATUS='A' AND  " + " DISTRICT_ID= RTPD.DISTRICT_ID) DISTRICT_NAME,PARTY_ADDRESS,POSTAL_CODE,PHONE_NUMBER,MOBILE_NUMBER,EMAIL_ID, " + " APPELLATE_TYPE_ID,GUARDIAN_NAME, MOTHER_NAME,ORGANIZATION_NAME,AUTHRZD_PERSN_NAME,SHARE_OF_PROPERTY,PHOTO_PROOF_ID,NAME_OF_OFFICIAL, DESG_OF_OFFICIAL, ADRS_OF_OFFICIAL from IGRS_REG_TXN_PARTY_DETLS rtpd" + " where REG_TXN_ID=? and rtpd.IS_APPLICANT not in('O') order by PARTY_TYPE_ID";
	// end
	public static final String UPDATEDOCSRCHDTLS = "UPDATE IGRS_DOC_SEARCH_DETAILS SET E_REGISTRATION_NUMBER=? WHERE DOC_SEARCH_TXN_ID=? ";
	public static final String UPDATEPYMTTXNDTLS = " UPDATE IGRS_DOC_SEARCH_DETAILS SET E_REGISTRATION_NUMBER=? WHERE DOC_SEARCH_TXN_ID=?";
	public static final String CHKESTAMPCODE = "SELECT ESTAMP_CODE FROM IGRS_ESTAMP_DETLS WHERE REG_INIT_ID=?";
	public static final String GETTYPEBRECORDDTLS = "SELECT DOC_SEARCH_TXN_ID,DISTRICT_ID,TEHSIL_ID,AREA_TYPE_ID,WARD_ID,MOHALLA_VILLAGE_ID,to_char(DATE_FROM,'dd/mm/yyyy'),to_char(DATE_TO,'dd/mm/yyyy') FROM IGRS_DOC_SEARCH_DATA" + " WHERE DOC_SEARCH_TXN_ID=?";
	public static final String GETUSERDTLSLIST = "select distinct ifm.FUNCTION_NAME,nvl(idsd.E_REGISTRATION_NUMBER,'-'),nvl(DISTRICT_NAME,'-'),nvl(SRO_NAME,'-'),nvl(SR_NAME,'-'),nvl(BOOK_NO,'-'),nvl(VOL_NO,'-'),nvl(SERIAL_NO,'-'),nvl(to_char(REG_DATE,'dd/mm/yyyy'),'-'),idsd.DOC_SEARCH_TXN_ID from" + " IGRS_DOC_SEARCH_DETAILS idsd,IGRS_SEARCH_PAYMENT_DETAILS ispd,IGRS_FUNCTION_MASTER ifm" + " where  ispd.PAYMENT_FLAG='P' and ifm.FUNCTION_ID= idsd.FUNCTION_ID and ispd.DOC_SEARCH_TXN_ID=idsd.DOC_SEARCH_TXN_ID" + " and idsd.SEARCHED_USER_ID=?";
	public static final String GETDWNLOADLOGLIST = "SELECT idsd.SEARCHED_USER_ID,iul.USER_TYPE_ID,count(ispd.DOC_SEARCH_TXN_ID) FROM IGRS_DOC_SEARCH_DETAILS idsd," + "IGRS_SEARCH_PAYMENT_DETAILS ispd,IGRS_USERS_LIST iul where ispd.FUNCTION_ID in('FUN_230','FUN_232') and ispd.payment_flag='P'" + " and idsd.SEARCHED_USER_ID=iul.USER_ID and trunc(ispd.created_date)>=(to_date(?,'dd/mm/yyyy')-?)" + " and idsd.DOC_SEARCH_TXN_ID=ispd.DOC_SEARCH_TXN_ID" + " group by idsd.SEARCHED_USER_ID,iul.USER_TYPE_ID having count(ispd.DOC_SEARCH_TXN_ID)>=?";
	
	public static final String GETCAVEATDTLS = "SELECT  b.CAVEAT_TYPE_DESC,a.CAVEAT_DETAILS,a.CAVEAT_STATUS from IGRS_CAVEAT_TXN a, IGRS_CAVEAT_TYPE_MASTER b where a.CAVEAT_TYPE_ID=b.CAVEAT_TYPE_ID " + "and a.REGISTRATION_ID   in ?  UNION SELECT 'Caveat logged by Bank',c.REMARKS,c.CAVEAT_STATUS from IGRS_CAVEAT_BANK_TXN c where c.REGISTRATION_ID   in ?";
	
	public static final String GETCAVEATDTLS_H = "SELECT  b.CAVEAT_TYPE_DESC,a.CAVEAT_DETAILS,a.H_CAVEAT_STATUS from IGRS_CAVEAT_TXN a, IGRS_CAVEAT_TYPE_MASTER b where a.CAVEAT_TYPE_ID=b.CAVEAT_TYPE_ID " + "and a.REGISTRATION_ID   in ?  UNION SELECT 'बैंक द्वारा लॉग चेतावनी',c.REMARKS,c.H_CAVEAT_STATUS from IGRS_CAVEAT_BANK_TXN c where c.REGISTRATION_ID   in ?";
	
	public static final String GETSUBCLAUSEDTLS = "SELECT   SUB_CLAUSE_NAME   FROM IGRS_SUB_CLAUSE_MASTER where  SUB_CLAUSE_STATUS='A' " + "AND SUB_CLAUSE_ID IN (SELECT  SUBCLAUSE_ID FROM IGRS_REG_INIT_PROPRTY_DTLS a, IGRS_PROP_TXN_DETAILS P  where  a.PROP_VAL_ID=P.VAL_TXN_ID AND   a.REG_TXN_ID in ?";
	
	/*
	 * public static final StringGETCOMPIANCEDTLS=
	 * "SELECT COMPLAINCE_NAME FROM IGRS_REG_COMPLIANCE_DETAILS WHERE COMPLAINCE_STATUS='A'"
	 * ;
	 */
	// ADDED BY SHRUTI--MODIFIED AS TABLE DOESNOT EXIST---
	public static final String GETCOMPIANCEDTLS = "SELECT '' FROM DUAL";
	// END
	
	public static final String GEWTADVNCDSRCHDTLS = "SELECT distinct C.REGISTRATION_NUMBER,to_char(c.CREATED_DATE,'dd/mm/yyyy') created_date,A.PROPERTY_ID, A.PROPERTY_ADDRESS " + "FROM IGRS_REG_PROPRTY_DTLS A,IGRS_REG_TXN_DETLS C where A.REG_TXN_ID=C.REG_TXN_ID" + "  AND c.REGISTRATION_NUMBER IS NOT NULL AND C.REGISTRATION_NUMBER=?";
	
	public static final String GETDOCPARTYDTLS = "SELECT distinct PARTYPE.PARTY_TYPE_ID,PARTY_TYPE_NAME,PARTY_FIRST_NAME||' '||PARTY_MIDDLE_NAME||' ' " + " ||PARTY_LAST_NAME || ' ' ||ORGANIZATION_NAME||  '' AUTHRZD_PERSN_NAME  FROM IGRS_REG_TXN_PARTY_DETLS PARDET ,IGRS_PARTY_TYPE_MASTER PARTYPE  ,IGRS_REG_INIT_PROP_TRANS_MAP PROPMAP ,IGRS_REG_PROPRTY_DTLS PROPDTLS " + " WHERE PARTY_TYPE_STATUS='A' AND  PARTYPE.PARTY_TYPE_ID=PARDET.PARTY_TYPE_ID AND PROPMAP.PROPERTY_ID=PROPDTLS.PROPERTY_ID AND PARDET.PARTY_TXN_ID=PROPMAP.PARTY_TXN_ID AND " + "  PROPMAP.PROPERTY_ID=? and PROPDTLS.PROPERTY_ID=?";
	
	public static final String GETSEARCHALISTDTLS = "SELECT ATTRIBUTE_VALUE FROM IGRS_CONFIG_PARAM_LIST WHERE ATTRIBUTE_NAME=? AND ATTRIBUTE_STATUS='A'";
	public static final String GETSEARCHARECORDLIST = "select DISTINCT T1.DOCTXN,T1.REGNO,T1.CDATE,T1.N from ( select  idsd.DOC_SEARCH_TXN_ID DOCTXN,nvl(E_REGISTRATION_NUMBER,'-') REGNO," + " to_char(idsd.CREATED_DATE,'dd/mm/yyyy') CDATE,(select 'N' from dual) N from IGRS_DOC_SEARCH_DETAILS idsd," + "IGRS_SEARCH_PAYMENT_DETAILS ispd where idsd.DOC_SEARCH_TXN_ID=ispd.DOC_SEARCH_TXN_ID and" + " idsd.function_id IN ('FUN_062','FUN_230') and ispd.function_id IN ('FUN_062','FUN_230')  and ispd.created_by=? "// AND
																																																																																																																															// rownum<?
																																																																																																																															// "
	+ " AND idsd.IS_OLD IS NULL order by idsd.created_date desc) T1   ORDER BY to_date(T1.CDATE ,'dd-mm-yyyy')  desc, T1.DOCTXN desc";
	
	public static final String GETSEARCHBLISTDTLS = "SELECT ATTRIBUTE_VALUE FROM IGRS_CONFIG_PARAM_LIST WHERE ATTRIBUTE_NAME=? AND ATTRIBUTE_STATUS='A'";
	
	public static final String GETSEARCHBRECORDLIST = "SELECT DISTINCT T1.DOCTXN,  T1.REGNO,  T1.CDATE,  T1.N " + "from ( select  idsd.DOC_SEARCH_TXN_ID DOCTXN,nvl(E_REGISTRATION_NUMBER,'-') REGNO," + " to_char(idsd.CREATED_DATE,'dd/mm/yyyy') CDATE,(select 'N' from dual) N from IGRS_DOC_SEARCH_DETAILS idsd," + "IGRS_SEARCH_PAYMENT_DETAILS ispd where idsd.DOC_SEARCH_TXN_ID=ispd.DOC_SEARCH_TXN_ID and" + " idsd.function_id IN ('FUN_063','FUN_232') and ispd.function_id IN ('FUN_063','FUN_232')  and ispd.created_by=?" + " AND idsd.IS_OLD IS NULL  order by idsd.created_date ) T1 ORDER BY to_date(T1.CDATE ,'dd-mm-yyyy') DESC,T1.DOCTXN desc";
	
	public static final String GETLOGLENGTH = "SELECT ATTRIBUTE_VALUE FROM IGRS_CONFIG_PARAM_LIST WHERE ATTRIBUTE_NAME=? AND ATTRIBUTE_STATUS='A'";
	
	public static final String GETLOGDURATION = "SELECT ATTRIBUTE_VALUE FROM IGRS_CONFIG_PARAM_LIST WHERE ATTRIBUTE_NAME=? AND ATTRIBUTE_STATUS='A'";
	public static final String GETRLOGRECORD = "SELECT idsd.SEARCHED_USER_ID,iul.USER_TYPE_ID,count(ispd.DOC_SEARCH_TXN_ID) FROM IGRS_DOC_SEARCH_DETAILS idsd," + "IGRS_SEARCH_PAYMENT_DETAILS ispd,IGRS_USERS_LIST iul where ispd.FUNCTION_ID in('FUN_062','FUN_231') and ispd.payment_flag='P'" + " and idsd.SEARCHED_USER_ID=iul.USER_ID and trunc(ispd.created_date)>=(to_date(?,'dd/mm/yyyy')-?)" + " and idsd.DOC_SEARCH_TXN_ID=ispd.DOC_SEARCH_TXN_ID" + " group by idsd.SEARCHED_USER_ID,iul.USER_TYPE_ID having count(ispd.DOC_SEARCH_TXN_ID)>=?";
	
	public static final String GETDOWNLOADCONFIGPARAM = "SELECT ATTRIBUTE_VALUE FROM IGRS_CONFIG_PARAM_LIST WHERE ATTRIBUTE_NAME=? AND ATTRIBUTE_STATUS='A'";
	
	public static final String GETDWNLOADDURATION = "SELECT ATTRIBUTE_VALUE FROM IGRS_CONFIG_PARAM_LIST WHERE ATTRIBUTE_NAME=? AND ATTRIBUTE_STATUS='A'";
	
	// added by shruti---25 nov 2014
	public static final String GET_GO_LIVE_DATE = "SELECT to_char(GO_LIVE_DATE,'dd/mm/yyyy') FROM IGRS_DISTRICT_MASTER WHERE DISTRICT_ID=?";
	
	public static final String SEARCHBASICQRY = "SELECT T1.R1,T1.D1 " + "FROM (" + "SELECT DISTINCT R.REGISTRATION_NUMBER R1,to_char(R.UPDATE_DATE,'dd/mm/yyyy') D1" + " FROM IGRS_REG_TXN_DETLS R,IGRS_REG_PROPRTY_DTLS P,IGRS_REG_PROP_KHASARA_DTLS K,IGRS_REG_TXN_PARTY_DETLS PA,IGRS_TEHSIL_MASTER T" + " WHERE  R.REG_TXN_ID=PA.REG_TXN_ID(+) AND R.REG_TXN_ID=P.REG_TXN_ID(+)" + " AND P.PROPERTY_ID=K.PROPERTY_ID(+)  AND (R.NULL_AND_VOID_FLAG is not null OR  P.DISTRICT_ID=R.REGISTRATION_DIST_ID)  AND R.REGISTRATION_DIST_ID IN(select district_id" + " from igrs_district_master where UPPER(district_name) like ?) and (R.REGISTRATION_NUMBER" + " IS NOT NULL AND R.REGISTRATION_TXN_STATUS=17) and p.tehsil_id=t.tehsil_id";
	// UPDATED BY RUSTAM FOR When two properties of different district are added
	// in the initiation TIME
	public static final String SEARCHBASICQRY_UPDATED = "SELECT T1.R1, " + "  T1.D1 " + "FROM " + "  (SELECT DISTINCT R.REGISTRATION_NUMBER R1, " + "    TO_CHAR(R.UPDATE_DATE,'dd/mm/yyyy') D1 " + "  FROM IGRS_REG_TXN_DETLS R, " + "    IGRS_REG_PROPRTY_DTLS P, " + "    IGRS_REG_PROP_KHASARA_DTLS K, " + "    IGRS_REG_TXN_PARTY_DETLS PA, " + "    IGRS_TEHSIL_MASTER T " + "  WHERE R.REG_TXN_ID            =PA.REG_TXN_ID(+) " + "  AND R.REG_TXN_ID              =P.REG_TXN_ID(+) " + "  AND P.PROPERTY_ID             =K.PROPERTY_ID(+) " + "  AND (R.NULL_AND_VOID_FLAG    IS NOT NULL " + "  OR P.DISTRICT_ID              =R.REGISTRATION_DIST_ID " + "  OR p.district_id              =?) " + "  AND ( R.REGISTRATION_DIST_ID IN " + "    (SELECT district_id " + "    FROM igrs_district_master " + "    WHERE UPPER(district_name) LIKE ? " + "    ) " + "  OR p.district_id             =?) " + "  AND(R.REGISTRATION_NUMBER   IS NOT NULL " + "  AND R.REGISTRATION_TXN_STATUS=17) " + "  AND p.tehsil_id              =t.tehsil_id";
	
	//update by saurav for mview
	public static final String GET_TABLE_NAME="select REG_TABLE_NAME,PARTY_TABLE_NAME,START_DATE, END_DATE from IGRS_FISCAL_YEAR WHERE FISCAL_YEAR_ID=? AND OLDORNEW='N'";
	//public static final String SEARCH_BASE_QUERY="SELECT T1.R1,  T1.D1  FROM ( SELECT DISTINCT p.REGISTRATION_NUMBER R1, TO_CHAR(p.UPDATE_DATE,'dd/mm/yyyy') D1 FROM ";
	public static final String SEARCH_BASE_QUERY="SELECT DISTINCT p.REGISTRATION_NUMBER R1, TO_CHAR(p.UPDATE_DATE,'dd/mm/yyyy') D1 FROM ";
	public static final String COMPLETING_BASE_QUERY=" IGRS_TEHSIL_MASTER T WHERE p.REG_TXN_ID          =PA.REG_TXN_ID(+) AND p.REGISTRATION_DIST_ID =?  AND p.tehsil_id             =t.tehsil_id";
	public static final String SEARCHBASICQRY_UPDATED_MV="SELECT T1.R1,  T1.D1  FROM ( SELECT DISTINCT p.REGISTRATION_NUMBER R1, TO_CHAR(p.UPDATE_DATE,'dd/mm/yyyy') D1 FROM MV_PROPERTY_DETLS_DOC_SEARCH P, IGRS_REG_TXN_PARTY_DETLS PA, IGRS_TEHSIL_MASTER T WHERE p.REG_TXN_ID          =PA.REG_TXN_ID(+) AND p.REGISTRATION_DIST_ID =?  AND p.tehsil_id             =t.tehsil_id";
	public static final String GETQRYWITHTEHSIL = " AND  R.REGISTRATION_TEHSIL_ID=T.TEHSIL_ID AND R.REGISTRATION_TEHSIL_ID IN(SELECT TEHSIL_ID FROM IGRS_TEHSIL_MASTER WHERE UPPER(TEHSIL_NAME) like ?)";
	
	public static final String GETQRYWITHDURATION = " AND p.UPDATE_DATE BETWEEN to_date(?,'dd-mon-yy hh24:mi:ss') AND to_date(?,'dd-mon-yy hh24:mi:ss')";
	
	public static final String GETQRYWITHPROPDISTRICT = " AND P.DISTRICT_ID = ?";
	
	public static final String GETQRYWITHPROPTEHSIL = " AND P.TEHSIL_ID = ?";
	
	public static final String GETQRYWITHPROPAREA = " AND P.AREA_TYPE_ID = ?";
	
	public static final String GETQRYWITHPROPGOVBODY = " AND P.GOV_BODY_ID = ?";
	
	public static final String GETQRYWITHPROPWARD = " AND P.WARD_ID = ?";
	
	public static final String GETQRYWITHPROPMOHALLA = " AND P.MOHALLA_ID = ?";
	
	public static final String GETQRYWITHPROPKHASRA = " AND UPPER(P.KHASRA_NUMBER) like ?";
	
	// public static final String
	// GETQRYWITHPARTYFIRSTNAME=" AND PA.PARTY_FIRST_NAME like ?";
	public static final String GETQRYWITHPARTYFIRSTNAME = " AND (UPPER(PA.PARTY_FIRST_NAME) like ? OR UPPER(PA.NAME_OF_OFFICIAL) like ?)";
	
	public static final String GETQRYWITHPARTYMIDDLENAME = " AND UPPER(PA.PARTY_MIDDLE_NAME) like ?";
	
	public static final String GETQRYWITHPARTYLASTNAME = " AND UPPER(PA.PARTY_LAST_NAME) like ?";
	
	public static final String GETQRYWITHPARTYMOTHERNAME = " AND UPPER(PA.MOTHER_NAME) like ?";
	
	public static final String GETQRYWITHPARTYGUARDIANNAME = " AND UPPER(PA.GUARDIAN_NAME) like ?";
	
	public static final String GETQRYWITHPARTYORGNAME = " AND UPPER(PA.ORGANIZATION_NAME) like ?";
	
	public static final String GETQRYWITHPARTYADDRESS = " AND (UPPER(PA.PARTY_ADDRESS) like ? OR UPPER(PA.ADRS_OF_OFFICIAL) like ?)";
	
	public static final String GETFNAMEQUERY=" AND PA.PARTY_FIRST_NAME LIKE ? ";
	
	public static final String GETMIDNAMEQUERY=" AND PA.PARTY_MIDDLE_NAME LIKE ? ";
	
	public static final String GETLASTNAMEQUERY=" AND PA.PARTY_LAST_NAME LIKE ? ";
	
	public static final String GETMOTHERNAME=" AND PA.MOTHER_NAME LIKE ? ";
	
	public static final String GETGUARDIANNAME=" AND PA.GUARDIAN_NAME LIKE ? ";
	
	public static final String GETORGNAME=" AND PA.ORGANIZATION_NAME LIKE ? ";
	
	//public static final String ORDERREGNOASC = " ) T1 ORDER BY TO_DATE(T1.D1,'DD-MM-YYYY') DESC";
	public static final String ORDERREGNOASC = " ORDER BY TO_CHAR(p.UPDATE_DATE,'dd/mm/yyyy') DESC";
	// hi
	public static final String SEARCHBASICQRYHI = "SELECT T1.R1,T1.D1 " + "FROM (" + "SELECT DISTINCT R.REGISTRATION_NUMBER R1,to_char(R.UPDATE_DATE,'dd/mm/yyyy') D1" + " FROM IGRS_REG_TXN_DETLS R,IGRS_REG_PROPRTY_DTLS P,IGRS_REG_PROP_KHASARA_DTLS K,IGRS_REG_TXN_PARTY_DETLS PA,IGRS_TEHSIL_MASTER T" + " WHERE  R.REG_TXN_ID=PA.REG_TXN_ID(+) AND R.REG_TXN_ID=P.REG_TXN_ID(+)" + " AND P.PROPERTY_ID=K.PROPERTY_ID(+)  AND P.DISTRICT_ID=R.REGISTRATION_DIST_ID  AND R.REGISTRATION_DIST_ID IN(select district_id" + " from igrs_district_master where UPPER(h_district_name) like ?) and (R.REGISTRATION_NUMBER" + " IS NOT NULL AND R.REGISTRATION_TXN_STATUS=17) and p.tehsil_id=t.tehsil_id ";
	// UPDATED BY RUSTAM FOR When two properties of different district are added
	// in the initiation TIME
	public static final String SEARCHBASICQRYHI_UPDATED = "SELECT T1.R1, " + "  T1.D1 " + "FROM " + "  (SELECT DISTINCT R.REGISTRATION_NUMBER R1, " + "    TO_CHAR(R.UPDATE_DATE,'dd/mm/yyyy') D1 " + "  FROM IGRS_REG_TXN_DETLS R, " + "    IGRS_REG_PROPRTY_DTLS P, " + "    IGRS_REG_PROP_KHASARA_DTLS K, " + "    IGRS_REG_TXN_PARTY_DETLS PA, " + "    IGRS_TEHSIL_MASTER T " + "  WHERE R.REG_TXN_ID            =PA.REG_TXN_ID(+) " + "  AND R.REG_TXN_ID              =P.REG_TXN_ID(+) " + "  AND P.PROPERTY_ID             =K.PROPERTY_ID(+) " + "  AND (R.NULL_AND_VOID_FLAG    IS NOT NULL " + "  OR P.DISTRICT_ID              =R.REGISTRATION_DIST_ID " + "  OR p.district_id              =?) " + "  AND ( R.REGISTRATION_DIST_ID IN " + "    (SELECT district_id " + "    FROM igrs_district_master " + "    WHERE UPPER(h_district_name) LIKE ? " + "    ) " + "  OR p.district_id             =?) " + "  AND(R.REGISTRATION_NUMBER   IS NOT NULL " + "  AND R.REGISTRATION_TXN_STATUS=17) " + "  AND p.tehsil_id              =t.tehsil_id";
	
	//updated by saurav for mview implementation
	public static final String SEARCHBASICQRYHI_UPDATED_MV = "SELECT T1.R1,  T1.D1  FROM ( SELECT DISTINCT p.REGISTRATION_NUMBER R1, TO_CHAR(p.UPDATE_DATE,'dd/mm/yyyy') D1 FROM MV_PROPERTY_DETLS_DOC_SEARCH P, IGRS_REG_TXN_PARTY_DETLS PA, IGRS_TEHSIL_MASTER T WHERE p.REG_TXN_ID          =PA.REG_TXN_ID(+) AND p.REGISTRATION_DIST_ID =?  AND p.tehsil_id             =t.tehsil_id";
	public static final String GETQRYWITHTEHSILHI = " AND  R.REGISTRATION_TEHSIL_ID=T.TEHSIL_ID AND R.REGISTRATION_TEHSIL_ID IN(SELECT TEHSIL_ID FROM IGRS_TEHSIL_MASTER WHERE H_TEHSIL_NAME like ?)";
	
	public static final String CHECK_PAYMENT_DETAILS = "SELECT NVL(PAID_AMOUNT,0),NVL(TOTAL_FEE,0) FROM IGRS_SEARCH_PAYMENT_DETAILS WHERE DOC_SEARCH_TXN_ID=? AND FUNCTION_ID=?";
	
	public static final String UPDATE_DOCSTATUS = "UPDATE IGRS_DOC_SEARCH_DETAILS SET E_REGISTRATION_NUMBER=? where DOC_SEARCH_TXN_ID=?  AND FUNCTION_ID IN('FUN_063','FUN_232')";
	
	public static final String UPDATE_DOWNSTATUS = "UPDATE IGRS_DOC_SEARCH_DETAILS SET DOC_SEARCH_STATUS='Y' where DOC_SEARCH_TXN_ID=? ";
	
	public static final String GET_DOWNSTATUS = "SELECT DISTINCT NVL(DOC_SEARCH_STATUS,'N') FROM IGRS_DOC_SEARCH_DETAILS  where DOC_SEARCH_TXN_ID=? ";
	
	public static final String GET_SIGN_STATUS = "SELECT SIGNATURE_TIME FROM IGRS_REG_TXN_DETLS WHERE REGISTRATION_NUMBER =? ";
	// "(SELECT DISTINCT E_REGISTRATION_NUMBER FROM IGRS_DOC_SEARCH_DETAILS  where DOC_SEARCH_TXN_ID=? )";
	
	public static final String DOWNLOAD_COMPLETED = "update IGRS_SEARCH_PAYMENT_DETAILS set paid_amount=0 where doc_search_txn_id=?";
	public static final String CHECKDOWNLOADED = "select count(*) from ( select  idsd.DOC_SEARCH_TXN_ID DOCTXN,nvl(E_REGISTRATION_NUMBER,'-') REGNO," + " to_char(idsd.CREATED_DATE,'dd/mm/yyyy') CDATE,(select 'N' from dual) N from IGRS_DOC_SEARCH_DETAILS idsd," + "IGRS_SEARCH_PAYMENT_DETAILS ispd where idsd.DOC_SEARCH_TXN_ID=ispd.DOC_SEARCH_TXN_ID and" + " idsd.function_id IN ('FUN_063','FUN_230','FUN_062','FUN_232') and ispd.function_id IN ('FUN_063','FUN_230','FUN_062','FUN_232') AND IDSD.DOC_SEARCH_STATUS='Y' and IDSD.DOC_SEARCH_TXN_ID=? "// AND
																																																																																																																																									// rownum<?
																																																																																																																																									// "
	+ " AND idsd.IS_OLD IS NULL order by idsd.created_date desc) T1   ORDER BY to_date(T1.CDATE ,'dd-mm-yyyy')  desc, T1.DOCTXN desc";
	public static final String NEW_DOWNLOAD_COMPLETED = "UPDATE IGRS_SEARCH_PAYMENT_DETAILS SET PAID_AMOUNT=0,DOC_SEARCH_TXN_ID=? WHERE DOC_SEARCH_TXN_ID IN(SELECT DOC_SEARCH_TXN_ID " + "FROM IGRS_DOC_SEARCH_DETAILS where DOC_SEARCH_STATUS!='Y' and DOC_SEARCH_TXN_ID=?)";
	public static final String NEW_UPDATE_DOWNSTATUS = "UPDATE IGRS_DOC_SEARCH_DETAILS SET DOC_SEARCH_STATUS='Y' where DOC_SEARCH_TXN_ID=? ";
	
	public static final String NULLVOIDRECORD = "SELECT COURT_NAME,COURT_ORDER_NO,TO_CHAR(COURT_ORDER_DATE,'DD/MM/YYYY') FROM NULL_AND_VOID_HISTORY WHERE REGISTRATION_NUMBER=? and UPDATION_DATE =(select max(UPDATION_DATE) from NULL_AND_VOID_HISTORY  where REGISTRATION_NUMBER =?)";
	
	public static final String CHECK_NULL_VOID_FLAG = "select NULL_AND_VOID_FLAG from IGRS_REG_TXN_DETLS where REGISTRATION_NUMBER=?";
	
	public static final String CHECK_PROTEST_FLAG = "select protest_status from IGRS_REG_TXN_DETLS where REGISTRATION_NUMBER=?";
	
	public static final String GETPROTESTID = "select PROTEST_ID ,COURT_ORDER_DOC_PATH,COURT_ORDER_DOC from IGRS_PROTEST_TXN_DETLS where PROPERTY_ID=? and PROTEST_ID is not null";
	
	// public static final String
	// UPDATE_DOCSTATUS="UPDATE IGRS_SEARCH_PAYMENT_DETAILS SET PAID_AMOUNT=0 WHERE DOC_SEARCH_TXN_ID=? AND FUNCTION_ID=? ";
	public static final String BankChargeId = "SELECT CAVEAT_BANK_TXN_ID, CAVEAT_STATUS, TO_CHAR(caveat_logged_date,'DD/MM/YYYY'),TO_CHAR(caveat_release_date,'DD/MM/YYYY') FROM IGRS_CAVEAT_BANK_TXN  WHERE REGISTRATION_ID=?";
	public static final String GETPROTESTDTLS = "SELECT PROPERTY_ID, PROTEST_TXN_ID ,COURT_ORDER_DOC_PATH,COURT_ORDER_DOC,PROTEST_STATUS FROM IGRS_PROTEST_TXN_DETLS WHERE PROPERTY_ID=? AND PROTEST_STATUS in('LOGGED','RELEASED')";
	public static final String GETPROTESTDTLS_H = "SELECT PROPERTY_ID,PROTEST_TXN_ID ,COURT_ORDER_DOC_PATH,COURT_ORDER_DOC,PROTEST_STATUS FROM IGRS_PROTEST_TXN_DETLS WHERE PROPERTY_ID=? AND PROTEST_STATUS in('LOGGED','RELEASED')";
	// ADDED BY SAURAV
	public static final String GET_DOC_COUNT = "SELECT count(a.REG_TXN_ID) FROM IGRS_REG_TXN_DETLS a, IGRS_DEED_TYPE_MASTER b WHERE a.DEED_ID    =b.DEED_TYPE_ID AND b.DOC_SRCH_FLAG='Y' and a.registration_number=?";
	//for old document search
	public static final String OLD_DOC_SEARCH_BASIC="select distinct A.VOLNO, A.DOC_NUM, A.REGISTREATION_DATE from IGRS_OLD_DOC_SEARCH_DATA A where A.DISTRICT_ID=?";
	public static final String OLD_DOC_SEARCH_DATE=" and A.REGISTREATION_DATE between to_Date(?,'dd/mm/yyyy') and to_date(?,'dd/mm/yyyy')";
	public static final String OLD_DOC_SEARCH_PROP_DIST=" and A.PROP_DISTRICT  =?";
	public static final String OLD_DOC_SEARCH_PROP_TEH=" and A.TEHSIL LIKE ?";
	public static final String OLD_DOC_SEARCH_PROP_AREA=" and A.AREA_ID =?";
	public static final String OLD_DOC_SEARCH_PROP_WARD=" AND A.WARD LIKE ?";
	public static final String OLD_DOC_SEARCH_PROP_MOHALLA=" AND A.COLONY LIKE ?";
	public static final String OLD_DOC_SEARCH_PROP_KHASRA=" AND A.KHASRA LIKE ?";
	public static final String OLD_DOC_SEARCH_FIRST_NAME=" AND (A.SELLER_NAME like ? or A.BUYER_NAME like ?)";
	public static final String OLD_DOC_SEARCH_MIDDLE_NAME=" AND (A.SELLER_NAME like ? or A.BUYER_NAME like ?)";
	public static final String OLD_DOC_SEARCH_LAST_NAME=" AND (A.SELLER_NAME like ? or A.BUYER_NAME like ?)";
	public static final String OLD_DOC_SEARCH_ORG_NAME=" AND (A.SELLER_NAME like ? or A.BUYER_NAME like ?)";
	public static final String OLD_DOC_SEARCH_PARTY_ADDRESS=" AND (A.BUYER_ADDRESS like ? or A.SELLER_ADDRESS like ?)";
	public static final String OLD_DOC_SEARCH_PROP_DATA="select DISTRICT, TEHSIL, SUBAREA, WARD,COLONY, PROP_TYPE, NVL(KHASRA,'NA'), NVL(PLOT_NUM,'NA'), PROP_ADDRESS,MARKET_VALUE, CONSI_AMOUNT,SELLER_NAME, SELLER_ADDRESS, BUYER_NAME, BUYER_ADDRESS, nvl(DOC_TYPE,'NA') from IGRS_OLD_DOC_SEARCH_DATA where VOLNO=? and DOC_NUM=?";
	public static final String OLD_DOC_SEARCH_PARTY_DATA="select distinct FINANCIAL_YEAR, REGISTREATION_DATE from IGRS_OLD_DOC_SEARCH_DATA where VOLNO=? and DOC_NUM=?";
	public static final String DOC_SEARCH_TYPE="select SEARCH_TYPE from IGRS_DOC_SEARCH_DATA where DOC_SEARCH_TXN_ID=?";
	//added by saurav for document search type b
	public static final String GET_PARTY_DETAIL="SELECT p.PARTY_FIRST_NAME||' '||p.PARTY_MIDDLE_NAME||' '||p.PARTY_LAST_NAME, p.ORGANIZATION_NAME||' '||p.AUTHRZD_PERSN_NAME, p.DESG_OF_OFFICIAL||' '||p.NAME_OF_OFFICIAL FROM IGRS_REG_TXN_PARTY_DETLS p, IGRS_REG_TXN_DETLS r WHERE p.reg_txn_id       =r.reg_txn_id AND r.REGISTRATION_NUMBER=?";
	
	public static final String DOC_SEARCH_HYPER_LINK="select ATTRIBUTE_VALUE from IGRS_CONFIG_PARAM_LIST where ATTRIBUTE_ID='ATT_DOC'";
	public static final String DOC_SEARCH_TEHSIL="select DISTINCT A.TEHSIL_ID, A.TEHSIL_NAME,A.H_TEHSIL_NAME from igrs_tehsil_master A, IGRS_GUIDELINE_DOC_SEARCH_FY B where B.district_id=? AND B.FY in (?) AND a.district_id=b.district_id ORDER BY A.TEHSIL_NAME";
	public static final String DOC_SEARCH_SUB_AREA_URBAN="select b.SUB_AREA_TYPE_ID, b.SUB_AREA_TYPE_NAME, b.H_SUB_AREA_TYPE_NAME from IGRS_GUIDELINE_DOC_SEARCH_FY a, igrs_sub_area_type_master b where a.area_type_id=? and a.tehsil_id=b.tehsil_id and b.tehsil_id=?";
	public static final String DOC_SEARCH_SUB_AREA_RURAL="select DISTINCT a.SUB_AREA_TYPE_ID, a.SUB_AREA_TYPE_NAME, a.H_SUB_AREA_TYPE_NAME from igrs_sub_area_type_master a, ? b WHERE a.AREA_TYPE_ID=1 and a.area_type_id=B.AREA_TYPE_ID";
	public static final String WARD_PATWARI_NAME="select DISTINCT WARD_PATWARI_ID, WARD_PATWARI_NAME, H_WARD_PATWARI_NAME From IGRS_GUIDELINE_WARD_PATWARI where sub_area_type_id=? and tehsil_id=?";
	public static final String COLONY_NAME="SELECT COLONY_ID, COLONY_NAME, H_COLONY_NAME FROM IGRS_GUIDELINE_COLONY where ward_patwari_id=?";
	
	//added for FY wise District List
	public static final String DISTRICT_NAME_FY_WISE="select distinct district_id, guideline_id from IGRS_GUIDELINE_DOC_SEARCH_FY where fy=?";
	public static final String REG_TEHSIL_QUERY = "Select  DISTINCT A.TEHSIL_ID, A.TEHSIL_NAME from IGRS_TEHSIL_MASTER a, IGRS_GUIDELINE_DOC_SEARCH_FY b Where a.DISTRICT_ID=b.district_id AND a.TEHSIL_STATUS='A' and b.district_id=? and b.fy=? ORDER BY A.TEHSIL_ID, A.TEHSIL_NAME";

	public static final String REG_TEHSIL_QUERY_H = "Select  TEHSIL_ID, " + "H_TEHSIL_NAME from IGRS_TEHSIL_MASTER " + "Where DISTRICT_ID=? AND TEHSIL_STATUS='A' " + "ORDER BY TEHSIL_NAME ASC";
	
	//DOC SEARCH SUB AREA START
	public static final String DOC_SEARCH_SUB_AREA="select DISTINCT a.SUB_AREA_TYPE_ID, a.SUB_AREA_TYPE_NAME, a.H_SUB_AREA_TYPE_NAME from igrs_sub_area_type_master a, ";
	public static final String SUB_AREA_RURAL=" b, IGRS_GUIDELINE_DOC_SEARCH_FY C WHERE a.AREA_TYPE_ID=1 and a.area_type_id=B.AREA_TYPE_ID AND b.guideline_id=c.guideline_id and c.fy=? and a.area_type_id=b.area_type_id ORDER BY a.SUB_AREA_TYPE_NAME";
	public static final String SUB_AREA_URBAN=" b, IGRS_GUIDELINE_DOC_SEARCH_FY C where a.area_type_id=? and a.tehsil_id=b.tehsil_id and b.tehsil_id=? AND C.FY=? AND b.guideline_id=c.guideline_id AND a.sub_area_type_id=b.sub_area_type_id ORDER BY a.SUB_AREA_TYPE_NAME";
	//DOC SEARCH SUB AREA END
	//DOC SEARCH WARD START
	public static final String DOC_SEARCH_WARD_COMMON="select DISTINCT A.WARD_PATWARI_ID, A.WARD_PATWARI_NAME, A.H_WARD_PATWARI_NAME From igrs_ward_patwari_master a, ";
	public static final String WARD_REMAINING=" b, igrs_guideline_doc_search_fy c where a.SUBNAME=b.sub_area_type_id and b.guideline_id=c.guideline_id and c.fy=? AND b.tehsil_id=? AND b.sub_area_type_id=? AND a.ward_patwari_id=b.ward_patwari_id ORDER BY A.WARD_PATWARI_NAME";
	//DOC SEARCH WARD END

	//DOC SEARCH COLONY START
	public static final String DOC_SEARCH_COLONY_COMMON="SELECT DISTINCT a.COLONY_ID, a.COLONY_NAME, a.H_COLONY_NAME, a.colony_status FROM igrs_colony_master a, ";
	public static final String COLONY_REMAINING=" b, igrs_guideline_doc_search_fy c where b.colony_id=a.colony_id and b.guideline_id=c.guideline_id and c.fy=? AND b.ward_patwari_id=? ORDER BY a.COLONY_NAME";
	//DOC SEARCH COLONY END
	
	//DOC SEARCH TEHSIL START
	public static final String DOC_SEARCH_TEHSIL_COMMOM="select DISTINCT A.TEHSIL_ID, A.TEHSIL_NAME,A.H_TEHSIL_NAME from igrs_tehsil_master A, IGRS_GUIDELINE_DOC_SEARCH_FY B, ";
	public static final String TEHSIL_REMAINING=" C where B.district_id=? AND B.FY in (?) AND a.district_id=b.district_id AND c.guideline_id=b.guideline_id AND c.tehsil_id=a.tehsil_id ORDER BY A.TEHSIL_NAME";
	//DOC SEARCH TEHSIL END
	public static final String DOC_SEARCH_SELECT_REGID_OFFICE = "SELECT REG_TXN_ID FROM IGRS_REG_TXN_DETLS  WHERE  REGISTRATION_NUMBER = ";
	public static final String GET_FISCAL_YEAR_NAME="select FISCAL_YEAR from igrs_fiscal_year where fiscal_year_id=?";
	
}
