package com.wipro.igrs.clr.services;

public class CLRServicesSQL {

	public final static String CLR_PROPERTIES_ID = "Select A.PROPERTY_ID From Igrs_Reg_Proprty_Dtls a, IGRS_REG_TXN_DETLS b, IGRS_DEED_INSTRUMENT_MASTER c Where a.Reg_Txn_Id=? AND a.CLR_FLAG='Y' and a.reg_txn_id=b.reg_txn_id and B.INSTRUMENTS_ID=C.INSTRUMENT_ID and C.CLR_FLAG='Y'";
	public final static String CLR_PROP_DETAILS = "SELECT B.Deed_Type_Name, " + "  C.Instrument_Name, " + "  A.Registration_Number, " + "  to_char(A.Update_Date,'DD-MM-YYYY'), " + "  A.Registration_Office_Id, " + "  D.Property_Id, " + "  D1.DISTRICT_NAME, " + "  T1.TEHSIL_NAME, " + "  A1.AREA_TYPE_NAME, " + "  S1.SUB_AREA_TYPE_NAME, " + "  W1.WARD_PATWARI_NAME, " + "  C1.COLONY_NAME, " + "  c1.colony_id, " + "  D.Ri_Circle, " + "  E.Lgd_Code, " + "  G.Khasra_Id, " + "  G.Khasra_No, " + "  G.Distcode_Clr, " + "  G.Tehcode_Clr, " + "  G.KHASRA_AREA, " + "  G.TOTAL_SALEBLE_AREA, " + "  H.LANDOWNERID_DEPT_CLR, " + "  ofc.office_name, g.transaction_type " + "FROM Igrs_Reg_Txn_Detls a, " + "  Igrs_Deed_Type_Master b, " + "  Igrs_Deed_Instrument_Master C, " + "  Igrs_Reg_Proprty_Dtls D, " + "  Igrs_Colony_Master E, " + "  IGRS_REG_KHASRA_PROP_CLR G, " + "  IGRS_REG_KHASRA_PARTY_CLR H, " + "  IGRS_DISTRICT_MASTER D1, " + "  IGRS_TEHSIL_MASTER T1, " + "  IGRS_AREA_TYPE_MASTER A1, " + "  IGRS_SUB_AREA_TYPE_MASTER S1, " + "  IGRS_WARD_PATWARI_MASTER W1, " + "  IGRS_COLONY_MASTER C1, " + "  igrs_office_master ofc " + "WHERE A.REG_TXN_ID          =? " + "AND A.REG_TXN_ID            = D.REG_TXN_ID " + "AND D.Property_Id           =? " + "AND a.deed_id               = B.Deed_Type_Id " + "AND A.Instruments_Id        =C.Instrument_Id " + "AND D.Mohalla_Id            =E.Colony_Id " + "AND D.PROPERTY_ID           =G.PROPERTY_ID " + "AND G.KHASRA_ID             =H.KHASRA_ID " + "AND D.DISTRICT_ID           =D1.DISTRICT_ID " + "AND D.TEHSIL_ID             =T1.TEHSIL_ID " + "AND D.AREA_TYPE_ID          =A1.AREA_TYPE_ID " + "AND D.GOV_BODY_ID           =S1.SUB_AREA_TYPE_ID " + "AND D.WARD_ID               =W1.WARD_PATWARI_ID and D.PROPERTY_ID           =H.PROPERTY_ID " + "AND D.MOHALLA_ID            =C1.COLONY_ID " + "AND A.REGISTRATION_OFFICE_ID=ofc.office_id(+)";

	public final static String CLR_PARTY_DETAILS = "SELECT A.APPELLATE_TYPE_ID, " + "  G.APPELLATE_TYPE_NAME, " + "  A.PARTY_FIRST_NAME , " + "  A.PARTY_MIDDLE_NAME , " + "  A.PARTY_LAST_NAME , " + "  A.ORGANIZATION_NAME, " + "  A.AUTHRZD_PERSN_NAME, " + "  A.NAME_OF_OFFICIAL, " + "  A.DESG_OF_OFFICIAL, " + "  A.ADRS_OF_OFFICIAL, " + "  D.DISTRICT_NAME, " + "  (SELECT DISTRICT_NAME " + "  FROM IGRS_DISTRICT_MASTER " + "  WHERE DISTRICT_ID=A.AUTH_PER_DISTRICT_ID " + "  ) AUTH_PERSON_DIST, " + "  E.PARTY_TYPE_NAME, " + "  A.PHOTO_PROOF_ID, " + "  J.PHOTO_PROOF_TYPE_NAME, " + "  A.GUARDIAN_NAME, " + "  F.RELATION_TYPE_NAME, " + "  H.PROPERTY_ID, " + "  I.KHASRA_NO, " + "  I.KHASRA_ID, " + "  H.SHARES, " + "  (SELECT PARTY_FIRST_NAME " + "    ||' ' " + "    ||PARTY_MIDDLE_NAME " + "    ||' ' " + "    ||PARTY_LAST_NAME " + "  FROM IGRS_REG_TXN_PARTY_DETLS " + "  WHERE PARTY_TXN_ID=A.PARENT_ID " + "  ) POA_NAME_IND, " + "  (SELECT ORGANIZATION_NAME " + "    ||'/' " + "    ||AUTHRZD_PERSN_NAME " + "  FROM IGRS_REG_TXN_PARTY_DETLS " + "  WHERE PARTY_TXN_ID=A.PARENT_ID " + "  ) POA_NAME_ORG, " + "  (SELECT B1.PARTY_TYPE_NAME " + "  FROM IGRS_REG_TXN_PARTY_DETLS A1, " + "    IGRS_PARTY_TYPE_MASTER B1 " + "  WHERE A1.PARTY_TXN_ID=A.PARENT_ID " + "  AND A1.PARTY_TYPE_ID =B1.PARTY_TYPE_ID " + "  ) POA_TYPE, " + "  A.PARTY_ADDRESS, " + "  A.PARENT_ID, " + "  A.AUTH_PER_PARTY_ADDRESS, " + "  (SELECT A1.APPELLATE_TYPE_ID " + "  FROM IGRS_REG_TXN_PARTY_DETLS A1 " + "  WHERE A1.PARTY_TXN_ID=A.PARENT_ID " + "  ) POA_APP_TYPE, " + "  a.party_txn_id , " + "  a.RELATION_TYPE_ID, " + "  a.party_gender, " + "  a.mobile_number, " + "  a.category_id, " + "  a.email_id, " + "  a.district_id " + "FROM IGRS_REG_TXN_PARTY_DETLS A, " + "  IGRS_PARTY_TYPE_MASTER B, " + "  IGRS_DISTRICT_MASTER D, " + "  IGRS_PARTY_TYPE_MASTER E, " + "  IGRS_RELATION_TYPE_MASTER F, " + "  IGRS_APPELLATE_TYPE_MASTER G, " + "  IGRS_REG_PROP_SHARE_MAP_CLR H, " + "  IGRS_REG_KHASRA_PROP_CLR I, " + "  IGRS_PHOTOID_PROOF_TYPE_MASTER j " + "WHERE A.PARTY_TYPE_ID    =B.PARTY_TYPE_ID " + "AND A.REG_TXN_ID         =? " + "AND H.PROPERTY_ID        =? " + "AND A.DISTRICT_ID        =D.DISTRICT_ID(+) " + "AND A.PARTY_TYPE_ID      =E.PARTY_TYPE_ID " + "AND A.RELATION_TYPE_ID   =F.RELATION_TYPE_ID(+) " + "AND A.APPELLATE_TYPE_ID  =G.APPELLATE_TYPE_ID " + "AND A.PARTY_TXN_ID(+)    =H.PARTY_TXN_ID " + "AND H.REG_TXN_ID         =I.REG_TXN_ID " + "AND H.PROPERTY_ID        =I.PROPERTY_ID " + "AND H.KHASRA_NO          =I.KHASRA_NO " + "AND A.PHOTO_PROOF_TYPE_ID=J.PHOTO_PROOF_TYPE_ID(+)";
	public final static String INSERT_CLR_STATUS = "INSERT INTO IGRS_CLR_DATA_SHARE_STATUS (REG_TXN_ID, REGISTRATION_NUMBER, PROPERTY_ID, STATUS, CREATED_DATE) VALUES (?,(select REGISTRATION_NUMBER from IGRS_REG_TXN_DETLS where REG_TXN_ID   =?),?,?,SYSDATE)";
	public final static String INSERT_PROP_DATA = "INSERT " + "INTO IGRS_CLR_PROP_DATA_DETAIL " + "  ( " + "    DEED_TYPE_NAME, " + "    INSTRUMENT_TYPE_NAME, " + "    REGISTRATION_NUMBER, " + "    REGISTRATION_DATE, " + "    REGISTRATION_OFFICE_ID, " + "    PROPERTY_ID, " + "    DISTRICT_NAME, " + "    TEHSIL_NAME, " + "    AREA_TYPE_NAME, " + "    SUB_AREA_TYPE_NAME, " + "    WARD_NAME, " + "    COLONY_NAME, " + "    COLONY_ID, " + "    RI_CIRCLE, " + "    LGD_CODE, " + "    KHASRA_ID, " + "    KHASRA_NUMBER, " + "    CLR_DIST_ID, " + "    CLR_TEH_ID, " + "    KHASRA_AREA, " + "    SALEABLE_AREA, " + "    CLR_OWNER_ID, REGISTRATION_OFFICE_NAME,transaction_type, reg_txn_id " + "  ) " + "  VALUES " + "  ( " + "    ?, " + "    ?, " + "    ?, " + "    ?, " + "    ?, " + "    ?, " + "    ?, " + "    ?, " + "    ?, " + "    ?, " + "    ?, " + "    ?, " + "    ?, " + "    ?, " + "    ?, " + "    ?, " + "    ?, " + "    ?, " + "    ?, " + "    ?, " + "    ?, " + "    ?,?,?,? " + "  )";
	public final static String CHECK_CLR_DATA = "SELECT COUNT(1) FROM IGRS_CLR_DATA_SHARE_STATUS WHERE REG_TXN_ID=? AND PROPERTY_ID=?";
	public final static String INSERT_PARTY_DATA = "INSERT " + "INTO IGRS_CLR_PARTY_DETAIL " + "  ( " + "    APPELLATE_TYPE_ID, " + "    APPELLATE_TYPE_NAME, " + "    PARTY_FIRST_NAME, " + "    PARTY_MIDDLE_NAME, " + "    PARTY_LAST_NAME, " + "    PARTY_ADDRESS, " + "    ORG_NAME, " + "    AUTHRZD_PRSN_NAME, " + "    NAME_OF_OFFICIAL, " + "    DESG_OF_OFFICIAL, " + "    ADRS_OF_OFFICIAL, " + "    POA_NAME, " + "    POA_TYPE, " + "    MOBILE_NUMBER, " + "    DISTRICT, " + "    EMAIL_ID, " + "    CATEGORY, " + "    PARTY_TYPE, " + "    GUARDIAN_NAME, " + "    RELATION_TYPE, " + "    PROP_ID, " + "    KHASRA_NUMBER, " + "    KHASRA_ID, " + "    PARTY_SHARE, " + "    PHOTO_PROOF_TYPE, " + "    PHOTO_PROOF_ID, " + "    PARTY_TXN_ID, " + "    REG_TXN_ID, GENDER " + "  ) " + "  VALUES " + "  ( " + "    ?, " + "    ?, " + "    ?, " + "    ?, " + "    ?, " + "    ?, " + "    ?, " + "    ?, " + "    ?, " + "    ?, " + "    ?, " + "    ?, " + "    ?, " + "    ?, " + "    ?, " + "    ?, " + "    ?, " + "    ?, " + "    ?, " + "    ?, " + "    ?, " + "    ?, " + "    ?, " + "    ?, " + "    ?, " + "    ?, " + "    ?, " + "    ?,? " + "  )";
	public final static String CHECK_CLR_PROP_DATA = "SELECT COUNT(1) FROM IGRS_CLR_PROP_DATA_DETAIL WHERE REG_TXN_ID=? AND PROPERTY_ID=?";
	public final static String CHECK_CLR_PARTY_DATA = "SELECT COUNT(1) FROM IGRS_CLR_PARTY_DETAIL WHERE REG_TXN_ID=? AND PROP_ID=?";
	public final static String DELETE_CLR_PROP_DATA = "DELETE FROM IGRS_CLR_PROP_DATA_DETAIL WHERE REG_TXN_ID=? AND PROPERTY_ID=?";;
	public final static String DELETE_CLR_PARTY_DATA = "DELETE FROM IGRS_CLR_PARTY_DETAIL WHERE REG_TXN_ID=? AND PROP_ID=?";
	public final static String UPDATE_CLR_SHARE_STATUS = "UPDATE IGRS_CLR_DATA_SHARE_STATUS SET STATUS=1 WHERE REG_TXN_ID=? AND PROPERTY_ID=?";
	// below are for pushing data to CLR table
	public final static String CHECK_BUYER_STATUS = "SELECT a.APPELLATE_TYPE_ID,a.PARTY_TYPE_ID, a.PARENT_ID, B.CLAIMANT_FLAG, B.PARTY_TYPE_NAME FROM IGRS_REG_TXN_PARTY_DETLS a, IGRS_PARTY_TYPE_MASTER b WHERE a.PARTY_TXN_ID in (?) and a.PARTY_TYPE_ID=b.PARTY_TYPE_ID";
	public final static String INSERT_DATA_TO_CLR = "INSERT " + "INTO GIRD_MAPIT.REGISTRATION_SAMPADA@WEBGIS_CLR " + "  ( " + "    DISTRICT_ID, " + "    tehsil_id, " + "    LGD_CODE, " + "    KHASRAID, " + "    REGISTRATION_NUMBER, " + "    REGISTRATION_DATE, " + "    TYPE_OF_REGISTRATION, " + "    PARTY_TRANSACTING_FAVOR_WHOM, " + "    TRANSACTING_AREA, " + "    PUSH_DATE, " + "    READBY_WEBGIS,SAMPADA_PROPERTYID,PARTY_TYPE,TRANSACTION_TYPE,PARTY_FIRST_NAME,PARTY_MIDDLE_NAME,PARTY_LAST_NAME,ORGANIZATION_NAME,AUTHRZD_PERSN_NAME,NAME_OF_OFFICIAL,DESG_OF_OFFICIAL,RELATION_TYPE_ID , PARTY_ADDRESS,ADRS_OF_OFFICIAL ,ADDRESS_DISTRICT_ID,MOBILE_NUMBER,PARTY_GENDER,CATEGORY_ID,OWNER_SHARE,IS_CYBER, GUARDIAN_NAME   " + "  )" + " VALUES " + "  ( " + "    ?, " + "    ?, " + "    ?, " + "    ?,?, " + "    to_date(?,'dd-mm-yyyy'), " + "    ?, " + "    ?, " + "    ?, " + "    sysdate, " + "    ?,?,?,? ,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?" + "  )";
	public final static String CHK_DATA_AT_CLR = "SELECT count(1) FROM GIRD_MAPIT.REGISTRATION_SAMPADA@WEBGIS_CLR where REGISTRATION_NUMBER=(Select registration_number From Igrs_Reg_Txn_Detls WHERE  Reg_Txn_Id=?)";
	public final static String SHARE_CHK = "select shares from IGRS_REG_PROP_SHARE_MAP_CLR  WHERE PROPERTY_ID=? and KHASRA_NO=? and PARTY_TXN_ID=?";
	public final static String FETCH_DATA_FOR_CLR = "SELECT B.Deed_Type_Name, " + "  C.Instrument_Name, " + "  A.Registration_Number, " + "  TO_CHAR(A.Update_Date,'DD-MM-YYYY'), " + "  A.Registration_Office_Id, " + "  D.Property_Id, " + "  D1.DISTRICT_NAME, " + "  T1.TEHSIL_NAME, " + "  A1.AREA_TYPE_NAME, " + "  S1.SUB_AREA_TYPE_NAME, " + "  W1.WARD_PATWARI_NAME, " + "  C1.COLONY_NAME, " + "  c1.colony_id, " + "  D.Ri_Circle, " + "  E.Lgd_Code, " + "  G.Khasra_Id, " + "  G.Khasra_No, " + "  G.Distcode_Clr, " + "  G.Tehcode_Clr, " + "  G.KHASRA_AREA, " + "  G.TOTAL_SALEBLE_AREA, " + "  ofc.office_name, g.transaction_type " + "FROM Igrs_Reg_Txn_Detls a, " + "  Igrs_Deed_Type_Master b, " + "  Igrs_Deed_Instrument_Master C, " + "  Igrs_Reg_Proprty_Dtls D, " + "  Igrs_Colid_Lgdcode_Mapping E, " + "  IGRS_REG_KHASRA_PROP_CLR G, " + "  IGRS_DISTRICT_MASTER D1, " + "  IGRS_TEHSIL_MASTER T1, " + "  IGRS_AREA_TYPE_MASTER A1, " + "  IGRS_SUB_AREA_TYPE_MASTER S1, " + "  IGRS_WARD_PATWARI_MASTER W1, " + "  IGRS_COLONY_MASTER C1, " + "  IGRS_OFFICE_MASTER OFC " + "WHERE A.REG_TXN_ID          =? " + "AND A.REG_TXN_ID            = D.REG_TXN_ID " + "AND D.Property_Id           =? " + "AND a.deed_id               = B.Deed_Type_Id " + "AND A.Instruments_Id        =C.Instrument_Id " + "AND D.Mohalla_Id            =E.Colony_Id " + "AND D.PROPERTY_ID           =G.PROPERTY_ID " + "AND D.DISTRICT_ID           =D1.DISTRICT_ID " + "AND D.TEHSIL_ID             =T1.TEHSIL_ID " + "AND D.AREA_TYPE_ID          =A1.AREA_TYPE_ID " + "AND D.GOV_BODY_ID           =S1.SUB_AREA_TYPE_ID " + "AND D.WARD_ID               =W1.WARD_PATWARI_ID " + "AND D.MOHALLA_ID            =C1.COLONY_ID " + "AND A.REGISTRATION_OFFICE_ID=OFC.OFFICE_ID(+) ";
	//for sign merger
	public final static String GET_FORMA1_PATH="Select form_via From Igrs_Reg_Txn_Detls Where Reg_Txn_Id=?";
	public final static String GET_FORMA2_PATH="Select form_vib From Igrs_Reg_Txn_Detls Where Reg_Txn_Id=?";
	
	public final static String GET_RCMS_CASE_DETAIL ="Select distinct nvl(APPLICATIONNUMBER,'NA'), NVL(CASE_NUMBER,'NA') from Igrs_Rcms_Response_Dtls where reg_txn_id=?";
	public final static String CHECK_IF_CYBER="select nvl(is_cyber,'N') from Igrs_Rcms_Response_Dtls where reg_txn_id=?";
}
