package com.wipro.igrs.eToken.sql;

public class ETokenSQL {

	public static final String  INSERT_ETOKEN_INFO = "INSERT INTO IGRS_ETOKEN_INFO (ETOKENNO,STATUS,FLAG,CREATEDDATE,CREATEDBY,UPDATEDDATE,UPDATEDBY)" +
	" VALUES (?,?,?,sysdate,?,'','')";//added by tanu

	public static final String IGRS_RESISSUE_ETOKEN ="SELECT reg_id, "+
	" ETOKENNO,COUNTER_TYPE,NO_OF_PERSONS,PERSON_TYPE, "+
	" TO_CHAR(created_date,'dd/mm/yyyy'), (select OFFICE_NAME from igrs_office_master where office_id=sro_id )"+
	" FROM IGRS_ETOKEN_MAKER_DETAILS ch WHERE reg_id=? AND flag    = 'A'"+
	" UNION ALL "+
	" SELECT reg_id,  ETOKENNO, COUNTER_TYPE, NO_OF_PERSONS,PERSON_TYPE,"+
	" TO_CHAR(created_date,'dd/mm/yyyy'), (select OFFICE_NAME from igrs_office_master where office_id=sro_id )"+
	" FROM IGRS_ETOKEN_CHECKER_DETAILS "+
	" WHERE reg_id=?"+
	" AND flag    = 'A'";

	public static final String GET_DISTRICT_LIST = "SELECT DISTRICT_ID, DISTRICT_NAME FROM " +
	"IGRS_DISTRICT_MASTER WHERE DISTRICT_STATUS= 'A' and  state_id=1  order by district_name";

	public static final String GET_DISTRICT_LIST_HINDI = "SELECT DISTRICT_ID, H_DISTRICT_NAME FROM " +
	"IGRS_DISTRICT_MASTER WHERE DISTRICT_STATUS= 'A' and  state_id=1  order by district_name";
	
	public static final String GET_ETOKEN_DISTRICT_LIST_Hindi = "select DISTRICT_ID,H_DISTRICT_NAME FROM IGRS_DISTRICT_MASTER WHERE DISTRICT_STATUS= 'A' and  state_id=1 " +
	"and district_id in ( select district_id_old from igrs_office_master where etoken_flag='Y' and office_id = ?)";


	public static final String GET_SRO_LIST = "SELECT OFFICE_ID, OFFICE_NAME FROM IGRS_OFFICE_MASTER WHERE " +
	"OFFICE_TYPE_ID = '3' AND OFFICE_STATUS = 'A' AND DISTRICT_ID =";

	public static final String GET_SRO_LIST_HINDI = "SELECT OFFICE_ID, H_OFFICE_NAME FROM IGRS_OFFICE_MASTER WHERE " +
	"OFFICE_TYPE_ID = '3' AND OFFICE_STATUS = 'A' AND DISTRICT_ID =";


	public static final String SAVE_MAKER_COUNTER_DETLS = "INSERT INTO IGRS_MAKER_COUNTER_SRO_MASTER(COUNTER_ID,DISTRICT_ID," +
	"SRO_ID,COUNTER_NAME,COUNTER_DESC,STATUS,CREATED_BY,CREATED_DATE) " +
	"VALUES(?,?,?,?,?,'A',?,to_date(?,'dd/mm/yyyy'))";

	public static final String SAVE_CHECKER_COUNTER_DETLS = "INSERT INTO IGRS_CHCKER_COUNTER_SRO_MASTER(COUNTER_ID,DISTRICT_ID," +
	"SRO_ID,COUNTER_NAME,COUNTER_DESC,STATUS,CREATED_BY,CREATED_DATE) " +
	"VALUES(?,?,?,?,?,'A',?,to_date(?,'dd/mm/yyyy'))";

	public static final String UNIQUE_COUNTER_NAME_CHECK_MAKER = "SELECT COUNT(*) FROM " +
	"IGRS_MAKER_COUNTER_SRO_MASTER WHERE UPPER(COUNTER_NAME)=UPPER(?)";

	public static final String UNIQUE_COUNTER_NAME_CHECK_CHECKER = "SELECT COUNT(*) FROM " +
	"IGRS_CHCKER_COUNTER_SRO_MASTER WHERE UPPER(COUNTER_NAME)=UPPER(?)";

	public static final String GET_MAKER_COUNTER_DETAILS = "SELECT COUNTER_ID,COUNTER_NAME,COUNTER_DESC,STATUS FROM " +
	"IGRS_MAKER_COUNTER_SRO_MASTER WHERE DISTRICT_ID = ? AND UPPER(SRO_ID) = UPPER(?)  order by STATUS";

	public static final String GET_CHECKER_COUNTER_DETAILS = "SELECT COUNTER_ID,COUNTER_NAME,COUNTER_DESC,STATUS FROM " +
	"IGRS_CHCKER_COUNTER_SRO_MASTER WHERE DISTRICT_ID = ? AND UPPER(SRO_ID) = UPPER(?)  order by STATUS";

	public static final String GET_COMPLETE_COUNTER_DETLS_MAKER = "SELECT COUNTER_NAME,COUNTER_DESC FROM " +
	"IGRS_MAKER_COUNTER_SRO_MASTER WHERE COUNTER_ID =";

	public static final String GET_COMPLETE_COUNTER_DETLS_CHECKER = "SELECT COUNTER_NAME,COUNTER_DESC FROM " +
	"IGRS_CHCKER_COUNTER_SRO_MASTER WHERE COUNTER_ID =";

	public static final String UPDATE_COUNTER_DETLS_MAKER = "UPDATE IGRS_MAKER_COUNTER_SRO_MASTER SET " +
	"DISTRICT_ID = ?, SRO_ID = ?,COUNTER_NAME = ?,COUNTER_DESC = ?,STATUS = ?," +
	"UPDATE_BY = ?,UPDATE_DATE =to_date(?,'dd/mm/yyyy') WHERE COUNTER_ID = ?";

	public static final String UPDATE_COUNTER_DETLS_CHECKER = "UPDATE IGRS_CHCKER_COUNTER_SRO_MASTER SET " +
	"DISTRICT_ID = ?, SRO_ID = ?,COUNTER_NAME = ?,COUNTER_DESC = ?,STATUS = ?," +
	"UPDATE_BY = ?,UPDATE_DATE =to_date(?,'dd/mm/yyyy') WHERE COUNTER_ID = ?";

	public static final String UNIQUE_CONSTRAINT_FOR_EDIT_MAKER = "SELECT COUNT(*) FROM IGRS_MAKER_COUNTER_SRO_MASTER " +
	"WHERE UPPER(COUNTER_NAME)=UPPER(?) and counter_id not in (?)";

	public static final String UNIQUE_CONSTRAINT_FOR_EDIT_CHECKER = "SELECT COUNT(*) FROM IGRS_CHCKER_COUNTER_SRO_MASTER " +
	"WHERE UPPER(COUNTER_NAME)=UPPER(?) and counter_id not in (?)";

	public static final String GET_OFFICE_DISTRICT_DETLS = "SELECT o.OFFICE_NAME, d.DISTRICT_NAME FROM " +
	"IGRS_OFFICE_MASTER o, IGRS_DISTRICT_MASTER d WHERE " +
	"o.DISTRICT_ID = d.DISTRICT_ID AND o.OFFICE_ID = ?";


	public static final String GET_OFFICE_DISTRICT_DETLS_HINDI = "SELECT o.H_OFFICE_NAME, d.H_DISTRICT_NAME FROM " +
	"IGRS_OFFICE_MASTER o, IGRS_DISTRICT_MASTER d WHERE " +
	"o.DISTRICT_ID = d.DISTRICT_ID AND o.OFFICE_ID = ?";

	public static final String GET_LOCK_DETAILS = "select m.office_name,m.office_id,h.district_id ,h.district_name from igrs_office_master m ,igrs_district_master h where m.district_id=h.district_id and m.office_id=?";


	public static final String UPDATE_EOTKEN = "update IGRS_ETOKEN_MAKER_DETAILS set SRO_ID=?,COUNTER_NO=? where REG_ID=?";

	public static final String GET_REG_DETAILS = "select CREATED_BY from IGRS_REG_TXN_DETLS where REG_TXN_ID=?";

	public static final String GET_ETOKEN_REPORT_DETAILS = "SELECT ETOKENNO,FLAG,COUNTER_TYPE,trunc(CREATED_DATE),REG_ID"+
	" FROM igrs_etoken_maker_details  WHERE SRO_ID=? AND trunc(CREATED_DATE) between TO_DATE(?,'DD-MM-YY') and TO_DATE(?,'DD-MM-YY') union "+
	" SELECT ETOKENNO,FLAG,COUNTER_TYPE,trunc(CREATED_DATE),REG_ID "+
	"FROM  igrs_etoken_checker_details  where sro_id  =? AND trunc(CREATED_DATE) between TO_DATE(?,'DD-MM-YY') and TO_DATE(?,'DD-MM-YY')";


	public static final String GET_ETOKEN_REPORT_MAKER = "SELECT ETOKENNO,FLAG,COUNTER_TYPE,trunc(CREATED_DATE),REG_ID "+
	" FROM igrs_etoken_maker_details  WHERE SRO_ID=? AND trunc(CREATED_DATE) between TO_DATE(?,'DD-MM-YY') and TO_DATE(?,'DD-MM-YY')";


	public static final String GET_ETOKEN_REPORT_CHECKER = "SELECT ETOKENNO,FLAG,COUNTER_TYPE,trunc(CREATED_DATE),REG_ID "+
	" FROM  igrs_etoken_checker_details  where sro_id  =? AND trunc(CREATED_DATE) between TO_DATE(?,'DD-MM-YY') and TO_DATE(?,'DD-MM-YY')";


	public static final String GET_SRO_COUNTERS_MAKER = "SELECT COUNTER_ID,COUNTER_NAME FROM " +
	"IGRS_MAKER_COUNTER_SRO_MASTER WHERE SRO_ID = ? AND STATUS = 'A' AND" +
	" COUNTER_ID NOT IN(SELECT COUNTER_ID FROM IGRS_MAKER_COUNTER_MAPPING WHERE STATUS = 'A') ORDER BY COUNTER_ID";

	public static final String GET_MAPPED_MAKERS_LIST = " SELECT mkc.MAPPING_ID,mkc.USER_ID,us.FIRST_NAME, cs.COUNTER_NAME FROM " +
	"IGRS_MAKER_COUNTER_MAPPING mkc,IGRS_USER_REG_DETAILS us,IGRS_MAKER_COUNTER_SRO_MASTER cs " +
	"WHERE mkc.COUNTER_ID = cs.COUNTER_ID AND " +
	"mkc.USER_ID = us.USER_ID AND mkc.SRO_ID = ? AND mkc.STATUS = 'A'";

	public static final String INSERT_MAPPED_MAKERS_LIST = "INSERT INTO IGRS_MAKER_COUNTER_MAPPING(MAPPING_ID,USER_ID,COUNTER_ID,SRO_ID,STATUS,CREATED_BY,CREATED_DATE,MAKER_AVAILABLE_STATUS) " +
	"VALUES(IGRS_MAKER_COUNTER_MAPPING_SEQ.NEXTVAL,?,?,?,'A',?,to_date(?,'dd/mm/yyyy'),'N')";

	public static final String UPDATE_MAPPED_MAKER_DETLS = "UPDATE IGRS_MAKER_COUNTER_MAPPING SET STATUS = 'D'," +
	" UPDATE_BY = ? , UPDATE_DATE = to_date(?,'dd/mm/yyyy') WHERE MAPPING_ID = ? ";

	public static final String GET_MAKERS_MAPPED_TO_SRO_OLD = "SELECT DISTINCT UG.USER_ID, um.FIRST_NAME FROM  " +
	"IGRS_ROLE_MASTER RM, IGRS_ROLE_GROUP_MASTER GM,IGRS_RGROUP_ROLE_MAPPING RG ," +
	"IGRS_ROLE_OFFICE_MAPPING offrol, IGRS_USER_ROLE_GROUP_MAPPING UG,IGRS_USER_REG_DETAILS um WHERE " +
	"offrol.ROLE_OFFICE_MAP_ID=RG.ROLE_OFFICE_MAP_ID and " +
	"offrol.ROLE_ID=rm.ROLE_ID AND RM.ROLE_STATUS = 'A'  AND " +
	"GM.ROLE_GROUP_STATUS = 'A' AND  UG.ROLE_GROUP_ID = RG.ROLE_GROUP_ID AND " +
	"UG.USER_ID = UM.USER_ID and offrol.OFFICE_ID = ? and rm.ROLE_ID = 'RL1356609581406'" +
	" and UG.USER_ID NOT IN (SELECT USER_ID FROM IGRS_MAKER_COUNTER_MAPPING WHERE STATUS = 'A')";

	//Added By Mohit Soni
	public static final String GET_MAKERS_MAPPED_TO_SRO="SELECT  a.user_id,j.first_name"
		+" FROM IGRS_USER_ROLE_GROUP_MAPPING a,"
		+"  IGRS_ROLE_FN_ACTIVITY_MAPPING b,"
		+"  IGRS_RGROUP_ROLE_MAPPING d,"
		+"  IGRS_ROLE_OFFICE_MAPPING e,"
		+"  IGRS_OFFICE_MASTER o,"
		+"  IGRS_USER_REG_DETAILS j"
		+" WHERE a.ROLE_GROUP_ID=d.ROLE_GROUP_ID"
		+" AND  e.ROLE_OFFICE_MAP_ID = d.ROLE_OFFICE_MAP_ID"
		+" AND j.user_id=a.user_id"
		+" AND o.office_id= ?"
		+" AND e.office_id = o.office_id"
		+" AND  e.ROLE_ID = b.ROLE_ID"
		+" AND b.ACTIVITY_ID='ACT_232' " +
		" AND a.user_id NOT IN" +
		"(SELECT distinct USER_ID FROM IGRS_CHECKER_COUNTER_MAPPING WHERE STATUS = 'A' union  SELECT USER_ID FROM IGRS_MAKER_COUNTER_MAPPING WHERE STATUS = 'A')";


	public static final String GET_SRO_COUNTERS_CHECKER = "SELECT COUNTER_ID,COUNTER_NAME FROM " +
	"IGRS_CHCKER_COUNTER_SRO_MASTER WHERE SRO_ID = ? AND STATUS = 'A' AND" +
	" COUNTER_ID NOT IN(SELECT COUNTER_ID FROM IGRS_CHECKER_COUNTER_MAPPING WHERE STATUS = 'A') ORDER BY COUNTER_ID";

	public static final String GET_MAPPED_CHECKERS_LIST = " SELECT mkc.MAPPING_ID, mkc.USER_ID, us.FIRST_NAME, cs.COUNTER_NAME FROM " +
	"IGRS_CHECKER_COUNTER_MAPPING mkc,IGRS_USER_REG_DETAILS us,IGRS_CHCKER_COUNTER_SRO_MASTER cs " +
	"WHERE mkc.COUNTER_ID = cs.COUNTER_ID AND " +
	"mkc.USER_ID = us.USER_ID AND mkc.SRO_ID = ? AND mkc.STATUS = 'A'";

	public static final String INSERT_MAPPED_CHECKERS_LIST = "INSERT INTO IGRS_CHECKER_COUNTER_MAPPING(MAPPING_ID,USER_ID,COUNTER_ID,SRO_ID,STATUS,CREATED_BY,CREATED_DATE,CHECKER_AVAILABLE_STATUS) " +
	"VALUES(IGRS_CHKER_COUNTER_MAPPING_SEQ.NEXTVAL,?,?,?,'A',?,to_date(?,'dd/mm/yyyy'),'N')";

	public static final String UPDATE_MAPPED_CHECKERS_DETLS = "UPDATE IGRS_CHECKER_COUNTER_MAPPING SET STATUS = 'D'," +
	" UPDATE_BY = ? , UPDATE_DATE = to_date(?,'dd/mm/yyyy') WHERE MAPPING_ID = ? ";

	public static final String GET_CHECKERS_MAPPED_TO_SRO_OLD = "SELECT DISTINCT UG.USER_ID, um.FIRST_NAME FROM  " +
	"IGRS_ROLE_MASTER RM, IGRS_ROLE_GROUP_MASTER GM,IGRS_RGROUP_ROLE_MAPPING RG ," +
	"IGRS_ROLE_OFFICE_MAPPING offrol, IGRS_USER_ROLE_GROUP_MAPPING UG,IGRS_USER_REG_DETAILS um WHERE " +
	"offrol.ROLE_OFFICE_MAP_ID=RG.ROLE_OFFICE_MAP_ID and " +
	"offrol.ROLE_ID=rm.ROLE_ID AND RM.ROLE_STATUS = 'A'  AND " +
	"GM.ROLE_GROUP_STATUS = 'A' AND  UG.ROLE_GROUP_ID = RG.ROLE_GROUP_ID AND " +
	"UG.USER_ID = UM.USER_ID and offrol.OFFICE_ID = ? and rm.ROLE_ID = 'RL1356671129765'" +
	" and UG.USER_ID NOT IN (SELECT USER_ID FROM IGRS_CHECKER_COUNTER_MAPPING WHERE STATUS = 'A')";

	//Added By Mohit Soni
	public static final String GET_CHECKERS_MAPPED_TO_SRO="SELECT  a.user_id,j.first_name"
		+" FROM IGRS_USER_ROLE_GROUP_MAPPING a,"
		+"  IGRS_ROLE_FN_ACTIVITY_MAPPING b,"
		+"  IGRS_RGROUP_ROLE_MAPPING d,"
		+"  IGRS_ROLE_OFFICE_MAPPING e,"
		+"  IGRS_OFFICE_MASTER o,"
		+"  IGRS_USER_REG_DETAILS j"
		+" WHERE a.ROLE_GROUP_ID=d.ROLE_GROUP_ID"
		+" AND  e.ROLE_OFFICE_MAP_ID = d.ROLE_OFFICE_MAP_ID"
		+" AND j.user_id=a.user_id"
		+" AND o.office_id= ?"
		+" AND e.office_id = o.office_id"
		+" AND  e.ROLE_ID = b.ROLE_ID"
		+" AND b.ACTIVITY_ID='ACT_233' " +
		" AND a.user_id NOT IN" +
		"(SELECT distinct USER_ID FROM IGRS_CHECKER_COUNTER_MAPPING WHERE STATUS = 'A' union  SELECT USER_ID FROM IGRS_MAKER_COUNTER_MAPPING WHERE STATUS = 'A')";

	public static final String GET_MAKER_COUNTER_ACTIVE_OFFICE  = "SELECT counter_id"
		+" FROM IGRS_MAKER_COUNTER_SRO_MASTER"
		+" WHERE sro_id=?"
		+" AND rownum  <?"
		+" ORDER BY counter_id";

	public static final String GET_ETOKEN_NUMBER = "select IGRS_ETOKEN_DETAILS_SEQUENCE.nextval from dual";
	public static final String GET_ETOKEN_NUMBER_OFFICE = "select MAX(cnt) from (select (TO_NUMBER(TRIM(ETOKENNO)))as cnt from igrs_etoken_maker_details where  sro_id=? union all "
		+" select (TO_NUMBER(TRIM(ETOKENNO))) as cnt from igrs_etoken_checker_details where  sro_id=?)" ;



	//
	public static final String GET_AVAILABLE_MAKERS_LIST = "SELECT MP.MAPPING_ID,MP.USER_ID,MP.COUNTER_ID,MU.FIRST_NAME, MC.COUNTER_NAME,MP.MAKER_AVAILABLE_STATUS " +
	"FROM IGRS_MAKER_COUNTER_MAPPING MP,IGRS_MAKER_COUNTER_SRO_MASTER MC,IGRS_USER_REG_DETAILS MU " +
	"WHERE MP.SRO_ID = ? AND MP.STATUS = 'A' AND" +
	" MP.USER_ID = MU.USER_ID AND MP.COUNTER_ID = MC.COUNTER_ID ";

	public static final String GET_AVAILABLE_CHECKERS_LIST = "SELECT MP.MAPPING_ID,MP.USER_ID,MP.COUNTER_ID,MU.FIRST_NAME, MC.COUNTER_NAME,MP.CHECKER_AVAILABLE_STATUS " +
	"FROM IGRS_CHECKER_COUNTER_MAPPING MP,IGRS_CHCKER_COUNTER_SRO_MASTER MC,IGRS_USER_REG_DETAILS MU " +
	"WHERE MP.SRO_ID = ? AND MP.STATUS = 'A' AND" +
	" MP.USER_ID = MU.USER_ID AND MP.COUNTER_ID = MC.COUNTER_ID ";

	public static final String UPDATE_MAKER_AVAILABLITY_STATUS = "UPDATE IGRS_MAKER_COUNTER_MAPPING " +
	"SET MAKER_AVAILABLE_STATUS = ? WHERE MAPPING_ID =?";

	public static final String UPDATE_CHECKER_AVAILABLITY_STATUS = "UPDATE IGRS_CHECKER_COUNTER_MAPPING " +
	"SET CHECKER_AVAILABLE_STATUS = ? WHERE MAPPING_ID =?";


	//****************************************************ADDED BY ROOPAM***************************************************************

	public static final String CHECK_REG_INIT_ID = "SELECT A.REG_TXN_ID, A.REGISTRATION_TXN_STATUS, TO_CHAR(B.SLOT_DATE,'dd/MM/yyyy'),   to_char(C.TIME_FROM,'hh:mi AM'),to_char(C.TIME_TO,'hh:mi AM') FROM IGRS_REG_TXN_DETLS A,IGRS_REG_SLOT_BOOK_TXN_DTLS B,IGRS_REG_SLOT_MASTER C "+
	"WHERE B.SLOT_ID=C.SLOT_ID  AND B.OFFICE_ID=? AND to_char(A.REG_TXN_ID)=B.REG_TXN_ID AND A.REG_TXN_ID=?";
	
	public static final String CHECK_REG_INIT_ID_WILL = "SELECT A.REG_TXN_ID, " +
"  A.REGISTRATION_TXN_STATUS, " +
"  TO_CHAR(B.SLOT_DATE,'dd/MM/yyyy') " +
"FROM IGRS_REG_TXN_DETLS A, " +
"  IGRS_REG_SLOT_BOOK_TXN_DTLS B " +
"WHERE B.OFFICE_ID        =? " +
"AND TO_CHAR(A.REG_TXN_ID)=B.REG_TXN_ID " +
"AND A.REG_TXN_ID         =?";

	public static final String CHECK_DEED_ID = "SELECT A.REG_TXN_ID, A.REGISTRATION_TXN_STATUS ,A.DEED_ID,B.SLOT_ID,TO_CHAR(A.CREATED_DATE,'dd/MM/yyyy') FROM IGRS_REG_TXN_DETLS A,IGRS_REG_SLOT_BOOK_TXN_DTLS B WHERE " +
	"TO_CHAR(A.REG_TXN_ID)=B.REG_TXN_ID AND B.OFFICE_ID=?  AND  A.REG_TXN_ID=?";

	public static final String CHECK_DEED_ID_forRegtxnID = "SELECT DEED_ID FROM IGRS_REG_TXN_DETLS WHERE REG_TXN_ID=?" ;

	//------------------Added By Mohit Soni--------------------------------------------------------------------------------------------------//

	public static final String INSERT_MAKER_ETOKEN_DETAILS = "insert into IGRS_ETOKEN_MAKER_DETAILS  (ETOKENNO,COUNTER_TYPE,NO_OF_PERSONS,PERSON_TYPE,CREATED_DATE,CREATED_BY,REG_ID,FLAG,REG_STATUS,SRO_ID) values(?,?,?,?,sysdate,?,?,'A',?,?)";

	public static final String INSERT_CHECKER_ETOKEN_DETAILS = "insert into IGRS_ETOKEN_CHECKER_DETAILS  (ETOKENNO,COUNTER_TYPE,NO_OF_PERSONS,PERSON_TYPE,CREATED_DATE,CREATED_BY,REG_ID,FLAG,REG_STATUS,SRO_ID) values(?,?,?,?,sysdate,?,?,'A',?,?)";

	public static final String MOVE_TO_CHECKER = "Update IGRS_ETOKEN_MAKER_DETAILS set FLAG='D',reg_status=? where reg_status=10 and FLAG='A' and reg_id = ? ";

	//public static final String GET_ACTIVE_MAKER_COUNTERS  = "Select COUNTER_ID,COUNTER_NAME from IGRS_MAKER_COUNTER_SRO_MASTER where SRO_ID=? and STATUS='A'";
	public static final String GET_ACTIVE_MAKER_COUNTERS  = "SELECT A.COUNTER_ID ,B.COUNTER_NAME FROM  IGRS_COUNTER_ATTENDENCE_MASTER A,IGRS_ET_OFFICE_COUNTER_MAPPING B " +
	"WHERE A.IS_ACTIVE='A' AND TRUNC(A.CREATED_DATE) = TRUNC(SYSDATE) AND A.COUNTER_ID=B.MAPPING_ID AND UPPER(B.COUNTER_TYPE)=UPPER('MAKER') AND A.SRO_ID=?";

	//public static final String GET_ACTIVE_CHECKER_COUNTERS  = "Select COUNTER_ID,COUNTER_NAME from IGRS_CHCKER_COUNTER_SRO_MASTER where SRO_ID=? and STATUS='A'";

	public static final String GET_ACTIVE_CHECKER_COUNTERS  ="SELECT A.COUNTER_ID ,B.COUNTER_NAME FROM  IGRS_COUNTER_ATTENDENCE_MASTER A," +
	"IGRS_ET_OFFICE_COUNTER_MAPPING B WHERE A.IS_ACTIVE='A' AND TRUNC(A.CREATED_DATE) = TRUNC(SYSDATE) " +
	"AND A.COUNTER_ID=B.MAPPING_ID AND UPPER(B.COUNTER_TYPE)=UPPER('CHECKER') AND A.SRO_ID=?";

	public static final String GET_REG_STATUS_ETOKEN_CHECK_M = "SELECT reg.REG_TXN_ID,"+
	" reg.REGISTRATION_TXN_STATUS,"+
	" mkr.sro_id,mkr.PERSON_TYPE"+
	" FROM IGRS_REG_TXN_DETLS reg,"+
	"  IGRS_ETOKEN_MAKER_DETAILS mkr "+
	" WHERE reg.reg_txn_id=mkr.reg_id"+
	" AND mkr.flag    ='A'"+
	" AND reg.REG_TXN_ID=?";


	public static final String GET_REG_COUNTER_NO = "Select COUNTER_NO from IGRS_ETOKEN_MAKER_DETAILS where REG_ID=? and created_date in (select max(created_date) from IGRS_ETOKEN_MAKER_DETAILS where REG_ID=?)" ;
	public static final String GET_REG_COUNTER_NAME = "SELECT COUNTER_NAME FROM IGRS_ET_OFFICE_COUNTER_MAPPING WHERE MAPPING_ID=?" ;

	public static final String GET_REG_STATUS_ETOKEN_CHECK_C = " SELECT reg.REG_TXN_ID,"+
	" reg.REGISTRATION_TXN_STATUS,"+
	"  mkr.sro_id,mkr.PERSON_TYPE"+
	" FROM IGRS_REG_TXN_DETLS reg,"+
	" IGRS_ETOKEN_CHECKER_DETAILS mkr"+
	" WHERE reg.reg_txn_id=mkr.reg_id"+
	" AND mkr.flag ='A'"+
	" AND reg.REG_TXN_ID=?";


	public static final String UPDATE_OFFICE_MASTER = "UPDATE IGRS_OFFICE_MASTER SET OFFICE_IP_ADDRESS = ? WHERE office_id = ?";

	public static final String GET_OFFICE_IP = "SELECT OFFICE_IP_ADDRESS from IGRS_OFFICE_MASTER where OFFICE_ID=?";

	public static final String UPDATE_MAKER_TABLE = "update IGRS_ETOKEN_MAKER_DETAILS set FLAG='D',reg_status=? where reg_status = 10 and FLAG='A' and reg_id = ?";


	public static final String UPDATE_CHECKER_TABLE = "update IGRS_ETOKEN_CHECKER_DETAILS set FLAG='D',reg_status=? where reg_status = 13 and FLAG='A' and reg_id = ?";
	public static final String UPDATE_CHECKER_TABLE_get = "select distinct ab.etokenno from IGRS_ETOKEN_MAKER_DETAILS ab where ab.reg_id=? union "+
	" select bc.etokenno from IGRS_ETOKEN_CHECKER_DETAILS bc where bc.reg_id=?";

	public static final String get_details_date = "select TO_CHAR(sysdate,'dd/MM/yyyy') from dual";

	public static final String GET_UPDATE_DETAILS= "select distinct ETOKENNO,COUNTER_TYPE,NO_OF_PERSONS,PERSON_TYPE,REG_ID,SRO_ID from "+
	" IGRS_ETOKEN_MAKER_DETAILS where flag='A' and REG_ID=? and SRO_ID=? union all"+
	" select ETOKENNO,COUNTER_TYPE,NO_OF_PERSONS,PERSON_TYPE,REG_ID,SRO_ID from "+
	" IGRS_ETOKEN_CHECKER_DETAILS where flag='A' and REG_ID=? and SRO_ID=? ";


	public static final String DELETE_OLD_MAKER = "delete from igrs_etoken_maker_details where reg_id=?";
	public static final String DELETE_OLD_CHECKER = "delete from IGRS_ETOKEN_CHECKER_DETAILS where reg_id=?";
	public static final String GET_NO_OF_TOKENS="SELECT COUNT(*)"+
	" FROM"+
	" (SELECT DISTINCT(ETOKENNO)"+
	" FROM igrs_etoken_maker_details"+
	" WHERE TRUNC(CREATED_DATE) BETWEEN TO_DATE(?,'DD-MM-YY') AND TO_DATE(?,'DD-MM-YY')+1 and sro_id=?"+
	" UNION"+
	" SELECT DISTINCT(ETOKENNO)"+
	" FROM igrs_etoken_checker_details"+
	" WHERE TRUNC(CREATED_DATE) BETWEEN TO_DATE(?,'DD-MM-YY') AND TO_DATE(?,'DD-MM-YY')+1 and sro_id=?"+
	" AND ETOKENNO NOT IN"+
	" (SELECT DISTINCT(ETOKENNO)"+
	" FROM igrs_etoken_maker_details"+
	" WHERE TRUNC(CREATED_DATE) BETWEEN TO_DATE(?,'DD-MM-YY') AND TO_DATE(?,'DD-MM-YY')+1 and sro_id=?))";

	public static final String GET_NO_OF_TOKENS_COMPLETED ="SELECT COUNT(DISTINCT(ETOKENNO))"+
	" FROM igrs_etoken_checker_details "+
	" WHERE TRUNC(CREATED_DATE) BETWEEN TO_DATE(?,'DD-MM-YY') AND TO_DATE(?,'DD-MM-YY')+1 "+
	" AND sro_id=? "+
	" AND reg_status=17";


	public static final String GET_NO_OF_TOKENS_HOLD_M ="SELECT COUNT(DISTINCT(ETOKENNO))"+
	" FROM IGRS_ETOKEN_MAKER_DETAILS"+
	" WHERE TRUNC(CREATED_DATE) BETWEEN TO_DATE(?,'DD-MM-YY') AND TO_DATE(?,'DD-MM-YY')+1"+
	" AND sro_id =?"+
	" AND reg_status=11 and reg_id not in(SELECT reg_id from igrs_etoken_maker_details where flag='A' and reg_status=10)";


	public static final String GET_NO_OF_TOKENS_HOLD_C ="SELECT COUNT(DISTINCT(ETOKENNO))"+
	"FROM IGRS_ETOKEN_CHECKER_DETAILS"+
	"WHERE TRUNC(CREATED_DATE) BETWEEN TO_DATE(?,'DD-MM-YY') AND TO_DATE(?,'DD-MM-YY')+1"+
	"AND sro_id    =?"+
	"AND reg_status=14 and reg_id not in(SELECT reg_id from IGRS_ETOKEN_CHECKER_DETAILS where flag='A' and reg_status=13)";


	public static final String GET_REG_NUMBERS_MAKER = "select distinct REGISTRATION_TXN_ID from igrs_etoken_maker_time where reg_status=13 and sro_id=?";

	public static final String GET_DATE_CHECK_MAKER = "SELECT COUNT(*) FROM igrs_etoken_maker_time x, (SELECT MIN(created_date) as mini FROM igrs_etoken_maker_time"+
	" WHERE REGISTRATION_TXN_ID=?)y "+
	" WHERE x.REGISTRATION_TXN_ID=? "+
	" AND  x.created_date=y.mini "+
	" and x.created_date BETWEEN to_date(?,'dd/mm/yy') AND to_date(?,'dd/mm/yy')+1";

	public static final String GET_TIME_MAKER = "SELECT REGISTRATION_TXN_ID, round(SUM(TIME_TAKEN)) FROM igrs_etoken_maker_time "+
	" WHERE REGISTRATION_TXN_ID=? GROUP BY REGISTRATION_TXN_ID";



	public static final String GET_REG_NUMBERS_CHECKER = "select distinct REGISTRATION_TXN_ID from igrs_etoken_checker_time where reg_status=17 and sro_id=?";

	public static final String GET_DATE_CHECK_CHECKER = "SELECT COUNT(*) FROM igrs_etoken_checker_time x, (SELECT MIN(created_date) as mini FROM igrs_etoken_checker_time"+
	" WHERE REGISTRATION_TXN_ID=?)y "+
	" WHERE x.REGISTRATION_TXN_ID=? "+
	" AND  x.created_date=y.mini "+
	" and x.created_date BETWEEN to_date(?,'dd/mm/yy') AND to_date(?,'dd/mm/yy')+1";

	public static final String GET_TIME_CHECKER = "SELECT REGISTRATION_TXN_ID, round(SUM(TIME_TAKEN)) FROM igrs_etoken_checker_time "+
	" WHERE REGISTRATION_TXN_ID=? GROUP BY REGISTRATION_TXN_ID";


	public static final String GET_COUNTER_MAKER = "select max(Counter_id) from (select COUNTER_ID from IGRS_MAKER_COUNTER_SRO_MASTER where sro_id=? union select COUNTER_ID from IGRS_CHCKER_COUNTER_SRO_MASTER where sro_id=?)";


	public static final String GET_COUNTER_CHECKER= "select max(nvl(counter_id,1)) from igrs_checker_counter_sro_master where sro_id=? and status='A'";

	public static final String GET_ETOKEN_DISTRICT_LIST = "select DISTRICT_ID,DISTRICT_NAME FROM IGRS_DISTRICT_MASTER WHERE DISTRICT_STATUS= 'A' and  state_id=1 " +
	"and district_id in ( select district_id_old from igrs_office_master where etoken_flag='Y' and office_id = ?)";

	public static final String GET_ETOKEN_DISTRICT_LIST_HINDI = "select DISTRICT_ID,H_DISTRICT_NAME FROM IGRS_DISTRICT_MASTER WHERE DISTRICT_STATUS= 'A' and  state_id=1 " +
	"and district_id in ( select district_id_old from igrs_office_master where etoken_flag='Y' and office_id =?)";

	public static final String GET_ETOKEN_SRO_LIST = "SELECT OFFICE_ID, OFFICE_NAME FROM IGRS_OFFICE_MASTER WHERE " +
	"OFFICE_TYPE_ID = '3' AND OFFICE_STATUS = 'A' AND etoken_flag='Y' AND DISTRICT_ID =";

	public static final String GET_ETOKEN_SRO_LIST_HINDI = "SELECT OFFICE_ID, H_OFFICE_NAME FROM IGRS_OFFICE_MASTER WHERE " +
	"OFFICE_TYPE_ID = '3' AND OFFICE_STATUS = 'A' AND etoken_flag='Y' AND DISTRICT_ID =";

	public static final String GET_USERID_COUNTER__MAKER_LIST = "SELECT IM.ACTIVITY_NAME,Q1.USER_ID " +
	"FROM (  SELECT F.DISTRICT_NAME,E.OFFICE_NAME, E.OFFICE_ID,F.DISTRICT_ID, D.USER_ID, COUNT (FM.IGRS_ROLE_FN_ACTIVITY_MAP_ID)" +
	" CNT FROM IGRS_ROLE_FN_ACTIVITY_MAPPING FM, IGRS_ROLE_OFFICE_MAPPING B,IGRS_OFFICE_MASTER E,IGRS_DISTRICT_MASTER F, " +
	"IGRS_USER_ROLE_GROUP_MAPPING D,IGRS_RGROUP_ROLE_MAPPING C WHERE" +
	"  FM.ACTIVITY_ID IN ('ACT_232') AND B.ROLE_ID = FM.ROLE_ID AND B.OFFICE_ID = E.OFFICE_ID AND E.DISTRICT_ID = F.DISTRICT_ID " +
	"AND D.ROLE_ACTIVE = 'A' AND C.ROLE_OFFICE_MAP_ID = B.ROLE_OFFICE_MAP_ID AND C.STATUS = 'A' " +
	"AND D.ROLE_GROUP_ID = C.ROLE_GROUP_ID GROUP BY F.DISTRICT_NAME, E.OFFICE_NAME, E.OFFICE_ID, F.DISTRICT_ID, " +
	"D.USER_ID HAVING COUNT (FM.IGRS_ROLE_FN_ACTIVITY_MAP_ID) < 2) Q1,IGRS_USER_ROLE_GROUP_MAPPING U1, IGRS_RGROUP_ROLE_MAPPING R," +
	" IGRS_ROLE_OFFICE_MAPPING D, IGRS_ROLE_FN_ACTIVITY_MAPPING FM, IGRS_ACTIVITY_MASTER IM WHERE U1.USER_ID = Q1.USER_ID " +
	"AND U1.ROLE_GROUP_ID = R.ROLE_GROUP_ID AND R.ROLE_OFFICE_MAP_ID = D.ROLE_OFFICE_MAP_ID AND D.STATUS = 'A' " +
	"AND D.OFFICE_ID = Q1.OFFICE_ID AND FM.ROLE_ID = D.ROLE_ID AND FM.ACTIVITY_ID = IM.ACTIVITY_ID AND IM.ACTIVITY_ID " +
	"IN ('ACT_232')  AND Q1.DISTRICT_ID = ? AND Q1.OFFICE_ID = ? AND Q1.USER_ID not in(select COUNTER_USER_ID from IGRS_COUNTER_SRO_MASTER)";
	
	
	public static final String GET_USERID_COUNTER__MAKER_LIST_NEW = "SELECT IM.ACTIVITY_NAME,Q1.USER_ID " +
			"FROM (  SELECT F.DISTRICT_NAME,E.OFFICE_NAME, E.OFFICE_ID,F.DISTRICT_ID, D.USER_ID, COUNT (FM.IGRS_ROLE_FN_ACTIVITY_MAP_ID)" +
			" CNT FROM IGRS_ROLE_FN_ACTIVITY_MAPPING FM, IGRS_ROLE_OFFICE_MAPPING B,IGRS_OFFICE_MASTER E,IGRS_DISTRICT_MASTER F, " +
			"IGRS_USER_ROLE_GROUP_MAPPING D,IGRS_RGROUP_ROLE_MAPPING C WHERE" +
			"  FM.ACTIVITY_ID IN ('ACT_232','ACT_233') AND B.ROLE_ID = FM.ROLE_ID AND B.OFFICE_ID = E.OFFICE_ID AND E.DISTRICT_ID = F.DISTRICT_ID " +
			"AND D.ROLE_ACTIVE = 'A' AND C.ROLE_OFFICE_MAP_ID = B.ROLE_OFFICE_MAP_ID AND C.STATUS = 'A' " +
			"AND D.ROLE_GROUP_ID = C.ROLE_GROUP_ID GROUP BY F.DISTRICT_NAME, E.OFFICE_NAME, E.OFFICE_ID, F.DISTRICT_ID, " +
			"D.USER_ID HAVING COUNT (FM.IGRS_ROLE_FN_ACTIVITY_MAP_ID) < 2) Q1,IGRS_USER_ROLE_GROUP_MAPPING U1, IGRS_RGROUP_ROLE_MAPPING R," +
			" IGRS_ROLE_OFFICE_MAPPING D, IGRS_ROLE_FN_ACTIVITY_MAPPING FM, IGRS_ACTIVITY_MASTER IM WHERE U1.USER_ID = Q1.USER_ID " +
			"AND U1.ROLE_GROUP_ID = R.ROLE_GROUP_ID AND R.ROLE_OFFICE_MAP_ID = D.ROLE_OFFICE_MAP_ID AND D.STATUS = 'A' " +
			"AND D.OFFICE_ID = Q1.OFFICE_ID AND FM.ROLE_ID = D.ROLE_ID AND FM.ACTIVITY_ID = IM.ACTIVITY_ID AND IM.ACTIVITY_ID " +
			"IN ('ACT_232')  AND Q1.DISTRICT_ID = ? AND Q1.OFFICE_ID = ? AND Q1.USER_ID not in(select COUNTER_USER_ID from IGRS_COUNTER_SRO_MASTER)";

	public static final String GET_USERID_COUNTER_LIST = "SELECT Q1.USER_ID,IM.ACTIVITY_NAME FROM (SELECT F.DISTRICT_NAME,E.OFFICE_NAME,E.OFFICE_ID,F.DISTRICT_ID,D.USER_ID,COUNT (FM.IGRS_ROLE_FN_ACTIVITY_MAP_ID) CNT FROM IGRS_ROLE_FN_ACTIVITY_MAPPING FM,IGRS_ROLE_OFFICE_MAPPING B,IGRS_OFFICE_MASTER E,IGRS_DISTRICT_MASTER F,IGRS_USER_ROLE_GROUP_MAPPING D,IGRS_RGROUP_ROLE_MAPPING C WHERE FM.ACTIVITY_ID IN ('ACT_233', 'ACT_232') AND B.ROLE_ID            = FM.ROLE_ID AND B.OFFICE_ID          = E.OFFICE_ID AND E.DISTRICT_ID        = F.DISTRICT_ID AND D.ROLE_ACTIVE        = 'A' AND C.ROLE_OFFICE_MAP_ID = B.ROLE_OFFICE_MAP_ID AND C.STATUS             = 'A' AND D.ROLE_GROUP_ID = C.ROLE_GROUP_ID GROUP BY F.DISTRICT_NAME,E.OFFICE_NAME,E.OFFICE_ID,F.DISTRICT_ID,D.USER_ID HAVING COUNT (FM.IGRS_ROLE_FN_ACTIVITY_MAP_ID) < 2) Q1,IGRS_USER_ROLE_GROUP_MAPPING U1,IGRS_RGROUP_ROLE_MAPPING R,IGRS_ROLE_OFFICE_MAPPING D, IGRS_ROLE_FN_ACTIVITY_MAPPING FM, IGRS_ACTIVITY_MASTER IM WHERE U1.USER_ID         = Q1.USER_ID AND U1.ROLE_GROUP_ID     = R.ROLE_GROUP_ID AND R.ROLE_OFFICE_MAP_ID = D.ROLE_OFFICE_MAP_ID AND D.STATUS             = 'A' AND D.OFFICE_ID          = Q1.OFFICE_ID AND FM.ROLE_ID           = D.ROLE_ID AND FM.ACTIVITY_ID= IM.ACTIVITY_ID AND IM.ACTIVITY_ID IN ('ACT_233', 'ACT_232') AND Q1.OFFICE_ID =? AND Q1.DISTRICT_ID= ? AND Q1.USER_ID not in(select COUNTER_USER_ID from IGRS_COUNTER_SRO_MASTER)";


	public static final String GET_USERID_COUNTER__CHECKER_LIST = "SELECT IM.ACTIVITY_NAME,Q1.USER_ID " +
	"FROM (  SELECT F.DISTRICT_NAME,E.OFFICE_NAME, E.OFFICE_ID,F.DISTRICT_ID, D.USER_ID, COUNT (FM.IGRS_ROLE_FN_ACTIVITY_MAP_ID)" +
	" CNT FROM IGRS_ROLE_FN_ACTIVITY_MAPPING FM, IGRS_ROLE_OFFICE_MAPPING B,IGRS_OFFICE_MASTER E,IGRS_DISTRICT_MASTER F, " +
	"IGRS_USER_ROLE_GROUP_MAPPING D,IGRS_RGROUP_ROLE_MAPPING C WHERE" +
	"  FM.ACTIVITY_ID IN ('ACT_233') AND B.ROLE_ID = FM.ROLE_ID AND B.OFFICE_ID = E.OFFICE_ID AND E.DISTRICT_ID = F.DISTRICT_ID " +
	"AND D.ROLE_ACTIVE = 'A' AND C.ROLE_OFFICE_MAP_ID = B.ROLE_OFFICE_MAP_ID AND C.STATUS = 'A' " +
	"AND D.ROLE_GROUP_ID = C.ROLE_GROUP_ID GROUP BY F.DISTRICT_NAME, E.OFFICE_NAME, E.OFFICE_ID, F.DISTRICT_ID, " +
	"D.USER_ID HAVING COUNT (FM.IGRS_ROLE_FN_ACTIVITY_MAP_ID) < 2) Q1,IGRS_USER_ROLE_GROUP_MAPPING U1, IGRS_RGROUP_ROLE_MAPPING R," +
	" IGRS_ROLE_OFFICE_MAPPING D, IGRS_ROLE_FN_ACTIVITY_MAPPING FM, IGRS_ACTIVITY_MASTER IM WHERE U1.USER_ID = Q1.USER_ID " +
	"AND U1.ROLE_GROUP_ID = R.ROLE_GROUP_ID AND R.ROLE_OFFICE_MAP_ID = D.ROLE_OFFICE_MAP_ID AND D.STATUS = 'A' " +
	"AND D.OFFICE_ID = Q1.OFFICE_ID AND FM.ROLE_ID = D.ROLE_ID AND FM.ACTIVITY_ID = IM.ACTIVITY_ID AND IM.ACTIVITY_ID " +
	"IN ('ACT_233')  AND Q1.DISTRICT_ID = ? AND Q1.OFFICE_ID = ? AND Q1.USER_ID not in(select COUNTER_USER_ID from IGRS_COUNTER_SRO_MASTER)";

	public static final String GET_USERID_COUNTER_LIST__MAKER_HINDI = "SELECT im.h_activity_name,Q1.USER_ID FROM (  SELECT F.DISTRICT_NAME,E.OFFICE_NAME, " +
	"E.OFFICE_ID,F.DISTRICT_ID, D.USER_ID, COUNT (FM.IGRS_ROLE_FN_ACTIVITY_MAP_ID) CNT FROM IGRS_ROLE_FN_ACTIVITY_MAPPING FM, IGRS_ROLE_OFFICE_MAPPING B" +
	",IGRS_OFFICE_MASTER E,IGRS_DISTRICT_MASTER F, IGRS_USER_ROLE_GROUP_MAPPING D,IGRS_RGROUP_ROLE_MAPPING C WHERE     FM.ACTIVITY_ID IN ( 'ACT_232') " +
	"AND B.ROLE_ID = FM.ROLE_ID AND B.OFFICE_ID = E.OFFICE_ID AND E.DISTRICT_ID = F.DISTRICT_ID AND D.ROLE_ACTIVE = 'A' AND C.ROLE_OFFICE_MAP_ID = B.ROLE_OFFICE_MAP_ID" +
	" AND C.STATUS = 'A' AND D.ROLE_GROUP_ID = C.ROLE_GROUP_ID GROUP BY F.DISTRICT_NAME, E.OFFICE_NAME, E.OFFICE_ID, F.DISTRICT_ID, D.USER_ID HAVING " +
	"COUNT (FM.IGRS_ROLE_FN_ACTIVITY_MAP_ID) < 2) Q1,IGRS_USER_ROLE_GROUP_MAPPING U1, IGRS_RGROUP_ROLE_MAPPING R, IGRS_ROLE_OFFICE_MAPPING D, IGRS_ROLE_FN_ACTIVITY_MAPPING FM," +
	" IGRS_ACTIVITY_MASTER IM WHERE U1.USER_ID = Q1.USER_ID AND U1.ROLE_GROUP_ID = R.ROLE_GROUP_ID AND R.ROLE_OFFICE_MAP_ID = D.ROLE_OFFICE_MAP_ID AND D.STATUS = 'A' " +
	"AND D.OFFICE_ID = Q1.OFFICE_ID AND FM.ROLE_ID = D.ROLE_ID AND FM.ACTIVITY_ID = IM.ACTIVITY_ID AND IM.ACTIVITY_ID IN ('ACT_232')  AND Q1.DISTRICT_ID = ? " +
	"AND Q1.OFFICE_ID = ? AND Q1.USER_ID not in(select COUNTER_USER_ID from IGRS_COUNTER_SRO_MASTER)";

	public static final String GET_USERID_COUNTER_LIST__CHECKER_HINDI = "SELECT im.h_activity_name,Q1.USER_ID FROM (  SELECT F.DISTRICT_NAME,E.OFFICE_NAME, " +
	"E.OFFICE_ID,F.DISTRICT_ID, D.USER_ID, COUNT (FM.IGRS_ROLE_FN_ACTIVITY_MAP_ID) CNT FROM IGRS_ROLE_FN_ACTIVITY_MAPPING FM, IGRS_ROLE_OFFICE_MAPPING B" +
	",IGRS_OFFICE_MASTER E,IGRS_DISTRICT_MASTER F, IGRS_USER_ROLE_GROUP_MAPPING D,IGRS_RGROUP_ROLE_MAPPING C WHERE     FM.ACTIVITY_ID IN ( 'ACT_233') " +
	"AND B.ROLE_ID = FM.ROLE_ID AND B.OFFICE_ID = E.OFFICE_ID AND E.DISTRICT_ID = F.DISTRICT_ID AND D.ROLE_ACTIVE = 'A' AND C.ROLE_OFFICE_MAP_ID = B.ROLE_OFFICE_MAP_ID" +
	" AND C.STATUS = 'A' AND D.ROLE_GROUP_ID = C.ROLE_GROUP_ID GROUP BY F.DISTRICT_NAME, E.OFFICE_NAME, E.OFFICE_ID, F.DISTRICT_ID, D.USER_ID HAVING " +
	"COUNT (FM.IGRS_ROLE_FN_ACTIVITY_MAP_ID) < 2) Q1,IGRS_USER_ROLE_GROUP_MAPPING U1, IGRS_RGROUP_ROLE_MAPPING R, IGRS_ROLE_OFFICE_MAPPING D, IGRS_ROLE_FN_ACTIVITY_MAPPING FM," +
	" IGRS_ACTIVITY_MASTER IM WHERE U1.USER_ID = Q1.USER_ID AND U1.ROLE_GROUP_ID = R.ROLE_GROUP_ID AND R.ROLE_OFFICE_MAP_ID = D.ROLE_OFFICE_MAP_ID AND D.STATUS = 'A' " +
	"AND D.OFFICE_ID = Q1.OFFICE_ID AND FM.ROLE_ID = D.ROLE_ID AND FM.ACTIVITY_ID = IM.ACTIVITY_ID AND IM.ACTIVITY_ID IN ('ACT_233')  AND Q1.DISTRICT_ID = ? " +
	"AND Q1.OFFICE_ID = ? AND Q1.USER_ID not in(select COUNTER_USER_ID from IGRS_COUNTER_SRO_MASTER)";

	public static final String GET_COUNTER = "select max(Counter_id) from (select COUNTER_ID from IGRS_COUNTER_SRO_MASTER where sro_id=?)";

	//public static final String GET_COUNTER_OFFICE_MAPPING_LIST="select counter_name from IGRS_ET_OFFICE_COUNTER_MAPPING where office_id=?";
	public static final String GET_COUNTER_OFFICE_MAPPING_LIST="SELECT MAPPING_ID,COUNTER_NAME FROM IGRS_ET_OFFICE_COUNTER_MAPPING WHERE  OFFICE_ID=? and COUNTER_TYPE=? " +
	"and mapping_id not in(select COUNTER_MAPPING_ID from IGRS_COUNTER_SRO_MASTER) order by COUNTER_NAME";


	public static final String SAVE_COUNTER_DETLS = "INSERT INTO IGRS_COUNTER_SRO_MASTER(COUNTER_ID,DISTRICT_ID,SRO_ID,COUNTER_USER_ID,COUNTER_TYPE," +
	"COUNTER_MAPPING_ID,STATUS,CREATED_BY,CREATED_DATE) VALUES(?,?,?,?,?,?,'A',?,to_date(?,'dd/mm/yyyy'))";

	// blocked by akansha
	/*
	 * public static final String GET_COUNTER_DETAILS =
	 * "SELECT A.COUNTER_ID,B.COUNTER_NAME,B.COUNTER_TYPE,A.COUNTER_USER_ID,A.STATUS FROM IGRS_COUNTER_SRO_MASTER A,"
	 * +
	 * "IGRS_ET_OFFICE_COUNTER_MAPPING B WHERE A.COUNTER_MAPPING_ID=B.MAPPING_ID AND A.DISTRICT_ID=? AND UPPER(A.SRO_ID)=UPPER(?) order by STATUS,B.COUNTER_NAME"
	 * ;
	 * 
	 * public static final String GET_COUNTER_DETAILS_HINDI =
	 * "SELECT A.COUNTER_ID,B.COUNTER_NAME,B.COUNTER_TYPE_H,A.COUNTER_USER_ID,A.STATUS FROM IGRS_COUNTER_SRO_MASTER A,"
	 * +
	 * "IGRS_ET_OFFICE_COUNTER_MAPPING B WHERE A.COUNTER_MAPPING_ID=B.MAPPING_ID AND A.DISTRICT_ID=? AND UPPER(A.SRO_ID)=UPPER(?) order by STATUS,B.COUNTER_NAME"
	 * ;
	 */

	public static final String GET_COUNTER_DETAILS = "SELECT A.COUNTER_ID,B.COUNTER_NAME,B.COUNTER_TYPE,A.COUNTER_USER_ID,A.STATUS FROM IGRS_COUNTER_SRO_MASTER A,"
		+ "IGRS_ET_OFFICE_COUNTER_MAPPING B WHERE A.COUNTER_MAPPING_ID=B.MAPPING_ID AND A.DISTRICT_ID=? AND UPPER(A.SRO_ID)=UPPER(?) order by STATUS,B.COUNTER_NAME";

	public static final String GET_COUNTER_DETAILS_HINDI = "SELECT A.COUNTER_ID,B.COUNTER_NAME,B.COUNTER_TYPE_H,A.COUNTER_USER_ID,A.STATUS FROM IGRS_COUNTER_SRO_MASTER A,"
		+ "IGRS_ET_OFFICE_COUNTER_MAPPING B WHERE A.COUNTER_MAPPING_ID=B.MAPPING_ID AND A.DISTRICT_ID=? AND UPPER(A.SRO_ID)=UPPER(?) order by STATUS,B.COUNTER_NAME";

	//coomented bu akansha
	/*public static final String GET_COMPLETE_COUNTER_DETLS = " SELECT B.COUNTER_NAME,A.COUNTER_USER_ID,B.COUNTER_TYPE,A.COUNTER_MAPPING_ID " +
	"FROM IGRS_COUNTER_SRO_MASTER A,IGRS_ET_OFFICE_COUNTER_MAPPING B WHERE A.COUNTER_MAPPING_ID=B.MAPPING_ID AND COUNTER_ID = ";
*/
	
	public static final String GET_COMPLETE_COUNTER_DETLS = " SELECT B.COUNTER_NAME,A.COUNTER_USER_ID,B.COUNTER_TYPE,A.COUNTER_MAPPING_ID " +
			"FROM IGRS_COUNTER_SRO_MASTER A,IGRS_ET_OFFICE_COUNTER_MAPPING B WHERE A.COUNTER_MAPPING_ID=B.MAPPING_ID AND  A.DISTRICT_ID=? AND UPPER(A.SRO_ID)=UPPER(?) and a.COUNTER_ID =?";

	//coomented bu akansha
	/*public static final String GET_COMPLETE_COUNTER_DETLS_HINDI = " SELECT B.COUNTER_NAME,A.COUNTER_USER_ID,B.COUNTER_TYPE_H,A.COUNTER_MAPPING_ID " +
	"FROM IGRS_COUNTER_SRO_MASTER A,IGRS_ET_OFFICE_COUNTER_MAPPING B WHERE A.COUNTER_MAPPING_ID=B.MAPPING_ID AND COUNTER_ID =";
*/
	
	
	public static final String GET_COMPLETE_COUNTER_DETLS_HINDI = " SELECT B.COUNTER_NAME,A.COUNTER_USER_ID,B.COUNTER_TYPE_H,A.COUNTER_MAPPING_ID " +
			"FROM IGRS_COUNTER_SRO_MASTER A,IGRS_ET_OFFICE_COUNTER_MAPPING B WHERE A.COUNTER_MAPPING_ID=B.MAPPING_ID AND  A.DISTRICT_ID=? AND UPPER(A.SRO_ID)=UPPER(?) and a.COUNTER_ID =?";

	
	public static final String UPDATE_COUNTER_DETLS = "UPDATE IGRS_COUNTER_SRO_MASTER SET STATUS = ?,UPDATE_BY = ?," +
	"UPDATE_DATE =TO_DATE(SYSDATE,'dd/mm/yyyy') WHERE COUNTER_ID = ? AND DISTRICT_ID =? AND SRO_ID=?";

	public static final String GET_MAPPED_COUNTER_LIST="SELECT A.COUNTER_USER_ID,B.COUNTER_TYPE,A.COUNTER_MAPPING_ID," +
	"B.COUNTER_NAME FROM IGRS_COUNTER_SRO_MASTER A,IGRS_ET_OFFICE_COUNTER_MAPPING B WHERE" +
	" A.COUNTER_MAPPING_ID=B.MAPPING_ID AND A.DISTRICT_ID=? AND  A.STATUS='A' AND UPPER(A.SRO_ID)=UPPER(?) order by B.COUNTER_NAME";

	public static final String GET_MAPPED_COUNTER_LIST_HINDI="SELECT A.COUNTER_USER_ID,B.COUNTER_TYPE_H,A.COUNTER_MAPPING_ID," +
	"B.COUNTER_NAME FROM IGRS_COUNTER_SRO_MASTER A,IGRS_ET_OFFICE_COUNTER_MAPPING B WHERE" +
	" A.COUNTER_MAPPING_ID=B.MAPPING_ID AND A.DISTRICT_ID=? AND  A.STATUS='A' AND UPPER(A.SRO_ID)=UPPER(?) order by B.COUNTER_NAME";

	public static final String GET_ATTENDENCE_MASTER_LIST="SELECT COUNTER_ID FROM IGRS_COUNTER_ATTENDENCE_MASTER " +
	"WHERE " +
	"TRUNC(CREATED_DATE)=TRUNC(SYSDATE) AND" +
	" IS_ACTIVE='A' AND DISTRICT_ID=? AND UPPER(SRO_ID)=UPPER(?)";

	public static final String INSERT_ATTENDENCE_MASTER_DATA="INSERT INTO IGRS_COUNTER_ATTENDENCE_MASTER" +
	"( ATTENDENCE_ID,COUNTER_ID, IS_ACTIVE, DISTRICT_ID,SRO_ID,CREATED_BY,CREATED_DATE) " +
	"VALUES (Etoken_Counter_Attendence.nextval, ?,  'A',  ?, ?, ?, SYSTIMESTAMP)";

	public static final String UPDATE_ATTENDENCE_MASTER_DATA="UPDATE IGRS_COUNTER_ATTENDENCE_MASTER " +
	"SET IS_ACTIVE='D',UPDATE_DATE=SYSTIMESTAMP,UPDATE_BY=? WHERE IS_ACTIVE='A' " +
	"AND COUNTER_ID=? AND DISTRICT_ID=? AND SRO_ID=?";

	public static final String GET_USERID_COUNTER_TYPE = "SELECT IM.ACTIVITY_NAME,Q1.USER_ID " +
	"FROM (  SELECT F.DISTRICT_NAME,E.OFFICE_NAME, E.OFFICE_ID,F.DISTRICT_ID, D.USER_ID, COUNT (FM.IGRS_ROLE_FN_ACTIVITY_MAP_ID)" +
	" CNT FROM IGRS_ROLE_FN_ACTIVITY_MAPPING FM, IGRS_ROLE_OFFICE_MAPPING B,IGRS_OFFICE_MASTER E,IGRS_DISTRICT_MASTER F, " +
	"IGRS_USER_ROLE_GROUP_MAPPING D,IGRS_RGROUP_ROLE_MAPPING C WHERE" +
	"  FM.ACTIVITY_ID IN ('ACT_233', 'ACT_232') AND B.ROLE_ID = FM.ROLE_ID AND B.OFFICE_ID = E.OFFICE_ID AND E.DISTRICT_ID = F.DISTRICT_ID " +
	"AND D.ROLE_ACTIVE = 'A' AND C.ROLE_OFFICE_MAP_ID = B.ROLE_OFFICE_MAP_ID AND C.STATUS = 'A' " +
	"AND D.ROLE_GROUP_ID = C.ROLE_GROUP_ID GROUP BY F.DISTRICT_NAME, E.OFFICE_NAME, E.OFFICE_ID, F.DISTRICT_ID, " +
	"D.USER_ID HAVING COUNT (FM.IGRS_ROLE_FN_ACTIVITY_MAP_ID) < 2) Q1,IGRS_USER_ROLE_GROUP_MAPPING U1, IGRS_RGROUP_ROLE_MAPPING R," +
	" IGRS_ROLE_OFFICE_MAPPING D, IGRS_ROLE_FN_ACTIVITY_MAPPING FM, IGRS_ACTIVITY_MASTER IM WHERE U1.USER_ID = Q1.USER_ID " +
	"AND U1.ROLE_GROUP_ID = R.ROLE_GROUP_ID AND R.ROLE_OFFICE_MAP_ID = D.ROLE_OFFICE_MAP_ID AND D.STATUS = 'A' " +
	"AND D.OFFICE_ID = Q1.OFFICE_ID AND FM.ROLE_ID = D.ROLE_ID AND FM.ACTIVITY_ID = IM.ACTIVITY_ID AND IM.ACTIVITY_ID " +
	"IN ('ACT_233', 'ACT_232')  AND Q1.DISTRICT_ID = ? AND Q1.OFFICE_ID = ? AND Q1.USER_ID =?";

	public static final String GET_USERID_COUNTER_TYPE_HINDI = "SELECT im.h_activity_name,Q1.USER_ID FROM (  SELECT F.DISTRICT_NAME,E.OFFICE_NAME, " +
	"E.OFFICE_ID,F.DISTRICT_ID, D.USER_ID, COUNT (FM.IGRS_ROLE_FN_ACTIVITY_MAP_ID) CNT FROM IGRS_ROLE_FN_ACTIVITY_MAPPING FM, IGRS_ROLE_OFFICE_MAPPING B" +
	",IGRS_OFFICE_MASTER E,IGRS_DISTRICT_MASTER F, IGRS_USER_ROLE_GROUP_MAPPING D,IGRS_RGROUP_ROLE_MAPPING C WHERE     FM.ACTIVITY_ID IN ('ACT_233', 'ACT_232') " +
	"AND B.ROLE_ID = FM.ROLE_ID AND B.OFFICE_ID = E.OFFICE_ID AND E.DISTRICT_ID = F.DISTRICT_ID AND D.ROLE_ACTIVE = 'A' AND C.ROLE_OFFICE_MAP_ID = B.ROLE_OFFICE_MAP_ID" +
	" AND C.STATUS = 'A' AND D.ROLE_GROUP_ID = C.ROLE_GROUP_ID GROUP BY F.DISTRICT_NAME, E.OFFICE_NAME, E.OFFICE_ID, F.DISTRICT_ID, D.USER_ID HAVING " +
	"COUNT (FM.IGRS_ROLE_FN_ACTIVITY_MAP_ID) < 2) Q1,IGRS_USER_ROLE_GROUP_MAPPING U1, IGRS_RGROUP_ROLE_MAPPING R, IGRS_ROLE_OFFICE_MAPPING D, IGRS_ROLE_FN_ACTIVITY_MAPPING FM," +
	" IGRS_ACTIVITY_MASTER IM WHERE U1.USER_ID = Q1.USER_ID AND U1.ROLE_GROUP_ID = R.ROLE_GROUP_ID AND R.ROLE_OFFICE_MAP_ID = D.ROLE_OFFICE_MAP_ID AND D.STATUS = 'A' " +
	"AND D.OFFICE_ID = Q1.OFFICE_ID AND FM.ROLE_ID = D.ROLE_ID AND FM.ACTIVITY_ID = IM.ACTIVITY_ID AND IM.ACTIVITY_ID IN ('ACT_233', 'ACT_232')  AND Q1.DISTRICT_ID = ? " +
	"AND Q1.OFFICE_ID = ? AND Q1.USER_ID =?";

	public static final String UPDATE_MAKER_COUNTER = "update IGRS_ETOKEN_MAKER_DETAILS set COUNTER_NO=? where REG_ID=? and ETOKENNO=? and flag='A'";
	public static final String UPDATE_CHECKER_COUNTER = "update IGRS_ETOKEN_CHECKER_DETAILS set COUNTER_NO=? where REG_ID=? and ETOKENNO=? and flag='A'";
	public static final String GET_COUNTER_MAPPING_ID = "SELECT MAPPING_ID FROM IGRS_ET_OFFICE_COUNTER_MAPPING WHERE COUNTER_NAME=? AND OFFICE_ID=?";

	public static final String SELECT_ATTENDENCE_MASTER_DATA="SELECT count(*) FROM IGRS_COUNTER_ATTENDENCE_MASTER WHERE " +
	"DISTRICT_ID=? AND SRO_ID=? and TRUNC(CREATED_DATE) = TRUNC(SYSDATE)";

	public static final String GET_MAKER_COUNTERS="SELECT A.COUNTER_MAPPING_ID,B.COUNTER_NAME FROM IGRS_COUNTER_SRO_MASTER A, " +
	"IGRS_ET_OFFICE_COUNTER_MAPPING B  WHERE A.STATUS='A' AND A.SRO_ID=? " +
	"AND A.COUNTER_TYPE='Maker' AND A.COUNTER_ID=B.MAPPING_ID";
	public static final String GET_ETOKEN_ACTIVE_MAKER_COUNTER_LIST="SELECT A.COUNTER_ID ,B.COUNTER_NAME FROM  IGRS_COUNTER_ATTENDENCE_MASTER A,IGRS_ET_OFFICE_COUNTER_MAPPING B " +
	"WHERE A.IS_ACTIVE='A' AND TRUNC(A.CREATED_DATE) = TRUNC(SYSDATE) AND A.COUNTER_ID=B.MAPPING_ID AND UPPER(B.COUNTER_TYPE)=UPPER('MAKER') AND A.SRO_ID=?" ;
	
	public static final String GET_ETOKEN_ACTIVE_CHECKER_COUNTER_LIST="SELECT A.COUNTER_ID ,B.COUNTER_NAME FROM  IGRS_COUNTER_ATTENDENCE_MASTER A,IGRS_ET_OFFICE_COUNTER_MAPPING B " +
	"WHERE A.IS_ACTIVE='A' AND TRUNC(A.CREATED_DATE) = TRUNC(SYSDATE) AND A.COUNTER_ID=B.MAPPING_ID AND UPPER(B.COUNTER_TYPE)=UPPER('CHECKER') AND A.SRO_ID=?" ;

	public static final String check_COUNTER_Number_maker = "Select COUNTER_NO from  IGRS_ETOKEN_MAKER_DETAILS  where REG_ID=? and ETOKENNO=?";

	public static final String check_COUNTER_Number_checker = "Select COUNTER_NO from  IGRS_ETOKEN_CHECKER_DETAILS  where REG_ID=? and ETOKENNO=?";
	
}
