/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.wipro.igrs.empmgmt.form;

import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import com.wipro.igrs.baseaction.form.BaseForm;
import com.wipro.igrs.empmgmt.dto.TrainingDTO;
import com.wipro.igrs.empmgmt.dto.EmployeeDTO;


public class TrainingForm extends BaseForm{
	TrainingDTO trainingDTO=new TrainingDTO();
	ArrayList employeeList=new ArrayList();

	/**
	 * @return the trainingDTO
	 */
	public TrainingDTO getTrainingDTO() {
		return trainingDTO;
	}

	/**
	 * @param trainingDTO the trainingDTO to set
	 */
	public void setTrainingDTO(TrainingDTO trainingDTO) {
		this.trainingDTO = trainingDTO;
	}

	/**
	 * @return the employeeList
	 */
	public ArrayList getEmployeeList() {
		return employeeList;
	}

	/**
	 * @param employeeList the employeeList to set
	 */
	public void setEmployeeList(ArrayList employeeList) {
		this.employeeList = employeeList;
	}
	public void setEmployeeDTO(int index ,EmployeeDTO value){
		for(; index>=employeeList.size();employeeList.add(new EmployeeDTO()));
		 employeeList.add(index,value);
	}
	public EmployeeDTO getEmployeeDTO(int index){
		for(; index>=employeeList.size();employeeList.add(new EmployeeDTO()));
		return (EmployeeDTO) employeeList.get(index);
	
	}
	
}
