/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.wipro.igrs.empmgmt.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import com.wipro.igrs.baseaction.form.BaseForm;
import com.wipro.igrs.empmgmt.dto.TransferDTO;

/** 
 * MyEclipse Struts
 * Creation date: 06-13-2008
 * 
 * XDoclet definition:
 * @struts.form name="transferForm"
 */
public class TransferForm extends BaseForm {
	private TransferDTO transferDTO=new TransferDTO();
	private String actionName;
	/*
	 * Generated Methods
	 */

	/**
	 * @return the transferDTO
	 */
	public TransferDTO getTransferDTO() {
		return transferDTO;
	}

	/**
	 * @param transferDTO the transferDTO to set
	 */
	public void setTransferDTO(TransferDTO transferDTO) {
		this.transferDTO = transferDTO;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/**
	 * @return the actionName
	 */
	public String getActionName() {
		return actionName;
	}

	/**
	 * @param actionName the actionName to set
	 */
	public void setActionName(String actionName) {
		this.actionName = actionName;
	}
}