/*
 * Copyright Notice
 *==============================================================================
 * This file contains proprietary information of Wipro Infotech, Bangalore.
 * Copying or reproduction without prior written approval is prohibited.
 * Copyright (c) 2007-08
 *==============================================================================
 *
 * File Name   :   CommonSQL.java
 * Author      :   Imran Shaik
 * Description :   Represents the SQL Class for Registration Initiation.
 * ----------------------------------------------------------------------------
 * Version         Last Modified By     Last Modified On           Modification
 * ----------------------------------------------------------------------------
 * 	0.0             Imran Shaik		     18th Mar, 2008	 
 *  1.0         Sayed Taha(Wipro-egypt)     27th Aug, 2008 		 
 * ----------------------------------------------------------------------------
 */


package com.wipro.igrs.deedmaster.sql;


public class CommonSQL {
    public static final String INSERT_MODULE_MASTER = "INSERT INTO IGRS_MODULE_MASTER M (M.MODULE_ID,M.MODULE_NAME,M.MODULE_DESCRIPTION,M.MODULE_STATUS,M.CREATED_BY,M.CREATED_DATE) VALUES (IGRS_MODULE_MASTER_SEQ1.NEXTVAL,?,?,'A',?,SYSDATE)";
    public static final String SELECT_MODULES_LIST = "SELECT MODULE_ID,MODULE_NAME FROM IGRS_MODULE_MASTER WHERE MODULE_STATUS='A'";
    public static final String SELECT_SUB_MODULES_LIST = "SELECT SUB_MODULE_ID,SUB_MODULE_NAME FROM IGRS_SUB_MODULE_MASTER WHERE SUB_MODULE_STATUS='A'";
    public static final String SELECT_DEEDS_LIST = "SELECT M.DEED_TYPE_ID,M.DEED_TYPE_NAME,M.DEED_TYPE_DESCRIPTION FROM IGRS_DEED_TYPE_MASTER M WHERE M.DEED_STATUS='A'";
    public static final String SELECT_INSTRUMENTS_LIST = "SELECT INSTRUMENT_ID,INSTRUMENT_NAME,INSTRUMENT_DESCRIPTION FROM IGRS_DEED_INSTRUMENT_MASTER WHERE INSTRUMENT_STATUS='A'";
    public static final String INSERT_SUB_MODULE_MASTER = "INSERT INTO IGRS_SUB_MODULE_MASTER M (M.SUB_MODULE_ID,M.MODULE_ID,M.SUB_MODULE_NAME,M.SUB_MODULE_DESCRIPTION,M.SUB_MODULE_STATUS,M.CREATED_BY,M.CREATED_DATE) VALUES (IGRS_SUB_MODULE_MASTER_SEQ.NEXTVAL,?,?,?,'A',?,SYSDATE)";
    public static final String INSERT_FUNCTION_MASTER = "INSERT INTO IGRS_FUNCTION_MASTER M (M.FUNCTION_ID,M.SUB_MODULE_ID,M.FUNCTION_NAME,M.FUNCTION_DESC,M.PAYMENT_FLAG,M.INTIMATION_FLAG,M.FUNCTION_STATUS,M.CREATED_BY,M.CREATED_DATE) VALUES (IGRS_FUNCTION_MASTER_SEQ.NEXTVAL,?,?,?,?,?,'A',?,SYSDATE)";
    public static final String INSERT_DEED_TYPE_MASTER ="INSERT INTO IGRS_DEED_TYPE_MASTER (DEED_TYPE_ID ,DEED_TYPE_NAME, DEED_TYPE_DESCRIPTION,DEED_STATUS,CREATED_BY,CREATED_DATE,DEED_CATEGORY,PIN_REQUIRED,PROPERTY_RELATED_DEED,ROR_REQUIRED,DEED_PRIORITY,PROPERTY_VAL_REQD,DUTY_CAL_REQD) values(IGRS_DEED_TYPE_MASTER_SEQ.NEXTVAL,?,?,'A',?,SYSDATE,?,?,?,?,?,?,?)";
    public static final String IS_DEEP_TYPE_EXIST="SELECT * FROM IGRS_DEED_TYPE_MASTER WHERE DEED_TYPE_NAME=? AND DEED_STATUS='A'";
    //   "INSERT INTO IGRS_DEED_TYPE_MASTER M (M.DEED_TYPE_ID,M.DEED_TYPE_NAME,M.DEED_TYPE_DESCRIPTION,M.DEED_CATEGORY,M.DEED_STATUS,M.CREATED_BY,M.CREATED_DATE) VALUES (IGRS_DEED_TYPE_MASTER_SEQ.NEXTVAL,?,?,?,'A',?,SYSDATE)";
    public static final String GET_DEEP_TYPE_BYNAME="SELECT DEED_TYPE_ID FROM IGRS_DEED_TYPE_MASTER WHERE DEED_TYPE_NAME=? AND DEED_STATUS='A'";
    public static final String INSERT_SUB_CLAUSE_MASTER = "INSERT INTO IGRS_SUB_CLAUSE_MASTER S (S.SUB_CLAUSE_ID,S.SUB_CLAUSE_NAME,S.SUB_CLAUSE_DESC,S.SUB_CLAUSE_STATUS,S.CREATED_BY,S.CREATED_DATE) VALUES (IGRS_SUB_CLAUSE_SEQ.NEXTVAL,?,?,'A',?,SYSDATE)";
    public static final String SELECT_SUB_CLAUSE = "SELECT S.SUB_CLAUSE_ID,S.SUB_CLAUSE_NAME,S.SUB_CLAUSE_DESC,S.SUB_CLAUSE_STATUS FROM IGRS_SUB_CLAUSE_MASTER S WHERE S.SUB_CLAUSE_ID=?";
    public static final String UPDATE_SUB_CLAUSE = "UPDATE IGRS_SUB_CLAUSE_MASTER S SET S.SUB_CLAUSE_NAME=?,S.SUB_CLAUSE_DESC=?,S.SUB_CLAUSE_STATUS=?,S.UPDATE_BY,S.UPDATE=SYSDATE WHERE S.SUB_CLAUSE_ID=?";
    public static final String SELECT_MODULE_MASTER_LIST = "SELECT MODULE_ID,MODULE_NAME,MODULE_DESCRIPTION FROM IGRS_MODULE_MASTER WHERE MODULE_STATUS='A'";
    public static final String SELECT_SUB_MODULE_MASTER_LIST = "SELECT SUB_MODULE_ID,SUB_MODULE_NAME,SUB_MODULE_DESCRIPTION FROM IGRS_SUB_MODULE_MASTER WHERE SUB_MODULE_STATUS='A'";
    public static final String SELECT_FUNCTION_MASTER_LIST = "SELECT FUNCTION_ID,FUNCTION_NAME,FUNCTION_DESC FROM IGRS_FUNCTION_MASTER WHERE FUNCTION_STATUS='A'";
    public static final String SELECT_SUB_CLAUSE_MASTER_LIST = "SELECT S.SUB_CLAUSE_ID,S.SUB_CLAUSE_NAME,S.SUB_CLAUSE_DESC FROM IGRS_SUB_CLAUSE_MASTER S WHERE S.SUB_CLAUSE_STATUS='A'";
    public static final String SELECT_DEED_TYPE_MASTER_LIST = "SELECT M.DEED_TYPE_ID,M.DEED_TYPE_NAME,M.DEED_TYPE_DESCRIPTION FROM IGRS_DEED_TYPE_MASTER M WHERE M.DEED_STATUS='A'";
    public static final String SELECT_INSTRUMENT_MASTER_LIST = "SELECT INSTRUMENT_ID,INSTRUMENT_NAME,INSTRUMENT_DESCRIPTION FROM IGRS_DEED_INSTRUMENT_MASTER WHERE INSTRUMENT_STATUS='A'";
    public static final String SELECT_EXEMPTION_MASTER_LIST = "SELECT E.EXEMPTION_ID,E.EXEMPTION_NAME,E.EXEMPTION_DESCRIPTION FROM IGRS_DEED_EXEMPTION_MASTER E WHERE E.EXEMPTION_STATUS='A'";
    public static final String SELECT_MODULE = "SELECT MODULE_ID,MODULE_NAME,MODULE_DESCRIPTION,MODULE_STATUS FROM IGRS_MODULE_MASTER WHERE MODULE_ID=?";
    public static final String SELECT_SUB_MODULE = "SELECT SUB_MODULE_ID,SUB_MODULE_NAME,SUB_MODULE_DESCRIPTION,SUB_MODULE_STATUS,MODULE_ID FROM IGRS_SUB_MODULE_MASTER WHERE SUB_MODULE_ID=?";
    public static final String SELECT_FUNCTION = "SELECT FUNCTION_ID,FUNCTION_NAME,FUNCTION_DESC,FUNCTION_STATUS,SUB_MODULE_ID,PAYMENT_FLAG,INTIMATION_FLAG FROM IGRS_FUNCTION_MASTER WHERE FUNCTION_ID=?";
    public static final String SELECT_DEED_TYPE = "SELECT M.DEED_TYPE_ID,M.DEED_TYPE_NAME,M.DEED_TYPE_DESCRIPTION,M.DEED_STATUS,M.DEED_CATEGORY FROM IGRS_DEED_TYPE_MASTER M WHERE M.DEED_TYPE_ID=?";
    public static final String SELECT_DEED_TYPE_SEARCH = "SELECT  DEED_TYPE_ID ,DEED_TYPE_NAME, DEED_TYPE_DESCRIPTION,DEED_STATUS,DEED_CATEGORY,PIN_REQUIRED,PROPERTY_RELATED_DEED,ROR_REQUIRED,DEED_PRIORITY,PROPERTY_VAL_REQD,DUTY_CAL_REQD FROM IGRS_DEED_TYPE_MASTER where DEED_TYPE_ID=?";
    public static final String SELECT_DEED_TYPE_NAME = "SELECT DEED_TYPE_ID, DEED_TYPE_NAME,DEED_STATUS FROM IGRS_DEED_TYPE_MASTER where DEED_STATUS='A' order by DEED_TYPE_ID";
    public static final String UPDATE_MODULE = "UPDATE IGRS_MODULE_MASTER M SET M.MODULE_NAME=?,M.MODULE_DESCRIPTION=?,M.MODULE_STATUS=?,M.UPDATE_BY=?,M.UPDATE_DATE=SYSDATE WHERE M.MODULE_ID=?";
    public static final String UPDATE_SUB_MODULE = "UPDATE IGRS_SUB_MODULE_MASTER S SET S.SUB_MODULE_NAME=?,S.SUB_MODULE_DESCRIPTION=?,S.SUB_MODULE_STATUS=?,S.MODULE_ID=?,S.UPDATE_BY=?,S.UPDATE_DATE=SYSDATE WHERE S.SUB_MODULE_ID=?";
    public static final String UPDATE_FUNCTION = "UPDATE IGRS_FUNCTION_MASTER F SET F.FUNCTION_NAME=?,F.FUNCTION_DESC=?,F.FUNCTION_STATUS=?,F.PAYMENT_FLAG=?,F.INTIMATION_FLAG=?,F.SUB_MODULE_ID=?,F.UPDATE_BY=?,F.UPDATE_DATE=SYSDATE WHERE F.FUNCTION_ID=?";
    public static final String UPDATE_DEED_TYPE = "UPDATE igrs_deed_type_master SET deed_type_name = ?,  deed_type_description = ?, update_by = ?,  UPDATE_date = sysdate,  deed_category = ?,  pin_required = ?,  property_related_deed = ?,  ror_required = ? , DEED_PRIORITY=? , PROPERTY_VAL_REQD=? , DUTY_CAL_REQD=?  WHERE  deed_type_id = ?";
    public static final String INSERT_INSTRUMENT_MASTER = "INSERT INTO IGRS_DEED_INSTRUMENT_MASTER I (I.INSTRUMENT_ID,I.INSTRUMENT_NAME,I.INSTRUMENT_DESCRIPTION,I.DEED_TYPE_ID,I.INSTRUMENT_STATUS,I.CREATED_BY,I.CREATED_DATE) VALUES (IGRS_INSTRUMENT_MASTER_SEQ.NEXTVAL,?,?,?,'A',?,SYSDATE)";
    public static final String SELECT_INSTRUMENT = "SELECT I.INSTRUMENT_ID,I.INSTRUMENT_NAME,I.INSTRUMENT_DESCRIPTION,I.INSTRUMENT_STATUS,I.DEED_TYPE_ID FROM IGRS_DEED_INSTRUMENT_MASTER I WHERE I.INSTRUMENT_ID=?";
    public static final String UPDATE_INSTRUMENT = "UPDATE IGRS_DEED_INSTRUMENT_MASTER I SET I.INSTRUMENT_NAME=?,I.INSTRUMENT_DESCRIPTION=?,I.INSTRUMENT_STATUS=?,I.DEED_TYPE_ID=?I.UPDATE_BY=?,I.UPDATE_DATE=SYSDATE WHERE I.INSTRUMENT_ID=?";
    public static final String INSERT_EXEMPTION_MASTER = "INSERT INTO IGRS_DEED_EXEMPTION_MASTER E (E.EXEMPTION_ID,E.EXEMPTION_NAME,E.EXEMPTION_DESCRIPTION,E.DEED_TYPE_ID,E.INSTRUMENT_ID,E.EXEMPTION_STATUS,E.CREATED_BY,E.CREATED_DATE) VALUES (IGRS_EXEMPTION_MASTER_SEQ.NEXTVAL,?,?,?,?,'A',?,SYSDATE)";
    public static final String SELECT_EXEMPTION = "SELECT E.EXEMPTION_ID,E.EXEMPTION_NAME,E.EXEMPTION_DESCRIPTION,E.DEED_TYPE_ID,E.INSTRUMENT_ID,E.EXEMPTION_STATUS FROM IGRS_DEED_EXEMPTION_MASTER E WHERE E.EXEMPTION_ID=?";
    public static final String UPDATE_EXEMPTION = "UPDATE IGRS_DEED_EXEMPTION_MASTER E SET E.EXEMPTION_NAME=?,E.EXEMPTION_DESCRIPTION=?,E.EXEMPTION_STATUS=?,E.DEED_TYPE_ID=?,E.INSTRUMENT_ID=?,E.UPDATE_BY,E.UPDATE_DATE=SYSDATE WHERE E.EXEMPTION_ID=?";
}
