package com.wipro.igrs.formmptc27.sql;

public class FormMPTC27SQL {
	
	public static final String SELECT_ALL_EMP_ID = 
		" SELECT EMP_ID FROM IGRS_EMP_MASTER ";

	public static final String SELECT_EMP_BY_ID = 
		" SELECT e.EMP_ID, e.FIRST_NAME, e.MIDDLE_NAME, e.LAST_NAME, o.OFFICIATING, g.MIN_SALARY_SLAB, g.MAX_SALARY_SLAB, g.INCREMENT_AMOUNT, sb.COMPONENT_VALUE, " +
		" sm.SALARY_DATE, sb.EFFECTIVE_DATE, l.LEAVE_FROM, l.LEAVE_TO " +
		" FROM IGRS_EMP_MASTER e, IGRS_EMP_OFFICIAL_DETAILS o, IGRS_EMP_GRADE_CADRE_MAPPING gm, " +
		" IGRS_EMP_GRADE_MASTER g, IGRS_EMP_SALARY_BASIC_DTLS sb, IGRS_EMP_SALARY_MONTHLY_DTL sm,  " +
		" IGRS_EMP_LEAVE_DETAILS l " +
		" WHERE e.EMP_ID=? AND e.EMP_ID=o.EMP_ID AND e.EMP_ID=gm.EMP_ID AND gm.GRADE_ID=g.GRADE_ID AND e.EMP_ID=sb.EMP_ID " +
		" AND e.EMP_ID=sm.EMP_ID AND e.EMP_ID=l.EMP_ID ";
}
