package com.wipro.igrs.spotinspslabmaster.sql;

public class InspectioncreateCommonSQL {
	
	//constants
	
	public static final String SELECT_ALL_INSPECTIONS ="select SLAB_ID ,SLAB_MIN_RANGE,SLAB_MAX_RANGE,SLAB_STATUS,CREATED_BY,to_char(CREATED_DATE,'DD/MM/YYYY') CREATED_DATE  from IGRS_SPOT_INSP_SLAB_MASTER where SLAB_STATUS ='A' ORDER BY SLAB_MIN_RANGE ";
	public static final String SELECT_ALL_ACTIVE_INSPECTIONS ="select SLAB_ID ,SLAB_MIN_RANGE,SLAB_MAX_RANGE,SLAB_STATUS,CREATED_BY,to_char(CREATED_DATE,'DD/MM/YYYY') CREATED_DATE  from IGRS_SPOT_INSP_SLAB_MASTER where UPPER(SLAB_STATUS) ='A'  ORDER BY SLAB_MIN_RANGE ";
	//public static final String ADD_NEW_INSPECTION="insert into IGRS_SPOT_INSP_SLAB_MASTER(SLAB_ID,SLAB_MIN_RANGE,SLAB_MAX_RANGE,SLAB_STATUS,SLAB_PERCENTAGE,CREATED_BY,CREATED_DATE,UPDATE_BY,UPDATE_DATE,MIN_SPOT_INSP) values(?||IGRS_SPOT_INS_TXN_ID_SEQ.nextval,?,?,?,?,?,sysdate,?,sysdate,?)";
	//public static final String ADD_NEW_INSPECTION="insert into IGRS_SPOT_INSP_SLAB_MASTER(SLAB_ID,SLAB_MIN_RANGE,SLAB_MAX_RANGE,SLAB_STATUS,SLAB_PERCENTAGE,CREATED_BY,CREATED_DATE,UPDATE_BY,UPDATE_DATE,MIN_SPOT_INSP,SLAB_PERIOD_FROM,SLAB_PERIOD_TO,REMARKS,APPROVAL_STATUS) values(?||IGRS_SPOT_INS_TXN_ID_SEQ.nextval,?,?,?,?,?,sysdate,?,sysdate,?,?,?,?,'P')"; //Ramesh commented on 05 Jan 13
	public static final String ADD_NEW_INSPECTION="insert into IGRS_SPOT_INSP_SLAB_MASTER(SLAB_ID,SLAB_MIN_RANGE,SLAB_MAX_RANGE,SLAB_STATUS,CREATED_BY,CREATED_DATE,UPDATE_BY,UPDATE_DATE) values(?,?,?,?,?,sysdate,?,sysdate)";
	public static final String SELECT_INSPECTION_BY_ID="select SLAB_ID ,SLAB_MIN_RANGE,SLAB_MAX_RANGE,SLAB_STATUS,CREATED_BY,CREATED_DATE  from IGRS_SPOT_INSP_SLAB_MASTER where SLAB_ID=?";
	//SLAB_ID ,SLAB_MIN_RANGE,SLAB_MAX_RANGE,SLAB_STATUS,SLAB_PERCENTAGE,CREATED_BY,CREATED_DATE,UPDATE_BY,UPDATE_DATE ,MIN_SPOT_INSP,to_char(SLAB_PERIOD_FROM ,'DD/MM/YYYY') SLAB_PERIOD_FROM,to_char(SLAB_PERIOD_TO ,'DD/MM/YYYY') SLAB_PERIOD_TO,REMARKS 
	public static final String DELETE_INSPECTION_BY_ID="UPDATE IGRS_SPOT_INSP_SLAB_MASTER SET SLAB_STATUS='R' where SLAB_ID=?";
	public static final String UPDATE_INSPECTION="UPDATE IGRS_SPOT_INSP_SLAB_MASTER SET SLAB_MIN_RANGE=?,SLAB_MAX_RANGE=?,SLAB_STATUS=?,CREATED_BY=?,UPDATE_BY=?,UPDATE_DATE=sysdate where SLAB_ID=?";
	
	public static final String UPDATE_APPROVE_INSPECTION="UPDATE IGRS_SPOT_INSP_SLAB_MASTER SET APPROVAL_STATUS=?,APPROVED_REMARKS=?,APPROVAL_DATE=sysdate where SLAB_ID=?";
	
}
