package com.wipro.igrs.revenueManagement.sql;

public class RevenueMgtSQL {
	
	public static final String FUNCTION_QUERY = "Select FUNCTION_ID, FUNCTION_NAME from IGRS_FUNCTION_MASTER "+
                                                "WHERE FUNCTION_STATUS='A'";
	
	//BELOW CREATED BY ROOPAM ON 6 NOV 2013
	public static final String FUNCTION_QUERY_NEW = "Select FUNCTION_ID, FUNCTION_NAME from IGRS_FUNCTION_MASTER "+
    											"WHERE FUNCTION_STATUS='A' AND PAYMENT_FLAG IN ('Y','N')";
	
//	public static final String FUNCTION_QUERY_NEW_HINDI = "Select FUNCTION_ID, FUNCTION_NAME,FUNCTION_NAME_H from IGRS_FUNCTION_MASTER "+
//														"WHERE FUNCTION_STATUS='A' AND PAYMENT_FLAG IN ('Y','N')";
	
	public static final String SERVICE_QUERY = "SELECT t.SERVICE_ID, m.SERVICE_NAME   FROM IGRS_SERVICE_MASTER m, IGRS_FUNCTION_SERVICE_MAPPING t" +
			                                   "  WHERE t.SERVICE_ID=m.SERVICE_ID AND t.FUNCTION_ID=?";
	
	//public static final String SERVICE_QUERY_HINDI = "SELECT t.SERVICE_ID, m.SERVICE_NAME, m.SERVICE_NAME_H   FROM IGRS_SERVICE_MASTER m, IGRS_FUNCTION_SERVICE_MAPPING t" +
    //												"  WHERE t.SERVICE_ID=m.SERVICE_ID AND t.FUNCTION_ID=?";
	
	public static final String MAJOR_HEAD_QUERY = "Select REVENUE_MAJOR_HEAD, REVENUE_MAJOR_HEAD from IGRS_REVENUE_MAJOR_HEAD_MASTER "+
                                                  "WHERE REVENUE_MAJOR_HEAD_STATUS='A'";


	public static final String SUB_MAJOR_HEAD_QUERY = "Select REVENUE_SUB_MAJOR_HEAD, REVENUE_SUB_MAJOR_HEAD from IGRS_REVENUE_SBMJRHD_MASTER "+
                                                      "WHERE REVENUE_MAJOR_HEAD=? AND REVENUE_SUB_MAJOR_HEAD_STATUS='A'";
	
	//BELOW CREATED BY ROOPAM ON 6 NOV 2013
	public static final String SUB_MAJOR_HEAD_QUERY_NEW = "Select REVENUE_SUB_MAJOR_HEAD, REVENUE_SUB_MAJOR_HEAD from IGRS_REVENUE_SBMJRHD_MASTER "+
    												  "WHERE REVENUE_SUB_MAJOR_HEAD_STATUS='A'";

	public static final String MINOR_HEAD_QUERY = "Select REVENUE_MINOR_HEAD, REVENUE_MINOR_HEAD from IGRS_REVENUE_MINOR_HEAD_MASTER "+
                                                  "WHERE REVENUE_SUB_MAJOR_HEAD=? AND REVENUE_MINOR_HEAD_STATUS='A'";
	
	//BELOW CREATED BY ROOPAM ON 6 NOV 2013
	public static final String MINOR_HEAD_QUERY_NEW = "Select REVENUE_MINOR_HEAD, REVENUE_MINOR_HEAD from IGRS_REVENUE_MINOR_HEAD_MASTER "+
    											      "WHERE REVENUE_MINOR_HEAD_STATUS='A'";

	
	public static final String DEPENDENCY_QUERY = "Select PARAM_ID, PARAM_NAME from IGRS_FEE_PARAM_MASTER "+
                                                  "WHERE PARAM_STATUS='A' AND DEPENDENCY_FLG='Y'";

	public static final String OPERATOR_QUERY = "Select OPERATOR_ID, OPERATOR_NAME from IGRS_OPERATOR_MASTER "+
                                                "WHERE OPERATOR_STATUS='A'";

	
	public static final String YEAR_QUERY =     "Select CALENDAR_YEAR A, CALENDAR_YEAR B from IGRS_CALENDAR_YEAR "+
                                                "WHERE CALENDAR_YEAR_STATUS='A' ORDER BY A DESC";
	

	public static final String DISTRICT_QRY=  "SELECT DISTRICT_ID, DISTRICT_NAME FROM IGRS_DISTRICT_MASTER " +
			                                  "WHERE STATE_ID ='1' AND DISTRICT_STATUS ='A'";
	
	public static final String OFFICE_TYPE_DETAILS = "SELECT OFFICE_TYPE_ID,OFFICE_TYPE_NAME FROM IGRS_OFFICE_TYPE_MASTER WHERE ACTIVE_FLAG = 'A' ";
    
	
   public static final String OFFICE_NAME_DETAILS = "SELECT OFFICE_ID,OFFICE_NAME FROM IGRS_OFFICE_MASTER WHERE OFFICE_TYPE_ID =? AND DISTRICT_ID=? AND OFFICE_STATUS='A'";
	
   public static final String REPORT_QRY_DATE = "SELECT p.CHALLAN_SERIAL_NUMBER,TO_CHAR(p.CREATED_DATE,'dd/MM/yyyy hh:mi:ss AM'),p.FUNCTION_ID, f.FUNCTION_NAME,p.PAYMENT_MODE_ID, m.PAYMENT_MODE," +
   		                                        " p.OFFICE_ID, o.OFFICE_NAME,p.DISTRICT_ID, d.DISTRICT_NAME, p.CREATED_BY, TO_CHAR(p.CHALLAN_ONLINE_DATE,'dd/MM/yyyy hh:mi:ss AM'),p.PAID_AMOUNT,p.CHALLAN_AMOUNT,f.FUNCTION_NAME_H,m.PAYMENT_MODE_H,o.H_OFFICE_NAME,d.H_DISTRICT_NAME " +
   		                                        "FROM IGRS_PAYMENT_ECHALLAN_DETAILS p, IGRS_FUNCTION_MASTER f, IGRS_PAYMENT_MODE_MASTER m, IGRS_OFFICE_MASTER o, IGRS_DISTRICT_MASTER d " +
   		                                        "WHERE p.FUNCTION_ID=f.FUNCTION_ID AND p.OFFICE_ID=o.OFFICE_ID AND p.DISTRICT_ID=d.DISTRICT_ID AND " +
   		                                        "p.PAYMENT_MODE_ID = m.PAYMENT_MODE_ID AND p.PAYMENT_MODE_ID IN(?) AND TRUNC(p.CHALLAN_ONLINE_DATE)=TO_DATE(?,'dd/mm/yyyy')AND p.DISTRICT_ID=? AND p.OFFICE_ID=? order by p.CHALLAN_ONLINE_DATE desc";
   
   public static final String REPORT_QRY_WEEK_YEAR = "SELECT p.CHALLAN_SERIAL_NUMBER,TO_CHAR(p.CREATED_DATE,'dd/MM/yyyy hh:mi:ss AM'),p.FUNCTION_ID, f.FUNCTION_NAME,p.PAYMENT_MODE_ID, m.PAYMENT_MODE, " +
   		                                        "p.OFFICE_ID, o.OFFICE_NAME,p.DISTRICT_ID, d.DISTRICT_NAME, p.CREATED_BY, TO_CHAR(p.CHALLAN_ONLINE_DATE,'dd/MM/yyyy hh:mi:ss AM'), p.PAID_AMOUNT,p.CHALLAN_AMOUNT,f.FUNCTION_NAME_H,m.PAYMENT_MODE_H,o.H_OFFICE_NAME,d.H_DISTRICT_NAME " +
   		                                        "FROM IGRS_PAYMENT_ECHALLAN_DETAILS p, IGRS_FUNCTION_MASTER f, IGRS_PAYMENT_MODE_MASTER m, IGRS_OFFICE_MASTER o, IGRS_DISTRICT_MASTER d " +
   		                                        "WHERE p.FUNCTION_ID=f.FUNCTION_ID AND p.OFFICE_ID=o.OFFICE_ID AND p.DISTRICT_ID=d.DISTRICT_ID AND " +
   		                                        "p.PAYMENT_MODE_ID = m.PAYMENT_MODE_ID AND p.PAYMENT_MODE_ID IN(?) AND " +
   		                                        "(trunc(p.CHALLAN_ONLINE_DATE) BETWEEN TO_DATE(?,'dd/mm/yyyy') AND TO_DATE(?,'dd/mm/yyyy')) " +
   		                                        "AND p.DISTRICT_ID=? AND p.OFFICE_ID=? order by p.CHALLAN_ONLINE_DATE desc";
   
   
  public static final String SUM_QRY_WEEK_YEAR= "SELECT SUM(PAID_AMOUNT), SUM(CHALLAN_AMOUNT)FROM IGRS_PAYMENT_ECHALLAN_DETAILS WHERE " +
  		                                        "PAYMENT_MODE_ID=? AND(TRUNC(CHALLAN_ONLINE_DATE) BETWEEN TO_DATE(?,'dd/mm/yyyy') AND TO_DATE(?,'dd/mm/yyyy')) " +
  		                                        "AND DISTRICT_ID=? AND OFFICE_ID=?";
  
  public static final String SUM_QRY_DATE= "SELECT SUM(PAID_AMOUNT),SUM(CHALLAN_AMOUNT)FROM IGRS_PAYMENT_ECHALLAN_DETAILS WHERE " +
                                           "PAYMENT_MODE_ID=? AND TRUNC(CHALLAN_ONLINE_DATE)=TO_DATE(?,'dd/mm/yyyy') " +
                                           "AND DISTRICT_ID=? AND OFFICE_ID=?";
  
  //added by SHREERAJ FOR ADVANCE PAYMENT
  public static final String LICENSE_NUMBER_DETAILS = "SELECT S.LICENSE_NUMBER,T.SP_TYPE_NAME,S.LICENSE_FROM_DATE,S.LICENSE_TO_DATE, S.SP_TYPE_ID FROM IGRS_SP_DETLS S,IGRS_SP_TYPE_MASTER T" +
		  												" WHERE S.STATUS='A' AND S.SP_TYPE_ID=T.SP_TYPE_ID AND S.APPLCTN_STATUS='8' AND S.LICENSE_NUMBER=?";
 
  public static final String LICENSE_NUMBER_DETAILS_DURATION = "SELECT S.LICENSE_NUMBER,T.SP_TYPE_NAME,S.LICENSE_FROM_DATE,S.LICENSE_TO_DATE, S.SP_TYPE_ID FROM IGRS_SP_DETLS S, IGRS_SP_TYPE_MASTER T " +
		  														" WHERE S.SP_TYPE_ID=T.SP_TYPE_ID and S.STATUS='A' AND S.APPLCTN_STATUS='8' and TRUNC(S.UPDATE_DATE) BETWEEN TO_DATE(?,'dd/mm/yyyy')AND TO_DATE(?,'dd/mm/yyyy')";
  
  public static final String FULL_NAME_INDIVIDUAL = "SELECT FIRST_NAME||' '||MIDDLE_NAME||' '||LAST_NAME name FROM IGRS_USER_REG_DETAILS WHERE USER_ID="
		  										   +" (SELECT CREATED_BY FROM IGRS_SP_DETLS WHERE APPLCTN_STATUS='8' AND STATUS='A' AND LICENSE_NUMBER=? AND SP_TYPE_ID='1')";
  
 // public static final String FULL_NAME_BANK ="select distinct BANK_NAME from IGRS_SP_DETLS where APPLCTN_STATUS='8' AND STATUS='A' AND SP_TYPE_ID IN(2,3,4) ANDLICENSE_NUMBER=? ";
  
  public static final String ACC_BAL_SP_ESATMP= "SELECT distinct nvl(ACCOUNT_BAL,0) FROM IGRS_CREDIT_LIMIT_TXN_ESTAMP WHERE LICENSE_NO=? and  PAYMENT_FLAG='C' AND UPDATE_DATE=(SELECT MAX(UPDATE_DATE) FROM IGRS_CREDIT_LIMIT_TXN_ESTAMP  where LICENSE_NO=? and PAYMENT_FLAG='C')";

  public static final String ACC_BAL_SP_OTHERS= "SELECT distinct nvl(ACCOUNT_BAL,0) FROM IGRS_CREDIT_LIMIT_TXN_LOG WHERE LICENSE_NO=? and  PAYMENT_FLAG='C' AND UPDATE_DATE=(SELECT MAX(UPDATE_DATE) FROM IGRS_CREDIT_LIMIT_TXN_LOG  where LICENSE_NO=? and PAYMENT_FLAG='C')";

  public static final String AUTHO_NAME_SP = "SELECT DISTINCT BANK_NAME FROM IGRS_SP_DETLS WHERE  LICENSE_NUMBER=? AND STATUS='A' AND APPLCTN_STATUS='8' AND SP_TYPE_ID IN (2,3,4) ";

  public static final String SELECT_SP_ACCOUNT_STMT_ESTAMP="select TO_CHAR(TRANSACTION_DATE,'DD/MM/YYYY hh:mi:ss AM'),"
			+" PAYMENT_TXN_ID,iptm.PAYMENT_MODE,CREDIT_OR_DEBIT ,ROUND(PAID_AMOUNT,2),"
			+" FUNCTION_NAME,round(ACCOUNT_BAL,2),nvl(round(SP_COMM,2),0) from IGRS_CREDIT_LIMIT_TXN_ESTAMP icltl,"
			+" IGRS_FUNCTION_MASTER ifm,IGRS_PAYMENT_MODE_MASTER iptm"
			+" where ifm.FUNCTION_ID=icltl.FUNCTION_ID and icltl.PAYMENT_MODE_ID=iptm.PAYMENT_MODE_ID"
			+" and icltl.LICENSE_NO=? AND icltl.PAYMENT_FLAG='C'";
  
  public static final String SELECT_SP_ACCOUNT_STMT_OTHERS="select TO_CHAR(TRANSACTION_DATE,'DD/MM/YYYY hh:mi:ss AM'),"
		+" PAYMENT_TXN_ID,iptm.PAYMENT_MODE,CREDIT_OR_DEBIT ,ROUND(PAID_AMOUNT,2),"
		+" FUNCTION_NAME,round(ACCOUNT_BAL,2),nvl(round(SP_COMM,2),0) from IGRS_CREDIT_LIMIT_TXN_LOG icltl,"
		+" IGRS_FUNCTION_MASTER ifm,IGRS_PAYMENT_MODE_MASTER iptm"
		+" where ifm.FUNCTION_ID=icltl.FUNCTION_ID and icltl.PAYMENT_MODE_ID=iptm.PAYMENT_MODE_ID"
		+" and icltl.LICENSE_NO=? AND icltl.PAYMENT_FLAG='C'";
  
  //FOLLOWING CREATED BY ROOPAM
  public static final String UPDATE_MATRIX = "UPDATE IGRS_FUNCTION_SERVICE_MAPPING SET UPDATE_BY=?,UPDATE_DATE=sysdate,REVENUE_MAJOR_HEAD=?,REVENUE_SUB_MAJOR_HEAD=?,REVENUE_MINOR_HEAD=?,FEE_RU=?,FEE_SP=?,FEE_DR=? WHERE FUNCTION_ID=? AND SERVICE_ID=?";
  public static final String GET_MATRIX_VIEW = "SELECT A.MAPPING_ID, A.FUNCTION_ID,B.FUNCTION_NAME,A.SERVICE_ID,C.SERVICE_NAME,A.REVENUE_MAJOR_HEAD,A.REVENUE_SUB_MAJOR_HEAD,A.REVENUE_MINOR_HEAD,A.FEE_RU,A.FEE_SP,A.FEE_DR FROM IGRS_FUNCTION_SERVICE_MAPPING A, IGRS_FUNCTION_MASTER B, IGRS_SERVICE_MASTER C WHERE A.FUNCTION_ID=B.FUNCTION_ID AND A.SERVICE_ID=C.SERVICE_ID";
  
  public static final String DISTRICT_QRY_HINDI=  "SELECT DISTRICT_ID, DISTRICT_NAME,H_DISTRICT_NAME FROM IGRS_DISTRICT_MASTER " +
  "WHERE STATE_ID ='1' AND DISTRICT_STATUS ='A' ORDER BY DISTRICT_NAME ASC";
  
  public static final String OFFICE_TYPE_DETAILS_HINDI = "SELECT OFFICE_TYPE_ID,OFFICE_TYPE_NAME,OFFICE_TYPE_NAME_H FROM IGRS_OFFICE_TYPE_MASTER WHERE ACTIVE_FLAG = 'A' ORDER BY OFFICE_TYPE_NAME ASC";
  
  public static final String OFFICE_NAME_DETAILS_HINDI = "SELECT OFFICE_ID,OFFICE_NAME,H_OFFICE_NAME FROM IGRS_OFFICE_MASTER WHERE OFFICE_TYPE_ID =? AND DISTRICT_ID=? AND OFFICE_STATUS='A' ORDER BY OFFICE_NAME ASC";
  
  //public static final String GET_MATRIX_VIEW_HINDI = "SELECT A.MAPPING_ID, A.FUNCTION_ID,B.FUNCTION_NAME,A.SERVICE_ID,C.SERVICE_NAME,A.REVENUE_MAJOR_HEAD,A.REVENUE_SUB_MAJOR_HEAD,A.REVENUE_MINOR_HEAD,A.FEE_RU,A.FEE_SP,A.FEE_DR,B.FUNCTION_NAME_H,C.SERVICE_NAME_H FROM IGRS_FUNCTION_SERVICE_MAPPING A, IGRS_FUNCTION_MASTER B, IGRS_SERVICE_MASTER C WHERE A.FUNCTION_ID=B.FUNCTION_ID AND A.SERVICE_ID=C.SERVICE_ID";
  
  public static final String LICENSE_NUMBER_DETAILS_HINDI = "SELECT S.LICENSE_NUMBER,T.SP_TYPE_NAME,S.LICENSE_FROM_DATE,S.LICENSE_TO_DATE, S.SP_TYPE_ID,T.H_SP_TYPE_NAME FROM IGRS_SP_DETLS S,IGRS_SP_TYPE_MASTER T" +
	" WHERE S.STATUS='A' AND S.SP_TYPE_ID=T.SP_TYPE_ID AND S.APPLCTN_STATUS='8' AND S.LICENSE_NUMBER=?";
  
  public static final String LICENSE_NUMBER_DETAILS_DURATION_HINDI = "SELECT S.LICENSE_NUMBER,T.SP_TYPE_NAME,S.LICENSE_FROM_DATE,S.LICENSE_TO_DATE, S.SP_TYPE_ID,T.H_SP_TYPE_NAME FROM IGRS_SP_DETLS S, IGRS_SP_TYPE_MASTER T " +
	" WHERE S.SP_TYPE_ID=T.SP_TYPE_ID and S.STATUS='A' AND S.APPLCTN_STATUS='8' and TRUNC(S.UPDATE_DATE) BETWEEN TO_DATE(?,'dd/mm/yyyy')AND TO_DATE(?,'dd/mm/yyyy')";
  
  public static final String SELECT_SP_ACCOUNT_STMT_ESTAMP_HINDI="select TO_CHAR(TRANSACTION_DATE,'DD/MM/YYYY hh:mi:ss AM'),"
		+" PAYMENT_TXN_ID,iptm.PAYMENT_MODE,CREDIT_OR_DEBIT ,ROUND(PAID_AMOUNT,2),"
		+" FUNCTION_NAME,round(ACCOUNT_BAL,2),nvl(round(SP_COMM,2),0),FUNCTION_NAME_H,iptm.PAYMENT_MODE_H from IGRS_CREDIT_LIMIT_TXN_ESTAMP icltl,"
		+" IGRS_FUNCTION_MASTER ifm,IGRS_PAYMENT_MODE_MASTER iptm"
		+" where ifm.FUNCTION_ID=icltl.FUNCTION_ID and icltl.PAYMENT_MODE_ID=iptm.PAYMENT_MODE_ID"
		+" and icltl.LICENSE_NO=? AND icltl.PAYMENT_FLAG='C'";

public static final String SELECT_SP_ACCOUNT_STMT_OTHERS_HINDI="select TO_CHAR(TRANSACTION_DATE,'DD/MM/YYYY hh:mi:ss AM'),"
	+" PAYMENT_TXN_ID,iptm.PAYMENT_MODE,CREDIT_OR_DEBIT ,ROUND(PAID_AMOUNT,2),"
	+" FUNCTION_NAME,round(ACCOUNT_BAL,2),nvl(round(SP_COMM,2),0),FUNCTION_NAME_H,iptm.PAYMENT_MODE_H from IGRS_CREDIT_LIMIT_TXN_LOG icltl,"
	+" IGRS_FUNCTION_MASTER ifm,IGRS_PAYMENT_MODE_MASTER iptm"
	+" where ifm.FUNCTION_ID=icltl.FUNCTION_ID and icltl.PAYMENT_MODE_ID=iptm.PAYMENT_MODE_ID"
	+" and icltl.LICENSE_NO=? AND icltl.PAYMENT_FLAG='C'";

public static final String REPORT_QRY_DATE_CASH = "  SELECT p.CHALLAN_SERIAL_NUMBER,TO_CHAR(p.CREATED_DATE,'dd/MM/yyyy hh:mi:ss AM'),p.PAYMENT_MODE_ID, m.PAYMENT_MODE,"+
   "p.OFFICE_ID, o.OFFICE_NAME,p.DISTRICT_ID, d.DISTRICT_NAME, p.CREATED_BY, TO_CHAR(p.CHALLAN_ONLINE_DATE,'dd/MM/yyyy hh:mi:ss AM'),p.PAID_AMOUNT,p.CHALLAN_AMOUNT,m.PAYMENT_MODE_H,o.H_OFFICE_NAME,d.H_DISTRICT_NAME "+ 
   "FROM IGRS_PAYMENT_ECHALLAN_DETAILS p, IGRS_PAYMENT_MODE_MASTER m, IGRS_OFFICE_MASTER o, IGRS_DISTRICT_MASTER d "+ 
   "WHERE p.OFFICE_ID=o.OFFICE_ID AND p.DISTRICT_ID=d.DISTRICT_ID AND "+ 
   "p.PAYMENT_MODE_ID = m.PAYMENT_MODE_ID AND p.PAYMENT_MODE_ID=? AND TRUNC(p.CHALLAN_ONLINE_DATE)=TO_DATE(?,'dd/mm/yyyy')AND p.DISTRICT_ID=? AND p.OFFICE_ID=? order by p.CHALLAN_ONLINE_DATE desc";

public static final String REPORT_QRY_WEEK_YEAR_CASH = " SELECT p.CHALLAN_SERIAL_NUMBER,TO_CHAR(p.CREATED_DATE,'dd/MM/yyyy hh:mi:ss AM'),p.PAYMENT_MODE_ID, m.PAYMENT_MODE,"+
   "p.OFFICE_ID, o.OFFICE_NAME,p.DISTRICT_ID, d.DISTRICT_NAME, p.CREATED_BY, TO_CHAR(p.CHALLAN_ONLINE_DATE,'dd/MM/yyyy hh:mi:ss AM'), p.PAID_AMOUNT,p.CHALLAN_AMOUNT,m.PAYMENT_MODE_H,o.H_OFFICE_NAME,d.H_DISTRICT_NAME "+ 
   "FROM IGRS_PAYMENT_ECHALLAN_DETAILS p, IGRS_PAYMENT_MODE_MASTER m, IGRS_OFFICE_MASTER o, IGRS_DISTRICT_MASTER d "+
   "WHERE p.OFFICE_ID=o.OFFICE_ID AND p.DISTRICT_ID=d.DISTRICT_ID AND "+
   "p.PAYMENT_MODE_ID = m.PAYMENT_MODE_ID AND p.PAYMENT_MODE_ID=? AND "+
   "(trunc(p.CHALLAN_ONLINE_DATE) BETWEEN TO_DATE(?,'dd/mm/yyyy') AND TO_DATE(?,'dd/mm/yyyy')) "+ 
   "AND p.DISTRICT_ID=? AND p.OFFICE_ID=? order by p.CHALLAN_ONLINE_DATE desc";

/*public static final String REPORT_QRY_WEEK_YEAR_CASH = "select p.TRANSACTION_ID, TO_CHAR(p.CREATED_DATE,'dd/MM/yyyy hh:mi:ss AM'),p.PAYMENT_TYPE_ID, m.PAYMENT_MODE,"
	+" p.OFFICE_ID, o.OFFICE_NAME,p.DISTRICT_ID, d.DISTRICT_NAME, p.CREATED_BY, TO_CHAR(p.CHALLAN_ONLINE_DATE,'dd/MM/yyyy hh:mi:ss AM'),p.GROSS_AMOUNT, p.NET_AMOUNT,m.PAYMENT_MODE_H,o.H_OFFICE_NAME,d.H_DISTRICT_NAME" 
	+" FROM IGRS_PAYMENT_MODE_DETAILS p, IGRS_PAYMENT_MODE_MASTER m, IGRS_OFFICE_MASTER o, IGRS_DISTRICT_MASTER d "
	+" WHERE p.OFFICE_ID=o.OFFICE_ID AND p.DISTRICT_ID=d.DISTRICT_ID AND "
	+" p.PAYMENT_TYPE_ID = m.PAYMENT_MODE_ID AND p.PAYMENT_TYPE_ID=? AND "
	+" (trunc(p.CHALLAN_ONLINE_DATE) BETWEEN TO_DATE(?,'dd/mm/yyyy') AND TO_DATE(?,'dd/mm/yyyy'))" 
	+" AND p.DISTRICT_ID=? AND p.OFFICE_ID=? order by p.CHALLAN_ONLINE_DATE desc";*/

public static final String FUNCTION_QUERY_NEW_HINDI = "Select F.FUNCTION_ID, UPPER(F.FUNCTION_NAME) , F.FUNCTION_NAME_H from IGRS_FUNCTION_MASTER F, IGRS_FUNCTION_SERVICE_MAPPING S WHERE F.FUNCTION_STATUS='A' AND S.MAPPING_STATUS='A' AND S.FUNCTION_ID=F.FUNCTION_ID AND (S.REVENUE_MAJOR_HEAD IS NULL OR S.REVENUE_MAJOR_HEAD='') ORDER BY F.FUNCTION_NAME";

public static final String SERVICE_QUERY_HINDI = "SELECT t.SERVICE_ID, m.SERVICE_NAME, m.SERVICE_NAME_H, t.CAPTURE_FEE,t.FEE_BASED_ON,t.FEE_BASED_ON_H FROM IGRS_SERVICE_MASTER m, IGRS_FUNCTION_SERVICE_MAPPING t WHERE t.SERVICE_ID=m.SERVICE_ID AND t.FUNCTION_ID=?";

public static final String GET_MATRIX_VIEW_HINDI = "SELECT A.MAPPING_ID, A.FUNCTION_ID,UPPER(B.FUNCTION_NAME),A.SERVICE_ID,UPPER(C.SERVICE_NAME),A.REVENUE_MAJOR_HEAD,A.REVENUE_SUB_MAJOR_HEAD,A.REVENUE_MINOR_HEAD,A.FEE_RU,A.FEE_SP,A.FEE_DR,B.FUNCTION_NAME_H,C.SERVICE_NAME_H,A.CAPTURE_FEE,A.FEE_BASED_ON,A.FEE_BASED_ON_H FROM IGRS_FUNCTION_SERVICE_MAPPING A, IGRS_FUNCTION_MASTER B, IGRS_SERVICE_MASTER C WHERE A.FUNCTION_ID=B.FUNCTION_ID AND A.SERVICE_ID=C.SERVICE_ID AND A.MAPPING_STATUS='A' AND A.REVENUE_MAJOR_HEAD IS NOT NULL ORDER BY B.FUNCTION_NAME";
  

}
