/**
 * 
 */
package com.wipro.igrs.revenueManagement.sql;

/**
 * @author RA836784
 *
 */
public class RevMgtSQL {
	
////t.TRANSACTION_ID, t.AMOUNT_PAID, t.CREATED_DATE
//	
//public static final String VIEW_DETLS_QRY ="SELECT *" +
//			" FROM IGRS_PAYMENT_TXN_DETLS t" +
//			" WHERE 1=1 AND (PAYMENT_TYPE_ID=?) " +
//			" OR (t.AMOUNT_PAID=? OR" +
//			" t.TRANSACTION_ID=?" +
//			" OR(t.CREATED_DATE BETWEEN TO_DATE(?, 'dd/mm/yyyy')-1 AND TO_DATE(?, 'dd/mm/yyyy')+1) " ;
//			
//			//" AND t.PROPERTY_LOCK_ID NOT IN(SELECT PROPERTY_LOCK_ID FROM IGRS_PROP_LOCK_TXN_DETLS WHERE LOCK_DATE IS NULL AND RELEASE_DATE IS NULL AND (LOCK_STATUS_ID='1' OR LOCK_STATUS_ID='2'))";
//
//public static final String VIEW_RECEIPT_ID="SELECT PAYMENT_MODE_TXN_ID FROM IGRS_PAYMENT_TXN_MAP WHERE PAYMENT_TXN_ID=? ";
////public static final String VIEW_RELEASE_DATE= "SELECT TO_CHAR(RELEASE_DATE,'dd/MM/yyyy hh:mi:ss AM') FROM IGRS_PROP_LOCK_TXN_DETLS WHERE PROPERTY_LOCK_ID=? AND LOCK_STATUS_ID =?";
//
//


/*public static final String VIEW_DETLS_QRY	="SELECT t.TRANSACTION_ID, u.PAYMENT_MODE_TXN_ID, t.CREATED_DATE, t.AMOUNT_PAID , t.PAYMENT_TYPE_ID ,t.PAYMENT_PURPOSE,t.USER_ID" +
                                           "FROM IGRS_PAYMENT_TXN_DETLS t, IGRS_PAYMENT_TXN_MAP m" +
	"where " +
		"t.PAYMNET_TYPE_ID=? "+ 
		"AND t.CREATED_DATE BETWEEN NVL(TO_DATE(?,'DD/MM/YYYY'), t.CREATED_DATE) AND NVL(TO_DATE(?,'DD/MM/YYYY'),t.CREATED_DATE) " +
		"AND m.PAYMENT_MODE_TXN_ID =NVL(?,m.PAYMENT_MODE_TXN_ID) "+
		"AND t.TRANSACTION_ID=NVL(?,t.TRANSACTION_ID)"+
		"AND t.TRANSACTION_ID=m.TRANSACTION_ID";

*/
//public static final String VIEW_RECEIPT_ID ="SELECT *" +
	

/*//public static final String VIEW_DETLS_QRY ="SELECT t.PROPERTY_LOCK_ID, t.REGISTRATION_NUMBER, t.PROPERTY_TXN_ID, m.LOCK_STATUS_NAME,t.LOCK_STATUS_ID  " +
		" FROM IGRS_PROP_LOCK_TXN_DETLS t, IGRS_PROP_LOCK_STATUS_MASTER m " +
		" WHERE m.LOCK_STATUS_ID=t.LOCK_STATUS_ID AND (t.LOCK_STATUS_ID='1' OR t.LOCK_STATUS_ID='2') " +
		" AND(t.PROPERTY_LOCK_ID=? OR" +
		" t.REGISTRATION_NUMBER=? OR t.LOCK_STATUS_ID=? " +
		" OR(t.LOCK_DATE BETWEEN TO_DATE(?, 'dd/mm/yyyy')-1 AND TO_DATE(?, 'dd/mm/yyyy')+1) " +
		" OR(t.RELEASE_DATE BETWEEN TO_DATE(?, 'dd/mm/yyyy')-1 AND TO_DATE(?, 'dd/mm/yyyy')+1)) "+
		" AND t.PROPERTY_LOCK_ID NOT IN(SELECT PROPERTY_LOCK_ID FROM IGRS_PROP_LOCK_TXN_DETLS WHERE LOCK_DATE IS NULL AND RELEASE_DATE IS NULL AND (LOCK_STATUS_ID='1' OR LOCK_STATUS_ID='2'))";*/

		/*public static final String VIEW_DETLS_QRY	="SELECT TRANSACTION_ID, AMOUNT_PAID ,CREATED_DATE, PAYMENT_TYPE_ID ,PAYMENT_PURPOSE,USER_ID,DISTRICT_ID,OFFICE_ID" +
        " FROM IGRS_PAYMENT_TXN_DETAILS  " +
"where " +
"PAYMENT_TYPE_ID=? "+ 
"OR ( (CREATED_DATE BETWEEN TO_DATE(?, 'dd/mm/yyyy')-1 AND TO_DATE(?, 'dd/mm/yyyy')+1) " + 
"OR TRANSACTION_ID=? ) " ;
*/

		
	/*	
		//for credit limit
		
		public static final String VIEW_DETLS_QRY = "SELECT T.TRANSACTION_ID,T.AMOUNT_PAID ,TO_CHAR(T.CREATED_DATE,'dd/MM/yyyy hh:mi:ss AM'),"+
				 " T.PAYMENT_PURPOSE,T.USER_ID, "+
				 " T.DISTRICT_ID,T.OFFICE_ID ,F.FUNCTION_NAME,O.OFFICE_NAME,D.DISTRICT_NAME"+
				 " FROM IGRS_PAYMENT_TXN_DETAILS T ,IGRS_FUNCTION_MASTER F,IGRS_OFFICE_MASTER O,IGRS_DISTRICT_MASTER D"+
				" WHERE T.PAYMENT_PURPOSE=F.FUNCTION_ID"+
				" AND T.OFFICE_ID =O.OFFICE_ID"+
				" AND T.DISTRICT_ID =D.DISTRICT_ID"+
			    " AND T.PAYMENT_TYPE_ID=?"+
				" OR (T.CREATED_DATE BETWEEN TO_DATE(?, 'dd/mm/yyyy')-1 AND TO_DATE(?, 'dd/mm/yyyy')+1)"+
				" OR T.TRANSACTION_ID=?"; */
		
		
		//For Cash/Challan/Online Transaction Mapping
		
public static final String GET_SEARCH_DETAILS_QUERY = 
			

 "SELECT T.TRANSACTION_ID,T.AMOUNT_PAID ,TO_CHAR(T.CREATED_DATE,'dd/MM/yyyy hh:mi:ss AM'),"+
		 " T.PAYMENT_PURPOSE,T.USER_ID, "+
		 " T.DISTRICT_ID,T.OFFICE_ID ,F.FUNCTION_NAME,O.OFFICE_NAME,D.DISTRICT_NAME,M.PAYMENT_MODE_TXN_ID"+
		 " FROM IGRS_PAYMENT_TXN_DETAILS T ,IGRS_FUNCTION_MASTER F,IGRS_OFFICE_MASTER O,IGRS_DISTRICT_MASTER D,IGRS_PAYMENT_TXN_MAP M"+
		" where 1=1  AND T.PAYMENT_PURPOSE=F.FUNCTION_ID"+
		" AND T.OFFICE_ID =O.OFFICE_ID"+
		" AND T.DISTRICT_ID =D.DISTRICT_ID"+
		" AND T.TRANSACTION_ID=M.PAYMENT_TXN_ID";

     // For Cash/Online/Challan/Credit Limit Transaction Mapping
	
	public static final String TRANSACTION_QUERY_PAYMENTID_CLAUSE="  AND T.PAYMENT_TYPE_ID=?";
	public static final String TRANSACTION_QUERY_OFFICEID_CLAUSE = " and district_id = (select district_id from IGRS_OFFICE_MASTER where office_id=?)";
	public static final String TRANSACTION_QUERY_TXNID_CLAUSE = " AND T.TRANSACTION_ID=?";
	public static final String TRANSACTION_QUERY_PAYMENT_PURPOSE_CLAUSE = " AND T.PAYMENT_PURPOSE=?";
	public static final String TRANSACTION_QUERY_DATE_BOTH_CLAUSE = " AND (T.CREATED_DATE BETWEEN TO_DATE(?,'DD/MM/YYYY') AND TO_DATE(?,'DD/MM/YYYY')+1)";
	public static final String TRANSACTION_ORDER_BY_DATE_CLAUSE = " ORDER BY T.CREATED_DATE DESC";
		
	
		
		//For Credit Limit Transaction Mapping
	
	public static final String GET_SEARCH_DETAILS_QUERY1 = 
			

			 "SELECT T.TRANSACTION_ID,T.AMOUNT_PAID ,TO_CHAR(T.CREATED_DATE,'dd/MM/yyyy hh:mi:ss AM'),"+
					 " T.PAYMENT_PURPOSE,T.USER_ID, "+
					 " T.DISTRICT_ID,T.OFFICE_ID ,F.FUNCTION_NAME,O.OFFICE_NAME,D.DISTRICT_NAME"+
					 " FROM IGRS_PAYMENT_TXN_DETAILS T ,IGRS_FUNCTION_MASTER F,IGRS_OFFICE_MASTER O,IGRS_DISTRICT_MASTER D"+
					" where 1=1  AND T.PAYMENT_PURPOSE=F.FUNCTION_ID"+
					" AND T.OFFICE_ID =O.OFFICE_ID"+
					" AND T.DISTRICT_ID =D.DISTRICT_ID";
					

		
		
		
		
	//For Cash Receipt Search
	
	public static final String GET_CASH_DETAILS_RECEIPT_SEARCH = 
				

	/* "SELECT M.TRANSACTION_ID,M.GROSS_AMOUNT,TO_CHAR(M.CREATED_DATE,'dd/MM/yyyy hh:mi:ss AM'),"+
			 " (SELECT OFFICE_NAME FROM IGRS_OFFICE_MASTER O WHERE O.OFFICE_ID=M.OFFICE_ID), "+
			 " (SELECT FUNCTION_NAME FROM IGRS_FUNCTION_MASTER F WHERE F.FUNCTION_ID=M.FUNCTION_ID), "+
			 " (SELECT U.FIRST_NAME||' '||U.MIDDLE_NAME||' '||U.LAST_NAME FROM IGRS_USER_REG_DETAILS U WHERE M.CREATED_BY=U.USER_ID"+
			 "FROM  IGRS_PAYMENT_MODE_DETAILS M"+
			" where 1=1  AND LOWER(M.TRANSACTION_ID)=?  ";
			*/

			" SELECT M.TRANSACTION_ID,M.GROSS_AMOUNT,TO_CHAR(M.CREATED_DATE,'dd/MM/yyyy hh:mi:ss AM'),"+
			 " M.OFFICE_ID, M.FUNCTION_ID, M.CREATED_BY , O.OFFICE_NAME, F.FUNCTION_NAME,U.USER_ID,"+
			  " U.FIRST_NAME||' '||U.MIDDLE_NAME||' '||U.LAST_NAME , M.STATUS_FLAG " +
			" FROM IGRS_PAYMENT_MODE_DETAILS M,IGRS_OFFICE_MASTER O,IGRS_FUNCTION_MASTER F, IGRS_USER_REG_DETAILS U"+
			" WHERE M.OFFICE_ID   =O.OFFICE_ID"+
			" AND M.FUNCTION_ID   =F.FUNCTION_ID"+
			" AND M.CREATED_BY    =U.USER_ID"+
			" AND LOWER(M.TRANSACTION_ID)=?";
		
		
	
	//For CHALLAN Receipt Search
	
	public static final String GET_CHALLAN_DETAILS_RECEIPT_SEARCH = 
			" SELECT M.CHALLAN_SERIAL_NUMBER,M.PAID_AMOUNT,TO_CHAR(M.CREATED_DATE,'dd/MM/yyyy hh:mi:ss AM'), "+
			" M.OFFICE_ID, M.FUNCTION_ID, M.CREATED_BY , O.OFFICE_NAME, F.FUNCTION_NAME,U.USER_ID, "+
			" U.FIRST_NAME||' '||U.MIDDLE_NAME||' '||U.LAST_NAME , M.STATUS_FLAG"+
			" FROM IGRS_PAYMENT_ECHALLAN_DETAILS M,IGRS_OFFICE_MASTER O,IGRS_FUNCTION_MASTER F, IGRS_USER_REG_DETAILS U "+
			" WHERE M.OFFICE_ID   =O.OFFICE_ID "+
			" AND M.FUNCTION_ID   =F.FUNCTION_ID "+
			" AND M.CREATED_BY    =U.USER_ID "+
			" AND LOWER(M.CHALLAN_SERIAL_NUMBER)=? AND PAYMENT_MODE_ID=?";
					
	//For ONLINE Receipt Search
	
		public static final String GET_ONLINE_DETAILS_RECEIPT_SEARCH = 
				" SELECT M.CHALLAN_SERIAL_NUMBER,M.PAID_AMOUNT,TO_CHAR(M.CREATED_DATE,'dd/MM/yyyy hh:mi:ss AM'), "+
				" M.OFFICE_ID, M.FUNCTION_ID, M.CREATED_BY , O.OFFICE_NAME, F.FUNCTION_NAME,U.USER_ID, "+
				" U.FIRST_NAME||' '||U.MIDDLE_NAME||' '||U.LAST_NAME , M.STATUS_FLAG"+
				" FROM IGRS_PAYMENT_ECHALLAN_DETAILS M,IGRS_OFFICE_MASTER O,IGRS_FUNCTION_MASTER F, IGRS_USER_REG_DETAILS U "+
				" WHERE M.OFFICE_ID   =O.OFFICE_ID "+
				" AND M.FUNCTION_ID   =F.FUNCTION_ID "+
				" AND M.CREATED_BY    =U.USER_ID "+
				" AND LOWER(M.CHALLAN_SERIAL_NUMBER)=? AND PAYMENT_MODE_ID=?";
		
		//For Revenue Collection Reports
		
		
		// To populate district , office type, office name
		public static final String DISTRICT_QRY=  "SELECT DISTRICT_ID, DISTRICT_NAME FROM IGRS_DISTRICT_MASTER " +
                "WHERE STATE_ID ='1' AND DISTRICT_STATUS ='A'";

public static final String OFFICE_TYPE_DETAILS = "SELECT OFFICE_TYPE_ID,OFFICE_TYPE_NAME FROM IGRS_OFFICE_TYPE_MASTER WHERE ACTIVE_FLAG = 'A' ";


public static final String OFFICE_NAME_DETAILS = "SELECT OFFICE_ID,OFFICE_NAME FROM IGRS_OFFICE_MASTER WHERE OFFICE_TYPE_ID =? AND DISTRICT_ID=? AND OFFICE_STATUS='A'";

//For Search Criteria Of Cash Revenue Collection Report 

public static final String CASH_REVENUE_COLLECTION_REPORT_QRY = " SELECT M.TRANSACTION_ID,TO_CHAR(M.CREATED_DATE,'dd/MM/yyyy hh:mi:ss AM'),M.FUNCTION_ID, F.FUNCTION_NAME,M.PAYMENT_TYPE_ID, "+
         " M.CREATED_BY , M.GROSS_AMOUNT " +
           " FROM IGRS_PAYMENT_MODE_DETAILS M, IGRS_FUNCTION_MASTER F "+
           " WHERE M.FUNCTION_ID=F.FUNCTION_ID AND  M.DISTRICT_ID=? AND M.OFFICE_ID=? AND (M.CREATED_DATE BETWEEN TO_DATE(?,'DD/MM/YYYY') AND TO_DATE(?,'DD/MM/YYYY')+1) " ;
           
//For Search Criteria Of Challan Revenue Collection Report 

public static final String CHALLAN_REVENUE_COLLECTION_REPORT_QRY = " SELECT M.CHALLAN_SERIAL_NUMBER,TO_CHAR(M.UPDATE_DATE,'dd/MM/yyyy hh:mi:ss AM'),M.FUNCTION_ID, F.FUNCTION_NAME,M.PAYMENT_MODE_ID,PM.PAYMENT_MODE ,M.CREATED_BY , M.CHALLAN_AMOUNT "+
 " FROM IGRS_PAYMENT_ECHALLAN_DETAILS M, IGRS_FUNCTION_MASTER F ,IGRS_PAYMENT_MODE_MASTER PM "+
 " WHERE M.FUNCTION_ID=F.FUNCTION_ID AND M.PAYMENT_MODE_ID=PM.PAYMENT_MODE_ID AND  M.DISTRICT_ID=? AND M.OFFICE_ID=? AND (M.UPDATE_DATE BETWEEN TO_DATE(?,'DD/MM/YYYY') AND TO_DATE(?,'DD/MM/YYYY')+1) AND  M.PAYMENT_MODE_ID=?";
         
//For Search Criteria Of Online Revenue Collection Report 
public static final String ONLINE_REVENUE_COLLECTION_REPORT_QRY = " SELECT M.CHALLAN_SERIAL_NUMBER,TO_CHAR(M.UPDATE_DATE,'dd/MM/yyyy hh:mi:ss AM'),M.FUNCTION_ID, F.FUNCTION_NAME,M.PAYMENT_MODE_ID,PM.PAYMENT_MODE ,M.CREATED_BY , M.CHALLAN_AMOUNT "+
		 " FROM IGRS_PAYMENT_ECHALLAN_DETAILS M, IGRS_FUNCTION_MASTER F ,IGRS_PAYMENT_MODE_MASTER PM "+
		 " WHERE M.FUNCTION_ID=F.FUNCTION_ID AND M.PAYMENT_MODE_ID=PM.PAYMENT_MODE_ID AND  M.DISTRICT_ID=? AND M.OFFICE_ID=? AND (M.UPDATE_DATE BETWEEN TO_DATE(?,'DD/MM/YYYY') AND TO_DATE(?,'DD/MM/YYYY')+1) AND  M.PAYMENT_MODE_ID=?";

//For Total Sum of Cash Revenue Collection

public static final String SUM_QRY_CASH_REVENUE_COLLECTION= "SELECT SUM(GROSS_AMOUNT) FROM IGRS_PAYMENT_MODE_DETAILS M WHERE " +
          "  M.DISTRICT_ID=? AND M.OFFICE_ID=? AND (M.CREATED_DATE BETWEEN TO_DATE(?,'DD/MM/YYYY') AND TO_DATE(?,'DD/MM/YYYY')+1)";
          

//For Total Sum of Challan Revenue Collection

public static final String SUM_QRY_CHALLAN_REVENUE_COLLECTION= "SELECT SUM(CHALLAN_AMOUNT),SUM(PAID_AMOUNT) FROM IGRS_PAYMENT_ECHALLAN_DETAILS M WHERE " +
        "  M.DISTRICT_ID=? AND M.OFFICE_ID=? AND (M.UPDATE_DATE BETWEEN TO_DATE(?,'DD/MM/YYYY') AND TO_DATE(?,'DD/MM/YYYY')+1) AND M.PAYMENT_MODE_ID=?";
        
//For Total Sum of Challan Revenue Collection

public static final String SUM_QRY_ONLINE_REVENUE_COLLECTION= "SELECT SUM(CHALLAN_AMOUNT),SUM(PAID_AMOUNT) FROM IGRS_PAYMENT_ECHALLAN_DETAILS M WHERE " +
      "  M.DISTRICT_ID=? AND M.OFFICE_ID=? AND (M.UPDATE_DATE BETWEEN TO_DATE(?,'DD/MM/YYYY') AND TO_DATE(?,'DD/MM/YYYY')+1) AND M.PAYMENT_MODE_ID=? ";

//added by Roopam for transactional hindi of rev mgmt.
public static final String DISTRICT_QRY_HINDI=  "SELECT DISTRICT_ID, DISTRICT_NAME,H_DISTRICT_NAME FROM IGRS_DISTRICT_MASTER " +
"WHERE STATE_ID ='1' AND DISTRICT_STATUS ='A' ORDER BY DISTRICT_NAME ASC";

public static final String OFFICE_TYPE_DETAILS_HINDI = "SELECT OFFICE_TYPE_ID,OFFICE_TYPE_NAME,OFFICE_TYPE_NAME_H FROM IGRS_OFFICE_TYPE_MASTER WHERE ACTIVE_FLAG = 'A' ORDER BY OFFICE_TYPE_NAME ASC";

public static final String OFFICE_NAME_DETAILS_HINDI = "SELECT OFFICE_ID,OFFICE_NAME,H_OFFICE_NAME FROM IGRS_OFFICE_MASTER WHERE OFFICE_TYPE_ID =? AND DISTRICT_ID=? AND OFFICE_STATUS='A' ORDER BY OFFICE_NAME ASC";

public static final String GET_CASH_DETAILS_RECEIPT_SEARCH_HINDI =" SELECT M.TRANSACTION_ID,M.GROSS_AMOUNT,TO_CHAR(M.CREATED_DATE,'dd/MM/yyyy hh:mi:ss AM'),"+
			 " M.OFFICE_ID, M.FUNCTION_ID, M.CREATED_BY , O.OFFICE_NAME, F.FUNCTION_NAME,U.USER_ID,"+
			  " U.FIRST_NAME||' '||U.MIDDLE_NAME||' '||U.LAST_NAME , M.STATUS_FLAG, O.H_OFFICE_NAME, F.FUNCTION_NAME_H " +
			" FROM IGRS_PAYMENT_MODE_DETAILS M,IGRS_OFFICE_MASTER O,IGRS_FUNCTION_MASTER F, IGRS_USER_REG_DETAILS U"+
			" WHERE M.OFFICE_ID   =O.OFFICE_ID"+
			" AND M.FUNCTION_ID   =F.FUNCTION_ID"+
			" AND M.CREATED_BY    =U.USER_ID"+
			" AND LOWER(M.TRANSACTION_ID)=?";

/*public static final String GET_CHALLAN_DETAILS_RECEIPT_SEARCH_HINDI = 
	" SELECT M.CHALLAN_SERIAL_NUMBER,M.PAID_AMOUNT,TO_CHAR(M.CREATED_DATE,'dd/MM/yyyy hh:mi:ss AM'), "+
	" M.OFFICE_ID, M.FUNCTION_ID, M.CREATED_BY , O.OFFICE_NAME, F.FUNCTION_NAME,U.USER_ID, "+
	" U.FIRST_NAME||' '||U.MIDDLE_NAME||' '||U.LAST_NAME , M.STATUS_FLAG, O.H_OFFICE_NAME, F.FUNCTION_NAME_H"+
	" FROM IGRS_PAYMENT_ECHALLAN_DETAILS M,IGRS_OFFICE_MASTER O,IGRS_FUNCTION_MASTER F, IGRS_USER_REG_DETAILS U "+
	" WHERE M.OFFICE_ID   =O.OFFICE_ID "+
	" AND M.FUNCTION_ID   =F.FUNCTION_ID "+
	" AND M.CREATED_BY    =U.USER_ID "+
	" AND LOWER(M.CHALLAN_SERIAL_NUMBER)=? AND PAYMENT_MODE_ID=?";*/

public static final String GET_CHALLAN_DETAILS_RECEIPT_SEARCH_HINDI = 
" SELECT M.CHALLAN_SERIAL_NUMBER,M.PAID_AMOUNT,TO_CHAR(M.CREATED_DATE,'dd/MM/yyyy hh:mi:ss AM'), "+
" M.OFFICE_ID, M.FUNCTION_ID, M.CREATED_BY , O.OFFICE_NAME, F.FUNCTION_NAME,U.USER_ID, "+
" U.FIRST_NAME||' '||U.MIDDLE_NAME||' '||U.LAST_NAME , M.STATUS_FLAG, O.H_OFFICE_NAME, F.FUNCTION_NAME_H"+
" FROM IGRS_PAYMENT_ECHALLAN_DETAILS M,IGRS_OFFICE_MASTER O,IGRS_FUNCTION_MASTER F, IGRS_USER_REG_DETAILS U "+
" WHERE M.OFFICE_ID   =O.OFFICE_ID "+
" AND M.FUNCTION_ID   =F.FUNCTION_ID "+
" AND M.CREATED_BY    =U.USER_ID "+
" AND M.EPNR_NO=? AND PAYMENT_MODE_ID=?";

public static final String GET_ONLINE_DETAILS_RECEIPT_SEARCH_HINDI = 
	" SELECT M.CHALLAN_SERIAL_NUMBER,M.PAID_AMOUNT,TO_CHAR(M.CREATED_DATE,'dd/MM/yyyy hh:mi:ss AM'), "+
	" M.OFFICE_ID, M.FUNCTION_ID, M.CREATED_BY , O.OFFICE_NAME, F.FUNCTION_NAME,U.USER_ID, "+
	" U.FIRST_NAME||' '||U.MIDDLE_NAME||' '||U.LAST_NAME , M.STATUS_FLAG, O.H_OFFICE_NAME, F.FUNCTION_NAME_H"+
	" FROM IGRS_PAYMENT_ECHALLAN_DETAILS M,IGRS_OFFICE_MASTER O,IGRS_FUNCTION_MASTER F, IGRS_USER_REG_DETAILS U "+
	" WHERE M.OFFICE_ID   =O.OFFICE_ID "+
	" AND M.FUNCTION_ID   =F.FUNCTION_ID "+
	" AND M.CREATED_BY    =U.USER_ID "+
	" AND M.CRN_NUMBER=? AND PAYMENT_MODE_ID=?";

public static final String CASH_REVENUE_COLLECTION_REPORT_QRY_HINDI = " SELECT M.TRANSACTION_ID,TO_CHAR(M.CREATED_DATE,'dd/MM/yyyy hh:mi:ss AM'),M.FUNCTION_ID, F.FUNCTION_NAME,M.PAYMENT_TYPE_ID, "+
" M.CREATED_BY , M.GROSS_AMOUNT,F.FUNCTION_NAME_H " +
  " FROM IGRS_PAYMENT_MODE_DETAILS M, IGRS_FUNCTION_MASTER F "+
  " WHERE M.FUNCTION_ID=F.FUNCTION_ID AND  M.DISTRICT_ID=? AND M.OFFICE_ID=? AND (M.CREATED_DATE BETWEEN TO_DATE(?,'DD/MM/YYYY') AND TO_DATE(?,'DD/MM/YYYY')+1) order by M.CREATED_DATE desc" ;

public static final String ONLINE_REVENUE_COLLECTION_REPORT_QRY_HINDI = " SELECT M.CHALLAN_SERIAL_NUMBER,TO_CHAR(M.UPDATE_DATE,'dd/MM/yyyy hh:mi:ss AM'),M.FUNCTION_ID, F.FUNCTION_NAME,M.PAYMENT_MODE_ID,PM.PAYMENT_MODE ,M.CREATED_BY , M.CHALLAN_AMOUNT,F.FUNCTION_NAME_H,PM.PAYMENT_MODE_H,M.PAID_AMOUNT "+
" FROM IGRS_PAYMENT_ECHALLAN_DETAILS M, IGRS_FUNCTION_MASTER F ,IGRS_PAYMENT_MODE_MASTER PM "+
" WHERE M.FUNCTION_ID=F.FUNCTION_ID AND M.PAYMENT_MODE_ID=PM.PAYMENT_MODE_ID AND  M.DISTRICT_ID=? AND M.OFFICE_ID=? AND (M.UPDATE_DATE BETWEEN TO_DATE(?,'DD/MM/YYYY') AND TO_DATE(?,'DD/MM/YYYY')+1) AND  M.PAYMENT_MODE_ID=? order by M.UPDATE_DATE desc";

public static final String CHALLAN_REVENUE_COLLECTION_REPORT_QRY_HINDI = " SELECT M.CHALLAN_SERIAL_NUMBER,TO_CHAR(M.UPDATE_DATE,'dd/MM/yyyy hh:mi:ss AM'),M.FUNCTION_ID, F.FUNCTION_NAME,M.PAYMENT_MODE_ID,PM.PAYMENT_MODE ,M.CREATED_BY , M.CHALLAN_AMOUNT,F.FUNCTION_NAME_H,PM.PAYMENT_MODE_H,M.PAID_AMOUNT "+
" FROM IGRS_PAYMENT_ECHALLAN_DETAILS M, IGRS_FUNCTION_MASTER F ,IGRS_PAYMENT_MODE_MASTER PM "+
" WHERE M.FUNCTION_ID=F.FUNCTION_ID AND M.PAYMENT_MODE_ID=PM.PAYMENT_MODE_ID AND  M.DISTRICT_ID=? AND M.OFFICE_ID=? AND (M.UPDATE_DATE BETWEEN TO_DATE(?,'DD/MM/YYYY') AND TO_DATE(?,'DD/MM/YYYY')+1) AND  M.PAYMENT_MODE_ID=? order by M.UPDATE_DATE desc";

/*public static final String GET_SEARCH_DETAILS_QUERY_HINDI = 
	 "SELECT T.TRANSACTION_ID,T.AMOUNT_PAID ,TO_CHAR(T.CREATED_DATE,'dd/MM/yyyy hh:mi:ss AM'),"+
			 " T.PAYMENT_PURPOSE,T.USER_ID, "+
			 " T.DISTRICT_ID,T.OFFICE_ID ,F.FUNCTION_NAME,O.OFFICE_NAME,D.DISTRICT_NAME,M.PAYMENT_MODE_TXN_ID, "+
			 " F.FUNCTION_NAME_H,O.H_OFFICE_NAME,D.H_DISTRICT_NAME "+
			 " FROM IGRS_PAYMENT_TXN_DETAILS T ,IGRS_FUNCTION_MASTER F,IGRS_OFFICE_MASTER O,IGRS_DISTRICT_MASTER D,IGRS_PAYMENT_TXN_MAP M"+
			" where 1=1  AND T.PAYMENT_PURPOSE=F.FUNCTION_ID"+
			" AND T.OFFICE_ID =O.OFFICE_ID"+
			" AND T.DISTRICT_ID =D.DISTRICT_ID"+
			" AND T.TRANSACTION_ID=M.PAYMENT_TXN_ID ";*/

public static final String GET_SEARCH_DETAILS_QUERY_HINDI = 
	 "SELECT T.TRANSACTION_ID,T.AMOUNT_PAID ,TO_CHAR(T.CREATED_DATE,'dd/MM/yyyy hh:mi:ss AM'),"+
			 " T.PAYMENT_PURPOSE,T.USER_ID, "+
			 " T.DISTRICT_ID,T.OFFICE_ID ,F.FUNCTION_NAME,(select p.office_name from IGRS_OFFICE_MASTER p where t.OFFICE_ID=p.OFFICE_ID) OFFICE_NAME," +
			 "(select p.DISTRICT_NAME from IGRS_DISTRICT_MASTER p where t.DISTRICT_ID=p.DISTRICT_ID) DISTRICT_NAME,M.PAYMENT_MODE_TXN_ID, "+
			 " F.FUNCTION_NAME_H,(select p.H_OFFICE_NAME from IGRS_OFFICE_MASTER p where t.OFFICE_ID=p.OFFICE_ID) H_OFFICE_NAME," +
			 "(select p.H_DISTRICT_NAME from IGRS_DISTRICT_MASTER p where t.DISTRICT_ID=p.DISTRICT_ID) H_DISTRICT_NAME "+
			 " FROM IGRS_PAYMENT_TXN_DETAILS T ,IGRS_FUNCTION_MASTER F,IGRS_PAYMENT_TXN_MAP M"+
			" where 1=1  AND T.PAYMENT_PURPOSE=F.FUNCTION_ID"+
			" AND T.TRANSACTION_ID=M.PAYMENT_TXN_ID ";

/*public static final String GET_SEARCH_DETAILS_QUERY1_HINDI = 
	 "SELECT T.TRANSACTION_ID,T.AMOUNT_PAID ,TO_CHAR(T.CREATED_DATE,'dd/MM/yyyy hh:mi:ss AM'),"+
			 " T.PAYMENT_PURPOSE,T.USER_ID, "+
			 " T.DISTRICT_ID,T.OFFICE_ID ,F.FUNCTION_NAME,O.OFFICE_NAME,D.DISTRICT_NAME, "+
			 " F.FUNCTION_NAME_H,O.H_OFFICE_NAME,D.H_DISTRICT_NAME "+
			 " FROM IGRS_PAYMENT_TXN_DETAILS T ,IGRS_FUNCTION_MASTER F,IGRS_OFFICE_MASTER O,IGRS_DISTRICT_MASTER D"+
			" where 1=1  AND T.PAYMENT_PURPOSE=F.FUNCTION_ID"+
			" AND T.OFFICE_ID =O.OFFICE_ID"+
			" AND T.DISTRICT_ID =D.DISTRICT_ID ";*/

public static final String GET_SEARCH_DETAILS_QUERY1_HINDI = 
"SELECT T.TRANSACTION_ID,T.AMOUNT_PAID ,TO_CHAR(T.CREATED_DATE,'dd/MM/yyyy hh:mi:ss AM'),"+
		 " T.PAYMENT_PURPOSE,T.USER_ID, "+
		 " T.DISTRICT_ID,T.OFFICE_ID ,F.FUNCTION_NAME,(select p.office_name from IGRS_OFFICE_MASTER p where t.OFFICE_ID=p.OFFICE_ID) OFFICE_NAME,"+
         "(select p.DISTRICT_NAME from IGRS_DISTRICT_MASTER p where t.DISTRICT_ID=p.DISTRICT_ID) DISTRICT_NAME, "+
		 " F.FUNCTION_NAME_H,(select p.H_OFFICE_NAME from IGRS_OFFICE_MASTER p where t.OFFICE_ID=p.OFFICE_ID) H_OFFICE_NAME,"+
		 "(select p.H_DISTRICT_NAME from IGRS_DISTRICT_MASTER p where t.DISTRICT_ID=p.DISTRICT_ID) H_DISTRICT_NAME "+
		 " FROM IGRS_PAYMENT_TXN_DETAILS T ,IGRS_FUNCTION_MASTER F"+
		" where 1=1  AND T.PAYMENT_PURPOSE=F.FUNCTION_ID";
		
		

public static final String OFFICE_NAME=
	"SELECT OFFICE_NAME FROM IGRS_OFFICE_MASTER WHERE OFFICE_ID=?";
public static final String OFFICE_NAME_HINDI=
	"SELECT H_OFFICE_NAME FROM IGRS_OFFICE_MASTER WHERE OFFICE_ID=?";
    
//added by Shreeraj
public static final String GET_PURPOSE_LIST="SELECT A.FUNCTION_ID,A.FUNCTION_NAME,A.FUNCTION_NAME_H FROM IGRS_FUNCTION_MASTER A, IGRS_FUNCTION_SERVICE_MAPPING B WHERE A.FUNCTION_ID=B.FUNCTION_ID AND B.MAPPING_STATUS='A' AND A.FUNCTION_STATUS='A' ORDER BY FUNCTION_NAME ";

//For Total Sum of Cash Revenue Collection

public static final String SUM_QRY_CASH_REVENUE_COLLECTION_COMBINE= "SELECT SUM(GROSS_AMOUNT) FROM IGRS_PAYMENT_MODE_DETAILS M WHERE " +
          "  M.DISTRICT_ID=? AND M.OFFICE_ID=? AND (M.CREATED_DATE BETWEEN TO_DATE(?,'DD/MM/YYYY') AND TO_DATE(?,'DD/MM/YYYY')+1)";
          

//For Total Sum of Challan Revenue Collection

public static final String SUM_QRY_CHALLAN_REVENUE_COLLECTION_COMBINE= "SELECT SUM(CHALLAN_AMOUNT) FROM IGRS_PAYMENT_ECHALLAN_DETAILS M WHERE " +
        "  M.DISTRICT_ID=? AND M.OFFICE_ID=? AND (M.UPDATE_DATE BETWEEN TO_DATE(?,'DD/MM/YYYY') AND TO_DATE(?,'DD/MM/YYYY')+1) AND M.PAYMENT_MODE_ID=?";
        
//For Total Sum of Challan Revenue Collection

public static final String SUM_QRY_ONLINE_REVENUE_COLLECTION_COMBINE= "SELECT SUM(CHALLAN_AMOUNT) FROM IGRS_PAYMENT_ECHALLAN_DETAILS M WHERE " +
      "  M.DISTRICT_ID=? AND M.OFFICE_ID=? AND (M.UPDATE_DATE BETWEEN TO_DATE(?,'DD/MM/YYYY') AND TO_DATE(?,'DD/MM/YYYY')+1) AND M.PAYMENT_MODE_ID=? ";

public static final String CREDITLIMITPARAM="SELECT ATTRIBUTE_VALUE FROM  IGRS_CONFIG_PARAM_LIST WHERE ATTRIBUTE_NAME='CREDIT_LIMIT_REV_SEARCH_PERIOD' AND ATTRIBUTE_STATUS='A'";
public static final String CHALLANPARAM="SELECT ATTRIBUTE_VALUE FROM  IGRS_CONFIG_PARAM_LIST WHERE ATTRIBUTE_NAME='CHALLAN_REV_SEARCH_PERIOD' AND ATTRIBUTE_STATUS='A' ";


}