/**
 * Copyright (c) 2009-10 WIPRO INFOTECH. All Rights Reserved.
 *
 *  This software is the confidential and proprietary information of WIPRO
 *  ("Confidential Information"). You shall not
 *  disclose such Confidential Information and shall use it only in
 *  accordance with the terms of the license agreement you entered into
 *  with WIPRO.
 *
 * WIPRO MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE
 * SUITABILITY OF THE SOFTWARE, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A
 * PARTICULAR PURPOSE, OR NON-INFRINGEMENT. WIPRO SHALL NOT BE
 * LIABLE FOR ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF
 * USING, MODIFYING OR DISTRIBUTING THIS SOFTWARE OR ITS
 * DERIVATIVES.
 *
 * Customer specific copyright notice - NA
 */
package com.wipro.igrs.caveats.sql;

/**
* 
* CommonSQL.java <br>
* CommonSQL <br>
* 
* @version 1.0
* 
* @author <b>WIPRO JAVA TEAM</b> <br>
*         Created on 04-Dec-2007 <br>
*         Last Modified on 28-Mar-2013
*/
public class CommonSQL {
	//
	
	public static final String SERVICE_FEE_PROCEDURE = "CALL " 
		+"IGRS_SERVICE_FEE_PKG.IGRS_SERVICE_FEE_PROC(?,?,?,?,?,?)";
	
	public static final String GET_REGINIT_ID ="SELECT REG_TXN_ID FROM IGRS_REG_TXN_DETLS WHERE REGISTRATION_NUMBER=?";
	public static final String GET_VAL_DETAILS = "Select ism.prop_val_req_flag from IGRS_REG_TXN_DETLS reg,IGRS_DEED_INSTRUMENT_MASTER ism where  reg.instruments_id = ism.instrument_id AND REG.REGISTRATION_NUMBER = ?";
    //public static final String PRESENT_PAYMENT_ENTRY="select PAYMENT_FLAG,PAYMENT_TXN_ID from IGRS_CAVEAT_PAYMENT_DETAILS where CAVEAT_TXN_ID=";
	public static final String PRESENT_PAYMENT_ENTRY="select PAYMENT_FLAG,PAYMENT_TXN_ID from IGRS_CAVEAT_PAYMENT_DETAILS where PAYMENT_TXN_ID=(select max(PAYMENT_TXN_ID) from IGRS_CAVEAT_PAYMENT_DETAILS where CAVEAT_TXN_ID=";
	public static final String Caveat_Get_Details="select a.office_id , a.office_name, a.district_id, b.district_name from igrs_office_master a, igrs_district_master b where a.district_id=b.district_id and a.office_id=";
	public static final String COPY_PAYMENT_DTLS= "INSERT INTO IGRS_CAVEAT_PAYMENT_DETAILS(TRANSACTION_ID,CAVEAT_TXN_ID,FUNCTION_ID,PAID_AMOUNT,PAYMENT_FLAG,CREATED_BY,CREATED_DATE,PAYABLE_AMOUNT) VALUES(?,?,?,?,?,?,SYSDATE,?)";
	public static final String Caveat_Get_Ott="SELECT DISTINCT(PM.PROPERTY_TXN_ID) FROM IGRS_LOAN_OTT_MASTER OM, IGRS_OTT_PROP_MAPPING PM WHERE PM.OTT_ID    = OM.OTT_ID AND OM.OTT_STATUS = 'A' AND PM.PROPERTY_TXN_ID IN (";

	public static final String IGRS_DOCUMENT_DTLS = "INSERT INTO IGRS_CAVEAT_DOC_DTLS(CAVEATS_DOC_ID, TRANSACTION_ID,DOC_NAME, UPLOADED_DOC_PATH)VALUES(?,?,?,?)";
    //public static final String CAVEATS_CHARGES_INSERT=" INSERT INTO IGRS_CAVEAT_TXN(TRANSACTION_ID,INSTITUTE_NAME,INSTITUTE_ADDRESS,INSTITUTE_REP_NAME,COUNTRY_ID,STATE_ID,DISTRICT_ID,POSTAL_CODE,PHONE_NUMBER,CAVEAT_TYPE_ID,STAY_ORDER_NO,STAY_ORDER_DETAILS,CAVEAT_DETAILS,DOCUMENT_NAME,REMARKS,REGISTRATION_ID,CAVEAT_STATUS,CAVEAT_LOGGED_DATE,CREATED_BY,CREATED_DATE) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,TO_DATE(TO_CHAR(SYSDATE,'DD/MM/YYYY'),'DD/MM/YYYY'),?,TO_DATE(TO_CHAR(SYSDATE,'DD/MM/YYYY'),'DD/MM/YYYY'))";

    public static final String CAVEATS_CHARGES_INSERT=" INSERT INTO IGRS_CAVEAT_TXN(TRANSACTION_ID,INSTITUTE_NAME,INSTITUTE_ADDRESS,INSTITUTE_REP_NAME,COUNTRY_ID,STATE_ID,DISTRICT_ID,POSTAL_CODE,PHONE_NUMBER,CAVEAT_TYPE_ID,STAY_ORDER_NO,STAY_ORDER_DETAILS,CAVEAT_DETAILS,DOCUMENT_NAME,REMARKS,REGISTRATION_ID,CAVEAT_STATUS,CAVEAT_LOGGED_DATE,CREATED_BY,CREATED_DATE) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,TO_DATE(TO_CHAR(SYSDATE,'DD/MM/YYYY'),'DD/MM/YYYY'),?,TO_DATE(TO_CHAR(SYSDATE,'DD/MM/YYYY'),'DD/MM/YYYY'))";
    public static final String CAVEATS_CHARGES_INSERT_PROPERTYID="INSERT INTO IGRS_CAVEAT_PROPERTY_MAP (CAVEAT_TXN_ID,PROPERTY_TXN_ID)VALUES(?,?)";
    public static final String CAVEATS_CHARGES_INSERT_FILE="UPDATE IGRS_CAVEAT_TXN SET DOCUMENT_NAME=?, UPLOADED_DOC=? WHERE TRANSACTION_ID=?";
    
    public static final String IGRS_CAVEATS_CAVEAT_MASTER="SELECT CAVEAT_TYPE_NAME,CAVEAT_TYPE_ID,STAY_ORDER_STATUS FROM IGRS_CAVEAT_TYPE_MASTER WHERE CAVEAT_TYPE_STATUS='A'";
    public static final String IGRS_CAVEATS_CAVEAT_MASTER_hi="SELECT H_CAVEAT_TYPE_NAME,CAVEAT_TYPE_ID,STAY_ORDER_STATUS FROM IGRS_CAVEAT_TYPE_MASTER WHERE CAVEAT_TYPE_STATUS='A'";

    public static final String IGRS_COUNTRY_MASTER="SELECT COUNTRY_ID,COUNTRY_NAME FROM IGRS_COUNTRY_MASTER WHERE COUNTRY_STATUS='A'";

    public static final String IGRS_COUNTRY_MASTER_hi="SELECT COUNTRY_ID,H_COUNTRY_NAME FROM IGRS_COUNTRY_MASTER WHERE COUNTRY_STATUS='A'";
    public static final String IGRS_STATE_MASTER="SELECT STATE_ID,STATE_NAME FROM IGRS_STATE_MASTER WHERE COUNTRY_ID=? AND STATE_STATUS='A'";
    public static final String IGRS_STATE_MASTER_hi="SELECT STATE_ID,H_STATE_NAME FROM IGRS_STATE_MASTER WHERE COUNTRY_ID=? AND STATE_STATUS='A'";

    public static final String IGRS_DISTRICT_MASTER="SELECT DISTRICT_ID,DISTRICT_NAME FROM IGRS_DISTRICT_MASTER WHERE STATE_ID=? AND DISTRICT_STATUS='A'";

    public static final String IGRS_DISTRICT_MASTER_hi="SELECT DISTRICT_ID,H_DISTRICT_NAME FROM IGRS_DISTRICT_MASTER WHERE STATE_ID=? AND DISTRICT_STATUS='A'";
    
    public static final String IGRS_CAVEATS_SEARCH_REFID="SELECT TRANSACTION_ID,INSTITUTE_NAME,INSTITUTE_ADDRESS,INSTITUTE_REP_NAME,(SELECT DISTINCT (CP.PAYABLE_AMOUNT-CP.PAID_AMOUNT)DUE_AMOUNT FROM IGRS_CAVEAT_TXN CT,IGRS_CAVEAT_TYPE_MASTER CM,(SELECT IGRS_CAVEAT_PAYMENT_DETAILS.CAVEAT_TXN_ID,SUM(IGRS_CAVEAT_PAYMENT_DETAILS.PAID_AMOUNT) PAID_AMOUNT,NVL(MAX(IGRS_CAVEAT_PAYMENT_DETAILS.TOTAL_FEE),50)PAYABLE_AMOUNT FROM IGRS_CAVEAT_PAYMENT_DETAILS GROUP BY IGRS_CAVEAT_PAYMENT_DETAILS.CAVEAT_TXN_ID) CP WHERE CT.TRANSACTION_ID = CP.CAVEAT_TXN_ID and CT.TRANSACTION_ID=?),(SELECT COUNTRY_NAME FROM IGRS_COUNTRY_MASTER WHERE COUNTRY_ID=IGRS_CAVEAT_TXN.COUNTRY_ID ),(SELECT STATE_NAME FROM IGRS_STATE_MASTER WHERE STATE_ID=IGRS_CAVEAT_TXN.STATE_ID ),(SELECT DISTRICT_NAME FROM IGRS_DISTRICT_MASTER WHERE DISTRICT_ID=IGRS_CAVEAT_TXN.DISTRICT_ID),POSTAL_CODE,PHONE_NUMBER,(SELECT CAVEAT_TYPE_NAME FROM IGRS_CAVEAT_TYPE_MASTER WHERE CAVEAT_TYPE_ID=IGRS_CAVEAT_TXN.CAVEAT_TYPE_ID),STAY_ORDER_NO,STAY_ORDER_DETAILS,CAVEAT_DETAILS,DOCUMENT_NAME,UPLOADED_DOC_PATH,REMARKS,REGISTRATION_ID,CAVEAT_STATUS,TO_CHAR(STAY_ORDER_START_DATE,'DD/MM/YYYY'),TO_CHAR(STAY_ORDER_UPTO_DATE,'DD/MM/YYYY'),REASON_FOR_RELEASE,REMARKS_FOR_RELEASE FROM IGRS_CAVEAT_TXN WHERE TRANSACTION_ID=?";
    public static final String IGRS_CAVEATS_RELEASE_BY_REGNO="SELECT REGISTRATION_ID,CAVEAT_STATUS,TRANSACTION_ID,TO_CHAR(CAVEAT_LOGGED_DATE,'DD/MM/YYYY')FROM IGRS_CAVEAT_TXN WHERE REGISTRATION_ID=? AND CAVEAT_STATUS='LOGGED'";
    public static final String IGRS_CAVEATS_RELEASE_BY_DURATION="SELECT REGISTRATION_ID,CAVEAT_STATUS,TRANSACTION_ID,TO_CHAR(CAVEAT_LOGGED_DATE,'DD/MM/YYYY')FROM IGRS_CAVEAT_TXN WHERE CAVEAT_LOGGED_DATE BETWEEN TO_DATE(?,'DD/MM/YYYY') AND TO_DATE(?,'DD/MM/YYYY')AND CAVEAT_STATUS='LOGGED' ORDER BY TRANSACTION_ID ";
    public static final String IGRS_CAVEATS_UPDATE_RELEASE="UPDATE IGRS_CAVEAT_TXN SET CAVEAT_STATUS='RELEASED', REASON_FOR_RELEASE=?, REMARKS_FOR_RELEASE=?, UPDATE_BY=?, CAVEAT_RELEASE_DATE=SYSDATE,UPDATE_DATE=SYSDATE, RELEASE_DOC_NAME=?, RELEASE_DOC=? WHERE TRANSACTION_ID=?";
  
    //$11Query for Caveat Release by Bank
    public static final String IGRS_CAVEATS_BANK_RELEASE_REFID="SELECT CAVEAT_BANK_TXN_ID,OTT_ID,LOAN_ACCOUNT_NO,TO_CHAR(LOAN_START_DATE,'DD/MM/YYYY'),TO_CHAR(LOAN_END_DATE,'DD/MM/YYYY'),LOAN_AMOUNT,LOAN_SECURED_AMOUNT,NO_OF_INSTALLMENTS,BANK_NAME,BANK_ADDRESS,BANK_REP_NAME,DOCUMENT_NAME,UPLOADED_DOC_PATH,REMARKS,REGISTRATION_ID,CAVEAT_STATUS,TO_CHAR(CAVEAT_LOGGED_DATE,'DD/MM/YYYY'),BANK_PERSON_CONTACT_NO,BANK_PERSON_EMAIL_ID FROM IGRS_CAVEAT_BANK_TXN WHERE CAVEAT_BANK_TXN_ID=?";
    public static final String IGRS_CAVEATS_BANK_RELEASE_REGNO="SELECT REGISTRATION_ID,CAVEAT_STATUS,CAVEAT_BANK_TXN_ID,TO_CHAR(CAVEAT_LOGGED_DATE,'DD/MM/YYYY')FROM IGRS_CAVEAT_BANK_TXN WHERE REGISTRATION_ID=? AND CAVEAT_STATUS='LOGGED'";
    public static final String IGRS_CAVEATS_BANK_RELEASE_DURATION="SELECT REGISTRATION_ID,CAVEAT_STATUS,CAVEAT_BANK_TXN_ID,TO_CHAR(CAVEAT_LOGGED_DATE,'DD/MM/YYYY')FROM IGRS_CAVEAT_BANK_TXN WHERE CAVEAT_LOGGED_DATE BETWEEN TO_DATE(?,'DD/MM/YYYY') AND TO_DATE(?,'DD/MM/YYYY')AND CAVEAT_STATUS='LOGGED' ORDER BY CAVEAT_BANK_TXN_ID";
    public static final String IGRS_CAVEATS_BANK_RELEASE_UPDATE="UPDATE IGRS_CAVEAT_BANK_TXN SET CAVEAT_STATUS='RELEASED', REASON_FOR_RELEASE=?, REMARKS_FOR_RELEASE=?, UPDATE_BY=?,CAVEAT_RELEASE_DATE=SYSDATE,UPDATE_DATE=SYSDATE WHERE CAVEAT_BANK_TXN_ID=? AND CAVEAT_STATUS='LOGGED'";
    //$11End
    //query with Property ID
    

   // public static final String IGRS_CAVEATS_SEARCH_REFID_SEARCH="select distinct ctxn.TRANSACTION_id,cprop.PROPERTY_TXN_ID,(nvl(cpay.TOTAL_FEE,50)-cpay.PAID_AMOUNT) due_amount ,ctxn.INSTITUTE_NAME,ctxn.INSTITUTE_ADDRESS,ctxn.INSTITUTE_REP_NAME,ctxn.POSTAL_CODE,ctxn.PHONE_NUMBER,(SELECT CAVEAT_TYPE_NAME FROM IGRS_CAVEAT_TYPE_MASTER CT WHERE ct.CAVEAT_TYPE_ID=ctxn.CAVEAT_TYPE_ID)CAVEAT_TYPE_NAME ,ctxn.STAY_ORDER_NO,ctxn.STAY_ORDER_DETAILS,ctxn.CAVEAT_DETAILS,ctxn.DOCUMENT_NAME, (SELECT UPLOADED_DOC_PATH FROM IGRS_CAVEAT_DOC_DTLS DNT WHERE DNT.TRANSACTION_ID=cpay.caveat_txn_id)UPLOADED_DOC_PATH,ctxn.REMARKS,ctxn.REGISTRATION_ID,ctxn.CAVEAT_STATUS,ctxn.CAVEAT_LOGGED_DATE,ctxn.CAVEAT_RELEASE_DATE,ctxn.REASON_FOR_RELEASE,ctxn.REMARKS_FOR_RELEASE, (SELECT COUNTRY_NAME FROM IGRS_COUNTRY_MASTER CNT WHERE CNT.COUNTRY_ID=CTXN.COUNTRY_ID) COUNTRY,(SELECT STATE_NAME FROM IGRS_STATE_MASTER STT WHERE STT.STATE_ID=CTXN.STATE_ID) STATE,(SELECT DISTRICT_NAME FROM IGRS_DISTRICT_MASTER DIST WHERE DIST.DISTRICT_ID=CTXN.DISTRICT_ID),cpay.PAID_AMOUNT from IGRS_CAVEAT_TXN ctxn,IGRS_CAVEAT_PROPERTY_MAP cprop,IGRS_CAVEAT_PAYMENT_DETAILS cpay where ctxn.TRANSACTION_ID=cprop.CAVEAT_TXN_ID and cpay.CAVEAT_TXN_ID=ctxn.TRANSACTION_ID and ctxn.TRANSACTION_ID=?";
   // public static final String IGRS_CAVEATS_SEARCH_REFID_SEARCH="select distinct ctxn.TRANSACTION_id,cprop.PROPERTY_TXN_ID,(NVL(CPAY.TOTAL_FEE,50)-NVL(CPAY.PAID_AMOUNT,0)) DUE_AMOUNT ,ctxn.INSTITUTE_NAME,ctxn.INSTITUTE_ADDRESS,ctxn.INSTITUTE_REP_NAME,ctxn.POSTAL_CODE,ctxn.PHONE_NUMBER,(SELECT CAVEAT_TYPE_NAME FROM IGRS_CAVEAT_TYPE_MASTER CT WHERE ct.CAVEAT_TYPE_ID=ctxn.CAVEAT_TYPE_ID)CAVEAT_TYPE_NAME ,ctxn.STAY_ORDER_NO,ctxn.STAY_ORDER_DETAILS,ctxn.CAVEAT_DETAILS,ctxn.DOCUMENT_NAME, (SELECT UPLOADED_DOC_PATH FROM IGRS_CAVEAT_DOC_DTLS DNT WHERE DNT.TRANSACTION_ID=cpay.caveat_txn_id)UPLOADED_DOC_PATH,ctxn.REMARKS,ctxn.REGISTRATION_ID,ctxn.CAVEAT_STATUS,ctxn.CAVEAT_LOGGED_DATE,ctxn.CAVEAT_RELEASE_DATE,ctxn.REASON_FOR_RELEASE,ctxn.REMARKS_FOR_RELEASE, (SELECT COUNTRY_NAME FROM IGRS_COUNTRY_MASTER CNT WHERE CNT.COUNTRY_ID=CTXN.COUNTRY_ID) COUNTRY,(SELECT STATE_NAME FROM IGRS_STATE_MASTER STT WHERE STT.STATE_ID=CTXN.STATE_ID) STATE,(SELECT DISTRICT_NAME FROM IGRS_DISTRICT_MASTER DIST WHERE DIST.DISTRICT_ID=CTXN.DISTRICT_ID),NVL(CPAY.PAID_AMOUNT,'0') from IGRS_CAVEAT_TXN ctxn,IGRS_CAVEAT_PROPERTY_MAP cprop,IGRS_CAVEAT_PAYMENT_DETAILS cpay where ctxn.TRANSACTION_ID=cprop.CAVEAT_TXN_ID and cpay.CAVEAT_TXN_ID=ctxn.TRANSACTION_ID and ctxn.TRANSACTION_ID=?";

    public static final String IGRS_CAVEATS_SEARCH_REFID_SEARCH="SELECT DISTINCT ctxn.TRANSACTION_id,cprop.PROPERTY_TXN_ID,(CPAY.PAYABLE_AMOUNT-CPAY.PAID_AMOUNT) DUE_AMOUNT ,ctxn.INSTITUTE_NAME,ctxn.INSTITUTE_ADDRESS,ctxn.INSTITUTE_REP_NAME,ctxn.POSTAL_CODE, ctxn.PHONE_NUMBER,ctxn.CASE_NUMBER,TO_CHAR(ctxn.COURT_ORDER_DATE,'DD/MM/YYYY') AS COURT_ORDER_DATE,(SELECT CAVEAT_TYPE_NAME FROM IGRS_CAVEAT_TYPE_MASTER CT WHERE ct.CAVEAT_TYPE_ID=ctxn.CAVEAT_TYPE_ID)CAVEAT_TYPE_NAME ,ctxn.STAY_ORDER_NO,ctxn.STAY_ORDER_DETAILS,ctxn.CAVEAT_DETAILS,ctxn.DOCUMENT_NAME,(SELECT UPLOADED_DOC_PATH FROM IGRS_CAVEAT_DOC_DTLS DNT WHERE DNT.TRANSACTION_ID=cpay.caveat_txn_id)UPLOADED_DOC_PATH,ctxn.REMARKS,ctxn.REGISTRATION_ID,ctxn.CAVEAT_STATUS, TO_CHAR(CTXN.STAY_ORDER_START_DATE,'DD/MM/YYYY') AS STAY_ORDER_START_DATE,TO_CHAR(CTXN.STAY_ORDER_UPTO_DATE,'DD/MM/YYYY') AS STAY_ORDER_UPTO_DATE,ctxn.REASON_FOR_RELEASE,ctxn.REMARKS_FOR_RELEASE,(SELECT COUNTRY_NAME FROM IGRS_COUNTRY_MASTER CNT WHERE CNT.COUNTRY_ID=CTXN.COUNTRY_ID) COUNTRY,(SELECT STATE_NAME FROM IGRS_STATE_MASTER STT WHERE STT.STATE_ID=CTXN.STATE_ID) STATE,(SELECT DISTRICT_NAME FROM IGRS_DISTRICT_MASTER DIST WHERE DIST.DISTRICT_ID=CTXN.DISTRICT_ID),CPAY.PAID_AMOUNT FROM IGRS_CAVEAT_TXN ctxn,IGRS_CAVEAT_PROPERTY_MAP cprop,(SELECT CAVEAT_TXN_ID,SUM(nvl(PAID_AMOUNT,0)) PAID_AMOUNT, MAX(NVL(amount,0))PAYABLE_AMOUNT  FROM IGRS_CAVEAT_PAYMENT_DETAILS C,IGRS_CAVEAT_TXN T where T.TRANSACTION_ID=c.CAVEAT_TXN_ID GROUP BY c.CAVEAT_TXN_ID)CPAY WHERE ctxn.TRANSACTION_ID=cprop.CAVEAT_TXN_ID AND CPAY.CAVEAT_TXN_ID   =CTXN.TRANSACTION_ID AND ctxn.TRANSACTION_ID=?";
    
    public static final String IGRS_CAVEATS_SEARCH_REFID_SEARCH_hi="SELECT DISTINCT ctxn.TRANSACTION_id,cprop.PROPERTY_TXN_ID,(CPAY.PAYABLE_AMOUNT-CPAY.PAID_AMOUNT) DUE_AMOUNT ,ctxn.INSTITUTE_NAME,ctxn.INSTITUTE_ADDRESS,ctxn.INSTITUTE_REP_NAME,ctxn.POSTAL_CODE, ctxn.PHONE_NUMBER,ctxn.CASE_NUMBER,TO_CHAR(ctxn.COURT_ORDER_DATE,'DD/MM/YYYY') AS COURT_ORDER_DATE,(SELECT H_CAVEAT_TYPE_NAME FROM IGRS_CAVEAT_TYPE_MASTER CT WHERE ct.CAVEAT_TYPE_ID=ctxn.CAVEAT_TYPE_ID)CAVEAT_TYPE_NAME ,ctxn.STAY_ORDER_NO,ctxn.STAY_ORDER_DETAILS,ctxn.CAVEAT_DETAILS,ctxn.DOCUMENT_NAME,(SELECT UPLOADED_DOC_PATH FROM IGRS_CAVEAT_DOC_DTLS DNT WHERE DNT.TRANSACTION_ID=cpay.caveat_txn_id)UPLOADED_DOC_PATH,ctxn.REMARKS,ctxn.REGISTRATION_ID,ctxn.CAVEAT_STATUS, TO_CHAR(CTXN.STAY_ORDER_START_DATE,'DD/MM/YYYY') AS STAY_ORDER_START_DATE,TO_CHAR(CTXN.STAY_ORDER_UPTO_DATE,'DD/MM/YYYY') AS STAY_ORDER_UPTO_DATE,ctxn.REASON_FOR_RELEASE,ctxn.REMARKS_FOR_RELEASE,(SELECT H_COUNTRY_NAME FROM IGRS_COUNTRY_MASTER CNT WHERE CNT.COUNTRY_ID=CTXN.COUNTRY_ID) COUNTRY,(SELECT H_STATE_NAME FROM IGRS_STATE_MASTER STT WHERE STT.STATE_ID=CTXN.STATE_ID) STATE,(SELECT H_DISTRICT_NAME FROM IGRS_DISTRICT_MASTER DIST WHERE DIST.DISTRICT_ID=CTXN.DISTRICT_ID),CPAY.PAID_AMOUNT FROM IGRS_CAVEAT_TXN ctxn,IGRS_CAVEAT_PROPERTY_MAP cprop,(SELECT CAVEAT_TXN_ID,SUM(nvl(PAID_AMOUNT,0)) PAID_AMOUNT, MAX(NVL(AMOUNT,0))PAYABLE_AMOUNT  FROM IGRS_CAVEAT_PAYMENT_DETAILS C,IGRS_CAVEAT_TXN T where T.TRANSACTION_ID=c.CAVEAT_TXN_ID GROUP BY c.CAVEAT_TXN_ID)CPAY WHERE ctxn.TRANSACTION_ID=cprop.CAVEAT_TXN_ID AND CPAY.CAVEAT_TXN_ID   =CTXN.TRANSACTION_ID AND ctxn.TRANSACTION_ID=?";
    
    
    public static final String IGRS_CAVEATS_SEARCH_REFID_VIEW="SELECT TRANSACTION_ID,INSTITUTE_NAME,INSTITUTE_ADDRESS,INSTITUTE_REP_NAME,(SELECT COUNTRY_NAME FROM IGRS_COUNTRY_MASTER WHERE COUNTRY_ID=IGRS_CAVEAT_TXN.COUNTRY_ID ),(SELECT STATE_NAME FROM IGRS_STATE_MASTER WHERE STATE_ID=IGRS_CAVEAT_TXN.STATE_ID ),(SELECT DISTRICT_NAME FROM IGRS_DISTRICT_MASTER WHERE DISTRICT_ID=IGRS_CAVEAT_TXN.DISTRICT_ID),POSTAL_CODE,PHONE_NUMBER,(SELECT CAVEAT_TYPE_NAME FROM IGRS_CAVEAT_TYPE_MASTER WHERE CAVEAT_TYPE_ID=IGRS_CAVEAT_TXN.CAVEAT_TYPE_ID),STAY_ORDER_NO,STAY_ORDER_DETAILS,CAVEAT_DETAILS,DOCUMENT_NAME,UPLOADED_DOC,REMARKS,REGISTRATION_ID,CAVEAT_STATUS,TO_CHAR(CAVEAT_LOGGED_DATE,'DD/MM/YYYY'),TO_CHAR(CAVEAT_RELEASE_DATE,'DD/MM/YYYY'),REASON_FOR_RELEASE,REMARKS_FOR_RELEASE,(SELECT PROPERTY_TXN_ID FROM IGRS_CAVEAT_PROPERTY_MAP PM WHERE PM.CAVEAT_TXN_ID=TRANSACTION_ID) FROM IGRS_CAVEAT_TXN  WHERE TRANSACTION_ID=?";
    
    public static final String IGRS_CAVEATS_SEARCH_TXNID_VIEW="SELECT REGISTRATION_ID,CAVEAT_STATUS,TRANSACTION_ID,TO_CHAR(CAVEAT_LOGGED_DATE,'DD/MM/YYYY')FROM IGRS_CAVEAT_TXN WHERE TRANSACTION_ID=? ORDER BY CAVEAT_LOGGED_DATE ASC";
    
    
    public static final String IGRS_CAVEATS_SEARCH_REGNO_VIEW="SELECT REGISTRATION_ID,CAVEAT_STATUS,TRANSACTION_ID,TO_CHAR(CAVEAT_LOGGED_DATE,'DD/MM/YYYY')FROM IGRS_CAVEAT_TXN WHERE REGISTRATION_ID=? ORDER BY CAVEAT_LOGGED_DATE ASC";
    
    
    public static final String IGRS_CAVEATS_SEARCH_STATUS_VIEW="SELECT REGISTRATION_ID,CAVEAT_STATUS,TRANSACTION_ID,TO_CHAR(CAVEAT_LOGGED_DATE,'DD/MM/YYYY')FROM IGRS_CAVEAT_TXN WHERE CAVEAT_STATUS=? ORDER BY CAVEAT_LOGGED_DATE ASC";
    
  //  public static final String IGRS_CAVEATS_SEARCH_ALL_VIEW="SELECT REGISTRATION_ID,CAVEAT_STATUS,TRANSACTION_ID,TO_CHAR(CAVEAT_LOGGED_DATE,'DD/MM/YYYY')FROM IGRS_CAVEAT_TXN WHERE TRANSACTION_ID=? OR REGISTRATION_ID=? OR CAVEAT_STATUS=? OR CAVEAT_LOGGED_DATE BETWEEN TO_DATE(?,'DD/MM/YYYY') AND TO_DATE(?,'DD/MM/YYYY') ORDER BY TRANSACTION_ID";
   // public static final String IGRS_CAVEATS_SEARCH_DURATION_VIEW="SELECT REGISTRATION_ID,CAVEAT_STATUS,TRANSACTION_ID,TO_CHAR(CAVEAT_LOGGED_DATE,'DD/MM/YYYY')FROM IGRS_CAVEAT_TXN WHERE CAVEAT_LOGGED_DATE BETWEEN TO_DATE(?,'DD/MM/YYYY') AND TO_DATE(?,'DD/MM/YYYY') ORDER BY TRANSACTION_ID";
    //MODIFIED BY ASHIMA
    public static final String IGRS_CAVEATS_SEARCH_ALL_VIEW="SELECT REGISTRATION_ID,CAVEAT_STATUS,TRANSACTION_ID,TO_CHAR(CAVEAT_LOGGED_DATE,'DD/MM/YYYY')FROM IGRS_CAVEAT_TXN WHERE TRANSACTION_ID=? OR REGISTRATION_ID=? OR CAVEAT_STATUS=? OR CAVEAT_LOGGED_DATE BETWEEN TO_DATE(?,'DD/MM/YYYY') AND TO_DATE(?,'DD/MM/YYYY') ORDER BY CAVEAT_LOGGED_DATE ASC";
      public static final String IGRS_CAVEATS_SEARCH_DURATION_VIEW="SELECT REGISTRATION_ID,CAVEAT_STATUS,TRANSACTION_ID,TO_CHAR(CAVEAT_LOGGED_DATE,'DD/MM/YYYY')FROM IGRS_CAVEAT_TXN WHERE CAVEAT_LOGGED_DATE BETWEEN TO_DATE(?,'DD/MM/YYYY') AND TO_DATE(?,'DD/MM/YYYY') ORDER BY CAVEAT_LOGGED_DATE ASC";
///////
    public static final String IGRS_CAVEATS_CHECK_PIN="SELECT REG_NO,PIN,CAVEATS FROM CAVEATS_REGISTRATION WHERE  REG_NO=? AND PIN=?";
    
    public static final String IGRS_CAVEATS_OTT_ACTIVE="SELECT * FROM IGRS_CAVEATS_OTT WHERE  REG_NO=? AND OTT_STATUS='Active' ";
    public static final String IGRS_CAVEATS_OTT_INSERT="INSERT INTO IGRS_CAVEATS_OTT(REG_NO,PIN,OTT,EXP_DAE_OF_OTT,OTT_STATUS,OTT_DATE)VALUES(?,?,?,TO_DATE(?,'DD/MM/YYYY'),?,TO_DATE(?,'DD/MM/YYYY'))";
    public static final String IGRS_CAVEATS_OTT_EXDAYS="SELECT DAYS FROM IGRS_CAVEATS_OTT_EXDATE";
    public static final String IGRS_CAVEATS_OTT_SEARCH_BYBANK="SELECT REGISTRATION_ID,OTT_TXN_ID FROM IGRS_REG_OTT_DETAILS WHERE REGISTRATION_ID=? AND OTT_TXN_ID=? AND OTT_STATUS='A'";
    public static final String IGRS_CAVEATS_OTT_UPDATE="UPDATE IGRS_REG_OTT_DETAILS SET OTT_STATUS='D' WHERE REGISTRATION_ID=? AND OTT_TXN_ID=?";
    
    // (OLD)public static final String IGRS_CAVEATS_INSERT_BYBANK="INSERT INTO IGRS_CAVEAT_BANK_TXN (REG_NO,LOGGED_DATE,OTT,NAME_OF_INSTI,ADDRESS_OF_INSTI,CONTACT_NO_INSTI,NAME_OF_AUTH,MOBILE_NO_AUTH,EMAIL_OF_AUTH,EMAIL_OF_INSTI,LOAN_AMOUNT,SECURED_AMOUNT,INSTALL_AMOUNT,NO_OF_INSTALL,LOAN_DUEDATE) VALUES(?,SYSDATE,?,?,?,?,?,?,?,?,?,?,?,?,TO_DATE(?,'DD/MM/YYYY'))";
    
    public static final String IGRS_CAVEATS_INSERT_BYBANK="INSERT INTO IGRS_CAVEAT_BANK_TXN (CAVEAT_BANK_TXN_ID,OTT_ID,LOAN_ACCOUNT_NO,LOAN_START_DATE,LOAN_END_DATE,LOAN_AMOUNT,LOAN_SECURED_AMOUNT,NO_OF_INSTALLMENTS,BANK_NAME,BANK_ADDRESS,BANK_REP_NAME,DOCUMENT_NAME,UPLOADED_DOC,REMARKS,REGISTRATION_ID,CAVEAT_STATUS,CAVEAT_LOGGED_DATE,BANK_PERSON_CONTACT_NO,BANK_PERSON_EMAIL_ID,CREATED_BY,CREATED_DATE)VALUES(?,?,?,TO_DATE(?,'DD/MM/YYYY'),TO_DATE(?,'DD/MM/YYYY'),?,?,?,?,?,?,?,?,?,?,?,TO_DATE(TO_CHAR(SYSDATE,'DD/MM/YYYY'),'DD/MM/YYYY'),?,?,?,SYSDATE)";
    
    //Query For Searching Registration ID from Registration Transaction Table.
    public static final String IGRS_CAVEATS_REGID_SEARCH_IN_REG_TABLE="SELECT REGISTRATION_NUMBER FROM IGRS_REG_TXN_DETLS WHERE REGISTRATION_NUMBER=?";
    
    /*public static final String GET_CAVEATS_REGID_PROPERTYID="SELECT REGC.REG_INIT_ID, REGI.PROPERTY_ID, REGI.PROP_TYPE_ID, TYP.PROPERTY_TYPE_NAME " +
    		"FROM IGRS_REG_PROPRTY_DTLS REGI, IGRS_PROPERTY_TYPE_MASTER TYP , IGRS_REG_COMPLETION_DETAILS REGC " +
    		"WHERE REGI.PROPERTY_ID IS NOT NULL AND " +
    		"REGI.PROP_TYPE_ID = TYP.PROPERTY_TYPE_ID AND " +
    		"REGI.REG_TXN_ID = REGC.REG_INIT_ID AND REGC.REG_COMP_NUMBER = ?";*/
    
    
    
    public static final String GET_CAVEATS_REGID_PROPERTYID="SELECT REGC.REG_TXN_ID,"+
  "  REGI.PROPERTY_ID,"+
   " REGI.PROP_TYPE_ID,"+
  "  TYP.PROPERTY_TYPE_NAME,"+
  "  ism.prop_val_req_flag"+
"  FROM IGRS_REG_PROPRTY_DTLS REGI,"+
  "  IGRS_PROPERTY_TYPE_MASTER TYP ,"+
  "  IGRS_REG_TXN_DETLS REGC,"+
  "  IGRS_DEED_INSTRUMENT_MASTER ism"+
  " WHERE REGI.PROPERTY_ID      IS NOT NULL"+
  " AND REGI.PROP_TYPE_ID        = TYP.PROPERTY_TYPE_ID"+
 "  AND REGI.REG_TXN_ID          = REGC.REG_TXN_ID"+
  " AND regc.instruments_id = ism.instrument_id"+
  " AND REGC.REGISTRATION_NUMBER = ?";
    
    
    
    
    
    
    
    //RegInit1225185324771
    
  //  public static final String GET_CAVEATS_TXN_ID = "SELECT CONCAT('CTXN', LPAD(IGRS_CAVEAT_MASTER_SEQ.NEXTVAL, 16, '0')) AS CVTTXN FROM DUAL";
    
    public static final String CAVEATS_PAYMENT_TXN_ID = "SELECT  IGRS_CAVEAT_MASTER_SEQ.NEXTVAL FROM DUAL";
    
   
    public static final String CAVETAS_PAYTXN_INSERT = "INSERT INTO IGRS_CAVEAT_PAYMENT_DETAILS  (TRANSACTION_ID,CAVEAT_TXN_ID,PAYMENT_FLAG,FUNCTION_ID,CREATED_BY,CREATED_DATE,PAYABLE_AMOUNT)  VALUES (?,?,?,?,?,SYSDATE,?)";
   //ADDED FOR DASHBOARD
   public static final String CAVEATS_DASHBOARD="SELECT NVL(CT.TRANSACTION_ID,'-'), "+
  " NVL(CM.CAVEAT_TYPE_NAME,'-'), "+
 "  NVL(CP.PAID_AMOUNT,'0'), "+
 "  CT.AMOUNT, "+
 "  (CT.AMOUNT-CP.PAID_AMOUNT)DUE_AMOUNT, "+
 "  CP.UPDATED_DATE, "+
 "  TO_CHAR((CT.CREATED_DATE),'dd/mm/yyyy') CREATED_DATE "+
   
" FROM IGRS_CAVEAT_TXN CT, "+
 "  IGRS_CAVEAT_TYPE_MASTER CM, "+
 " (SELECT IGRS_CAVEAT_PAYMENT_DETAILS.CAVEAT_TXN_ID, "+
 "    SUM(IGRS_CAVEAT_PAYMENT_DETAILS.PAID_AMOUNT) PAID_AMOUNT, "+
  "   TO_CHAR(MAX(IGRS_CAVEAT_PAYMENT_DETAILS.UPDATE_DATE), 'dd/mm/yyyy') UPDATED_DATE "+
 "  FROM IGRS_CAVEAT_PAYMENT_DETAILS "+
 "  WHERE IGRS_CAVEAT_PAYMENT_DETAILS.PAYMENT_FLAG !='C' "+
 "  GROUP BY IGRS_CAVEAT_PAYMENT_DETAILS.CAVEAT_TXN_ID "+
  " ) CP "+
 " WHERE CT.TRANSACTION_ID = CP.CAVEAT_TXN_ID "+
 " AND CT.CAVEAT_TYPE_ID   = CM.CAVEAT_TYPE_ID "+
 " AND CT.CAVEAT_STATUS    = 'INITIATED'"+
 " AND CT.CREATED_BY       = '";
 
   
   public static final String CAVEATS_DASHBOARD_HI="SELECT NVL(CT.TRANSACTION_ID,'-'), "+
   " NVL(CM.H_CAVEAT_TYPE_NAME,'-'), "+
  "  NVL(CP.PAID_AMOUNT,'0'), "+
  "  CT.AMOUNT, "+
  "  (CT.AMOUNT-CP.PAID_AMOUNT)DUE_AMOUNT, "+
  "  CP.UPDATED_DATE, "+
  "  TO_CHAR((CT.CREATED_DATE),'dd/mm/yyyy') CREATED_DATE "+
    
 " FROM IGRS_CAVEAT_TXN CT, "+
  "  IGRS_CAVEAT_TYPE_MASTER CM, "+
  " (SELECT IGRS_CAVEAT_PAYMENT_DETAILS.CAVEAT_TXN_ID, "+
  "    SUM(IGRS_CAVEAT_PAYMENT_DETAILS.PAID_AMOUNT) PAID_AMOUNT, "+
   "   TO_CHAR(MAX(IGRS_CAVEAT_PAYMENT_DETAILS.UPDATE_DATE), 'dd/mm/yyyy') UPDATED_DATE "+
  "  FROM IGRS_CAVEAT_PAYMENT_DETAILS "+
  "  WHERE IGRS_CAVEAT_PAYMENT_DETAILS.PAYMENT_FLAG !='C' "+
  "  GROUP BY IGRS_CAVEAT_PAYMENT_DETAILS.CAVEAT_TXN_ID "+
   " ) CP "+
  " WHERE CT.TRANSACTION_ID = CP.CAVEAT_TXN_ID "+
  " AND CT.CAVEAT_TYPE_ID   = CM.CAVEAT_TYPE_ID "+
  " AND CT.CAVEAT_STATUS    = 'INITIATED'"+
  " AND CT.CREATED_BY       = '";

   
   public static final String CAVEATS_DASHBOARD_ORDER="ORDER BY CREATED_DATE DESC";

    public static final String CAVEATS_PARTIAL="SELECT DISTINCT NVL(CT.TRANSACTION_ID,'-'), "+
    "(CP.PAYABLE_AMOUNT-(NVL(CP.PAID_AMOUNT,0)))DUE_AMOUNT  "+
    "FROM IGRS_CAVEAT_TXN CT,  "+
      "IGRS_CAVEAT_TYPE_MASTER CM,  "+
      "(SELECT CAVEAT_TXN_ID,  "+
        "SUM(NVL(PAID_AMOUNT,0)) PAID_AMOUNT,  "+
        "MAX(NVL(amount,0))PAYABLE_AMOUNT  "+
      "FROM IGRS_CAVEAT_PAYMENT_DETAILS C,  "+
        "IGRS_CAVEAT_TXN T  "+
      "WHERE T.TRANSACTION_ID=c.CAVEAT_TXN_ID  "+
      "GROUP BY c.CAVEAT_TXN_ID  "+
      ")CP  "+
    "WHERE CT.TRANSACTION_ID = CP.CAVEAT_TXN_ID  "+
    "AND CT.TRANSACTION_ID   =  ";

    public static final String CAVEATS_PAYMENT_STATUS="UPDATE IGRS_CAVEAT_PAYMENT_DETAILS SET PAYMENT_FLAG='C' WHERE CAVEAT_TXN_ID=?";
    public static final String CAVEATS_LOG_STATUS="UPDATE IGRS_CAVEAT_TXN SET CAVEAT_STATUS='LOGGED' WHERE TRANSACTION_ID=?";
    

    //
    
    public static final String GET_BANKCAVEATS_TXN_ID = "SELECT CONCAT('CTXN', LPAD(IGRS_BANKCAVEAT_SEQ.NEXTVAL, 16, '0')) AS CVTTXN FROM DUAL";
    //modified by ashima-------//
    public static final String LOG_CAVEATS_NONBANK="INSERT INTO IGRS_CAVEAT_TXN " +
    		"(TRANSACTION_ID,INSTITUTE_NAME,INSTITUTE_ADDRESS,INSTITUTE_REP_NAME,COUNTRY_ID,STATE_ID,DISTRICT_ID,POSTAL_CODE,PHONE_NUMBER,CASE_NUMBER,COURT_ORDER_DATE," +
    		"CAVEAT_TYPE_ID,STAY_ORDER_NO,STAY_ORDER_DETAILS,CAVEAT_DETAILS,DOCUMENT_NAME,UPLOADED_DOC,REMARKS,REGISTRATION_ID," +
    		"CAVEAT_STATUS,CAVEAT_LOGGED_DATE,CREATED_BY,CREATED_DATE,STAY_ORDER_START_DATE,STAY_ORDER_UPTO_DATE, PROPERTY_TXN_LOCK,AMOUNT) " +
    		"values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,SYSDATE,?,SYSDATE,?,?,?,?)";
    //------------------------------------------------
    public static final String LOG_CAVEATS_BANK = "INSERT INTO IGRS_CAVEAT_BANK_TXN " +
    		"( CAVEAT_BANK_TXN_ID , OTT_ID , CAVEAT_TYPE_ID , BANK_NAME , BANK_ADDRESS , BANK_REP_NAME , BANK_PERSON_CONTACT_NO , " +
    		"BANK_PERSON_EMAIL_ID , LOAN_ACCOUNT_NO , LOAN_AMOUNT , LOAN_SECURED_AMOUNT , INSTALLMENT_AMOUNT , NO_OF_INSTALLMENTS , " +
    		"LOAN_END_DATE , REGISTRATION_ID , CREATED_BY , CAVEAT_STATUS , " +
    		"CAVEAT_LOGGED_DATE , CREATED_DATE,PAID_STAMP_DUTY,LOAN_PURPOSE,TYPE_MORTGAGE,DATE_REG,SUPPLEDOC_EREG_NUMBER ) VALUES " +
    		"( ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , TO_DATE(?,'DD/MM/YYYY') , ? , ? , 'LOGGED' , SYSDATE , SYSDATE ,?,?,?,?,?) "; 
    public static final String LOG_CAVEATS_PROPERTY_MAP="INSERT INTO IGRS_CAVEAT_PROPERTY_MAP ( CAVEAT_TXN_ID, PROPERTY_TXN_ID, CAVEAT_PROPERTY_MAP_ID) VALUES " +
    		"(?,?,IGRS_CAVEAT_PROP_MAP_SEQ.NEXTVAL)";
    /*
    public static final String BASE_CAVEATS_QUERY =" SELECT CTX.TRANSACTION_ID, CTX.INSTITUTE_NAME, CTX.INSTITUTE_ADDRESS, CTX.INSTITUTE_REP_NAME,CTX.COUNTRY_ID, CTX.STATE_ID, CTX.DISTRICT_ID, CTX.POSTAL_CODE, CTX.PHONE_NUMBER, CTX.CAVEAT_TYPE_ID, CTX.STAY_ORDER_NO, CTX.STAY_ORDER_DETAILS,CTX.CAVEAT_DETAILS, CTX.DOCUMENT_NAME, DNT.UPLOADED_DOC_PATH, CTX.REMARKS, CTX.REGISTRATION_ID, CTX.CAVEAT_STATUS,TO_CHAR(CTX.CAVEAT_LOGGED_DATE,'DD/MM/YYYY') AS CAVEAT_LOGGED_DATE, TO_CHAR(CTX.CAVEAT_RELEASE_DATE,'DD/MM/YYYY') AS CAVEAT_RELEASE_DATE,CTX.REASON_FOR_RELEASE, CTX.REMARKS_FOR_RELEASE, CTX.CREATED_BY, CTX.CREATED_DATE, CTX.UPDATE_BY, CTX.UPDATE_DATE, CTM.CAVEAT_TYPE_NAME, CRM.COUNTRY_NAME, STM.STATE_NAME, DTM.DISTRICT_NAME, TO_CHAR(CTX.STAY_ORDER_START_DATE,'DD/MM/YYYY') AS STAY_ORDER_START_DATE,TO_CHAR(CTX.STAY_ORDER_UPTO_DATE,'DD/MM/YYYY') AS STAY_ORDER_UPTO_DATE, CTX.RELEASE_DOC, CTX.PROPERTY_TXN_LOCK, CTX.RELEASE_DOC_NAME FROM IGRS_CAVEAT_TXN CTX, IGRS_CAVEAT_TYPE_MASTER CTM, IGRS_COUNTRY_MASTER CRM, IGRS_STATE_MASTER STM, IGRS_DISTRICT_MASTER DTM,IGRS_CAVEAT_DOC_DTLS DNT WHERE 1=1 AND CTX.CAVEAT_TYPE_ID = CTM.CAVEAT_TYPE_ID AND CTX.COUNTRY_ID = CRM.COUNTRY_ID AND CTX.STATE_ID = STM.STATE_ID AND CTX.DISTRICT_ID = DTM.DISTRICT_ID AND CTX.TRANSACTION_ID=DNT.TRANSACTION_ID ";
    public static final String CAVEATS_QUERY_TXN_CLAUSE = " AND CTX.TRANSACTION_ID = ?";
    public static final String CAVEATS_QUERY_REGN_CLAUSE = " AND CTX.REGISTRATION_ID = ?";
    public static final String CAVEATS_QUERY_STATUS_CLAUSE = " AND CTX.CAVEAT_STATUS = ?";
    public static final String CAVEATS_QUERY_DATE_BOTH_CLAUSE = " AND (CTX.CREATED_DATE BETWEEN TO_DATE(?,'DD/MM/YYYY') AND TO_DATE(?,'DD/MM/YYYY')+1)";
    public static final String CAVEATS_QUERY_DATE_FROM_CLAUSE = " AND (CTX.CREATED_DATE BETWEEN TO_DATE(?,'DD/MM/YYYY') AND SYSDATE)";
    
    
   public static final String CAVEATS_QUERY_DATE_TO_CLAUSE = " AND (CTX.CREATED_DATE BETWEEN (SELECT MIN(CAVEAT_LOGGED_DATE) FROM IGRS_CAVEAT_TXN) AND TO_DATE(?,'DD/MM/YYYY')+1) ";
   public static final String CAVEATS_QUERY_ORDER=" ORDER BY CAVEAT_LOGGED_DATE ASC";
   */
    
    //added by ashima
    
    public static final String BASE_CAVEATS_QUERY =" SELECT CTX.TRANSACTION_ID, CTX.INSTITUTE_NAME, CTX.INSTITUTE_ADDRESS, CTX.INSTITUTE_REP_NAME,CTX.COUNTRY_ID, CTX.STATE_ID, CTX.DISTRICT_ID, CTX.POSTAL_CODE, CTX.PHONE_NUMBER, CTX.CAVEAT_TYPE_ID, CTX.STAY_ORDER_NO, CTX.STAY_ORDER_DETAILS, CTX.CAVEAT_DETAILS, CTX.DOCUMENT_NAME, DNT.UPLOADED_DOC_PATH, CTX.REMARKS, CTX.REGISTRATION_ID, CTX.CAVEAT_STATUS, CTX.CAVEAT_LOGGED_DATE, TO_CHAR(CTX.CAVEAT_RELEASE_DATE,'DD/MM/YYYY') AS CAVEAT_RELEASE_DATE, CTX.REASON_FOR_RELEASE, CTX.REMARKS_FOR_RELEASE, CTX.CREATED_BY, CTX.CREATED_DATE, CTX.UPDATE_BY, CTX.UPDATE_DATE, CTM.CAVEAT_TYPE_NAME, CRM.COUNTRY_NAME, STM.STATE_NAME, DTM.DISTRICT_NAME, TO_CHAR(CTX.STAY_ORDER_START_DATE,'DD/MM/YYYY') AS STAY_ORDER_START_DATE,TO_CHAR(CTX.STAY_ORDER_UPTO_DATE,'DD/MM/YYYY') AS STAY_ORDER_UPTO_DATE, CTX.RELEASE_DOC, CTX.PROPERTY_TXN_LOCK, CTX.RELEASE_DOC_NAME,  CTX.CASE_NUMBER,TO_CHAR(CTX.COURT_ORDER_DATE,'DD/MM/YYYY') FROM IGRS_CAVEAT_TXN CTX, IGRS_CAVEAT_TYPE_MASTER CTM, IGRS_COUNTRY_MASTER CRM, IGRS_STATE_MASTER STM, IGRS_DISTRICT_MASTER DTM, IGRS_CAVEAT_DOC_DTLS DNT WHERE 1=1 AND CTX.CAVEAT_TYPE_ID = CTM.CAVEAT_TYPE_ID AND CTX.COUNTRY_ID = CRM.COUNTRY_ID AND CTX.STATE_ID = STM.STATE_ID AND CTX.DISTRICT_ID = DTM.DISTRICT_ID AND CTX.TRANSACTION_ID=DNT.TRANSACTION_ID ";
    public static final String CAVEATS_QUERY_TXN_CLAUSE = " AND CTX.TRANSACTION_ID = ?";
    public static final String CAVEATS_QUERY_REGN_CLAUSE = " AND CTX.REGISTRATION_ID = ?";
    public static final String CAVEATS_QUERY_STATUS_CLAUSE = " AND CTX.CAVEAT_STATUS = ?";
    public static final String CAVEATS_QUERY_DATE_BOTH_CLAUSE = " AND (CTX.CREATED_DATE BETWEEN TO_DATE(?,'DD/MM/YYYY') AND TO_DATE(?,'DD/MM/YYYY')+1)";
    public static final String CAVEATS_QUERY_DATE_FROM_CLAUSE = " AND (CTX.CREATED_DATE BETWEEN TO_DATE(?,'DD/MM/YYYY') AND SYSDATE)";
    
    public static final String BASE_CAVEATS_QUERY_HI =" SELECT CTX.TRANSACTION_ID, CTX.INSTITUTE_NAME, CTX.INSTITUTE_ADDRESS, CTX.INSTITUTE_REP_NAME,CTX.COUNTRY_ID, CTX.STATE_ID, CTX.DISTRICT_ID, CTX.POSTAL_CODE, CTX.PHONE_NUMBER, CTX.CAVEAT_TYPE_ID, CTX.STAY_ORDER_NO, CTX.STAY_ORDER_DETAILS, CTX.CAVEAT_DETAILS, CTX.DOCUMENT_NAME, DNT.UPLOADED_DOC_PATH, CTX.REMARKS, CTX.REGISTRATION_ID, CTX.CAVEAT_STATUS, CTX.CAVEAT_LOGGED_DATE, TO_CHAR(CTX.CAVEAT_RELEASE_DATE,'DD/MM/YYYY') AS CAVEAT_RELEASE_DATE, CTX.REASON_FOR_RELEASE, CTX.REMARKS_FOR_RELEASE, CTX.CREATED_BY, CTX.CREATED_DATE, CTX.UPDATE_BY, CTX.UPDATE_DATE, CTM.H_CAVEAT_TYPE_NAME, CRM.H_COUNTRY_NAME, STM.H_STATE_NAME, DTM.H_DISTRICT_NAME, TO_CHAR(CTX.STAY_ORDER_START_DATE,'DD/MM/YYYY') AS STAY_ORDER_START_DATE,TO_CHAR(CTX.STAY_ORDER_UPTO_DATE,'DD/MM/YYYY') AS STAY_ORDER_UPTO_DATE, CTX.RELEASE_DOC, CTX.PROPERTY_TXN_LOCK, CTX.RELEASE_DOC_NAME,  CTX.CASE_NUMBER,TO_CHAR(CTX.COURT_ORDER_DATE,'DD/MM/YYYY') FROM IGRS_CAVEAT_TXN CTX, IGRS_CAVEAT_TYPE_MASTER CTM, IGRS_COUNTRY_MASTER CRM, IGRS_STATE_MASTER STM, IGRS_DISTRICT_MASTER DTM, IGRS_CAVEAT_DOC_DTLS DNT WHERE 1=1 AND CTX.CAVEAT_TYPE_ID = CTM.CAVEAT_TYPE_ID AND CTX.COUNTRY_ID = CRM.COUNTRY_ID AND CTX.STATE_ID = STM.STATE_ID AND CTX.DISTRICT_ID = DTM.DISTRICT_ID AND CTX.TRANSACTION_ID=DNT.TRANSACTION_ID ";
    public static final String CAVEATS_QUERY_STATUS_CLAUSE_HI = " AND CTX.H_CAVEAT_STATUS = ?";

   public static final String CAVEATS_QUERY_DATE_TO_CLAUSE = " AND (CTX.CREATED_DATE BETWEEN (SELECT MIN(CAVEAT_LOGGED_DATE) FROM IGRS_CAVEAT_TXN) AND TO_DATE(?,'DD/MM/YYYY')+1) ";
   public static final String CAVEATS_QUERY_ORDER=" ORDER BY CAVEAT_LOGGED_DATE ASC ";
    
    //
    
    
    
    
    
    
   ///change done in reg.property_id
    public static final String GET_CAVEATS_SELECTED_PROPS = "SELECT CTX.REGISTRATION_ID, CPM.PROPERTY_TXN_ID, TYP.PROPERTY_TYPE_ID, TYP.PROPERTY_TYPE_NAME"  +
    		" FROM IGRS_CAVEAT_PROPERTY_MAP CPM, IGRS_CAVEAT_TXN CTX, IGRS_PROPERTY_TYPE_MASTER TYP, IGRS_REG_PROPRTY_DTLS REG " +
    		"WHERE 1= 1 AND CPM.CAVEAT_TXN_ID = CTX.TRANSACTION_ID AND REG.PROPERTY_ID = CPM.PROPERTY_TXN_ID AND " +
    		"REG.PROP_TYPE_ID = TYP.PROPERTY_TYPE_ID AND CPM.CAVEAT_TXN_ID = ?";
    public static final String GET_CAVEATS_SELECTED_PROPS_hi = "SELECT CTX.REGISTRATION_ID, CPM.PROPERTY_TXN_ID, TYP.PROPERTY_TYPE_ID, TYP.H_PROPERTY_TYPE_NAME"  +
	" FROM IGRS_CAVEAT_PROPERTY_MAP CPM, IGRS_CAVEAT_TXN CTX, IGRS_PROPERTY_TYPE_MASTER TYP, IGRS_REG_PROPRTY_DTLS REG " +
	"WHERE 1= 1 AND CPM.CAVEAT_TXN_ID = CTX.TRANSACTION_ID AND REG.PROPERTY_ID = CPM.PROPERTY_TXN_ID AND " +
	"REG.PROP_TYPE_ID = TYP.PROPERTY_TYPE_ID AND CPM.CAVEAT_TXN_ID = ?";
    /*public static final String GET_BANK_CAVEATS_PROPERTYID = "SELECT REGI.PROPERTY_ID, REGC.REG_COMP_NUMBER, REGI.PIN_NO " +
    		"FROM IGRS_REG_PROPRTY_DTLS REGI, IGRS_REG_COMPLETION_DETAILS REGC " +
    		"WHERE REGI.PROPERTY_ID IS NOT NULL " +
    		"AND REGI.REG_TXN_ID = REGC.REG_INIT_ID " +
    		"AND REGC.REG_COMP_NUMBER = ? ";*/
    public static final String GET_BANK_CAVEATS_PROPERTYID="SELECT REGI.PROPERTY_ID, REGC.REGISTRATION_NUMBER,REGI.PIN_NO,REGI.PIN_FLAG FROM IGRS_REG_PROPRTY_DTLS REGI,IGRS_REG_TXN_DETLS REGC WHERE REGI.PROPERTY_ID IS NOT NULL AND REGI.REG_TXN_ID = REGC.REG_TXN_ID AND REGC.REGISTRATION_NUMBER = ?";
    //MODIFIED BY ASHIMA
    //public static final String GET_BANK_CAVEATS_PROPERTYID="SELECT REGI.PROPERTY_ID, REGC.REGISTRATION_NUMBER,REGI.PIN_NO,REGI.PIN_FLAG FROM IGRS_REG_PROPRTY_DTLS REGI,IGRS_REG_TXN_DETLS REGC WHERE REGI.PROPERTY_ID IS NOT NULL AND REGI.REG_TXN_ID = REGC.REG_TXN_ID AND REGI.PIN_FLAG !='D' AND REGC.REGISTRATION_NUMBER = ?";
    
    public static final String GET_OTT_VALID_ATTRIB_VAL = "SELECT ATTRIBUTE_VALUE FROM IGRS_CONFIG_PARAM_LIST WHERE MODULE_ID = 'MOD_06' AND ATTRIBUTE_STATUS = 'A' AND ATTRIBUTE_NAME = ?";
    
    public static final String GET_NEXT_OTT_ID = "SELECT CONCAT('OTT', LPAD(IGRS_CAVEAT_OTT_SEQ.NEXTVAL, 17, '0')) AS OTT_ID FROM DUAL";
    
    public static final String INSERT_OTT_DETAILS = "INSERT INTO IGRS_LOAN_OTT_MASTER " +
    		"( REGISTRATION_ID, OTT_ID, DATE_OF_CREATION, DATE_OF_EXPIRY, OTT_STATUS, CREATED_BY, CREATED_DATE)" +
    		" VALUES ( ?, ?, SYSDATE, (SYSDATE + ?), 'A', ?, SYSDATE) ";
    
    public static final String GET_OTT_DATES = "SELECT TO_CHAR(DATE_OF_CREATION, 'DD/MM/YYYY') AS DATE_OF_CREATION, " +
    		"TO_CHAR(DATE_OF_EXPIRY, 'DD/MM/YYYY') AS DATE_OF_EXPIRY FROM IGRS_LOAN_OTT_MASTER WHERE OTT_ID = ?";
    
    public static final String INSERT_OTT_PROP_MAPPING = "INSERT INTO IGRS_OTT_PROP_MAPPING " +
    		"( OTT_MAPPING_ID, REGISTRATION_ID, OTT_ID, PROPERTY_TXN_ID ) " +
    		"VALUES ( IGRS_OTT_MAPPING_SEQ.NEXTVAL, ?, ?, ? )";
    
    /*public static final String GET_ACTIVE_REG_OTT_SEARCH_RESULT = "SELECT PM.REGISTRATION_ID, PM.OTT_ID, PM.PROPERTY_TXN_ID FROM " +
    		"IGRS_OTT_PROP_MAPPING PM , IGRS_LOAN_OTT_MASTER OM WHERE PM.OTT_ID = OM.OTT_ID AND " +
    		"PM.REGISTRATION_ID = OM.REGISTRATION_ID AND OM.OTT_STATUS = 'A' AND PM.REGISTRATION_ID = ? AND PM.OTT_ID = ?  AND OM.CREATED_BY = ?";
    */
    //ashima
    public static final String GET_ACTIVE_REG_OTT_SEARCH_RESULT = "SELECT PM.REGISTRATION_ID,PM.OTT_ID,PM.PROPERTY_TXN_ID FROM IGRS_OTT_PROP_MAPPING PM ,IGRS_LOAN_OTT_MASTER OM WHERE PM.REGISTRATION_ID = OM.REGISTRATION_ID AND PM.OTT_ID = OM.OTT_ID AND OM.OTT_STATUS  = 'A' AND PM.REGISTRATION_ID = ? AND PM.OTT_ID = ? ";
    
    
    
    public static final String GET_ALL_REG_OTT_SEARCH_RESULT = "SELECT PM.REGISTRATION_ID, PM.OTT_ID, PM.PROPERTY_TXN_ID FROM " +
    		"IGRS_OTT_PROP_MAPPING PM , IGRS_LOAN_OTT_MASTER OM WHERE PM.OTT_ID = OM.OTT_ID AND " +
    		"PM.REGISTRATION_ID = OM.REGISTRATION_ID AND PM.REGISTRATION_ID = ? AND PM.OTT_ID = ? ";
    
    public static final String UPDATE_OTT_STATUS = "UPDATE IGRS_LOAN_OTT_MASTER SET OTT_STATUS = 'D', UPDATE_BY = ?, UPDATE_DATE = SYSDATE WHERE OTT_ID = ?";
    
    public static final String SEARCH_BANK_CAVEAT_DTLS_RELEASE = "SELECT CAVEAT_BANK_TXN_ID, OTT_ID, LOAN_ACCOUNT_NO, " +
    		"TO_CHAR(LOAN_END_DATE, 'DD/MM/YYYY') AS LOAN_END_DATE, LOAN_AMOUNT, LOAN_SECURED_AMOUNT, " +
    		"NO_OF_INSTALLMENTS, BANK_NAME, BANK_ADDRESS, BANK_REP_NAME, REGISTRATION_ID, " +
    		"TO_CHAR(CAVEAT_LOGGED_DATE, 'DD/MM/YYYY') AS CAVEAT_LOGGED_DATE, BANK_PERSON_CONTACT_NO, " +
    		"BANK_PERSON_EMAIL_ID, INSTALLMENT_AMOUNT,PAID_STAMP_DUTY,LOAN_PURPOSE,TYPE_MORTGAGE,DATE_REG,SUPPLEDOC_EREG_NUMBER FROM IGRS_CAVEAT_BANK_TXN " +
    		"WHERE CAVEAT_BANK_TXN_ID = ? AND CREATED_BY = ? AND CAVEAT_STATUS = 'LOGGED'";
    
	public static final String SEARCH_BANK_CAVEAT_DTLS_VIEW_BASE_QUERY = "SELECT CTX.CAVEAT_BANK_TXN_ID, CTX.OTT_ID, CTX.LOAN_ACCOUNT_NO, " +
			"TO_CHAR(CTX.LOAN_END_DATE, 'DD/MM/YYYY') AS LOAN_END_DATE, CTX.LOAN_AMOUNT, CTX.LOAN_SECURED_AMOUNT, CTX.NO_OF_INSTALLMENTS, " +
			"CTX.BANK_NAME, CTX.BANK_ADDRESS, CTX.BANK_REP_NAME, CTX.REGISTRATION_ID, " +
			"TO_CHAR(CTX.CAVEAT_LOGGED_DATE, 'DD/MM/YYYY') AS CAVEAT_LOGGED_DATE, CTX.BANK_PERSON_CONTACT_NO, CTX.BANK_PERSON_EMAIL_ID, " +
			"CTX.INSTALLMENT_AMOUNT, CTX.CAVEAT_STATUS, TO_CHAR(CTX.CAVEAT_RELEASE_DATE, 'DD/MM/YYYY') AS CAVEAT_RELEASE_DATE, " +
			"CTX.REMARKS_FOR_RELEASE, CTX.REASON_FOR_RELEASE,CTX.PAID_STAMP_DUTY,CTX.LOAN_PURPOSE,CTX.TYPE_MORTGAGE,CTX.DATE_REG,CTX.SUPPLEDOC_EREG_NUMBER FROM IGRS_CAVEAT_BANK_TXN CTX WHERE 1 = 1 ";
	
	public static final String BANK_CAVEAT_QUERY_USER_CLAUSE = " AND CTX.CREATED_BY = ?";
	public static final String BANK_CAVEAT_QUERY_TXN_CLAUSE = " AND CTX.CAVEAT_BANK_TXN_ID = ?";
    public static final String BANK_CAVEAT_QUERY_REGN_CLAUSE = " AND CTX.REGISTRATION_ID = ?";
    public static final String BANK_CAVEAT_QUERY_STATUS_CLAUSE = " AND CTX.CAVEAT_STATUS = ?";
   
    public static final String BANK_CAVEAT_QUERY_DATE_BOTH_CLAUSE = " AND (CTX.CREATED_DATE BETWEEN TO_DATE(?,'DD/MM/YYYY') AND TO_DATE(?,'DD/MM/YYYY')+1)";
    public static final String BANK_CAVEAT_QUERY_DATE_FROM_CLAUSE = " AND (CTX.CREATED_DATE BETWEEN TO_DATE(?,'DD/MM/YYYY') AND SYSDATE)";
    public static final String BANK_CAVEAT_QUERY_DATE_TO_CLAUSE = " AND (CTX.CREATED_DATE BETWEEN (SELECT MIN(CAVEAT_LOGGED_DATE) FROM IGRS_CAVEAT_BANK_TXN) AND TO_DATE(?,'DD/MM/YYYY')+1)";
    
    
    public static final String SEARCH_OTT_PROPERTY_MAPPING = "SELECT PROPERTY_TXN_ID FROM IGRS_OTT_PROP_MAPPING WHERE OTT_ID = ?";
	public static final String GET_BANK_VALID_USER_ROLE_NAME = "SELECT DISTINCT(RM.ROLE_NAME) FROM " +
			"IGRS_ROLE_MASTER RM, IGRS_ROLE_GROUP_MASTER GM, IGRS_RGROUP_ROLE_MAPPING GP, IGRS_USER_ROLE_GROUP_MAPPING UG " +
			"WHERE RM.ROLE_ID = GP.ROLE_ID AND GM.ROLE_GROUP_ID = GP.ROLE_GROUP_ID AND RM.ROLE_STATUS = 'A' " +
			"AND GM.ROLE_GROUP_STATUS = 'A' AND UG.ROLE_GROUP_ID = GM.ROLE_GROUP_ID AND UG.USER_ID = ? " +
			"AND RM.ROLE_NAME IN (SELECT CM.ATTRIBUTE_VALUE FROM IGRS_CONFIG_PARAM_LIST CM WHERE CM.ATTRIBUTE_STATUS = 'A' AND CM.ATTRIBUTE_NAME = ? )";
	
	public static final String GET_DRS_OFFICIAL_USER_ID_CHECK = "SELECT DISTINCT ROM.ROLE_NAME " +
			"FROM IGRS_USER_ROLE_GROUP_MAPPING UGM, IGRS_RGROUP_ROLE_MAPPING RGM, IGRS_ROLE_MASTER ROM " +
			"WHERE UGM.ROLE_GROUP_ID = RGM.ROLE_GROUP_ID AND ROM.ROLE_ID = RGM.ROLE_ID AND " +
			"USER_ID = ? AND ROM.ROLE_NAME = " +
			"( SELECT ATTRIBUTE_VALUE FROM IGRS_CONFIG_PARAM_LIST WHERE MODULE_ID = 'MOD_06' AND ATTRIBUTE_STATUS = 'A' AND ATTRIBUTE_NAME = ? )";
	
	public static final String SEARCH_BANK_OTT_VIEW_BASE_QUERY = "SELECT OTT_ID, REGISTRATION_ID, DECODE(OTT_STATUS, 'A', 'Activated', 'D', 'Deactivated', 'E', 'Expired') AS OTT_STATUS, TO_CHAR(DATE_OF_CREATION, 'DD/MM/YYYY') AS DATE_OF_CREATION, TO_CHAR( DATE_OF_EXPIRY, 'DD/MM/YYYY')  AS DATE_OF_EXPIRY FROM IGRS_LOAN_OTT_MASTER WHERE 1=1";
	public static final String SEARCH_BANK_OTT_VIEW_BASE_QUERY_hi = "SELECT OTT_ID, REGISTRATION_ID, DECODE(OTT_STATUS, 'A', 'सक्रिय', 'D', 'निष्क्रिय ', 'E', 'समय सीमा समाप्त') AS OTT_STATUS, TO_CHAR(DATE_OF_CREATION, 'DD/MM/YYYY') AS DATE_OF_CREATION, TO_CHAR( DATE_OF_EXPIRY, 'DD/MM/YYYY')  AS DATE_OF_EXPIRY FROM IGRS_LOAN_OTT_MASTER WHERE 1=1";

	public static final String OTT_CAVEAT_QUERY_USER_CLAUSE = " AND CREATED_BY = ?";
	public static final String OTT_CAVEAT_QUERY_OTT_CLAUSE = " AND OTT_ID = ?";
    public static final String OTT_CAVEAT_QUERY_REGN_CLAUSE = " AND REGISTRATION_ID = ?";
    public static final String OTT_CAVEAT_QUERY_STATUS_CLAUSE = " AND OTT_STATUS = ?";
    public static final String OTT_CAVEAT_QUERY_DATE_BOTH_CLAUSE = " AND (DATE_OF_CREATION BETWEEN TO_DATE(?,'DD/MM/YYYY') AND TO_DATE(?,'DD/MM/YYYY')+1)";
    public static final String OTT_CAVEAT_QUERY_DATE_FROM_CLAUSE = " AND (DATE_OF_CREATION BETWEEN TO_DATE(?,'DD/MM/YYYY') AND SYSDATE)";
    public static final String OTT_CAVEAT_QUERY_DATE_TO_CLAUSE = " AND (DATE_OF_CREATION BETWEEN (SELECT MIN(DATE_OF_CREATION) FROM IGRS_LOAN_OTT_MASTER) AND TO_DATE(?,'DD/MM/YYYY')+1)";
	/*public static final String GET_STAY_ORDER_LOGGED_COUNT = "SELECT COUNT (CT.REGISTRATION_ID) AS REG_COUNT FROM " +
			"IGRS_CAVEAT_TXN CT, IGRS_CAVEAT_TYPE_MASTER CM WHERE " +
			"CT.STAY_ORDER_NO IS NOT NULL AND UPPER(CT.CAVEAT_STATUS) = 'LOGGED' AND " +
			"CT.CAVEAT_TYPE_ID = CM.CAVEAT_TYPE_ID AND " +
			"UPPER(CM.STAY_ORDER_STATUS) = 'Y' AND " +
			"CT.REGISTRATION_ID = ?";*/
    
    //ADDED BY ASHIMA FOR OTT ON 20 JAN
	public static final String GET_STAY_ORDER_LOGGED_COUNT = "SELECT COUNT (CT.REGISTRATION_ID) AS REG_COUNT FROM " +
	"IGRS_CAVEAT_BANK_TXN CT , IGRS_LOAN_OTT_MASTER CM WHERE " +
    " CT.REGISTRATION_ID = CM.REGISTRATION_ID AND " +
	" UPPER(CT.CAVEAT_STATUS) = 'LOGGED'  AND  " +
	"CT.REGISTRATION_ID = ?";
	/*public static final String GET_STAY_ORDER_LOGGED_COUNT_hi = "SELECT COUNT (CT.REGISTRATION_ID) AS REG_COUNT FROM " +
	"IGRS_CAVEAT_TXN CT, IGRS_CAVEAT_TYPE_MASTER CM WHERE " +
	"CT.STAY_ORDER_NO IS NOT NULL AND UPPER(CT.CAVEAT_STATUS) = 'LOGGED' AND " +
	"CT.CAVEAT_TYPE_ID = CM.CAVEAT_TYPE_ID AND " +
	"UPPER(CM.STAY_ORDER_STATUS) = 'Y'  AND " +
	"CT.REGISTRATION_ID = ?";*/
	
	public static final String GET_STAY_ORDER_LOGGED_COUNT_hi="SELECT COUNT (CT.REGISTRATION_ID) AS REG_COUNT FROM " +
	"IGRS_CAVEAT_BANK_TXN CT , IGRS_LOAN_OTT_MASTER CM WHERE " +
    " CT.REGISTRATION_ID = CM.REGISTRATION_ID AND " +
	" UPPER(CT.CAVEAT_STATUS) = 'LOGGED'  AND  " +
	"CT.REGISTRATION_ID = ?";
	
	public static final String GET_IVRS_DETAILS = "SELECT CAVEAT_STATUS FROM IGRS_CAVEAT_TXN txn ,  IGRS_CAVEAT_PROPERTY_MAP maps"+
" WHERE txn.REGISTRATION_ID =? and maps.property_txn_id=? and txn.transaction_id = maps.caveat_txn_id";
	
	public static final String GET_IVRS_DETAILS_1 = "SELECT CAVEAT_STATUS FROM IGRS_CAVEAT_BANK_TXN txn "+
" WHERE txn.REGISTRATION_ID =?";
	
	//Log protest changes by santosh
	public static final String GET_DISTRICT_DETAILS = "select district_name,district_id from IGRS_DISTRICT_MASTER where DISTRICT_STATUS='A' and district_id = (select district_id from IGRS_OFFICE_MASTER where office_id = ?)";

	public static final String GET_DISTRICT_DETAILS_H = "select h_district_name,district_id from IGRS_DISTRICT_MASTER where district_id = (select district_id from IGRS_OFFICE_MASTER where office_id = ? )";
	
   public static String TEHSIL_NAME_EN="SELECT distinct(T.TEHSIL_ID),T.TEHSIL_NAME FROM IGRS_TEHSIL_MASTER T,IGRS_GUIDELINE_MASTER_CHILD1 G WHERE T.TEHSIL_ID=G.TEHSIL_ID AND T.DISTRICT_ID=? AND T.TEHSIL_STATUS='A'";
	
	public static String TEHSIL_NAME_HI="SELECT distinct(T.TEHSIL_ID),T.H_TEHSIL_NAME FROM IGRS_TEHSIL_MASTER T,IGRS_GUIDELINE_MASTER_CHILD1 G WHERE T.TEHSIL_ID=G.TEHSIL_ID AND T.DISTRICT_ID=? AND T.TEHSIL_STATUS='A'";

	public static String AREA_NAME_EN="SELECT AREA_TYPE_ID,AREA_TYPE_NAME FROM IGRS_AREA_TYPE_MASTER WHERE  AREA_TYPE_STATUS='A'";
	
	public static String AREA_NAME_HI="SELECT AREA_TYPE_ID,H_AREA_TYPE_NAME FROM IGRS_AREA_TYPE_MASTER WHERE AREA_TYPE_STATUS='A'";
	
	//public static String AREA_NAME_EN_PARTN="SELECT AREA_TYPE_ID,AREA_TYPE_NAME FROM IGRS_AREA_TYPE_MASTER WHERE  AREA_TYPE_STATUS='A' AND AREA_TYPE_ID=1";
	
	//public static String AREA_NAME_HI_PARTN="SELECT AREA_TYPE_ID,H_AREA_TYPE_NAME FROM IGRS_AREA_TYPE_MASTER WHERE AREA_TYPE_STATUS='A' AND AREA_TYPE_ID=1";

	public static String SUB_AREA_NAME_EN="SELECT SUB_AREA_TYPE_ID,SUB_AREA_TYPE_NAME FROM IGRS_SUB_AREA_TYPE_MASTER WHERE AREA_TYPE_ID=? AND SUB_AREA_TYPE_STATUS='A'";
	
	public static String SUB_AREA_NAME_HI="SELECT SUB_AREA_TYPE_ID,H_SUB_AREA_TYPE_NAME FROM IGRS_SUB_AREA_TYPE_MASTER WHERE AREA_TYPE_ID=? AND SUB_AREA_TYPE_STATUS='A'";

	public static String SUB_AREA_NAME_EN_UR="SELECT distinct(S.SUB_AREA_TYPE_ID),S.SUB_AREA_TYPE_NAME FROM IGRS_SUB_AREA_TYPE_MASTER S,IGRS_GUIDELINE_MASTER_CHILD1 G WHERE S.AREA_TYPE_ID=G.AREA_TYPE_ID AND S.TEHSIL_ID=G.TEHSIL_ID AND S.SUB_AREA_TYPE_ID=G.SUB_AREA_TYPE_ID AND S.AREA_TYPE_ID=? AND S.SUB_AREA_TYPE_STATUS='A' AND S.TEHSIL_ID=?";
	
	public static String SUB_AREA_NAME_HI_UR="SELECT distinct(S.SUB_AREA_TYPE_ID),S.H_SUB_AREA_TYPE_NAME FROM IGRS_SUB_AREA_TYPE_MASTER S,IGRS_GUIDELINE_MASTER_CHILD1 G WHERE S.AREA_TYPE_ID=G.AREA_TYPE_ID AND S.TEHSIL_ID=G.TEHSIL_ID AND S.SUB_AREA_TYPE_ID=G.SUB_AREA_TYPE_ID AND S.AREA_TYPE_ID=? AND S.SUB_AREA_TYPE_STATUS='A' AND S.TEHSIL_ID=?";

	public static String WARD_PATWARI_NAME_EN="SELECT distinct(WPM.WARD_PATWARI_ID),WPM.WARD_PATWARI_NAME,WM.SUBAREA_WARD_MAPPING_ID FROM IGRS_WARD_PATWARI_MASTER WPM,IGRS_SUBAREA_WARD_MAPPING WM,igrs_guideline_master_child1 G WHERE WM.WARD_PATWARI_ID=WPM.WARD_PATWARI_ID AND G.ward_patwari_id=wpm.ward_patwari_id AND WM.SUB_AREA_TYPE_ID=? AND WPM.TEHSIL_ID =? ";
	
	public static String WARD_PATWARI_NAME_HI="SELECT distinct(WPM.WARD_PATWARI_ID) ,WPM.H_WARD_PATWARI_NAME,WM.SUBAREA_WARD_MAPPING_ID FROM IGRS_WARD_PATWARI_MASTER WPM,IGRS_SUBAREA_WARD_MAPPING WM,igrs_guideline_master_child1 G WHERE WM.WARD_PATWARI_ID=WPM.WARD_PATWARI_ID AND G.ward_patwari_id=wpm.ward_patwari_id AND WM.SUB_AREA_TYPE_ID=? AND WPM.TEHSIL_ID =? ";
	
	public static String COLONY_NAME_EN="SELECT distinct(C.COLONY_ID), C.COLONY_NAME,M.COLONY_WARD_MAPPING_ID,C.APPLICABLE_SUBCLAUSE_ID FROM IGRS_COLONY_MASTER C ,IGRS_COLONY_WARD_MAPPING M, igrs_guideline_master_child1 G WHERE M.COLONY_ID=C.COLONY_ID AND G.colony_id=c.colony_id AND G.colony_id=M.colony_id AND M.SUBAREA_WARD_MAPPING_ID=?";
	
	public static String COLONY_NAME_HI="SELECT distinct(C.COLONY_ID), C.H_COLONY_NAME,M.COLONY_WARD_MAPPING_ID, C.APPLICABLE_SUBCLAUSE_ID  FROM IGRS_COLONY_MASTER C ,IGRS_COLONY_WARD_MAPPING M,igrs_guideline_master_child1 G  WHERE M.COLONY_ID=C.COLONY_ID AND G.colony_id=c.colony_id  AND G.colony_id=M.colony_id AND M.SUBAREA_WARD_MAPPING_ID=?";
	
	public static String PROPERTY_TYPE_NAME_EN="SELECT PROPERTY_TYPE_ID,PROPERTY_TYPE_NAME FROM IGRS_PROPERTY_TYPE_MASTER WHERE  PROPERTY_TYPE_STATUS='A'";
	
	public static String PROPERTY_TYPE_NAME_HI="SELECT PROPERTY_TYPE_ID,H_PROPERTY_TYPE_NAME FROM IGRS_PROPERTY_TYPE_MASTER WHERE PROPERTY_TYPE_STATUS='A'";
	public static final String GET_CAVEATS_PROPERTY_DETLS="SELECT REGI.PROPERTY_ID,PM.PROPERTY_TYPE_NAME,REGI.PROTEST_ID,REGI.PROTEST_STATUS,REGC.REGISTRATION_DIST_ID,PM.H_PROPERTY_TYPE_NAME FROM IGRS_REG_PROPRTY_DTLS REGI,IGRS_REG_TXN_DETLS REGC,IGRS_PROPERTY_TYPE_MASTER PM WHERE REGI.PROPERTY_ID IS NOT NULL AND REGI.REG_TXN_ID = REGC.REG_TXN_ID AND REGI.PROP_TYPE_ID=PM.PROPERTY_TYPE_ID AND REGC.REGISTRATION_TXN_STATUS >=17 AND REGC.REGISTRATION_NUMBER = ?";
	public static final String GET_CAVEATS_SERVICE_FEE="SELECT FEE_DR FROM IGRS_FUNCTION_SERVICE_MAPPING WHERE MAPPING_STATUS='A' AND FUNCTION_ID=?";
	public static final String GET_REG_TXN_ID = "SELECT REG_TXN_ID FROM IGRS_REG_TXN_DETLS WHERE REGISTRATION_NUMBER = ?";
	public static final String GET_PROTEST_DETLS = "SELECT PROTEST_ID,PROTEST_STATUS FROM IGRS_REG_PROPRTY_DTLS WHERE PROPERTY_ID = ?";
	public static final String UPDATE_REG_PROTEST_DETLS="UPDATE IGRS_REG_TXN_DETLS SET COURT_STAY_ORDER=? , PROTEST_STATUS=? WHERE REGISTRATION_NUMBER=?";
	public static final String UPDATE_PROPERTY_PROTEST_DETLS="UPDATE IGRS_REG_PROPRTY_DTLS SET PROTEST_ID=? , PROTEST_STATUS=? WHERE PROPERTY_ID=?";
	
	public static final String INSERT_PROTEST_DETLS_SMPD_DOC_Y = "INSERT INTO IGRS_PROTEST_TXN_DETLS " +
			"(PROTEST_TXN_ID,REGISTRATION_NUMBER,PROPERTY_ID,SAMPADA_DOC_FLAG,COURT_ORDER_DOC,COURT_ORDER_DOC_PATH,ORDER_NO,ORDER_DATE,COURT_NAME,COURT_ADDRESS,COURT_DISTRICT,POSTAL_CODE,PHONE_NUMBER,APPLICANT_NAME,STAY_ORDER_FLAG,STAY_ORDER_START_DATE,STAY_ORDER_UPTO_DATE,CREATED_DATE,CREATED_BY,PAYABLE_AMOUNT,PROTEST_DETAILS,PROTEST_STATUS,PROTEST_LOG_DISTRICT,MULTI_REG_FLAG)" +
			"VALUES(?,?,?,?,?,?,?,TO_DATE(?,'DD/MM/YYYY'),?,?,?,?,?,?,?,TO_DATE(?,'DD/MM/YYYY'),TO_DATE(?,'DD/MM/YYYY'),TO_DATE(SYSDATE,'DD/MM/YYYY'),?,?,?,?,?,?)";
	public static final String INSERT_PROTEST_DETLS_SMPD_DOC_N = "INSERT INTO IGRS_PROTEST_TXN_DETLS " +
	"(PROTEST_TXN_ID,SAMPADA_DOC_FLAG,DISTRICT_ID,AREA_ID,SUB_AREA_ID,TEHSIL_ID,COLONY_ID,WARD_ID,PROPERTY_DETLS,COURT_ORDER_DOC,COURT_ORDER_DOC_PATH,COURT_DISTRICT,ORDER_NO,ORDER_DATE,COURT_NAME,COURT_ADDRESS,POSTAL_CODE,PHONE_NUMBER,APPLICANT_NAME,STAY_ORDER_FLAG,STAY_ORDER_START_DATE,STAY_ORDER_UPTO_DATE,CREATED_DATE,CREATED_BY,PAYABLE_AMOUNT,PROTEST_DETAILS,PROTEST_STATUS,AREA_NAME,SUB_AREA_NAME,TEHSIL_NAME,WARD_NAME,COLONY_NAME,PROTEST_LOG_DISTRICT)" +
	"VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,TO_DATE(?,'DD/MM/YYYY'),?,?,?,?,?,?,TO_DATE(?,'DD/MM/YYYY'),TO_DATE(?,'DD/MM/YYYY'),TO_DATE(SYSDATE,'DD/MM/YYYY'),?,?,?,?,?,?,?,?,?,?)";
	public static final String VALIDATE_REG_NO="SELECT CANCELLATION_FLAG,NULL_AND_VOID_FLAG FROM IGRS_REG_TXN_DETLS WHERE REGISTRATION_NUMBER = ?";
	public static final String GET_PROTEST_DATA="SELECT SAMPADA_DOC_FLAG,PROTEST_TXN_ID,PROPERTY_ID,REGISTRATION_NUMBER,PROPERTY_DETLS,AREA_NAME,SUB_AREA_NAME,TEHSIL_NAME,WARD_NAME,COLONY_NAME,COURT_ORDER_DOC,ORDER_NO,TO_CHAR(ORDER_DATE,'DD-MM-YYYY'),COURT_NAME,COURT_ADDRESS,POSTAL_CODE,PHONE_NUMBER,APPLICANT_NAME,STAY_ORDER_FLAG,TO_CHAR(CREATED_DATE,'DD-MM-YY'),PAYABLE_AMOUNT,PROTEST_DETAILS,TO_CHAR(STAY_ORDER_START_DATE,'DD-MM-YYYY'),STAY_ORDER_UPTO_DATE,COURT_DISTRICT,COURT_ORDER_DOC_PATH,RELEASE_REMARKS,RELEASE_DOC,RELEASE_DOC_PATH,PROTEST_STATUS,PAID_AMOUNT,PAID_BY,TO_CHAR(PAYMENT_DATE,'DD-MM-YYYY'),PROTEST_LOG_DISTRICT FROM IGRS_PROTEST_TXN_DETLS WHERE PROTEST_TXN_ID=? ";
	public static final String GET_PROTEST_DATA_hi="SELECT SAMPADA_DOC_FLAG,PROTEST_TXN_ID,PROPERTY_ID,REGISTRATION_NUMBER,PROPERTY_DETLS,AREA_NAME,SUB_AREA_NAME,TEHSIL_NAME,WARD_NAME,COLONY_NAME,COURT_ORDER_DOC,ORDER_NO,ORDER_DATE,COURT_NAME,COURT_ADDRESS,POSTAL_CODE,PHONE_NUMBER,APPLICANT_NAME,STAY_ORDER_FLAG,CREATED_DATE,PAYABLE_AMOUNT,PROTEST_DETAILS,STAY_ORDER_START_DATE,STAY_ORDER_UPTO_DATE,DISTRICT_ID,COURT_ORDER_DOC_PATH,RELEASE_REMARKS,RELEASE_DOC,RELEASE_DOC_PATH FROM IGRS_PROTEST_TXN_DETLS WHERE PROTEST_TXN_ID=?";
	
	public static final String GET_PROTESTREL_DATA="SELECT SAMPADA_DOC_FLAG,PROTEST_TXN_ID,PROPERTY_ID,REGISTRATION_NUMBER,PROPERTY_DETLS,AREA_NAME,SUB_AREA_NAME,TEHSIL_NAME,WARD_NAME,COLONY_NAME,COURT_ORDER_DOC,ORDER_NO,TO_CHAR(ORDER_DATE,'DD-MM-YYYY'),COURT_NAME,COURT_ADDRESS,POSTAL_CODE,PHONE_NUMBER,APPLICANT_NAME,STAY_ORDER_FLAG,TO_CHAR(CREATED_DATE,'DD-MM-YY'),PAYABLE_AMOUNT,PROTEST_DETAILS,TO_CHAR(STAY_ORDER_START_DATE,'DD-MM-YYYY'),STAY_ORDER_UPTO_DATE,COURT_DISTRICT,COURT_ORDER_DOC_PATH,RELEASE_REMARKS,RELEASE_DOC,RELEASE_DOC_PATH,PAID_AMOUNT,PAID_BY,TO_CHAR(PAYMENT_DATE,'DD-MM-YYYY'),PROTEST_LOG_DISTRICT FROM IGRS_PROTEST_TXN_DETLS WHERE  PROTEST_STATUS='LOGGED' AND PROTEST_TXN_ID=?";
	//public static final String GET_PROTESTREL_DATA_hi="SELECT SAMPADA_DOC_FLAG,PROTEST_TXN_ID,PROPERTY_ID,REGISTRATION_NUMBER,PROPERTY_DETLS,AREA_NAME,SUB_AREA_NAME,TEHSIL_NAME,WARD_NAME,COLONY_NAME,COURT_ORDER_DOC,ORDER_NO,ORDER_DATE,COURT_NAME,COURT_ADDRESS,POSTAL_CODE,PHONE_NUMBER,APPLICANT_NAME,STAY_ORDER_FLAG,CREATED_DATE,PAYABLE_AMOUNT,PROTEST_DETAILS,STAY_ORDER_START_DATE,STAY_ORDER_UPTO_DATE,DISTRICT_ID,COURT_ORDER_DOC_PATH,RELEASE_REMARKS,RELEASE_DOC,RELEASE_DOC_PATH FROM IGRS_PROTEST_TXN_DETLS WHERE PROTEST_TXN_ID=? AND PROTEST_STATUS='लॉग इन'";
	//public static final String GET_PROTEST_DATA1="SELECT SAMPADA_DOC_FLAG,PROTEST_TXN_ID,PROPERTY_ID,REGISTRATION_NUMBER,PROPERTY_DETLS,AREA_NAME,SUB_AREA_NAME,TEHSIL_NAME,WARD_NAME,COLONY_NAME,COURT_ORDER_DOC,ORDER_NO,ORDER_DATE,COURT_NAME,COURT_ADDRESS,POSTAL_CODE,PHONE_NUMBER,APPLICANT_NAME,STAY_ORDER_FLAG,CREATED_DATE,PAYABLE_AMOUNT,PROTEST_DETAILS FROM IGRS_PROTEST_TXN_DETLS WHERE CREATED_DATE BETWEEN TO_DATE(?,'DD-MM-YYYY') AND TO_DATE(?,'DD-MM-YYYY')";
	public static final String GET_PROTEST_ID="SELECT PROTEST_TXN_ID,TO_CHAR(CREATED_DATE,'DD-MM-YY') FROM IGRS_PROTEST_TXN_DETLS WHERE PROTEST_STATUS='LOGGED' AND PROTEST_LOG_DISTRICT IN (?,?) AND CREATED_DATE BETWEEN TO_DATE(?,'DD-MM-YYYY') AND TO_DATE(?,'DD-MM-YYYY')";
	//public static final String GET_PROTEST_ID_hi="SELECT PROTEST_TXN_ID,CREATED_DATE FROM IGRS_PROTEST_TXN_DETLS WHERE CREATED_DATE BETWEEN TO_DATE(?,'DD-MM-YYYY') AND TO_DATE(?,'DD-MM-YYYY') AND PROTEST_STATUS='लॉग इन'";
	//public static final String GET_PAYMENT_DETLS="SELECT PAYMENT_FLAG,PAID_AMOUNT,CREATED_BY,CREATED_DATE from IGRS_CAVEAT_PAYMENT_DETAILS where CREATED_DATE=(SELECT MAX(CREATED_DATE) FROM IGRS_CAVEAT_PAYMENT_DETAILS WHERE CAVEAT_TXN_ID=?) AND PAYMENT_FLAG IN ('P','C')  AND CAVEAT_TXN_ID = ? ";
	
	public static final String INSERT_PROTEST_REL_DETLS = "INSERT INTO IGRS_PROTEST_TXN_DETLS " +
	"(PROTEST_TXN_ID,SAMPADA_DOC_FLAG,PROPERTY_ID,REGISTRATION_NUMBER,DISTRICT_ID,AREA_NAME,SUB_AREA_NAME,TEHSIL_NAME,WARD_NAME,COLONY_NAME,PROPERTY_DETLS,COURT_ORDER_DOC,COURT_ORDER_DOC_PATH,COURT_DISTRICT,ORDER_NO,ORDER_DATE,COURT_NAME,COURT_ADDRESS,POSTAL_CODE,PHONE_NUMBER,APPLICANT_NAME,STAY_ORDER_FLAG,STAY_ORDER_START_DATE,CREATED_BY,PAYABLE_AMOUNT,PAID_AMOUNT,PAID_BY,PAYMENT_DATE,PROTEST_DETAILS,PROTEST_STATUS,PROTEST_ID,RELEASE_DOC,RELEASE_REMARKS,CREATED_DATE,PROTEST_LOG_DISTRICT,RELEASE_DOC_PATH)" +
	"VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,TO_DATE(?,'DD/MM/YYYY'),?,?,?,?,?,?,TO_DATE(?,'DD/MM/YYYY'),?,?,?,?,TO_DATE(?,'DD-MM-YYYY'),?,?,?,?,?,TO_DATE(SYSDATE,'DD/MM/YYYY'),?,?)";
	
	public static final String GET_PROTEST_SEARCH_DATA="SELECT PROTEST_TXN_ID,TO_CHAR(CREATED_DATE,'DD-MM-YY'),REGISTRATION_NUMBER,PROTEST_STATUS FROM IGRS_PROTEST_TXN_DETLS WHERE PROTEST_LOG_DISTRICT IN (?,?) AND CREATED_DATE BETWEEN TO_DATE(?,'DD-MM-YYYY') AND TO_DATE(?,'DD-MM-YYYY')";
	public static final String GET_PROTEST_SEARCH_DATA2="SELECT PROTEST_TXN_ID,TO_CHAR(CREATED_DATE,'DD-MM-YY'),REGISTRATION_NUMBER,PROTEST_STATUS FROM IGRS_PROTEST_TXN_DETLS WHERE PROTEST_TXN_ID = ? AND PROTEST_LOG_DISTRICT IN (?,?)";
	public static final String GET_PROTEST_SEARCH_DATA3="SELECT PROTEST_TXN_ID,TO_CHAR(CREATED_DATE,'DD-MM-YY'),REGISTRATION_NUMBER,PROTEST_STATUS,MULTI_REG_FLAG FROM IGRS_PROTEST_TXN_DETLS WHERE PROTEST_STATUS = ?";
	public static final String GET_PROTEST_SEARCH_DATA13="SELECT PROTEST_TXN_ID,TO_CHAR(CREATED_DATE,'DD-MM-YY'),REGISTRATION_NUMBER,PROTEST_STATUS,MULTI_REG_FLAG FROM IGRS_PROTEST_TXN_DETLS WHERE PROTEST_STATUS = ? AND PROTEST_LOG_DISTRICT IN (?,?)";
	public static final String GET_PROTEST_SEARCH_DATA4="SELECT PROTEST_TXN_ID,CREATED_DATE,REGISTRATION_NUMBER,PROTEST_STATUS,COURT_DISTRICT FROM IGRS_PROTEST_TXN_DETLS WHERE PROTEST_LOG_DISTRICT = ?";
	//public static final String GET_PROTEST_SEARCH_DATA5="SELECT PROTEST_TXN_ID,CREATED_DATE,REGISTRATION_NUMBER,PROTEST_STATUS,COURT_DISTRICT FROM IGRS_PROTEST_TXN_DETLS WHERE CREATED_DATE BETWEEN TO_DATE(?,'DD-MM-YYYY') AND TO_DATE(?,'DD-MM-YYYY')";
	public static final String VALIDATE_PROTEST_REL_STATUS="SELECT PROTEST_STATUS FROM IGRS_PROTEST_TXN_DETLS WHERE PROTEST_ID=?";
	
	//public static final String VALIDATE_PROTEST_REL_STATUS_hi="SELECT PROTEST_TXN_ID FROM IGRS_PROTEST_TXN_DETLS WHERE PROTEST_ID=? AND PROTEST_STATUS='जारी'";
	public static final String UPDATE_PROTEST_STATUS="UPDATE IGRS_PROTEST_TXN_DETLS SET PROTEST_STATUS=?,PAID_AMOUNT=?, PAID_BY=?,PAYMENT_DATE=TO_DATE(?,'DD-MM-YYYY') WHERE PROTEST_TXN_ID=?";
	//public static final String UPDATE_PAYMENT_DETAILS="UPDATE IGRS_PROTEST_TXN_DETLS SET PAID_AMOUNT=?, PAID_BY=? WHERE PROTEST_TXN_ID=?";
	public static final String GET_USER_TYPE_ID="SELECT USER_TYPE_ID FROM IGRS_USERS_LIST WHERE USER_ID=?";
	public static final String GET_DIST_ID_NAME_SP="SELECT DISTINCT(A.DISTRICT_ID), B.DISTRICT_NAME  FROM IGRS_SP_DETLS A, IGRS_DISTRICT_MASTER B WHERE A.DISTRICT_ID=B.DISTRICT_ID AND A.APPLCTN_STATUS=8 AND A.CREATED_BY=?";
	public static final String GET_DISTRICT_NAME_HINDI="SELECT H_DISTRICT_NAME FROM IGRS_DISTRICT_MASTER WHERE DISTRICT_ID=?";
	public static final String GET_DISTRICT_NAME="SELECT DISTRICT_NAME FROM IGRS_DISTRICT_MASTER WHERE DISTRICT_ID=?";
	public static final String INSERT_CAVEATS_PAYMENT_DETLS ="INSERT INTO IGRS_CAVEAT_PAYMENT_DETAILS(TRANSACTION_ID,CAVEAT_TXN_ID,CREATED_BY,CREATED_DATE,PAYMENT_FLAG,PAYMENT_MODE_ID,FUNCTION_ID,PAYABLE_AMOUNT,TOTAL_FEE) VALUES(?,?,?,SYSDATE,?,?,?,?,?)";
	public static final String GET_CAVEATS_PAYMENT_TXN_ID_SEQ="SELECT IGRS_CAVEAT_PAYMENT_SEQ.NEXTVAL FROM DUAL";
	public static final String UPDATE_PROTEST_DETLS="UPDATE IGRS_PROTEST_TXN_DETLS SET PROTEST_STATUS=?, UPDATED_DATE=SYSDATE, UPDATED_BY=? WHERE PROTEST_TXN_ID=?";
	//public static final String GET_PROTEST_DETLS1 = "SELECT PROTEST_TXN_ID,STAY_ORDER_FLAG,PROTEST_STATUS FROM IGRS_PROTEST_TXN_DETLS WHERE CREATED_DATE=(SELECT MAX(CREATED_DATE) FROM IGRS_PROTEST_TXN_DETLS WHERE REGISTRATION_NUMBER=?) AND REGISTRATION_NUMBER=?";
	//public static final String GET_PYMNT_DETLS = "SELECT PAYMENT_FLAG,PAID_AMOUNT,CREATED_BY,CREATED_DATE FROM IGRS_CAVEAT_PAYMENT_DETAILS WHERE CAVEAT_TXN_ID =?";
	//public static final String UPDATE_PROTEST_PYMNT_DETLS = "UPDATE IGRS_PROTEST_TXN_DETLS SET PROTEST_STATUS = ? AND PAID_AMOUNT = ? AND PAID_BY = ? AND PAYMENT_DATE = ? WHERE PROTEST_TXN_ID =?";
	  public static final String GET_PROTEST_SEARCH_DATA8="SELECT PROTEST_TXN_ID,TO_CHAR(CREATED_DATE,'DD-MM-YY'),REGISTRATION_NUMBER,PROTEST_STATUS FROM IGRS_PROTEST_TXN_DETLS WHERE PROTEST_TXN_ID = ? AND PROTEST_STATUS = ? AND PROTEST_LOG_DISTRICT IN (?,?) AND CREATED_DATE BETWEEN TO_DATE(?,'DD-MM-YYYY') AND TO_DATE(?,'DD-MM-YYYY')";

		public static final String GET_PROTEST_SEARCH_DATA9="SELECT PROTEST_TXN_ID,TO_CHAR(CREATED_DATE,'DD-MM-YY'),REGISTRATION_NUMBER,PROTEST_STATUS FROM IGRS_PROTEST_TXN_DETLS WHERE PROTEST_TXN_ID = ? AND PROTEST_STATUS = ? AND PROTEST_LOG_DISTRICT IN (?,?)";

		public static final String GET_PROTEST_SEARCH_DATA6="SELECT PROTEST_TXN_ID,TO_CHAR(CREATED_DATE,'DD-MM-YY'),REGISTRATION_NUMBER,PROTEST_STATUS FROM IGRS_PROTEST_TXN_DETLS WHERE PROTEST_TXN_ID = ? AND PROTEST_LOG_DISTRICT IN (?,?) AND CREATED_DATE BETWEEN TO_DATE(?,'DD-MM-YYYY') AND TO_DATE(?,'DD-MM-YYYY')";

		public static final String GET_PROTEST_SEARCH_DATA7="SELECT PROTEST_TXN_ID,TO_CHAR(CREATED_DATE,'DD-MM-YY'),REGISTRATION_NUMBER,PROTEST_STATUS FROM IGRS_PROTEST_TXN_DETLS WHERE PROTEST_STATUS = ? AND PROTEST_LOG_DISTRICT IN (?,?) AND CREATED_DATE BETWEEN TO_DATE(?,'DD-MM-YYYY') AND TO_DATE(?,'DD-MM-YYYY')";
		
		public static final String GET_PROTEST_SEARCH_DATA10="select PROTEST_TXN_ID , CREATED_DATE , REGISTRATION_NUMBER , PROTEST_STATUS , PROTEST_LOG_DISTRICT "+
															"from ( SELECT property_id,PROTEST_TXN_ID,TO_CHAR(CREATED_DATE,'DD-MM-YY') AS CREATED_DATE ,REGISTRATION_NUMBER,PROTEST_STATUS,PROTEST_LOG_DISTRICT "+
															"FROM IGRS_PROTEST_TXN_DETLS WHERE PROTEST_STATUS IN ('LOGGED','RELEASED') AND PROTEST_LOG_DISTRICT IN (?,?) "+
															"AND CREATED_DATE BETWEEN TO_DATE(?,'DD-MM-YYYY') AND TO_DATE(?,'DD-MM-YYYY') order by property_id ) ";
		
		public static final String GET_PROTEST_SEARCH_DATA11="select PROTEST_TXN_ID , CREATED_DATE , REGISTRATION_NUMBER , PROTEST_STATUS , PROTEST_LOG_DISTRICT "+
																"from ( SELECT property_id,PROTEST_TXN_ID,TO_CHAR(CREATED_DATE,'DD-MM-YY') AS CREATED_DATE ,REGISTRATION_NUMBER,PROTEST_STATUS,PROTEST_LOG_DISTRICT "+
																"FROM IGRS_PROTEST_TXN_DETLS WHERE PROTEST_STATUS IN ('LOGGED','RELEASED') AND PROTEST_LOG_DISTRICT IN (?,?) AND REGISTRATION_NUMBER = ? "+
																"AND CREATED_DATE BETWEEN TO_DATE(?,'DD-MM-YYYY') AND TO_DATE(?,'DD-MM-YYYY') order by property_id ) ";
		
		public static final String GET_CHALLAN_PAYMENT_DETLS="SELECT PAYMENT_TXN_ID from IGRS_CAVEAT_PAYMENT_DETAILS where CREATED_DATE=(SELECT MAX(CREATED_DATE) FROM IGRS_CAVEAT_PAYMENT_DETAILS WHERE TRANSACTION_ID=?) AND PAYMENT_FLAG IN ('P','C')  AND TRANSACTION_ID = ? ";
		public static final String GET_PROTEST_SEARCH_DATA12="SELECT PROTEST_TXN_ID,TO_CHAR(CREATED_DATE,'DD-MM-YY'),REGISTRATION_NUMBER,PROTEST_STATUS,MULTI_REG_FLAG FROM IGRS_PROTEST_TXN_DETLS WHERE PROTEST_STATUS = ? AND CREATED_DATE BETWEEN TO_DATE(?,'DD-MM-YYYY') AND TO_DATE(?,'DD-MM-YYYY')";
		public static final String GET_PROTEST_PAYMENT_DETLS = "SELECT PAYMENT_FLAG,PAID_AMOUNT,CREATED_BY,TO_CHAR(CREATED_DATE,'DD-MM-YYYY') from IGRS_CAVEAT_PAYMENT_DETAILS where CREATED_DATE=(SELECT MAX(CREATED_DATE) FROM IGRS_CAVEAT_PAYMENT_DETAILS WHERE CAVEAT_TXN_ID=?) AND PAYMENT_FLAG IN ('P','C')  AND CAVEAT_TXN_ID = ? ";
		public static final String OFFICE_TYPE = "select office_type_id from igrs_office_master where office_id =? ";
		public static final String INSP_GET_ZONE_DIG = "SELECT D.ZONE_ID FROM IGRS_DISTRICT_MASTER D,igrs_office_master O WHERE o.district_id=d.district_id AND  o.office_id=? ";
		public static final String INSP_GET_DISTRICT_ZONE_LIST_HINDI = "Select h_district_name,district_id from igrs_district_master where zone_id=? order by district_name";
		public static final String INSP_GET_DISTRICT_ZONE_LIST = "Select district_name,district_id from igrs_district_master where zone_id=? order by district_name";
		public static final String GET_OFFICE_TYPE_ID = "select office_type_id from igrs_office_master where OFFICE_ID=?";
		public static final String GET_DIST_NAME_DIG = "Select DISTRICT_ID,district_name,h_district_name from igrs_district_master where district_status='A' "+
		" and district_id in( select district_id from igrs_office_master where office_status='A' "+
		"and parent_id in(?)) ORDER BY DISTRICT_NAME ASC ";
		public static final String GET_DIST_NAME_DR = "Select DISTRICT_ID,district_name,h_district_name from igrs_district_master where district_status='A' "
			+ " and district_id in( select district_id from igrs_office_master where office_status='A' "
			+ "and office_id in(?)) ORDER BY DISTRICT_NAME ASC ";
		public static final String GET_DIST_NAME_SR = "Select DISTRICT_ID,district_name,h_district_name from igrs_district_master where district_status='A' "
			+ " and district_id in( select district_id from igrs_office_master where office_status='A' "
			+ "	and office_id in(?)) ORDER BY DISTRICT_NAME ASC ";
		public static final String DISTRICT_QUERY_HINDI = "Select DISTRICT_ID, "
			+ "DISTRICT_NAME,H_DISTRICT_NAME from IGRS_DISTRICT_MASTER "
			+ " Where STATE_ID=? AND DISTRICT_STATUS='A' "
			+ "ORDER BY DISTRICT_NAME ASC";
		public static final String GET_DISTRICT_DETLS = "select district_name from IGRS_DISTRICT_MASTER where DISTRICT_STATUS='A' and district_id=?";
		public static final String GET_DISTRICT_DETLS_H = "select h_district_name from IGRS_DISTRICT_MASTER where DISTRICT_STATUS='A' and district_id =?";
		public static final String GET_DISTRICT_VALUES = "select district_name,h_district_name from IGRS_DISTRICT_MASTER where DISTRICT_STATUS='A' and district_id =?";
		public static final String GET_DISTRICT_ID_VAL = "select district_id from IGRS_DISTRICT_MASTER where DISTRICT_STATUS='A' and district_name=?";
		public static final String GET_DISTRICT_ID_VAL_H = "select district_id  from IGRS_DISTRICT_MASTER where DISTRICT_STATUS='A' and h_district_name =?";
		public static final String VALIDATE_PROTEST_DISTRICT="SELECT PROTEST_LOG_DISTRICT FROM IGRS_PROTEST_TXN_DETLS WHERE PROTEST_TXN_ID=?";



}
