package com.wipro.igrs.caveats.sql;

public class DocumentFlagEvaluationSQL {
	
	public static final String GET_LANGUAGE="select LANGUAGE from IGRS_REG_TXN_DETLS where REG_TXN_ID=?";
	
	public static final String GET_REG_DATE_INIT="select TO_CHAR(REG_COMP_DATE,'dd/mm/yyyy') from IGRS_REG_TXN_DETLS where REG_TXN_ID=? ";
	
	public static final String GET_ESTAMP_CODE_DETLS = "SELECT C.ESTAMP_CODE FROM IGRS_ESTAMP_DETLS C,IGRS_REG_ESTAMP_MAP M WHERE C.ESTAMP_TXN_ID=M.ESTAMP_TXN_ID AND M.REG_TXN_ID = ? ORDER BY C.ESTAMP_TXN_ID DESC";
	
	public static final String GET_PARTY_DETAILS_CER_OTHER_HI="SELECT R.APPELLATE_TYPE_ID,R.PARTY_FIRST_NAME,R.PARTY_MIDDLE_NAME,R.PARTY_LAST_NAME,R.GUARDIAN_NAME,R.ORGANIZATION_NAME,R.AUTHRZD_PERSN_NAME,R.PARTY_ADDRESS||', '||D.H_DISTRICT_NAME||', '||S.H_STATE_NAME||', '||C.H_COUNTRY_NAME, "+
	"R.NAME_OF_OFFICIAL,R.ADRS_OF_OFFICIAL||', '||D.H_DISTRICT_NAME||', '||S.H_STATE_NAME||', '||C.H_COUNTRY_NAME,P.H_PARTY_TYPE_NAME,R.OWNER_ID,R.PARTY_TXN_ID FROM IGRS_REG_TXN_PARTY_DETLS R,IGRS_DISTRICT_MASTER D,IGRS_COUNTRY_MASTER C,IGRS_STATE_MASTER S,IGRS_PARTY_TYPE_MASTER P WHERE S.STATE_ID=R.STATE_ID AND C.COUNTRY_ID=R.COUNTRY_ID AND D.DISTRICT_ID=R.DISTRICT_ID AND P.PARTY_TYPE_ID=R.PARTY_TYPE_ID AND R.REG_TXN_ID=? AND IS_APPLICANT NOT IN('O') order by R.PARTY_TXN_ID";

	public static final String GET_PARTY_DETAILS_CER_COMMOMN_HI="SELECT R.APPELLATE_TYPE_ID,R.PARTY_FIRST_NAME,R.PARTY_MIDDLE_NAME,R.PARTY_LAST_NAME,R.GUARDIAN_NAME,R.ORGANIZATION_NAME,R.AUTHRZD_PERSN_NAME,R.PARTY_ADDRESS||', '||D.H_DISTRICT_NAME||', '||S.H_STATE_NAME||', '||C.H_COUNTRY_NAME, "+
	 "R.NAME_OF_OFFICIAL,R.ADRS_OF_OFFICIAL||', '||D.H_DISTRICT_NAME||', '||S.H_STATE_NAME||', '||C.H_COUNTRY_NAME,R.ROLE_NAME,R.OWNER_ID,R.PARTY_TXN_ID FROM IGRS_REG_TXN_PARTY_DETLS R,IGRS_DISTRICT_MASTER D,IGRS_COUNTRY_MASTER C,IGRS_STATE_MASTER S WHERE S.STATE_ID=R.STATE_ID AND C.COUNTRY_ID=R.COUNTRY_ID AND D.DISTRICT_ID=R.DISTRICT_ID AND R.REG_TXN_ID=? AND IS_APPLICANT NOT IN('O') order by PARTY_TXN_ID";

	public static final String GET_PARTY_DETAILS_CER_OTHER="SELECT R.APPELLATE_TYPE_ID,R.PARTY_FIRST_NAME,R.PARTY_MIDDLE_NAME,R.PARTY_LAST_NAME,R.GUARDIAN_NAME,R.ORGANIZATION_NAME,R.AUTHRZD_PERSN_NAME,R.PARTY_ADDRESS||', '||D.DISTRICT_NAME||', '||S.STATE_NAME||', '||C.COUNTRY_NAME, "+
	 "R.NAME_OF_OFFICIAL,R.ADRS_OF_OFFICIAL||', '||D.DISTRICT_NAME||', '||S.STATE_NAME||', '||C.COUNTRY_NAME,P.PARTY_TYPE_NAME,R.OWNER_ID,R.PARTY_TXN_ID FROM IGRS_REG_TXN_PARTY_DETLS R,IGRS_DISTRICT_MASTER D,IGRS_COUNTRY_MASTER C,IGRS_STATE_MASTER S,IGRS_PARTY_TYPE_MASTER P WHERE S.STATE_ID=R.STATE_ID AND C.COUNTRY_ID=R.COUNTRY_ID AND D.DISTRICT_ID=R.DISTRICT_ID AND P.PARTY_TYPE_ID=R.PARTY_TYPE_ID AND R.REG_TXN_ID=? AND IS_APPLICANT NOT IN('O') order by R.PARTY_TXN_ID";
	
	public static final String GET_PARTY_DETAILS_CER_COMMOMN="SELECT R.APPELLATE_TYPE_ID,R.PARTY_FIRST_NAME,R.PARTY_MIDDLE_NAME,R.PARTY_LAST_NAME,R.GUARDIAN_NAME,R.ORGANIZATION_NAME,R.AUTHRZD_PERSN_NAME,R.PARTY_ADDRESS||', '||D.DISTRICT_NAME||', '||S.STATE_NAME||', '||C.COUNTRY_NAME, "+
	 "R.NAME_OF_OFFICIAL,R.ADRS_OF_OFFICIAL||', '||D.DISTRICT_NAME||', '||S.STATE_NAME||', '||C.COUNTRY_NAME,R.ROLE_NAME,R.OWNER_ID,R.PARTY_TXN_ID FROM IGRS_REG_TXN_PARTY_DETLS R,IGRS_DISTRICT_MASTER D,IGRS_COUNTRY_MASTER C,IGRS_STATE_MASTER S WHERE S.STATE_ID=R.STATE_ID AND C.COUNTRY_ID=R.COUNTRY_ID AND D.DISTRICT_ID=R.DISTRICT_ID AND R.REG_TXN_ID=? AND IS_APPLICANT NOT IN('O') order by R.PARTY_TXN_ID";
	
	public static final String  GET_CONSIDER_AMOUNT = "select sum(total) from ( "+
	" select   coalesce (pr.field_value, 'NA') total  from igrs_prop_duty_field_detls pr inner join "+ 
	"igrs_reg_txn_detls re on re.duty_txn_id=pr.duty_txn_id where re.reg_txn_id=? and "+
	"pr.inst_field_map_id in (select inst_field_map_id from IGRS_INST_FIELD_MAPPING where CONSIDER_MAP_FLAG='Y'))" ;
	
	public static final String GET_PARTY_DETAILS_CER_OWNER="SELECT R.APPELLATE_TYPE_ID,R.PARTY_FIRST_NAME,R.PARTY_MIDDLE_NAME,R.PARTY_LAST_NAME,R.GUARDIAN_NAME,R.ORGANIZATION_NAME,R.AUTHRZD_PERSN_NAME,R.PARTY_ADDRESS, "+
	 "R.NAME_OF_OFFICIAL,R.ADRS_OF_OFFICIAL,R.ROLE_NAME,R.OWNER_ID,R.PARTY_TXN_ID FROM IGRS_REG_TXN_PARTY_DETLS R where R.PARENT_ID=? order by R.PARTY_TXN_ID";
	
	public static final String GET_COMMON_FLAG="SELECT COMMON_FLOW FROM IGRS_DEED_INSTRUMENT_MASTER I, IGRS_REG_TXN_DETLS R WHERE I.INSTRUMENT_ID=R.INSTRUMENTS_ID AND R.REG_TXN_ID=?";
	
	public static final String GET_CONSENTER_DETAILS_REG="SELECT R.CONSENTER_FIRST_NAME,R.FATHER_NAME,R.CONSENTER_ADDRESS||', '||D.DISTRICT_NAME||', '||S.STATE_NAME||', '||C.COUNTRY_NAME FROM IGRS_REG_CONSENTER_DETAILS R,IGRS_DISTRICT_MASTER D,IGRS_COUNTRY_MASTER C,IGRS_STATE_MASTER S WHERE S.STATE_ID=R.STATE_ID AND C.COUNTRY_ID=R.COUNTRY_ID AND D.DISTRICT_ID=R.DISTRICT_ID AND R.REG_TXN_ID=?";
	
	public static final String GET_CONSENTER_DETAILS_REG_HI="SELECT R.CONSENTER_FIRST_NAME,R.FATHER_NAME,R.CONSENTER_ADDRESS||', '||D.H_DISTRICT_NAME||', '||S.H_STATE_NAME||', '||C.H_COUNTRY_NAME FROM IGRS_REG_CONSENTER_DETAILS R,IGRS_DISTRICT_MASTER D,IGRS_COUNTRY_MASTER C,IGRS_STATE_MASTER S WHERE S.STATE_ID=R.STATE_ID AND C.COUNTRY_ID=R.COUNTRY_ID AND D.DISTRICT_ID=R.DISTRICT_ID AND R.REG_TXN_ID=?";
	
	public static final String GET_REG_STAMP_DETLS = "SELECT STAMP_DUTY,REG_FEE,TOTAL FROM IGRS_REG_CHK_STAMP_DUTY_DTLS WHERE REG_TXN_ID = ?";
	
	public static final String GET_DEED_DOC_PATH = "SELECT DEED_DOC_FILEPATH FROM IGRS_REG_TXN_DETLS WHERE REG_TXN_ID = ?";
	
	public static final String GET_ESTAMP_DETLS = "SELECT ESTAMP_PDF_PATH,ESTAMP_TXN_ID FROM IGRS_REG_ESTAMP_MAP WHERE REG_TXN_ID = ?";
	
	public static final String GET_MARKET_VALUE="SELECT SUM(P.FINAL_MV) FROM IGRS_PROP_VAL_TXN_DETLS P,IGRS_REG_PROPRTY_DTLS R WHERE R.VAL_TXN_ID=P.VAL_TXN_ID AND R.REG_TXN_ID=?";

	public static final String CHECK_FINAL_DOC_GEN_FLAG ="SELECT DISTINCT FINAL_DOC_GEN_FLAG FROM IGRS_REG_TXN_DETLS WHERE  REG_TXN_ID =?";
	
	 public static final String CHECK_STATUS ="SELECT DISTINCT REGISTRATION_TXN_STATUS,REG_TXN_ID FROM IGRS_REG_TXN_DETLS WHERE REGISTRATION_NUMBER =?";
	 
	 public static final String GET_CMPLETION_NUMBER = "SELECT DISTINCT REGISTRATION_NUMBER FROM IGRS_REG_TXN_DETLS WHERE  REG_TXN_ID=?";
	 
	 public static final String CHECK_REG_NUMBER="SELECT REGISTRATION_NUMBER from IGRS_REG_TXN_DETLS where REGISTRATION_NUMBER=?";
	 
	 public static final String GET_NULL_AND_VOID_FLAG="SELECT NULL_AND_VOID_FLAG from IGRS_REG_TXN_DETLS where REGISTRATION_NUMBER=?";
	 
	 public static final String GET_OFFICE_COMP="select REGISTRATION_OFFICE_ID from IGRS_REG_TXN_DETLS where REG_TXN_ID=?";
	 
	 public static final String GET_USER_COMP="select UPDATE_BY from IGRS_REG_TXN_DETLS where REG_TXN_ID=?";

	 public static final String DECLARE_NULL_VOID="UPDATE IGRS_REG_TXN_DETLS SET NULL_AND_VOID_UPDATION_DATE=?, NULL_AND_VOID_FLAG=?, NULL_AND_VOID_UPDATED_BY=? where REGISTRATION_NUMBER=?";
	 
	 public static final String INSERT_NULL_VOID_DETAILS = "INSERT INTO NULL_AND_VOID_HISTORY (TXN_ID,REGISTRATION_NUMBER,REMARKS,UPDATED_BY,UPDATION_DATE,UPLOAD_PATH,COURT_ORDER_NO,COURT_NAME,COURT_ORDER_DATE) VALUES (?,?,?,?,?,?,?,?,TO_DATE(?,'DD-MM-YYYY'))";
	 
	 public static final String GET_TXN_SEQ="SELECT IGRS_NULL_VOID_TXN_SEQ.NEXTVAL FROM DUAL";
	 
	 public static final String GET_LAST_UPDATION_DETAILS="select TO_CHAR(NULL_AND_VOID_UPDATION_DATE, 'dd/MM/yyyy hh12:mi:ss'),NULL_AND_VOID_UPDATED_BY from IGRS_REG_TXN_DETLS where REGISTRATION_NUMBER=?";
	 
	 public static final String GET_LAST_REMARKS_UPLOADS="select REMARKS,UPLOAD_PATH,COURT_NAME,COURT_ORDER_NO,TO_CHAR(COURT_ORDER_DATE,'dd/MM/yyyy') from NULL_AND_VOID_HISTORY where REGISTRATION_NUMBER=? and UPDATED_BY=? and TO_CHAR(UPDATION_DATE, 'dd/MM/yyyy hh12:mi:ss')=?";
	 public static final String GET_REGINIT_ID ="SELECT REG_TXN_ID FROM IGRS_REG_TXN_DETLS WHERE REGISTRATION_NUMBER=?";
	 
}
