/*
 * Copyright Notice
 *==============================================================================
 * This file contains proprietary information of Wipro Infotech, Egypt.
 * Copying or reproduction without prior written approval is prohibited.
 * Copyright (c) 2007-08
 *==============================================================================
 *
 * File Name   :   FunctionDeptCommonSQL.java
 * Author      :   Mahmoud Eid 
 * Description :   Represents the CommonSQL Class for  Function Department Master.
 * ----------------------------------------------------------------------------
 * Version         Modified By     Modified On           Modification
 * ----------------------------------------------------------------------------
 * 1.0             Mahmoud Eid  10th August, 2008	 		 
 * --------------------------------------------------------------------------------
 */
package com.wipro.igrs.officemaster.sql;

public class OfficeCommonSQL {
	

		// Constants ---------------------------------------------------------------
		// Select Query
		public static final String INSERT_OFFICE_MASTER = "INSERT INTO IGRS_OFFICE_MASTER (OFFICE_ID,"+
				"OFFICE_NAME,OFFICE_DESCRIPTION,OFFICE_STATUS,PARENT_ID,DISTRICT_ID,"+
				"TEHSIL_ID,WARD_ID,OFFICE_ADDRESS,OFFICE_PHONE_NO,OFFICE_FAX_NO,"+
				"CREATED_BY,CREATED_DATE,MOHALLA_VILLAGE_ID,"+
				"OFFICE_TYPE_ID) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,sysdate,"+
				"?,?)";
		
		public static final String SELECT_OFFICE_MASTER = "SELECT OFFICE_ID,OFFICE_NAME,"+
		"OFFICE_DESCRIPTION,OFFICE_STATUS,PARENT_ID,IGRS_OFFICE_MASTER.DISTRICT_ID,IGRS_OFFICE_MASTER.TEHSIL_ID,IGRS_OFFICE_MASTER.WARD_ID,OFFICE_ADDRESS,"+
		"OFFICE_PHONE_NO,OFFICE_FAX_NO,IGRS_OFFICE_MASTER.CREATED_BY,IGRS_OFFICE_MASTER.CREATED_DATE,IGRS_OFFICE_MASTER.UPDATE_BY,IGRS_OFFICE_MASTER.UPDATE_DATE,IGRS_OFFICE_MASTER.MOHALLA_VILLAGE_ID,"+
		"IGRS_OFFICE_MASTER.OFFICE_TYPE_ID,"+
		"DISTRICT_NAME,TEHSIL_NAME,WARD_PATWARI_NAME,MOHALLA_VILLAGE_NAME,"+
		"OFFICE_TYPE_NAME FROM IGRS_OFFICE_MASTER left outer join IGRS_DISTRICT_MASTER on IGRS_OFFICE_MASTER.DISTRICT_ID = IGRS_DISTRICT_MASTER.DISTRICT_ID left outer join IGRS_TEHSIL_MASTER on IGRS_OFFICE_MASTER.TEHSIL_ID = IGRS_TEHSIL_MASTER.TEHSIL_ID "+
		"left outer join IGRS_WARD_PATWARI_MASTER on IGRS_OFFICE_MASTER.WARD_ID = IGRS_WARD_PATWARI_MASTER.WARD_PATWARI_ID left outer join IGRS_MOHALLA_VILLAGE_MASTER on IGRS_OFFICE_MASTER.MOHALLA_VILLAGE_ID = IGRS_MOHALLA_VILLAGE_MASTER.MOHALLA_VILLAGE_ID left outer join IGRS_OFFICE_TYPE_MASTER on IGRS_OFFICE_MASTER.OFFICE_TYPE_ID = IGRS_OFFICE_TYPE_MASTER.OFFICE_TYPE_ID  WHERE OFFICE_STATUS <> 'R'";
		
		public static final String UPDATE_OFFICE_MASTER = "UPDATE IGRS_OFFICE_MASTER SET OFFICE_NAME = ? , OFFICE_DESCRIPTION = ?,"+
		"OFFICE_STATUS = ?, PARENT_ID = ?,DISTRICT_ID = ?,TEHSIL_ID = ?,"+
		"WARD_ID = ?, OFFICE_ADDRESS = ?,OFFICE_PHONE_NO = ?,OFFICE_FAX_NO = ?,"+
		"UPDATE_BY = ?,UPDATE_DATE = sysdate,MOHALLA_VILLAGE_ID = ?,"+
		"OFFICE_TYPE_ID = ? WHERE OFFICE_ID = ?";
		
		public static final String SELECT_OFFICE_MASTER_ID = "SELECT OFFICE_ID,OFFICE_NAME,"+
		"OFFICE_DESCRIPTION,OFFICE_STATUS,PARENT_ID,IGRS_OFFICE_MASTER.DISTRICT_ID,IGRS_OFFICE_MASTER.TEHSIL_ID,IGRS_OFFICE_MASTER.WARD_ID,OFFICE_ADDRESS,"+
		"OFFICE_PHONE_NO,OFFICE_FAX_NO,IGRS_OFFICE_MASTER.CREATED_BY,IGRS_OFFICE_MASTER.CREATED_DATE,IGRS_OFFICE_MASTER.UPDATE_BY,IGRS_OFFICE_MASTER.UPDATE_DATE,IGRS_OFFICE_MASTER.MOHALLA_VILLAGE_ID,"+
		"IGRS_OFFICE_MASTER.OFFICE_TYPE_ID,"+
		"DISTRICT_NAME,TEHSIL_NAME,WARD_PATWARI_NAME,MOHALLA_VILLAGE_NAME,"+
		"OFFICE_TYPE_NAME FROM IGRS_OFFICE_MASTER left outer join IGRS_DISTRICT_MASTER on IGRS_OFFICE_MASTER.DISTRICT_ID = IGRS_DISTRICT_MASTER.DISTRICT_ID left outer join IGRS_TEHSIL_MASTER on IGRS_OFFICE_MASTER.TEHSIL_ID = IGRS_TEHSIL_MASTER.TEHSIL_ID "+
		"left outer join IGRS_WARD_PATWARI_MASTER on IGRS_OFFICE_MASTER.WARD_ID = IGRS_WARD_PATWARI_MASTER.WARD_PATWARI_ID left outer join IGRS_MOHALLA_VILLAGE_MASTER on IGRS_OFFICE_MASTER.MOHALLA_VILLAGE_ID = IGRS_MOHALLA_VILLAGE_MASTER.MOHALLA_VILLAGE_ID left outer join IGRS_OFFICE_TYPE_MASTER on IGRS_OFFICE_MASTER.OFFICE_TYPE_ID = IGRS_OFFICE_TYPE_MASTER.OFFICE_TYPE_ID  WHERE OFFICE_ID = ? and OFFICE_STATUS <> 'R'";
		
		public static final String SELECT_OFFICE_MASTER_NAME = "SELECT OFFICE_ID FROM IGRS_OFFICE_MASTER WHERE OFFICE_NAME = ?";
		
		public static final String SELECT_OFFICE_TYPE = "SELECT OFFICE_TYPE_ID,OFFICE_TYPE_NAME FROM IGRS_OFFICE_TYPE_MASTER WHERE OFFICE_TYPE_STATUS <> 'R'";
	
		public static final String DELETE_OFFICE_MASTER = "UPDATE IGRS_OFFICE_MASTER SET OFFICE_STATUS = 'R' WHERE OFFICE_ID = ?";
}
