package com.wipro.igrs.rti.constants;

public class Constants {
    public static final String IGRS_RTI_INFO = 
        "SELECT COUNT(*) FROM IGRS_RTI_INFO WHERE TRUNC(REQUEST_DATE) BETWEEN TO_CHAR(TO_DATE('";
    public static final String SET_DRO_NAME = 
        "UPDATE IGRS_RTI_INFO SET DRO_NAME='";
    public static final String RESOLUTION_INFO = 
        "UPDATE IGRS_RTI_INFO SET RESOLUTION_INFO=? , RESOLUTION_REMARK =? WHERE RTI_ID=?";
    public static final String RTI_STATUS = 
        "SELECT RTI_ID,FIRST_NAME,MID_NAME,LAST_NAME,GENDER,AGE,FATHER_NAME,MOTHER_NAME,SPOUSE_NAME,ADDRESS,CITY,COUNTRY,STATE,PIN,PHONE,MOBILE,EMAIL,IDPROOFNO,REQUEST_INFO,RESOLUTION_INFO,RESOLUTION_REMARK,RTI_STATUS,DRO_NAME,DR_NAME,TO_CHAR(REQUEST_DATE,'DD/MM/YYYY'),TO_CHAR(RESOLUTION_DATE,'DD/MM/YYYY') FROM IGRS_RTI_INFO WHERE RTI_ID= ? AND RTI_STATUS=? "; //AND  TRUNC(REQUEST_DATE) BETWEEN ? ";
    //public static final String RTI_ID="SELECT RTI_ID,FIRST_NAME,MID_NAME FROM IGRS_RTI_INFO WHERE RTI_ID=?"; 

    public static final String INSERT_VALUES = 
        "INSERT INTO IGRS_RTI_INFO (RTI_ID, FIRST_NAME,MID_NAME,LAST_NAME,GENDER,AGE,FATHER_NAME,MOTHER_NAME,SPOUSE_NAME,ADDRESS,CITY,COUNTRY,STATE,PIN,PHONE,MOBILE,EMAIL,IDPROOFNO,REQUEST_INFO,REQUEST_DATE,RTI_STATUS)"; //VALUES";//(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,sysdate,?)";

    //  "INSERT INTO IGRS_RTI_INFO (RTI_ID, FIRST_NAME,MID_NAME,LAST_NAME,GENDER,AGE,FATHER_NAME,MOTHER_NAME,SPOUSE_NAME,ADDRESS,CITY,COUNTRY,STATE,PIN,PHONE,MOBILE,EMAIL,IDPROOFNO,REQUEST_INFO,REQUEST_DATE,RTI_STATUS)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,sysdate,?)";

    public static final String EMAIL_SERVICE_ID ="SER_002";
    public static final String SMS_SERVICE_ID ="SER_001"; 
    public static final String POST_SERVICE_ID ="SER_003"; 
    public static final String OTHERS_SERVICE_ID ="SER_004";
}
