/**
 * ===========================================================================
 * File           :   CommonSQL.java
 * Description    :   Represents the SQL Class

 * Author         :   Nithya
 * Created Date   :   Jan 08, 2008

 * Updated By	  :   Imran Shaik
 * Updated Data	  :   Oct 21,2008
 * 
 * ===========================================================================
 */

package com.wipro.igrs.intimationtransaction.sql;

public class CommonSQL {

    //For Payment Validation
    public static final String INTIMATION_CHALLAN_PAYMENT_VALIDATE = 
    "SELECT TRANSACTION_ID,CHALLAN_ONLINE_NUMBER,CHALLAN_ONLINE_DATE,NET_AMOUNT,BANK_NAME FROM IGRS_PAYMENT_MODE_DETAILS ";

    // To get Fee 
    public static final String SERVICE_FEE_QUERY = 
    "SELECT PARAM_VALUE FROM IGRS_SERVICE_FEE_PARAM_MAPPING WHERE FUNCTION_ID ='FUN_036' AND PARAM_ID ='1'";

    //To get Other Fee   
    public static final String SERVICE_OTHER_FEE_QUERY = 
    "SELECT PARAM_VALUE FROM IGRS_SERVICE_FEE_PARAM_MAPPING WHERE FUNCTION_ID ='FUN_036' AND PARAM_ID ='2'";
    
    //To insert payment details into IGRS_TXN_INTIMN_PAYMENT_DTLS
    public static final String INTIMATION_TXN_PAYMENT_SUBMIT =
    "INSERT INTO IGRS_TXN_INTIMN_PAYMENT_DTLS(TXN_INTMN_PAYMENT_ID," +
    "INTIMATION_TXN_ID,FUNCTION_ID,PAYABLE_AMOUNT,PAYMENT_FLAG," +
    "CREATED_BY,CREATED_DATE)" +
    "VALUES(?,?,?,?,?,?,SYSDATE)";  
    
    public static final String INTIMATION_TXN_PAYMENT_SUBMIT1 = 
    		"SELECT WT.INTIMATION_TXN_ID, NVL(WP.PAID_AMOUNT,'0'), (NVL(WP.PAYABLE_AMOUNT,'0')-NVL(WP.PAID_AMOUNT,'0')) DUE_AMOUNT, WP.UPDATE_DATE,TO_CHAR((WT.CREATED_DATE),'dd/mm/yyyy') CREATED_DATE,WP.PAYABLE_AMOUNT FROM IGRS_TXN_INTIMN_PAYMENT_DTLS WT, (SELECT IGRS_TXN_INTIMN_PAYMENT_DTLS.INTIMATION_TXN_ID,SUM(IGRS_TXN_INTIMN_PAYMENT_DTLS.PAID_AMOUNT) PAID_AMOUNT, MAX(IGRS_TXN_INTIMN_PAYMENT_DTLS.PAYABLE_AMOUNT) PAYABLE_AMOUNT,TO_CHAR(MAX(IGRS_TXN_INTIMN_PAYMENT_DTLS.UPDATE_DATE), 'dd/mm/yyyy') UPDATE_DATE FROM IGRS_TXN_INTIMN_PAYMENT_DTLS where IGRS_TXN_INTIMN_PAYMENT_DTLS.PAYMENT_FLAG !='C' GROUP BY IGRS_TXN_INTIMN_PAYMENT_DTLS.INTIMATION_TXN_ID ) WP WHERE WP.INTIMATION_TXN_ID = WT.INTIMATION_TXN_ID ORDER BY WT.INTIMATION_TXN_ID";
    		 
    		    
    public static final String PRESENT_PAYMENT_ENTRY =		   
    		"SELECT PAYMENT_FLAG,TXN_INTMN_PAYMENT_ID FROM IGRS_TXN_INTIMN_PAYMENT_DTLS WHERE TXN_INTMN_PAYMENT_ID=(SELECT MAX(TXN_INTMN_PAYMENT_ID) FROM IGRS_TXN_INTIMN_PAYMENT_DTLS WHERE INTIMATION_TXN_ID=?)";   
    		  
    		 
    public static final String PENDING_BALANCE_DETAILS="SELECT DISTINCT (TO_NUMBER(WP.PAYABLE_AMOUNT)-nvl((WP.PAID_AMOUNT),'0'))DUE_AMOUNT "+

          " FROM IGRS_INTIMN_TXN_INFO WT,(SELECT IGRS_TXN_INTIMN_PAYMENT_DTLS.INTIMATION_TXN_ID,SUM(IGRS_TXN_INTIMN_PAYMENT_DTLS.PAID_AMOUNT) PAID_AMOUNT,MAX(IGRS_TXN_INTIMN_PAYMENT_DTLS.PAYABLE_AMOUNT) PAYABLE_AMOUNT,TO_CHAR(MAX(IGRS_TXN_INTIMN_PAYMENT_DTLS.UPDATE_DATE), 'dd/mm/yyyy') UPDATE_DATE"+  

          " FROM IGRS_TXN_INTIMN_PAYMENT_DTLS GROUP BY IGRS_TXN_INTIMN_PAYMENT_DTLS.INTIMATION_TXN_ID) WP WHERE WP.INTIMATION_TXN_ID = WT.INTIMATION_TXN_ID AND WT.INTIMATION_TXN_ID=?";
		
    public static final String PYMNT_UPDATE = "UPDATE IGRS_TXN_INTIMN_PAYMENT_DTLS SET PAYMENT_FLAG=? WHERE " +

                        " INTIMATION_TXN_ID =? ";		

		
    
    public static final String GET_COUNTRY="select country_name from igrs_country_master where country_id=?";
    public static final String GET_COUNTRY_HI="select h_country_name from igrs_country_master where country_id=?";
    public static final String GET_STATE="select state_name from igrs_state_master where state_id=?";
    public static final String GET_STATE_HI="select h_state_name from igrs_state_master where state_id=?";
	public static final String GET_DISTRICT="select district_name from igrs_district_master where district_id=?";
	public static final String GET_PHOTOID_TYPE_NAME="SELECT PHOTO_PROOF_TYPE_NAME FROM IGRS_PHOTOID_PROOF_TYPE_MASTER WHERE PHOTO_PROOF_TYPE_ID=?";
	public static final String GET_DISTRICT_HI="select h_district_name from igrs_district_master where district_id=?";
	public static final String GET_PHOTOID_TYPE_NAME_HI="SELECT H_PHOTO_PROOF_TYPE_NAME FROM IGRS_PHOTOID_PROOF_TYPE_MASTER WHERE PHOTO_PROOF_TYPE_ID=?";
	
	//To update after modify in view
	 public static final String INTIMATION_TXN_UPDATE ="UPDATE IGRS_INTIMN_TXN_DETAILS SET INTIMATION_TYPE_ID=?,INTIMATION_TYPE_VALUE=?  WHERE INTIMATION_TXN_ID=? AND INTIMATION_TYPE_ID=?";
	
	
	
    //To insert Intimn Req Form details into  IGRS_INTIMN_TXN_PARTY_DETAILS 
    public static final String INTIMATION_TXN_INFO_SUBMIT1 = 
    "INSERT INTO IGRS_INTIMN_TXN_INFO(INTIMATION_TXN_ID,FUNCTION_ID, " + 
    "PARTY_FIRST_NAME,PARTY_MIDDLE_NAME,PARTY_LAST_NAME,PARTY_GENDER,PARTY_AGE,NATIONALITY," + 
    "COUNTRY_ID,STATE_ID,DISTRICT_ID,PARTY_ADDRESS,POSTAL_CODE,PHONE_NUMBER, " +
    "MOBILE_NUMBER,EMAIL_ID,PHOTO_PROOF_TYPE_ID,PHOTO_PROOF_ID,GUARDIAN_NAME, " + 
    "MOTHER_NAME,PARTY_THUMB_IMPRESSION,PARTY_PHOTO,PARTY_SIGNATURE," +
    "UPDATE_BY,UPDATE_DATE,CREATED_BY,CREATED_DATE,VOLUME_NO,BOOK_NUM, " +
    "REG_NUM,INTIMATION_START_DATE,INTIMATION_END_DATE,INTIMATION_TYPE_ID,"+
    "INTIMATION_TYPE_VALUE,TOTAL,OTHERS,FEE,FLAG)"+
    "VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,SYSDATE,?,SYSDATE,?,?,?,?,?,?,?,?,?,?,?) ";   

    //To insert Intimn Req Form details into  IGRS_INTIMATION_TXN_DETAILS 
    public static final String INTIMATION_TXN_INFO_SUBMIT2 = 
    "INSERT INTO IGRS_INTIMATION_TXN_DETAILS(TRANSACTION_ID,REGISTRATION_ID, " + 
    "INTIMATION_REQ_TYPE,FUNCTION_ID,CREATED_BY,CREATED_DATE,UPDATE_BY, " + 
    "UPDATE_DATE,INTIMATION_STATUS,REGISTRATION_DATE,INTIMATION_START_DATE, " +
    "INTIMATION_END_DATE,PAYMENT_TXN_ID) " +
    "VALUES(?,?,?,?,?,SYSDATE,?,?,?,?,?,?,?) ";  

    //To insert Intimn Req Form details into  IGRS_INTIMATION_TXN_MAPPING    
    public static final String INTIMATION_TXN_INFO_SUBMIT3 = 
    "INSERT INTO IGRS_INTIMATION_TXN_MAPPING(TRANSACTION_ID,INTIMATION_TYPE_ID, " + 
    "INTIMATION_TYPE_VALUE)" +
    "VALUES(?,?,?) ";     
 
    public static final String INTIMATION_TXN_INFO_SUBMIT6 =
    		"SELECT IGRS_TXN_INTIMN_PAYMENT_SEQ.NEXTVAL FROM DUAL";
    
    public static final String INTIMATION_TXN_INFO_SUBMIT5 =
    		"SELECT IGRS_TXN_INTIMN_DETAIL_SEQ.NEXTVAL FROM DUAL";
    
    
    //To insert Intimn Req Form details into  IGRS_INTIMATION_REQ_TYPE_MAP 
    public static final String INTIMATION_TXN_INFO_SUBMIT4 = 
    "INSERT INTO IGRS_INTIMN_TXN_DETAILS(TXN_INTIMN_DETAIL_ID,INTIMATION_TXN_ID,INTIMATION_TYPE_ID, " + 
    "UPDATE_BY,UPDATE_DATE,CREATED_BY,CREATED_DATE,INTIMATION_TYPE_VALUE)" +
    "VALUES(?,?,?,?,SYSDATE,?,SYSDATE,?) "; 

    //To get from IGRS_INTIMATION_TXN_DETAILS  for VIEW    
    public static final String INTIMATION_VIEW_QUERY = 
    "SELECT TRANSACTION_ID,TO_CHAR(CREATED_DATE),REGISTRATION_ID,INTIMATION_STATUS FROM IGRS_INTIMATION_TXN_DETAILS WHERE";

    //To get from IGRS_INTIMATION_TXN_PARTY_DETAILS and IGRS_INTIMATION_TXN_DETAILS for VIEW  
    public static final String INTIMATION_DETAILS_GET_QUERY1 = 
    "SELECT A.INTIMATION_TXN_ID,A.PARTY_FIRST_NAME,A.PARTY_MIDDLE_NAME,A.PARTY_LAST_NAME,"+
    "A.PARTY_GENDER,A.PARTY_AGE,A.GUARDIAN_NAME,A.MOTHER_NAME,A.PARTY_ADDRESS,A.COUNTRY_ID,A.STATE_ID,"+
    "A.DISTRICT_ID,A.POSTAL_CODE,A.PHONE_NUMBER,A.MOBILE_NUMBER,A.EMAIL_ID,"+
    "A.PHOTO_PROOF_TYPE_ID,A.PHOTO_PROOF_ID,A.BANK_NAME,A.BANK_ADDRESS,B.INTIMATION_START_DATE, " + 
    "B.INTIMATION_END_DATE,B.REGISTRATION_ID,B.FUNCTION_ID,B.INTIMATION_STATUS,B.CREATED_DATE FROM IGRS_INTIMN_TXN_PARTY_DETAILS A ,IGRS_INTIMATION_TXN_DETAILS B WHERE A.INTIMATION_TXN_ID =? AND B.TRANSACTION_ID =?";  

    public static final String INTIMATION_REQ_DETAILS_GET_QUERY1 = 
    		"SELECT A.INTIMATION_TXN_ID,A.PARTY_FIRST_NAME,A.PARTY_MIDDLE_NAME,A.PARTY_LAST_NAME,"+
    			    "A.PARTY_GENDER,A.PARTY_AGE,A.COUNTRY_ID,A.STATE_ID,A.DISTRICT_ID,A.PARTY_ADDRESS,A.POSTAL_CODE,"+
    			    "A.PHONE_NUMBER,A.MOBILE_NUMBER,A.EMAIL_ID,"+
    			    "A.PHOTO_PROOF_TYPE_ID,A.PHOTO_PROOF_ID,A.GUARDIAN_NAME,A.MOTHER_NAME,A.INTIMATION_START_DATE, " + 
    			    "A.INTIMATION_END_DATE,A.FEE FROM IGRS_INTIMN_TXN_INFO A WHERE A.INTIMATION_TXN_ID =?";  

    public static final String INTIMATION_REQ_DETAILS_GET_QUERY2 = 
    		"SELECT INTIMATION_TYPE_ID,INTIMATION_TYPE_VALUE  FROM IGRS_INTIMN_TXN_DETAILS  WHERE INTIMATION_TXN_ID =?";
    
    //To get from IGRS_INTIMATION_TXN_MAPPING for VIEW  
    public static final String INTIMATION_DETAILS_GET_QUERY3 = 
    "SELECT INTIMATION_TYPE_ID,INTIMATION_TYPE_VALUE FROM IGRS_INTIMATION_TXN_MAPPING WHERE TRANSACTION_ID =?";

    //To get from IGRS_INTIMATION_REQ_TYPE_MAP for VIEW
    //updated from function id to function name
    public static final String INTIMATION_DETAILS_GET_QUERY2 = 
    //"SELECT REQ_TYPE_FN_ID FROM IGRS_INTIMATION_REQ_TYPE_MAP WHERE TRANSACTION_ID =?";
	"SELECT FUNCTION_NAME FROM IGRS_FUNCTION_MASTER,IGRS_INTIMATION_REQ_TYPE_MAP WHERE REQ_TYPE_FN_ID=FUNCTION_ID AND TRANSACTION_ID =?";
   
    /*public static final String INTIMATION_FEE_QUERY = " SELECT IMAP.FUNCTION_ID,IMAP.PARAM_VALUE,IMAS.PARAM_NAME" +
	" FROM IGRS_SERVICE_FEE_PARAM_MAPPING IMAP,IGRS_SERVICE_FEE_PARAM_MASTER IMAS" +
	" WHERE PARENT_ID IS NULL  AND IMAS.PARAM_ID = IMAP.PARAM_ID AND FUNCTION_ID=?";*/
	
    public static final String INTIMATION_FEE_QUERY = "select FEE_RU from IGRS_FUNCTION_SERVICE_MAPPING where FUNCTION_ID=?";
    
    public static final String INTIMATION_SEARCH_QUERY = "SELECT INTIMATION_TXN_ID,TO_CHAR(CREATED_DATE,'dd/mm/yyyy') FROM IGRS_INTIMN_TXN_INFO WHERE INTIMATION_TXN_ID=?";
    
    //FOR GEETTING LIST OF FUNTIONS TO INTIMATE
    public static final String FUNTIONS_LIST = "SELECT FUNCTION_ID,FUNCTION_NAME,FUNCTION_NAME_H FROM IGRS_FUNCTION_MASTER WHERE INTIMATION_FLAG='Y'";
    
    
    
    public static final String INTIMATION_DELETE_QUERY = "DELETE FROM IGRS_INTIMN_TXN_INFO WHERE INTIMATION_TXN_ID=?";
    
    public static final String INTIMATION_DELETE_QUERY1 = "DELETE FROM IGRS_INTIMN_TXN_DETAILS WHERE INTIMATION_TXN_ID=?";
    
    public static final String INTIMATION_TOTALFEE_QUERY ="SELECT TOTAL FROM IGRS_INTIMN_TXN_INFO WHERE INTIMATION_TXN_ID=?";
    
    public static final String GET_OFFICE_DETAILS="select a.office_id , a.office_name, a.district_id, b.district_name from igrs_office_master a, igrs_district_master b where a.district_id=b.district_id and a.office_id=?";

    public static final String GET_USER_DETAILS="select a.district_id, b.district_name from igrs_sp_detls a, igrs_district_master b where a.district_id=b.district_id and applctn_status=8 and a.created_by=?";

    public static final String CHECK_ENTRY="Select * from IGRS_INTIMN_TXN_DETAILS where INTIMATION_TXN_ID=? AND INTIMATION_TYPE_ID=?";
    public static final String INSERT_ENTRY="Insert into IGRS_INTIMN_TXN_DETAILS(TXN_INTIMN_DETAIL_ID,INTIMATION_TXN_ID,INTIMATION_TYPE_ID,INTIMATION_TYPE_VALUE,CREATED_BY,CREATED_DATE) values(?,?,?,?,?,sysdate) ";
    public static final String DELETE_ENTRY="delete from IGRS_INTIMN_TXN_DETAILS where INTIMATION_TXN_ID=? AND INTIMATION_TYPE_ID=?";

}     